### ISSUE TITLE
MapOptions.tileMaterial change doesnt effect map

### ISSUE THREAD

**Issue by m3rt32** [mapbox/mapbox-unity-sdk#1003]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1
* Mapbox SDK version: 1.4.5
* The platform you're building to: IOS&Android
* A description of what you're trying to do: Assigning Tile Material in runtime & changing map material in runtime

We are trying to use custom styles in runtime, but after map initialization we can change parameters such as mapstyle, vectordata(like extruded building materials and color). Style change happens as follows:

>  GetActive Tiles->Add to list-> Dispose Tiles->Apply styles to abstract map->Load tiles via map visualizer.

 But once we try to change the tile material as follows, `_map.Options.tileMaterial = ExampleMaterial;` inspector data changes but those changes never assigned to tiles, they are still using the default material instance.(Not just only cached tiles, but also newly instantiated tiles) Is there a way to apply those changes ? We've tried to use `_map.UpdateMap();` method but it didnt worked.

**Comment by brnkhy** [comment]
@m3rt32 we don't have automatically update map on settings change at the moment (but it's coming). One thing you can do is to change material of all existing tiles yourself. 
You can get all active tiles from `AbstractMap.MapVisualizer.ActiveTiles` dictionary, then change their material with something like `UnityTile.MeshRenderer.mater = value`. This would change materials for all existing tiles.
But if you want to change material used for new tiles as well, you should use `AbstractMap.MapVisualizer.SetTileMaterial(material)` function. This should change the setting and it will be applied to all new tiles created.
Only issue at this point (depending on your use case) would be tiles that exists but inactive/cached for recycling. They are kept in a Queue called `_inactiveTiles` under MapVisualizer. It's protected but you can create a public get method to find and change those as well. Again, depending on your use case, it might not even be necessary.

Let me know if thsoe doesn't solve the issue.

**Comment by m3rt32** [comment]
ActiveTiles solution solved my issue. Because of all tiles were active in the beginning, _inactiveTiles property wasnt necessary. Thank you!
