### ISSUE TITLE
Cannot get build for Android versions smaller than 24.

### ISSUE THREAD

**Issue by ufktvfk** [mapbox/mapbox-unity-sdk#1007]
Hi, for this issue: https://github.com/mapbox/mapbox-unity-sdk/issues/982#issue-353719360

I tried to:

1.Uncheck Android in the inspector for
Assets/Mapbox/Unity/Location/Plugins/Android/com.mapbox.android.unity-debug

2.Delete whole folder:
Assets/Mapbox/Unity/Location/Plugins/Android/

This suggestions caused that map is not shown in my app. I mean map is not even initalized.

But I found a workaround  but not sure it is correct or suggested way. I basically edited AndroidManifest file for mapbox unity sdk.
![mapbox package](https://user-images.githubusercontent.com/23186662/45343465-a8bf2600-b5a9-11e8-9813-fcc79f3f4e80.JPG)

After I did this, I successfully got build for API level 19 which is below 24. It worked fine in the phone.

But is this method can be trusted or is this a hack?  It will not use methods that is introduced with API level 24 right ?

**Comment by jordy-isaac** [comment]
@ufktvfk I was able to get this to build, but you're correct about the methods for lvl 24. It's still a useful workaround and thanks for sharing!
