### ISSUE TITLE
Getting Coordinates from the json.

### ISSUE THREAD

**Issue by Dreadedmonkey** [mapbox/mapbox-unity-sdk#1008]
Hello, 

I have made a custom tileset with a custom dataset, added it to the map. I have used "IFeaturePropertySettable" to get the properties, such as title and description that are from the json, of the prefab that I have placed. Now I am wondering how to get the Geometry of the prefab, mainly the Coordinates, that are contained within the json file ? 

I just want to do this so I can check if the player is close enough to the spawned prefab so they can interact or make the prefab visible.

Sorry for the simple question.

**Comment by Dreadedmonkey** [comment]
Thanks for much for your help. I was also thinking that the performance might be affected, so I just added a  flat square to the bottom of the spawnable prefab and check if the place is inside that. 

However, for future reference, would it be possible to share the code to get the Str value that you have shown in your picture ?  Other than that I dont have an issue, and this can be closed.

**Comment by jordy-isaac** [comment]
I don't believe that it was retrieved by a script in this case, it was explicitly specified. Please keep us updated on your project and check out the [dev program](https://www.mapbox.com/unity-developer-program/) if you haven't already.
