### ISSUE TITLE
map show problem in the zoomable map case

### ISSUE THREAD

**Issue by IfnoLee** [mapbox/mapbox-unity-sdk#1013]
* Unity version: 2017.4.1f1
  * Scripting Runtime Version: .Net4.6
  * Scripting Backend: Mono
  * Api Compatibility Level: .Net4.6
* Mapbox SDK version: 1.4.3/1.4.4/1.4.5
* The platform you're building to:PC
* A description of what you're trying to do:just look but important
* Steps to recreate the bug if appropriate:the place near by Kunming Changshui Airport in china，show some layer
* Links to your logs are also helpful: NONE
mapbox style URL:  the default map satellite street style in zoomable Map 
![Uploading Snipaste_2018-09-14_15-42-13.PNG…]()
![snipaste_2018-09-14_15-42-32](https://user-images.githubusercontent.com/38685433/45537198-27c88e80-b836-11e8-8cdb-6f23d197e03c.PNG)
![snipaste_2018-09-14_16-08-56](https://user-images.githubusercontent.com/38685433/45538284-382e3880-b839-11e8-98d0-8e9267b21986.PNG)

**Comment by jordy-isaac** [comment]
@IfnoLee I wasn't quite able to reproduce this. Can you let us know the coordinates and zoom level?

**Comment by IfnoLee** [comment]
![snipaste_2018-09-17_10-26-35](https://user-images.githubusercontent.com/38685433/45604163-51ff9380-ba64-11e8-99da-9224347d1b29.PNG)

**Comment by IfnoLee** [comment]
@jordy-isaac

**Comment by jordy-isaac** [comment]
This looks like it could be an issue with the satellite imagery for that area and zoom level. We've flagged the data team on it to check it out, but don't have an eta on when it could be fixed. If you have your own imagery that is better for your use case, it can be used with Mapbox. Here's more info: https://www.mapbox.com/help/how-satellite-imagery-works/#uploading-satellite-imagery
