### ISSUE TITLE
Globe Mode

### ISSUE THREAD

**Issue by IfnoLee** [mapbox/mapbox-unity-sdk#1014]
Hope make a Globe Mode in Unity 3D，like google map, then Greenland's projection is no longer the size of Africa。I consider this is important。**The Globe in Mapbox SDK for Unity3D  but not use now**。

![image](https://user-images.githubusercontent.com/38685433/45743894-ae62de80-bc2f-11e8-9187-b7c390e4801a.png)

**Comment by IfnoLee** [comment]
@atripathi-mb

**Comment by jordy-isaac** [comment]
@IfnoLee There's a globe example in the SDK. Have you had a look at that yet? Can you provide more details on the projection issue?

**Comment by IfnoLee** [comment]
> @IfnoLee There's a globe example in the SDK. Have you had a look at that yet? Can you provide more details on the projection issue?

 I looked the Globe Demo in Mapbox SDK for Unity，but it cannot zoom in / out .

**Comment by IfnoLee** [comment]
@jordy-isaac

**Comment by jordy-isaac** [comment]
The example scene for the globe does not zoom. However, you could implement zooming on your own, Have a look at the [zoomable map example](https://www.mapbox.com/unity-sdk/maps/examples/zoomable-map/) to see how you can approach the implementation.
