### ISSUE TITLE
Question: How can I add a custom building?

### ISSUE THREAD

**Issue by AzeExMachina** [mapbox/mapbox-unity-sdk#1016]
Hi everyone, following the example for the replace feature posted [here](https://www.mapbox.com/unity-sdk/maps/examples/replace-features/)  I was able to replicate the described behaviour on my implementation of a map. Trying with the coordinates for the Empire State Building works perfectly. Then I tried to replace "Arena di Verona" in Italy with the same building prefab but to no avail, am I missing something? Reading the description of the example: 

> This example demonstrates how you can use the ReplaceFeatureModifier to swap out a default extruded building with a custom 3D object. With this modifier, you can replace your corporate office locations with a branded building model, or spawn a highly detailed 3D object in place of a famous monument or building.

I saw that I could replace even a corporate office. Am I missing something? Do I need something else, like a custom map id that already has data on the buildings I want to then customize?

Thanks in advance!

* Unity version: 2018.1.5f
* Mapbox SDK version: 1.4.5

**Comment by AzeExMachina** [comment]
I found out how to solve this issue, as I thought I had to create a custom dataset and add a polyline in the place of my building to then being able to replace it with a custom modifier. I'm closing this issue.

**Comment by Zouron** [comment]
@AzeExMachina I know its been a while, but can i ask how you came to this solution. I was able to load my modifier after folwwing your steps, but there is no indication of this in any of the documentation.
