### ISSUE TITLE
Access open street map features informations

### ISSUE THREAD

**Issue by bourgeoismaxime** [mapbox/mapbox-unity-sdk#1019]
Hello,
I'm using Mapbox 1.4.5 on Unity 2018.2.8f1 on the Editor (for now).
In the past, I was able to find all the details about the map (get the roads names, get the features types ...) but I cannot find how anymore. Ultimately my goal is to be able to know what is around (names of the roads, how many parks, where is the closest fast food, ...). Is there a way to know that kind of stuff using the Unity SDK ?

Thanks, Max

Edit : Or is there a way to link the "Map features" section with the "Point of interest" one ?

**Comment by jordy-isaac** [comment]
Hi @bourgeoismaxime. All of this data is available to you. I would check out the [City Simulator](https://www.mapbox.com/unity-sdk/maps/examples/city-simulator/), [Data Explorer](https://www.mapbox.com/unity-sdk/maps/examples/data-explorer/), and the [POI Placement](https://www.mapbox.com/unity-sdk/maps/examples/poi-placement/) examples (POIs have a [video tutorial](https://www.mapbox.com/unity-sdk/maps/examples/poi-placement/#create-a-custom-scene-with-pois)). 

Take a look at how the (Map Features)[https://www.mapbox.com/unity-sdk/maps/overview/map-features/] are configured. These examples will show you how to set it up using the SDK. For information on the layers used, check out the documentation for the tileset [layer reference](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#layer-reference).

**Comment by bourgeoismaxime** [comment]
Thanks for the information. Is there a way to access all these datas by script using a specific position (lat,lon) and a range ? The aim is to know what's near a specific position without always storing the datas using the Map features section.
