### ISSUE TITLE
Adding Swiftype meta tags

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-unity-sdk#102]
Right now the Mapbox Unity SDK documentation doesn't provide useful metadata to Swiftype to help guide our search results. For example:

![image](https://cloud.githubusercontent.com/assets/2180540/26605870/b59e6bdc-455d-11e7-8f64-f3cfe8617e7d.png)

We should add Swiftype meta tags to improve our search results and give us more flexibility in displaying and styling results. This is especially important for the /help redesign.

I'm unfamiliar with how this site is built @david-rhodes, would you mind helping me add a couple meta tags to the template? 🙏 

```html
<!-- name of the subsite (this value remains constant throughout this subsite) -->
<meta class='swiftype' name='type' data-type='enum' content='Mapbox SDK for Unity' /> 
<!-- title of current page (this value changes for each page) -->
<meta class='swiftype' name='title' data-type='string' content='Getting Started' /> 
```

There is also an excerpt tag that you can add, but I understand if this data is not easily accessible. So if it's a pain, then we don't need to add this meta tag:

```html
<!-- excerpt of current content on the page, truncated to around 30 words (this value changes for each page) -->
<!-- Example: -->
<meta class='swiftype' name='excerpt' data-type='string' content='Build anything with Mapbox.js v3.1.1, a library for fast &amp; interactive maps.' /> 
````

**Comment by david-rhodes** [comment]
@katydecorah Apologies, but I don't really understand the template, either. However, we're currently in the process of overhauling documentation (built with Jekyll?) anyway, so I wonder how relevant this is. 

/cc @isiyu @danswick

**Comment by katydecorah** [comment]
> However, we're currently in the process of overhauling documentation (built with Jekyll?) anyway

Good to know! We can move forward with this in the overhaul

**Comment by MiroMuse** [comment]
@david-rhodes @katydecorah hey team! I'm currently grooming our backlog - if this issue is resolved, can you please close? Thanks!
