### ISSUE TITLE
Map Editor NullReferenceException

### ISSUE THREAD

**Issue by saintsalo** [mapbox/mapbox-unity-sdk#1020]
I was just starting off with the mapbox unity sdk, and am running into an issue with the Map Editor. I just installed the mapbox-unity-sdk and started the Location-basedGame example, which seems to be running okay (It loads the map and shows the player moving). But when I open Map Editor there's nothing showing, and I notice several errors in the console all pertaining to NullReferenceException:

> NullReferenceException: Object reference not set to an instance of an object
> Mapbox.Editor.NodeEditor.GUIScaleUtility.BeginScale (UnityEngine.Rect& rect, Vector2 zoomPivot, Single zoom, Boolean adjustGUILayout) (at Assets/Mapbox/Unity/Editor/NodeEditor/EditorZoomArea.cs:137)
> Mapbox.Editor.NodeEditor.NodeBasedEditor.OnGUI () (at Assets/Mapbox/Unity/Editor/NodeEditor/NodeBasedEditor.cs:160)
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
> UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
> UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
> UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)

I'm using windows 10 with Unity 2018.2.0f2 Personal (64bit). 
I just downloaded the Unity SDK today (v1.4.5)

I'm not sure if there's something I'm missing, or if this is an actual issue. Thanks for the help!

**Comment by atripathi-mb** [comment]
@saintsalo Unity changed the topmostRect internal causing this issue. Here is a PR fixing it. Will be available in the SDK with our next release. https://github.com/mapbox/mapbox-unity-sdk/pull/980

**Comment by saintsalo** [comment]
@atripathi-mb great! Thanks for the info.

**Comment by saintsalo** [comment]
i just replaced mapbox-unity-sdk/sdkproject/Assets/Mapbox/Unity/Editor/NodeEditor/EditorZoomArea.cs with latest in dev branch and works fine. Thanks.
