### ISSUE TITLE
Add prefab to Tabletop AR example

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#1025]
Hi,

I want to add a 3D model of a building to the table top AR example on Mapbox. I'm using spawnonmap.cs script to put building on a latlong but the 3D model does not align well and is not placed on the table plane.
How do I solve this?

Regards,
Tarak Shah.

**Comment by jordy-isaac** [comment]
@tarakinsuide Is it a building that's not available in the building data? [Buildings](https://www.mapbox.com/unity-sdk/maps/overview/map-features/#buildings) are already configured on the [Tabletop example](https://www.mapbox.com/unity-sdk/maps/examples/tabletop-ar/). Can you let us know a bit more about your use case and include some screenshots of how the object is not aligned as you'd expect?
