### ISSUE TITLE
Accessing Dataset Properties via script

### ISSUE THREAD

**Issue by AzeExMachina** [mapbox/mapbox-unity-sdk#1029]
Greetings everyone, I have a problem in trying to retrieve tilesets data at runtime.

I have a custom tileset I'm using on my AbstractMap in Unity, I've added a Map Feature I'm using to visualize some modified prefabs on buildings. 
What I wanted to know however is how to access the following properties from my tilesets. I've seen that I can filter on those keys in the inspector. So how can I access those?
![image](https://user-images.githubusercontent.com/28900356/46157262-9ddbe500-c27b-11e8-8469-fbd90a900cd9.png)

Thanks in advance!

**Comment by jordy-isaac** [comment]
@AzeExMachina Currently, the best way to access these keys is via the inspector. We're looking into public APIs for these and are working on APIs for the rest of the AbstractMap as well for devs who want to do this via script.

**Comment by Sailendrakc** [comment]
Hello,
 any updates on this? I have a polygon dataset with some property (key-value), exported it to tileset, and styled it as a new layer in a new basic style.  When I publish and use that style in Unity3d, the polygon is inscribed in the map and there is nothing more to do about it. How can I get the position of such datasets and how to get properties associated with them?
