### ISSUE TITLE
Unity - Mapbox Custom Name's places

### ISSUE THREAD

**Issue by ivermc** [mapbox/mapbox-unity-sdk#1039]
Hi everyone, i'm developing a proyect with custom places, this have id, names, numbers, and other data. All this information is in the custom dataset of the map, this places shows in the map, but i want extract this information in Unity for show each name of the points of interest created. 

![imagen](https://user-images.githubusercontent.com/43762212/46311212-6fb61800-c58f-11e8-8bc2-f9ab72593401.png)

Here is a way i found to show name's places but the Map Id is locked, is there a way to change this Map ID? or another way to do some similar like this?

Forgive me, my Unity knowledge is very limited. I just started using Unity with the mapbox-sdk.

**Comment by jordy-isaac** [comment]
@ivermc Thanks for the ticket. The [POI](https://www.mapbox.com/unity-sdk/maps/examples/poi-placement/) component on the AbstractMap is just for the Mapbox streets tileset. If you have custom POIs that you need, you'll want to [upload your data](https://www.mapbox.com/help/uploads/) to Mapbox and bring it in as [custom data](https://www.mapbox.com/unity-sdk/maps/overview/custom-maps/#use-custom-data). You can use the `FEATURES` section to bring in your data.
