### ISSUE TITLE
Unity - Mapbox show name places

### ISSUE THREAD

**Issue by ivermc** [mapbox/mapbox-unity-sdk#1042]
Hi, i'm with a proyect with mapbox, i need to show the data name of places are in a custom dataset, This information is alredy uploaded.

![imagen](https://user-images.githubusercontent.com/43762212/46359940-4a311900-c638-11e8-9d5e-b6b3691a146f.png)

And it shows in the map.

![imagen](https://user-images.githubusercontent.com/43762212/46359996-777dc700-c638-11e8-8a2a-9a450006769d.png)

i want the names show in Unity, i need use "Game Object Modifiers" or "Add Component" to do that and extract the data of field "Nombre" of the tilesets and shows in the map.

Thanks for the support.

**Comment by jordy-isaac** [comment]
@ivermc You can configure the tileset as a custom `Data Source` on the `AbstractMap.cs` script. You can find the documentation on custom data [here](https://www.mapbox.com/unity-sdk/maps/overview/custom-maps/#use-custom-data).
