### ISSUE TITLE
How to search POI from custom data set

### ISSUE THREAD

**Issue by vin67** [mapbox/mapbox-unity-sdk#1043]
I can add custom data sets using comma to seperate map ID's and add Features related to to my additional Map ID's and generate new buildings on the screen.

However, as far as i can tell, its not possible to use Points Of Interest part of the Inspector for custom Map ID's and options to "find by prefab location" is limited to the base map mapbox,mapbox-streets-v7?

![screen shot 2018-10-03 at 6 12 02 am](https://user-images.githubusercontent.com/5768363/46374137-4bfbea80-c6d3-11e8-8076-5e71d0a88b82.png)

If that is the case can someone point me in the right direction on  how I would go about creating poi's similar to "POI Placement" example but for new generated buildings that are in custom maps? Does it entail using Game Object Modifier somehow? Should I somehow be using spawnonglobe.cs as a modifier to create additional objects above the buildings I create? Appreciate the guidance on the best approach to do this.

macOS 10.13.6
Unity 2018.2.10f1
mapbox unity sdk 1.4.5

**Comment by jordy-isaac** [comment]
For custom POIs you won't able to use the Points of Interest section. This for the Mapbox tileset only.
​
​Instead, you can [upload the data to Mapbox](https://www.mapbox.com/help/uploads/), and then [bring it in to Unity](https://www.mapbox.com/unity-sdk/maps/overview/custom-maps/#use-custom-data). From there, you can set up the [features on the AbstractMap](https://www.mapbox.com/unity-sdk/maps/overview/map-features/) using your custom data source to visualize your points. You can use a PrefabModifier to specify the 3D objects you want at the given coordinates.

**Comment by vin67** [comment]
Thanks for the guidance. Thats the steer I needed. I created a new prefab modifier and added a prefab I ended up using a copy of the POI example prefabs and now modifying it and now in the process of modifying the TextLabelSetter script to present data from the custom data layer.

**Comment by hmaskat17** [comment]
Unity 2018.2.11.f1 --- Mapbox SDK 2.0.0 --- Building to Android

Hi! Sorry, i'm new to Unity and Mapbox. I have a similar issue. 

I am trying to use a custom data source to display 3d models over my map co-ordinates and display their properties information when the 3d prefabs are clicked on.

I succeeded in displaying the 3d models over the co-ordinates using a POI PrefabModifier.

I am not able to display the additional GeoJSON properties data of my custom dataset, similar to how multiple properties are shown together in the InteractiveStyledVectorMap. How is this done? I want a new panel, that shows a few of the properties data, to display when the 3d model is clicked on. Thanks.
