### ISSUE TITLE
Mapbox Features

### ISSUE THREAD

**Issue by Flameshot** [mapbox/mapbox-unity-sdk#1053]
Hello everyone and have a nice week. I need a start point for some features which I saw mapbox has but I don't find documentation for them for unity.

The first one is Highlight buildings feature ( I saw the script, I saw how to add it on buldings but it seems I didn't set something right so it doesn't work)
The second one: I'm looking to draw lines on the map, like rectengulars around the building or street or circles and somehow to save the position of drawings (this will be made using server). Any help will be appreciated
Have a nice day.

**Comment by brnkhy** [comment]
@Flameshot Highlight modifier needs mesh colliders enabled on buildings, can you please check that's set correct?
I also just realized it's only highlighting roof in realistic style though (first material), I'll try to fix that asap.

For the second question, you can try to create a custom game object modifier. You can think of GameObjectModifiers as entities that recieves features after their mesh generation has been done. In general we use them to set materials after mesh gen for example, or add colliders. 
But in you case, you can add it to building layer for example, get the incoming features, find the bounding box of the already calculated vertices and then draw your rectangle in any way you want/need.

**Comment by Flameshot** [comment]
@brnkhy hello. Ok I found that I didn't have mesh colliders enabled on buildings, now it works.

I'm still thinking of a way to make the second feature with lines. Can you please make a detailed explanation about the second question, I'm still trying to understand the logic.

**Comment by Flameshot** [comment]
Hello @jordy-isaac  @brnkhy . I started working on drawing tools using Triangle.NET framework. When I will finish all the features I will port here. You can close this ticket.

Have a nice day.

**Comment by jordy-isaac** [comment]
Thanks for closing the loop!
