### ISSUE TITLE
Errors when building for iOS

### ISSUE THREAD

**Issue by dpruitt90** [mapbox/mapbox-unity-sdk#1087]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: Unity 2018.2.12f1
* Mapbox SDK version: 1.4.5
* The platform you're building to: iOS
* A description of what you're trying to do: Build an app for iOS

1.  Build app for iOS in Unity
2.  Build opens xCode and reports successful build
3.  Attempt to build for device, and receive the following error (after receiving the error mentioned in #644 and manually updating search headers - isn't that fixed?????:

/clang:-1: linker command failed with exit code 1 (use -v to see invocation)

**Comment by atripathi-mb** [comment]
@dpruitt90 This error seems to occur with the way Unity exports xCode projects. 
If you rebuild the xCode project and chose the option `Append` , it will start working. 

The header paths are correctly appended but somehow xCode is not able to find it.

**Comment by atripathi-mb** [comment]
@dpruitt90 
> /clang linker command failed with exit code 1 (use -v to see invocation)

Are you sure this is Mapbox related error?

**Comment by dpruitt90** [comment]
@atripathi-mb 
Please disregard.  It looks like it was due to a setting in the "Target Minimum IOS Version.  When set to 9.0 we got the build errors.  Setting to 8.0 and everything worked.
