### ISSUE TITLE
Extent option Camera bound freeze unity when rotating downward around 30 degrees

### ISSUE THREAD

**Issue by Thaina** [mapbox/mapbox-unity-sdk#1090]
Using unity 2018.3 and mapbox 1.45 with CitySimulator scene. I try using map tiles from camera bounds. But when I change camera rotationX from 25 to around 30, unity just freeze and I need to end task

Rotate around Y axis don't have any problem. It create and remove tiles around camera normally

**Comment by jordy-isaac** [comment]
@Thaina I wasn't able to reproduce this on the [latest release v2.0](https://www.mapbox.com/install/unity/). Would you mind giving it a try and letting me know how it goes?

**Comment by Thaina** [comment]
@jordy-isaac Will do it soon, thank you

**Comment by donedgardo** [comment]
I been encountering same problem when giving free look, around 30~ degree rotation on x axis unity crashes. Sometimes it doesn’t but it freezes until tiles get rendered, but mostly crashes. This is with the 2.0 sdk.

**Comment by 112kutiko** [comment]
hello i have the same problem
unity 2020.2.5f1
sdk 2.1.1

**Comment by RomanAtBrief** [comment]
Same problem. Honestly guys you need to release SDK update !

**Comment by Markovicho** [comment]
some news about this issue in another thread : [1797](https://github.com/mapbox/mapbox-unity-sdk/issues/1797)

**Comment by brnkhy** [comment]
I'm afraid this is inevitable in v2.1.1 as it doesn't have a proper quad tree implementation and low degree camera angles loads way too much tiles at once. 
I am working on this for possible future versions but there's no ETA on that :(
