### ISSUE TITLE
reload map loads map with overlapping tiles

### ISSUE THREAD

**Issue by Gzbx** [mapbox/mapbox-unity-sdk#1091]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.0f3
  * Scripting Runtime Version:  .net 3.5
  * Scripting Backend: Mono
  * Api Compatibility Level: .Net 2.0 Subset
* Mapbox SDK version: 1.4.5
* The platform you're building to: Windows
* A description of what you're trying to do:
Reload a map to a new location
* Steps to recreate the bug if appropriate:
Loaded a map initialised on start with the following settings
![image](https://user-images.githubusercontent.com/35828779/46948498-07f0e880-d0ca-11e8-9262-1f2055c79d1b.png)

then  call reload map using the example in UpdateMap.cs and supplied a different location ( any will do) and the tiles do not stitch together properly - they overlap as below

![image](https://user-images.githubusercontent.com/35828779/46948448-dbd56780-d0c9-11e8-96e4-d02c164f80ce.png)

* Links to your logs are also helpful:

**Comment by atripathi-mb** [comment]
> A description of what you're trying to do:
Reload a map to a new location


@Gzbx How are you reloading the map? The suggested way is to use the `map.UpdateMap( latlong,zoom)` . 

Can you provide detailed steps to reproduce or code snippet of map reloading?

**Comment by Gzbx** [comment]
Hi @atripathi-mb, yes it is using updatemap. The code is adapted from the update map sample. I will forward on the exact code ASAP.

**Comment by Gzbx** [comment]
Here is the code that reloads the map.


namespace Mapbox.Examples
{
    using Mapbox.Unity;
    using UnityEngine;
    using UnityEngine.UI;
    using Mapbox.Geocoding;
    using Mapbox.Utils;
    using Mapbox.Unity.Map;

    [RequireComponent(typeof(InputField))]
    public class UpdateMap : MonoBehaviour
    {
        [HideInInspector]
        public AbstractMap[] m_arrMap;

        // The input field players use to change their maps location.
        InputField m_ifWhereGo;

        ForwardGeocodeResource m_fgrResource;

        public static bool m_sbSearched = false;

        public static Vector2d m_v2dCoords;

        public Vector2d Coordinate
        {
            get
            {
                return m_v2dCoords;
            }
        }

        bool m_bHasResponse;
        public bool HasResponse
        {
            get
            {
                return m_bHasResponse;
            }
        }

        public ForwardGeocodeResponse Response { get; private set; }


        void Awake()
        {
            m_ifWhereGo = GetComponent<InputField>();
            m_ifWhereGo.onEndEdit.AddListener(HandleUserInput);
            m_fgrResource = new ForwardGeocodeResource("");

            // Get all the maps and put them in an array.
            m_arrMap = FindObjectsOfType<AbstractMap>();
        }

        void HandleUserInput(string searchString)
        {
            m_bHasResponse = false;
            if (!string.IsNullOrEmpty(searchString))
            {
                m_fgrResource.Query = searchString;
                MapboxAccess.Instance.Geocoder.Geocode(m_fgrResource, HandleGeocoderResponse);
                // Setting the string as the last place searched.
                m_ifWhereGo.placeholder.GetComponent<Text>().text = searchString;
                // Clear the search term.
                m_ifWhereGo.text = "";
            }
        }

        void HandleGeocoderResponse(ForwardGeocodeResponse res)
        {
            m_bHasResponse = true;
            if (null == res)
            {
                m_ifWhereGo.text = "no geocode response";

                // Sorry that location could not be found.
                // TODO.
            }
            else if (null != res.Features && res.Features.Count > 0)
            {
                var center = res.Features[0].Center;
                //_inputField.text = string.Format("{0},{1}", center.x, center.y);
                m_v2dCoords = res.Features[0].Center;

            }
            Response = res;
            OnGeocoderResponse(res);

            // Delete all the map data because it would appear in the new location.
            GameObject.Find("LogicManager").GetComponent<SaveLoadMap>().DeleteMapData();
            
            // Tell the car the game has searched.
            m_sbSearched = true;
        }

        void OnGeocoderResponse(ForwardGeocodeResponse response)
        {
            if (null != response.Features && response.Features.Count > 0)
                for (int i = 0; i < m_arrMap.Length; ++i)
                    m_arrMap[i].UpdateMap(response.Features[0].Center, (int)m_arrMap[i].Zoom);
        }
    }
}

**Comment by atripathi-mb** [comment]
@Gzbx Unfortunately, the script that you have attached does not allow me to reproduce the issue. There is additional setup required to run that script. 

As a first step, can you try reproducing the issue with just the ReloadMap script?

You can provide us with a small project to reproduce the issue or give all steps required to reproduce the issue you are seeing.

**Comment by Gzbx** [comment]
@atripathi-mb , I have linked a unity project. Download and Unzip the project. Open in Unity.  Run the CarV3 scene from the main assets folder. Enter the location "30 wall st richmond". The problem appears - I hope this helps.

https://drive.google.com/open?id=1NSxpPgMQojk811eaeO-xSbMB31skwfhB

unity and mapbox version as in the first post.

regards

George

**Comment by Gzbx** [comment]
the above project uses the original ReloadMap.cs script and ReloadMapCanvas Prefab provided in the mapbox examples.

**Comment by Gzbx** [comment]
@atripathi-mb some more information, if you continue to search for locations you will continue to get issues.
Here is a video of my testing:
https://drive.google.com/file/d/1u3xOF3gYDQwz6EJjbh3-iYXjqwHPv2fX/view?usp=sharing

**Comment by Gzbx** [comment]
@atripathi-mb thanks for the feedback - testing now in 1.4.5 with custom scaling

**Comment by Gzbx** [comment]
Thanks @atripathi-mb , that works.

If I may can I ask one further question related to the texture size of tiles. I have noticed that for each tile at default settings there is an 8mb texture created. When scaling up the number of tiles I am coming up against memory limitations. Are there any options to reduce the size of the texture without loosing quality. I am assuming that each tile is not actually 8mb to download and that somehow this is inflated. Your feedback is appreciated.

**Comment by Gzbx** [comment]
![image](https://user-images.githubusercontent.com/35828779/47294644-6b928d00-d659-11e8-9d75-5169d1af7e30.png)
here is an extract from the unity profiler.

**Comment by brnkhy** [comment]
@Gzbx I think your images are uncompressed, if you check "Use Compression" under `Abstract Map -> Image" section, those numbers will probably go down drastically. 
Also can you please let me know the new numbers after you try as well?

**Comment by Gzbx** [comment]
Thanks @brnkhy, I will check back tonight and revert.

**Comment by Gzbx** [comment]
@brnkhy thanks for your advise here are my tests:

2MB : no retina,no compression and no mipmap
8MB : with retina, no compression and no mimap
.5MB : no retina,with compression and no mipmap
2MB : with retina,with compression and no mipmap
2.7MB : no retina,no compression and with mipmap
10.7MB : with retina,no compression and with mipmap
.7MB : no retina,with compression and with mipmap
2.7MB : with retina,with compression and with mipmap

note: need to clear cache between tests :)

I wasn't seeing the results at first. I tracked this down to having more than one map in the scene. It appears as though only one set of image raster options get used by both maps. Would you advise against using more than one map in a scene? In my case I hadn't worked out how to toggle map features on and off at run-time so as a workaround I was using another map that I could activate or de-activate to achieve the result I was after. 

Happy to close this issue - if you could provide a sample of how to activate/deactivate a map feature in run time - that would be greatly appreciated.

**Comment by brnkhy** [comment]
@Gzbx thanks a lot for the numbers! I also did some tests and I think this is the best Texture2D.Load can do at the moment. runtime resource loading isn't easy :(
All maps should be individual and use its own settings, if that's not the case it's definitely a bug. I think we don't test that case too much as it's one of the uncommon cases. I'll check and see what I can find but meanwhile you can open a ticket for it as well.

**Comment by jordy-isaac** [comment]
Closing this one in favor of #1107

**Comment by Pizoline** [comment]
This bug is still present (or reappeared) in v2.1.1, and easy to reproduce:
-Create an empty scene
-Add a Mapbox Map
-Configure "Scaling Option" to "World Scale"
-Play
-During playmode, change location far away (using inspector or UpdateMap method)
Farther you jump, more is the tiles overlapping

**Comment by lukemadera** [comment]
I'm having a similar but reverse problem - the tiles have gaps. Any update on a fix for this?
