### ISSUE TITLE
Can't use Maptiler Servers

### ISSUE THREAD

**Issue by dermarder** [mapbox/mapbox-unity-sdk#1092]
Dear Mapbox team,

im not able to use maptiler service with your sdk. This should work oob as they are using the Mapbox vector tile pbf format right?

Thank you very much in advance for your help.

**Comment by jordy-isaac** [comment]
Hi @dermarder That's a 3rd party tool that looks like it's using openstreetmap. Is there a reason that you are needing maptiler instead of one of our map prefabs?
