### ISSUE TITLE
Scene loading bug

### ISSUE THREAD

**Issue by MarjanPl** [mapbox/mapbox-unity-sdk#1102]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
2018.2
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
2.0
* The platform you're building to:
iOS
* A description of what you're trying to do:
just build and see what happens
* Steps to recreate the bug if appropriate:
just use the 2.0 release and build to iOS
* Links to your logs are also helpful: 

You are using a scriptable Object called "ScenesList" to generate your main menu. However, the second entry of the scene list is null.
Obviously this leads to an exception when trying on a device (only one button created in the scrollview).
Besides that, the scrollview is not really setup for different screen sizes.

After i deleted the missing entry i was able to use it on an iPhoneX.

**Comment by jordy-isaac** [comment]
@MarjanPl What example scene did you build? Can you also post a screenshot of your player and build settings? Please provide a bit more detail and steps to reproduce.

**Comment by MarjanPl** [comment]
I am speaking of release 2.0.
You have a number of scenes in the build settings. starting scene is "main" which simply creates u GUI with a list of the other settings by the help of a scriptable object, which holds strings in an array with scene names (Which seems unnecessary, as you can pull this from Unity scene manager class anyways).

2nd entry was not assigned. 

End of story.
