### ISSUE TITLE
AddGameObjectModifier at runtime

### ISSUE THREAD

**Issue by Flameshot** [mapbox/mapbox-unity-sdk#1105]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version:  2018.2.6f1
  * Scripting Runtime Version:  .NET 3.5 Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level:  .NET 2.0 Subset

* Mapbox SDK version:  v2.0.0
* The platform you're building to: Desktop
* A description of what you're trying to do:: I made a method which creates a new layer in MapFeatures so when I click on an UI button the new layer is created. Everything works fine here, but the next step, I'm trying to add an gameobject modifier like this: https://pastebin.com/x6TjXycL ( I found this example on ApiTest.cs ) the problem is I get nullreference in SubLayerBehaviorModifiers.cs on method AddGameobjectModifier. So I tested on debug mode with breakpoint and GoMidifiers is null everytime. 

EDIT: I found something: public List<GameObjectModifier> GoModifiers is never initialized so it will be null. So I made this:

myLayer.GoModifiers = new List < GameObjectModifier > ();
myLayer.BehaviorModifiers.AddGameObjectModifier(ScriptableObject.CreateInstance<AddMonoBehavioursModifier>());
_map.VectorData.AddFeatureSubLayer(myLayer);

With those lines I add a gameobject modifier of AddMonoBehaviorusModifier type in editor, but now I don't know how to attach the modifier to the script programatically.

**Comment by Flameshot** [comment]
I've fixed my problem. Everything works fine now. But I think the idea of initialization the GoModifiers list should be made in sdk not on user scripts.

**Comment by jordy-isaac** [comment]
Thanks for closing the loop! We also really appreciate the feedback.

**Comment by jordy-isaac** [comment]
@greglemonmapbox Assigning this one over to you so you can take a look at the feedback.
