### ISSUE TITLE
Complications using multiple maps in one scene

### ISSUE THREAD

**Issue by Gzbx** [mapbox/mapbox-unity-sdk#1107]
**Unity version:** 2017.3.0f3
**Scripting Runtime Version:** .net 3.5
**Scripting Backend:** Mono
**Api Compatibility Level:** .Net 2.0 Subset
**Mapbox SDK version:** 1.4.5
The platform you're building to: Windows
**A description of what you're trying to do:**
I have 2 or more maps in the scene and noticed that the image raster options seem to be shared such that the settings in the first map are used by the second map. I verified this by ensuring the each map had unique raster settings and then I embedded debug statements into the MapImageFactory.cs  class into the following function to output the image raster options being passed. My observations where that the settings always matched the first map.

![image](https://user-images.githubusercontent.com/35828779/47495909-1c3e9d80-d8a1-11e8-9955-a18bd24ab5ec.png)

Another complication I have noticed when using two maps in a scene is that where you specify a range around transform extent and specify a target transform. If you follow the same target transform on 2 maps, only one map moves with the target.

![image](https://user-images.githubusercontent.com/35828779/47496349-45136280-d8a2-11e8-969f-113878d9f7bd.png)

I assume this is because there is code in the RangeAroundTransformTileProvider in the following function that updates the _rangeTileProviderOptions.targetTransform.hasChanged = false; and as both maps share this transform once the first map has processed, the second will think the transform has not changed.

![image](https://user-images.githubusercontent.com/35828779/47496887-f49d0480-d8a3-11e8-9140-271c6bec56cd.png)

My work around is to use a unique target transform in each map and synchronize there transform positions.

**Comment by brnkhy** [comment]
@Gzbx really sorry I couldn't look into this earlier.
I just checked the first issue and it seems fixed in the latest version. 

With the second issue, using two targets and syncing them should work but it would be a little costly I guess (yet another script and update call etc). Another option would be caching position in `RangeAroundTransformTileProvider` itself without relying on `hasChanged` flag kept on the game obeject itself (because there'll be two separate tile providers so caches will be separete).

I tried this and I think it works;
```
public override void UpdateTileProvider()
		{
			if (_waitingForTargetTransform && !_initialized)
			{
				if (_rangeTileProviderOptions.targetTransform != null)
				{
					_initialized = true;
				}
			}

			if (_rangeTileProviderOptions != null && _rangeTileProviderOptions.targetTransform != null && _rangeTileProviderOptions.targetTransform.position != _cachedPosition)
			{
				UpdateTileExtent();
				_rangeTileProviderOptions.targetTransform.hasChanged = false;
				_cachedPosition = _rangeTileProviderOptions.targetTransform.position;
			}
		}
```
