### ISSUE TITLE
Reload map after changing terrain exaggeration

### ISSUE THREAD

**Issue by Gzbx** [mapbox/mapbox-unity-sdk#1112]
Unity version: **2017.3.0f3**
Scripting Runtime Version: **.net 3.5**
Scripting Backend: **Mono**
Api Compatibility Level: **.Net 2.0 Subset**
Mapbox SDK version: **1.4.5**
The platform you're building to: Windows
A description of what you're trying to do:
I want to change the terrain exaggeration settings at run time and reload the map.

Here is what I have been able to do successfully:

**Step 1)** I start with a standard AbstractMap in the scene and a range around transform extent. the transform is not moving and effectively at world.zero.

![image](https://user-images.githubusercontent.com/35828779/47605266-1cc96680-da50-11e8-8f54-e1943c2b3814.png)

**Step 2)** In code I find my map using:
           ` AbstractMap[] arrMap = FindObjectsOfType<AbstractMap>();`

**Step 3)** In code I can successfully change the exaggeration factor by setting a value for:
            `arrMap[0].Terrain.LayerProperty.requiredOptions.exaggerationFactor`

Up until this point all is OK and I can see in the inspector that the terrain settings are accurately reflected. But I can not work out how to reload the map. Below is what I have tried without any success - any advice/sample code on how to reload a map with new terrain exaggeration settings would be appreciated.

**Step 4**
I have tried to use the function, 
           ` arrMap[0].UpdateMap(arrMap[0].CenterLatitudeLongitude, arrMap[0].AbsoluteZoom);`
but as the lat/long and the zoom level are not changing - this has no effect

I have tried to use the function 
           ` arrMap[0].Initialize(arrMap[0].CenterLatitudeLongitude, arrMap[0].AbsoluteZoom);`
OR
          `arrMap[0].ResetMap()`
but these both throw numerous exceptions the first of which is on this line

![image](https://user-images.githubusercontent.com/35828779/47605128-04f0e300-da4e-11e8-8eb0-09cd4f031fa3.png)

```
NullReferenceException: Object reference not set to an instance of an object
Mapbox.Unity.MeshGeneration.Factories.TerrainFactoryBase.OnUnregistered (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainFactoryBase.cs:62)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Unregister (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:78)
Mapbox.Unity.Map.AbstractMapVisualizer.DisposeTile (UnwrappedTileId tileId) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:251)
Mapbox.Unity.Map.AbstractMapVisualizer.Initialize (IMapReadable map, IFileSource fileSource) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:95)
Mapbox.Unity.Map.AbstractMap.InitializeMap (Mapbox.Unity.Map.MapOptions options) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:517)
Mapbox.Unity.Map.AbstractMap.SetUpMap () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:488)
Mapbox.Unity.Map.AbstractMap.Initialize (Vector2d latLon, Int32 zoom) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:542)
TerrainSliderHandler.UpdateMap () (at Assets/TerrainSliderHandler.cs:49)
TerrainSliderHandler.OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData) (at Assets/TerrainSliderHandler.cs:32)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerUpHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:43)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerUpHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()
```

I would appreciate your speedy consideration on how best to update terrain exaggeration and reload a map.

**Comment by Gzbx** [comment]
here is the complete class this class is added to a slider in my UI

![image](https://user-images.githubusercontent.com/35828779/47605317-906b7380-da50-11e8-8993-7c73d65f9f23.png)

note: incontrol is an input manager we use, but for testing purposes it could be standard input control.

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using InControl;
using Mapbox.Unity.Map;

public class TerrainSliderHandler : MonoBehaviour,IPointerUpHandler, IPointerDownHandler// These are the interfaces the OnPointerUp method requires.
{
    private InputDevice m_idJoystick;

    //OnPointerDown is also required to receive OnPointerUp callbacks
    public void OnPointerDown(PointerEventData eventData)
    {
    }
    private void Awake()
    {
        m_idJoystick = InputManager.ActiveDevice;
    }
    private void Update()
    {
        if (m_idJoystick.Action1.WasReleased)
        {
            UpdateMap();
        }
    }

    //Do this when the mouse click on this selectable UI object is released.
    public void OnPointerUp(PointerEventData eventData)
    {
        UpdateMap();
    }

    private void UpdateMap()
    {
        float fSliderValue = GetComponent<Slider>().value;

        Debug.Log("slider values: " + fSliderValue);

        AbstractMap[] arrMap = FindObjectsOfType<AbstractMap>();
        for (int i = 0; i < arrMap.Length; ++i)
        {
            //code to set the exageration factor
            arrMap[i].Terrain.LayerProperty.requiredOptions.exaggerationFactor = fSliderValue;
            arrMap[i].UpdateMap(arrMap[i].CenterLatitudeLongitude, arrMap[i].AbsoluteZoom);
            //Mapbox.Unity.MapboxAccess.Instance.ClearAllCacheFiles();
            //arrMap[i].MapVisualizer.ActiveTiles.Clear(); 
            //arrMap[i].ResetMap();
            //arrMap[i].Initialize(arrMap[i].CenterLatitudeLongitude, arrMap[i].AbsoluteZoom);
        }
    }
}

**Comment by atripathi-mb** [comment]
@Gzbx Updating settings at runtime are supported starting with v2.0. 
I would suggest updating to the latest version and use API's to change the exaggeration factor.

**Comment by Gzbx** [comment]
Hi @atripathi-mb , I am close to a deadline and think it too risky to update to 2.0 at the moment. I will take a look at the code for 2.0 - can you point me to an example scene or class to look into?

**Comment by jordy-isaac** [comment]
@Gzbx We don't have an example scene for this but you can find the API documentation [here](https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.ITerrainLayer.html).

**Comment by Gzbx** [comment]
@jordy-issac can you point me towards the code that performs the reload/update of the map once it detects a change in settings?

**Comment by atripathi-mb** [comment]
@Gzbx There were multiple changes to make runtime update/reloading tiles possible. It was a major effort and hence it was released in a separate release. 
It would be difficult to point to a single method or file.
