### ISSUE TITLE
Process for using ArCore Cloud Anchors with Mapbox Unity SDK

### ISSUE THREAD

**Issue by CedricKnapp** [mapbox/mapbox-unity-sdk#1114]
In order to use the newer Cloud Anchor feature provided by  [ARCore SDK for Unity version 1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0) or newer, I've experimented with trying to upgrade the version of Google ARCore from the version which is provided with the mapbox unity sdk. This has caused many project breaking issues for me. 

I was wondering if there was an already defined way or if anyone had experience with using Cloud Anchors with the Mapbox Unity SDK.

Thanks!

**Comment by jordy-isaac** [comment]
@CedricKnapp We'll be [updating](https://github.com/mapbox/mapbox-unity-sdk/issues/1100) to [ARFoundation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/index.html#about-ar-foundation) soon which should have latest version of ARCore.

**Comment by CedricKnapp** [comment]
@jordy-isaac Would you have any time estimate when a release may come out with the updated ARFoundation?

**Comment by jordy-isaac** [comment]
@CedricKnapp I don't have an exact timeline but given we've had quite a bit of demand recently so it's a high priority. Keep an eye on this repo for updates.

**Comment by CedricKnapp** [comment]
Thanks for the info. Great to hear! 
-------- Original message --------From: "Jordy W." <notifications@github.com> Date: 2018-10-29  6:47 PM  (GMT-05:00) To: mapbox/mapbox-unity-sdk <mapbox-unity-sdk@noreply.github.com> Cc: CedricKnapp <cedriccknapp@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [mapbox/mapbox-unity-sdk] Process for using ArCore Cloud Anchors with Mapbox Unity SDK (#1114) 
@CedricKnapp I don't have an exact timeline but given we've had quite a bit of demand recently so it's a high priority. Keep an eye on this repo for updates.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mapbox/mapbox-unity-sdk","title":"mapbox/mapbox-unity-sdk","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mapbox/mapbox-unity-sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jordy-isaac in #1114: @CedricKnapp I don't have an exact timeline but given we've had quite a bit of demand recently so it's a high priority. Keep an eye on this repo for updates."}],"action":{"name":"View Issue","url":"https://github.com/mapbox/mapbox-unity-sdk/issues/1114#issuecomment-434109059"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mapbox/mapbox-unity-sdk/issues/1114#issuecomment-434109059",
"url": "https://github.com/mapbox/mapbox-unity-sdk/issues/1114#issuecomment-434109059",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mapbox/mapbox-unity-sdk] Process for using ArCore Cloud Anchors with Mapbox Unity SDK (#1114)",
"sections": [
{
"text": "",
"activityTitle": "**Jordy W.**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jordy-isaac",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mapbox/mapbox-unity-sdk\",\n\"issueId\": 1114,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mapbox/mapbox-unity-sdk/issues/1114#issuecomment-434109059"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402457475\n}"
}
],
"themeColor": "26292E"
}
]
