### ISSUE TITLE
Get player location name

### ISSUE THREAD

**Issue by Natatem00** [mapbox/mapbox-unity-sdk#1115]
Hello. I create game in Unity3D with MapBox, and I can't find answer on my question: how I can convert LatitudeLongitude(Vector2) data and get location name like "Ukraine, Kiev"?

**Comment by jordy-isaac** [comment]
@Natatem00 Can you let us know a bit more about your use case and what you're trying to achieve in the end? Have you seen the `ReverseGeocoder` playground example scene? You can find it the following folder `Mapbox > Examples > 5_Playground`

**Comment by Natatem00** [comment]
@jordy-isaac Thank you. I found what i want. I'm trying to create multiplayer game and I need get player's country and city name, to make sort in database
