### ISSUE TITLE
Android minimum SDK version(Unity3D)

### ISSUE THREAD

**Issue by Natatem00** [mapbox/mapbox-unity-sdk#1120]
Hello, I have a problem again. When I try to build my game for android(in Unity3D) I have minimum SDK version problem. I need it to be around 19 version, but it's 24. I tried to change android manifest, but it didn't help. So...I can use only 24 version of SDK, or I can change it somehow?

**Comment by jordy-isaac** [comment]
Hi @Natatem00 

That's our custom native Android GPS Plugin. Its min requirement is set to 24 as it uses methods that are not available on earlier versions.

However, if you do want to downgrade you can download the Zip files without the command line: https://github.com/mapbox/mapbox-unity-sdk/releases
Some other things to try:

1. Uncheck `Android` in the inspector for
    Assets/Mapbox/Unity/Location/Plugins/Android/com.mapbox.android.unity-debug
2. Delete whole folder:
    Assets/Mapbox/Unity/Location/Plugins/Android/

If the above does not work I would suggest moving your min supported device up to lvl 24 to be able to make use of the Maps SDK for Unity.


https://github.com/mapbox/mapbox-unity-sdk/issues/982 also has a reported workaround.

**Comment by AssIsBack** [comment]
Hello, Jordy!

What do you mean by "methods" in MapBox?

We want to use MapBox 21 SDK in Unity (to capture more users with older version of Android). What kind of problems can appear? Problems with compas, location, build?
