### ISSUE TITLE
Best way to update SDK?

### ISSUE THREAD

**Issue by tab1887** [mapbox/mapbox-unity-sdk#1122]
Hi,

I'm wondering if there is any recommended way to update the SDK from one version to another.
Currently I'm trying to update from 1.4.4 to 2.0.

Just re-importing the new package does not work, as it leaves a bunch of outdated files in the project that throw all kinds of errors.

If I delete all Mapbox files before importing, I guess I will have to setup my map from scratch?

Is there any clever way to do it?

Kind Regards,
Tim

I'm on Unity 2018.2.14 on MacOS.

**Comment by jordy-isaac** [comment]
Hi @tab1887 Yes, you would need to set up a map from scratch if you deleted and reimported. I find it best to open two instances of Unity and try to address each error. We don't have a guide for migrating except for the major one from [1.3 to 1.4](https://www.mapbox.com/unity-sdk/maps/overview/migrate-version/). Although that's a different migration, the workflow how it's done might be helpful to you. 

If you're stuck on any errors please open an issue and someone in the community might be able to offer some ideas. You can also email help@mapbox.com with screenshots of any errors.

**Comment by tab1887** [comment]
Hi  @jordy-isaac  ,

thank you very much for your fast response. I've got it working for this time. Hopefully it will work also next time, when my project may be a bit more advanced ;-)
