### ISSUE TITLE
How to calculate appropriate zoom for bounding box

### ISSUE THREAD

**Issue by halzate93** [mapbox/mapbox-unity-sdk#1125]
Hi,

I'm fairly new with the Mapbox SDK and I've been working with the Zoomable Map example as a starting point.

I'm trying to set the zoom of the map so 2 arbitrary lat,long coordinates are displayed in my viewport.

This far I got the bounds and I've been looking into using the meters per pixel math as recommended in this issue: https://github.com/mapbox/mapbox-unity-sdk/issues/478

This is what my equation looks like this far: 

pixelSize = distance / viewport.pixelWidth //distance in meters
C = 40075016.686d //based on https://wiki.openstreetmap.org/wiki/Zoom_levels
z = (ln(C * cos(latitude)) - ln(pixelSize))/ln(2)

But the values don't seem to make sense.

I would love to see a FitToBounds (Vector2dBounds bounds) function in the AbstractMap class, like the ones available in the Android and Web APIs:
http://www.mapbox.com.s3-website-us-east-1.amazonaws.com/android-sdk/examples/fit-bound-camera/

**Comment by halzate93** [comment]
This is what the actual C# implementation looks like in Unity:

`
private double CalculateZoomLevel (BoundingBox framing)
        {
            double metersPerPixel = (framing.extentsMeters.x * 2d) / Camera.main.pixelWidth;
            double zoom = (Mathd.Log (C * Mathd.Cos (framing.latLong.Center.x * Mathd.Deg2Rad)) - Mathd.Log (metersPerPixel)) / LOG_2;
            Debug.LogFormat ("zoom:{0} pixelSize:{1} lat:{2} d:{3} ", zoom, metersPerPixel, framing.latLong.Center.x, framing.extentsMeters.x * 2d);
            return zoom;
        }
`

**Comment by halzate93** [comment]
After a few tries I got it, this is what my function looks like:

```csharp
//C = 40075016.686d LOG_2 = 0.69314718056d
private float CalculateZoomLevel (BoundingBox framing)
        {
            double metersPerPixel = (framing.extentsMeters.x * 2d) / Camera.main.pixelWidth;
            float zoom = (float) (((Mathd.Log (C * Mathd.Cos (framing.latLong.Center.x * Mathd.Deg2Rad)) - Mathd.Log (metersPerPixel)) / LOG_2) - 8d);
            Debug.LogFormat ("zoom:{0} pixelSize:{1} lat:{2} d:{3} ", zoom, metersPerPixel, framing.latLong.Center.x, framing.extentsMeters.x * 2d);
            return zoom;
        }
```

Make sure to calculate the extents of the bounding box in meters: 
```
private struct BoundingBox
        {
            public Vector2d extentsMeters;
            public Vector2dBounds latLong;

            public BoundingBox (Vector2dBounds latLong, Vector2d extentsMeters)
            {
                this.latLong = latLong;
                this.extentsMeters = extentsMeters;
            }

            public static BoundingBox Build (double south, double east, double north, double west)
            {
                Vector2dBounds latLong = new Vector2dBounds(new Vector2d(south, west), new Vector2d(north, east));
                Vector2d extentsMeters = CalculateExtentsMetersFromBounds (latLong);
                return new BoundingBox (latLong, extentsMeters);
            }

            private static Vector2d CalculateExtentsMetersFromBounds (Vector2dBounds latLongBounds)
            {
                Vector2d bottomLeft = Conversions.LatLonToMeters (latLongBounds.SouthWest);
                Vector2d topRight = Conversions.LatLonToMeters (latLongBounds.NorthEast);
                return new Vector2d ((topRight.x - bottomLeft.x) * 0.5d, (topRight.y - bottomLeft.y) * 0.5d);
            }
        }
```

**Comment by halzate93** [comment]
Hi guys, 

So I thought I got it right last year but now after testing on different resolutions my code to calculate the appropriate zoom level doesn't work as expected.

I am using the AbstractMap class and the dynamic zoom example as a starting point. I'm using an ortographic camera with size 40, and the unityTileSize to 40 as well with the custom strategy.

I have tried 2 approaches: 

1) calculating the zoom by working out the math from the pixelsize equations looking through the code and commented in the Conversions class pointing to https://wiki.openstreetmap.org/wiki/Zoom_levels

This is my code at this point:
```csharp
//Doesn't work properly
        private float CalculateZoom (Vector2dBounds framing)
        {
            double tileSizeDegrees = (framing.East - framing.West) / ((2d * mapCamera.orthographicSize * mapCamera.aspect) / (map.Options.scalingOptions.unityTileSize));
            float zoomLevel = (float)(((LOG_360 - Mathd.Log (tileSizeDegrees)) / LOG_2) - 8d);
            return Mathf.Clamp(zoomLevel, minZoom, maxZoom);
        }
```

My guess is that I'm not considering the scale change in the scale of the map itself but I haven't been able to figure out how everything works together.

Could someone point me in the right direction?

**Comment by brnkhy** [comment]
@halzate93 First I must apologize, every time I read your ticket I say "Ok this'll take some thinking so I'll finish other tickets first" and then just forget to come back. 
I like the idea a lot but it depends on so many factors (camera type, fov if perspective, tile count to load, tiles to load etc) that I don't think it'll be easy. 
You have to fix either zoom level or tile count for this right? I understand you want to calculate zoom level though so how do you want to decide the tile count? 
Also if you're using the tile size information (in meter) on zoom levels wikipedia page, I believe they are in real world meters (not mercator) so they'll be only good on equatoral region and will get worse and worse as you move to higher/lower latitudes.

I'll look into the calculations tomorrow (🤞) and see if I can think of something.

**Comment by halzate93** [comment]
Hi @brnkhy,

Thanks for taking a look.

I found a work around (I do a binary search for different zoom levels with a max number of iterations and check for visibility from the camera). I added padding as well in the viewport.

```csharp
 private void UpdateMapToBoundsImmediate (Vector2dBounds bounds)
        {
            float closestZoom = minZoom;
            float zoomDelta = (maxZoom - minZoom) / 2f;
            float currentZoom = minZoom + zoomDelta;
            float bottomWithHeightPercentage = paddingBottom + Screen.height * (1f - screenHeightPercentage) / 2f;
            float topWithHeightPercentage = Screen.height - paddingTop - Screen.height * (1f - screenHeightPercentage) / 2f;
            Vector3 worldPosition;
            Vector2 screenPosition;
            for (int i = 0; i < maxZoomApproximateIterations; i++)
            {
                map.UpdateMap(bounds.Center, currentZoom);
                worldPosition = map.GeoToWorldPosition(bounds.NorthEast, false);
                screenPosition = mapCamera.WorldToScreenPoint(worldPosition);
                zoomDelta /= 2f;
                if (screenPosition.x >= paddingLeft && screenPosition.x <= Screen.width - paddingRight && screenPosition.y >= bottomWithHeightPercentage && screenPosition.y <= topWithHeightPercentage)
                {
                    closestZoom = currentZoom;
                    currentZoom += zoomDelta;
                }
                else
                    currentZoom -= zoomDelta;
            }
            UpdateMap(bounds.Center, closestZoom);
        }
```

But still think this should be doable, I was trying to make it work for width only, then a similar approach could be applied to height and pick the smaller of both.

First with the orthographic size of the camera I can get the width of the viewport in world space. Then I know the width of the tile using the scaling strategy used in the AbstractMap and the unityTileSize. So the bottom part is how many tiles are visible in the screen (Float). And the result is degrees/tile. Which in hindsight might be where I'm wrong.

```csharp
double tileSizeDegrees = (framing.East - framing.West) / ((2d * mapCamera.orthographicSize * mapCamera.aspect) / (map.Options.scalingOptions.unityTileSize));
```

Then I have the equation for tile scale in degrees used in the Conversion class:

```csharp
public static float GetTileScaleInDegrees(float latitude, int zoom)
{
	return (float)(360.0f / Math.Pow(2f, zoom + 8));
}
```

Which relates to the one done in meters, the difference is that degrees shouldn't be affected by latitudes changes, right?, the equation in the Open street maps wiki does accommodate for changes in latitude: Stile = C ∙ cos(latitude) / 2 zoomlevel so maybe I could use that one instead. 

So doing some math on the equation I solve for zoomLevel:
float zoomLevel = (float)(((LOG_360 - Mathd.Log (tileSizeDegrees)) / LOG_2) - 8d); where LOG_360 and LOG_2 are constants.

I'll give it another shot this week and post any updates on my end. Let me know if what I'm trying to do makes sense.

It would also be useful to know how this has been implemented on the other implementations of Mapbox.

https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/

Cheers,
Hector

**Comment by nilsk123** [comment]
> ```cs
>  private void UpdateMapToBoundsImmediate (Vector2dBounds bounds)
>         {
>             float closestZoom = minZoom;
>             float zoomDelta = (maxZoom - minZoom) / 2f;
>             float currentZoom = minZoom + zoomDelta;
>             float bottomWithHeightPercentage = paddingBottom + Screen.height * (1f - screenHeightPercentage) / 2f;
>             float topWithHeightPercentage = Screen.height - paddingTop - Screen.height * (1f - screenHeightPercentage) / 2f;
>             Vector3 worldPosition;
>             Vector2 screenPosition;
>             for (int i = 0; i < maxZoomApproximateIterations; i++)
>             {
>                 map.UpdateMap(bounds.Center, currentZoom);
>                 worldPosition = map.GeoToWorldPosition(bounds.NorthEast, false);
>                 screenPosition = mapCamera.WorldToScreenPoint(worldPosition);
>                 zoomDelta /= 2f;
>                 if (screenPosition.x >= paddingLeft && screenPosition.x <= Screen.width - paddingRight && screenPosition.y >= bottomWithHeightPercentage && screenPosition.y <= topWithHeightPercentage)
>                 {
>                     closestZoom = currentZoom;
>                     currentZoom += zoomDelta;
>                 }
>                 else
>                     currentZoom -= zoomDelta;
>             }
>             UpdateMap(bounds.Center, closestZoom);
>         }
> ```

Very interesting approach! Going to look into this myself soon

**Comment by Tasta** [comment]
Hello guys,

I encountered the same need to zoom on a given bounding box. 
My aspect ratio is portrait, so my approach was to attempt and fit a given distance into the width of the screen.

My solution relies on computing how many Unity World Units fit in the screen, translate that into meters, compute the target scale, and inverse the computations done by Mapbox to translate Zoom into Scale.

It's kinda hacky, but it does the job.

Here's the code:

    public void ZoomToFit(float distance) {
            // Get screen visible width in World Units
            float screenHeightInUnits = mapCamera.orthographicSize * 2;
            float screenWidthInUnits = screenHeightInUnits * Screen.width / Screen.height;

            // Get how many meters are displayed in a screen
            float meters = screenWidthInUnits * map.Options.scalingOptions.unityTileSize / 10.0f;

            // Reverse computations of scale, to compute target zoom
            float targetScale = meters / distance;
            float targetZoom = (float)Math.Log(targetScale, 2.0f) + map.InitialZoom;

            // Start a routine to neatly lerp towards target zoom
            if (changingZoom != null)
                StopCoroutine(changingZoom);
            changingZoom = StartCoroutine(LerpZoom(targetZoom));
    }
