### ISSUE TITLE
Navigation with Time / Distance estimate support

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#1126]
I'm using `The traffic and directions example` 
,but `DirectionsFactor.cs script` only offer `Directions` game object. 
I want to use `time estimate` `distance estimate` even more `Turn-by-turn guidance` . 
Does `mapbox-unity-sdk` have any founction or method to implement it?

**Comment by jordy-isaac** [comment]
@willychang21 You can get the response from the directions API. I would suggest that you check out the Directions playground scene. You can find the playground at the folder path: `Mapbox > Examples > 5_Playground > Scenes > Directions`. You might also find the [API documentation](https://www.mapbox.com/api-documentation/#directions) for the Directions API helpful.
