### ISSUE TITLE
SpwanInsideModifier on recycled tiles

### ISSUE THREAD

**Issue by tab1887** [mapbox/mapbox-unity-sdk#1130]
The SpawnInsideModifier seems to spawn objects in completely wrong locations when working on a recycled UnityTile.

I'm using the SDK Package 2.0.0 on Unity 2018.2.14. on MacOS.

Steps to reproduce:
- In a fresh project import Mapbox SDK 2.0.0
- Setup a map with just 1 visible tile (e.g. RangeAroundCenter with 0 extent)
- Add a feature layer for buildings (with mesh colliders)
- Add a SpawnInsideModifier to spawn some random objects on flat building polygons
- Add a script to call UpdateMap with new coordinates some time after the first Initialize

Observations:
- On first initialization the Spawn looks as expected
- After updating the map there are objects spawned way outside the building on the new map location

After commenting out line 201 of AbstractMapVisualizer

//unityTile = _inactiveTiles.Dequeue();

practically disabling the use of recycled tiles, all is working fine.

I have found issue #928 that seems to be related, but as this is from July, I would guess the fix is already part of the V2.0.0 package?

Map after initialize
![image](https://user-images.githubusercontent.com/40249029/47969315-046fd200-e076-11e8-9610-e9d2aa529b0c.png)

Map after first update
![image](https://user-images.githubusercontent.com/40249029/47969319-16ea0b80-e076-11e8-9506-76cd90e7e92c.png)

Script used to update
![image](https://user-images.githubusercontent.com/40249029/47969323-25382780-e076-11e8-9e36-2818ae775729.png)

Disabling recycled tiles fixes the issue
![image](https://user-images.githubusercontent.com/40249029/47969327-2c5f3580-e076-11e8-9ea3-e2243cb491b9.png)

**Comment by atripathi-mb** [comment]
@brnkhy Could you take a look at this issues please?

**Comment by brnkhy** [comment]
Hey @tab1887,
I'm checking it at the moment but I'm afraid I couldn't recreate it.

What I did;
- Opened Interactive Styled Vector map, deleted all layers except building (so it actually could have been any scene)
- Extent options, range around center with 1 extent (wanted to load&recycle more tiles, also tried with 0)
- First location is the default location in the scene, I believe it's SF
- Settings and first location looks like this;
![unity_2018-11-05_23-29-09](https://user-images.githubusercontent.com/1465390/48024858-c85e6f00-e152-11e8-90e4-bd4cc3748ad5.png)
- created exact same test script, same location and zoom level as well.
- pressed space and it looks like this;
![unity_2018-11-05_23-31-34](https://user-images.githubusercontent.com/1465390/48024907-f80d7700-e152-11e8-8107-0f7a4167daa5.png)

so I guess one of us is missing something. any chance you forgot to add layer gameobject modifier? I believe spawn inside modifier depends on that.
Can you send a shot of your settings as well please?

**Comment by tab1887** [comment]
As promised, here are screenshots of the full map settings of my simple example scene:

In Edit mode (showing initial coordinates)
![image](https://user-images.githubusercontent.com/40249029/48090156-78d97b00-e206-11e8-90f4-c89497624b0d.png)

At runtime (after space key was pressed):
![image](https://user-images.githubusercontent.com/40249029/48089847-b984c480-e205-11e8-8c6f-727f1e4901ae.png)
![image](https://user-images.githubusercontent.com/40249029/48089866-c30e2c80-e205-11e8-914a-c9ed4dc4d45a.png)
![image](https://user-images.githubusercontent.com/40249029/48089891-ce615800-e205-11e8-9973-6ec3e80b6a6a.png)
![image](https://user-images.githubusercontent.com/40249029/48089910-db7e4700-e205-11e8-81dd-99432839c6b1.png)
![image](https://user-images.githubusercontent.com/40249029/48089919-df11ce00-e205-11e8-9938-7e4486855be5.png)


If it would help, I could try to upload the full Unity project somewhere.

**Comment by brnkhy** [comment]
also as a simple note, layers aren't set in your screenshots. LayerModifier should have a layer set and then SpawnInsideModifier layer mask should point to same layer.

**Comment by brnkhy** [comment]
I pushed the fix above here; https://github.com/mapbox/mapbox-unity-sdk/tree/spawnInsideBoundsFix
Haven't PRed yet as I'm not totally convinced yet. I tried some stuff like calling `Mesh.RecalculateBounds` hoping that somehow it would update the collider bounds as well but didn't work.
I don't get one thing though. If this is really about collider bounds being outdated and wrong, how does those rays still hit it? Strange...

**Comment by tab1887** [comment]
Thanks again for taking the time to look into this.

Today I have added a script like the one found [here](https://answers.unity.com/questions/461588/drawing-a-bounding-box-similar-to-box-collider.html) to the SpawnInsideModifierScript to make the collider bounds visible. Here are the results from my simple test scene:

After Initialize:
![image](https://user-images.githubusercontent.com/40249029/48229976-d78b2a00-e3a9-11e8-9589-aa8495db954b.png)

After Update:
![image](https://user-images.githubusercontent.com/40249029/48229995-e540af80-e3a9-11e8-9075-0cb74877ef1f.png)

I think that one can clearly see here, that the colliders (or at least their bounds) that are used to spawn the objects on the second image are some leftovers from the first image.

So, from my point of view, it is obviously related to the re-use of the tile, or maybe colliders itself are somehow recycled (either by your SDK or even Unity itself)?

**Comment by tab1887** [comment]
Another observation:

Added some debug output to ColliderModifier.cs
![image](https://user-images.githubusercontent.com/40249029/48231846-e1b02700-e3af-11e8-813e-0acffef4469f.png)

Results from first initialize
![image](https://user-images.githubusercontent.com/40249029/48231863-fb516e80-e3af-11e8-894c-1137ac19352c.png)

Results from UpdateMap
![image](https://user-images.githubusercontent.com/40249029/48231877-04dad680-e3b0-11e8-8102-b169ab87a0f3.png)

So, it seems like the VectorEntity already has a MeshCollider attached to it and now a second one is added without removing the old one.
Could that cause the mess?

**Comment by tab1887** [comment]
I did some further analysis and I think the main problem is the delayed execution of Object.Destroy() in Unity. According to the documentation this is not done immediately, but some only after the current Update loop (but in the same frame).

So, in ColliderModifier.cs in method RemoveColliderFrom(VectorEntity ve) the Destroy is triggered, but not executed. When the SpawnInsideModifier is run in the same Update loop, it will have two colliders per VectorEntity and likely choose the old one.

From my point of view the solution needs two parts:

1. Disable the old collider before calling Destroy, so that it does not affect raycasting anymore.

![image](https://user-images.githubusercontent.com/40249029/48378193-5b0d8980-e6d0-11e8-9809-1c4455697225.png)

2. In SpawnInsideModifier either get all colliders and use the bounds of the active one, or go with the mesh bounds as you suggested.

![image](https://user-images.githubusercontent.com/40249029/48378172-4a5d1380-e6d0-11e8-9d7e-448fd280d3ab.png)

**Comment by brnkhy** [comment]
@tab1887 sorry about the loong silence. I only now had a change to check this again, changing to mesh bounds seems to work fine and removed the collider dependency of spawn inside modifier so I pushed it here; https://github.com/mapbox/mapbox-unity-sdk/pull/1247
hopefully fix will be in very soon. 
Thanks for all feedback @tab1887!

**Comment by tab1887** [comment]
Hi @brnkhy ,

many thanks for the update.

I'm not sure if your submitted fix is really fixing the issue completely. As I tried to elaborate in my previous post, the main issue is that you have two active colliders attached to the VectorEntity at the time when the SpawnInsideModifier executes (an old one, from the previous, recycled mesh, and a new one for the current mesh).
So, if you are now only changing the bounds for casting rays from the collider (most likely the first, old one) to the mesh, it will certainly improve the situation by casting rays in the correct area, but you still have that additional old collider active. If it randomly overlaps the new mesh bounds, rays will still hit the old collider, even if the new (current) collider does not cover the whole mesh-bounds area. So there is still a (small) chance to spawn objects outside of the current mesh's current collider.

I still believe that the additional disabling of the old collider as shown in my point 1. above (or something similar) should be part of the fix.

Maybe I can try to create a test case later to proof this.

**Comment by brnkhy** [comment]
@tab1887 I think you're right. My initial tests looked good when I wrote that but I can definitely recreate issue now. I really don't want to use `GetComponents` though (because of the cost) so I'll try to find another way I guess.

**Comment by brnkhy** [comment]
@tab1887 for some reason I'm having a little hard time creating this again so I couldn't test it very well but looks like DestroyImmediate works well in this case as well. And I mean `DestroyImmediate` on collider instead of `Destroy` (which waits for the end of the frame). Did a little search and looks like the main reason DestroyImmediate being not suggested is that it breaks the regular script call chain (and causing side effects because of that) but that shouldn't be a trouble in this case.
I pushed it in same branch #1247 ,. I'll test it more though and would be nice if you can test and let me know if it works on your end as well.

**Comment by tab1887** [comment]
@brnkhy sorry for the late reply - I was busy with other things.
I have tested your version successfully now. Thank you very much for taking the time to fix it!

**Comment by brnkhy** [comment]
oh no, thank **you** @tab1887 for all reports and testing! I really appreciate all the time and effort you put in this. 🙏
