### ISSUE TITLE
How to re-request a tile?

### ISSUE THREAD

**Issue by Naphier** [mapbox/mapbox-unity-sdk#1131]
* Unity version: 
  * Scripting Runtime Version: .Net 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: .Net 4.x
* Mapbox SDK version: v1.4.5
* The platform you're building to: Android / Windows
* A description of what you're trying to do: Re-request failed tile

Sorry I couldn't find information on this very easily. 

We're using a pretty basic implementation of a range tile provider. Oftentimes tiles will fail to download (seems like the timeout is global?) properly (HeightDataState, RasterDataState, or VectorDataState will be an Error). What's the easiest way for going about re-requesting specific tile? 

Thanks!

**Comment by brnkhy** [comment]
@Naphier I think this would be a nice helper function that we looked over. I'll look into it but meanwhile you can try using `TileProvider_OnTileAdded` and `TileProvider_OnTileRemoved` functions in `AbstractMap`. They are protected so you'll have to change them to public and I haven't tried this myself yet and it's not the most optimal solution for sure but I think it should work if you Remove and re-Add a tile. .

**Comment by ihachani** [comment]
Hi I am facing the same issue in a way. I want to reload failed tiles. If I change the method to public what should I do to rerequest for the failed tile.

By the way there is a class called `TileErrorHandler` can we use that class to re-request the failed tile.

**Comment by brnkhy** [comment]
@ihachani If you detect the failed tile, you probably have its tile id and you can use that to rerequest the tile with those methods. I'm afraid there's no built-in way to detect and rerequest at the moment though.
