### ISSUE TITLE
Get Walkable Space Within An Area

### ISSUE THREAD

**Issue by redwraith2** [mapbox/mapbox-unity-sdk#1133]
Hi,

Currently, I have a selector where you can input latlon coordinates and a square around those coordinates. Within these bounds, is there any way I can get the road objects within that small region (500x500 feet)? Also, is there any way I can get the walkable space, i.e. parks + roads?

I would like to spawn an exact number of objects in a specified region, and am trying to avoid spawning them in water, in buildings, etc.

Screenshot of two of the five placeholder items spawning in the water:
![screenshot_20181107-082311](https://user-images.githubusercontent.com/4700187/48144969-b3730000-e266-11e8-80c9-96df497eeba9.png)

Thank you.

**Comment by brnkhy** [comment]
@redwraith2 I think your best bet would be raycasting down in that area and place objects when it doesn't hit water or buildings (or base mesh). Of course to be able to do that, you'll have to create water/building layers, set them to proper Unity Layers etc.
Walkable area is kinda hard to define so I think it would be an easier approach to say not buildings/water etc.

**Comment by jordy-isaac** [comment]
@redwraith2 Please re-open if you have any further questions on this
