### ISSUE TITLE
Modifying Visible Buffer for Range Around Transform in code

### ISSUE THREAD

**Issue by TheCodeDestroyer** [mapbox/mapbox-unity-sdk#1136]
Hi!

I was looking around the documentation and couldn't find anything decent to my understanding on how I could maybe mutate `Visible Buffer` for `Range Around Transform` from a script, I would really appreciate an example or some pointer.

Thank you in advance!

**Comment by brnkhy** [comment]
@TheCodeDestroyer if you're using v2.0, there should be `SetExtent` and `SetExtentOptions` methods under `AbstractMap` class. You should be able to use those to change everything related to TileProvider
