### ISSUE TITLE
AR Worldscale Excamples need explanations

### ISSUE THREAD

**Issue by MarjanPl** [mapbox/mapbox-unity-sdk#1137]
Hi,
i just tested the AR Worldscale Examples in release 2.0 on an iPhone X with iOS 12.
Besides entering my own token in the setup window i didn't change anything.

When i go outside to test it (tried several locations) it seems that position, rotation and scale are rather off.

From the placed virtual buildings (transparent orange shader) i can hardly see what should be were.
Even if using the manual alignment example i am having a hard time. At least i can set the rotation there, but i think the complete scale of the augmentation is off by something between 30 - 50% (scaled down, it seems to small).

**As for the setup:**
- i used the development branch from this site.
- used Unity 2017.4.13f1 (also Unity 2018.2)
- used an IPhoneX with iOs 12
- iPhone has Wifi and Bluetooth and location services on
- location is in Berlin, tried last (52.544058, 13.415392)

**As for other information concerning AR WorldScale with Mapbox:**
- i tried to find info on the web, Youtube, map box site including this (https://www.mapbox.com/unity-sdk/maps/examples/world-scale-ar/)
- i tried other related tutorials, but the problem is, that either the map box version is outdated or the unity editor.
- there is a note that one has to add Layers to unity - tried that - but after checking some of the game objects still have wrong assignments. This is not an issue when downloading and using the whole project from GitHub and not the release unity package. Doesn't seam to make a difference, by the way.

**If i would guess...**
- the scaling issue could be either: in case you calculate something against iPhones screen size. Or because the maps here don't have the resolution you have in your area.
- the rotation issue: I have no clue. 

**Information and improvements of the following kind would be helpful:**
- what am i expected to see?
- what is the ground scanning / plane detection for? 
- the AR Plane seems to be at eye level but should be on the ground (but this is hard to tell)
- scrolling the map in the manual alignment example is not made for iPhoneX resolution. (scrolls faster than finger position, thus hard to use)
- Which script is dealing with positioning and rotating the AR Map? Are there public exposed fields in some scripts i should adjust?
- if Unitys location services are being used, can one swap them out against google maps or apples?

In the moment the AR Worldscale examples seem unusable to me.
Would be willing to help testing things here (my coding abilities are not good enough to help here)

Edit: might be related to: 
https://github.com/mapbox/mapbox-unity-sdk/issues/1128

**Comment by jordy-isaac** [comment]
@MarjanPl Thanks for the feedback! We really do appreciate it, and your detailed report on your experience is really helpful. You're right that the documentation could use a refresh. This is something that is planned. 

Currently,  We're working on implementing [ARFoundation](https://github.com/mapbox/mapbox-unity-sdk/issues/1100) into the SDK, and that means that the current AR solution, ARFoundation will be removed. Once we get this done, we'll be able to update the docs. There will undoubtedly be a lot of changes to document, including plane detection, positioning, and rotating that you mentioned in your ticket. I'm also planning on doing a more comprehensive getting started tutorial. 

The issues with alignment and rotation are also something that we're working on. Mapbox is going to be focusing on improving the localization of the device and objects in the AR space. Right now, world-scale AR is a bit limited due to this, and we understand to use location data in AR that this needs to improve. Thanks again for the report

**Comment by Aashish-1008** [comment]
Hey @jordy-isaac ,
Is support for AR Foundation & mapbox added ?

**Comment by Alvarden15** [comment]
Yeah, i'm having problems with the AR World Scale example, too. Except it doesn't load at all. In the editor, it works fine, but when i build and test it, it doesn't load.
As for my setup, it's this:
* Unity version: 2018.3
  * Scripting Runtime Version: .Net 4.X Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: .Net 4.X
* Mapbox SDK version: 2
* The platform you're building to: Android
I'm working with a Samsung S7, so there shouldn't be any problem, probably.

**Comment by Alvarden15** [comment]
Hope that update come soon.

**Comment by anandp803** [comment]
hey i am using mapbox AR with unity  for instantiating object as per location in AR but mapbox location accuracy is not good , can any one tell how i can accurate GPS location in map box .
I am making location based messaging App in AR.

**Comment by tpaslou** [comment]
Is there any update with explanations and the Worldscale example ? I m trying hard to just place some objects in specific longitude and altitude using ARCore and i am really confused . Any help would be much appreciated .

**Comment by ksi3321** [comment]
@jordy-isaac Any update on this thread?

**Comment by saszer** [comment]
just gonna ping this one up!

**Comment by josefsHD** [comment]
I would also love a more in-depth look at how to customise and use the world-scale AR example project. So much work seems to have gone into it but one page of high-level overview isn't enough to get started!

**Comment by mattmedlin** [comment]
Is there any update on the ARFoundation documentation? I am trying to use World Scale AR and the alignment is off and the gps says ignored.
