### ISSUE TITLE
How to get lat and lon when user click on map tiles in unity

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#1138]
Hi
I'm using map box unity sdk. I want to get the lat and long when user click on map tile. 

This my mapbox setting :
Basic Map
Camera Bounds Tile Provider 
Build Map at location

When I click on the map tile I'm able to get the corner lat and long of map tile. But I want to get precise Lat and long now matter user click anywhere on the map tile. 

Looking for help. any help would be much appreciated.

**Comment by josh-windsor** [comment]
```
if (Input.GetMouseButtonDown(0))
{
    Vector3 mousePosScreen = Input.mousePosition;
    mousePosScreen.z = _mainCam.transform.localPosition.y;
    Vector3 location = _mainCam.ScreenToWorldPoint(mousePosScreen);
    Vector2d coordinate = _mapRef.WorldToGeoPosition(location);
    Debug.Log(coordinate.x + ", " + coordinate.y);
}
```
I use this, pretty sure it's in one of the demos. Hope this is what you are looking for?
