### ISSUE TITLE
How can I change style of the map In runtime.

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-unity-sdk#114]
I want to change the MapImageFactory.mapid, but how can I change in runtime?

**Comment by david-rhodes** [comment]
Which version of the SDK are you using? With v0.5.1, you can change the `MapId` and call `Update` in the `MapImageFactory`. With v1.0, we have plans to refactor the Map Factory Framework to better support runtime customization. In the meantime, you can add some public methods to `MapVisualizer` to `DisposeAllTiles` and `LoadAllTiles`. Dispose all tiles, change your `MapID`, then reload all tiles. It's a bit messy, but should work in the meantime.

**Comment by NinjaDanz3r** [comment]
Is this workaround still possible in 1.1.0? I've used it for a while but it seems to have broken with the 1.1.0 update.

**Comment by david-rhodes** [comment]
@NinjaDanz3r For clarification, you mean 1.1.0, not 1.0.0? Was this working in v1.0.0? If so, which technique did you use? `Update` or `Dispose/LoadAllTiles`?

**Comment by NinjaDanz3r** [comment]
Dispose/LoadAllTiles, and I was running the 1.0.0 available from here:
https://www.mapbox.com/install/unity/.

**Comment by david-rhodes** [comment]
@NinjaDanz3r I don't think we changed anything that would have broken your code. But we never added those methods ourselves, so if you updated then your class was likely overwritten, right?

**Comment by david-rhodes** [comment]
In `develop` you can now `Initialize` a map more than once (to change location, MapId, zoom level, etc). `MapId` and `Factories` are now public, so you can set those and then call `Initialize` in your map.

**Comment by piyushvishwakarma** [comment]
i used two Image factories, here i pass map style id as custom map type
Now i want to use two map as I have two style ids
how can i fetch one map style with the ID dynamically and show it in the scene?
Example: I need to use couple of maps for day and night cycles(for day map1, for night map2). Now I am trying clearing the cache to load another id. Could you please guide me in which way I have to do it so as to use both the maps?

**Comment by david-rhodes** [comment]
First of all, now that we support reinitializing a map, I recommend just using one `MapImageFactory`. In your map reload script, have a reference to the `MapImageFactory`. Change it's `MapId` before calling `Initialize` in `AbstractMap`. That's it!

As an aside, you don't have to clear the cache, as each id gets its own cache allocation.

**Comment by piyushvishwakarma** [comment]
Thanks David now its working.....

**Comment by stars66** [comment]
I want to change map style in runtime. I used MapImageFactory.
mapImageFactory._customStyle.Id = my_map_style;
But nothing happens.
How can I do it?

**Comment by RomanAtBrief** [comment]
Hi @david-rhodes 
I am trying to do the same thing. How would you change Abstract Map parameters from other script?
Say Image Data Source or Switching on and off 3D buildings?
Thank you

**Comment by RomanAtBrief** [comment]
I found all other these. Looks like it is what I need. How to use them from within separate Monobehavior Script?
https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.IImageryLayer.html

**Comment by arifduman** [comment]
Here you go dude!
`AbstractMap.ImageLayer.SetProperties(ImagerySourceType.MapboxSatelliteStreet, true, false, false);`

**Comment by steve6t6** [comment]
Hello, running into this issue in 2024, I have an Abstract Map reference, how do I set both the layer source and the tile set ID (tilesetid) to my custom map style? 

The Abstract map gives me access to the ImageLayer and the ability to set source, bit not tile set.

**Comment by vector-8** [comment]
You could use **SetLayerSource**, e.g.
`Map.ImageLayer.SetLayerSource(Mapbox.Unity.Map.ImagerySourceType.MapboxStreets)`
