### ISSUE TITLE
Import new style

### ISSUE THREAD

**Issue by DanieleSuppo73** [mapbox/mapbox-unity-sdk#1141]
Hello,
I've just downloaded a json file for styling from Maputnik.
However when I try to upload it (from my local drive) to Mapbox studio I get this error message
"Invalid source URL".
Why?
Thank-you

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by twelch** [comment]
@DanieleSuppo73 this sounds unrelated to Unity SDK, probably a support@mapbox question.  Hard to tell without you posting your style doc.
 
I would assume (I'm not with Mapbox) that Studio is strict about what datasources it will allow, probably only Mapbox hosted sources.  If you have self-hosted sources then you likely need to self-host your style doc as well and tell the Unity SDK to use it.  See my recent answer over here -- https://github.com/mapbox/mapbox-unity-sdk/issues/1139

**Comment by DanieleSuppo73** [comment]
You are totally right, it's not the right place for my post.
Anyway Maputnik should work perfectly with Mapbox (it require the Mapbox token too..).
Many thanks for your reply!
