### ISSUE TITLE
Good job but...

### ISSUE THREAD

**Issue by DanieleSuppo73** [mapbox/mapbox-unity-sdk#1143]
Ok, you at Mapbox did a really good job with your maps. Nice, clean, and easy to use (furthermore for free!). Really many thanks!
But...
When you move to Unity it seem to me that you did a lot of unnecessary code, to do the most basic stuff.
Please forgive me but most of your C# code is quite useless, redundant and sometimes not working as expected (for example your script "QuadTreeCameraMovement"... I modified it and now it's working but in my opinion is a bit a shame to write such a code).
Not to mention most of all your other scripts... too long to read and to debug, with no reason.
For sure anyone could do it's own script with your API but, you know, if some code is directly delivered from the provider the 1st basic approach is to get it as a bible...
Anyway, many thanks!

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Thanks for your feedback. We'd welcome any PR's if you would like to refactor it and make improvements.
