### ISSUE TITLE
Mapbox AR world scale building on android

### ISSUE THREAD

**Issue by tyrroncondo14** [mapbox/mapbox-unity-sdk#1145]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by tyrroncondo14** [comment]
I follow the documentation in https://www.mapbox.com/unity-sdk/maps/examples/world-scale-manual-align-ar/ but when I build it on my android phone it goes like this. I'm trying to use my phone's camera.

![image](https://user-images.githubusercontent.com/29406798/48977732-2986bc00-f0db-11e8-91c1-f3042bd689ef.png)

**Comment by tyrroncondo14** [comment]
![ar](https://user-images.githubusercontent.com/29406798/50354088-4c46ac00-0585-11e9-87f7-d1adb087d214.jpg) @jordy-isaac sorry for the late response. It works! But my my problem is why it is not opening my device camera?

I try detecting a ground plane and allowing permission to use my device camera,location, etc.

**Comment by tyrroncondo14** [comment]
I solve it by installing ARCore by google in the app store. Thanks by the way

**Comment by mmanurung** [comment]
Hi, i want to ask
If i'm using unity 2018 and mapbox unity newest sdk
and i want to try worldscale ar
but my phone isn't supported by arcore google

at the end, the apk succedd installed on my phone, but it went black screen right after the 'unity' logo come

is there any solution for this?
all my fam's phone sadly don't supported by arcore
right now i'm reinstalling unity 2021, idk if it will make change
