### ISSUE TITLE
Change Point of Interest layer during runtime.

### ISSUE THREAD

**Issue by atxkirl** [mapbox/mapbox-unity-sdk#1149]
I'm new to this SDK, is it currently possible to change the point of interest layer during runtime? I want to have quests that show specific location types (example: a quest that requires a player to go to a park, so I only want to show park POIs)

**Comment by jordy-isaac** [comment]
Hi @atxkirl 

[Runtime editing](https://blog.mapbox.com/let-play-drive-your-game-styling-8541057764a6) is possible if you're using [version 2.0](https://www.mapbox.com/install/unity/) of the SDK. You'll want to check out the [API doucmentation](https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.VectorLayer.html) as well.

**Comment by atxkirl** [comment]
> Hi @atxkirl
> 
> [Runtime editing](https://blog.mapbox.com/let-play-drive-your-game-styling-8541057764a6) is possible if you're using [version 2.0](https://www.mapbox.com/install/unity/) of the SDK. You'll want to check out the [API doucmentation](https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.VectorLayer.html) as well.

Hi, I'm not sure what function to call to change toggle active POI layers... Sorry if I'm being blind but I'm quite lost right now

**Comment by jordy-isaac** [comment]
HI @atxkirl Take a look at the documentation for [`IVectorDataLayer`](https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.IVectorDataLayer.html). I think this might be wahat your looking for.
