### ISSUE TITLE
Mapbox:Json namespace missing

### ISSUE THREAD

**Issue by derekdominoes** [mapbox/mapbox-unity-sdk#115]
I just got a clean develop branch and Mapbox:Json namespace is used a lot but never implements. As such, opening examples (tried LocationProvider) in Unity fail for build reasons.

**Comment by Alexphauge** [comment]
You have to run the update-mapbox-unity-sdk-core.bat file in the project folder, I seem to remember that fixes a lot of stuff from the get-go.
