### ISSUE TITLE
Request feature mapbox in unity

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1153]
Related to other issue #1152 , as im beginning with unity, i cant get using mapbox in unity.
Perhaps an easier way should be, to create in unity a floor ( flat cube) with some dimension: ex: 100 m x 200 m ( rectangle). And then put in its surface a map with a center location position ( ex; i want in lleida i select the center of the area (42. long , 0.6 lat) i want to add to unity). So this map would be downloaded and used in the game. Then in the map settings add layers and in my case 3dbuildings and names of streets and some pois ( all kind of personalization).

So in the floor with map, would be easier to add player character and other objects to play.

Also would be nice that pois or other names would be editable ( choose which names appear and what doesnt). Ex: select 10 poi that would appear, the others dont.

Thanks

**Comment by jordy-isaac** [comment]
Hi @ejgutierrez74 I would suggest taking a look at the following [tutorial](https://www.mapbox.com/help/create-a-map-in-unity/) and [video](https://www.mapbox.com/unity-sdk/maps/examples/poi-placement/#create-a-custom-scene-with-pois). 

If you have any additional questions, please email us at help@mapbox.com
