### ISSUE TITLE
iOS Unity Cloud build .h file not found

### ISSUE THREAD

**Issue by inkipinki** [mapbox/mapbox-unity-sdk#1155]
* Unity version: 2018.3.0b9
  * Scripting Runtime Version: 4.x equivalent
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net Standard 2.0
* Mapbox SDK version: 2.0.0
* The platform you're building to: iOS
* A description of what you're trying to do: Build the project in unity cloud build.
* Steps to recreate the bug if appropriate:

- Create a new 3D project in Unity 2018.3.0b9
- Import mapbox 2.0.0 unitypackage
- (in iOS build setting):
- Disable multithreaded batching
- Set all signing info (in unity and in cloud)
- Set minimum iOS version to 9.0
- Create a new empty scene and add that one only to the build settings
- Upload to bitbucket.
- Start build in cloud and it fails with the following 2 errors.

**/BUILD_PATH/overlandbound.ob1.ob1-ios-clean-test/temp.XXXXXX20181205-3269-1w022yp/Libraries/Mapbox/Core/Plugins/iOS/MapboxMetricsClient.m:1:9: 'MapboxMobileEvents/MapboxMobileEvents.h' file not found**

**/BUILD_PATH/overlandbound.ob1.ob1-ios-clean-test/temp.XXXXXX20181205-3269-1w022yp/Libraries/Mapbox/Core/Plugins/iOS/MapboxMetricsClient.m:1:9: 'MapboxMobileEvents/MapboxMobileEvents.h' file not found**

* Links to your logs are also helpful: 
https://pastebin.com/dymbKrKz

lines 964 and 966 are the errors.

**Comment by jordy-isaac** [comment]
@inkipinki Are you able to build to iOS without using cloud build? I was looking at the logs and the [documentation for cloud build](https://developer.cloud.unity3d.com/support/faq/) and it sounds like our maps sdk might not work straight away. It also appears unity is open to adding support if you send them logs. I hope this helps.

**Comment by inkipinki** [comment]
I can build without cloud build, but that is a major setback if the only way.

What points you to "it sounds like our maps sdk might not work straight away" ?

inki
________________________________
