### ISSUE TITLE
Create Buildings any where in the city 

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1158]
* Unity version: 2017.4.10f1
  * Mapbox SDK version: 1.4.4
* The platform you're building to: windows
* A description of what you're trying to do: I want to add the possibility to add buildings, roads, or any object any where in the city with mapbox in unity. Any sugguest?

**Comment by jordy-isaac** [comment]
Hi @roura-12 I'd suggest upgrading to [v2.0](https://www.mapbox.com/install/unity/) and then checking out the [example scenes](https://www.mapbox.com/unity-sdk/maps/examples/). They will show to visualize roads, buildings, and how to use custom data. If you have any further questions you can get in touch with [Mapbox support](https://www.mapbox.com/contact/support/).
