### ISSUE TITLE
Problems with Mapbox Telemetry on mobile

### ISSUE THREAD

**Issue by Anheurystics** [mapbox/mapbox-unity-sdk#1160]
* Unity version:  Unity 2018.2.0f2
  * Scripting Runtime Version: .NET 3.5 Equivalent
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to: Android and iOS
* A description of what you're trying to do: Both using and disabling mapbox telemetry
* Steps to recreate the bug if appropriate:
iOS: Having telemetry enabled (which seems to be by default) will cause random crashes on iOS. The stacktrace mentions UnityWebRequest.
Android: Trying to turn off telemetry throws the following error:
```
E Unity   : java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.telemetry.location.LocationEngine.removeLocationEngineListener(com.mapbox.services.android.telemetry.location.LocationEngineListener)' on a null object reference
E Unity   :      at com.mapbox.services.android.telemetry.MapboxTelemetry.shutdownTelemetry(MapboxTelemetry.java:596)
E Unity   :      at com.mapbox.services.android.telemetry.MapboxTelemetry.flushEventsQueueImmediately(MapboxTelemetry.java:526)
E Unity   :      at com.mapbox.services.android.telemetry.MapboxTelemetry.pushTurnstileEvent(MapboxTelemetry.java:540)
E Unity   :      at com.mapbox.services.android.telemetry.MapboxTelemetry.setTelemetryEnabled(MapboxTelemetry.java:330)
Unity   :      at com.ma
```

Addendum: The iOS also seems to crash randomly with an "EXC_BAD_ACCESS" when quickly moving and zooming the map around.

**Comment by jordy-isaac** [comment]
@Anheurystics I haven't been able to reproduce this. Do you have a min test case or steps to reproduce?
