### ISSUE TITLE
mapbox-unity-sdk_v2.0.0.unitypackage: no VECTOR layer section

### ISSUE THREAD

**Issue by liuty10** [mapbox/mapbox-unity-sdk#1166]
I am using unity2018.2.14f1 and I have downloaded the mapbox-unity-sdk_v2.0.0.unitypackage.

I try to follow the tutorial below: Build a Unity 3D game with Mapbox (15/29) Points of Interest and Game Object Modifiers
Here is the link: https://www.youtube.com/watch?v=vFrUseeVn_s)

Problem:
I can't find the "VECTOR" layer section when I imported the "mapbox-unity-sdk_v2.0.0.unitypackage".

Why it's like that? I can't follow the tutorial step by step. In the tutorial above, it uses "mapbox-unity-sdk_v1.4.1.unitypackage", but I also have trouble with the 1.4.1 source code. Can anyone help me with this problem?

**Comment by jordy-isaac** [comment]
Thanks for the ticket. That particular tutorial will was created by Devslopes. Given the scope of the tutorial, it's unlikely that it will be updated, but they have a [free version of the course on Udemy](https://www.udemy.com/mapbox-unity-3d-essentials/) with a Q&A section directly with the instructors. They might have new info to provide.
