### ISSUE TITLE
Hiccups when redrawing tiles

### ISSUE THREAD

**Issue by asger600** [mapbox/mapbox-unity-sdk#1172]
Hey
I'm experiencing pretty big framedrops when i try to do a zoom on a worldmap.
It happens everytime when mapbox loads the next set of tiles, and it seems to be related to garbage collection. 
I'm using `_map.UpdateMap(latlon, zoom); `to redraw the map when zooming.

Unity 2018.2.8f1
Mapbox v 2.0

**Comment by asger600** [comment]
Here's a screenshot from the profiler
<img width="840" alt="screenshot 2018-12-12 at 09 54 01" src="https://user-images.githubusercontent.com/18396761/49857965-14f13600-fdf4-11e8-80db-39ed820ea2af.png">

**Comment by asger600** [comment]
ok, I dug a little deeper.
It seems to be this call `_rasterData.LoadImage(data);` in `SetRasterData()` that causes the hiccups. It also seems to be a common unity issue, not being able to load images without stalling the main thread.

**Comment by jordy-isaac** [comment]
@asger600 Thanks for the context. We'll keep looking into ways to improve performance moving forward.
