### ISSUE TITLE
World Scale AR NOT working

### ISSUE THREAD

**Issue by AbdullahBurhan** [mapbox/mapbox-unity-sdk#1173]
* Unity version:  **Unity 2018.2.8f**
  * Scripting Runtime Version:  **.NET 3.5**
  * Scripting Backend: **Mono**
  * Api Compatibility Level: **.NET 2.0 subset**
* Mapbox SDK version: **v.2.0.1**
* The platform you're building to **Android**
* A description of what you're trying to do:
I am building the world scale AR scene to android, but what I get in the log are error messages telling me that the "Minimum movement not yet met".
and there is a difference between the AR delta and the GPS delta.
knowing that I made sure that the references are assigned properly in the scene, and I am not using internet connection during the test.
Any help Please!
![notyetmet](https://user-images.githubusercontent.com/41993944/49886993-37af3900-fe4c-11e8-9545-ae9b8adaa6ef.jpg)

**Comment by jordy-isaac** [comment]
@AbdullahBurhan Can you let us know a bit more about how to reproduce this? Did you use the example scene provided in the SDK? What happens if you try again on the device with a data connection?

**Comment by AbdullahBurhan** [comment]
@jordy-isaac Yes, I have used the example scene from the provided SDK without any changes, and I have tried it again with internet connection but it is still giving me the same messages.

**Comment by AbdullahBurhan** [comment]
https://www.youtube.com/watch?v=9h-g2mqEf6w&feature=youtu.be

Here I am using an internet connection, but the problem still occurs.

**Comment by AbdullahBurhan** [comment]
Any help !

**Comment by MarjanPl** [comment]
i am having this too - in germany. i guess what you see in the log is not an error. It is just a hint.
The template will only update your location once you moved x far. Means, if you stand still nothing happens and you get this message continuously. you need to walk. quite far. lets say 10 meters at least. in between however, you get this message.

a difference in gps and movement delta is normal and desired. read through this, it is explained here: https://www.mapbox.com/unity-sdk/maps/examples/world-scale-ar/

The current world scale AR example did not work for me on an iPhone X in Berlin. Scale seems to be off as well as rotation and position.
An offset of around 10 meters in position and several degrees of rotation plus the scale issue makes it completely unusable for me.
i also tried the world scale manual alignment example. here i can try to adjust this values. but still it is impossible for me to correctly map anything here.

Thus i stopped looking Ito this for now and wait for a release which at least uses ARFoundation in Unity and hopefully a better Example.

As for Android: Somewhere in your settings - don't remember were - you can toggle on higher precision for location. This down not exist on iOS. give it a try.

Other than that i fear - GPS in Europe is way less precise than in the US.

**Comment by Alvarden15** [comment]
Yeah, i'm having this problem too. Not sure if it's that or something else. I'm currently at Peru, by the way.

**Comment by DanielOS96** [comment]
Yeah also having the same problem here.

**Comment by ibrews** [comment]
any fix?

**Comment by cquentin48** [comment]
I have tried to launch the mapbox sdk world scale example and it crash directly and returned to the desktop home without telling me what's wrong.

**Comment by cquentin48** [comment]
I have tried your example of world scale AR while adding the missing content documented here : "https://docs.mapbox.com/unity/maps/examples/world-scale-ar/" and it crash!
Could someone help me?

**Comment by Alvarden15** [comment]
Ok, it seems that i'm not the only one with this type of problem.
Hope there will be another update for the sdk.

**Comment by cquentin48** [comment]
For me it was solved when I built it. There is just the problem of arcore from google which I can't use because of my phone version, which is weird because my phone version is above android 7.0.

**Comment by huix9527** [comment]
This product is a total shit, never works, shut the stupid company down.
