### ISSUE TITLE
Mapbox Unity AR with Image Targets

### ISSUE THREAD

**Issue by BoDaCat** [mapbox/mapbox-unity-sdk#1180]
I have a need to try and integrate Mapbox with Image Targets for augmented reality instead of the plane detection. Has this been done before? Are there any suggested ways on how to accomplish this? Possibly with Vuforia?

**Comment by jordy-isaac** [comment]
You could likely use Vuforia for image tracking and this instantiate a map prefab when the image is detected.

**Comment by BoDaCat** [comment]
This is what I thought as well. My issue is when the prefab instantiates on the image, the 3D terrain feature does not seem to work. It works when using the camera provided by Mapbox and the suggested implementation with plane detection, but not with Vuforia's camera. Am I missing a step somewhere possibly?

**Comment by AbdullahBurhan** [comment]
@BoDaCat , try to change the "Clip_TerrainMaterial " material in the MapRoot gameobject ---> Generals--->Others --->Tile Material .
Because this shader's material is clipping the map when you are using Vuforia camera.
