### ISSUE TITLE
.gitignore vs Unity project's Mapbox key

### ISSUE THREAD

**Issue by jskubick** [mapbox/mapbox-unity-sdk#1181]
What do I need to add to my Unity project's .gitignore file to guarantee that my own Mapbox key will absolutely, positively, NEVER accidentally end up getting exposed to the world if I eventually decide to share the project on Github?

**Comment by jordy-isaac** [comment]
@atripathi-mb Do you know what needs to be added or if the default gitignore will filter out the api key?

**Comment by atripathi-mb** [comment]
the deafult gitignore in our sdk ignores autogenerated files, so it should ignore the `Assets\Resources\Mapbox` folder. 

To be safe, you can add the folder explicitly to the gitignore.

**Comment by jskubick** [comment]
Cool, thanks!
