### ISSUE TITLE
Possible bug in CitySimulatorMap

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1185]
* Unity version:2017.4.17 
  *Mapbox SDK version:2.0 
* The platform you're building to:
* A description of what you're trying to do:
With city simulator map i put a character in one position ex: 0,0,0. I have the setup apparently correct as it works perfect with mapbox terrain and terrain with elevation layer. But if i switch to flat terrain, the character falls passing the map as a ghost come across a wall. As told before i have the add collider option enabled, and with other options it doesnt happen. I do can change styles but always with elevation terrain, i cant use a flat terrain. 
Id need to test flat terrain as my character moves backwards if he find some slopes
Either if i use custom or mapbox terrain, if i use flat terrain the character falls.
Again using either custom or mapbox terrain , Low polygon terrain and terrain with elevation works
Globe Terrain works very strange.
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
@ejgutierrez74 So that we can better understand what's happening here. Can you post some screenshots of your settings and maybe a video of what's happening?

**Comment by ejgutierrez74** [comment]
Sorry @jordy-isaac but im a teacher and these days ive been very busy with my students....

Here two examples ( with same configuration, one video the character falls down like no floor in the map, and the other works in expected way, the character falls till the floor ):

https://drive.google.com/open?id=1Fuy8JcPFvpS2B3eJgqXJWmvZFG7OvrOW
https://drive.google.com/open?id=1hcKDCaSUCl7amHF6bieJr023nJbZhgSB

**Comment by ejgutierrez74** [comment]
Sorry @jordy-isaac do you have watched the videos ? enough or want any information ??

Seems related to #1234 

Thanks

**Comment by sumitsingh47** [comment]
Yes , i am also facing this issue when selecting flat terrain. I have checked someone told here that after uncheck and check Add Collider by manually , it adds the collider.
Conclusion:- the methods public override void UpdateProperty(UnityTile tile) is not called when selecting flat terrain.
Please suggest any solution if anybody found. Thanks in Advance.
