### ISSUE TITLE
Best way to record state of spawned objects

### ISSUE THREAD

**Issue by 1701Tiberius** [mapbox/mapbox-unity-sdk#1186]
I am spawning POI objects in the world (something like Pokestops in Pokemon Go) that need to know when they have been hit and not allow a player to hit them a second time for a preset duration.  I can get all the time stuff to work, but am trying to figure out the best way to know that I have already hit this object when a user restarts the game (i.e. carry a state over if a user restarts their session).

My idea was to store the lat long coords and time hit of every object the player hits in the world, then when a new POI object loads, check the lat longs against it's current position and then check to see if enough time has elapsed. The issue with this is that the lat longs do change (when getting the Vector2d from the map object) - so I know I would have to apply some kind of fudge factor to checking the location and identifying the object.

I know there might be a better way to handle this, so I wanted to ask.

Thanks!

**Comment by jordy-isaac** [comment]
@1701Tiberius I would suggest using an AddMonobehavioursModifier to handle the logic and track the state of the POIs that you're spawning in.
