### ISSUE TITLE
Update map when a player's lat long coordinates are changed

### ISSUE THREAD

**Issue by 1701Tiberius** [mapbox/mapbox-unity-sdk#1187]
The basic idea is that a player can move a joystick and travel through the world (as far as they want), starting at the current GPS location. What is the best way to implement this with a location provider so that the map updates as the player moves?

Thanks!

**Comment by heath3n** [comment]
You can easily modify the `LocationBasedGame` template to achieve this:

1. In the `Map` object under the `Abstract Map` component, set `Extent Options` > `Range Around Transform` and set the buffers to something small initially (`2`, perhaps) so you will be able to see that the map actually does load as you move. Set `Target Transform` > `PlayerTarget`.
2. Create a simple movement script like you would for any Unity object, and attach it to `PlayerTransform`. Mine looks like this:
```C#
using UnityEngine;

public class DebugMovement : MonoBehaviour {
    public float moveSpeed = 3.0f;

    void Update() {
        var x = Input.GetAxis("Horizontal") * Time.deltaTime * 200.0f;
        var z = Input.GetAxis("Vertical") * Time.deltaTime * moveSpeed;

        transform.Rotate(0, x, 0);
        transform.Translate(0, 0, z);
    }
}
```
3. On the `PlayerTarget` object, disable the `Immediate Position With Location Provider` and `Rotate With Location Provider` scripts.

I hope this was helpful.

**Comment by 1701Tiberius** [comment]
Thank you! Much appreciated!
