### ISSUE TITLE
"GPS disabled" on android

### ISSUE THREAD

**Issue by Natatem00** [mapbox/mapbox-unity-sdk#1188]
Hello. I have a problem. When I use "LocationBasedGame" game on my android phone: it's give me my cuurent position, but after 10-15 secconds I see the inscription "GPS disabled" and it's begin throw me in different positions on the map. What's wrong?

**Comment by jordy-isaac** [comment]
Hi @Natatem00 What version of the SDK are you using and what device are you running the game on? Can you please send us some more info to help@mapbox.com and we'll look into it for you.
