### ISSUE TITLE
Is there a way to get the names and locations of nearby cities so that I can drop them into an onscreen compass locator?

### ISSUE THREAD

**Issue by 1701Tiberius** [mapbox/mapbox-unity-sdk#1189]
Wanting to drop them into an onscreen compass locator. The caveat: these cities may not be in a tile in Unity (in other words they are distant, like for instance, we might be in Austin, TX, but I want to be able to display a tick (and maybe a distance) for every city within 100 miles, like San Antonio, TX for instance.

Thank you!

**Comment by 1701Tiberius** [comment]
Wanting to drop them into an onscreen compass locator. The caveat: these cities may not be in a tile in Unity (in other words they are distant, like for instance, we might be in Austin, TX, but I want to be able to display a tick (and maybe a distance) for every city within 100 miles, like San Antonio, TX for instance.

Thank you!

**Comment by jordy-isaac** [comment]
@1701Tiberius You may want to look into the [Tilequery API](https://www.mapbox.com/help/tilequery-api-playground/) for an implementation such as this.
