### ISSUE TITLE
Value returned by GeoToWorldPosition changes unexpectedly

### ISSUE THREAD

**Issue by jskubick** [mapbox/mapbox-unity-sdk#1195]
Assume that "map" is a reference to the AbstractMap in ARTabletopKit -> MapHolder -> MapRoot

I created a new MonoBehaviour & attached it to ARTabletopKit -> MapHolder. Let's call it "TestBehavior"

In TestBehavior.Start(), I'm executing:

    // private Vector3 pos is an instance variable
    pos = map.GeoToWorldPosition(new Vector2d(37.784179, -122.401583), false);
	
... and pos.y ends up being equal to 0.

In TestBehavior.Update(), I'm executing:

    void Update() {
        frameNumber++;
	    Vector3 currentPos = map.GeoToWorldPosition(new Vector2d(37.784179, -122.401583), false);
	    if (pos.y != currentPos.y)
	        Debug.Log($"world changed position to {currentPos.y} during frame {frameNumber}");
		
... and sometime around the 18th-20th time Update() executes, the value of currentPos.y suddenly changes from 0 to -1 (only y changes... x and z are unchanged).

What Event do I need to subscribe to in order to be notified when something happens that would cause the value returned by GeoToWorldPosition() for a given latitude & longitude to change?

(for what it's worth, I'm already subscribing to AbstractMap's OnInitialize, OnMapRedrawn, and OnUpdated... the only one that fires is OnInitialize, and IT fires sometime between Start() and the first frame for which Update() executes... and as noted, the change isn't observed until 18-20 frames later).

Also... what does the bool argument in GeoToWorldPosition actually DO? The API docs for AbstractMap.GeoToWorldPosition() say "if set to true will return the terrain height (in Unity Units) at that point", but when I've tried using it, the bool argument's value doesn't actually seem to make any difference to the x, y, and z values in the Vector3 it returns -- they're the same regardless.

**Comment by brnkhy** [comment]
Hey @jskubick, really sorry I somehow missed this one. Have you been able to find what the problem is?
Last boolean in 'GeoToWorldPosition' should be height flag as you noted but might be zero regardless if you're using flat maps for example.
