### ISSUE TITLE
GPS Disabled

### ISSUE THREAD

**Issue by AbdullahBurhan** [mapbox/mapbox-unity-sdk#1201]
Unity version: Unity 2018.2.8f
Scripting Runtime Version: .NET 3.5
Scripting Backend: Mono
Api Compatibility Level: .NET 2.0 subset
Mapbox SDK version: v.2.0.1
The platform you're building to Android.
I am getting a 'GPS disabled' message when I open the WorldScaleAR scene on my Android device.

**Comment by jordy-isaac** [comment]
@AbdullahBurhan Please email more info about your device, as well as your build and player settings to the support team at support@mapbox.com and we can help you troubleshoot.

**Comment by lMasc** [comment]
im getting the same error/message too in unity 2018.3
