### ISSUE TITLE
Any way to convert from Mapbox terrain mesh to Unity terrain?

### ISSUE THREAD

**Issue by colin-young** [mapbox/mapbox-unity-sdk#1206]
I am attempting to use an asset (EasyRoads3D) that ~~requires~~ works better with a Unity terrain object. Unfortunately Mapbox generates a mesh to represent terrain. Is there any way to convert from the mesh to the Unity heightmap representation? It doesn't seem to me that it should be all that difficult of a problem once you understand the scaling that's needed, but I can't find much information on doing that, and all the mesh to terrain converters I've found are edit-time not runtime.

Is there a way to create a TerrainFactory that would output a Unity terrain instead of a mesh?

**Comment by jasonhbartlett** [comment]
@colin-young I wanted to do this too.  There are some tools outside of Unity that will give you raw height map data of any gps location which you can use to then generate the terrain object in Unity.  Check out this site: [Terrain.Party](https://terrain.party/) 
This is another cool terrain tool I found, though I haven't had a chance to play with it too much. [L3DT](http://www.bundysoft.com/docs/doku.php?id=l3dt:about)
I bet there is a way to do this with Mapbox, but it would take some clever Unity tricks I'm sure.

**Comment by colin-young** [comment]
Thanks for the suggestions. I've looked at terrain party before, but last time I checked they had no data for the area I'm interested in, or the data they have is at too coarse an interval (Florida, which is, literally, flatter than Kansas). I believe they have 10m resolution and the area I'm modeling is less than that, and getting the minor variations correct is important, which Mapbox is able to do. Plus there's the issue of getting my data translated from lat-long to the Unity coordinates, which Mapbox does a great job of, even if I don't always understand the where/how.

At this point the terrain is the least of my problems since I can work around it if necessary. It's just one of those things that would be nice to check off my list

**Comment by brnkhy** [comment]
@colin-young we haven't tried using unity terrain with SDK so far and I'm afraid I didn't have any quick solutions for you at the moment. Looks like terrain object has `TerrainData.SetHeights` method though (and we already have that array) so it might be possible to make it work I guess. I'll try to look into this some time, let's keep the ticket open.

**Comment by colin-young** [comment]
Thanks @brnkhy . I'm sure there are good and valid reasons why Mapbox decided to create a mesh for the terrain and I'm sure there are good and valid reasons why EasyRoads3D is built to use Unity Terrain. It's my misfortune to have fallen into that gap. I don't have a good understanding of Terrain at the moment, so I'll need to educate myself about that first (how do I map the XZ bounds of a mesh to the bounds of a Terrain, then mapping individual Terrain pixels to Mapbox heights, etc.)
