### ISSUE TITLE
Not finding google_ar_required.aar and google_ar_optional.aar files needed for ARCore support

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1208]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.4.17f
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to:Linux
* A description of what you're trying to do:
Just to make the project cleaner i moved some folders into a Mapbox folder:
![image](https://user-images.githubusercontent.com/11474846/50538585-e6a08400-0b71-11e9-9830-fc0709735471.png)

* Steps to recreate the bug if appropriate: Import mapbox sdk to your project, then put all the things in a folder ( just to make it cleaner). You move the files inside unity, so it has to be aware of links and files moved.
* Links to your logs are also helpful: 
![image](https://user-images.githubusercontent.com/11474846/50538611-30896a00-0b72-11e9-9e92-0d57ff30abbb.png)

It should be aware when you change files...perhaps changing configuration item  ??

Also would be nice to delete all the AR related things if you dont want to use them....

The error cames in building and run, if you execute inside unity ( play), it works...If you build the scene and then generate and executable file and then go to file manager and run it, it works... Its only build &run that doesnt work...

Thanks

**Comment by ejgutierrez74** [comment]
??

**Comment by jordy-isaac** [comment]
You'll need to remove all AR related files or folders if not using AR.

**Comment by ejgutierrez74** [comment]
@jordy-isaac but the problem here are two:
1 - One possible bug with structure of folders, when you move them inside unity, gives the commented error.

2 - If you try to remove all ar related files, it gives an error as reported above and also in other issue ive read..perhaps another bug.....Its not easy or not possible to delete ar related files.

Thanks

**Comment by ElRoberto13** [comment]
HI! I finally figured out how to solve this bug. In the Google AR Core SDK folder, find a file called BuildHelper.cs. Then find the location of the files google_ar_required.aar and google_ar_optional.aar. Modify lines 61 and 62 in BuildHelper.cs to reflect the true location of these two files. Works for me so far!

**Comment by johnson-52197** [comment]
> HI! I finally figured out how to solve this bug. In the Google AR Core SDK folder, find a file called BuildHelper.cs. Then find the location of the files google_ar_required.aar and google_ar_optional.aar. Modify lines 61 and 62 in BuildHelper.cs to reflect the true location of these two files. Works for me so far!

It really worked, Thanks mate
