### ISSUE TITLE
Get Custom Feature data to textfield

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1209]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by Schaggo** [comment]
I am trying to parse strings set up in map box studio to display in unity. If anyone could point me to the location of mentioned custom strings it would be much appreciated. Thanks

**Comment by colin-young** [comment]
Assuming you mean you have added properties to your geoJSON feature definition, generated a tileset, and are now attempting to find those properties in Unity, if you look at the DataExplorer sample, the info display shows how to find those values in the Properties collection of the feature.

**Comment by Schaggo** [comment]
Thanks for the reply! Sorry for being so vague.
