### ISSUE TITLE
Cannot Import mapbox, errors in console, menu  item does not appear

### ISSUE THREAD

**Issue by o2x7** [mapbox/mapbox-unity-sdk#1211]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 2017.2.0f3
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to: iOS
* A description of what you're trying to do: Import Mapbox SDK
* Steps to recreate the bug if appropriate: 

1. New project
2. Import Custom Package -> mapbox-unity-sdk
3. Errors

* Links to your logs are also helpful: 

Hello

I am trying to do the most basic thing - import the mapbox sdk using the latest version of unity and mapbox and am hitting errors.  The mapbox menu item does not appear and I see the following errors in the console:

`Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainStrategies/LowPolyTerrainStrategy.cs(117,23): error CS0103: The name `IndexFormat' does not exist in the current context

Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainStrategies/LowPolyTerrainStrategy.cs(117,9): error CS1061: Type `UnityEngine.Mesh' does not contain a definition for `indexFormat' and no extension method `indexFormat' of type `UnityEngine.Mesh' could be found. Are you missing an assembly reference?

Metal: Fragment shader missing texture binding at index 0 (_MainTex / Hidden/BlitCopy)

A polygon of cone is self-intersecting and has been discarded.

Shader error in 'Mapbox/Clip_MapboxStylesPerRenderer': Unexpected identifier "UNITY_INSTANCING_BUFFER_START". Expected one of: typedef const void inline uniform nointerpolation extern shared static volatile row_major column_major struct or a user-defined type at line 76

`

**Comment by brnkhy** [comment]
@o2x7 I think `IndexFormat` was introduced in 2017.3 and you're using an older version, 2017.2.
Updating you editor should fix the issue but in case you can't, I'll check if deleting that line (or low poly class as whole) would help. Can't say it was intentional to have it there, might be a onverlook on our side.
