### ISSUE TITLE
How to increase the number of tiles you can cache with Mapbox

### ISSUE THREAD

**Issue by Robert-J-Taylor** [mapbox/mapbox-unity-sdk#1212]
Unity version: 2018.2.16f1
 Mapbox SDK version: v2.0.0

I am working on a project for a client for which I need to use the Mapbox Satellite imagery. We're creating an interactive display with hotspots users can click on to get more information about the location. When a user clicks on a hotspot we zoom into that location on the map. We're looking to display as much detail on the map as possible. We're currently using the "Range Around Center" option under the Extent Options. Under the Extent Options we're setting the North, West, East, and South coordinates to precisely map out only the tiles that we need to show in order to cut down on load time and to lower the number of tiles we need to cache. Our client may not always have internet and there will most likely be times where they will need to rerun the project as well. So having the ability to cache all the tiles needed for the map itself is a must. We've already gone into the mapbox configuration settings and increased the Mem Cache Size to 1000 tiles along with the File Cache size to 3000 tiles, but unfortunately it seems we may need slightly more in order to meet our needs. Is there any way to up the number of tiles that can be cached. If there are any other ways to optimize load time that would be quite helpful as well. Any suggestions/tips would be greatly appreciated. Thank you for your time!

**Comment by jordy-isaac** [comment]
@Robert-J-Taylor Please reach out to our [sales team](https://www.mapbox.com/contact/sales/) to discuss offline mapping options.
