### ISSUE TITLE
Display polyline on zoomable map

### ISSUE THREAD

**Issue by nilsk123** [mapbox/mapbox-unity-sdk#1215]
Hi,

I'm using the pannable / zoomable map example which is included in the unity package. I can not figure  out how to display a simple polyline based on a list of coordinates... this seems obvious for other platforms using the "addAnotation" method but I can't figure it out for unity.

I've been trying the directions example, but it only visualises text, no actual route line. How do i go from a list of vector2d coordinates to displaying a polyline?

**Comment by ivangarrera** [comment]
I would also like to know if it is possible to draw a polyline that connects the coordinates of a given list of coordinates.
