### ISSUE TITLE
CitySimulatorMap Scaling Options not working

### ISSUE THREAD

**Issue by helscar** [mapbox/mapbox-unity-sdk#1216]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: Unity 2017.4.13f
  * Scripting Runtime Version: Stable(.NET 3.5)
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 2.0 Subset
* Mapbox SDK version: 2.0
* The platform you're building to: Windows

Hi, 
I am trying to generate a terrain using real world unit size but World Scale Scaling Options don't work. 
Am i not understanding the way this option should work? 
What should i do to have a terrain at the correct world size ?

I need to create real world environnement for Architectural project and the correct size of the generated zone for each building is really important. 

Thank you

**Comment by colin-young** [comment]
Are you using 1 unit in Unity = 1 meter? That bit me a few times (a 65 meter building looks _very_ different than a 65 foot one). Can you post code/screenshots that show the specific issue you're having?

**Comment by helscar** [comment]
i made two images with a 10x10x10 unity unit cube on the map. 

here is 9 tile on zoom 18. You can see the cube is smaller than the road
![image](https://user-images.githubusercontent.com/13275712/50698894-8ebcbe00-1046-11e9-9322-1a1c78b715ac.png)

here is 9 tile on zoom 15. You can see the cube is way larger than any road
![image](https://user-images.githubusercontent.com/13275712/50699065-0e4a8d00-1047-11e9-8c15-017d780feed7.png)

is this the intended behaviour ?

**Comment by colin-young** [comment]
See:
* `MapAtWorldScale`: https://github.com/mapbox/mapbox-unity-sdk/issues/550 (and my own question about the scaling issue: https://github.com/mapbox/mapbox-unity-sdk/issues/329)
* Some older information on scaling, lat-long, etc. that might illuminate some things: https://github.com/mapbox/mapbox-unity-sdk/issues/123

**Comment by brnkhy** [comment]
@helscar I tried a similar test and it looks good for me; 
z18
<img width="401" alt="screen shot 2019-01-08 at 5 12 33 pm" src="https://user-images.githubusercontent.com/1465390/50835844-cdb18300-1368-11e9-827d-b1cce6fc90aa.png">
z15
<img width="421" alt="screen shot 2019-01-08 at 5 12 59 pm" src="https://user-images.githubusercontent.com/1465390/50835853-d1dda080-1368-11e9-94cc-36010bc4d768.png">

So we must be doing something different. Are you changing zoom level while running using the slider in abstract map? I think there's an issue there, it probably doesn't reset the object scales or something so yields bad result. If you stop and run it again though it should work as expected, can you verify that please? 
I'll try to look into the runtime change issue soon as well.
