### ISSUE TITLE
Creating a NavMesh for the map.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#122]
Ok so what I currently want to do is create a NavMesh for the map (my end goal is to create a map where I can use Unity's navigation system for my AI).

Creating the NavMesh at runtime for a tile is not a problem, but I'm not sure where I should hook into the process of terrain generation to create the NavMesh.

What I've got so far is a custom factory that extends `AbstractTileFactory` where I use a similar system to `MeshFactory`. In `OnRegistered` I add a listener:

```csharp
tile.OnHeightDataChanged += HeightDataChangedHandler;
```

And in the callback I create the NavMesh:
```csharp
private void CreateNavmesh(UnityTile tile)
{
    List<NavMeshBuildSource> sources = new List<NavMeshBuildSource>();
    NavMeshBuildSource s = new NavMeshBuildSource
    {
        transform = tile.transform.localToWorldMatrix,
        shape = NavMeshBuildSourceShape.Mesh,
        sourceObject = tile.MeshFilter.mesh
    };
    sources.Add(s);

    NavMeshData data = NavMeshBuilder.BuildNavMeshData(settings, sources,
        new Bounds(Vector3.zero, Vector3.one * 1000), Vector3.zero, Quaternion.identity);
    
    navMeshInstances.Add(tile, NavMesh.AddNavMeshData(data));
}
```

However, the NavMesh is always generated at `y = 0`, so I assume that the `tile.MeshFilter.mesh` is not updated here yet.

Any idea how I can get a callback when the mesh of the terrain is updated with the height data?

Note: The logic in the `CreateNavmesh(UnityTile tile)` method works fine if I run it manually after the entire map has been loaded.

**Comment by brnkhy** [comment]
@mihakrajnc hmm I'm not sure if I get it correct but after a brief look, it looks like we're firing the event right before applying it on the mesh and that seems to be your problem right?
Event is actually intended for data being available as the name suggests but it's also totally understandable to expect mesh being generated after that. 
You can see the `GenerateTerrainMesh` function inside TerrainFactory, that's where we apply the changes and at the end of the `CreateTerrainHeight` function, there are two lines;
```
tile.SetHeightData(pngRasterTile.Data, _heightModifier);
GenerateTerrainMesh(tile);
```
First one fires the event and second one applies the data so you can create another event for mesh being ready and fire it right after second one. Or you can pass second function as callback to first one and run it before the event etc.
Does that help?

**Comment by mihakrajnc** [comment]
@brnkhy Exactly what i was looking for! A new `OnMeshDataChanged` event, called after the height mesh is created did the trick. One step closer now:

![image](https://user-images.githubusercontent.com/8857844/27154177-5c94f5e4-5154-11e7-82fc-515a99ece04b.png)

When I get the `NavMeshFactory` working I'll post it somewhere here for anyone else who wants to use it.
Thanks!

**Comment by brnkhy** [comment]
@mihakrajnc awesome, looking forward to it!

**Comment by david-rhodes** [comment]
I made a demo several months ago with (beta) runtime navigation meshes, and IIRC, I had to wait a frame after the mesh was generated for the navigation mesh to build correctly. The good news is--the Unity examples included one that would regularly poll and calculate navigation as needed. 

That said, this use-case is exactly why we chose to use `AbstractFactories` to generate data! I'm looking forward to seeing it @mihakrajnc!

**Comment by mihakrajnc** [comment]
Here we go, after looking at [Unity's examples](https://github.com/Unity-Technologies/NavMeshComponents) (thanks for the idea @david-rhodes), the first thing I tried was just adding their `NavMeshSourceTag` to every tile, and having a `LocalNavMeshBuilde` in my scene.

Which worked! But that would be too easy and IMO would have unnecessary overhead...

So here is the final `NavMeshFactory`: https://gist.github.com/mihakrajnc/db8da69d45286ee0c5eef2488c1945c5

Much simpler than I originally thought it would be. The only thing that didn't work for me were the bounds of the `UpdateNavmeshDataAsync` method. In the [documentation](https://docs.unity3d.com/2017.1/Documentation/ScriptReference/AI.NavMeshBuilder.UpdateNavMeshDataAsync.html) it states that:

> Empty bounds is treated as no-bounds, that is, the NavMesh will cover all the inputs.

However, giving it `new Bounds()` or `new Bounds(Vector3.zero, Vector3.zero)` didn't have that effect. Any idea what else "Empty bounds" might mean? I just gave it huge bounds as a temporary solution.

Another useful thing to have here would be a `NavMeshObsticleModifier`, that would add a `NavMeshObsticle` to the generated building meshes, so that the buildings are cut out of the mesh. In theory just adding it to the building's `GameObject` should work as it should detect the mesh and position itself around it. But it wouldn't work with funky shapes of buildings.

This is the result with the factory, and some prefabs placed on the scene with `NavMeshObstile`'s on them (note that it's one continuous NavMesh across the entire map, unlike the previous screenshot):

![image](https://user-images.githubusercontent.com/8857844/27256355-51dbdc0c-53b2-11e7-86af-2126cf3d6147.png)

**Comment by mihakrajnc** [comment]
Ok so this tile provider doesn't work well. There is noticeable lag when loading the tiles and looking at the  profiler the `NavMeshFactory` consumes about 30% of the processing power of the frame when tiles are loaded, even when doing it Async.

So, keeping in mind that many sequential calls to the Async method will freeze the game, I made a new factory, which signals to a Singleton in the scene when a new tile has been loaded. The singleton then waits for all tiles to be loaded in that sequence, and only then calls the Async method. Works well and without lag, however, for my needs, it still wasn't good enough. If the user is moving, even at a reasonable car speed (e.g. 50kmph), the NavMesh calculations can't keep up and currently I don't see any way around this...

I'll be trying some other NavMesh-type assets to see if any can keep up with runtime generation.

**Comment by david-rhodes** [comment]
@mihakrajnc A few thoughts:

1. What is the terrain resolution of each tile? Have you tried decreasing this? 
2. Have you tried tweaking your navmesh slope settings? Slope calculations can eat up a lot of time.
3. Something that we will probably implement in the future for other purposes: use a lower zoom level for terrain data. For example, 1 terrain tile at z14 can serve elevation data for 16 raster tiles at z16. This would obviously lower the complexity of the navmesh system.

**Comment by david-rhodes** [comment]
You can use the new [`AddMonoBehavioursModifier`](https://github.com/mapbox/mapbox-unity-sdk/blob/e7a96cb396cde5b4c62dc2dbbc5f58af6a2c4839/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/GameObjectModifiers/AddMonoBehavioursModifier.cs) to attach a `NavMeshSourceTag` to any mesh created from a `MeshFactory`, now. This is useful if you want to add navigation to specific vector tile layers.

For clarity, this does not replace the solution @mihakrajnc added above, but augments it.

**Comment by jordy-isaac** [comment]
Closing this one. Please re-open if any additional help is needed.
