### ISSUE TITLE
Mapbox WorldScaleAR-ManualAlignment :Disable Rotation or manual-alignment

### ISSUE THREAD

**Issue by tyrroncondo14** [mapbox/mapbox-unity-sdk#1222]
I'm using mapbox version 2.0.0 and unity version 2018.3.0f2.
Im using the scene WorldScaleAR-ManualAlignment. How can I disable the rotation and the dragging the pan but not the relocate button?

**Comment by jordy-isaac** [comment]
Hi @tyrroncondo14 I would suggest having a look at the `DebugCanvas` game object and using just the pieces that you would like in your scene.
