### ISSUE TITLE
import 3d models failed

### ISSUE THREAD

**Issue by dud26** [mapbox/mapbox-unity-sdk#1223]
I was using the mapboxWorldScaleManualAlignment scene. I created a 3d model in blender, and I'm trying to export it in unity to place it in the map using spawnonmap script. I export the file as fbx. But when I drag it into unity, the 3d model looks like this. The 3D model seems to be okay in other projects.  And one more thing how can I assign the 3d model's rotation so it will fit in the real world.
![error2](https://user-images.githubusercontent.com/46429396/50747372-8b0b8000-126e-11e9-943f-438775fbfbdb.png)
![error1](https://user-images.githubusercontent.com/46429396/50747373-8b0b8000-126e-11e9-8b71-e8ccc603aead.png)

**Comment by brnkhy** [comment]
@dud26 looks like triangles are inverted (looking inside). I would suggest checking your export (in blender) and import (in unity) settings. Sorry can't help more on this but it's a 3d model issue.

If this is a particular building you want to replace, I would suggest checking `Replace Features` demos scene and how it uses the `ReplaceFeatureModifier`.  `SpawnOnMap` aims little different usecases.

**Comment by dud26** [comment]
Hi sorry for the late response. Thanks for the idea. I really appreciate it. I read the documentation about replace features and yes that is what I need!. But what if I want to replace a specific building but it is not searchable in the mapbox search feature. Can you hive me a tip how to place a building exactly including its rotation in the real world. Again thank you very much for the reply I really appreciate it.

**Comment by dud26** [comment]
One more thing. can I add a 3d model with animation with any of the mapbox features? Thank you so much.

**Comment by dud26** [comment]
Hi @brnkhy ! I have another question please. Can I place a 3d model with animation that will be triggered when I click a button?
