### ISSUE TITLE
Cant edit map in unity scene 

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1233]
Related with #1153 

I use an abstractmap / citysimulator... but in my scene in unity i only have the prefab...it would be nice to have the map downloaded so i could work with different buildings or aspects of the scene, as other game objects in unity. ex: change the texture of a concrete building, perhaps moving it because street is too little to pass my character, put new objects like trees, treauser chests.... now i have to play scene put the object in a random place, play the scene and pause it, then take note of the position and size of object and then stop game, and edit the object with the notes taken....

Also dont know how to move or chnge texture of a building ( one determined building not all the buildings). Or for example id like to add some textures to the river, but as everytime the scene "reloads" i cant...

Also i found that some random times, the map is not loaded on time, so my character doesnt touch ground and falls infinite in y axis...( as there is no ground).

Thanks again

**Comment by jordy-isaac** [comment]
@ejgutierrez74 We'll have preview mode in the next release and if you would like to check it out early, you can pull the `develop` branch and try it out.
