### ISSUE TITLE
Error on building for ARCore 

### ISSUE THREAD

**Issue by kndol** [mapbox/mapbox-unity-sdk#1236]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.3.0f2 
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: API Level 24
* Mapbox SDK version: 2.0.1
* The platform you're building to: Android
* A description of what you're trying to do: build and run
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 

Destroy may not be called from edit mode! Use DestroyImmediate instead.
Also think twice if you really want to destroy something in edit mode. Since this will destroy objects permanently.
UnityEngine.Object:Destroy(Object)
Mapbox.Unity.Map.AbstractMap:Awake() (at Assets/Mapbox/Unity/Map/AbstractMap.cs:443)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by jordy-isaac** [comment]
@kndol We should have this cleared up on the next release. Thanks for reporting.

**Comment by avmakesthings** [comment]
@jordy-isaac I'm still getting this issue 
- Unity version:  2018.3.4f1
- Scripting Runtime Version: .NET 4.x Equivalent
- Scripting Backend: Mono
- Api Compatibility Level: API .NET 3.0
- Mapbox SDK version: 2.0
- The platform you're building to: iOS

I'm working with your ar-foundation-port branch and just trying to build the Mapbox worldscaleAR example.
