### ISSUE TITLE
Cursor location is shifted after moving the map

### ISSUE THREAD

**Issue by Dymchick1** [mapbox/mapbox-unity-sdk#1238]
Hello! Thanks a lot for your support, you do a great job for Unity Mapbox.
I've just started with Mapbox a couple days ago and got a problem.

I want to make a project with the ZoomableMap Demo provided in the example folder. 
So I've drag a map with my mouse and while map position is changing **cursor position incorrectly сhange** relative to other objects too. 

For example: 

Mapbox cursor before/after dragging:
![cursor position before drag](https://user-images.githubusercontent.com/16517358/51034781-e4e6af80-15b8-11e9-96ae-acf26d101107.PNG)
![cursor position after drag](https://user-images.githubusercontent.com/16517358/51034782-e4e6af80-15b8-11e9-8cf8-eddf517f9227.PNG)

Google cursor before/after dragging:
![cursor position before drag google](https://user-images.githubusercontent.com/16517358/51035256-77d41980-15ba-11e9-8848-0c94be687423.PNG)
![cursor position after drag google](https://user-images.githubusercontent.com/16517358/51035257-77d41980-15ba-11e9-9f03-dbfc591abf1b.PNG)

I tried to increase Pan Speen in QuadTreeCameraMovement script to 2,7. This value works well until you change zoom, then it stops work. 

I use last Mapbox SDK version with Unity 2018.2.14
I'm waiting for your answer.

**Comment by jordy-isaac** [comment]
@Dymchick1 Thanks for reporting this. It looks like something that would be good to fix. Since these example scenes are meant to show more of what's possible rather than be fully featured apps, it might be a bit lower priority. However, we'd be happy to review a PR if you come up a solution as you work on this project.
