### ISSUE TITLE
Query location - just making sure I did this correctly

### ISSUE THREAD

**Issue by 1701Tiberius** [mapbox/mapbox-unity-sdk#1241]
The location information in my game has been updating correctly for the last month on both Mac and PC, but today I did my first build to iOS, and my real world location was no longer being correctly updated (the game does not use GPS to find location, but rather updates a player position and finds where it is in the world based on joystick user input). Any way, it took a couple hours, but I found a directive in the AbstractEditorLocationProvider that starts a coroutine QueryLocation(). When I removed the directive, allowing all platforms to access this code, terrain and buildings started showing up on my iOS build.

Is this the correct way to handle this? Is .1 a good wait interval, or is something higher a better way to go?

Just wondering - it's working, but it would be great to get confirmation that I can't be doing something better.

Thanks!

**Comment by jordy-isaac** [comment]
@1701Tiberius Is there a reason you're needed a location provider if you're specifying the location based on user input? The `LocationProvider` is used for centering the map with the device location.

**Comment by 1701Tiberius** [comment]
Hi @jordy-isaac -

I know it's been a week or so, but had to research exactly how that code was implemented. I actually use it initially to find a player's starting location, and turning on that subroutine was the only way to make it position someone at the device's location. My question is that if I were to use the GPS to find that location, would the QueryLocation() coroutine be the right approach, and if it had to be updated, then would .1 be a good wait interval?

Thanks,
Garry
