### ISSUE TITLE
Reloading WorldScaleAR or TableTopAR scene

### ISSUE THREAD

**Issue by samisuleman10** [mapbox/mapbox-unity-sdk#1243]
-Mapbox SDK version: 2.0
-Unity Version 2018.2.17f1
-Android Pixel XL

I am using WorldScaleAR Example for my game. First time when the scene loads it works fine with POI objects visible as i placed. As the game is based on multiple scenes and there is option for reloading the scene after pause. When the scene is reloaded I cannot see the POI object and nothing is working properly. I am novice to Unity and Mapbox. Your help will be appreciated in this regard.

**Comment by samisuleman10** [comment]
The problem has been solve, the solution is [here](https://github.com/Unity-Technologies/experimental-ARInterface/issues/59).

**Comment by jordy-isaac** [comment]
Thanks for closing the loop!
