### ISSUE TITLE
location based game 50+ custom 3d features

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1244]
Hi, I am working on a location based game utilizing pan and zoom and lots of custom 3d objects loaded via the map feature panel. now the performance is really slow. It works fine on an iPhone X but everything else is damn slow or right away crashes.

Is there a better way to use map box studio datasets to place objects?
Any suggestions? 

Help is much appreciated!

**Comment by jordy-isaac** [comment]
Hi @Schaggo 

I would try a few things:
Make sure that your Extent Options are set to not load more tiles than you need.
Turn off colliders where you don't need them
Make sure compression is enabled and retina is disabled
Use filters to conditionally render the game objects only when you need them 

How are you placing your objects? This might make a difference as well.

**Comment by Schaggo** [comment]
Thanks for the reply. 
I am using the “camera bounds” option to reduce loaded tiles to the minimum amount.
Compression is on, retina off...

The loaded prefabs all have a collider via a collider modifier. They are placed directly on the map sometimes slightly intersecting it. 

When I am back at the pc I will try to get info on the filters you mentioned.

**Comment by Schaggo** [comment]
Ok i figured it out. mapbox wasn't the problem. Thanks for the kind help!

**Comment by ejgutierrez74** [comment]
@Schaggo what was the problem ?? Also could you post a code of how do you put objects in a map ? Looks interesting...

**Comment by ejgutierrez74** [comment]
can you put an example if code?

**Comment by Schaggo** [comment]
> can you put an example of code? Thanks

what component do you need code for?
