### ISSUE TITLE
Make more tutorials 

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1245]
There are some interesting news : 
https://blog.mapbox.com/tagged/unity

But there's a lack of tutorials, im missing a step-by-step tutorial of how to implement the feature

ex: https://blog.mapbox.com/editing-your-maps-at-runtime-ec4f60de1561
Is nice to know that we can edit our maps at runtime, but would be nicer to put some examples, tutorial ans how to implement it.
@atripathi-mb 

https://blog.mapbox.com/build-ar-experiences-with-places-data-48a4856c482f
@jim-martin 

https://blog.mapbox.com/painting-san-francisco-with-the-maps-sdk-for-unity-bf4abc1d4641
@brnkhy 

Also adapted to mapbosx sdk 2.0.0

**Comment by jordy-isaac** [comment]
Hi @ejgutierrez74 thanks for the input. We hope to make some more tutorials in the future, and this is good feedback. A couple other tutorials you might be interested in are below:

[Runtime styling](https://blog.mapbox.com/let-play-drive-your-game-styling-8541057764a6) - This one is a tutorial but it has some code and how to implement
[Add POIs](https://docs.mapbox.com/unity/maps/examples/poi-placement/#create-a-custom-scene-with-pois) - Not specifically AR, but you would approach it the same way
[PocketDroids GO](https://www.youtube.com/watch?v=RhG1kfDBhgM) - Build a location based game
[Drenches of War](https://www.mapbox.com/help-video/tutorials/unity-game-drenches-of-war/) - Tabletop AR game tutorial
