### ISSUE TITLE
AR as option

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1246]
I have with many troubles and compiling errors with Mapbox Unity and Google ARCore/ArKit, but if i deleted it i found nothing was working and reimport again all mapbox package. So its a feature request that if you dont want/need this, to import a "lite" package without this. Also lots of examples and prefabs are imported, and perhaps if you only need citysimulator, to import only the things needed for city simulator....
You can release a full mapbox package, full mapbox without AR/VR, citysimulatormapbox package and so on....
Some kind of more configurable. Also related to #791  #1208  #938

**Comment by jordy-isaac** [comment]
Thanks for the feedback. We'll think about this option in the future, but for now you'll need to uncheck them when importing or delete them if imported and not needed. I appreciate the input!
