### ISSUE TITLE
Transfer /mapbox-unity-sdk to docs.mapbox.com

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-unity-sdk#1248]
@mapbox/frontend-platform and @mapbox/docs are working together to transfer this site to the new `docs.mapbox.com` domain.

Here are the steps in the process.

- [x] Launch the site at `docs.mapbox.com`.
- [x] QA the site .
- [x] 301 redirect from `www` to `docs`.
- [ ] Delete `www` files and branches.

We're going to start on this today, and try to finish it today or tomorrow.

**Comment by davidtheclark** [comment]
@mapbox/unity After taking a look at this repo, I don't think that I should try to do this without your help. This may be as easy as changing the branch reference here: https://github.com/mapbox/mapbox-unity-sdk/blob/f7e29dc65e75b545eae1d7bc5265e31033d8e3bf/scripts/build.csx#L226-L227

Or there may be a lot that I'm not aware of.

How do you think we should proceed?

**Comment by atripathi-mb** [comment]
@davidtheclark IIRC Our CI is setup to create a branch called `mb-pages` which contains API documentation and that's what gets picked up here https://docs.mapbox.com/unity/maps/overview/ & here https://www.mapbox.com/mapbox-unity-sdk/api/

I am not familiar with the "magic" that links the [`mb-pages`](https://github.com/mapbox/mapbox-unity-sdk/tree/mb-pages) branch from our repo on to mapbox.com

If we need to change the name of the branch on our end then changing the two lines above should be suffiecient. 

Note - Our CI is broken right now since we security could not figure out how to link github to CI after the switch to SSO.

**Comment by davidtheclark** [comment]
Has this site been republished since the updates to Publisher? I don't see evidence of the `.artifacts.yml` that would be necessary. I don't think I understand how this *could* be published right now. What's the status?

Here are the changes we need to make to get this published to its new home on `docs.mapbox.com`:

- Publishing must work, so I believe that means there needs to be an `.artifacts.yml` file at the root of the publishable branch (currently `mb-pages`, but that's changing, see below).
- We'll need to add a `.publisher.yml` file at the root of of the publishable branch, with the content `subdomain: docs`.
- Then we'll need to change the publishable branch we use to `publisher-production`.

@mapbox/docs @atripathi-mb who can I work with to get this build & publish process adjusted?

**Comment by atripathi-mb** [comment]
@davidtheclark No, our docs were last published on 10/16/2018. I think the Publisher updates were rolled out later. 

You can work with @brnkhy or me on the Unity side.

**Comment by davidtheclark** [comment]
The transition is complete!

@atripathi-mb once https://github.com/mapbox/mapbox-unity-sdk/pull/1251 merges, can you please delete the `mb-pages` branch? Publishing should happen now from the `publisher-production` branch. At that point, we can close this issue.

**Comment by davidtheclark** [comment]
`mb-pages` will no longer publish, so I suggest deleting it. Closing out this issue, though, as the transition is complete.

**Comment by atripathi-mb** [comment]
@davidtheclark deleted `mb-pages`.
