### ISSUE TITLE
Null reference in PositionWithLocationProvider.Awake

### ISSUE THREAD

**Issue by derekdominoes** [mapbox/mapbox-unity-sdk#126]
PositionWithLocationProvider.Awake accesses the static LocationProviderFactory.Instance which may be null if Awake on LocationProviderFactory has not been called before that of PostionWithLocationProvider.Awake.

This was working fine for me until I changed some of my project's files organization. Then the error occurred even after trying to return to the old files organization.

Unity does not guarantee the order of calling Awake functions normally. So this design dependency could happen to anyone at any time. I can get around it by using Unity Edit->Project Settings->Script Execution Order and adding the LocationProviderFactory class. But this is does not seem to be the best solution or at least needs to be documented.

**Comment by david-rhodes** [comment]
@derekdominoes You are correct, this event registration should be happening in `Start()`. This will be fixed in our next release.

**Comment by david-rhodes** [comment]
@derekdominoes c0bc2cfd88855ee1892ff2ef8756c258233ab4aa
