### ISSUE TITLE
Problem: World-scale AR manual alignment

### ISSUE THREAD

**Issue by BaerAlex** [mapbox/mapbox-unity-sdk#1260]
Unity version: 2018.3.1f1
Scripting Backend: Visual Studio
Mapbox SDK version: v2.0.0

Hello everybody,
is it possible to turn off the Ground-Map-Overlay on the ArAlignedMap and not to lose the representation of the PIO's and not to get a black screen on the minimap?
Thanks for support.

**Comment by jordy-isaac** [comment]
I believe we got back to your support ticket by email. If you still have some more questions you can respond there or open a ticket with us at help@mapbox.com
