### ISSUE TITLE
GPS inaccuracy

### ISSUE THREAD

**Issue by dasMalle** [mapbox/mapbox-unity-sdk#1261]
Our problem is that the location is updating but the gps accuracy never gets better than 20m and the location is way off. 

![image](https://user-images.githubusercontent.com/7252639/51749073-a4099300-20ae-11e9-875a-77e8b5538d2d.png)

We are expecting raw gps updates to process further ourselves. Is it possible to get that with higher accuracy? 

* Unity version: 2018.3.0.2f
  * Scripting Runtime Version: 3.5
  * Scripting Backend: mono
  * Api Compatibility Level: net 2.0 subset
* Mapbox SDK version: 2.0
* The platform you're building to: android api 24
* A description of what you're trying to do: Getting the gps location accuracy to <10m. 
* Steps to recreate the bug if appropriate: go outside 

#1128

**Comment by phaax** [comment]
We’ve run several tests here with different phones and so far we’ve been able to narrow it down to being an issue with phones that are running Android Pie.
 
On phones with Android Nougat we could reach accuracies below 10 meters (6m to be exact). But on Android Pie it’s never below 20 meters.

**Comment by MarjanPl** [comment]
Also, in Android there is a setting to use higher precision localization somewhere hidden in preferences. Depends on the Android Version if and where that is. I think it is using open Wifi Spots to accomplish this.
IOs doesn't have something like that as i remember.
