### ISSUE TITLE
heading can not be found in  \Unity\Location\DeviceLocationProvider.cs

### ISSUE THREAD

**Issue by chenaptx** [mapbox/mapbox-unity-sdk#1262]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: .Net
  * Api Compatibility Level: 
* Mapbox SDK version: latest mapbox-unity-sdk_v2.0.0
* The platform you're building to: hololens
* A description of what you're trying to do:  build the project to visual studio
* Steps to recreate the bug if appropriate: import and build
* Links to your logs are also helpful: "heaing" is undefined
it seems that in  line 320
  // +90.0 to make top (north) 0?							double heading = (Math.Atan2(latDiff, lngDiff) * 180.0 / Math.PI) + 90.0f;
							
the definition of double heading is wrongly disabled

**Comment by roura-12** [comment]
what do you want to do exactly , is it a location based game of type of  Pokemon Go ?
Give us more details about your work

**Comment by jordy-isaac** [comment]
Please re-open or email us at help@mapbox.com if you need any additional help.
