### ISSUE TITLE
Invalid token 

### ISSUE THREAD

**Issue by chenaptx** [mapbox/mapbox-unity-sdk#1263]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 
I am in China and the token submitted is always checked invalid.
Since the docs.mapbox cannot be accessed from China (with VPN open), I wonder if the server to check the token is set in a related ip?

**Comment by jordy-isaac** [comment]
Hi @chenaptx please email support@mapbox.com and we can help troubleshoot your token.

**Comment by StarKing777** [comment]
Hi there,
I am in South Africa.
Using Unity 2.6
using the latest Mapbox SDK version.
I am using the SDK on my personal computer.
Its keeps telling me that I have an invalid access token.

I have been trying to trouble shoot it for two days now.

I mailed Mapbox support.

anyone got any advice on this issue?

Kind regards

Jesse

**Comment by thebadpanda** [comment]
@StarKing777 same issue here. works perfect with Postman, but when call the API from Java it's always 
"Not Authorized - Invalid Token"
