### ISSUE TITLE
Buildings removing or adding at run time 

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1264]
Unity 2017.4.17f1 
Mapbox v2.0.0
I want to add buildings by dragging and dropping them to the map and remove existing buildings by selecting with the mouse is it possible? and how? Thanks

**Comment by jordy-isaac** [comment]
Hi @roura-12. [Runtime editing](https://blog.mapbox.com/editing-your-maps-at-runtime-ec4f60de1561) is supported in version 2.0 of the SDK. You'll want to modifiy the [vector layer](https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.VectorLayer.html) with an onClick similar to the way it's done in this [blog post](https://blog.mapbox.com/let-play-drive-your-game-styling-8541057764a6).

**Comment by roura-12** [comment]
thank you I will try that
