### ISSUE TITLE
Custom style select

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1269]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.4.19f
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to: 
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 

using Mapbox.Unity.Map;
using UnityEngine;
using UnityEngine.UI;

public class ToggleStyle : MonoBehaviour
{
    private AbstractMap abstractMap;
    private Text buttonText;
    private bool nightModeOn = true;

    void Start()
    {
        abstractMap = FindObjectOfType<AbstractMap>(); 
        buttonText = FindObjectOfType<Button>().GetComponentInChildren<Text>();
    }

    public void ChangeImagery()
    {
        if (nightModeOn)
        {
            abstractMap.ImageLayer.SetLayerSource(ImagerySourceType.MapboxSatellite);
            buttonText.text = "Night Mode";
            nightModeOn = false;
        }
        else 
        {
            abstractMap.ImageLayer.SetLayerSource(ImagerySourceType.MapboxDark);
            buttonText.text = "Sattelite Mode";
            nightModeOn = true;
        }
    }
}

@jordy-isaac is possible with your code to load a custom map style created in mapbox studio... in concrete id like to load: mapbox://styles/egutierrez74/cjp86u7fz05cx2smn135h8l1c

I have a menu where user can choose between different styles-map, and i wanted to add my custom one...

Thanks,

**Comment by jordy-isaac** [comment]
Hi @ejgutierrez74! This is very possible. I made a demo on how to do it and you can check it out in this [blog post](https://blog.mapbox.com/let-play-drive-your-game-styling-8541057764a6).

**Comment by ejgutierrez74** [comment]
So, set ??:

`abstractMap.ImageLayer.SetLayerSource(mapbox://styles/egutierrez74/cjp86u7fz05cx2smn135h8l1c);`
