### ISSUE TITLE
TrafficAndDirections Scene Exemple 

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1270]
mapbox v2.0.0
Unity 2017.4.17f 
![traffic](https://user-images.githubusercontent.com/7107407/52058355-8c775200-2567-11e9-97c7-c6502a5fe8c8.PNG)

I want to know if the custom data are real time traffic data or are prepared to be used in this exemple;
If I want to create real time city data I can use it or I should find other data sources ( how to do that if it is the case) 
Thank You.  
@jordy-isaac @brnkhy @atripathi-mb

**Comment by jordy-isaac** [comment]
This is the actual data from the [Traffic v1 tileset](https://docs.mapbox.com/vector-tiles/reference/mapbox-traffic-v1/)
