### ISSUE TITLE
Map at design time

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1271]
Mapbox v2.0.0 
Unity 2017.4.17f1
Hey guys, I want to know if I can get the map at the design time so it will be easier to add objets.
Thank you 
@jordy-isaac @brnkhy @atripathi-mb

**Comment by jordy-isaac** [comment]
We'll have a preview mode so that you can see your map without running your scene in the next release. You can also check it out now on the `develop` branch.
