### ISSUE TITLE
Mapbox in Unreal Engine?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [mapbox/mapbox-unity-sdk#1272]
Hello Mapbox Team,

The Mapbox SDK in Unity is really amazing, thank you for sharing it to us. 

Do you have a plan to make another SDK for Unreal Engine too? I notice a lot of companies using Unreal Engine to develop their products or simulators. 

Thank you.

**Comment by jordy-isaac** [comment]
Hi @Xunzhaocunzi Glad you like the Maps SDK for Unity. At this time we don't have immediate plans for an Unreal SDK. We'll be sure to blog about it if things change.

**Comment by delebash** [comment]
Any update on a plugin for Unreal?  https://blog.mapbox.com/unreal-engine-for-auto-with-mapbox-acb5e8c1dd71.  Although I don't just want this for auto.
