### ISSUE TITLE
Player position movement not accurate in world scale - ar example

### ISSUE THREAD

**Issue by dhruvmodhapp** [mapbox/mapbox-unity-sdk#1274]
Hi All Guys,
                   I having **trouble with GPS Positioning of player** in world scale - ar example. Player position not accurate where I moving. I moved around London Liverpool Street, but the position of a player not accurate place on the map view. 
                   What should need to solve a problem of GPS location accurate for player position on map? In Location Provider - Device (Desired Accuracy In Meters, Update Distance in Meter, Update Time in Millisecond) in all three parameter which value GPS update make optimize for accurate player location?
- When I am testing in India, player location is not updating well. But in London near to Countryside(Northern Parkland), player position movement working as nice as expected.
Any solution? @jordy-isaac

**Comment by jordy-isaac** [comment]
Hi @dhruvmodhapp I would check out this ticket for some ways to improve GPS.
https://github.com/mapbox/mapbox-unity-sdk/issues/1261
