### ISSUE TITLE
Mapbox/unity/trip_duration_and_distance

### ISSUE THREAD

**Issue by drusttaib** [mapbox/mapbox-unity-sdk#1275]
Hello,
I am using Mapbox with Unity 2018.2. I can use DirectionFactory to create direction from one point to another. I want to know how to get the distance and duration of my trip

@jordy-isaac  could you help me with this?

**Comment by jordy-isaac** [comment]
@drusttaib You can find the `distance` property in the [route object](https://docs.mapbox.com/api/navigation/#route-object) which is returned from the directions api. This isn't surfaced in the example scene, but you could customize it with a way to handle the response the way that you need. 

The `Directions` playground scene in SDK might also be of help to you. You can find it at the following path: `Mapbox > Examples > 5_Playground > Directions`
