### ISSUE TITLE
When Mapbox Unity SDK v2.0 will be updated?

### ISSUE THREAD

**Issue by ufktvfk** [mapbox/mapbox-unity-sdk#1276]
Hi, I have a Udemy course teaching Location Based AR apps with Mapbox Unity SDK and I have a youtube channel where I share tutorials with Mapbox Unity SDK. .I am preparing new tutorials and new content with Mapbox Unity SDK. It is really important to prepare these with the latest Mapbox Unity SDK. 

So, when will the latest version be published? I think it is v2.01. If you can give a predicted day, I will be really glad :-)

**Comment by jordy-isaac** [comment]
Hi @ufktvfk We'll have a release coming out very soon which will include a feature to allow for previewing your map in the editor. That's going to be the major change in the next release and it won't have major implications for your course as long as you're already on 2.0.

However, if you want to get a head start you can get the WIP from the `develop` branch. Good luck on your class!

**Comment by ufktvfk** [comment]
Thank you:-) By the way, great work. I love Mapbox Unity SDK.
