### ISSUE TITLE
Runtime tile loading with CameraBoundsTileProvider crashes on device

### ISSUE THREAD

**Issue by darukin** [mapbox/mapbox-unity-sdk#128]
Runtime tile loading with CameraBoundsTileProvider at generate and dispose levels set at 2 causes whole app to crash on device when scrolling camera over tile boundaries frequently but not always. If I set the levels to 1 it's fine however. Also getting a wierd blue line across some tiles etc.

**Comment by david-rhodes** [comment]
@darukin Are you able to reproduce in the editor (any exceptions)? In any case, I recommend that your dispose range is higher than the generate range.

As for the blue lines, a screenshot would help. I suspect you are seeing the camera background color through tiles that have not yet loaded terrain data (and therefore tiles are not stitched together, yet).

**Comment by david-rhodes** [comment]
@darukin closing for now. Please re-open if your problem was not correctly addressed.
