### ISSUE TITLE
Player position not updating often enough in LocationBasedGame example

### ISSUE THREAD

**Issue by craehn** [mapbox/mapbox-unity-sdk#1280]
Hello,
I'm trying to use and build upon the Location-basedGame-example from the Mapbox SDK 2.0.0, but for some reason the position of the user updates very rarely. Sometimes i have to walk up to 20-30 meters before the player moves on the map. The location updates if I open Google Maps on the phone and switch between the two apps, though. 
I have tried changing some different values on the location provider objects and also tried switching positioning script on the PlayerTarget, from ImmediatePositionWithLocationProvider to PositionWithLocationProvider, but nothing seem to help. 

I'm using Unity 2018.3.2f1 and a Huawei Mate 20 Pro (Android 9.0).

I'm kind of new to Unity, so maybe there is something obvious I've missed? Or maybe the example isn't made for updating the position of the user that often? Would love some help with this! :)

**Comment by jordy-isaac** [comment]
Hi @craehn I just responded to the support ticket you had open with us. You can also check out this issue for some ways to improve your signal: https://github.com/mapbox/mapbox-unity-sdk/issues/1261

**Comment by phaax** [comment]
We have the same issue with Android 9.0 (Huawei P20 Pro). But all the tickets regarding this issue is closed and not taken seriously enough.

It is not a signal issue. It is an issue with the SDK (or at the very least Huawei / Android 9.0 phones).

**Comment by craehn** [comment]
It's just so weird! It works like a charm when I turn off mobile data and wifi, it then uses "gps" as location provider and it updates the users location often and with pretty decent accuracy, but I'm having trouble setting the location provider manually to only (or at least mostly) use gps. As soon as I turn on mobile data it starts using "network" as location provider which is not updating either at all or only updates like once or twice every minute with terrible accuracy (I'm talking 100+ meters of inaccuracy), even when walking in a very open area. 

I don't suppose you have any idea how to manually pick the gps location provider, @phaax ? I tried changing and commenting out some checks in the existing code where it looks like the script try to decide whether to use network or gps, but to no avail. :(

**Comment by BergWerkGIS** [comment]
> It's just so weird! It works like a charm when I turn off mobile data and wifi, it then uses "gps" as location provider and it updates the users location often and with pretty decent accuracy, but I'm having trouble setting the location provider manually to only (or at least mostly) use gps. As soon as I turn on mobile data it starts using "network" as location provider which is not updating either at all or only updates like once or twice every minute with terrible accuracy (I'm talking 100+ meters of inaccuracy), even when walking in a very open area.

@craehn @phaax that's a known issue with some Unity versions and some devices hanging on to the last position reported by wifi even when a much better GPS location is available (check the Unity forums, there are plenty of reports of that problem).

Unfortunately we haven't found a way around it - except switching off wifi.

However, on Android API version >=24 (Android 7, Nougat) you should be able to get better location using our custom [DeviceLocationProviderAndroidNative.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/f7e29dc65e75b545eae1d7bc5265e31033d8e3bf/sdkproject/Assets/Mapbox/Unity/Location/DeviceLocationProviderAndroidNative.cs) which reaches directly into the location services provided by Android bypassing Unity's `Input.Location`.

Take a look at the `LocationProvider` scene in 
https://github.com/mapbox/mapbox-unity-sdk/tree/develop/sdkproject/Assets/Mapbox/Examples/5_Playground/Scenes
which has the correct setup for the native Android location provider.

**Comment by craehn** [comment]
Thanks for the reply! 

I have to turn off mobile data as well for it to work, it is not wifi that's my main issue here, I almost never use wifi on my phone anyway. So turning off wifi does nothing - turning off mobile data "works". However I can't have an app where I have to turn off mobile data for it to work. :/ 

I have tried using the LocationProvider-example as well, but I'm experiencing the same problems with that. It was however that example scene that made me notice that it doesn't want to use "gps" as location provider as long as I have mobile data turned on. 

I doubt I will find a workaround if you people haven't found a way around this problem, so I guess I just have to put my project on ice for now.

**Comment by BergWerkGIS** [comment]
> I have to turn off mobile data as well for it to work, it is not wifi that's my main issue here

@craehn weird, for me it was always enough to just switch off wifi.

> so I guess I just have to put my project on ice for now.

You might want to try another Unity version (if that's possible for you) before you put your project on ice.
My impression was that this problem occurs very intermittently and some Unity versions work better than others.
Sorry, but I cannot give you any specific versions as it has been a while that I worked on that.

**Comment by phaax** [comment]
Turning Wi-Fi off did work. But that isn't really an option.
DeviceLocationProviderAndroidNative.cs makes no difference.
