### ISSUE TITLE
Avoid reserved/magic folder names

### ISSUE THREAD

**Issue by ahokinson** [mapbox/mapbox-unity-sdk#1281]
Unity will include all assets in a build that exist inside of folders name `Resources`.

When I was reviewing a Build Report, I noticed that a lot of Mapbox sample content was being included in my build. Deleting these sample resources from my project removes them from my build.

While this is a decent workaround, in practice, I'd like to keep everything vanilla within the Mapbox folder.

From the [Resources Folder Best Practices](https://unity3d.com/learn/tutorials/topics/best-practices/resources-folder):

> Don't use it.

To reproduce, create a project without Mapbox and build. Using the [build report inspector tool](https://assetstore.unity.com/packages/tools/utilities/build-report-inspector-for-unity-119923), review the included assets. Add the Mapbox SDK without adding any functionality to the project. Build again and review the new build report. Note the new included assets.

**Comment by brnkhy** [comment]
Hello @ahokinson,
We noticed this recently as well and will look into fixing it as soon as possible. Thanks for the ticket, I'll keep it open until it's fixed. 🙏
