### ISSUE TITLE
Player movement not accurate as Google/Apple map location updating.

### ISSUE THREAD

**Issue by dhruvmodhapp** [mapbox/mapbox-unity-sdk#1283]
Hi,
In Worldscale-ar, player location not updating accurate as Google/Apple Map location updating. The player moves after delay and not at precise location.
- What should we need to do for more accurate player movement on the map?
- I was tested near ' 55 Bishopsgate, London, UK' (51.515164, -0.082831). Is this (51.515164, -0.082831) location nearby, can we able to achieve a more accurate player movement?
- Any help will be appreciated. Thanks. @jordy-isaac @BergWerkGIS @atripathi-mb

![issue_bishopsgate_hiscox](https://user-images.githubusercontent.com/46337334/52459605-2785b280-2b8c-11e9-9d66-0ce0abc03fb8.png)

_Note: If this is a bug or support ticket, please provide the following information:_
Unity version: 2018.2.16f1
Scripting Backend: Visual Studio
API Compatibility Level: iOS 12.1
Mapbox SDK version: v2.0.0
The platform you're building to: iOS

**Comment by roura-12** [comment]
Hi Mathhew Hallberg talk about accuracy using Mapbox and has implemented two projects about that [https://github.com/MatthewHallberg/MapboxGPSHeading](url) [https://github.com/mapbox/mapbox-ar-unity](url)   and this is his video talking about that [https://www.youtube.com/watch?v=_Idze_NzDu0](url) 
I hope that they could help you
