### ISSUE TITLE
Anyone try WorldScaleAR_ARF based on ARFoundation

### ISSUE THREAD

**Issue by dhruvmodhapp** [mapbox/mapbox-unity-sdk#1284]
Hello,
I'd try WorldscaleAR_ARF of `ar-foundation port` branch based on ARFoundation instead of ARInterface. But having issue in not getting MapView. Only showing black screen.

Did anyone try WorldscaleAR_ARF for placing objects in AR Space?

**Comment by Dhivyanshup** [comment]
@![1548519662683](https://user-images.githubusercontent.com/45223414/52528724-2f1f9580-2d0b-11e9-85a1-414df23fd0f9.jpg)(http://Dhivyanshuparmhans.com//<>@Dhivyanshuparmhans #1282 

- [on] http://Dhivyanshuparmhans.com/<>Allworld using natworking linking permissions licence for safety government company Pvt Ltd us all world convart dhi natworking devolved project management government us support for linking natworking feeding on display issue convart to sarvar link to us working prosanal us support for linking natworking sat feeding on display in Dhivyanshuparmhans Image sat all computer nat wabsite natworking all world convart to sarvar for sat dhivyanshuparmhanscreen sosal natworking permission link to us all ios"sql"natwork sat on my phone us on the System `dhi natworking [`](http://Dhivyanshuparmhans.com)/All wab"nat"com"for"org"me"used"link"mail using natworking linking permissions licence working on relage my all world convart us alliances saport for Dhivyanshuparmhans warld us on relage god sat in the System my safety warld warking

**Comment by jordy-isaac** [comment]
@dhruvmodhapp Can you provide some screenshots and or more info on how you have your scene configured?
