### ISSUE TITLE
Some buildings ive added in OpenStreetMaps dont appear in CityMap

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1285]
* Mapbox SDK version: 2.0.0
* The platform you're building to: Linux
* A description of what you're trying to do:
Ive added some buildings in OpenStreetMaps in concrete:

Edfici Senna
41°36'22.3"N 0°37'34.1"E
41.606185, 0.626142
But when i execute CityMapSimulator with zoom 17, it doent appear 
* Steps to recreate the bug if appropriate:
Create an CitySimulatorMap, run the game, the building doesnt appear as many others ive added.

Seems many buildings ive added in my hometown, dont appear in citySimulatorMap

Thanks

**Comment by heath3n** [comment]
Mapbox does not immediately pull in all edits to OSM data. Your changes should eventually appear but there is no guarantee of the timeframe in which that will happen.

**Comment by ejgutierrez74** [comment]
any estimated time? i thought mapbox got data from OSM...so if OSM is updated how long would take these changes be in mapbox?
is problem of mapbisñx or problem of OSM?

thanks

**Comment by roura-12** [comment]
I think that you can use the already existing maps of Mapbox for Unity and add buildings using Layer Modifier and SpawnInsideModifier ; see DataExplorer example on how to use those game object modifiers 
![img](https://user-images.githubusercontent.com/7107407/52856606-3092f880-3125-11e9-960f-b1547fcc06e5.PNG)

What do you think about that problem @brnkhy @jordy-isaac

**Comment by ejgutierrez74** [comment]
@roura-12 i was talking that added them in the OSM ( edited and added them to Open Street Maps), so in theory as Mapbox take data from OSM, they should appear almost instantly. Dont know if its some kind of protocol or whatever that can retard the update of the maps...

**Comment by jordy-isaac** [comment]
It can take several weeks for edits to appear on Mapbox maps.

**Comment by ejgutierrez74** [comment]
why?
