### ISSUE TITLE
enable disable map features on runtime

### ISSUE THREAD

**Issue by mujtaba-kiani** [mapbox/mapbox-unity-sdk#1288]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by mujtaba-kiani** [comment]
How to enable/disable the map features on run time,I have added two layers on abstract map name bank and schools both are active on start. now I want to disable one with code. 
<img width="353" alt="screenshot 2019-02-15 at 5 20 51 pm" src="https://user-images.githubusercontent.com/21154214/52856434-351bd900-3146-11e9-90a7-e11ef077b014.png">

**Comment by AzeExMachina** [comment]
If you are assigning those features by code you can simply save the reference of that object, which is a VectorSubLayerProperties and do myProp.SetActive(false). If you also need to get them there are methods inside VectorData like:
- VectorData.FindFeatureSubLayerWithName(string)
- VectorData.GetFeatureSubLayerAtIndex(int)
and many other ways. Then you use SetActive to do what you want

**Comment by mujtaba-kiani** [comment]
Great. I was not creating layers from code. Thank.! it worked for me.
