### ISSUE TITLE
map text gets cut when map is repeated

### ISSUE THREAD

**Issue by asger60** [mapbox/mapbox-unity-sdk#1289]
I'm using the extend options in the abstract map script to repeat the map horizontally. It works but text that are close to the "repeat point" gets cut.
Is there any way to fix this?
<img width="1671" alt="screenshot 2019-02-18 at 09 58 04" src="https://user-images.githubusercontent.com/9567847/52939182-ccaa4300-3363-11e9-88c8-0ffb6da8c747.png">

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@asger60 
this is strange. Your style looks so good that I cannot tell which label is a part of imagery and which one is unity though. assuming labels are from mapbox style imagery, `Bering Sea` label should have been started from correct position (far right edge) as well though. Does it looks correct when you view it on Mapbox studio?
