### ISSUE TITLE
Terrain Elevation and Location based Player is not working together

### ISSUE THREAD

**Issue by q7v6rhgfzc8tnj3d** [mapbox/mapbox-unity-sdk#1290]
My Question is pretty simple I think. I tried to create a 3D Map (Terrain with Elevation). So far so good, but as soon as I started adding a location based Player it went flat on the Ground. So the Problem is that the Player target is not transformed right on the y axis(height). Is there something I am missing ?

TL;DR: I took the "LocationBasedGame" Prefab, changed the Map to "Terrain With Elevation", but the Player Target will not change his Height.

**Comment by q7v6rhgfzc8tnj3d** [comment]
Ok I think I found my luck in the following Hideout ;)


```
using Mapbox.Unity.Map;

AbstractMap map;
Vector3 vector;

// the Vector describing the Point in Unity units.
vector = map.GeoToWorldPosition(Vector2d latitudeLongitude, bool queryHeight = true);
```


I wonder though, why that is not an Option in the "LocationBasedGame" Prefab. If it is I apologise.

**Comment by teechoi** [comment]
I am currently dealing with the same problem as you did. Where did you input this change to control a player in a 3D elevation map?
