### ISSUE TITLE
DeviceLocationProviderAndroidNative shows debug toast messages on device

### ISSUE THREAD

**Issue by nilsk123** [mapbox/mapbox-unity-sdk#1291]
Hi,

I'm using mapbox 2.0.0 in Unity to implement a zoomable map which shows the users current gps location. This works fine, except on the device it shows debug messages for the native location service.

One of these I can find in the script, in getGpsInstance I comment the following line to get rid of the first message:

`_activityContext.Call("runOnUiThread", new AndroidJavaRunnable(() => { _gpsInstance.Call("showMessage", "Starting location listeners"); }));`

There are some additional 'time to first fix' toasts on the device however, which I can't find int he c# side of things. Any way to disable these? it looks really bad.

Unity version: 2018.3.6f1
Scripting runtime version: .net 4.x
Api compat: .net 4.x
Mapbox 2.0.0

**Comment by BergWerkGIS** [comment]
> There are some additional 'time to first fix' toasts on the device however, which I can't find int he c# side of things. Any way to disable these?

No, these come from Android, not from the SDK.

You even get them when starting Google Maps:

![image](https://user-images.githubusercontent.com/4549888/53321907-181b9e80-38da-11e9-8133-18c64171ef2c.png)

**Comment by nilsk123** [comment]
> > There are some additional 'time to first fix' toasts on the device however, which I can't find int he c# side of things. Any way to disable these?
> 
> No, these come from Android, not from the SDK.
> 
> You even get them when starting Google Maps:
> 
> ![image](https://user-images.githubusercontent.com/4549888/53321907-181b9e80-38da-11e9-8133-18c64171ef2c.png)

Thanks for the reply. Thats bizar though, I've never seen these message outside of mapbox projects.

**Comment by BergWerkGIS** [comment]
> Thanks for the reply. Thats bizar though, I've never seen these message outside of mapbox projects.

Agreed, that's weird, but I get them all the time from all kinds of apps.
And my screenshot above is from a device that has nothing Mapbox related installed.

**Comment by nilsk123** [comment]
> > Thanks for the reply. Thats bizar though, I've never seen these message outside of mapbox projects.
> 
> Agreed, that's weird, but I get them all the time from all kinds of apps.
> And my screenshot above is from a device that has nothing Mapbox related installed.

Hi BergWerkGIS,

Sorry to ask about this again, but i've been testing on numerous phones and with numerous apps. The only app showing these notifications is mapbox (or mapbox's native android location provider, to be specific). I can get them too when opening google maps, but ONLY when a mapbox project is still open in the background. 

Again, sorry to reopen this, but i've been testing extensively and I can't reproduce this any other way.

Can this be looked into?

**Comment by BergWerkGIS** [comment]
@nilsk123 I triple checked and the toast `Time to first GPS fix` is not created by the location plugin.

I did make a minuscule change to it tough on how Android's GNSS service is called.
Could you give that a spin: [com.mapbox.android.unity-debug.aar.txt](https://github.com/mapbox/mapbox-unity-sdk/files/2960575/com.mapbox.android.unity-debug.aar.txt)

Remove the `.txt` extension and replace the file here:
https://github.com/mapbox/mapbox-unity-sdk/tree/develop/sdkproject/Assets/Mapbox/Unity/Location/Plugins/Android

**Comment by BergWerkGIS** [comment]
@nilsk123 Do you have the app [GPS Status & Toolbox](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en) installed with the setting `Show time to GPS fix` switched on:

![image](https://user-images.githubusercontent.com/4549888/54267442-879bba00-4579-11e9-80a1-2d74f12003ff.png)

**Comment by nilsk123** [comment]
@BergWerkGIS I'm running the app on a clean out of the box sony xz3 with android 9, no gps status toolbox or other debug tools installed.

That being said, I'm happy to report the new AAR you sent me has resolved the issue :) Everything still works as expected and I don't get the debug toasts anymore.

Thanks for the fast communication!

**Comment by BergWerkGIS** [comment]
@nilsk123 great, glad that I could solve it - it was just a shot in the dark 😄

**Comment by nilsk123** [comment]
One last question! The time to first fix messages have finished, but on some devices theres a 'GPS disabled' toast. This happens when I turn off the screen and then go back to the application. 

![Screenshot_20190315-140452_ByAR Unity](https://user-images.githubusercontent.com/8883990/54433275-c07b9080-472b-11e9-9b81-1e7864f43f4e.jpg)

**Comment by nilsk123** [comment]
So I took the liberty to decompile the AAR/JAR posted above to remove the last toast, here is my patched version. I removed the call to maketoast, rename extension to .aar and overwrite.

[com.mapbox.android.unity-debug.txt](https://github.com/mapbox/mapbox-unity-sdk/files/3224198/com.mapbox.android.unity-debug.txt)

**Comment by Rienhl** [comment]
Have these changes been pushed to a stable release?

**Comment by nilsk123** [comment]
Nope, no release for unity in almost a year now
