### ISSUE TITLE
Enable and Disable layers at run time

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1292]
Hi guys,
I want to let the user enable the layers that hi needed. Is it possible to enable and disable layers at run time using Vector Layer Visualizer scriptable objects and a UI? 
the layers are appeared like this 
![toggle](https://user-images.githubusercontent.com/7107407/53110464-4183a580-353b-11e9-99e0-ddace82054f6.PNG)
and hi choose which layers to appear as needed. 

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: Unity 2017.4.17f1
  * Scripting Runtime Version: Runtime
  * Scripting Backend: C#
  * Api Compatibility Level: 
* Mapbox SDK version: v 2.0.0
* The platform you're building to:  Unity 2017.4.17f1 for PC
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @roura-12 this is possible on version 2.0+. Here's a link to the [api documentation](https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.ILayer.html)

**Comment by roura-12** [comment]
Thanks I'll try that :+1:
