### ISSUE TITLE
Unity SpawnInsideModifier does not work if Unity Tile Size is not 100

### ISSUE THREAD

**Issue by endlessfaith** [mapbox/mapbox-unity-sdk#1294]
Unity Mapbox SDK version: v.2.0.0

I am trying to use the SpawnInsideModifier to spawn trees. But when I set the Unity Tile Size to below 100, the number of trees reduces and once I hit below 9, the trees does not spawn at all. 

![image](https://user-images.githubusercontent.com/14850727/53216797-b3213800-3690-11e9-9315-f23443c06d8f.png)
Tile Size 100

![image](https://user-images.githubusercontent.com/14850727/53216824-d0ee9d00-3690-11e9-80e2-d4708d2cb807.png)
Tile Size 10

![image](https://user-images.githubusercontent.com/14850727/53216855-e5329a00-3690-11e9-8c6e-cf52ba8821cd.png)
Tile Size 1

![image](https://user-images.githubusercontent.com/14850727/53216880-f9769700-3690-11e9-9224-18a105cdf021.png)
My SpawnInsideModifier for reference

Is there anyway to fix this issue? As for my use case I have to set the Unity Tile Size to 0.25.

**Comment by roura-12** [comment]
Hi, even the buildings are not showing nicely; I don't know what is your problem give us more details about what you do. 
For the trees you can see the exemple of the data explorer; I think that your problem is that you spawn a lot of trees a reduced space so reduce the value of maw spawn

**Comment by endlessfaith** [comment]
Hi sorry I forgot to mention that the yellow blocks are placeholders for my trees.

As for my use case I need the Tile Size to be 0.25 so upon setting the Tile Size to that value, the yellow blocks will not spawn at all.

I tried reducing the Tile Size on the data explorer example and am also facing the same issues of the number of bushes reduces as the Tile Size reduces. I cannot set the Tile Size to 0.25 on the data explorer example scene as it freezes up my Unity when I try to run it at that value.

**Comment by roura-12** [comment]
the problem is not on the tile size but try to reduce the number of trees in the tree spawning modifier reduce max spawn and try again; 
I want to know how did you made a park  Mask Layer

**Comment by endlessfaith** [comment]
I tried reducing the max spawn gradually all the way until 1 and it still does not work. 

![image](https://user-images.githubusercontent.com/14850727/53381425-ab70d480-39ab-11e9-99e5-8d12553fe077.png)

![image](https://user-images.githubusercontent.com/14850727/53381445-b9265a00-39ab-11e9-8e46-3f7a34d5eb1e.png)

**Comment by roura-12** [comment]
I think that you have named a new layer in unity layers and attribute it to the forestLayerModifier; there's a difference between unity layers and mapbox layers; you should not attribute the park layer to the ForestLayerModifier; see the data explorer exemple again

**Comment by endlessfaith** [comment]
Hi sorry but I do not see how does that help with my problem. I am able to get the trees (Yellow long cubes) to spawn if you refer back to my first post. 

In any case the the layer modifier works for my scene as you can see below. (They are the one in darker green)
![image](https://user-images.githubusercontent.com/14850727/53611702-731b0180-3c0a-11e9-8982-58767bae0ac9.png)


My problem is the number of trees decreases as I reduce my Unity Tile Size under Abstract Map to below 100, and once it reaches below 9, the trees does not spawn at all. It does the same thing in the data explorer. Also the Scale Down With world does not work too on the data explorer

![image](https://user-images.githubusercontent.com/14850727/53611541-f25c0580-3c09-11e9-9942-4ac28220cd4a.png) This image is when Unity Tile Size is set to 10.

I tried to set the Unity Tile Size to 0.25 in the data explorer, which is the value that I need my map to be at but unfortunately I am not able to run it as for some reason it freezes my Unity every time I hit play.

**Comment by roura-12** [comment]
I recommend you to reduce the max spawn ; it will not exceed the map borders if you increase the tile size as shown in the first figure and will not be too little and unperceived when tile size is 10; this is the problem I think

**Comment by endlessfaith** [comment]
I tried reducing it to 1 and it still does not spawn in my scene with tile size 0.25. I have to wait till monday to test it on the data explorer scene when im back in office. Is there any mapbox developers out there that can help?

**Comment by brnkhy** [comment]
Hello @endlessfaith and @roura-12,
First of all, I'm sorry I don't know how I didn't see this before.
I checked the Spawn Inside modifier and looks like it doesn't take tile scale into account and when you decrease tile size down to 1, it thinks park is around 1 m2 or lower and not able to fit a tree there.
SpawnInside modifier is a very old script, probably written before tile scaling changes and we looked over this bug.

I change script a little like this, I hope it helps for now. We'll look into this more in the future;
```
namespace Mapbox.Unity.MeshGeneration.Modifiers
{
	using Mapbox.Unity.MeshGeneration.Data;
	using Mapbox.Unity.MeshGeneration.Components;
	using UnityEngine;
	using System.Collections.Generic;
	using System;

	[CreateAssetMenu(menuName = "Mapbox/Modifiers/Spawn Inside Modifier")]
	public class SpawnInsideModifier : GameObjectModifier
	{
		[SerializeField]
		int _spawnRateInSquareMeters;

		[SerializeField]
		int _maxSpawn = 1000;

		[SerializeField]
		GameObject[] _prefabs;

		[SerializeField]
		LayerMask _layerMask;

		[SerializeField]
		bool _scaleDownWithWorld;

		[SerializeField]
		bool _randomizeScale;

		[SerializeField]
		bool _randomizeRotation;

		int _spawnedCount;

		private Dictionary<GameObject, List<GameObject>> _objects;
		private Queue<GameObject> _pool;

		public override void Initialize()
		{
			if (_objects == null || _pool == null)
			{
				_objects = new Dictionary<GameObject, List<GameObject>>();
				_pool = new Queue<GameObject>();
			}
		}

		public override void Run(VectorEntity ve, UnityTile tile)
		{
			_spawnedCount = 0;
			var bounds = ve.Mesh.bounds;
			var center = ve.Transform.position + bounds.center;
			center.y = 0;

			var area = (float)(bounds.size.x * bounds.size.z) / tile.TileScale;
			int spawnCount = (int)(Mathf.Min(area / (_spawnRateInSquareMeters * tile.TileScale), _maxSpawn));
			while (_spawnedCount < spawnCount)
			{
				var x = UnityEngine.Random.Range(-bounds.extents.x, bounds.extents.x);
				var z = UnityEngine.Random.Range(-bounds.extents.z, bounds.extents.z);
				var ray = new Ray(center + new Vector3(x, 100, z), Vector3.down * 2000);

				RaycastHit hit;
				if (Physics.Raycast(ray, out hit, 150, _layerMask))
				{
					var index = UnityEngine.Random.Range(0, _prefabs.Length);
					var transform = GetObject(index, ve.GameObject).transform;
					transform.position = hit.point;
					if (_randomizeRotation)
					{
						transform.localEulerAngles = new Vector3(0, UnityEngine.Random.Range(-180f, 180f), 0);
					}
					if (!_scaleDownWithWorld)
					{
						transform.localScale = Vector3.one / tile.TileScale;
					}
					else
					{
						transform.localScale = Vector3.one  * tile.TileScale;
					}

					if (_randomizeScale)
					{
						var scale = transform.localScale;
						var y = UnityEngine.Random.Range(scale.y * .7f, scale.y * 1.3f);
						scale.y = y;
						transform.localScale = scale;
					}

				}
				_spawnedCount++;
			}
		}

		public override void OnPoolItem(VectorEntity vectorEntity)
		{
			if(_objects.ContainsKey(vectorEntity.GameObject))
			{
				foreach (var item in _objects[vectorEntity.GameObject])
				{
					item.SetActive(false);
					_pool.Enqueue(item);
				}

				_objects[vectorEntity.GameObject].Clear();
				_objects.Remove(vectorEntity.GameObject);
			}
		}

		public override void Clear()
		{
			foreach (var go in _pool)
			{
				go.Destroy();
			}
			_pool.Clear();
			foreach (var tileObject in _objects)
			{
				foreach (var go in tileObject.Value)
				{
					if (Application.isEditor && !Application.isPlaying)
					{
						DestroyImmediate(go);
					}
					else
					{
						Destroy(go);
					}
				}
			}
			_objects.Clear();
		}

		private GameObject GetObject(int index, GameObject go)
		{
			GameObject ob;
			if (_pool.Count > 0)
			{
				ob = _pool.Dequeue();
				ob.SetActive(true);
				ob.transform.SetParent(go.transform);
			}
			else
			{
				ob = ((GameObject)Instantiate(_prefabs[index], go.transform, false));
			}
			if (_objects.ContainsKey(go))
			{
				_objects[go].Add(ob);
			}
			else
			{
				_objects.Add(go, new List<GameObject>() { ob });
			}
			return ob;
		}
	}
}
```
