### ISSUE TITLE
Loading times very slow

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1296]
Hello since like past week or two, i noticed mapbox is slower loading map in unity. I dont know if its some update in unity or some servers problems in mapbox.

I have to set the params and positions of characters, because the map wont be able to launch before the character are "on the floor". If the map is not loaded Characters dont have floor and fall infinity down side.

Another option could be modify the abstract map script and that would load on Awake instead of Start methods ( as i understand the awake method is executed before Start)

Also i have the option to load different styles as @jordy-isaac  explained. Im facing that some times i have half style: half of the map or one part with one style, and another parts of the map with other style... I think that all is related with update/loading times. I select the style in a menu before the scene is loaded ( dont change it in runtime)

Hope this would be solved soon.

**Comment by jordy-isaac** [comment]
If you have a test case we can check out we'd love to look into this more. Please email us at support@mapbox.com if so. Thanks!
