### ISSUE TITLE
Never-ending SQLite calls crashes application

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#1297]
* Unity version:  2018.2.15f1
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.0.0
* The platform you're building to: Unity Editor and Windows Standalone

We have a weird bug where Mapbox starts a never-ending loop of _something_ database-related, which ends up crashing our application. 

It's quite hard to debug as it only happens on certain PC's at certain times, and it comes and goes without us really changing anything in code that should trigger it. It happens both in the Editor and in Standalone builds. 

We currently have 3 different AbstractMap components in our scene. Not sure if that has anything to do with it. 

We seem to have tracked it to scripts related to SQLite and cache. 

Here you see the size of the cache file on disk. It increases in size along with the processor usage increasing until it runs out of memory and crashes. 
![image](https://user-images.githubusercontent.com/35730930/53340667-df93b900-3909-11e9-8acd-fd75a2c1369a.png)

This Execute method keeps being called with this input string query being passed in. 
![image](https://user-images.githubusercontent.com/35730930/53341219-44034800-390b-11e9-911f-80899367988a.png)

When we tried commenting out the prune method on line 279 in SQLiteCache.cs, it ended up actually running, though after using 22,5 gb of memory and generating a 135 mb large cache.db file. 
![image](https://user-images.githubusercontent.com/35730930/53342029-626a4300-390d-11e9-8cb3-677f015f55db.png)

The Add method where we commented out the prune method is only being called with the forceInsert bool set to true, which only happens this place: 
![image](https://user-images.githubusercontent.com/35730930/53342904-5da68e80-390f-11e9-801a-a5f0d4cff2b4.png)

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad I don't have a solution at hand but my hunch is that the SQLite calls are just the symptoms and not the root cause /cc @atripathi-mb 

Maybe you could include a full stack trace from when `Excute("DELETE ...")` gets called?
