### ISSUE TITLE
Changing extend option dynamically

### ISSUE THREAD

**Issue by sumitsingh47** [mapbox/mapbox-unity-sdk#1298]
I am changing the extent options from camera bounds to Range Around Transform, i got success by writing these lines in my own script:- 
mapCamera.GetComponent<AbstractMap>().Options.extentOptions.extentType = MapExtentType.RangeAroundTransform;

But after changing that dynamically camera starts the occlusion culling unexpectedly . It is not showing all gameObjects that are in focus of camera.
Should i call more functions of Abstract Map script??

Please describe the method one by one...

Thanks in Advance.

**Comment by jordy-isaac** [comment]
If you're still having trouble with this one can you please send provide some screenshots or a video of what's happening here or at support@mapbox.com?
