### ISSUE TITLE
Move tile coordinate scaling to after modifier executions

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#130]
Feature (buildings, roads, everything in vector data) vertex data is defined in Tile Coordinates which goes from 0 to layer.Extent and to convert that to meters we do a conversion in VectorFeatureUnity constructor. This is done at the begining of VectorLayerVisualizer at the moment.
Problem here is that, these tile coordinates are integer values, if I remember correctly generally between 0-512. But once we convert that to meters, we get float values and run all modifier on these float values as well.
1) Working with integers is easier
2) It guarantees that we're working at the highest possible precision
3) Earcut algorithm uses integer by default, I changed it to use float for now but might cause corner cases.
4) Moving this to end, theoratically, should be easy and not cause too many troubles anyway (all I can think of is, maaaybe the chamfer modifier).

So yes, in general switching to integer for this will be safer and a little probably faster.

**Comment by david-rhodes** [comment]
@brnkhy still an option?

**Comment by brnkhy** [comment]
closing this for now, we can think about this again with mod stack rework
