### ISSUE TITLE
Is tileset geoJSON data parsed and accessible in Unity?

### ISSUE THREAD

**Issue by aumaro-nyc** [mapbox/mapbox-unity-sdk#1300]
Currently, we had the idea to store building data (building name, projects contained within, etc..) in the geoJSON data defined in a Mapbox Studio dataset so that it can be parsed and used to populate a GUI pop-up related with each building.

The closest I have been able to get is accessing a custom defined field in the geoJSON for a building as a Feature data layer filter, but the value returned is the custom defined filter value and not the value stored in the geoJSON string. (This was within the AbstractMap.cs script)

So far, I have not been able to verify if the geoJSON data is actually accessible from a tileset within Unity. If it is, I am curious to know what script handles the parsing of the data so that we can attempt to save the custom building data fields when the geoJSON is initially parsed.

Any help or tips would be greatly appreciated! Thanks

**Comment by colin-young** [comment]
Take a look at the data explorer example, specifically https://github.com/mapbox/mapbox-unity-sdk/blob/f7e29dc65e75b545eae1d7bc5265e31033d8e3bf/sdkproject/Assets/Mapbox/Examples/Scripts/FeatureUiMarker.cs#L75. That shows how to read the data.

**Comment by pkennedysolspec** [comment]
I found may way to this line on my own, but although I have data properties in my custom data this line creates an error on custom objects.
