### ISSUE TITLE
Display area and scale it by zoomable map

### ISSUE THREAD

**Issue by fred37000** [mapbox/mapbox-unity-sdk#1303]
Hello,

I develop a game with Unity 2018.3 and Mapbox V2.0.0 for find a POI in zoomable map.
i tried to displayed a circle area (~150meters) around a middle of POI.
And after, i wish to scale gameobjects spawned (circle of area for exemple) compared with zoom map.

Thanks for reading and future responses.

**Comment by jordy-isaac** [comment]
Can you let us know more about your use case? Have you taken a look at how we're scaling the markers in the [ZoomableMap example](https://docs.mapbox.com/unity/maps/examples/zoomable-map/#place-custom-markers)?

If you need additonal help please email us at support@mapbox.com
