### ISSUE TITLE
"Mapbox" Menu not appearing after importing package

### ISSUE THREAD

**Issue by tpolong** [mapbox/mapbox-unity-sdk#1304]
Unity version: 
  * Scripting Runtime Version: Unity 2018.3.7f1
* Mapbox SDK version: mapbox-unity-sdk_v2.0.0.unitypackage
* The platform I'm building to:windows 10
![image](https://user-images.githubusercontent.com/13393721/53936652-897efc80-40e5-11e9-9d0e-114776e63807.png)
"Mapbox" menu does not appear after importing. The full asset folder is available.

**Comment by roura-12** [comment]
[https://www.mapbox.com/install/unity/](url)  you should add token see the installation guide

**Comment by tpolong** [comment]
![image](https://user-images.githubusercontent.com/13393721/54083868-45e5f600-4364-11e9-9b97-f2ba9b8b4994.png)
It still has the same errors

**Comment by roura-12** [comment]
[https://forum.unity.com/threads/mapbox-import-problem.639760/](url)   I think that it is a problem related to unity 2018 swap to unity 2017

**Comment by jordy-isaac** [comment]
If you're still having this trouble with the latest version of Unity and 2.0 of the SDK, please let us know at support@mapbox.com

**Comment by xiaoliyong** [comment]
@tpolong  have you solved this problem?

**Comment by tpolong** [comment]
@xiaoliyong I used the 2017 unity,could solved this problem

**Comment by xiaoliyong** [comment]
@tpolong   are you used unity 2017 + mapbox-unity-sdk_v2.0.0?   i used sdk 1.3 which can suited unity 2019.

**Comment by tpolong** [comment]
I just tested unity 2017 + mapbox-unity-sdk_v2.0.0 and unity 2018 + mapbox-unity-sdk_v2.0.0.
