### ISSUE TITLE
null error when toggling vector features 

### ISSUE THREAD

**Issue by djzielin** [mapbox/mapbox-unity-sdk#1311]
VectorTileFactory.cs around line 416 needs a null check on the tile.VectorData
otherwise get errors when we toggle the features on/off

if (layerName != "")
{
     if(tile.VectorData!=null)
           builder.Create(tile.VectorData.Data.GetLayer(layerName), tile, DecreaseProgressCounter);
}

**Comment by jordy-isaac** [comment]
Thanks for pointing this out @djzielin

**Comment by brnkhy** [comment]
Hello @djzielin ,
Do you mean toggling vector layers from checkboxes? I tried it with the latest and couldn't recreate it so I think it's fixed (and will be in the next version very soon) or I misunderstood it.
Thanks!

**Comment by djzielin** [comment]
Problem happened when toggling while running.

**Comment by Kisamegr** [comment]
Hello, this issue still exists as of today. I created another issue explaining in detail how I got it #1572

**Comment by caraneel** [comment]
I also got this issue, but adding the null check as suggested by @djzielin worked for me.
