### ISSUE TITLE
AR Foundation roadmap?

### ISSUE THREAD

**Issue by linojon** [mapbox/mapbox-unity-sdk#1314]
Hello, i'm toying with the "ar-foundation-port" branch (in Unity 2018.3.x). Successfully built and run the TabletopAR_ARF example scene. What is the roadmap for its release?

**Comment by jordy-isaac** [comment]
We will release it in a future version, but it won't be in the next release and we don't quite have a date for it at this time. We have the branch up for use in the meantime.
