### ISSUE TITLE
Il2cpp build failed  2018.3.8f1

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [mapbox/mapbox-unity-sdk#1315]
* Unity Version 2018.3.8f1: 
* Scripting Runtime Version: .NET4x Equivalent
* Scripting Backend: IL2CCP
* Api Compatibility Level: .Net4 / .net Standard 2.0
* Mapbox SDK version: 2.0
* The platform you're building to: Android
* A description of what you're trying to do: Build and Run
* Steps to recreate the bug if appropriate:

Create a new Unity project, Create an empty scene with a camera, add a scene to build settings, Import mapbox latest SDK, add activation key set player settings and switch platform click build and run.

Tested both on Windows and Mac same issue

Failed running C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Debug" --outputpath="D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a\libil2cpp.so" --cachedirectory="D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Assets\..\Library\il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Users/edgar/AppData/Local/Android/Sdk/android-ndk" --map-file-parser="C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --directory="D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\assets\bin\Data\Managed" --generatedcppdir="D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput" 

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a
	Cache directory: D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Library\il2cpp_android_arm64-v8a\il2cpp_cache
ObjectFiles: 649 of which compiled: 212
	Time Compile: 7040 milliseconds Il2CppTypeDefinitions.cpp
	Time Compile: 5693 milliseconds Il2CppAttributes.cpp
	Time Compile: 5538 milliseconds Il2CppInvokerTable.cpp
	Time Compile: 3735 milliseconds Bulk_System.Xml_12.cpp
	Time Compile: 3591 milliseconds Il2CppMetadataUsage.cpp
	Time Compile: 3386 milliseconds Bulk_Mapbox.Json_2.cpp
	Time Compile: 3363 milliseconds Bulk_System.Data_3.cpp
	Time Compile: 3336 milliseconds Bulk_Assembly-CSharp_2.cpp
	Time Compile: 3243 milliseconds Bulk_Generics_22.cpp
	Time Compile: 3204 milliseconds Bulk_System.Data_6.cpp
Total compilation time: 52025 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\edgar\AppData\Local\Temp\tmp2A30.tmp" -o "D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Library\il2cpp_android_arm64-v8a\il2cpp_cache\linkresult_FB18192EC6CDC079CC56877D6352EB78\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\platforms\android-21\arch-arm64" -gcc-toolchain "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64" -target aarch64-none-linux-android -Wl,--wrap,sigaction -L "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\sources\cxx-stl\gnu-libstdc++\4.9\libs\arm64-v8a" -lgnustl_static -llog -rdynamic -fuse-ld=bfd.exe

D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARFaceAnchor_GetBlendShapesInfo_m5DD3AE08B9E8E02939D0A735EDCE0924C566EBB2':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:22441: undefined reference to `GetBlendShapesInfo'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARKitFaceTrackingConfiguration_IsARKitFaceTrackingConfigurationSupported_mB5D4CE5AB3137E3D4F9A4ADC1B4C305FFD5BD809':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:23166: undefined reference to `IsARKitFaceTrackingConfigurationSupported'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARKitSessionConfiguration_IsARKitSessionConfigurationSupported_m57D612BE00CF16CBB1147230EAB6C5354D63020E':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:23274: undefined reference to `IsARKitSessionConfigurationSupported'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARKitWorldTrackingSessionConfiguration_IsARKitWorldTrackingSessionConfigurationSupported_mA6A1B57A1C699B9D13F466338606B502E0F0A029':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:23392: undefined reference to `IsARKitWorldTrackingSessionConfigurationSupported'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_unity_CreateNativeARSession_mA7A42AA6FE4382CBC8F45651D8B7E4020D0EF428':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27109: undefined reference to `unity_CreateNativeARSession'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_session_SetSessionCallbacks_m3FEEA43450102F375BDE989A55320EB8522D5238':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27140: undefined reference to `session_SetSessionCallbacks'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_session_SetPlaneAnchorCallbacks_m5CE4D9A6B9B87734231FDCA367B160377859D3DC':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27162: undefined reference to `session_SetPlaneAnchorCallbacks'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_session_SetUserAnchorCallbacks_mD7B56925E1E1931A50219C18E84F4C7271F005B1':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27184: undefined reference to `session_SetUserAnchorCallbacks'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_session_SetFaceAnchorCallbacks_mF807BBBB8636383BE08C3497B9A67BAD4F45FF00':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27206: undefined reference to `session_SetFaceAnchorCallbacks'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartWorldTrackingSession_mCC27A1E2D4DDA42120C0BE3D6FDF5DE5FCBF997A':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27222: undefined reference to `StartWorldTrackingSession'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartWorldTrackingSessionWithOptions_mE0440B192425A3593D7E4461EBF4537494C63CE7':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27241: undefined reference to `StartWorldTrackingSessionWithOptions'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartSession_m6D02A743FBAFAD5EAFC2DDFA0E8B3B4F3FB43589':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27260: undefined reference to `StartSession'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartSessionWithOptions_m468A75438913905FDF44A75D6995881F18088DC2':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27279: undefined reference to `StartSessionWithOptions'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartFaceTrackingSession_mAF0B430D694EBB7E3369EEBC6D1C232922865033':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27298: undefined reference to `StartFaceTrackingSession'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_StartFaceTrackingSessionWithOptions_m72BDAF7253FD70011C6C6EAF0FD6481215B5460D':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27317: undefined reference to `StartFaceTrackingSessionWithOptions'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_PauseSession_mE36D084AB4C4B6A30A01226F998C49D2118132BD':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27330: undefined reference to `PauseSession'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_HitTest_m7D7351903A27A634A48635E33D5FECA8E65CE483':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27340: undefined reference to `HitTest'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_GetLastHitTestResult_m0F447BA89362A145E46E5724CBB7055F1ED734F7':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27353: undefined reference to `GetLastHitTestResult'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_GetVideoTextureHandles_m6BFFD6A9B0C363855A7F1ECADBBB29132771BCB3':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27372: undefined reference to `GetVideoTextureHandles'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_GetAmbientIntensity_mE42C6620DED241FAE2718E809DB3728A42FA50AA':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27383: undefined reference to `GetAmbientIntensity'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_GetTrackingQuality_m5001CEB636AFFBB5D6DCB909EAC63E81E5AFB57E':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27394: undefined reference to `GetTrackingQuality'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_GetARPointCloud_m446BDD6EAE392644E1A218324AD1856DF3037080':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27405: undefined reference to `GetARPointCloud'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_SetCameraNearFar_m300A89711AE2D3F3F97B14689D8D968064440EC3':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27416: undefined reference to `SetCameraNearFar'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_CapturePixelData_mB5D95348F0F9D895F8B30C336BB87B5371F45711':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27426: undefined reference to `CapturePixelData'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_SessionAddUserAnchor_m99EACE0AFE3101DBB8B4A97CEF33CC0150EBF91B':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27436: undefined reference to `SessionAddUserAnchor'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `UnityARSessionNativeInterface_SessionRemoveUserAnchor_mFA8F64EEA3398B586F450EDBADC9BB68EFA921E6':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:27451: undefined reference to `SessionRemoveUserAnchor'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\edgar\AppData\Local\Temp\tmp2A30.tmp" -o "D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Library\il2cpp_android_arm64-v8a\il2cpp_cache\linkresult_FB18192EC6CDC079CC56877D6352EB78\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\platforms\android-21\arch-arm64" -gcc-toolchain "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64" -target aarch64-none-linux-android -Wl,--wrap,sigaction -L "C:\Users\edgar\AppData\Local\Android\Sdk\android-ndk\sources\cxx-stl\gnu-libstdc++\4.9\libs\arm64-v8a" -lgnustl_static -llog -rdynamic -fuse-ld=bfd.exe

D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARFaceAnchor_GetBlendShapesInfo_m5DD3AE08B9E8E02939D0A735EDCE0924C566EBB2':
D:\Work\Scape\_ProjectStash\Unity\ScapeKitPlayground\Temp\StagingArea\Il2Cpp\il2cppOutput/Bulk_Assembly-CSharp_7.cpp:22441: undefined reference to `GetBlendShapesInfo'
D:/Work/Scape/_ProjectStash/Unity/ScapeKitPlayground/Library/il2cpp_android_arm64-v8a/il2cpp_cache/7BEDE609753E7490FD39750A84789021.o: In function `ARKitFaceTrackingConfiguration_IsARKitFaceTrackingConfigurationSupported_mB5D4CE5AB3137E3D4F9A4ADC1B4C305FFD5BD809':
: 

===========================================

Exception: C:\Program Files\Unity\Hub\Editor\2018.3.8f1\Editor\Data\il2cpp/build/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:368)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (System.String inputDirectory, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:349)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:211)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <df7ba4d130594d168eec372b930522d4>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <df7ba4d130594d168eec372b930522d4>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <df7ba4d130594d168eec372b930522d4>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <df7ba4d130594d168eec372b930522d4>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:286)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by tjukic** [comment]
Have the very same issue lately.

**Comment by Edgar-BlipparDev** [comment]
Ok Found a workaround leaving for anyone that run into same issue. I suspect issue is not with Mapbox but with Arkit.

If you have the project with AR Core and ArKit and the platform you are compiling to is Android you will run into issue IL2CP failed. I suspect ARKit is not checking somewhere if compiling is happening for Android or IOS based on:

ARKitFaceTrackingConfiguration_IsARKitFaceTrackingConfigurationSupported_m021C73A4F853ED9BE3F12B39F9359B0F2DCAFFC1.

To replicate issue download Mapbox run in Unity with IL2CP it will always fail:

To work around the issue I had to remove any reference of ARKit from the project when compiling for Android and put it back when I am compiling for IOS. This is not ideal but it will work. Of course when compiling for IOS put arkit back in.

**Comment by tjukic** [comment]
It's pretty much everywhere. You can't simply remove it? All examples, SDK source, everywhere. Clean ARCore and ARKit usage are fine otherwise.

**Comment by brnkhy** [comment]
Thanks a lot for the ticket AND the solution @Edgar-BlipparDev  🙏

**Comment by AlekseiBo** [comment]
How come this issue is closed? The workaround isn't clear, a have extra errors when deleting the ARKit folder. Without il2CPP support, you cannot publish to Google Play. It is ridiculous.

**Comment by branko88** [comment]
Agreed that the workaround isn't clear. Struggling with this for a while now. After deleting the ARKit folder, unity throws error on all scripts in ARRemote, including ARKitInterface.cs. Deleting those too results in the AR Root camera not occupying the phones camera when launching for android. @brnkhy can this be further explored?

**Comment by cheesemichael** [comment]
after deleting ARKit plugin and some scrips IOS related.  i can build IL2CPP for Arm7 and x86 and it works fine. B
ut when i enable x64  the camera will not work

**Comment by AbrarAmin1** [comment]
> after deleting ARKit plugin and some scrips IOS related. i can build IL2CPP for Arm7 and x86 and it works fine. B
> ut when i enable x64 the camera will not work

@cheesemichael did you find the solution for it?

**Comment by Markovicho** [comment]
> Thanks a lot for the ticket AND the solution @Edgar-BlipparDev 🙏

Sorry but I don't see a real solution over here. Could you please re-open the issue ?

**Comment by brnkhy** [comment]
Hey, sorry I wasn't aware the issue persists. I thought original poster solved it already. Reopening.

**Comment by saszer** [comment]
will mapbox fix this for upper unity versions?

**Comment by Bullseye25** [comment]
**SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix Black Camera problem

Hi Everyone,

This solution works 100%.

DO NOT USE the default AR Controller script that is default in Mapbox (disable it)
Update the latest Unity ARcore SDK
At AR Root - use AR Core Session Script as the new AR Controller (comes with latest Unity ARCore SDK)
AR Camera - Use Track Pose Driver for tracking movement, AR Core Background Renderer for rendering camera view (comes with latest UnityARCore SDK)
Graphics API - OpenGLES2, OpenGLES3 both works
Make sure you have a 64 bit libarcore_camera_utility
** lemme know if it works for you**

**SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix build errors

And while waiting for Devedse's awesome ARKit update to fix the 64bit IL2CPP build errors, you can do this

Hi, while we wait for the AR Kit fix. you can do this

delete UnityARKitPlugin folder
delete UnityARInterface/ARRemote folder
3)delete UnityARInterface/Examples/ARFocusSquare folder
4)delete UnityARInterface/Scripts/ARKitinterface.cs
build again...

** to reverse these steps, import the mapbox-unity-sdk_v2.1.1 again

Ref: https://github.com/mapbox/mapbox-unity-sdk/issues/1459

**Comment by iliasmour** [comment]
> **SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix Black Camera problem
> 
> Hi Everyone,
> 
> This solution works 100%.
> 
> DO NOT USE the default AR Controller script that is default in Mapbox (disable it) Update the latest Unity ARcore SDK At AR Root - use AR Core Session Script as the new AR Controller (comes with latest Unity ARCore SDK) AR Camera - Use Track Pose Driver for tracking movement, AR Core Background Renderer for rendering camera view (comes with latest UnityARCore SDK) Graphics API - OpenGLES2, OpenGLES3 both works Make sure you have a 64 bit libarcore_camera_utility ** lemme know if it works for you**
> 
> **SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix build errors
> 
> And while waiting for Devedse's awesome ARKit update to fix the 64bit IL2CPP build errors, you can do this
> 
> Hi, while we wait for the AR Kit fix. you can do this
> 
> delete UnityARKitPlugin folder delete UnityARInterface/ARRemote folder 3)delete UnityARInterface/Examples/ARFocusSquare folder 4)delete UnityARInterface/Scripts/ARKitinterface.cs build again...
> 
> ** to reverse these steps, import the mapbox-unity-sdk_v2.1.1 again
> 
> Ref: #1459

Hi @Bullseye25, I followed your steps but now I have a problem with  the 3D model which I use. It is always stuck in the screen like it is a UI object on canvas. It is not anchored in the real world. 
I can assume that the problem has to do with the AR Remote controller, because ARCameraCompassAlignment needs it.
Do you have any solutions on this issue?

**Comment by iliasmour** [comment]
> **SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix Black Camera problem
> 
> Hi Everyone,
> 
> This solution works 100%.
> 
> DO NOT USE the default AR Controller script that is default in Mapbox (disable it) Update the latest Unity ARcore SDK At AR Root - use AR Core Session Script as the new AR Controller (comes with latest Unity ARCore SDK) AR Camera - Use Track Pose Driver for tracking movement, AR Core Background Renderer for rendering camera view (comes with latest UnityARCore SDK) Graphics API - OpenGLES2, OpenGLES3 both works Make sure you have a 64 bit libarcore_camera_utility ** lemme know if it works for you**
> 
> **SOLUTION for Mapbox/ARCore/64Bit/IL2CPP) - to fix build errors
> 
> And while waiting for Devedse's awesome ARKit update to fix the 64bit IL2CPP build errors, you can do this
> 
> Hi, while we wait for the AR Kit fix. you can do this
> 
> delete UnityARKitPlugin folder delete UnityARInterface/ARRemote folder 3)delete UnityARInterface/Examples/ARFocusSquare folder 4)delete UnityARInterface/Scripts/ARKitinterface.cs build again...
> 
> ** to reverse these steps, import the mapbox-unity-sdk_v2.1.1 again
> 
> Ref: #1459

Can you be more specific about this?
"""AR Camera - Use Track Pose Driver for tracking movement""" 
There are many options that have to be defined (Device, Pose Source, Tracking Type etc.)
