### ISSUE TITLE
The player can have access to any feature layer and modify it

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1317]
Hi, There. In the game that I am developping currently, I want to let the player modify feature layers inside the game. 
For example, if i spawn cars in the road layer; how to let the player modify the number of cars their functionnatilities when playing; how can I as a developer use a UI and a script for example to    
add that. 
The second question that is related to this issue is how can we modify the scriptable objects (the game object modifiers (e.g the feature behaviour modifier, the prefab modifier, the loft modifier , etc.)

* Unity version: 2017.4.17f1
 * Mapbox SDK version: 2.0.0
@jordy-isaac  @brnkhy @atripathi-mb

**Comment by jordy-isaac** [comment]
@roura-12 thanks for the ticket. 

As for the first question you might want to use a `AddMonoBehaviorsModifer` and wire a UI that you want a player to use to a UI canvas.

To make custom modifiers, you can use the ones in the SDK, make your customizations and save it with a new name. 

Create a modifer using the Mapbox Menu by right clicking:
<img width="688" alt="Screen Shot 2019-03-31 at 11 31 44 PM" src="https://user-images.githubusercontent.com/33474236/55307708-31e65f00-540d-11e9-888b-6d436ec877e6.png">

After that you can use the `Add Existing` option in the UI to add the newly created modifer to the layer.

<img width="807" alt="custom-modifier" src="https://user-images.githubusercontent.com/33474236/55307974-0fa11100-540e-11e9-95dd-66b2b15f813b.png">

**Comment by roura-12** [comment]
thanks a lot.
