### ISSUE TITLE
Position of other players

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1318]
Hi, 

I made a little location based game, in which multiple players walk over a playing field. I'd like to display every players location selectively. 

My approach is to send lat/lon for each player to a db and then pull those infos - convert them to geojson and display them. 

If this is indeed the best way, could you give me a hint how to convert the geojson into a game object?

**Comment by roura-12** [comment]
Hey, I think that the best way of creating a db of players lat/lon is using scriptable object , see these tutorials they may help you
[https://www.youtube.com/watch?v=TLVf4ky7I3k&t=174s](url)
[https://www.youtube.com/watch?v=SNwPq01yHds&t=285s&pbjreload=10](url) 
but I don't know how to convert to geojson the data 
I hope that I help you

**Comment by Schaggo** [comment]
Hey, thanks for the reply!
Scripting the object isn't really the problem. 
Currently I pull lat/lon for a specific player and want to move it in reference to the map. 
I am still struggling to use MoveToGeocoordinate correctly. 

`PlayerMarker.transform.MoveToGeocoordinate( new Vector2d(PlayerLat,PlayerLon), new Vector2d(0, 0), 1);`

seems to move the `PlayerMarker` but not to the desired position. I guess that my reference point `new Vector2d(0,0)` isn't correct. Well, I'm a noob and mistaking completely...

**Comment by Schaggo** [comment]
Got it.
```
float worldScale = FindObjectOfType<AbstractMap>().WorldRelativeScale;
        Vector2d mapCenter = FindObjectOfType<AbstractMap>().CenterMercator;
```

**Comment by Mahado18** [comment]
Were those 2 lines enough to display all the players on the map?also if what you were doing there is a multiplayer geolocation game i dont see how you are making it a multiplayer game that way without using a server and sending infos to it?also i dont get it why you didnt just use the location provider ?

**Comment by Schaggo** [comment]
Sorry man, this is 4 year old code. I’m not the brightest now, I certainly was dumber back then. 

Let me see if I can figure out what you mean.

i can’t remember what the location provider exactly does. 
but indeed, this is a multiplayer game which since has switched to a complete different framework.

you are correct, every player sends ID, lat, and Lon to a database which the admin can access and display all current players. 
Do you need some help with something?

**Comment by Schaggo** [comment]
I vaguely remember that there was a problem with the location provider on specific devices. If I remember correctly I had to use a hack specifically for either huawei or the other Chinese guys… this might have been a way to circumvent something like rapid access to the provider… not sure though.

**Comment by Mahado18** [comment]
But could you position all of the players of the data base on the map juat by using those 2 lines?(or what are those 2 lines supposed to do?)

**Comment by Schaggo** [comment]
Sure! The simple version would be a for loop
For items in dataset create new template object and you’re  good

**Comment by Mahado18** [comment]
But does the position of all the players get updated corectly on the map while they are moving using this method?

**Comment by Mahado18** [comment]
Schbaggo, bro do you want to team up with me on my unity multiplayer mapbox AR project? , i am developing an app for a university in spain ,i have it all figured out except for the multiplayer part,i have no idea how to spawn each device location on the map and make it so each player can see the other player on the map in real time, can you help me?

**Comment by Schaggo** [comment]
Sorry no time. Here's the rundown of what you have to do: 

Each player sends his lat/lon to a database for an item that gets constantly overwritten or stores the local time. So, for example:  Id = "Player1", TimeZone = "GMT+2". localTime ="16:52",  Lat="3.9xxxxxxx", Lon ="lonvalue"

You update those values from the client side to the server and then pull the values back. You can either do this per player or for all players via your database. I'd suggest SQL as - while it is a bit ugly to write - is basically free on any website server. 

After this you asynchronously check for updates and if there is any: 
A) Move all player positions where the new position is not equal to the old position to the new position, or
B) kill all game objects representing players and spawn new game objects for each player. 

That's it
