### ISSUE TITLE
Q:Can third-party TMS services be loaded?

### ISSUE THREAD

**Issue by WorldInMine** [mapbox/mapbox-unity-sdk#1326]
Hello, I just started learning mapbox, I want to ask if (mapbox for untiy sdk) can use third-party map services such as TMS, WMS services (Argis). I want my application to be used offline, and I look forward to your reply.

**Comment by jordy-isaac** [comment]
There isn't support for it by default, but if you can get your data uploaded to Mapbox, you can bring it in as a [custom tileset](https://docs.mapbox.com/unity/maps/overview/custom-maps/#use-custom-data). As for offline mapping, we currently have ambient caching. Offline mapping is a feature that we're currently looking into.
