### ISSUE TITLE
Getting coordinates of Points of Interest

### ISSUE THREAD

**Issue by GeorgiKostov** [mapbox/mapbox-unity-sdk#1328]
Hey all,

I have looked through the Unity SDK and the forums for a while now, but didn't find any way to do it so I am asking here as a last ditch effort.

I am spawning a POI prefab for nearby locations and I need to know  coordinates for my game logic. The closest I came is by using the PrefabModifier.cs - I can add a reference to the script that's on the prefab I spawn and this way I can access all data that the PrefabModifier provides. I still can't figure out how to get the coordinates of the spawned prefab. 

It would also suffice to simply get a list of all POI coordinates - I just need the closest one to spawn a location prefab that I can interact with.

Thanks in advance!

**Comment by brnkhy** [comment]
Hey @GeorgiKostov 
Prefab modifier is actually a good place to start. But you'll be getting features one by one (so might be a little tricky to find closest) and poi positions will be all converted to Unity space at that point.
Still you can convert world space position to latlng using 'Conversions' class. And to find the closest, you can cache all incoming features in a list, when pick the closest when map/tile is all loaded.

Another way would be; if you want to get your hands dirty, interjecting at vector factory level where you have all features in one list. That might be a little more advanced though.

**Comment by sutee9** [comment]
I cannot find this conversion function you are referring to. I am spawning the prefabs, but how do I manage to label them after? I can not differentiate anymore which is which. I spent quite some time on this, and am not finding answers.
