### ISSUE TITLE
On Android 7.0 not able to use GPS

### ISSUE THREAD

**Issue by lezan** [mapbox/mapbox-unity-sdk#1330]
* Unity version: 2018.3.11f1
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.0.0
* The platform you're building to: Android (minimum API level Android 7.0 'Nougat" (API level 24).
* A description of what you're trying to do: I am not able to get GPS coordinates on Android 7.0.

Hello,
I am try to use Mapbox SDK to get long a lat to update player position on map, but I am not able to make it working on Android 7.0 (but on Android 9.0 is working). Now I am using LocationProvider scene, but I get IsLocationServiceEnabled equals to false (location 0, 0).
My App example in Android is allowed to use Location services (and Location services is also active).
Is Mapbox SDK not able to run on Android 7 (API 24)?

Thanks.

**Comment by brnkhy** [comment]
cc @atripathi-mb @jordy-isaac
