### ISSUE TITLE
Android ARM64 Support - SOLUTION

### ISSUE THREAD

**Issue by dorukeker** [mapbox/mapbox-unity-sdk#1331]
Hello All,

This is not an issue but rather the solution.
Google is enforcing 64-bit support for Android apps on Google Play, starting from August 1st.

Mapbox is using sqlite3 and the current version does not have the 64bit support. So currently if you turn on the 64 bit support in Unity, you will end up with a black screen.

The solution is to build the arm64 version of the sqlite3 and add this to the project.
Though I have already build it so I attach to this post.
Here are the steps:
- Download the attached zip file [arm64-v8a.zip](https://github.com/mapbox/mapbox-unity-sdk/files/3059629/arm64-v8a.zip)
- Copy the folder arm64-v8a under /Assets/Mapbox/Plugins/Android/libs/ (so you have /Assets/Mapbox/Plugins/Android/libs/arm64-v8a/)
- This folder contains libsqlite3.so
- Select this in Unity and in the inspector update the import settings. Platform: Android, CPU: ARM64
- Click Apply

This should solve that issue. If for some reason you need to build your own sqlite3 dll instead of using the ZIP file follow the instructions here https://ornithoptergames.com/how-to-set-up-sqlite-for-unity/#3androidsupport

@Mapbox: I suggest you add this to your Unity package. This is not anymore a good-to-have.

I hope this helps some one.
Cheers,
Doruk

**Comment by atripathi-mb** [comment]
@dorukeker Thanks for pointing this out and contributing to the SDK. Really appreciate it. We will update the sqllite library in the next release.

**Comment by mikavaliviita** [comment]
> * Download the attached zip file [arm64-v8a.zip](https://github.com/mapbox/mapbox-unity-sdk/files/3059629/arm64-v8a.zip)

Anyone else having problem with this?
**Unable to find main** is shown on logcat when running app compiled for arm64.

**Comment by BAAKILI1987** [comment]
is ther a solution for adobe air ! (flash builder or develepper) ?
thanks !!

**Comment by brnkhy** [comment]
@dorukeker @atripathi-mb 
I pushed arm64 solution here; https://github.com/mapbox/mapbox-unity-sdk/pull/1365

`Anyone else having problem with this?` 
I havent been able to test though. cc @atripathi-mb @jordy-isaac for android tests

`is ther a solution for adobe air ! (flash builder or develepper) ?`
Unity does adobe air builds?

**Comment by tallaaja** [comment]
Thank you my dude! You saved the day

**Comment by bhermer** [comment]
Life saver :)

**Comment by psymatrix** [comment]
Works for me! Thank so much!

**Comment by jeuxdaily** [comment]
hi
how can i do with adobe air
thanks

**Comment by bugracoskun** [comment]
I'm still getting error. I have used Mapbox 2.0.1. 

What am i doing wrong?

**Comment by panosdrak** [comment]
Thank you!! You just saved my app. I coudn't update it. I am wondering why MapBox haven't released an update yet.

**Comment by cheesemichael** [comment]
the new version of Mapbox Unity SDK actually  incorporated dorukeker solution. But i am still getting a black screen.  when i switch back to mono 32 bit.. it all works well.

i followed all instructions

Select this in Unity and in the inspector update the import settings. Platform: Android, CPU: ARM64
Click Apply

**also had to remove ARKit Plugin to remove all the "undefined reference" errors

**Comment by cheesemichael** [comment]
latest update.. 

Unity3D, backend scripting is IL2CPP.  when building Arm7 or x86 on IL2CPP it builds and work well.  When i build 64bit, the camera view goes black.  Any ideas ?

**Comment by Claverias4** [comment]
@dorukeker Thanks for this. it's work for me!!!

**Comment by siddharth3322** [comment]
> Hello All,
> 
> This is not an issue but rather the solution.
> Google is enforcing 64-bit support for Android apps on Google Play, starting from August 1st.
> 
> Mapbox is using sqlite3 and the current version does not have the 64bit support. So currently if you turn on the 64 bit support in Unity, you will end up with a black screen.
> 
> The solution is to build the arm64 version of the sqlite3 and add this to the project.
> Though I have already build it so I attach to this post.
> Here are the steps:
> 
> * Download the attached zip file [arm64-v8a.zip](https://github.com/mapbox/mapbox-unity-sdk/files/3059629/arm64-v8a.zip)
> * Copy the folder arm64-v8a under /Assets/Mapbox/Plugins/Android/libs/ (so you have /Assets/Mapbox/Plugins/Android/libs/arm64-v8a/)
> * This folder contains libsqlite3.so
> * Select this in Unity and in the inspector update the import settings. Platform: Android, CPU: ARM64
> * Click Apply
> 
> This should solve that issue. If for some reason you need to build your own sqlite3 dll instead of using the ZIP file follow the instructions here https://ornithoptergames.com/how-to-set-up-sqlite-for-unity/#3androidsupport
> 
> @mapbox: I suggest you add this to your Unity package. This is not anymore a good-to-have.
> 
> I hope this helps some one.
> Cheers,
> Doruk

This is worked for me :)
Thank you for your help.

**Comment by daijiangping** [comment]
Download the attached zip file arm64-v8a.zip, the download link is invalid!

**Comment by siddharth3322** [comment]
> Download the attached zip file arm64-v8a.zip, the download link is invalid!
this link does not have any problem
![64bit_sqlite](https://user-images.githubusercontent.com/3082151/71157740-9df14780-2268-11ea-8a70-83c21ed5b17e.png)

**Comment by daijiangping** [comment]
Thank you very much! Seems to be my network problem, can download




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Siddharth"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 下午4:35
收件人: "mapbox/mapbox-unity-sdk"<mapbox-unity-sdk@noreply.github.com&gt;; 
抄送: "不变的只有音乐"<1690351001@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [mapbox/mapbox-unity-sdk] Android ARM64 Support - SOLUTION (#1331)



 
下载附件的zip文件arm64-v8a.zip，下载链接无效！
 这个链接没有任何问题
 
  
— 
您收到此评论是因为您发表了评论。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by saidburhan** [comment]
Thank you Doruk.. 

İsim Türkçe olunca belki Türkçe de biliyorsundur diye böyle de yazayım dedim. Çok teşekkür ediyorum iki gündür çözemediğim meseleyi bir iki klasör açarak hallettim sayende.

**Comment by dorukeker** [comment]
> Thank you Doruk..
> 
> İsim Türkçe olunca belki Türkçe de biliyorsundur diye böyle de yazayım dedim. Çok teşekkür ediyorum iki gündür çözemediğim meseleyi bir iki klasör açarak hallettim sayende.

You are welcome. Rica ederim. Glad that it helped!

**Comment by alex78420** [comment]
What if i dont have MapBox installed?

**Comment by Webee-JC** [comment]
> What if i dont have MapBox installed?

but why?
