### ISSUE TITLE
All of the example projects are having issues when I play them on my android phone.

### ISSUE THREAD

**Issue by claytonc123** [mapbox/mapbox-unity-sdk#1338]
Not a single example project works %100 on my android device when there is no reason why it shouldn't be. ARCore is installed on my phone, "ARCore supported" is checked in the project settings, I allow the apps to use my camera and location, and my phone is in great condition. I have no idea what the problem is. Every single project.

The visuals are there, like the 3D models of buildings and the particle effects, but there is always one or more things not working, like the 3D models of buildings aren't in the right spot or the app doesn't show my location marker moving on the 2D map or the map texture won't load unless I turn on my data on my phone. These are just some examples and they aren't the same for every project. 

Is there a general solution to all this? Like reinstalling the plugin or creating a new project from scratch or changing my project settings? 

I am using a Samsung Galaxy S7, by the way.

Unity version: 2018.3.9f1
Scripting Runtime Version: .NET 4.x Equivalent
Scripting Backend: Mono
Api Compatibility Level: .NET Standard 2.0
Mapbox SDK version: 2.0.0
The platform you're building to: Android
A description of what you're trying to do: follow tutorial instructions, build projects and play them on my android phone
Steps to recreate the bug if appropriate:

**Comment by brnkhy** [comment]
@jordy-isaac do you have any idea?
