### ISSUE TITLE
Access to buildings roofs and walls 

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1339]
mapbox 2.0.0
unity 2017.4.17f1 
Hey guys,
I want to have access to the buildings roofs and walls. The case study is to create green roofs, in other words to add plants to the roof and I also need to have access to the walls and change their material. 
I think that the idea for the roofs is to add a feature layer and spawn inside such as the case of the park example but how can I do this.
@jordy-isaac @brnkhy @atripathi-mb Any idea thanks a lot.

**Comment by roura-12** [comment]
hey @BergWerkGIS  can you help me please?

**Comment by atripathi-mb** [comment]
@roura-12 

The `Texturing` section for layers allows you to set different materials for roof and side. 
![image](https://user-images.githubusercontent.com/32286016/56381120-ce0fb480-61c8-11e9-9fc6-eb2c93ab979b.png)

If you want to go the custom mesh route you can look at the [TexturedSideWallModifier](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/TextureSideWallModifier.cs) or [HeightModifier](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/HeightModifier.cs) to use raw mesh data as per your needs. 

For the custom mesh route, you will want to use the `Custom` primitive to set-up your modifiers.

**Comment by roura-12** [comment]
thanks a lot :)
