### ISSUE TITLE
World Scale AR rotation problem.

### ISSUE THREAD

**Issue by smtabatabaie** [mapbox/mapbox-unity-sdk#1342]
Hi, I'm trying to experiment with WorldScaleAR sample scene. It works perfect except the map and the buildings (which are in real size) are on the wrong orientation and rotation. I wanted to ask if there are any ways to match the map to the real world in terms of its rotation and position.
Thanks

**Comment by jordy-isaac** [comment]
@smtabatabaie You may need to align the scene so that the game objects match the orientation of the real world. Have a look at the [manual alignment example](https://docs.mapbox.com/unity/maps/examples/world-scale-manual-align-ar/)?

**Comment by smtabatabaie** [comment]
Thanks very much @jordy-isaac , Is there any way to do this automatically so there won't be any need to align manually?

**Comment by jordy-isaac** [comment]
The normal world-scale example scene is auto aligned, but as you pointed out it normally needs some help to match the real world. This is something that we're continuing to monitor, improve and iterate on as AR tech moves forward.

**Comment by smtabatabaie** [comment]
Thanks very much @jordy-isaac , but I'm not experiencing this. It depends on the angle you open the scene (ARKit world) and everything may be rotated depending on the rotation you open the app. I tried to fix it with Unity TrueNorth but I get into another problem which is when you rotate the map gameobject things like directions will fall apart and doesn't work afterwards.

**Comment by IAmirFatemi** [comment]
Hello, could you find a solution to this problem?
