### ISSUE TITLE
calculating world distance

### ISSUE THREAD

**Issue by linojon** [mapbox/mapbox-unity-sdk#1344]
hi, i'm using mapbox Conversions class to calculate the distance between two lat longs, but the results do not match up with other calculators (such as google maps "measure" feature, http://www.meridianoutpost.com/resources/etools/calculators/calculator-latitude-longitude-distance.php, http://www.csgnetwork.com/gpsdistcalc.html,

To create this example i created a new project in Unity 2018.3.7, imported Mapbox 2.0.0 package, opened the DataExplorer scene (any scene will do), added a canvas with my input and output fields and attached to following script

```
public class DistanceCalculator : MonoBehaviour
{
    public AbstractMap Map;
    public InputField FromInput;
    public InputField ToInput;
    public Button CalcButton;
    public InputField ResultText;
    public InputField ViaUnityResult;

    void Start()
    {
        CalcButton.onClick.AddListener(Calculate);
    }

    private void Calculate()
    {
        Vector2d fromLoc = Conversions.StringToLatLon(FromInput.text);
        Vector2d toLoc = Conversions.StringToLatLon(ToInput.text);

        Vector2d fromMeters = Conversions.LatLonToMeters(fromLoc);
        Vector2d toMeters = Conversions.LatLonToMeters(toLoc);
        double distance = (toLoc - fromLoc).magnitude;
        ResultText.text = distance.ToString();

        // via map
        Vector3 fromUnity = Map.GeoToWorldPosition(fromLoc, false);
        Vector3 toUnity = Map.GeoToWorldPosition(toLoc, false);
        float distanceUnity = new Vector2( toUnity.x - fromUnity.x, toUnity.z - fromUnity.z).magnitude / Map.WorldRelativeScale;

        ViaUnityResult.text = distanceUnity.ToString();
    }
```

The output of a calculation below
![image](https://user-images.githubusercontent.com/68624/56320723-bf76be00-6132-11e9-8c55-de3c63513ef1.png)

And same latlong via web calculator
![image](https://user-images.githubusercontent.com/68624/56320845-0d8bc180-6133-11e9-81a0-e8d80d52db2d.png)

![image](https://user-images.githubusercontent.com/68624/56320865-1d0b0a80-6133-11e9-89ca-090cda0da70d.png)

Notably, 6485m does not match 4635m.  Any insight would be much appreciated.

**Comment by BergWerkGIS** [comment]
This might be helpful: https://github.com/mapbox/mapbox-unity-sdk/issues/929#issuecomment-408358985

**Comment by linojon** [comment]
Thank you, CheapRuler works. It'd be nice to overload the ruler functions to take Vector2d latlon (and maybe rename it to LocalRuler :) ). Do you take pull requests? 

Meanwhile, i still dont understand why my second variant does not work, using unity world coordinates via an AbstractMap -- convert the 2 points i'm measuring between from latlong to unity world coordinates, get the distance, then adjust for WorldRelativeScale. I expected this to work, for short distances (a few kilometers).

**Comment by brnkhy** [comment]
I'll drop this link for other possible options like GeoCoordinate class and custom calcuation method;
https://stackoverflow.com/questions/6366408/calculating-distance-between-two-latitude-and-longitude-geocoordinates
