### ISSUE TITLE
WorldScaleAR - Manual alignment crashes when the app is touched

### ISSUE THREAD

**Issue by BVauer** [mapbox/mapbox-unity-sdk#1346]
* Unity version: 2018.2.21f1
* iOS 12.2
* Mapbox 2.0.0

Hey !
I am trying to build the WorldScaleAR - manual alignement example but I run into some troubles.
I can set an object on a map with Spawn on Map. 
And I think the think could work.
But each time I touch the screen of my iPhone the app crashes (iPhone 7 plus).
Any help would be much appreciated ! thanks !
Valentin

**Comment by chinmaygawande123** [comment]
Hey,
Having trouble with the same issue for 2 days i figured it out . You just need to check the light estimation checkbox in AR Root Gameobject > AR Controller Script . And its Done !
Thank You

**Comment by BVauer** [comment]
Thanks so much !!
I have just tried that and it works perfectly!

**Comment by chinmaygawande123** [comment]
You're Welcome !
