### ISSUE TITLE
WorldScaleAR example doesnt work

### ISSUE THREAD

**Issue by dpggit** [mapbox/mapbox-unity-sdk#1347]
I tried in editor and with an adroid build the WorldScaleAR example in the mapbox package and in editor just shows me a location which is not mine, not even in my country, and in the build just appears a black screen. I added the layers it demands in the warning which the scene shows.

I used Unity 2018.3.6, minimum api level 24, mapbox v2.0.0, scripting runtime version 4.0

My mobile doesnt have gyroscope , wanted to use gps to locate me

**Comment by InvincibleHacker** [comment]
Did you enable ARCore in player settings for android?

**Comment by dpggit** [comment]
I forgot to activate it, now it works, though it has some problems, with maps the precision is very poor, appears like 10 or 20m away, and the AR i wanted to see my environment with the camera but just shows virtual buildings in red and a huge blue dot

**Comment by jordy-isaac** [comment]
@dpggit What is it that you're developing in AR. You can turn off the building vector layer if you don't need the buildings in your scene.

**Comment by dpggit** [comment]
i wanted just see with the camera and see 3d models i place in geolocations, for instance arrow keys that show a direction to an address

**Comment by jordy-isaac** [comment]
You can add them with the [SpawnOnMap](https://docs.mapbox.com/unity/maps/overview/add-markers/) script or bring game objects via [map features vector layer](https://docs.mapbox.com/unity/maps/overview/map-features/) with a game object assigned.

**Comment by AAKLebanon** [comment]
Hi, I am still unable to reproduce the official WorldScaleAR example on my device. my device support ARCore, however when I walk forward I can't see the red route above of me. My device is Huawei Y9 2019, I am using mapbox-unity-sdk_v2.1.1 and Unity 2019.2.14f1. any idea ?
