### ISSUE TITLE
Mapbox menu not appearing in Unity 2019.1.0f2 after importing package

### ISSUE THREAD

**Issue by serhii-vlasiuk** [mapbox/mapbox-unity-sdk#1349]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.1.0f2
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to: Mac OS X
* A description of what you're trying to do: Import Mapbox sdk
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
@serhii-vlasiuk Does this continue after importing the SDK to a new project?

**Comment by serhii-vlasiuk** [comment]
Hi @jordy-isaac ,
Yes, after importing to new projects

**Comment by xiaoliyong** [comment]
have you solved this problem？

**Comment by brnkhy** [comment]
@serhii-vlasiuk I think the most common cause for this is compilation failure. Can you see any errors in the error log? If Unity cannot compile a single script due to an error or something, cancels all compilation process resulting mapbox code (including editor stuff of course) not being processed.

**Comment by jernkuan** [comment]
I fixed this by adding the ar foundation package from the package manager.

similar problem found here https://github.com/Unity-Technologies/arfoundation-samples/issues/79

**Comment by brnkhy** [comment]
@jernkuan great catch, Unity 2019 moved some AR classes to ArFoundation package so you should be getting missing class exception when you import the package. Installing ArFoundation package OR deleting mapbox ar folders (if you're not planning to use them) should fix that issue.

**Comment by Fernanflow** [comment]
dont work. Any ideas ?

**Comment by brnkhy** [comment]
@Fernanflow you probably have errors right? Can you share the errors?

**Comment by thomasdik1989** [comment]
Works in the latest version if you add the following package ARcore XR plugin.

**Comment by Streamweaver** [comment]
Confirming that installing ARFoundation from Package Manager fixed this for me.  I installed AR foundation after importing Mapbox SDK and getting the error, and it automatically launched the Mapbox setup dialog window.  I did receive a number of warnings immediately though, mostly about fields never being assigned to.

**Comment by yang-jian0227** [comment]
for me it still do not work.i have installed the AR Foundation package and also the package ARcore XR plugin.i use the unity 2019.4.0f1 version and mapbox-unity-sdk_v2.1.1.

**Comment by yang-jian0227** [comment]
Assets\Mapbox\Unity\Location\DeviceLocationProvider.cs(321,12): error CS0103: The name 'heading' does not exist in the current context
Assets\Mapbox\Unity\Location\DeviceLocationProvider.cs(321,27): error CS0103: The name 'heading' does not exist in the current context
Assets\Mapbox\Unity\Location\DeviceLocationProvider.cs(322,12): error CS0103: The name 'heading' does not exist in the current context
Assets\Mapbox\Unity\Location\DeviceLocationProvider.cs(322,30): error CS0103: The name 'heading' does not exist in the current context
Assets\Mapbox\Unity\Location\DeviceLocationProvider.cs(323,37): error CS0103: The name 'heading' does not exist in the current context

**Comment by yang-jian0227** [comment]
it also says:
component at index 2 could not be loaded when loading gameobject'ARCamera',remove it.

**Comment by yang-jian0227** [comment]
solve it !

**Comment by Streamweaver** [comment]
> solve it !

That's great.  Generally considered good form to post a good description of how you solved it so it helps others.

**Comment by yang-jian0227** [comment]
there is an error in the code.of the mapbox-unity-sdk_v2.1.1.
open deviceLocationProvider script,you can see one line of **double heading...**it is in the annotate mode.
all you need to do is to choose the line and press Enter.

**Comment by Tommy0814** [comment]
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Mapbox.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
Assets/Mapbox/Core/Plugins/ThirdParty/Mapbox.Json/Net35/Mapbox.Json.dll
Assets/MapBox/Core/Plugins/ThirdParty/Mapbox.Json/Net35/Mapbox.Json.dll
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.ValidateAndGetNameToPrecompiledAssembly (UnityEditor.Scripting.ScriptCompilation.PrecompiledAssembly[] precompiledAssemblies) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.ToScriptAssemblies (System.Collections.Generic.IDictionary`2[TKey,TValue] targetAssemblies, UnityEditor.Scripting.ScriptCompilation.ScriptAssemblySettings settings, UnityEditor.Scripting.ScriptCompilation.EditorBuildRules+CompilationAssemblies assemblies, System.Collections.Generic.HashSet`1[T] runUpdaterAssemblies) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.GenerateChangedScriptAssemblies (UnityEditor.Scripting.ScriptCompilation.EditorBuildRules+GenerateChangedScriptAssembliesArgs args) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScripts (UnityEditor.Scripting.ScriptCompilation.ScriptAssemblySettings scriptAssemblySettings, System.String tempBuildDirectory, UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions options, UnityEditor.Scripting.ScriptCompilation.EditorBuildRules+TargetAssembly[]& notCompiledTargetAssemblies, System.String[]& notCompiledScripts) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScripts (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions options, UnityEditor.BuildTargetGroup platformGroup, UnityEditor.BuildTarget platform) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions options, UnityEditor.BuildTargetGroup platformGroup, UnityEditor.BuildTarget platform) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions options, UnityEditor.BuildTargetGroup platformGroup, UnityEditor.BuildTarget platform) (at <480b5a3bd3214ce5831f6dd8c68fdc55>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)

None of the solutions mentioned above work for me. Still no Map Box Access Token Dialog window launched for me.

**Comment by brnkhy** [comment]
@Tommy0814 You have two mapbox folders in your project, one named `Mapbox`, other named `MapBox`. You have to delete one of them.

**Comment by Tommy0814** [comment]
> @Tommy0814 You have two mapbox folders in your project, one named `Mapbox`, other named `MapBox`. You have to delete one of them.

Actually, I just opened the project in 2019.4.0f1, then the Access Token Dialog window appears right after I opened the project. I was originally on 2019.4.4.f1. But thanks anyway.

**Comment by passenger-earth** [comment]
I had the same problem , the console said there was an error in one of the Google AR scripts. After reading the comments here , i installed ARFoundation and ARCore Package from the package manager and that solved the problem. Now i can access the mapbox setup window.!

**Comment by abhishekjairam01** [comment]
> I had the same problem , the console said there was an error in one of the Google AR scripts. After reading the comments here , i installed ARFoundation and ARCore Package from the package manager and that solved the problem. Now i can access the mapbox setup window.!

Bro how did u install ARFoundation and ARCore package? Pls help 🙏🙏🙏🙏

**Comment by Tommy0814** [comment]
Yes, but I forgot it. It was a long time ago. Now I’m a manager so I don’t
do development myself anymore.

**Comment by NavanshGoel** [comment]
@abhishekjairam01 
For windows Unity Goto Window>Package Manager>AR Foundation> Install
and the Mapbox setup window pops up right after the installation is complete

**Comment by EarthAdam** [comment]
I was having all of these issues too, and the solution at the end of this thread worked for me: https://github.com/mapbox/mapbox-unity-sdk/issues/1753
Basically remove the GoogleARCore, MapboxAR, and UnityARInterface folders (and don't use any AR features), or switch back to Unity 2019 LTS

**Comment by surdu** [comment]
Still not showing after installing the ARFoundation and ARCore XR Plugin. Using Unity v2020.3.15f2

```
Assets/UnityARInterface/ARRemote/Scripts/ARRemoteEditorInterface.cs(40,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/ARCoreBackgroundRenderer.cs(43,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

Assets/UnityARInterface/Scripts/ARCoreInterface.cs(51,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

Assets/UnityARInterface/Scripts/ARKitInterface.cs(26,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by polarecreater** [comment]
Delete GoogleARCore, UnityARKitPlugin, UnityARInterface, MapboxAR folders. If you use Mac, then it could be working. But if you use Window, then there are still errors "error CS0103: The name 'heading' does not exist in the current context". So I remove the script.

**Comment by Florian-crg** [comment]
Same problem here !

**Comment by kevin-smets** [comment]
> 
> 
> Delete GoogleARCore, UnityARKitPlugin, UnityARInterface, MapboxAR folders. If you use Mac, then it could be working. But if you use Window, then there are still errors "error CS0103: The name 'heading' does not exist in the current context". So I remove the script.

This worked for me, even on Windows. After the deletion it triggered the setup window. What a great first experience :D

**Comment by jeremytinkers** [comment]
> ArFoundation package

This worked for me as well. Also, i'd like to add that if you're using Unity 2019 and also don't intend to use AR, then its best to avoid importing AR Foundation . Importing that is tricky cuz you need to ensure you install AR Foundation 1.1 and not 1.0

**Comment by jeremytinkers** [comment]
> Delete GoogleARCore, UnityARKitPlugin, UnityARInterface, MapboxAR folders. If you use Mac, then it could be working. But if you use Window, then there are still errors "error CS0103: The name 'heading' does not exist in the current context". So I remove the script.


This worked for me as well. Also, i'd like to add that if you're using Unity 2019 and also don't intend to use AR, then its best to avoid importing AR Foundation . Importing that is tricky cuz you need to ensure you install AR Foundation 1.1 and not 1.0

**Comment by xwindor** [comment]
> > Delete GoogleARCore, UnityARKitPlugin, UnityARInterface, MapboxAR folders. If you use Mac, then it could be working. But if you use Window, then there are still errors "error CS0103: The name 'heading' does not exist in the current context". So I remove the script.
> 
> This worked for me as well. Also, i'd like to add that if you're using Unity 2019 and also don't intend to use AR, then its best to avoid importing AR Foundation . Importing that is tricky cuz you need to ensure you install AR Foundation 1.1 and not 1.0

I did this and was able to get rid of my errors in the console but the Setup window was not triggered. Any suggestions?
