### ISSUE TITLE
ARFoundation ar-foundation-port adding POI causes NullReferenceException

### ISSUE THREAD

**Issue by vin67** [mapbox/mapbox-unity-sdk#1352]
Unity 2019.1.0f2
Mac 10.14.4
SDK 2.0.0
ar-foundation-port
.net 4.x compatibility level
.net 4.x equivalent scripting runtime version
scripting backend IL2CPP (greyed out)

I was just adding POI using any of the settings and when press play the map disappears, no POI is placed and I get the error message. Do POI's work yet with the ar foundation branch?

> NullReferenceException: Object reference not set to an instance of an object
> Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer.AddOrCreateMeshModifier[T] () (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:92)
> Mapbox.Unity.MeshGeneration.Interfaces.LocationPrefabsLayerVisualizer.SetProperties (Mapbox.Unity.Map.VectorSubLayerProperties properties) (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/LocationPrefabsLayerVisualizer.cs:96)
> Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.AddPOIVectorLayerVisualizer (Mapbox.Unity.Map.PrefabItemOptions poiSubLayer) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:123)
> Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.CreatePOILayerVisualizers () (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:454)
> Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.OnInitialized () (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:188)
> Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Initialize (Mapbox.Platform.IFileSource fileSource) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:73)
> Mapbox.Unity.Map.AbstractMapVisualizer.Initialize (Mapbox.Unity.Map.Interfaces.IMapReadable map, Mapbox.Platform.IFileSource fileSource) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:96)
> Mapbox.Unity.Map.AbstractMap.InitializeMap (Mapbox.Unity.Map.MapOptions options) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:638)
> Mapbox.Unity.Map.AbstractMap.SetUpMap () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:520)
> Mapbox.Unity.Map.AbstractMap.Start () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:455)

**Comment by atripathi-mb** [comment]
This branch is a work in progress and not up-to date with the latest work. Issue is already fixed in the develop branch.
