### ISSUE TITLE
Issue 301 is reappearing

### ISSUE THREAD

**Issue by sutee9** [mapbox/mapbox-unity-sdk#1353]
This issue described in Issue 301 (Build fails because MapboxMobileEvents.h is not found) is appearing under the following circumstances.

1) Use one of the standard .gitignore files that almost everybody is using with unity. These ignore files always ignore folders named "build" / "builds".
2) collaborate with someone using git

The person who installed mapbox has the folder mapbox/unity/editor/build but all others in the same project don't have it, which makes that the post-process build is not executed.

A simple workaround is to rename the folder mapbox/unity/editor/build to mapbox/unity/editor/buildsettings 

Like this the problem doesn't appear and the build goes through for everyone. Also in unity cloud build.

We had this issue:
- Locally, the project built fine for me
- In cloudbuild, it failed every time.

**Comment by brnkhy** [comment]
thanks a lot for the ticket and solution @sutee9 🙏 
cc @atripathi-mb @jordy-isaac

**Comment by mhellnerdev** [comment]
This is the solution here.  Fixed my issue.  I'm working on PC and pushing through git to my mac to build.  thank you!
