### ISSUE TITLE
Maps not loading correctly on Android devices 

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1356]
Everything works fine on iOS devices but android (tested on Huawei p9 lite) results in the player being placed in the ocean. The map data also loads very slowly. Even on Wifi the map takes a good 15 seconds to load the blue ocean tiles. 

* Unity version: 2018.18f1
  * Scripting Runtime Version: .NET 4.x
  * Scripting Backend: IL2CCP
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: 2.0
* The platform you're building to: Android
* A description of what you're trying to do: Locate and Load Map
* Steps to recreate the bug if appropriate: Open App with WIFI disabled

**Comment by brnkhy** [comment]
Hey @Schaggo ,
That sounds like a GPS/Geolocation issue. Are you sure location permissions in the Android device are set correct? Do you have a chance to try same application on another android device? We have a lot of android developers so I'm guessing it's unlikely to be an sdk/code issue.

**Comment by Schaggo** [comment]
Permissions are set. With WiFi everting works fine. 

The devices location settings are on „GPS only“ 
Some android devices have no problem, but Huawei and blackberry seem to not work properly - depending on the model.

**Comment by brnkhy** [comment]
@Schaggo ah I see, so that's a device related issue. We'll try to find them and test it, thanks a lot for the report 🙏

**Comment by brnkhy** [comment]
cc @atripathi-mb @jordy-isaac
