### ISSUE TITLE
Interaction of POIs and custom scenes 

### ISSUE THREAD

**Issue by Gauravajariwal11** [mapbox/mapbox-unity-sdk#1357]
Mapbox SDK version: 2.0.0
The platform you're building to: Linux

So, 

I am working on this project which uses mapbox. I have integrated my desired location of map pretty fine, got it customized, got preferred POIs as well. So far so good. 

The problem I am facing is that I want the game to output a puzzle game (which my team member created and works fine) just when my PlayerTarget reaches in the range of any POIs, and clicks on it. Just like how a player would tap on a pokestop, or a gym in pokemon go. 

Any help would be appreciated. My project is kinda due in 2 days, and this is the only last thing left.

Thanks

**Comment by brnkhy** [comment]
Hey @Gauravajariwal11,
There should be a prefab field in POI settings, if you use that, you should be able to do all interactions through your custom prefab. Taht prefab can contains any scripts to detect on click for example or even have a UI canvas (and button) inside it.

**Comment by Gauravajariwal11** [comment]
@brnkhy You will be the life saver if you share your knowledge with me for just 30 mins. 

I know that there is a prefab field in POI settings, and I can put up any scripts and UI Canvas inside of it. But those scripts and canvases uses a lot of different images too. Can I put those images, button icon and maybe another prefab as well in that POI's specified prefab?

Again, THANKS a lot.

**Comment by brnkhy** [comment]
@Gauravajariwal11 I'm not sure if I understand what you said. Having a prefab there means you get a fresh start, using a script on that prefab you can do almost anything including spawning sub-gameobjects or a canvas with buttons etc.

**Comment by Gauravajariwal11** [comment]
@brnkhy Yes thanks I am checking that right now. 

what I wanted to do was to pull up entirely new scene when the user clicks on any of the POIs. Do you think you know anything about scene transitions through the POIs?

**Comment by Gauravajariwal11** [comment]
@brnkhy I have a last question though? So I made this scene which is essentially my game. Then I put a prefab on a POI with a script. This script basically changes my scene with the help of loadScene() to the scene of the game I want to use. I am still unable to enter the scene of the game. I put that prefab in POI, also put one gamemodifier prefab in buildings component. Where am I wrong?

Thanks

**Comment by brnkhy** [comment]
@Gauravajariwal11 ah I think I understand better now but I'm afraid that's a Unity thing and I have no idea about it. I can't remember doing scene transitions at all, like ever :) So I'm sorry but I won't be able to help much further than clicking the button on poi.

**Comment by Gauravajariwal11** [comment]
@brnkhy  Alright. Thanks a lot. :)
