### ISSUE TITLE
Mapbox Spawn on Map Script spawning marker far away from map

### ISSUE THREAD

**Issue by acoale** [mapbox/mapbox-unity-sdk#1359]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: **2018.3.11.f1**
  * Api Compatibility Level: **24**
* Mapbox SDK version: **2.0.0**
* The platform you're building to: **Android**
* A description of what you're trying to do: **Using the Geocoder to get lat/long from street address**
* Steps to recreate the bug if appropriate: **Firebase Database pull of geoaddress (street address) populate to list, 
foreach the list to process each address into a location, 
plug the string into HandleUserInput(searchstring) resource.
Query the string and pass it to HandleGeocoderReponse.
create cords with feature.Center.x.ToString..... pass cords to stringtolatlon()
instantiate a 3d Prefab and transform the local position using locations.** 
 * Links to your logs are also helpful: 
LOG OF DEBUG of LOCATION AND CORDINATES:
**Location 1 is: -104.76130,39.51850 of Feature: 39.5185, -104.7613
UnityEngine.Debug:Log(Object)**

Spawning prefab at: x: 321131.5; y: -4.775173; z: 40431.07

**Comment by brnkhy** [comment]
@acoale I had a little hard time understanding it but this line catched my eye;
`instantiate a 3d Prefab and transform the local position using locations.`
your final position looks like absolute position in mercator meters as well. I think your latlng to unity world conversion is wrong here, I mean you're converting it but without taking current map position into account. If you use `AbstractMap.GeoToWorldPosition` method, you will probably get better results. Can you try that and let me know again please?

**Comment by acoale** [comment]
I am sorry yes I am already doing that. I should have been more descriptive. The _locations is the variable that is declared in the debug: **-104.76130,39.51850**

instance.transform.localPosition = _map.GeoToWorldPosition(_locations, true);

The script is attached to the map, which is the abstract map. Also I did drag the map from the Heirarchy to the Serialized Field. So it should have everything it needs to populate the 3D marker in the correct location, but for some reason is populating it very far away.

**Comment by brnkhy** [comment]
@acoale 
`Location 1 is: -104.76130,39.51850 of Feature: 39.5185, -104.7613`
this also looks a little suspicious as lat/lng is swapped. Strangely, both latlng and lnglat is standard is some different cases. Can you check if it looks better if those swapped?

**Comment by acoale** [comment]
It worked, Kind of. But if the map is NOT at that location its still showing the prefab there. I assume that can be fixed by placing the location in the update function though. However it showed when the map wasn't set to that location originally, I am not sure why it did that. I also find it odd that the cords were produced from Mapbox itself in this method. 

_resource.Query = searchString;
MapboxAccess.Instance.Geocoder.Geocode(_resource, HandleGeocoderResponse);

Why does it flip the cords?

**Comment by acoale** [comment]
Yeah for whatever reason the marker position never changes even when the map location changes.

**Comment by brnkhy** [comment]
`Why does it flip the cords?`
It's actually not flipped but is confusing sometimes. Latitude corresponds to Y axis in mercator so when you say LatLng, you're actually saying yx. But then we're storing them as xy in data structures because that's the common way to do it in 3d space.

`Yeah for whatever reason the marker position never changes even when the map location changes.`
It's probably because you're spawning them once and leaving them there. You should have an anchor objects under tiles and then snap your UI element (or whatever you're using) to that anchor point every frame. I think `DataExplorer` demo scene does that.

Very happy to hear you solved it! I'm closing this for now then.
