### ISSUE TITLE
Forward Geocoding Could be done better

### ISSUE THREAD

**Issue by acoale** [mapbox/mapbox-unity-sdk#1361]
Perhaps I am missing something here. But the forwardgeocoding seems to pull an array of possibilities from a given address. This, while I see value in it at certain points is mostly useless to the vast majority of users, especially since their doesn't seem to be a way to narrow the results. I was looking at the API and do not see where we can set perams for Textual relevance for the Unity SDK. How is that applied? The docs on this could be much better to be honest.

**Comment by brnkhy** [comment]
Mapbox geocoding api returns a set of points for various reasons and we're exposing them all as is. I'm not sure how it's a bad thing though? I believe the main idea there is to ensure you have the right place when searching for short strings, like "amst" for example (will return multiple amsterdam search possibilities).

I haven't used geocoding much myself but reading; https://docs.mapbox.com/help/how-mapbox-works/geocoding/
I think you don't set a parameter for relevance but system automatically returns a relevance&score based on your search, in the results. You should be able to get these values like `ForwardGeocodeResponse.Features[i].Relevance`.

cc @jordy-isaac; am I right about this? ☝️

**Comment by acoale** [comment]
I wasn't implying it was useless. I stated that i CAN see the value, but for the most part I wouldn't understand it being the function mainly used. most people search by exact address. having a function that only pulls the high relevance would seem to save some resources to me. especially when you are using this as a method to populate markers and other such items on the map. I will look into how it pulls and see how possible it is for me to do, Is the below code what you think would pull the exact address?

Feature feature = _features[i];
if (feature.Relevance >= 1) 

More about geocoding in Unity docs would be very helpful. As I read the API reference I didn't think about filtering the results so much as putting in a parameter to pull the desired results. Since this does it differently covering it would be great. Thanks for the feedback!

**Comment by brnkhy** [comment]
I think that list is already sorted by relevance score so first item in the list should be the most relevant one.
I always imagined it like generic search boxes in map applications, you know how they suggest multiple stuff after each keystroke? You can see something similar here for example; www.barankahyaoglu.com/map
when you think like that, I think searching for the exact full address is not the common case I guess.

`More about geocoding in Unity docs would be very helpful.`
I think this is a great point. I'll definitely try to look into it. Thank you for the feedback 🙏
