### ISSUE TITLE
Error when moving Mapbox into subdirectory of Assets

### ISSUE THREAD

**Issue by andybak** [mapbox/mapbox-unity-sdk#1362]
The Mapbox SDK dumps a bunch of directories into the root of Assets. First thing I need to do when adding it to a project is:

a) delete all the stuff I'll never need like the various AR related stuff (please make these a separate package!)
b) Ideally move the remaining folders into my "3rd Party" folder so I can .gitignore it and keep it clearly separate from my files

Unfortunately there's some hard-coded paths which break when I do this.

**Comment by brnkhy** [comment]
`please make these a separate package`
It used to be like that, then we merged it all together at some point. I agree it is a little annoying (I never use ar either) but you can just not import them and all it takes is like 4 clicks?
I want to move everything under one single mapbox folder at some point though.

`there's some hard-coded paths which break when I do this.`
I generally do this as well but couldn't remember any breaks on top of my head. I'll try it myself but would be nice if you can post what you got as well (if you can remember).
