### ISSUE TITLE
Directions route not matching the actual streets 

### ISSUE THREAD

**Issue by Dahfab** [mapbox/mapbox-unity-sdk#1366]
- Unity version: Unity 2018.3.11f1
    - Scripting Runtime Version: .NET 4.x Equivalent
    - Scripting Backend: Mono
    - Api Compatibility Level: .NET Standard 2.0
- Mapbox SDK version: v2.0.0
- The platform you're building to: iOS

- A description of what you're trying to do:
I am trying to implement walking directions onto my tabletop AR map.

- Steps to recreate the bug if appropriate:
1. Make a new Unity Project
2. Import the Mapbox Package via Assets > Import Package > Custom Package.
3. Create a Scene with an AbstractMap.
4. Add the Directions Prefab.
5. Add Waypoints and change the DirectionsFactory.cs to “Walking”:

**Expected result:** Creates a route mesh following the streets and walking path’s.
 **Actual result:** Creates a route mesh going randomly trough buildings and not following the actual streets and path’s.

How can I change the DirectionsFactory.cs Script or something else so that the generated routes will match the actual streets and walking path's?

![Bildschirmfoto 2019-05-15 um 19 23 14](https://user-images.githubusercontent.com/29675300/57796997-bab12400-7749-11e9-8aa3-6f461cb4a5ec.png)

**Comment by brnkhy** [comment]
@Dahfab I tried to recreate this but it worked as expected for me. It looks like an issue with positioning though. I don't think directions script has to be at origin really but I think, somehow it's querying for wrong coordinates. Can you check it? Also does it work when you set it to driving for example? or does it work correct in `TrafficAndDirections` demo scene?

**Comment by Dahfab** [comment]
Ah I think I found something. It looks like it was a problem that I used a much bigger Scale in ARController. If I use the Scale of 1 the route is correct and if I increase the Scale the route is no longer correct. 

Problem now is that my map is way to big for AR on the phone but I can't scale it down because this will break the route once again...

**Comment by Dahfab** [comment]
So you can recreate this issue if you open the Directions Demo Scene and scale the map to other values than 1. 

Is it possible to scale the map and still remain correct routes?

**Comment by Dahfab** [comment]
Any recommendations so far?

**Comment by brnkhy** [comment]
Hey @Dahfab, sorry for late reply.
If I remember correct, directions factory is creating a route object in the root of the scene hierarchy so it won't get effected by map scale/rotation changes. I think the easier solution would be either creating that object under map or even better, update rotation/scale of that object using map rotation/scale values every update. I think that should snap them together well.

**Comment by Dahfab** [comment]
No worries @brnkhy, thanks for your recommendations!

Unfortunately both solutions don't seem to work. It seems like the route object is always effected in a bad way by the scale of the map and does not maintain its correct route even if it gets the updated scale from the map object.
