### ISSUE TITLE
Zoom level change to float type

### ISSUE THREAD

**Issue by xwu93** [mapbox/mapbox-unity-sdk#137]
Do we have the future plan to change the zoom parameter from int to float, give more flexible to show the map? I know the SDK for other platforms have the zoom level as float type.

I looked at the code, however, in someplace, it uses shift operator for two int type, as far as I know, you can't do shifting floating point types in C#, right?

Do you have other way to change the zoom effect more precisely?

Thanks.

**Comment by brnkhy** [comment]
@xwu93 I asked around and tried to understand the effects of this but I'm still not sure if I get it.
So data only changes in integer values like 13-14-15, and as far as I know, tile coverage only changes with those as well. So what's the difference between 15.4 and 15? 
In our javascript maps, 15.4 will look a little more zoomed in but that's all about camera work and nothing about the actual data and/or output. 
This shouldn't be too hard I guess but can you explain a little more why do you need this?

**Comment by david-rhodes** [comment]
@xwu93 Thanks for the suggestion! We'll keep this in mind as we address this issue: https://github.com/mapbox/mapbox-unity-sdk/issues/121.

**Comment by david-rhodes** [comment]
Map components now have a float representation as well.
