### ISSUE TITLE
Get OSM file from a Vector Tile

### ISSUE THREAD

**Issue by aromerosim** [mapbox/mapbox-unity-sdk#1370]
Hi everybody!

I'm trying to get the road information in OSM format from the Vector Tiles using the Mapbox SDK for Unity to use it in the EasyRoad 3D plugin. As documentation says [here](https://docs.mapbox.com/vector-tiles/specification/#format) that info is encoded using the PBF standard, as the info in is the OSM file, but in a different way. So, is there any way to convert directly an .mvt file to .osm file? 
I know that I can use the [Vector Tile Parser ](https://github.com/mapbox/vector-tile-cs) to decode the info and then encode it using the OSM standard, but it's really a hard job that I want to avoid!

Thank you guys.

**Comment by brnkhy** [comment]
@aromerosim I really don't think there would be an easy way for this. Even our data and data structure is different from raw osm. There's a `convert to geojson` method in vectorTile class for example, but I'm not sure how much that geojson corresponds to osm itself :(
But there has to be another way to pass data into easy road plugin I hope?

**Comment by aromerosim** [comment]
First of all, thank you for answering me @brnkhy, and sorry for my late response. The only other way to import data on EasyRoads 3D is in KML format, and there is not an easy way to get it neither. I think my last option is to get the data in plain text (in GeoJSON) using the method that you're referring to and then create a new file in OSM or KML format.
If you find another way, I would be glad to hear it.
Thanks!

**Comment by brnkhy** [comment]
@aromerosim geojson should be very similar to OSM (if not the same), I would suggest checking that. I also think any road asset like that would probably have a custom data structure for it as well. I mean does Easy roads only work for mapping applications? It probably does have a method taking list of points and some other information etc I guess?

**Comment by aromerosim** [comment]
@brnkhy yes, i will try to extract the necessary information from the GeoJSON to an OSM file (which is in xml, so I think they are not the same). Also, as you suggest, it can take a Vector3 and some more information to generate a road, therefore it would be possible to generate a road directly from the GeoJSON information but i think that would be more complex, imo. Thank you one more time!

**Comment by brnkhy** [comment]
@aromerosim oh I always though of GeoJSON when I heard OSM until now. But yes chasing a custom data structure approach (passing points etc) would be much better for you. I'm closing this for now but please let us know if you managed to get it to work and how it looks!
