### ISSUE TITLE
[Unity 2018.4.0f1] WWW class is obsolete

### ISSUE THREAD

**Issue by MlleDR** [mapbox/mapbox-unity-sdk#1375]
Unity 2018.4.0f1
Mapbox V2.0.0

Hi,

WWW class is obsolete with Unity 2018. Are you planning to update the scripts provided with Mapbox Unisty package?

Thanks

`Assets\Mapbox Package\Mapbox\Unity\Editor\StyleSearchWindow.cs(153,18): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'`

**Comment by unnanego** [comment]
I get 300+ warnings like that

**Comment by brnkhy** [comment]
I'll check this, we'll try to fix it as soon as possible. Sorry for all the trouble :(
