### ISSUE TITLE
i am creating a navigation ar app in unity i want to show arrows  from one choose location to another  can you please tell me how to do it

### ISSUE THREAD

**Issue by shubhamguptak** [mapbox/mapbox-unity-sdk#1376]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
I would suggest checking Traffic demo scene and the direction factory script inside it. Directions factory find the route between two points, as you would need I guess, and then draws a line in between them. Would be a good starting point I guess.
