### ISSUE TITLE
Accurate Markers in AR

### ISSUE THREAD

**Issue by JamieMcilwrath** [mapbox/mapbox-unity-sdk#1379]
Hi, I am using the latest version on Unity, I'm currently working on the AR Scene, I have taken the custom marker prefab and was able to spawn this on the current lat/long coords, the only issue is the map accuracy is off and the markers are facing the wrong way in the AR camera, on the map they are fine. How would I adjust the map to spawn to the same direction I am facing.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
cc @atripathi-mb @jordy-isaac

**Comment by atripathi-mb** [comment]
@JamieMcilwrath 
> the only issue is the map accuracy is off and the markers are facing the wrong way in the AR camera

What do you mean by `Map Accuracy is off`? GPS & Compass accuracy vary vastly depending on the location ( usually pretty bad in urban canyons) , you might want to do manual aligmnment or use 3rd party solutions for localizing in AR. 

See Manual Alignment / Automatic aligment examples in the SDK for reference
