### ISSUE TITLE
Bad access running vanilla slippy example on iOS

### ISSUE THREAD

**Issue by gershonatron** [mapbox/mapbox-unity-sdk#138]
Slipping around in the slippy example for about 15 seconds brings about a EXC_BAD_ACCESS (code=1, address=0x2de) in iOS 10.3.2. It locks up in SetStatusCode, within a WWW callback, though not immediately clear where the issue actually originates. Seems to happen in both dev and master.

**Comment by david-rhodes** [comment]
@gershonatron Sorry for the late reply. I have not seen this before, but I could really use some more information from you to help debug. 

- Hardware?
- Xcode stack trace?
- Is this from our `sdkproject` or your own with the example built?

Thanks!

**Comment by david-rhodes** [comment]
Another thing to check is that your `Dispose Buffer` is greater than `Visible Buffer." Closing for now since I haven't heard back, but please open if this issue is still occurring.
