### ISSUE TITLE
Set Waypoints to specific geo-location (lat/lon) 

### ISSUE THREAD

**Issue by Ryhter** [mapbox/mapbox-unity-sdk#1380]
Is there a way, to set a waypoint to a specific geo-location (lat/long) using Unity and the DirectionsFactory.cs? 

Any help on this?

**Comment by Ryhter** [comment]
i think i can solve what i need by Using this : 

public static void MoveToGeocoordinate(this Transform t, double lat, double lng, Vector2d refPoint, float scale = 1F) 
but i can't make it work as i wanted. 
Documentation isn't that clear, any tips on how to use it properly?

**Comment by brnkhy** [comment]
@Ryhter I'm afraid I don't understand what you're trying to achieve. Directions factory is all about finding routes (car/bicycle/walking), are you looking for something like that? If not what's the `waypoint` you mentioned?

**Comment by Ryhter** [comment]
Yeah, I figured out how DirectionsFactory works. I need to draw the direction's line, from the player to a waypoint. But I want to put that waypoint to a specific location (lat/lon) when the scene starts.

For example, in the Astronaut game, I want a direction line from the Astronaut to a waypoint specified by me with a specific geo location. In order to achieve that, I just have to set the waypoint prefab in directions prefab to the location I want. But I have an issue setting the location. 

Reading the documentation, I found this: public static void MoveToGeocoordinate(this Transform t, double lat, double lng, Vector2d refPoint, float scale = 1F). But I am not sure how it actually works cause i can't make it do what i really want. So I just need some help with this function if it's possible.

**Comment by brnkhy** [comment]
@Ryhter 
I'm still not sure but I guess there are two possible problems you might be having;
- not sure how to set lat/lng of the target point
You can check query method in the Directions Factory for this and see how it creates queries. (creating a Vector2d array etc)
- setting it but point is in wrong place
this might happen because of various stuff but if you have an object in game world for example, you should be able to do something like; 
`myObject.transform.GetGeoPosition(_map.CenterMercator, _map.WorldRelativeScale);`

**Comment by Ryhter** [comment]
Yeah, this helps a lot thanks. I'll check that out and I'll come back with some feedback.

**Comment by Ryhter** [comment]
Yeah, that was it. Thanks, i managed to set the 2nd waypoint to the lat/log that I wanted. SImply by doing this: waypoint.MoveToGeocoordinate( lat, lng, _map.CenterMercator, _map.WorldRelativeScale);

The issue might way the ref_point and the scale factor. Thanks for your time!

**Comment by brnkhy** [comment]
@Ryhter happy to hear it's fixed. 👍

**Comment by taeyoung98** [comment]
@Ryhter That's what I want to make. So I've used the code you said, but it didn't work completely. First, I have to change MoveToGeocoordinate method's parameters' types. Second, what script do you use that code in? I used that in DirctionsFactory.cs, I don't know exactly where to use it.

**Comment by Ryhter** [comment]
The way I did it was: I created a new game object, I attached to it a new script with a method like that:
    
void moveWaypointToGeoLocation(Transform waypoint)
    {
        waypoint.MoveToGeocoordinate(lat, lng, _map.CenterMercator, _map.WorldRelativeScale);
    }
lat, and lng is given by the user, waypoint is the transform of the game object 
you want to move to the geo-location. 

Then use this game object in the DirectionFactory.cs via the unity editor as one of the waypoints. In my example this is Waypoint#1

https://gyazo.com/761c451503925f993a5b613f40834101

**Comment by taeyoung98** [comment]
@Ryhter I've got solved it! Thank you a lot :)

**Comment by Heesunni** [comment]
> @Ryhter 
it is not work to me... plz help...
i just copy that code and I add it new script in the waypoint, but the waypoint is not move....:(

**Comment by MinasKatsiokalis** [comment]
> > @Ryhter
> > it is not work to me... plz help...
> > i just copy that code and I add it new script in the waypoint, but the waypoint is not moved....:(

Use this method:[ MoveToGeocoordinate(lat, lng, _map.CenterMercator, _map.WorldRelativeScale) ] 
This method will move the transform to a specific geo-location based on the map you provide as "_map" this should be a map active on the scene. 

Last, this was used in Mapbox 2.0, it's been years since then...maybe check the scripts. maybe something has been changed

**Comment by Heesunni** [comment]
> > > @Ryhter 
thank you for your comment
I use Mapbox 2.x so I think it still work!
This is my first time using Unity, so maybe it is not what you said..


using Mapbox.Unity.Map;
using Mapbox.Unity.Utilities;
using UnityEngine;

public class waypoint : MonoBehaviour
{
    AbstractMap _map;
    // Start is called before the first frame update
    void Start()
    {
        void moveWaypointToGeoLocation(Transform waypoint)
        {
            waypoint.MoveToGeocoordinate(lat, lng, _map.CenterMercator, _map.WorldRelativeScale);
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

this is all script  i added to the waypoint
of course i changed lat, lng 
but waypoint is not moving.....:(

is there any wrong ?? plz help...

**Comment by MinasKatsiokalis** [comment]
using Mapbox.Unity.Utilities;
using Mapbox.Unity.Map;
using Mapbox.Utils;
using UnityEngine;

///Set a waypoint to a geo location
public class SetToLocation : MonoBehaviour
{
    [SerializeField]
    AbstractMap _map;

    [SerializeField]
    float Latitude_var

    [SerializeField]
    float Longitude_var

    public GeoLocationData[] PointsOfIinterest;

    void Start()
    {
        MoveWaypointToGeoLocation(this.transform);
    }

    void Update()
    {   

    }

    //The method that sets the waypoint ot the geo location
    private void MoveWaypointToGeoLocation(Transform waypoint)
    {
        waypoint.MoveToGeocoordinate(Latitude_var, Longitude_var, _map.CenterMercator, _map.WorldRelativeScale);
    }

}



Note sure if the Long/Lat should be float...check this out and set it accordingly

**Comment by Heesunni** [comment]
oh my god thanks!!
i will trying

**Comment by Heesunni** [comment]
@Ryhter

is that Okay if i delete this one? : 
" public GeoLocationData[] PointsOfIinterest; "

it makes error because of there is not GeoLcationData[] class...
and 
![image](https://user-images.githubusercontent.com/61589814/118083344-b16ef680-b3f9-11eb-8c8a-c741f2419580.png)
it is changed like this thank you!!
but the object still not moving..............

**Comment by janira98** [comment]
If your waypoint and the player is the same position try MoveWaypointToGeoLocation(this.transform); adding to the update() function. It worked for me.
