### ISSUE TITLE
XxxDataFetcher's with null tile parameter

### ISSUE THREAD

**Issue by derekdominoes** [mapbox/mapbox-unity-sdk#1382]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by derekdominoes** [comment]
ImageDataFetcher.cs line 30 checks for the tile parameter being null:
`if (imageDataParameters.tile != null)`
However, a few lines after that it uses tile without any check. This is also inconsistently done in the other two DataFetchers. Is it valid to pass in a 'null' tile parameter? I assume it is because TileCacher.cs code that was posted does just this. Yet I don't see how it could have run given these inconsistencies.

**Comment by brnkhy** [comment]
@derekdominoes great catch! I wanted to fix that for so long but somehow it always slipped, didn't get merged etc.
I fixed it here; https://github.com/mapbox/mapbox-unity-sdk/pull/1383
but it needs some testing as same lines of code is also critical for detecting if tile is recycled and recieved data is still belongs to the tile etc.
other than that, data fetchers should be independent of tile class and everyone should be able to use them to pull any data they want in any system (without using UnityTile class for example)
