### ISSUE TITLE
How to access the properties runtime

### ISSUE THREAD

**Issue by Zhanghanfhyc** [mapbox/mapbox-unity-sdk#1388]
I'm new for using mapbox. I have to access the properties setted in dataset in runtime. So I add feature behaviour component in the gameobject and create a modifier for it. But I get the error:**NullReferenceException: Object reference not set to an instance of an object**.  Are there something I miss?

this is my code
`
public class AccessProperty : MonoBehaviour {
    public VectorFeatureUnity fb;
	void Start () {
        fb = gameObject.GetComponent<FeatureBehaviour>().Data;
        Debug.Log(fb.Data.GetValue("title"));
	}

}`

**Comment by brnkhy** [comment]
`fb = gameObject.GetComponent().Data;`

@Zhanghanfhyc I'm not sure which component that line supposed to get but does that part work at all? `Data` might be null, `title` might definitely be null. You should create a break point and check what's null first. Then simply null check for it probably as I don't think features are guaranteed to have titles for example.
