### ISSUE TITLE
Every time the location is updated, the marker follows.

### ISSUE THREAD

**Issue by ayj8655** [mapbox/mapbox-unity-sdk#1389]
Based on WorldScaleAR i Create marker using spwan on map script. I can see that the marker was created But the marker that was created follows me every time I move. 
![image](https://user-images.githubusercontent.com/30970014/59161863-b1399280-8b22-11e9-98da-e210c60e753c.png)
my hierarchy

![image](https://user-images.githubusercontent.com/30970014/59161875-d0382480-8b22-11e9-8951-ede5fb1c3b08.png)
my Inspector

I want to keep the marker that was created once in that position. 

Thank you for reading and can you help me?

**Comment by brnkhy** [comment]
@ayj8655 I'm not really experienced in AR stuff but from the look of your hierarchy, I guess it's keeping the camera fixed and moving the world around? I mean this is most likely an issue with child/parent relationship and if I remember correct markers are created at the root by default. Have you tried changing it to create them under `ArAlignedMap` object maybe? You can check `PrefabModifier` class for it.
