### ISSUE TITLE
Disk tile caching doesn't work on iOS.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#139]
I just tried out the new tile caching system, and it fails on iOS. Works fine on Android (and also in the editor), but when I tried it for iOS it throws an exception and the map fails to load:

```
MESSAGE
DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.

STACK TRACE
SQLite4Unity3d.SQLite3.Open (System.Byte[] filename, IntPtr& db, Int32 flags, IntPtr zvfs)
SQLite4Unity3d.SQLiteConnection..ctor (System.String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
Mapbox.Platform.MbTiles.MbTilesDb.openOrCreateDb (System.String dbName)
Mapbox.Platform.MbTiles.MbTilesDb..ctor (System.String tileset, Nullable`1 maxTileCount)
Mapbox.Platform.Cache.MbTilesCache.initializeMbTiles (System.String mapId)
Mapbox.Platform.Cache.MbTilesCache.Get (System.String mapId, CanonicalTileId tileId)
Mapbox.Platform.Cache.CachingWebFileSource.Request (System.String uri, System.Action`1 callback, Int32 timeout, CanonicalTileId tileId, System.String mapId)
Mapbox.Map.Tile.Initialize (IFileSource fileSource, CanonicalTileId canonicalTileId, System.String mapId, System.Action p)
Mapbox.Unity.MeshGeneration.MapVisualizer.LoadTile (UnwrappedTileId tileId)
Mapbox.Unity.Map.RangeTileProvider.OnInitialized ()
Location.LocationTileProvider.OnInitialized ()
Mapbox.Unity.Map.AbstractMap.Start ()

AFFECTED OS
iOS 10.3.2
iOS 11.0
```

Using the latest develop branch.

**Comment by BergWerkGIS** [comment]
hm, this was working before merging the associated PR.

Could you check the selected platforms for
`sdkproject/Assets/Mapbox/Core/Plugins/sqlite/x86/sqlite.dll`
and
`sdkproject/Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite.dll`

Maybe the `.meta`s got got mixed up somehow.

**Comment by mihakrajnc** [comment]
@BergWerkGIS 
x86 version:
![image](https://user-images.githubusercontent.com/8857844/27772773-3222075c-5f69-11e7-84d6-9548edea115b.png)

x64 version:
![image](https://user-images.githubusercontent.com/8857844/27772777-43b8b218-5f69-11e7-8380-a41316d23839.png)

Am I right to assume that all i have to do is add iOS to included platforms in x86?

**Comment by mihakrajnc** [comment]
Also, same thing for Android libraries, The x86 variant has "Any Platform" selected, and the armeabi-v7a has Android selected, even though they're both in the Android folder.

I'm not 100% sure how Unity's native system works here, but shouldn't both libraries be in either Android / iOS folders, and both have either Android / iOS platforms selected? If nothing else, for organizational purposes?

**Comment by BergWerkGIS** [comment]
Don't have any iOS devices to test, but checking `iOS` for the x86 version should do the trick.

wrt to Android, thanks for pointing that out, we'll have to revisit the `meta`s for those.

**Comment by mihakrajnc** [comment]
Hmm that doesn't seem to be the case. I set it up after the guides for [SQLite4Unity3d](https://github.com/codecoding/SQLite4Unity3d), but the problem is still there.... The weird thing is, it only happens when I build it over CloudBuild.

I found these bug reports about the issue: 
- https://github.com/codecoding/SQLite4Unity3d/issues/63
- https://issuetracker.unity3d.com/issues/il2cpp-dllnotfoundexception-unable-to-load-dll-sqlite3-the-specified-module-could-not-be-found?_ga=2.185688623.722030214.1499071497-722125156.1494930069

It seems like it's fixed in the newest _beta_ version (Release Candidate) as the only difference I can see it that my CloudBuild configurations are using `Unity 2017.1.0b10` (RC not available atm.) and my local installation is `Unity 2017.1.0f1`. I'll try `b10` locally to see if this is indeed the case.

**Comment by mihakrajnc** [comment]
I can confirm, the issue is fixed in `Unity 2017.1.0f1`.

**Comment by mihakrajnc** [comment]
For anyone wanting to use Cloud Build a temporary fix for this is to add a define in MapboxAccess:

```csharp
void ConfigureFileSource()
{
	_fileSource = new CachingWebFileSource(_configuration.AccessToken)
		.AddCache(new MemoryCache(_configuration.MemoryCacheSize))
#if !UNITY_WEBGL && !DISABLE_DISK_TILE_CACHE // <-- change this line (line #183)
		.AddCache(new MbTilesCache(_configuration.MbTilesCacheSize))
#endif
		;
}
```

And then add DISABLE_DISK_TILE_CACHE to your custom defines in Cloud Build.

**Comment by david-rhodes** [comment]
@mihakrajnc So I think we fixed the metas with this PR: https://github.com/mapbox/mapbox-unity-sdk/pull/144. iOS is not checked for `x86` because Apple no longer supports 32-bit applications, right?

Anyway, since appears to be a cloud build/unity issue, I'm closing for now. 

Thank you for the temporary workaround!
