### ISSUE TITLE
Directions API Inaccuracy

### ISSUE THREAD

**Issue by chinmaygawande123** [mapbox/mapbox-unity-sdk#1390]
Hi! 

So here is the thing. I am trying to achieve accurate navigation in my app. I started by getting points of geometry via this in DirectionsFactory.cs Script : -

![Screen Shot 2019-06-09 at 1 57 51 AM](https://user-images.githubusercontent.com/44647335/59152101-41aca000-8a5b-11e9-841e-8ce707ff8c47.png)

and the rendered line between each of them. I got good results when working with small distances like from New York To Manhattan : -

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/44647335/59152425-32c8ec00-8a61-11e9-8e58-f050af6f2e13.gif)

But when I tested it for long distances it went really weird (New York - Seattle) : -

![NewSeattle](https://user-images.githubusercontent.com/44647335/59152504-ff875c80-8a62-11e9-82c7-927889c34804.gif)

I want my directions workflow like the one given in this mapbox blog link : - https://docs.mapbox.com/help/how-mapbox-works/directions/ 

Any help would be appreciated!

Thank You 

* Unity version: 2018.3.13f1
* Mapbox SDK version: 2.0.0 
* The platform building to - iOS

**Comment by brnkhy** [comment]
@chinmaygawande123 hmm that is an interesting case which admittedly I never thought before. I mean when you create road mesh for such a big distance, it will surely breach floating point precision limit for example. I mean you're looking at Seattle in that video but it's probably trying to create mesh til New York.
I'm not sure if there's a quick fix for this. First thing I can think of is caching the whole route, cutting it into tiles somehow and then creating road mesh for only the tiles that exists at that moment. But then you'll have to redo this on zoom in/out. I'm afraid this is a case we (or at least I) never thought before.

**Comment by chinmaygawande123** [comment]
@brnkhy but when I counted the number of points in geometry from geoJSON with a simple integer variable name adder : -

![Screen Shot 2019-06-09 at 1 57 51 AM](https://user-images.githubusercontent.com/44647335/59205991-a2ee8380-8bc1-11e9-9a08-0c62e391c3f6.png)

it gave me this : -

![Screen Shot 2019-06-10 at 8 53 14 PM](https://user-images.githubusercontent.com/44647335/59206302-493a8900-8bc2-11e9-9629-b53587735d1d.png)

and I don't think there are only 26 geometrical turns from new york to Seattle? What is the problem here I do not understand clearly, Can you please suggest me a breakthrough way to do so for longer distances ?

Thanks for the reply.

**Comment by chinmaygawande123** [comment]
No Answers Yet 😞

**Comment by chinmaygawande123** [comment]
@brnkhy @jordy-isaac sorry I am asking it again but can you please recommend a breakthrough way of achieving navigation for longer distances like mentioned in this example:- https://docs.mapbox.com/help/how-mapbox-works/directions/   

Thank You
