### ISSUE TITLE
How to make buildings extrude even from a far out zoom

### ISSUE THREAD

**Issue by Flek26** [mapbox/mapbox-unity-sdk#1391]
I am looking to make buildings show up even when I have a farther zoom. I dont want it to be high def by any means. Just wanna show some sort of buildings.

**Comment by brnkhy** [comment]
@Flek26 I'm afraid that's not too easy. zoom level 14 or 15 only has very big buildings so you might want to try that? Other than that, if you load zoom 16+, you'll be getting all buildings and it will be very slow for big area/city shots.

**Comment by brnkhy** [comment]
I just noticed we have big buildings even at z13
<img width="899" alt="Screen Shot 2019-06-17 at 2 47 05 PM" src="https://user-images.githubusercontent.com/1465390/59602186-d1fb7c80-910e-11e9-9b45-74feb43c2a76.png">
