### ISSUE TITLE
Precision Panning in Unity

### ISSUE THREAD

**Issue by jonathan84clark** [mapbox/mapbox-unity-sdk#1392]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.3.14f1
  * Scripting Runtime Version: .Net 4.x Equivelant
  * Scripting Backend: Mono
  * Api Compatibility Level: .Net 4.x
* Mapbox SDK version: 2.0.0
* The platform you're building to: Windows
Hello,
I want to implement precision panning in Unity. For example please see the following:
https://docs.mapbox.com/mapbox-gl-js/example/center-on-symbol/
Note that when you click and pan around the cursor holds in the exact geoposition you click while the map is moved. I have been unable to replicate this behavior in Unity. When I use my code to pan around the map the cursor "slips" for lack of a better term. So far the best I have come up with is the following:
`                float xSlide = 0.0f;
                float ySlide = 0.0f;

                // Handles movement. The amount we move is inversely proportional to the zoom
                if (Input.touchCount > 0)
                {
                    xSlide = Input.GetTouch(pointer).deltaPosition.x * -1.0f; // Apply touch-specific scaler
                    ySlide = Input.GetTouch(pointer).deltaPosition.y * -1.0f; // Apply touch-specific scaler
                }
                else
                {
                    xSlide = Input.GetAxis("Mouse X") * -4.0f; // Apply mouse-specific scaler
                    ySlide = Input.GetAxis("Mouse Y") *  -4.0f; // Apply mouse-specific scaler
                }

                GetComponent<WebInterface>().StopMapCenter();
                float factor = Conversions.GetTileScaleInDegrees((float)map.CenterLatitudeLongitude.x, map.AbsoluteZoom);
                var latitudeLongitude = new Vector2d(map.CenterLatitudeLongitude.x + ySlide * factor, map.CenterLatitudeLongitude.y + xSlide * factor);
                
                map.UpdateMap(latitudeLongitude, map.Zoom);`

Is there a better way or a "proper" way to do this in Unity? I have only found one panning example for Unity/Mapbox and that is found here:
https://github.com/mapbox/mapbox-unity-sdk/issues/608
And that is what my code is based on, but it does not yield the precision panning behavior I need.
Any help on this would be great!

Thanks,

Jonathan L Clark

**Comment by jonathan84clark** [comment]
Ended up solving this one with the help of another engineer.
`                if ((Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began) || (Input.GetMouseButton(0) != prevMouseState))
                {
                    prevGeoPos = geoPosition;
                }
                else
                {
                    double deltaLat = prevGeoPos.x - geoPosition.x;
                    double deltaLong = prevGeoPos.y - geoPosition.y;
                    GetComponent<WebInterface>().StopMapCenter();
                    var latitudeLongitude = new Vector2d(map.CenterLatitudeLongitude.x + deltaLat, map.CenterLatitudeLongitude.y + deltaLong);
                    map.UpdateMap(latitudeLongitude, map.Zoom);
                }`

**Comment by Linspirit98** [comment]
> Ended up solving this one with the help of another engineer.
> ` if ((Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began) || (Input.GetMouseButton(0) != prevMouseState)) { prevGeoPos = geoPosition; } else { double deltaLat = prevGeoPos.x - geoPosition.x; double deltaLong = prevGeoPos.y - geoPosition.y; GetComponent<WebInterface>().StopMapCenter(); var latitudeLongitude = new Vector2d(map.CenterLatitudeLongitude.x + deltaLat, map.CenterLatitudeLongitude.y + deltaLong); map.UpdateMap(latitudeLongitude, map.Zoom); }`

Hi there! In your script i saw GetComponent<WebInterface>().StopMapCenter();
However it says "The type or namespace name WebInterface could not be found(are you missing using directive or an assembly reference?)". What is the package you are using? 
Thanks!

**Comment by jonathan84clark** [comment]
That is part of a custom proprietary package. I am not allowed to disclose the details of that implementation due to an NDA.
