### ISSUE TITLE
Side Walls Not forming correctly?

### ISSUE THREAD

**Issue by Flek26** [mapbox/mapbox-unity-sdk#1393]
![image](https://user-images.githubusercontent.com/33231394/59208383-9bea5580-8b6e-11e9-9c74-d65478373989.png)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.4.1f1

* Mapbox SDK version: 2.0.0

* The platform you're building to: AR 

* A description of what you're trying to do: Trying to get the walls to form around the terrain you you cant "look under" the map.

**Comment by Flek26** [comment]
![image](https://user-images.githubusercontent.com/33231394/59208421-aefd2580-8b6e-11e9-81e0-c1cb30259365.png)

**Comment by brnkhy** [comment]
I failed to recreate this using very similar settings. Can you notice anything imporant different?

<img width="1363" alt="Screen Shot 2019-06-17 at 2 44 51 PM" src="https://user-images.githubusercontent.com/1465390/59602093-92cd2b80-910e-11e9-8ad4-aae529d15b78.png">

your map root is scaled up, can you try fixing that by hand just to see if it works when it's just 1?

**Comment by Flek26** [comment]
What version of Unity are you using?

**Comment by Flek26** [comment]
![image](https://user-images.githubusercontent.com/33231394/59607827-ad38e200-90d9-11e9-8c42-5dd01aab2c54.png)

**Comment by Flek26** [comment]
Nevermind, I got it to work with just the map prefab that is located inside Mapbox, but the MapbopxAR map dose not work this way

**Comment by aglogger** [comment]
I think the problem here is as follows. The sidewalls are created correctly.  However, the shader in the TableTopAR example clips the map so that it is no longer completely visible to the user. The sidewalls are not adjusted to the visible area and still have the dimensions of the complete map.

Is there any possibility to use sidewalls in this scenario.

**Comment by brnkhy** [comment]
@aglogger ah now I get it but I'm afraid current side wall implementation wouldn't work with that. You would probably need some shader magic to be able to do that, or maybe disable shader clipping all together?
