### ISSUE TITLE
Add water feature to ALL tiles not just the center tile

### ISSUE THREAD

**Issue by jonathan84clark** [mapbox/mapbox-unity-sdk#1394]
_Note: If this is a bug or support ticket, please provide the following information:_
Unity version: 2018.3.14f1
Scripting Runtime Version: .Net 4.x Equivelant
Scripting Backend: Mono
Api Compatibility Level: .Net 4.x
Mapbox SDK version: 2.0.0
The platform you're building to: Windows
* A description of what you're trying to do: I am trying to add water features to ALL generated tiles. Right now only the center tile gets the water feature generated.  I am sure this is pretty simple, any help would be great!
* Steps to recreate the bug if appropriate: Not a defect just need some help
![WaterFeatureReq](https://user-images.githubusercontent.com/6521725/59283518-93058c80-8c1f-11e9-9664-1ed7b0a4c601.png)

**Comment by jonathan84clark** [comment]
I did find a workaround; by reading the pixel of a position at a racast hit and determining the color. I don't love this solution because if the map style gets changed then it won't work, but this will be good for those who need help.
By the way, I found this solution online after doing some digging but the online solution is missing one ultra-critical piece of information; each map tile needs a mesh collider added to it. Like so:
`        foreach (Transform child in map.transform)
        {
            if (child.gameObject.GetComponent<MeshCollider>() == null)
            {
                child.gameObject.AddComponent<MeshCollider>();
            }
        }`

After that you can pull the pixel colors:
`    /// <summary>
    /// Temporary function used to detect water (until we can pull more reliable data from maps)
    /// in the event that the map tile does not have a water feature
    /// </summary>
    /// <returns></returns>
    private bool isWaterClicked(RaycastHit rayHit)
    {
        Renderer rend = rayHit.transform.GetComponent<Renderer>();
        if (rend != null)
        {
            Texture2D mainTexture = rend.material.mainTexture as Texture2D;
            if (mainTexture != null)
            {
                Vector2 pixelUv = rayHit.textureCoord;
                pixelUv.x *= mainTexture.width;
                pixelUv.y *= mainTexture.height;
                Color color = mainTexture.GetPixel((int)pixelUv.x, (int)pixelUv.y);
                if (color.r < waterColor.r + color_tolerance && color.r > waterColor.r - color_tolerance &&
                    color.g < waterColor.g + color_tolerance && color.g > waterColor.g - color_tolerance &&
                    color.b < waterColor.b + color_tolerance && color.b > waterColor.b - color_tolerance)
                {
                    return true;
                }
            }
        }
        return false;
    }`

Is there a better way?

**Comment by brnkhy** [comment]
@jonathan84clark that really shouldn't be even possible 🤔 all tiles are processed one by one so if it works for first tile, it should work for all of them.
Only thing I can think of is, if a module or something bugs out (throws error) on first tile, unity generally just skips rest of the work all together, so that might be it? Are you getting any errors during this?
If not can you send me the latlng and I'll check the area myself as well.

**Comment by jonathan84clark** [comment]
I saw no errors. I also observed the same behavior when I created a brand new Unity project, imported mapbox and tested out the examples.

**Comment by ddutchie** [comment]
I had the same issue. The solution is to untick unique ids on water

**Comment by brnkhy** [comment]
@jonathan84clark @ddutchie Ah yes 🤦‍♂  unique id filtering should be only enabled for buildings on certain datasets, I'm afraid it's very easy to look over at the moment with current editor/inspector. I'm sorry :(
