### ISSUE TITLE
Querying Mapbox streets features at runtime

### ISSUE THREAD

**Issue by Keptrson** [mapbox/mapbox-unity-sdk#1397]
Hello.
I've read the SDK documentation backwards and forwards by now but I can't find a clear answer on this one.
What I'd like to achieve is a runtime codewise (c#) check on the features of a given position. The position will be somewhere on the rendered map. I 'd like to find out such things as landuse. I can't find examples or documentation stating how to access these features from code - only configurations. Android SDK on the contrary clearly lists queryRenderedFeatures as a property.
Leading me to suspect that this is not possible in Unity SDK :-/. 
Am I correct in that?

**Comment by brnkhy** [comment]
@Keptrson you can use mesh or gameobject modifiers for this. each feature is processed and prepared by sdk then pushed down to modifiers. For example, if you create a custom game object modifier and put it under your landuse layer, that modifier will get all landuse features and gameobjects created.
Mesh modifiers will get raw point data and create mesh, gameobject modifier will get properties and created gameobject if I remember correct.
If you check InteractiveStyle map demo scene for example, you can see a bunch of game object modifiers under parks layer. 
Hope that helps!

**Comment by Keptrson** [comment]
@brnkhy Thanks for the help :-).
I think I follow your thinking, but just to make sure I'd like to look inte the InteractiveStyle demo you mention. But is it in the SDK?
Can't seem to find it there among the examples (DataExplorer, AstronautGame etc) though.
Or am I looking in the wrong place?

**Comment by brnkhy** [comment]
@kepta yep, it should be at `Assets/Mapbox/Examples/1_DataExplorer/InteractiveStyledVectorMap.unity`
