### ISSUE TITLE
Using conversions.cs in editor

### ISSUE THREAD

**Issue by colin-young** [mapbox/mapbox-unity-sdk#1398]
I'm trying to create a geo to world calculator utility in the editor be attempting to use `Conversions.GeoToWorldPosition`. From https://github.com/mapbox/mapbox-unity-sdk/issues/294#issuecomment-337267707 I understand that my center point (supplied to `AbstractMap`) is in the center tile, but unlikely to be the coordinates I supply. Is there a way in the editor to get the center of the center tile? Worst case I suppose I could capture that at runtime, but it would be more elegant if I could do it all automatically.

Side note: I don't seem to be able to read the location properties from `AbstractMap` in the editor. Is that expected?

**Comment by brnkhy** [comment]
@colin-young I'm not sure what kind of a tool it is but if it's built to use a map object, abstract map should have location properties after it's initialized. Any chance you're trying to get it before it's initialized? 
Also if `placement options` is set to `location center`, you can simply use latlng as well, as it'll be snapped to unity space origin.

**Comment by colin-young** [comment]
I'm trying to read the abstract map _in the editor_. For now I've just created inputs for the user (me) to enter the Mercator center coordinates and the world scale factor. I understand the map doesn't have any of the tile data, etc., but I was hoping I might be able to get the center and scale properties dynamically in the Unity editor.

Just to explain what I'm doing: the default Mapbox terrain wasn't working for me for various reasons, so I've created my own terrain from source DEM by using QGIS and gdal utilities to map into the correct projection and cropping, then creating a raw heightmap that I import into Unity. Now I'm making edits to the terrain to match the real world and I need to place markers in the editor to aid in sculpting, so I created a little panel where I can enter a latitude and longitude and get the Unity-space coordinates. So now at runtime I'm just using Mapbox to generate the buildings and ignoring the Mapbox terrain portion. I still need to work out how to modify the building extruder to snap to my terrain, but after this little project I think I understand enough about what's going on with coordinate transforms to be able to figure it out.

**Comment by brnkhy** [comment]
@colin-young you should be able to do that (if I understand it correct) but what I was trying to say, objects/fields under abstract map might not be filled until `Initialize` is called. If you check the procedure starting with `StartEditorPreview` method for example, you'll see it calls Initialize and gets everything ready etc. Before that, (I think) we only have that latlng in a textfield in the inspector, right?

**Comment by colin-young** [comment]
I will check that out. I'm guessing I just need to hook into the map completed event (the name escapes me at the moment, but my runtime code uses it) in the editor code.

The odd thing is when I try to read the value from the map, even when adding a reference to the map manually in the editor via a gameobject reference field, I have not been able to read the lat/long property, although now you've got me thinking I might have been going directly for a parsed value and instead need to find the text field. I'll have a poke around tonight and see if that doesn't lead anywhere.

**Comment by colin-young** [comment]
@brnkhy It looks like the method you pointed me to (`StartEditorPreview`) isn't part of the released SDK? I don't see it in the 2.0.0 package and it doesn't appear to be in the `release/v2.0.1` branch, although I do see other editor preview code in there.

**Comment by brnkhy** [comment]
@colin-young this is the method I was refeering (with wrong name); https://github.com/mapbox/mapbox-unity-sdk/blob/dd595b407bc334ea953ae014324da6c0b7278338/sdkproject/Assets/Mapbox/Unity/Map/AbstractMap.cs#L560
You don't need it really, but it shows how system initializes map in editor by SetupMap => InitializeMap methods.

**Comment by colin-young** [comment]
Thanks! That will make it easier for me to find and follow the code. I would have never thought to look in `tile-events` for it
