### ISSUE TITLE
Scriptable Objects Order 

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1399]
Hey guys, 
I want to know if there is a chronological order when we place Mesh Modifier or ObjectGameModifiers. 
For example, for the POI layer (see Fig 1) we have a Prefab Modifier and a FeatureBehaviourModifier is there an order when draging them, when we add a FeatureBehaviourModifier before the Prefab Modifier can that change the behaviour of the POIs? (see Fig 2)
or for the park layer is there an logical order when placing the game object modifiers? (see Fig 3) if we change the order does this change the behaviour of the parks? 
![Fig 1](https://user-images.githubusercontent.com/7107407/59613972-20654700-9120-11e9-88c4-a1aba0a60470.PNG)
![Fig 2](https://user-images.githubusercontent.com/7107407/59613973-20654700-9120-11e9-8567-407ca085ebdb.PNG)
![Fig 3](https://user-images.githubusercontent.com/7107407/59614098-586c8a00-9120-11e9-8005-19b437d02933.PNG)
the first question:
If there is an order so how can put the order through a script instead of adding the game objects to the layers (through a monobehaviour) ?
The second question:
we want to add more than an item of the same type (example two Material Modifiers to the building layer and I want to add a condition when using one and when using the other) how can I do that through a monobehaviour.
Mapbox 2.0.0 
Unity 2017.4.17f1 
@brnkhy Please can you answer my questions? Thanks :)

**Comment by brnkhy** [comment]
hey @roura-12!
Modifiers executed in the orders shown in inspector but dependencies/priorities among them are up to developers to take care at the moment. In example, if I remember correct, `SpawnInsideModifier` is using raycasts to objects in certain layers so in that screenshot above, we had to set layer first, raycast second and only disable object afterwards. So order matters there. But stuff like `MaterialModifier` will most likely won't matter in most cases.

Two material modifiers will definitely wont work as second one will override the first one. If you want to add custom logic/selection to it, which is pretty standard, you should create a custom gameobject material and do it all in one modifier. You can clone existing material modifier, change names, logic etc and use it. We highly recommend using custom modifiers, everything will be easier when you start rolling your own custom ones :)

hope that helps!

**Comment by roura-12** [comment]
Hey @brnkhy 
Thank you for your replay. Can you explain more the idea of custom game object modifier please?

**Comment by brnkhy** [comment]
@roura-12 game object modifiers are run for each feature after a gameobject (mesh etc) created for them. i.e. after mesh and gameobject is created, material modifier sets materials on it.
I would suggest picking basic one first, like layer modifier, putting a breakpoint in it and see how it goes.
