### ISSUE TITLE
Adjust new logo to work with our brand guidelines

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-unity-sdk#14]
@david-rhodes I just saw the logo on https://mapbox.github.io/mapbox-unity-sdk/ and it's looking clipped with a slightly transparent white.

<img width="625" alt="screen shot 2017-04-17 at 5 49 20 pm" src="https://cloud.githubusercontent.com/assets/61150/25106182/3929f49c-2396-11e7-8433-d7d3ea2ac70c.png">

This should be adjusted to match out new brand guidelines
https://122e4e-mapbox.global.ssl.fastly.net/about/press/brand-guidelines/ Concretely:

- Use a full white opaque version
- Dimensions should be 132 x 42 pixels
- There should be an area of padding equal to the circular helmet.

**Comment by david-rhodes** [comment]
This was done: https://www.mapbox.com/mapbox-unity-sdk/
