### ISSUE TITLE
HoloLens build crashes sometimes 

### ISSUE THREAD

**Issue by Spaxe** [mapbox/mapbox-unity-sdk#140]
Windows 10 Creators Update, Unity 5.6.2f1, mapbox-unity-sdk `v100`, HoloLens Emulator 10.0.14393.0

To reproduce:
 1. Load `sdkproject` and open a 3D scene (e.g. MeshGeneration).
 2. Follow steps to set up build settings: https://www.mapbox.com/mapbox-unity-sdk/docs/hololens-development.html
 3. Build and run
 
The app runs sometimes. Some other time, it suspends right away and doesn't do anything.

This also seems to happen with an empty scene with Mapbox/Assets imported, and I am not sure about the exact cause of this. Investigation would be appreciated.

**Comment by BergWerkGIS** [comment]
@Spaxe haven't come across this before. Does it also happen when running your app with VS attached (F5/Debug)?
If so, any useful error messages in the `Output Window`?

**Comment by Spaxe** [comment]
Apologies for the delay in investigating this.

It looks like it's a memory issue on my part - avoiding loading more than 639MB to the VRAM, and things will be okay. :) 

Closing.

**Comment by david-rhodes** [comment]
@Spaxe Thanks for investigating! I've heard the HoloLens is stingy with memory :smirk:.

Out of curiosity, did logs reveal a low memory warning at any point?
