### ISSUE TITLE
Mapbox Token Error on Windows Build Only

### ISSUE THREAD

**Issue by andrewR23** [mapbox/mapbox-unity-sdk#1401]
Hi 
Hope someone can help. 
I am building a standalone Unity .exe for Windows from Mac using Mapbbox. 
(I am a Mac user and not so familar with Windows). 

I am using Unity 2018.3.1 and Mapbox 1.4.5. 

The application and map tests and works fine when built for IOS- all the tile data loads fine - but there are problems  when building and running the same project built for Windows -  the map tiles do not load. 

The error I get is : InvalidTokenExeption: StatusNotYetSet.  

I am using the same mapbox token for both builds, so wonder if it's a preferences issues? 

I have tried exporting the project several times and have found that some of the builds do bring up the  map tiles (but log the same error) whilst on others  the map is blank - or perhaps one tile loads and the  others don't. This inconsistancy is odd. 

Any suggestions welcomed. 

Thanks

Andrew

**Comment by brnkhy** [comment]
Hey @andrewR23,
can you check the suggested fix here; https://github.com/mapbox/mapbox-unity-sdk/issues/1396
