### ISSUE TITLE
Problem with location based game prefab

### ISSUE THREAD

**Issue by Moseco** [mapbox/mapbox-unity-sdk#1402]
Unity version 2019.1.6f1
Mapbox SDK version: 2.0.0

I am having a weird issue with the location based game prefab. 
In a clean project with the SDK freshly installed the location based game scene in the example folder and astronaut example work just fine.
But when I make a new scene and add the location based game prefab from the prefab folder it does not work. The player moves around like in the examples, but no map is shown. The error I get in the console is as follows: 

TransformTileProvider: No location marker transform specified.
UnityEngine.Debug:LogError(Object)

Is there some kind of setup that I am missing or what could I be doing wrong that makes it work in the example scenes but not with the prefab in a new scene?

**Comment by Laguland** [comment]
Hi I just had the same issue. Go to map prefab select abstract map and see if "Camera Extent" option is set to "Camera Bounds". Worked for me :)

**Comment by brnkhy** [comment]
@Moseco as @Laguland suggested, camera might not be looking at the correct spot I guess. You can fix that by switching to camera bounds or playing with camera location/direction etc.
If that's not the case, can you verify if map is created at all (somewhere)? Is the map object in hierarchy filled or empty when you run it? can you see tiles and child objects under tiles?

**Comment by Moseco** [comment]
@Laguland @brnkhy That solved my problem right away! Thank you for the help.

**Comment by Hayls99** [comment]
@Laguland Sorry to bring this up so much later! Can you explain where to find the camera extent option? I am having a similar issue but can't find that option. Thank you!

**Comment by xwindor** [comment]
> @Laguland Sorry to bring this up so much later! Can you explain where to find the camera extent option? I am having a similar issue but can't find that option. Thank you!

I had this issue too. It's not named Camera Extent Option, it's called Extent Option on the Map prefab in the Abstract Map (Script). Click General and you'll see it there. I also selected my main Camera as well. Not sure if that makes a difference.
