### ISSUE TITLE
Unity, mark areas on map and change color of it.

### ISSUE THREAD

**Issue by Laguland** [mapbox/mapbox-unity-sdk#1403]
Hello, 
Is it possible to dynamically change color of map between selected points? 
Something similar to this but in Unity: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ .
I haven't found any tutorials or information about it so I wonder if it is possible and if so where should I look to accomplish it?

**Comment by brnkhy** [comment]
@Laguland we don't have such a tool in the SDK but I believe you can do it by raycasting terrain, keeping track of clicks (corner points) and then triangulating them to create a polygon. Changing color should be easy once you have the polygon

**Comment by Laguland** [comment]
Thanks for the answer!
