### ISSUE TITLE
Missing namespace ARTabletop

### ISSUE THREAD

**Issue by TheDroog1** [mapbox/mapbox-unity-sdk#1404]
I'm using the _ar-foundation-port_ branch. These two errors come out: 

> Assets\MapboxAR\Examples\ARTabletop\Scripts\ARPlaneHandler.cs(24,21): error CS0246: The type or namespace name 'ARPlaneAddedEventArgs' could not be found (are you missing a using directive or an assembly reference?)

> Assets\MapboxAR\Examples\ARTabletop\Scripts\ARPlaneHandler.cs(30,23): error CS0246: The type or namespace name 'ARPlaneUpdatedEventArgs' could not be found (are you missing a using directive or an assembly reference?)`

I have already installed ARfoundation. What am I missing?

**Comment by TheDroog1** [comment]
@atripathi-mb

**Comment by TheDroog1** [comment]
@jordy-isaac

**Comment by atripathi-mb** [comment]
@TheDroog1 The branch is out of date and is not officially supported.

**Comment by bakalarczuk** [comment]
Wait a minute... did you said that there is no support for ARFoundation?
