### ISSUE TITLE
IL2CPP support for UWP 

### ISSUE THREAD

**Issue by stviucalgary** [mapbox/mapbox-unity-sdk#1407]
I have looked at the post from #485, #734, #945, #997, which mention that .net scripting backend is required for UWP / HoloLens builds. Unity 2019.1+ has fully deprecated .net scripting backend in favour of IL2CPP per https://docs.unity3d.com/2018.4/Documentation/Manual/windowsstore-dotnet.html. Just wondering if IL2CPP support for UWP will be added in the near future. 

Thanks in advance

**Comment by TLesaunier-artefacto** [comment]
Hey,

Why this issues is closed ? any solution ? I have same problem here. 
I want to build a UWP (for PC target only), but Mapbox seems to have bug with IL2CPP.
Map is not displaying.

I'm on Unity2019.4.
Build : UWP -> PC target
MapBox : 2.1.1
I have looked at the post from #485, #734, #945, #997 too, try them but not help me. 

Thanks

**Comment by mertusta1996** [comment]
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
