### ISSUE TITLE
Zoomable Map CRASHES !  on iOS

### ISSUE THREAD

**Issue by chinmaygawande123** [mapbox/mapbox-unity-sdk#1409]
* Unity version: 2018.3.1f1
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: IL2CPP
  * API Compatibility Level: .NET 4.x
* Mapbox SDK version: 2.0.0
* The platform you're building to: iOS 12.1
* XCode Version: 10.2.1
  The scene crashes after some time when zooming and panning giving this in XCode:
       "Background Job.Worker 0 (13): EXC_BAD_ACCESS (code=257, address=0x41)"

I have tried the troubleshooting it by changing Abstract Map parameters like used compression, disabled retina and changed Extent options but did not work. Any help would be appreciated. Thank You

Here is the snap of the Abstract Map script:

![Screen Shot 2019-06-27 at 1 51 36 AM](https://user-images.githubusercontent.com/44647335/60393077-40880380-9b2d-11e9-9f67-1301157af491.png)

**Comment by chinmaygawande123** [comment]
Here is the snap of the Abstract Map script: 

![Screen Shot 2019-06-27 at 1 51 36 AM](https://user-images.githubusercontent.com/44647335/60212264-718edc80-987e-11e9-8da8-c1c84aadf0b6.png)

**Comment by timskap** [comment]
https://github.com/mapbox/mapbox-unity-sdk/tree/dataFetcherTileDependencyFix
After adding this commit crashes has stopped

**Comment by chinmaygawande123** [comment]
@timskap Thank You, however I have upgraded to Unity 2019.1.8f1 and the crashes stopped.
