### ISSUE TITLE
Objects position zoom issue

### ISSUE THREAD

**Issue by Laguland** [mapbox/mapbox-unity-sdk#1410]
Hi,
Firstly, what I wanna archive. I want to be able to draw polygons on map and I want to have this polygons in right spot even if I zoom in or out.

I managed to get list of geo locations from mouse click and create polygon from it. The problem is once I zoom, polygon stays in Unity position. I have an idea to track if zoom happened and if so I would iterate through all object and move them to appropriate locations. (Similar to ZoomableMap example solution) I'm just afraid that once there will be a lot of objects(lets say thousands) once you zoom you get lag because Unity will update all positions. So I wonder is there any way to handle it though Features? Or is there any other good way to handle this using Mapbox? 
Also I have issue with custom POI. I set some custom POI at geo locations and once I hit play it shows my POI nicely but only when the zoom has the initial value. Zooming in and out makes it disappear (become grey in the hierarchy).

* Unity version: 2019.1.8f1
* Mapbox SDK version: 2.0

**Comment by brnkhy** [comment]
@Laguland if using custom tileset for polygons is an option, I would suggest trying that out. You'll have to add your polygons using mapbox studio (web tools) but sdk will pull the data (when you add your tileset to map of course) and recreate everything on zoom level changes.
If it's not an option, I can't think of any other way than recreating them on zoom level change. But of course I would highly suggest doing it in coroutine not to block everything.

**Comment by Laguland** [comment]
Thanks for your help :)
