### ISSUE TITLE
Popup on click to POIs

### ISSUE THREAD

**Issue by TheDroog1** [mapbox/mapbox-unity-sdk#1412]
I'm using the example world scale AR. I added points of interest using the special function of the Abstract Map script. I wish that when you click on the various POIs a popup comes out with maybe the description or images etc ... how could I do it?

**Comment by brnkhy** [comment]
@TheDroog1 you can set a custom prefab to be placed in POI locations. And of course these prefabs can contain any script you like. You can add them collider, detect which one is clicked on mouse down, then fetch the data belonging to that one etc.

**Comment by TheDroog1** [comment]
@brnkhy I took json files with points of interest, creating my own dataset. These points of interest are provided, in addition to the name, also a description and a URL for an image. Through the Map Features I was able to spawn prefabs to these POIs and through the POiLabelTextSetter.cs I was able to read both the name and the description (this through a toggle), so as to appear in the exact coordinates. Now I would like to know how to upload images from my dataset, perhaps always using the POiLabelTextSetter.cs.

**Comment by AdeVentura** [comment]
@brnkhy @TheDroog1  Could i please bump this issue, i am also really stuck on finding the best way to do this... How to click on a POI icon sprite (without POI name) in world space and then a pop up window to appear on the canvas overlay with POI name on it, and some buttons etc...

I have tried having the pop up window inactive on the hierarchy and then clicking the Icon (OnMouseDown) make it active,
but with that i cant work out how to pass the POI name from poiLabelTextSetter on the prefab spawned to the active pop up window.
One other thing i tried was making the pop up window a child object of the poi prefab icon, then placing poiLabelTextSetter on the window itself. This worked, however when the icon is clicked, all of the instantiated prefabs in view spawn the window at the same time and overlay each other, only showing the POI name that is rendered first on all that are clicked.
I have a feeling i need to learn some more about GetComponent or in the latter case a way to activate only the one prefab clicked on, But if you could please share which way you think is best way to do this and hint me in the right direction would be greatly appreciated thanks.

**Comment by brnkhy** [comment]
@AdeVentura sorry for the laate response, I missed this somehow.
This would require some custom work though. I think the easiest way would be using a custom prefab modifier. You can name your POI objects with a unique name, then when you detect a click, search a data list for data using that name.
Or you can add a custom script on the gameobject itself, then fetch it and read data off it on click.
