### ISSUE TITLE
Adding POIs from app

### ISSUE THREAD

**Issue by TheDroog1** [mapbox/mapbox-unity-sdk#1413]
I am using the WordScale AR example to display the POIs via the mobile phone camera. I would like to give the user who uses the app the possibility to add his own POI in the place where it is located, perhaps making him indicate also the Name and a Description. How could I do?

**Comment by brnkhy** [comment]
@TheDroog1 I guess you should get the unity space coordinate of where user clicks, convert that to latlng using helper methods inside `AbstractMap` and save it into your database or somewhere. I'm sorry but only the conversion part is really related to mapping, I think rest of it is all depends on your application/requirements/design.
