### ISSUE TITLE
update building layer at runtime

### ISSUE THREAD

**Issue by Miky91** [mapbox/mapbox-unity-sdk#1416]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.3.11f1
  * Scripting Runtime Version: Runtime
  * Scripting Backend: C#
  * Api Compatibility Level: 
* Mapbox SDK version: v 2.0.0
* The platform you're building to: Android
* A description of what you're trying to do:
Is there a way to update the building layer of the map in runtime? when I use the UpdateMapWithLocationProvider only updates the map, but it doesn't update the layers (or maybe it does it wrongly).

Thanks for all!

* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@Miky91 what do you exactly mean by update here? Are you expecting data changes or something? Things should be recreated every time a tile is loaded (first time or again) but data will be same cached data for example.

**Comment by Miky91** [comment]
@brnkhy  while the user moves in location based game, the map loads new places according the current position. But sometimes, the buildings layer loads some buildings in wrong places, like highways. I think it happens only when users moves at a high speed (maybe 50-60 km/h) but I am not sure
