### ISSUE TITLE
Mapbox proper touch gestures

### ISSUE THREAD

**Issue by redagrandrei** [mapbox/mapbox-unity-sdk#1419]
Hello. Does mapbox have proper touch gestures like pinch,pan,zoom and rotate with fingers? For example i didnt find touch rotation. I wrote a scripts myself though there are lots of bugs with map when im rotating some tiles dissapear and so on.

**Comment by redagrandrei** [comment]
For example the same bug posted by somebody else a year ago. 
https://www.youtube.com/watch?v=rpGhag1lLtw

**Comment by Flek26** [comment]
I would recoomend putting the Map object inside a empty game object and then scale/rotate that game object. Thats what I did and it works fine. Rotation and scaling is good.
