### ISSUE TITLE
Level of detail/zoom

### ISSUE THREAD

**Issue by NinjaDanz3r** [mapbox/mapbox-unity-sdk#142]
Use case: RTS style games where the user can zoom in and out and the application displays different tiles depending on the users distance from the map.

Currently I am using a solution where I switch between different abstract maps that have differing zoom levels and layers.
This couples with a system of cameras each rendering a separate abstract map and its tiles.
This is however a very kludgy solution and I believe other users would appreciate a good way to do this.

Loosely related to #141, as this could also benefit from a floating origin implementation.

![map](https://user-images.githubusercontent.com/10200316/27868694-ccdb174e-619d-11e7-90de-082f58594c06.png)

**Comment by brnkhy** [comment]
@NinjaDanz3r I want to try creating a quad tree for this but I love that camera trick as well to be honest 👍

**Comment by NinjaDanz3r** [comment]
Thanks!
It's slightly performance intensive since it's essentially rendering the same scene 5 times but it works.
As you say a quadtree solution using only one cameras frustum (perhaps slightly larger to accomodate for tiles around and behind the camera) projected onto earth space to determine appropriate tiles to load and unload would be wonderful.

**Comment by david-rhodes** [comment]
@NinjaDanz3r This is definitely something we want to do in the future. I bet we could make a quad tree implementation of `ITileProvider`. This would require positioning logic to be handled differently, though.

**Comment by jordy-isaac** [comment]
Closing this one. Please open again if there are any further questions.
