### ISSUE TITLE
How do you change Image of map with script

### ISSUE THREAD

**Issue by Flek26** [mapbox/mapbox-unity-sdk#1420]
How do you change the image that is being used on the map via script? 

I am trying to edit it with a button in game - to be able to witch from satellite view to street view. (If i have to re-render the map that is fine).

**Comment by brnkhy** [comment]
@Flek26 I think this is what you're looking for;
https://github.com/mapbox/mapbox-unity-sdk/blob/dd595b407bc334ea953ae014324da6c0b7278338/sdkproject/Assets/Mapbox/Unity/Tests/ApiTest.cs#L112

It might not work with and old version though.
