### ISSUE TITLE
Load map of real world bounding box?

### ISSUE THREAD

**Issue by linojon** [mapbox/mapbox-unity-sdk#1422]
Hello, this is more a question than an issue. I am pretty familiar with the mapbox unity sdk and abstract map. Given i load a map at start with player at center, a predetermined zoom level, and extents 1 in each direction. I then want to let the player move outside this bounding box and load the additional tiles including the player's new location tile and any inbetween him and the original extents. Help and suggestions would be appreciated. Thanks.

**Comment by linojon** [comment]
a few additional notes/questions
- This is similar to https://github.com/mapbox/mapbox-unity-sdk/issues/1125 but instead of calculating a zoom, i want to keep the current zoom and modify the extends to include the new location
- Using MapBox unity sdk 2.0.0, Unity 2019.1
- is there a function to get the Vector2dBounds of the current map (all the tiles not just one tile)?

**Comment by linojon** [comment]
ok, so i implemented a solution.

First, the following function calculates the bounds of a loaded map (as i couldn't find an equivalent in the SDK):

```
    public static Vector2dBounds MapBounds(AbstractMap map)
    {
        Vector2dBounds bounds = new Vector2dBounds();
        bool started = false;

        foreach (UnwrappedTileId tile in map.CurrentExtent)
        {
            Vector2dBounds tileBounds = Conversions.TileIdToBounds(tile.X, tile.Y, (int)map.Zoom);
            if (!started)
            {
                bounds = tileBounds;
                started = true;
            }
            else
            {
                bounds.Extend(tileBounds);
            }
        }
        return bounds;
    }
```

And a query whether a lat lon position is in bounds:

```
    public static bool InBounds(Vector2dBounds bounds, Vector2d point)
    {
        // x is n/s , y is e/w !
        return (point.y >= bounds.West && point.y <= bounds.East && 
                point.x >= bounds.South && point.x <= bounds.North);
    }
```

My map loader initializes an ExtentOptions when the map is first loaded

```
    private RangeTileProviderOptions extentOptions;

    public void LoadMap(Vector2d latlon, int zoom)
    {
        IsLoaded = false;
        HasError = false;
        ErrorMsg = "";

        RangeTileProviderOptions extentOptions = (RangeTileProviderOptions)_map.Options.extentOptions.GetTileProviderOptions();
        extentOptions.north = 1;
        extentOptions.south = 1;
        extentOptions.east = 1;
        extentOptions.west = 1;
        
        _map.Options.locationOptions.latitudeLongitude = latlon.x.ToString() + "," + latlon.y.ToString();
        _map.Options.locationOptions.zoom = zoom;
        _map.SetExtentOptions(ExtentOptions);

        _map.Initialize(latlon, zoom);
    }
```

Then, this ExpandMap grows the extents one unit at a time in the direction of the location we want to include.

```
   public void ExpandMap(Vector2d latlon)
    {
        while (InBounds(latlon) == false && HasError == false)
        {
            // x is n/s , y is e/w !
            if (latlon.y > Bounds.East)
                ExtentOptions.east++;
            if (latlon.y < Bounds.West)
                ExtentOptions.west++;
            if (latlon.x > Bounds.North)
                ExtentOptions.north++;
            if (latlon.x < Bounds.South)
                ExtentOptions.south++;

            int tileCount = (1 + ExtentOptions.east + ExtentOptions.west) *
                            (1 + ExtentOptions.north + ExtentOptions.south);
            if (tileCount >= _maxTileCount)
            {
                HasError = true;
                Debug.Log("abort Expand Map: Map tile count exceeds max " + tileCount + " / " + _maxTileCount);
                ErrorMsg = "Map tile buffer full";
            }
            else
            {
                IsLoaded = false;
                HasError = false;
                ErrorMsg = "";
                _map.SetExtentOptions(extentOptions);
            }
        }
    }
```

Note i have a max tile count to prevent the map from exploding by a position way out of bounds.

Also, as with my normal map loader code, i put this in an coroutine that's managed by a MapLoader helper with OnInitialized and OnVisualizerStateChanged listeners already implemented.

**Comment by brnkhy** [comment]
@linojon sorry for the very late response :(
I'll try this myself and maybe even use it it SDK, thank you very much!
