### ISSUE TITLE
Side walls not spawning correctly at new locations

### ISSUE THREAD

**Issue by Flek26** [mapbox/mapbox-unity-sdk#1426]
![image](https://user-images.githubusercontent.com/33231394/61488026-da90de00-a96c-11e9-9b6d-58e5080e6e12.png)

![image](https://user-images.githubusercontent.com/33231394/61488150-204da680-a96d-11e9-84c7-33ee22cb8b2d.png)

This is what I get when I go to a new location. Any reason why?

**Comment by brnkhy** [comment]
@Flek26 that's strange. by new locations, do you mean tiles loaded after initial loading? Like by camera movement and stuff?
