### ISSUE TITLE
Mapbox Unity lat/lon in-game coordinates don't match real life lat/lon coordinates

### ISSUE THREAD

**Issue by beckymathew** [mapbox/mapbox-unity-sdk#1427]
* Unity version: 2019.3.0a6
  * Scripting Runtime Version:
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: 2.0.0
* The platform you're building to: Windows 10

Hi! I’m trying to create a simulation of a drone that flies around the Brown University campus in Providence, RI. The map is centered at (41.826771, -71.40255). The drone also starts at the center of the map. The basic code attached to my GameObject is as follows. 

```
private void Update() {
            float lat = 41.8298f;
            float lon = -71.398465f;
            Vector3 position = Conversions.GeoToWorldPosition(lat, lon, map.CenterMercator, map.WorldRelativeScale).ToVector3xz();

            float step = speed * Time.deltaTime;
            transform.position = Vector3.MoveTowards(transform.position, position, step);
        
        if (translation.magnitude <= 0.5) {
                Debug.Log("Landed at lat/lon: " + transform.GetGeoPosition(map.CenterMercator, map.WorldRelativeScale));
        }
}
```

I’ve noticed that the drone goes to the “correct” latitude and longitude in game, but it doesn’t match the latitude and longitude found on Google Maps, Yahoo, TAMU, OSM, etc. 

For example, I tried to send it to (41.8298, -71.398465), which is the latitude and longitude for the Nelson Fitness Center (225 Hope St) on Google Maps and other sites. However, in the Unity map, this latitude and longitude is pretty far from the in-game Nelson Fitness Center, which is at (41.83362, -71.3924) according to Mapbox’s GetGeoPosition function. 

Interestingly, I’ve noted that the latitudes and longitudes get more and more inaccurate the farther away from the center of the map they are (based on six locations that I tried). However, the inaccuracy isn't by a constant factor. If I send the drone to the center at (41.826771, -71.40255), it matches exactly the same lat/lon found on Google Maps etc. 

Why doesn’t Mapbox’s latitude and longitude coordinates match what can be found online? How can I send my drone to the correct locations? 

I attached some screenshots below. Here’s what happens if you enter the Nelson Fitness Center’s latitude and longitude (not perfect, but pretty close). 
![Google Maps](https://user-images.githubusercontent.com/19481959/61541167-25623280-aa0d-11e9-9e79-f2939d2f4e85.PNG)

This is if the drone goes to those same coordinates in the Unity map (lat/lon coords circled in red at the bottom). It’s so far from the Nelson that you can’t even see the Nelson. 
![Mapbox coords](https://user-images.githubusercontent.com/19481959/61541198-3743d580-aa0d-11e9-817e-5220f7b34fab.png)

Here’s what happens when I manually move the drone to the Nelson Fitness Center. Mapbox’s calculated longitude and latitude for this is circled in red at the bottom. 
![Unity coords](https://user-images.githubusercontent.com/19481959/61541255-52aee080-aa0d-11e9-8732-3906951458b3.png)

Thank you!

**Comment by brnkhy** [comment]
@beckymathew I gave it a quick test, 
<img width="1678" alt="Screen Shot 2019-07-22 at 3 10 42 PM" src="https://user-images.githubusercontent.com/1465390/61631457-17254800-ac93-11e9-9b7f-5d89333510ed.png">
So if you compare image below to the google maps image you posted above, you'll see sphere is positioned at roughly at the same point as the google maps pin and latlng in your screenshot is again almost exactly same as the latlng I have in the script field at the bottom right corner (there's 0.000002 difference in latitude but I guess that would be pretty small and probably due to sphere/pin positioning difference).

This is the script I used; 
```
public class LatLngCheck : MonoBehaviour
{
    public AbstractMap Map;
    public Vector2d LatLng;

    private void Update()
    {
        LatLng = Map.WorldToGeoPosition(transform.position);
    }
}
```

Can you give it a try and see if you get similar results or not?
I feel like either you're passing a slightly off position values (maybe due to wrong object hierarchy/parenting/scale?) or maybe there's something off about map rotation/scale.

**Comment by beckymathew** [comment]
Hi! I realized that I had Map's transform scale at (2, 2, 2). When I reset it back to (1, 1, 1), the latitude and longitude worked perfectly. I'm not sure why it matters, but everything is okay now. Thank you so much!
