### ISSUE TITLE
Zooming using pinch or MouseZoom Locations

### ISSUE THREAD

**Issue by acoale** [mapbox/mapbox-unity-sdk#1428]
I was working on adjusting the zoom logic of the QuadTreeCameraMovement Script. i want the Zoom to be focused on a position of the map that the mouse is over OR pinch and zoom are at. I have code that I believe Should work, unless someone can tell me WHY it would not. 

HandleMouseandKeyboard
```
Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            var rayX = ray.origin.x;
            Debug.Log(rayX.ToString());
            var rayY = ray.origin.y;
            Debug.Log(rayY.ToString());
            Vector3 rayCastHit = new Vector3(ray.origin.x, ray.origin.y, ray.origin.z);
            var rayCast = _mapManager.WorldToGeoPosition(rayCastHit);

            zoomPoint = new Vector2((float)rayCast.x, (float)rayCast.y);
```

ZoomMapUsingTouchOrMouse
```
string zoomSpot = zoomPoint.x.ToString(CultureInfo.InvariantCulture) + ", " + zoomPoint.y.ToString(CultureInfo.InvariantCulture);
            Debug.Log("The Zoom Spot is: " + zoomSpot.ToString() + " *********************************************");
            var _location = Conversions.StringToLatLon(zoomSpot);
            Debug.Log("The Location is: " + _location.ToString() + " *********************************************");
            var zoom = Mathf.Max(8.01f, Mathf.Min(_mapManager.Zoom + zoomFactor * _zoomSpeed, 21.0f));
            if (Math.Abs(zoom - _mapManager.Zoom) > 0.0f)
            {
                _mapManager.UpdateMap(_location, zoom);
            }
```

When i zoom the map moves all over the city yet the latlon in the debug from _location and zoomSpot read as follows:

The Zoom Spot is: 39.48789, -104.7651 *********************************************

The Location is: -104.76510,39.48789 *********************************************

which is the location of a marker I have in this location.

**Comment by brnkhy** [comment]
@acoale you can find the cursor zoom part here; https://github.com/mapbox/mapbox-unity-sdk/tree/CursorZoom
