### ISSUE TITLE
Add support for Unity UI

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#143]
Currently, MB only supports loading a map in 3D with meshes.

It would be great to be able to load the map into Unity UI (aka a Canvas). The principle would be basically the same, but instead of generating meshes you would add `Image` components to tiles.

I took a crack at implementing it and it's relatively straight forward, just a bit of recalculating: https://gist.github.com/mihakrajnc/06c5c6e6fae19acd5af13d63856c16b2

Should work for the most part. And there's probably a way of calculating the positions without knowing the tile size, but I couldn't find it 👎

Note: You will need to add `IMap Map` to  `UnityTile` for this to work - can be retrieved in `Initialize`.

**Comment by brnkhy** [comment]
@mihakrajnc we talked&experimented about 2d maps in the past but we just used sprites. I have no idea but I never really thought about UI maps until now. I'll check this as soon as possible, thanks Miha! 👍

**Comment by mihakrajnc** [comment]
I've updated the script, it had some problems running out of the editor (for instance, Mapbox doesn't place the tiles as children of the root object when not in editor, which doesn't work with the Canvas). Here are also my "MinimapController", might come in handy:

```csharp
[RequireComponent(typeof(AbstractMap))]
public class MinimapController : MonoBehaviour
{
    [SerializeField] private RectTransform mapRoot;
    [SerializeField] private RectTransform rotationRoot;
    [SerializeField] private int tileSize = 100; // TODO: This should be automatic

    // Cached
    private AbstractMap cAbstractMap;

    private void Start()
    {
        cAbstractMap = GetComponent<AbstractMap>();
        TelemetryManager.Instance.TelemetryProvider.OnLocation += OnLocationUpdated;
        TelemetryManager.Instance.TelemetryProvider.OnHeading += OnHeadingUpdated;
    }

    private void OnHeadingUpdated(float bearing)
    {
        Vector3 compassEulerAngles = rotationRoot.eulerAngles;
        compassEulerAngles.z = bearing;
        rotationRoot.eulerAngles = compassEulerAngles;
    }

    private void OnLocationUpdated(Vector2d location)
    {
        if (!cAbstractMap.enabled)
        {
            cAbstractMap.CenterLatitudeLongitude = location;
            cAbstractMap.enabled = true;
        }

        Vector3 targetPosition = Conversions.GeoToWorldPosition(
                                     location,
                                     cAbstractMap.CenterMercator,
                                     cAbstractMap.WorldRelativeScale).ToVector3xz() / tileSize * 512 *
                                 mapRoot.localScale.x;

        float targetX = -targetPosition.x;
        float targetY = -targetPosition.z;

        targetPosition.x = targetX;
        targetPosition.y = targetY;
        targetPosition.z = 0;

        mapRoot.anchoredPosition = targetPosition;
    }

    private void OnDestroy()
    {
        if (!TelemetryManager.HasInstance) return;

        TelemetryManager.Instance.TelemetryProvider.OnLocation -= OnLocationUpdated;
        TelemetryManager.Instance.TelemetryProvider.OnHeading -= OnHeadingUpdated;
    }
}

```

And my Minimap setup:
![screen shot 2017-07-11 at 12 06 20](https://user-images.githubusercontent.com/8857844/28063454-6f9d7b88-6631-11e7-83e0-a5f9b6a871a9.png)

**Comment by david-rhodes** [comment]
@mihakrajnc Thanks for sharing! This is something I've wanted to do, but was unsure how popular of a feature it would be (UGUI support for maps). Seems there's interest :smirk:.

I wanted to point out that https://github.com/mapbox/mapbox-unity-sdk/pull/145 has fixed the no-parent problem for builds on device.

**Comment by brnkhy** [comment]
@mihakrajnc I just had time to try it out. It'll take some polishing, like using another gameobject as canvas and custom inspector etc but it's a nice starting point, especially with the positioning formula sorted out. Thanks again!

**Comment by mihakrajnc** [comment]
@MSFX Which parts are you having problems with? I'm still using both scripts in my code.

Note that `TelemetryManager` is my script and is not included in the SDK, so you'd have to find some other way of providing the coordinates to the `MinimapController `script.

**Comment by smxthereisonlyone** [comment]
@mihakrajnc I, too, have compile errors. Could you check with the latest sdk, please?
