### ISSUE TITLE
Failed unit tests in latest SDK version

### ISSUE THREAD

**Issue by timaiken95** [mapbox/mapbox-unity-sdk#1431]
* Unity version: 2018.3.7f1
* Mapbox SDK version: v2.0.0

A handful of unit tests fail in the latest version of Mapbox SDK for Unity. I did a clean install of the Unity package, but to no avail.

![failed_tests](https://user-images.githubusercontent.com/23046787/61872334-59dd5f00-aee3-11e9-9420-796fa577a80e.png)

**Comment by brnkhy** [comment]
I think this should be fixed now. 🙇
