### ISSUE TITLE
Zoomable Map - vector tiles instead of image tiles?

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1434]
How would I be able to stream vector instead of image tiles into the Zoomable Map scene?

**Comment by brnkhy** [comment]
@smxthereisonlyone You can enable vector from abstract map script inspector but(1) vector data isn't available on lower zoom levels (2) vector data (and mesh generation) is heavy so it probably won't be smooth out of box.

**Comment by smxthereisonlyone** [comment]
I will check it out. Maybe I can use another example as starting point and adapt the UI? For the AR examples (inspired by Pokemon Go), is the mesh generation better? So, theoretically, I could go from there and create maybe a top-down view?

**Comment by smxthereisonlyone** [comment]
Also @brnkhy , I have to say, that I do not find the options in the "abstract map script inspector" to choose the vectors.

**Comment by brnkhy** [comment]
@smxthereisonlyone I think mesh generation demo scene might be better to understand how things works as it's more simplistic.
If you check the `Map Layers` section, you'll see it'll be either disabled (`none`) in zoomable mao scene or there are no layers added (nothing under `map features` box). Again basic mesh generation demos would help to understand how it works.
<img width="447" alt="Screen Shot 2019-08-12 at 4 59 44 PM" src="https://user-images.githubusercontent.com/1465390/62870639-a23daf00-bd22-11e9-9376-2c0999426781.png">

**Comment by Philipp-M** [comment]
As far as I see the map styles aren't rendered yet on the device (vector instead of image layer), and only separate features can be enabled (like 3D-buildings).
Is there any plan to support map style device rendering of map layers (similar to e.g. Mapbox GL JS)?

**Comment by smxthereisonlyone** [comment]
Cool got it to work. How can I make it much more smooth? I need it to be able to run alongside ARKit on an iPhone SE - how can I make the polygons, labels etc. run fast? Thanks!
