### ISSUE TITLE
How to change "range around center" extents at runtime

### ISSUE THREAD

**Issue by peachpieproductions** [mapbox/mapbox-unity-sdk#1435]
I am trying to change the extents of the map at runtime with code. I have the extent options set to "Range around transform" and all the options N, S, E, W are all set to 1. I would like to change these values at runtime using code. I have been digging thru the SDK and cannot seem to figure it out. 

![image](https://user-images.githubusercontent.com/22354428/62297946-12eded00-b440-11e9-88c2-5b132f03ff67.png)

**Comment by brnkhy** [comment]
@peachpieproductions if you're using latest from repo, you can do this; https://github.com/mapbox/mapbox-unity-sdk/blob/dd595b407bc334ea953ae014324da6c0b7278338/sdkproject/Assets/Mapbox/Unity/Tests/ApiTest.cs#L52-L55

**Comment by peachpieproductions** [comment]
Awesome thank you so much!
