### ISSUE TITLE
Mapbox: Unity Cluster custom markers

### ISSUE THREAD

**Issue by anandp803** [mapbox/mapbox-unity-sdk#1437]
I want to cluster custom spawned markers using SpawnOnMap.cs.
Please let me know if we can cluster the markers based on Radius or if the markers collides with other marker on zoomout. Or do Mapbox unity provides cluster feature for custom markers.

**Comment by brnkhy** [comment]
@anandp803 I'm afraid clustering isn't available on unity sdk at the moment :(

**Comment by adikhel** [comment]
Do you have any plans to support this?

**Comment by spydeveloper** [comment]
Is there any news related to the custom cluster markers you guys usually go silent like this on multiple things we need support or any quick solution that you can give.

**Comment by brnkhy** [comment]
No clusters is not planned at the moment.

**Comment by tomires** [comment]
In case somebody is still looking for a solution, here is one with O(n^2) complexity. The function should be called when user finishes the pinch-to-zoom gesture.

https://gist.github.com/tomires/bba62ef7949018ee4d75cebefb0f69c3

**Comment by WaseemAbbas-DevCrew** [comment]
@brnkhy @anandp803 

Please check the **[SuperCluster-CSharp](https://github.com/DevCrew-io/SuperCluster-CSharp)** library available on [GitHub](https://github.com/DevCrew-io/SuperCluster-CSharp) and [NuGet packages](https://www.nuget.org/packages/DevCrew.SuperCluster). It is a port of the SuperCluster javascript library by MapBox. 

You can implement clustering in your Unity3D map with Mapbox.
