### ISSUE TITLE
Is there anyway to change color or height of buildings dynamically?

### ISSUE THREAD

**Issue by jjdblast** [mapbox/mapbox-unity-sdk#1439]
A noob question, is there anyway to update buildings' color and height at runtime? Such as change colors or height every 10 seconds.

I'm learning mapbox sdk examples 'interactiveStyledVectorMap', and trying to add MapboxStylesColorModifier in Features to do that, but have no idea how to do next. Is there any suggestions?

![image](https://user-images.githubusercontent.com/3394810/62614018-2f58c080-b93d-11e9-9d4a-36649c4b076c.png)

**Comment by brnkhy** [comment]
@jjdblast there's bunch of different ways to do that but all depends on your use case really. You can do it in a gameobject modifier as you started for example. You would have to keep track of all gameobjects in there, then get their material and change color at will for example. Changing height would be much trickier but you can just scale building in y axis as well.
