### ISSUE TITLE
World Scaled Map with Runtime Zoom Change

### ISSUE THREAD

**Issue by Neutrinora** [mapbox/mapbox-unity-sdk#1441]
Is it possible to get a map with following functionalities simultaneously with MapBox?:
- Runtime Zoom Level Change
- Fixed Map Transform Scale (No position change of a point on map in unity coordinates along various zoom levels)

If possible (and how :| ), i'm going to scale the map along the unity world (almost 200000x200000 unity meters), and going to limit zoom level to 18 to prevent floating point precision errors. 

We succeed building a map with our own tile streamer. But we want to use MapBox to handle map stuff. Trying to figure out a way to use MapBox in same way to take advantage of MapBox's cool additional features...

It's probably an easier solution than actual ZoomableMap example, but it's hard to dig deep in codes to change engine stuff, couldn't estimate where to point changes on, without breaking other stuff.

Related issues:
#121 #202

**Comment by brnkhy** [comment]
Hello @Neutrinora!
I'm trying to understand it but your case is a little confusing. 
First of all, how will world scale thing work with zoom levels? If everything will be in real sizes, why do you want zoom level change at all? I mean let's imagine you have a city at real scale, at that point zoom level only means detail level on vector layer or image layer. You want to... zoom out? but still keep everything at world scale so the result will be lower resolution imagery and building details? Am I getting this wrong?

**Comment by Neutrinora** [comment]
Thanks for response @brnkhy 
You're not getting this wrong. That's what we're already using. We've tried the same with mapbox, but couldn't succeed.

**Comment by brnkhy** [comment]
@Neutrinora I'm afraid I still don't understand the goal here. Can you explain what you want to happen a little more? Let's say I have a huge urban area with satellite imagery on terrain and buildings etc. Then I zoom out. What should happen?

**Comment by Neutrinora** [comment]
@brnkhy It's hard to describe as text, but have an idea now.
Thing about QuadTreeTileLoader...
Works like a QuadTreeTileLoader, except it doesn't scale unity objects, instead really zooming out unity camera.

**Comment by brnkhy** [comment]
@Neutrinora I think I just realized, by zooming out you mean camera zoom, not the zoom level of the map, is that correct?

**Comment by Neutrinora** [comment]
@brnkhy Actually, changing zoom level of camera and used dataset at simultaneously.

**Comment by supergra** [comment]
> You want to... zoom out? but still keep everything at world scale so the result will be lower resolution imagery and building details? Am I getting this wrong?

I think I may have exactly the same problem as @Neutrinora, and yes this is the correct interpretation for my case. 

I'd like to be able to change zoom levels at runtime, because (1) I load data for an arbitrary location, and (2) sometimes the imagery looks better at different levels. 

However, if I change the zoom level slider during runtime from X to Y, the position of everything on the map jumps, whereas if I just start at zoom Y, it is correct.

**Comment by sethHex** [comment]
would be amazing if you could actively change the mapbox zoom level at runtime for maps, seems like it always creates issues and renders blank tiles?
