### ISSUE TITLE
Is The SpawnInsideModifier Broken?

### ISSUE THREAD

**Issue by thsbrown** [mapbox/mapbox-unity-sdk#1442]
I have using the SpawnInsideModifier as a reference for producing prefabs inside a feature set. The problem is that the more that I inspect / debug the SpawnInsideModifier the more i'm beginning to believe that it's quite a bit buggy.

For example I'm noticing that it doesn't seem to cleanup the prefabs it Instantiates sometimes. It also seems to place prefabs in very strange position when moving between tiles. Below is link to a video demonstrating the bug.

[Demo of the bug](https://youtu.be/NDMJ--saJsk)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: **2018.4.2f1**
  * Scripting Runtime Version: **.NET 4.x** 
  * Scripting Backend: **Mono**
  * Api Compatibility Level: **.NET Stanadard 2.0**
* Mapbox SDK version: **2.0.0**
* The platform you're building to: **(In Editor)**
* A description of what you're trying to do: **Use the SpawnInsideModifier to spawn prefabs inside a specified feature data set.**
* Steps to recreate the bug if appropriate: 

**1. Open Astronaut Game Scene
2. Open Scene view
3. Select MapboxAstronaut in hierarchy 
4. Move Mapbox Astronaut around scene (drag green transform square to move by x & z) letting tiles load in and out as you drag him.
5. Notice how trees begin spawning in incorrect positions.**

* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
Hello @Spartanace1024 !
SpawnInsideModifier is one of the oldest ones I believe and I'm afraid not the most polished one. I thought we fixed those issues in your video but those fixes might not be in 2.0 I guess. Have you tried the same with latest from dev branch? It'll probably work fine with that.
