### ISSUE TITLE
Can't find an effective method to 'Layer' raster data on top of eachother

### ISSUE THREAD

**Issue by kevpegan** [mapbox/mapbox-unity-sdk#1445]
**Unity version:** 2018.3.14f1
**Scripting Runtime Version:** .NET 4.x
**Scripting Backend:** Mono
**Api Compatibility Level:** .NET4.x
**Mapbox SDK version:** 2.0.0
**The platform you're building to:** Windows
**A description of what you're trying to do:**
The application I am creating requires multiple 'layers' of a map to be able to be [swiped on and off](https://gyazo.com/428f0d9380aaed83b80d9db42a7e3708), which requires me to have a separate material for each layer so I can adjust the shader parameters for each layer. This is fine for Vector Layers, since I am able to use Tippecanoe to join mbtiles together and have all of the vector tiles layered in one map. However, for raster layers the only option I see is to create multiple instances of map objects and layer them on top of eachother in the hierarchy, since each 'AbstractMap' can only support one 'Image' data source, and even if it could support multiple data sources, each 'Tile' can only have one material attached to it. This solution I came up with _works_, but it requires a significant amount of RAM, and unfortunately the computer I will be deploying to does not have enough RAM.

Is there any way to have a 'layered' approach to raster data similar to how the 'Map Layers' section works with the vector data? If not, is there a better way to approach this situation than what I am currently doing?

**Comment by brnkhy** [comment]
Hello @kevpegan !
I did something similar for my pet project some time ago here; http://barankahyaoglu.com/map/
In the left menu under overlay imagery section, you can select roads and see the effect for example.
If I remember correct what I did was; created another factory (shouldn't be necessary though), call second imagery for each tile, assign it to a second texture field in the material with custom shader. Then in shader I draw only certain areas (so it'll just overlay and some areas will be transparent). I don't think you can avoid custom shader part really, especially if you want to do the slider part.

**Comment by kevpegan** [comment]
Thanks for the idea @brnkhy, I didnt think to try pulling the image data into another material, I will try doing that and update later with how it goes.
