### ISSUE TITLE
PoiLabelTextSetter does not work in my scene

### ISSUE THREAD

**Issue by Moseco** [mapbox/mapbox-unity-sdk#1449]
Using the PoiLabelTextSetter example script and the interface IFeaturePropertySettable does not work in my scene and I can't seem to figure out what is wrong.

I have taken a look at the example scene POIPlacement, and it works fine and the names get displayed correctly. 

Even taking the Prefabs from the example scene and using them in my scene does not work. Is there a setting in the map that I am missing?

**Comment by brnkhy** [comment]
<img width="351" alt="Screen Shot 2019-08-26 at 2 00 23 PM" src="https://user-images.githubusercontent.com/1465390/63686173-e2645d80-c809-11e9-8bfe-8872cae9a092.png">
@Moseco if you're using vector layers section, you should have a prefab modifier as seen in the screenshot above. That's the script which uses IFeaturePropertySettable. Any chance you're missing that?

**Comment by Moseco** [comment]
Turned out to be a very simple problem. I did not have the IFeaturePropertySettable script on the root object in the prefab. Whoops.
