### ISSUE TITLE
Buildings with Satellite Style Texturing show up incorrectly

### ISSUE THREAD

**Issue by ElRoberto13** [mapbox/mapbox-unity-sdk#1456]
When I try using the Satellite style, each building is displayed with the same satellite image. This makes for buildings with incorrect texturing - roofs made out of cars and roads.

Here's an image of the buildings with Satellite Style applied:
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/42687232/64397084-eecc8f80-d02d-11e9-8717-04b717508ae7.png">
Notice how the rooftops all have the same image. Instead of showing the rooftops, they display the same image of a road on them.

For reference, here's an image with the buildings turned off, so you can see what is supposed to be displayed on the rooftops.
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/42687232/64397184-571b7100-d02e-11e9-9fa9-1065980502bc.png">

My goal is to display the buildings with the Realistic Style for the sides and the Satellite Style for the roofs. I was going to inquire how to do that, but then I noticed that the Satellite style wasn't working properly to begin with. 

Another, possibly helpful, side note: When new tiles are loaded, such as when using the camera bounds option, all the rooftop images change simultaneously to another incorrect satellite image.

* Unity version: 2018.3.8f1 (and also occurred on 2019.3.0b1)
* Mapbox SDK version: 2.0.0
* The platform you're building to: iOS
* A description of what you're trying to do: Texture buildings using the Satellite Style
* Steps to recreate the bug if appropriate: Apply satellite style to buildings

**Comment by brnkhy** [comment]
This is most likely a material cloning problem which should be fixed on dev branch. You're probably using the latest package though and it probably still has that problem. An easy way to detect it; if you load only one tile, it'll look correct. If you load two tiles, second one will look correct and first one will look wrong, using the same texture as the second one.
What's happening is, system isn't cloning the material for each tile and overriding the texture in the original one.
By the way, I believe satellite rooftops with realistic textured sides isn't an available option in sdk at the moment but you should be able to do it with some customization.
First thing I would suggest is checking this code block in `MaterialModifier.cs`
```
else if (_options.style == StyleTypes.Satellite)
{
	for (int i = 0; i < min; i++)
	{
		mats[i] = Instantiate(_options.materials[i].Materials[UnityEngine.Random.Range(0, _options.materials[i].Materials.Length)]);
	}

	mats[0].mainTexture = tile.GetRasterData();
	mats[0].mainTextureScale = new Vector2(1f, 1f);
}
```

and be sure `Instantiate` is there.

**Comment by ElRoberto13** [comment]
Awesome, thank you. Any idea on when the non-dev branch package that I'm on will be updated to fix this problem?

**Comment by brnkhy** [comment]
v2.1.0 is released and you shouldn't have this problem with it!
closing this for now but feel free to reopen if you still have problem.
