### ISSUE TITLE
Some terrain tiles are white

### ISSUE THREAD

**Issue by imtrobin** [mapbox/mapbox-unity-sdk#1457]
Hi,  I use the Citysimulatorprefab, and change to Satelite, some terrain textures are white/wrong color.

![image](https://user-images.githubusercontent.com/531606/64404273-f6cc1400-d0ad-11e9-8c81-a69d22c32ca2.png)

![image](https://user-images.githubusercontent.com/531606/64404305-0fd4c500-d0ae-11e9-94ed-c35c1d28c6ed.png)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version:  2018.4.1f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version:  2.0
* The platform you're building to: Android

**Comment by brnkhy** [comment]
@imtrobin I checked the same lat/lng myself and I'm getting the same results. I'm afraid this is a data issue and satellite imagery of that region at that zoom level is just desaturated like that. I'll try to ask around with our satellite teams but there's no easy/quick fix for that :(
I'll close this for now but feel free to reopen it if you have any follow up questions.
