### ISSUE TITLE
Roads have transpareny fighting

### ISSUE THREAD

**Issue by imtrobin** [mapbox/mapbox-unity-sdk#1463]
Hi, I'm using the city simulator map. I noticed that the roads generated will have transparancy Z fight with my clouds/UI

![image](https://user-images.githubusercontent.com/531606/64940721-58069b00-d897-11e9-8d52-27db505e9bd5.png)

Unity 2018.1.9f1

**Comment by brnkhy** [comment]
Roads thends to have z-fighting with each other but I haven't seen them having troubles with other elements in the world. Is that canvas in world space? Are you using special shaders for roads? I'm afraid it's hard to say something with only this much info :(

**Comment by imtrobin** [comment]
Canvas is in world space. But the roads are default, I just added transparent clouds on on the sky. I suppose  I need to change the road render order or something
