### ISSUE TITLE
Buildings suffer from strange artifacts

### ISSUE THREAD

**Issue by iamcam** [mapbox/mapbox-unity-sdk#1471]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.2.5f1
* Mapbox SDK version: 2.0.0
* The platform you're building to: Mac
* A description of what you're trying to do:
When you get close enough to buildings, you'll start to notice they aren't being rendered properly - objects farther from the camera sometimes appear in front of near buildings. Strange boxes appear to float in the middle of the air (probably another ordering problem)

* Steps to recreate the bug if appropriate:
Use the zoomable map example and get in close to some sky scrapers near Central Park. Change the camera angle so you're looking down at an angle. As you move the camera, you'll start to see shapes are not quite moving as maybe they should be. Also notice internal walls(?) show through building faces that actually appear to be missing. This occurs with the forward and deferred rendering paths.

When using the legacy vertex shader, I don't experience these problems, however the vertex shader also lacks shadows (sorry - I'm a bit of a n00b and might be missing something).

I don't know if I'm missing something in the Mapbox configuration, but it really seems like these might be issues with how the building meshes are constructed.

![Screen Recording 2019-09-20 at 3 37 55 PM 2019-09-20 17_46_23](https://user-images.githubusercontent.com/51949/65365496-aa64f600-dbce-11e9-8ffa-efcf3a0b55b3.gif)

* Links to your logs are also helpful:

**Comment by atripathi-mb** [comment]
@iamcam Based on the gif, it looks like you have front face culling turned on. Could you check the material of the buildings if that is the case?

**Comment by iamcam** [comment]
@atripathi-mb I'm not sure how I would go about doing that, as this map is using the built-in light, dark, and color buildings styles (same issues with all 3 presets). The good news is that selecting a different materials seems to fix it.

**Comment by brnkhy** [comment]
@iamcam as you noted this is happening because of a strange (most likely Unity related) material bug and our default materials sometimes tend to act like this (because of some transparency flags). If you create an opaque material yourself and assign that, problem should be fixed.

**Comment by iamcam** [comment]
For those who find this at a later time, specifying a custom material (even if it's just a solid color) will fix this issue.
