### ISSUE TITLE
Example Scenes map textures not loading on iOS when another plugin exists in Assets - Red Question Mark appears instead

### ISSUE THREAD

**Issue by pa17** [mapbox/mapbox-unity-sdk#1472]
Hi there,

This is my first ticket so excuse me if something is missing. I am new to the Mapbox plugin for Unity and working on a location-based game for iOS. Currently, I am simply trying to get the example scenes (LocationBasedGame and AstronautGame) running on the device. Everything works well when using Unity Remote, but when I build the XCode project and then the app, the textures do not seem to load. I get a *mysterious* red question mark on every tile instead of the map.

Initially, the following error appeared:
"no 'ETag' header present in response for https://api.mapbox.com:443/styles/v1/mapbox/outdoors-v10/tiles/16/34323/22952@2x?events=true&access_token=MY_ACCESS_TOKEN"

I checked the api link and from my Mac I can access the image files, which is also why Unity Remote works. So far, I believed the problem stemmed from the iPhone either not having access to the Internet, but have since read that every app can make web requests (and tested it on WiFi and Mobile). Then, I suspected an error with loading the textures, and tried 'Use Compression' and 'Use Mip Map' in the AbstractMap class, both of which didn't help. Now I think the caching of the tiles might be an issue OR that iOS somehow cannot access the URL that the desktop computer doesn't seem to have a problem with. Could it be that iOS needs a different URL syntax to access image files? Final thing: The 'ETag' warning doesn't always occur; it doesn't work in either case

Any help would be appreciated :)

* Unity version: 2019.2.0f1
  * Scripting Runtime Version: 
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.0.0
* The platform you're building to: iOS

![IMG_0221](https://user-images.githubusercontent.com/13818089/65416142-7ae50200-ddf7-11e9-9202-106b3fb528e7.PNG)
![IMG_0222](https://user-images.githubusercontent.com/13818089/65416148-7d475c00-ddf7-11e9-80ba-e6d4363d481a.PNG)

**Comment by atripathi-mb** [comment]
@pa17 Looking at you screenshots, I see building footprints so your network connections seems to work. The issue seems to be iOS not handling image requests properly.

Could you paste a screenshot of the setting you used to build ?
Also, could you try using the .Net 4.x backend and see if that works?

**Comment by pa17** [comment]
Hey, thanks for your quick reply :) I have tried using the .Net 4.x backend - no luck... 

I hope this is what you asked for, otherwise just let me know! I haven't changed anything in the Build settings; this is the way Unity builds the XCode project.

![Screenshot 2019-09-23 at 23 10 40](https://user-images.githubusercontent.com/13818089/65463127-86681580-de57-11e9-9f4d-4b35746289a2.jpg)
![Screenshot 2019-09-23 at 23 10 54](https://user-images.githubusercontent.com/13818089/65463128-86681580-de57-11e9-988a-15fc7f6d9dad.jpg)
![Screenshot 2019-09-23 at 23 07 44](https://user-images.githubusercontent.com/13818089/65463130-8700ac00-de57-11e9-984e-42f7a13e0ab7.jpg)
![Screenshot 2019-09-23 at 23 10 07](https://user-images.githubusercontent.com/13818089/65463131-8700ac00-de57-11e9-9397-98eda7945f89.jpg)

**Comment by atripathi-mb** [comment]
@pa17 Sorry for not being clear. I meant `Player Settings` in Unity.

**Comment by pa17** [comment]
Here you go, supported URL schemes might be interesting?


![Screenshot 2019-09-24 at 09 16 02](https://user-images.githubusercontent.com/13818089/65489863-5a2ab400-deac-11e9-92bd-be3d14f29b45.jpg)
![Screenshot 2019-09-24 at 09 18 02](https://user-images.githubusercontent.com/13818089/65489865-5ac34a80-deac-11e9-9cc1-8bc630ac285a.jpg)

**Comment by pa17** [comment]
Hey there,
I just upgraded to the Mapbox v2.1.0 and the example scene now works properly. I will now try and integrate it into my existing project, and will close this if I don't run into the same issue. Thanks for the help!

**Comment by jbixon13** [comment]
@pa17 are there any steps to upgrading a project from 2.0.0 to 2.1.0 that are more involved than just downloading the new SDK and importing it? I'm new to Unity and want to avoid any unexpected issues.

**Comment by pa17** [comment]
Just make sure you delete any files that are you imported with 2.0.0. You can do it by clicking the unitypackage and seeing which files they are, then delete them and then import 2.1.0. For me, it was just deleted the Mapbox folder, as that was the only thing I imported.

**Comment by pa17** [comment]
Hello everyone,

I looked much more closely into this last night and found out that the reason for the red question marks was not related to Mapbox directly, but only occurs when I have another Plugin, specifically the  [Movesense Sensor Plugin](https://assetstore.unity.com/packages/tools/integration/movesense-sensor-plugin-118242) in my Assets folder. That being said, the issue persists **even when the plugin is not used at all in any scene**. 

Frustrating as it is, I really need the external sensor and the map to work together for my application. The only explanation I can muster is that, somehow, building the Movesense library messes with Mapbox's iOS image requests. I chose Unity so I can avoid Xcode as much as possible, but probably won't get around digging deeper. The only kind of relevant information I found on the Unity website:

_**WWW downloads are working fine in Unity Editor and on Android, but not on iOS**_
_The most common mistake is to assume that WWW downloads are always happening on a separate thread. On some platforms this might be true, but you should not take it for granted. Best way to track WWW status is either to use the yield statement or check status in Update method. You should not use busy while loops for that._

If anyone can answer these questions, I'd be extremely grateful:

1. Is it normal that different libraries affect each other that way?
2. Is it likely to be an issue with threading, i.e. the Movesense library somehow interrupts the image request, although it is not in use?
3. Is there anything I could try in the Xcode build process to disentangle the two libraries?

Thanks a lot!

**Comment by pa17** [comment]
I managed to fix it, finally! It took me so long, because I am new to Xcode and don't really understand the build process in detail yet. The bug was related to the sequence of linking the binaries with the Movesense libraries (libscan_ios.a, libmds.a, libMDSWrapper.a) with respect to the Mapbox libraries. Everything is working perfectly now after two days of struggle! 

Unity by default sets the sequence of the build phases in a way that links a Movesense library in between two Mapbox libraries etc. My process was to check the sequence in the working build (without Movesense plugin) and reorder it as such. The below sequence works, although it's probably not a good idea to have all the Movesense libraries at the very top, but that's the right path to the solution anyway.

![Screenshot 2019-09-25 at 11 29 42](https://user-images.githubusercontent.com/13818089/65588564-0ab9b600-df88-11e9-9c0e-0e7e7cede1b4.jpg)

and...

![programmermeme2](https://user-images.githubusercontent.com/13818089/65588579-10af9700-df88-11e9-83da-3afc539121ec.jpg)
