### ISSUE TITLE
Manually aligned map 

### ISSUE THREAD

**Issue by branko88** [mapbox/mapbox-unity-sdk#1473]
Hi, struggling to find relevant info; I'm looking at toggling the ability to rotate/pan the map. Where does mapbox manage the position/rotation in the manual alignment kit? I thought it might be the `ManualTouchCamera`, but nope.

**Comment by branko88** [comment]
After playing around, it is in fact dependent on `ManualTouchCamera`, if you compile without this script the panning/rotation are disabled. Although, it seems that after runtime it wont disable through a simple toggle; `enabled = false;`

**Comment by tpaslou** [comment]
So , in order to align the camera (or map) manually , what did you do ? Could you help me ?

**Comment by branko88** [comment]
If you want to align manually, use the `WorldAlignmentKitManual` prefab.
