### ISSUE TITLE
World Scale AR crashes on iOS if any tap on screen occurs

### ISSUE THREAD

**Issue by LAPhil66** [mapbox/mapbox-unity-sdk#1475]
Using Unity v2018.3.6f1
Testing on iPhone 8 with iOS 12.4.1
New Unity project having imported mapbox-unity-sdk_v2.1.0 from mapbox site
I added both location and camera usage descriptions.
Built using Xcode v11.0

The app starts up OK but any attempt to either select dismiss or log or indeed anywhere on the screen causes the app to crash.

No changes were made to the example scenes.
I tried to load the TabletopAR and WorldScaleAR-ManualAlignment scenes to but experienced the same results.

Any help would be very much appreciated as I need to get the example scenes working before making any changes so I know that any problems are no of my modifications.

**Comment by dhruvmodhapp** [comment]
You just need to check the light estimation checkbox in AR Root Gameobject > AR Controller Script.
