### ISSUE TITLE
Custom Line rendered - Berlin Wall

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1476]
Hey,

I would like to render the route where the former Berlin Wall was standing. How would I go about that? Do I create a custom layer in Mapbox Studio before that I can then somehow add to the map? 

Please direct me towards the necessary steps,

thanks a lot!

**Comment by smxthereisonlyone** [comment]
I found out how to do it - mapbox studio takes custom data entries that can be uploaded and then rendered into the map.

**Comment by brnkhy** [comment]
Yep! You can create a custom layer, define it as a line and you can use Line visualization (or Loft Modifier if you want to do some fancy an dmore complex stuff) inside the SDK.
