### ISSUE TITLE
Scale Up Tile instead of Showing Black Loading Tile

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1477]
Hey,

when zooming the old tiles get hidden and a black loading tile is shown. That is jarring to the eye. E.g. how can we just scale up the old tile when zooming in (so that it gets blurry) and not show the black loading tile? This is also how other map solutions work with texture tile based map zooming.

Best

**Comment by smxthereisonlyone** [comment]
Researching past issues, #1135 

The first question touches my question. 

I read the answer but it surely must be possible to have some kind of fix right now.

I mean, there is no great solution out there afaik for a simple map with a great api. Why are you guys not putting one dev for a month on this issue? The weird loading-tile-in-your-face-look must be deterring thousands of devs.

**Comment by brnkhy** [comment]
Hey @smxthereisonlyone 
Even though I agree this behaviour doesn't look the best, I'm afraid it isn't on timeline for now so it probably won't change any time soon. :( Sorry

**Comment by pandron** [comment]
Any updates on this much-desired fix?
