### ISSUE TITLE
How to zoom where clicked or touched?

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1479]
How would it be possible to zoom not always into center but wherever the mouse is hovering / the user is touching?

Thanks!

**Comment by StarKing777** [comment]
would be good to find this out

**Comment by kjyv** [comment]
How about: get the location of the touch in lat, long and with zoom simultaneously animate position?

**Comment by StarKing777** [comment]
> How about: get the location of the touch in lat, long and with zoom simultaneously animate position?

Hey bud how would you suggest going about animating the position?

Would you animate the camera position based on the users touch coordinates?

or any other ideas?

**Comment by brnkhy** [comment]
Sorry I missed this.
I think it's not trivial. I'll just drop some notes on top of my head, maybe I can give it a shot later myself again.
I'll use `zoomable map` system for now; we have a camera/world center latlng, then a mouse latlng.
When you zoom in/out, new tiles will be loaded (or not actually) and it should move all tiles (as zoomable map doesn't move map as far as I can remember) such that same latlng will be under mouse cursor again. 
First thing comes to my mind is, running mouse to get position again, substracting the old mouse latlng from that and using this difference vector to move the map. But I'm not sure if that'll be correct on perspective camera..... no wait it should right?
I'm sure I did this before (way before) at least once but it confuses me every time. (this and mouse-precise drag and move).

**Comment by brnkhy** [comment]
I gave it a shot, I think it works nice but I haven't really tested extensively; (It's just a single file change)
https://github.com/mapbox/mapbox-unity-sdk/tree/CursorZoom

You can see a short video of it here;
https://twitter.com/brnkhy/status/1283609693580132352?s=20

Hope this helps!
Closing this for now, feel free to reopen if you need though.
