### ISSUE TITLE
Don't render recycled tiles if they are not finished loading

### ISSUE THREAD

**Issue by NinjaDanz3r** [mapbox/mapbox-unity-sdk#148]
I have noted that if a tile is being recycled, it will be marked as recycled, re-used and placed in its new position before the new tile data has been fully loaded.
This is quite disorienting, since it appears at first glance that the wrong tile has been loaded only to later be replaced with the correct tile.

I currently use this workaround in the AbstractMap's update method:

`
foreach (Transform tileObject in transform)
{
tileObject.GetComponent<MeshRenderer>().enabled = (tileObject.GetComponent<UnityTile>().RasterDataState == TilePropertyState.Loaded);
}`
This snippet ensures that a tile has been fully loaded before it is displayed, but surely there must be a better solution?

**Comment by brnkhy** [comment]
I'm not sure but I think that behaviour was intended as system reacts to change right away and the whole process feels faster in general etc. I do agree it's a little confusing though, we probably can achieve some similar effect with more abstract data/activity I guess.

**Comment by NinjaDanz3r** [comment]
Perhaps setting the texture to a user-defined "Loading" texture until the tile has been loaded?

**Comment by brnkhy** [comment]
@NinjaDanz3r yes that totally would work, I was thinking about some abstract height data as well. I haven't checked the code yet thought so not sure if it'll be that easy. Will have a look as soon as possible

**Comment by david-rhodes** [comment]
@NinjaDanz3r This is actually a simple fix (and we can add the option to "clear old data on recycle"), but please note that it does create some extra performance overhead.

All you need to do is add `SetRasterData(null, false, false);` near the end of `Recycle()` of `UnityTile.cs`. This only clears the texture and does not reset the height. However, resetting the height is probably not worth the cost, given that you are likely to see seams with a flat tile anyway. However, if you need to reset the height to zero, add `ResetToFlatMesh(tile);` near the bottom of `OnRegistered` method of `TerrainFactory.cs`, right above `CreateTerrainHeight(tile);`.

**Comment by david-rhodes** [comment]
@NinjaDanz3r Did my suggestion help at all?

**Comment by NinjaDanz3r** [comment]
Haven't had time to try it out yet, but I will keep it in mind, thank you!

**Comment by david-rhodes** [comment]
In `develop` we have added an optional `loading` `Texture2d` to AbstractVisualizer. You can use this to avoid the recycled texture issue.
