### ISSUE TITLE
Animate UpdateMap

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1480]
Right now _mapManager.UpdateMap is changing the view instantly. How would it be possible to animate that?

**Comment by brnkhy** [comment]
@smxthereisonlyone I feel like `UpdateMap` should be instant but for example if you want to do a map moving animation or something, you can lerp between two latlng and pass new values to that function on each iteration. Same goes for the zoom I guess.
ope that helps!
