### ISSUE TITLE
ZoomableMap Scene + Directions

### ISSUE THREAD

**Issue by smxthereisonlyone** [mapbox/mapbox-unity-sdk#1481]
The Zoomable Map Scene and the Directions provided by DirectionsFactory don't work well together.

The Position and Scale of the directions mesh is not fitting while panning and zooming.

How could this be adapted?

Cheers

**Comment by smxthereisonlyone** [comment]
Okay, after trying a lot, I managed to do it with a custom line renderer implementation.

PM me if you wanna know more.

**Comment by brnkhy** [comment]
Hey @smxthereisonlyone!
Indeed `Directions` prefab was built for flat/urban type of maps. Even drag&drop breaks in Zoomable map demo if I remember correct.

Recently I did some improvements on this branch; https://github.com/mapbox/mapbox-unity-sdk/tree/directionsPrefabImprovements
I can't remember if it support elevation though, it might still be flat-only. You can find visuals on that branch here if you want to check it quickly; https://twitter.com/brnkhy/status/1178776042066067456?s=20

Thanks a lot for your feedback!

**Comment by adikhel** [comment]
I am facing the same problem. How was this solved @smxthereisonlyone ?

**Comment by baris-cincik** [comment]
Same problem here. Zooming/panning gets the directions out of sync. I would appreciate it if you could share your solution @smxthereisonlyone  :)
