### ISSUE TITLE
Vector2d.ToString() return longitude first

### ISSUE THREAD

**Issue by amit-nath30** [mapbox/mapbox-unity-sdk#1496]
Returning string with longitude first, is there any special reason for that? I am developing a project where I have to save map position when using vector2d.ToSting() for saving map center point and later loading using Conversions.StringToLatLon() to getting center lat/long Vector2d my map was behaving weirdly, That's when I figure out the problem

**Comment by brnkhy** [comment]
That's a really confusing issue with mapping in general. I cannot remember the exact reasons for it at the moment but (as an outsider myself) whole mapping community looks divided into two parts; latlng vs lnglat.
I believe we mostly use latlng in sdk normally but only use latlng on stuff refers to api data directly or something. Apologies for the confusion :( I'll try to see (and understand again) if we can change that easily but probably won't happen any time soon as it might also break a lot of stuff at this point.
