### ISSUE TITLE
Base vector layer polygon cut off

### ISSUE THREAD

**Issue by demirhere** [mapbox/mapbox-unity-sdk#1497]
I'm trying to understand how to work with vector layers so that they render appropriately. I'm not sure if this is a bug or not, but I've created this vector layer, an indoor map of a building. It displays accurately (even with extrusion) within the Mapbox Studio maps. However, when I render in Unity, half of the layer is cut off.

I have set my recipe to maxzoom to 20, with 0 simplification and 100 buffer. It looks fine when zoom level is set to 18 but at that level, I get some minor discrepancies, so I would rather be at 20. If I set the buffer to 0, I get even worse clipping and merging of polygons. 

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 2019.2.9f1
  * Scripting Backend: 4.0
  * Api Compatibility Level:  .NET 4.x
* Mapbox SDK version: 2.0.1
* The platform you're building to: Linux
* A description of what you're trying to do: I'm trying to load and render my vector layer.

![Screenshot from 2019-10-28 17-21-24](https://user-images.githubusercontent.com/40176533/67727693-9b304f80-f9a7-11e9-8226-b381bbb37740.png)

**Comment by abhishektrip** [comment]
@dogan-demir Could you post screenshots of the rendering in studio for us to understand what is the expected output?

Also, could you share the settings for the layer in Studio and in Unity for more details. 

My guess is these features are on tile boundaries and are somehow getting clipped.

**Comment by brnkhy** [comment]
@dogan-demir 
`It looks fine when zoom level is set to 18 but at that level, I get some minor discrepancies, so I would rather be at 20.`
I'm curious about this part. If I remember correct, z18 and z20 use exact same data. And I don't think your data would be detailed enough (looking at the screenshot) to reach floating point limit for the z18 tile size. Can you elaborate that a little more?
