### ISSUE TITLE
Point tileset not displaying in Mapbox SDK for Unity

### ISSUE THREAD

**Issue by armitage2817** [mapbox/mapbox-unity-sdk#1499]
I have a point tileset in Mapbox and can select the layer in Unity but the layer does not display and can't work out how to get it to display. Can anyone help with this?

Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by armitage2817** [comment]
I have a point tileset in Mapbox and can select the layer in Unity but the layer does not display and can't work out how to get it to display.  Can anyone help with this?

**Comment by abhishektrip** [comment]
> I have a point tileset in Mapbox and can select the layer in Unity but the layer does not display and can't work out how to get it to display. Can anyone help with this?

@armitage2817 Depending on how you setup a point layer, it needs a prefab or a GameObject Modifier to render an object as a representation for the point. 

Look at this example for more details https://docs.mapbox.com/unity/maps/examples/poi-placement/

**Comment by armitage2817** [comment]
Hi.  Thanks for this but its not quite the same issue.  I've worked out how
to use the POIs.  There's a great video about how to do that here

https://www.mapbox.com/videos/how-to/create-a-custom-scene-with-pois-using-maps-sdk-for-unity-3d/


My problem is with visualising my own point data tileset which i've
created in Mapbox.  I'm still trying to figure that out.

**Comment by armitage2817** [comment]
The tileset and style IDs are entered into Unity like this and the name of the tileset is in the list of available layers - but it doesn't display in the map.  The other standard Mapbox layers show up ok.

![image](https://user-images.githubusercontent.com/57393557/68924474-39326100-0781-11ea-83c7-75e44370dea2.png)

**Comment by brnkhy** [comment]
@armitage2817 data might be pulled and processed fine from what I see in that screenshot. But if you don't have anything under game object modifiers list, as @atripathi-mb suggested, you won't get any 3d representations out of it. Prefab modifier for example, puts an object on each point.

**Comment by armitage2817** [comment]
Hi @brnkhy . But I dont want any 3D features for my point.  I just want them to show as points on a flat map.  I'm trying to follow the instructions here where they create a test dataset with two red points in Mapbox and then copy the tileset link for use in Unity as shown in the screen shots below. 
 Unfortunately the instructions dont cover how to use the tileset link in Unity to get the points to display with the Mapbox symbols.  The actual dataset that I want to display has many different coloured points and I want the Mapbox colours to be reproduced in Unity.

https://www.yudiz.com/add-custom-dataset-points-to-mapbox-map-and-integrate-them-in-unity/

The tileset in Mapbox (2 red points)

![image](https://user-images.githubusercontent.com/57393557/69129204-39e33400-0aae-11ea-9592-bfae24fdbc77.png)

The same tileset displayed in Unity.

![image](https://user-images.githubusercontent.com/57393557/69129101-06080e80-0aae-11ea-8074-eef43bb9a4e9.png)

Its a bit frustrating that I cant get any of my own Mapbox data to display

**Comment by brnkhy** [comment]
@armitage2817 ah now I understand. You don't want to consume that data as vector but in the imagery. What you should do is to create a style from that tileset, again through mapbox studio. So dataset=>tileset=>style. then you can use the style url inside mapbox unity sdk, under image section (custom image) and pull that imagery.

**Comment by brnkhy** [comment]
I hope I was able to help, closing this for now. please feel free to reopen if necessary.
