### ISSUE TITLE
Mesh filters partially match certain keys

### ISSUE THREAD

**Issue by stevenschobert** [mapbox/mapbox-unity-sdk#150]
Hey all! Opening up this issue in a follow-up to #149.

## Issue

Adding an "exclude" filter to a vector layer visualizer will occasionally filter out results that only match the target filter.

This is caused by `TypeFilter` using `string.Contains` for key comparison: [TypeFilter.cs:L17-L18](https://github.com/mapbox/mapbox-unity-sdk/blob/db3c21fe61de724f80d2dacb5dd143695daab64e/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Filters/TypeFilter.cs#L17-L18)

#### Example

Adding a filter for `building:part` will remove any `building` types. Similar issues will occur for any of the colon-seperated types.

**Comment by brnkhy** [comment]
Hey @stevenschobert , PR is here; https://github.com/mapbox/mapbox-unity-sdk/pull/173 
I did just the simplest thing to adress this, we'll do a better fix for this with inspector/editor changes in the future.

**Comment by stevenschobert** [comment]
@brnkhy Awesome! 🎉 

I'll go ahead and close out this issue then!
