### ISSUE TITLE
Continuous Map

### ISSUE THREAD

**Issue by AzeExMachina** [mapbox/mapbox-unity-sdk#1500]
Hi everyone,
I'd like to know if there's a way to render my map as continuous and have the same behaviour I can experience in mapbox studio, where I can zoom, pan and my map is locked to north/south pole and will continue to repeat when panning east or west.
![image](https://user-images.githubusercontent.com/28900356/68215068-e4ebec00-ffde-11e9-9f85-faf1494da0d1.png)

Thanks in advance!

* Unity version: 2018.1.5f
  * Scripting Runtime Version: .NET 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: 2.0.0
* The platform you're building to: Windows/Linux

**Comment by abhishektrip** [comment]
@AzeExMachina Repeated scrolling is not supported out of the box since the implementation is generally application-specific. 

You can use a custome Tile Provider to have repeating tile extent or use camera tricks to achieve this behavior.

**Comment by brnkhy** [comment]
@AzeExMachina you probably already know it but just in case, closest thing to this is the `zoomable map` demo scene in the sdk. It doesn't tile and camera isn't locked. Those are the main two things different from what you asked I guess.

**Comment by jordy-isaac** [comment]
@AzeExMachina If you use `Range Around Transform` on the camera and then place some logic to translate it you can create a scrolling map. There's a video tutorial on how to do it on the [docs page for POIs](https://docs.mapbox.com/unity/maps/examples/poi-placement/#create-a-custom-scene-with-pois). If you're just interested in that part, it's at about the 2:25 mark.

**Comment by RomanAtBrief** [comment]
Hi @jordy-isaac  , @brnkhy and @abhishektrip ,

I have the same question. Unfortunately non of the answers really help or provide any solution.
Most of questions of such sort on GitHub have been closed without answering the question?!

I spent quite some time searching git and documentation, but unfortunately documentation needs a lot of work and all tutorials are basic.

Can you please advise how to create continuous map, like in original question? Range Around transform doesn't work as a solution as it conflicts with Quadtree Pan script, and it adds tile on north and south ! WHY?

If I have to make my own tile provider ok, it should be straightforward, but for example, after curating a new class I can not attach it into custom field?

Please advise....

`using System.Collections.Generic;
using Mapbox.Map;
using Mapbox.Unity.DataContainers;
using Mapbox.Unity.Map.TileProviders;
using UnityEngine;


public class ContinuousTileProvider : AbstractTileProvider
{
    public override bool Cleanup(UnwrappedTileId tile)
    {
        throw new System.NotImplementedException();
    }

    public override void OnInitialized()
    {
        throw new System.NotImplementedException();
    }

    public override void UpdateTileExtent()
    {
        throw new System.NotImplementedException();
    }
}`

**Comment by ashokdube** [comment]
Good job sir🚩🌷🚩

Thanks
