### ISSUE TITLE
Can't find AR Example scene in SDK v2.1.1

### ISSUE THREAD

**Issue by dhruvmodhapp** [mapbox/mapbox-unity-sdk#1504]
Hello,
I can't find the AR Example scene in the latest SDK v2.1.1. Does anybody know where is these AR examples scene?
@jordy-isaac Please help.

**Comment by abhishektrip** [comment]
@dhruvmodhapp Thanks for flagging this. The package on our website somehow got corrupted. If you re-download you will see the AR scenes in their usual place.
