### ISSUE TITLE
Map tiles not load

### ISSUE THREAD

**Issue by Miky91** [mapbox/mapbox-unity-sdk#1505]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.1.14f1
  * Scripting Runtime Version: .NET 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: 25
* Mapbox SDK version: v2.1.1
* The platform you're building to: Android
* A description of what you're trying to do:

I am developing a Location-based game but the map doesn't load the tiles, and always looks like in the photo:

![error](https://user-images.githubusercontent.com/9828723/68584655-814f3c00-0480-11ea-8848-fef869249665.PNG)

The Unity Tile component has the correct tile image in the "raster data" variable but is not assigned to the material "TerrainMaterial".
Nevertheless I have debugged the code from "UnityTile.cs" and it is assigned the raster image to the material but when the process finish "loadinggrid" texture continues in the material.
Also, the raster data state is loaded.

![imagen](https://user-images.githubusercontent.com/9828723/68585025-5dd8c100-0481-11ea-9c63-5b15c8d0a805.png)

![imagen](https://user-images.githubusercontent.com/9828723/68585048-6af5b000-0481-11ea-953d-7caffa0eae69.png)

How can I fix this problem?

Thank you a lot!

Miky

* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by abhishektrip** [comment]
@Miky91 
Could you provide more details on how to reproduce the issue? The information provided in the ticket is not sufficient to fully understand the issue. 

Could you provide screenshots of your map settings?

**Comment by Miky91** [comment]
@atripathi-mb of course!
Also, I'm using the Lightweight RP v5.7.2
These are my map settings:
![imagen](https://user-images.githubusercontent.com/9828723/68934905-e0ba8e00-0797-11ea-8440-95e3293551ab.png)
![imagen](https://user-images.githubusercontent.com/9828723/68934989-10699600-0798-11ea-9913-7756ad3d2535.png)

**Comment by brnkhy** [comment]
@Miky91 I believe this is because you're using lightweight render pipeline and its materials. 
SDK uses line below to set textures;
`MeshRenderer.sharedMaterial.mainTexture = _rasterData;`
but I believe `mainTexture` doesn't work for lightweight render pipeline and it should be changed to something like;
`MeshRenderer.sharedMaterial.SetTexture("_BaseTexture", _rasterData);`
I'm not sure about the texture name `_BaseTexture` but you can check it from material debug view in the inspector context menu.

**Comment by brnkhy** [comment]
I believe that should fix the problem so I'll close the ticket for now but please feel free to reopen it if it doesn't help 🙏

**Comment by Miky91** [comment]
@brnkhy  I tried using `MeshRenderer.sharedMaterial.SetTexture` but the problem continues.
I don't think this would be the problem because I have the same project in Unity 2018 with LWRP and it works fine

**Comment by Miky91** [comment]
@brnkhy any news about this issue? I didn't re-open this bug because I'm not a contributor...
