### ISSUE TITLE
Creating features in runtime

### ISSUE THREAD

**Issue by RobvT** [mapbox/mapbox-unity-sdk#1507]
Hi,

First of all thank you for this great tool with mapbox and unity SDK. 

Currently i am trying to add my own geojson featurecollections with REST-API calls from my own server to the mapbox map. I would like to use this SDK capabilities of visualizing the lines/polygons/etc. All the properties of the features (modifiers, etc.) will have to be set during runtime. What is the best way to add the geofeatures to the vectordata? 
Would it for example be smart to combine my own rest api response to the processtileJsondata method in the tilejsondata.cs? Or is it smarter to process the jsondata myself and add the feature layers to the vectorlayer.cs directly?

Thanks in advance.

**Comment by jordy-isaac** [comment]
@RobvT You can add them to your layer at runtime. Here are api docs: https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.ILayer.html

**Comment by RobvT** [comment]
@jordy-isaac  Thanks for the reply. I have been looking into it again for quite a few hours, but i can't find the proper way to add custom features at runtime. I assume that i need to use the extend of the active unitytiles to request my own features to my own api within that extend. Then add those features to the corresponding vectordata. Am i assuming this right? Could you perhaps give a small example of how to do it?

**Comment by FabienTschirhart** [comment]
Hello,

Somehow, am trying the same thing as @RobvT ;
I'd like to access the features list to modify them, and first of all, to enable or disable them at runtime ;
I manage to get the VectorData with ; 
`_map.GetComponent<AbstractMap>().VectorData`

But I do not understand how to reach the different existing features from this point, and to change their state by code. Using GetAllFeaturesSubLayers didn't get my anywhere close (well, i probably missed something).
And the IsLayerActive (from ILayer) ; is always true (and am not quite sure what it is pointing at).

A hand would be warmly welcome !

Thanks in advance !

**Comment by FabienTschirhart** [comment]
Found it, if anyone else is trying :

```

 public AbstractMap _map;

 _map.GetComponent<AbstractMap>().VectorData.FindFeatureSubLayerWithName("NameOfYourLayer").SetActive(true);


```

**Comment by brnkhy** [comment]
@RobvT are you still having the issue or is this good to close?
