### ISSUE TITLE
Missing language option for reverse geocoding resource

### ISSUE THREAD

**Issue by dblatner** [mapbox/mapbox-unity-sdk#1510]
Actually the language option is missing / not implemented in ReverseGeocodeResource.cs and GeocodeResource.cs , so I already implemented it and it works.

If you tell me how to create a branch and a pull request, I am happy to contribute my code to the community.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.1.x
* Mapbox SDK version: 2.1.1
* The platform you're building to: Android/iOS
* A description of what you're trying to do: get reverse geocoded results in the target language (see Mapbox reverse geocoding API)
* Steps to recreate the bug if appropriate: just try geocoding with Mapbox Unity SDK, it gives you Cyrillic, Chinese or other types of characters depending on the location you are querying.

**Comment by brnkhy** [comment]
Hey @dblatner!
You can branch from current dev branch head if that's what you're asking. Or if you're not too familiar with Git, you can post changes here for me to quickly check and see if I can apply them asap.
Thanks!
