### ISSUE TITLE
How to reference lat/long of a prefab from tileset?

### ISSUE THREAD

**Issue by jason-epel** [mapbox/mapbox-unity-sdk#1512]
I have a series of prefabs linked to a point tileset. I have collisions set up for when the player runs into the prefabs. How do I reference the lat/long of the point when the player collides?

**Comment by brnkhy** [comment]
@jason-epel so you want to get a prefab specific data on collision? 
You probably would want to store that data on prefab (in a script) and get it from that OR create a manager/controller class wich keeps a dictionar of gameobjects/latlng and check that on collision.
