### ISSUE TITLE
Estimated time for mapbox reflect change in OpenStreetMap

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1516]
Hello, ive edited some buildings and parks in my city LLeida.

So, when can i expect these changes take place in my game ? Any estimated time between a change in OSM and this change appeaars in Mapbox Maps ?

Thanks

**Comment by brnkhy** [comment]
@ejgutierrez74 If you added them directly to OSM, it might take a while I guess because they are all checked by hand for security :(
@jordy-isaac that's correct right?

for a faster solution, you can add them into a custom dataset and use that for now maybe?

**Comment by ejgutierrez74** [comment]
Well i want to be a good person and share with community... ;)

By the way how is going to have some offline maps in Unity Version ? Would be huge improvement, using less connection to mapbox, less bandwith and ability to play without internet connection.... Also less gigabytes wasted...

**Comment by brnkhy** [comment]
@ejgutierrez74 I'm afraid we still don't have offline maps but I'll probably be looking into that soon. Will update offline maps ticket if anything comes up! :)
