### ISSUE TITLE
il2cpp.exe did not run properly!

### ISSUE THREAD

**Issue by iplay3d** [mapbox/mapbox-unity-sdk#1518]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.2
  * Scripting Runtime Version: 
  * Scripting Backend: ilcpp
  * Api Compatibility Level: 4.0x
* Mapbox SDK version: 2.1.1
* The platform you're building to: android
* A description of what you're trying to do: on mapbox 2.0.0 build successful but crash game on device, then i update mapbox to latest now can not build and show this error
1)
`Failed running C:\Program Files\Unity 2019\Unity\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="D:\UnityClientProjects\sja\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="D:\UnityClientProjects\sja\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity 2019/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity 2019/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Users/Hoti-Tech/Downloads/android-ndk-r16b" --profiler-report --map-file-parser="C:/Program Files/Unity 2019/Unity/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=D:/UnityClientProjects/sja/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=D:/UnityClientProjects/sja/Temp/StagingArea/Il2Cpp/il2cppOutput 

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: D:\UnityClientProjects\sja\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a
	Cache directory: D:\UnityClientProjects\sja\Library\il2cpp_android_armeabi-v7a\il2cpp_cache
ObjectFiles: 336 of which compiled: 318
	Time Compile: 58989 milliseconds Il2CppAttributes.cpp
	Time Compile: 46971 milliseconds Il2CppInvokerTable.cpp
	Time Compile: 26484 milliseconds Assembly-CSharp2.cpp
	Time Compile: 26432 milliseconds Assembly-CSharp3.cpp
	Time Compile: 26014 milliseconds Assembly-CSharp5.cpp
	Time Compile: 25582 milliseconds Assembly-CSharp4.cpp
	Time Compile: 25431 milliseconds Il2CppTypeDefinitions.c
	Time Compile: 25070 milliseconds Unity.TextMeshPro1.cpp
	Time Compile: 23377 milliseconds System.Xml12.cpp
	Time Compile: 22387 milliseconds Unity.TextMeshPro2.cpp
Total compilation time: 675432 milliseconds.
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\Hoti-Tech\AppData\Local\Temp\tmp100E.tmp" -o "D:\UnityClientProjects\sja\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_F3BD458338F3EEFEFC49251FF43DB6DC\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\platforms\android-16\arch-arm" -gcc-toolchain "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a" -lgnustl_static -latomic -llog -rdynamic -fuse-ld=gold.exe

D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:13421: error: undefined reference to 'GetBlendShapesInfo'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:13421: error: undefined reference to 'GetBlendShapesInfo'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14091: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14091: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14199: error: undefined reference to 'IsARKitSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14199: error: undefined reference to 'IsARKitSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14317: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14317: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18167: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18256: error: undefined reference to 'PauseSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18266: error: undefined reference to 'HitTest'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18279: error: undefined reference to 'GetLastHitTestResult'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18186: error: undefined reference to 'StartSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18035: error: undefined reference to 'unity_CreateNativeARSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18066: error: undefined reference to 'session_SetSessionCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18088: error: undefined reference to 'session_SetPlaneAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18110: error: undefined reference to 'session_SetUserAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18132: error: undefined reference to 'session_SetFaceAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18148: error: undefined reference to 'StartWorldTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18167: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18186: error: undefined reference to 'StartSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18205: error: undefined reference to 'StartSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18224: error: undefined reference to 'StartFaceTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18243: error: undefined reference to 'StartFaceTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18256: error: undefined reference to 'PauseSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18266: error: undefined reference to 'HitTest'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18279: error: undefined reference to 'GetLastHitTestResult'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18298: error: undefined reference to 'GetVideoTextureHandles'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18309: error: undefined reference to 'GetAmbientIntensity'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18320: error: undefined reference to 'GetTrackingQuality'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18331: error: undefined reference to 'GetARPointCloud'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18342: error: undefined reference to 'SetCameraNearFar'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18352: error: undefined reference to 'CapturePixelData'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18362: error: undefined reference to 'SessionAddUserAnchor'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18377: error: undefined reference to 'SessionRemoveUserAnchor'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18035: error: undefined reference to 'unity_CreateNativeARSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18342: error: undefined reference to 'SetCameraNearFar'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18352: error: undefined reference to 'CapturePixelData'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18331: error: undefined reference to 'GetARPointCloud'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18148: error: undefined reference to 'StartWorldTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18205: error: undefined reference to 'StartSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18243: error: undefined reference to 'StartFaceTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18224: error: undefined reference to 'StartFaceTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18298: error: undefined reference to 'GetVideoTextureHandles'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18309: error: undefined reference to 'GetAmbientIntensity'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18320: error: undefined reference to 'GetTrackingQuality'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18362: error: undefined reference to 'SessionAddUserAnchor'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18377: error: undefined reference to 'SessionRemoveUserAnchor'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14091: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14199: error: undefined reference to 'IsARKitSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14317: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Program.DoRun(String[] args)
   at il2cpp.Program.Run(String[] args)
   at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\Hoti-Tech\AppData\Local\Temp\tmp100E.tmp" -o "D:\UnityClientProjects\sja\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_F3BD458338F3EEFEFC49251FF43DB6DC\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id --sysroot "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\platforms\android-16\arch-arm" -gcc-toolchain "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" -target armv7-none-linux-androideabi -Wl,--wrap,sigaction -L "C:\Users\Hoti-Tech\Downloads\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a" -lgnustl_static -latomic -llog -rdynamic -fuse-ld=gold.exe

D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:13421: error: undefined reference to 'GetBlendShapesInfo'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:13421: error: undefined reference to 'GetBlendShapesInfo'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14091: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14091: error: undefined reference to 'IsARKitFaceTrackingConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14199: error: undefined reference to 'IsARKitSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14199: error: undefined reference to 'IsARKitSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14317: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:14317: error: undefined reference to 'IsARKitWorldTrackingSessionConfigurationSupported'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18167: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18256: error: undefined reference to 'PauseSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18266: error: undefined reference to 'HitTest'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18279: error: undefined reference to 'GetLastHitTestResult'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18186: error: undefined reference to 'StartSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18035: error: undefined reference to 'unity_CreateNativeARSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18066: error: undefined reference to 'session_SetSessionCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18088: error: undefined reference to 'session_SetPlaneAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18110: error: undefined reference to 'session_SetUserAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18132: error: undefined reference to 'session_SetFaceAnchorCallbacks'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18148: error: undefined reference to 'StartWorldTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18167: error: undefined reference to 'StartWorldTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18186: error: undefined reference to 'StartSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18205: error: undefined reference to 'StartSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18224: error: undefined reference to 'StartFaceTrackingSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18243: error: undefined reference to 'StartFaceTrackingSessionWithOptions'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18256: error: undefined reference to 'PauseSession'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18266: error: undefined reference to 'HitTest'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18279: error: undefined reference to 'GetLastHitTestResult'
D:\UnityClientProjects\sja\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp24.cpp:18298: error: undefined reference to 'GetVideoTextureHandles'
D:\UnityCl<message truncated>`

2)
`Exception: C:\Program Files\Unity 2019\Unity\Editor\Data\il2cpp/build/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:71)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:503)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (System.String inputDirectory, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:484)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:334)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:63)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5557b445b4634c46b2ec8376c040bd34>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5557b445b4634c46b2ec8376c040bd34>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <5557b445b4634c46b2ec8376c040bd34>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <5557b445b4634c46b2ec8376c040bd34>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:281)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@iplay3d I don't know much about mobile builds myself but are you sure this is mapbox sdk related? I mean are you able to create builds without mapbox unity sdk included for example? Couldn't see anything related to mapbox in the log :(

**Comment by ahmedaniss25** [comment]
problem fixed here : https://youtu.be/P_-vOfad_yc
