### ISSUE TITLE
How to add data to search in Unity 3d (Search ForwardGeocode)

### ISSUE THREAD

**Issue by hiangsui** [mapbox/mapbox-unity-sdk#1519]
hello i have a question. i'm working mapbox in unity 3d and i'm trying to add a data (from my create in Geojson dataset) to search in unity. (Search ForwardGeocode Location) but i'm not sure how.

i read document but doucument have many too much and my english not very well.

right now i think i have to upgrade account or contact anyone ?

i have to upgrade in the future but right now i just try everything to explore for understand.

thank you.

Edit : i create image for explain. you can see.

![AskMapbox](https://user-images.githubusercontent.com/52460048/71794971-81ca1480-3076-11ea-85eb-3fe89176b3fc.jpg)

**Comment by brnkhy** [comment]
@hiangsui If I understand it correct, it's not possible really. You can't add metadata to existing mapbox features. You can define new dataset/layers using mapbox studio though.

edit: closed this for now but please feel free to reopen if you have any followup questions.
