### ISSUE TITLE
How to get vector3 position in Unity3D from latitudeLongitude and altitude ?

### ISSUE THREAD

**Issue by IfnoLee** [mapbox/mapbox-unity-sdk#1523]
GeoToWorldPosition method seem to have not altitude parameter.
How get accuracy Exaggeration factor from real elevation?
![image](https://user-images.githubusercontent.com/38685433/72313896-ebc26980-36c7-11ea-8f9d-5eebf5b251c0.png)

* Unity version: 2019.2.6f1
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET4.X
* Mapbox SDK version: v2.1.1

**Comment by IfnoLee** [comment]
> GeoToWorldPosition method seem to have not altitude parameter.
> How get accuracy Exaggeration factor from real elevation?
> ![image](https://user-images.githubusercontent.com/38685433/72313896-ebc26980-36c7-11ea-8f9d-5eebf5b251c0.png)
> 
> * Unity version: 2019.2.6f1
>   
>   * Scripting Backend: IL2CPP
>   * Api Compatibility Level: .NET4.X
> * Mapbox SDK version: v2.1.1

I will try this.  https://github.com/mapbox/mapbox-unity-sdk/issues/1447

**Comment by brnkhy** [comment]
@IfnoLee AbstractMap class has
`public virtual Vector3 GeoToWorldPosition(Vector2d latitudeLongitude, bool queryHeight = true)`
I think that should help?

**Comment by wisdomware** [comment]
Is there any plan to add this feature as IfnoLee requested? I am also looking for a way to add multiple 3d models with Lat, Long, and Altitude with each model has a different elevation to my tabletop AR.

**Comment by brnkhy** [comment]
@wisdomware the method in abstract map already takes a parameter to enable elevation. Isn't that what you're looking for?

**Comment by IfnoLee** [comment]
@brnkhy  Thank you ! 
I know this method 
`public virtual Vector3 GeoToWorldPosition(Vector2d latitudeLongitude, bool queryHeight = true)) `
,but I would get a method that get vector3 from latitudeLongitude and any altitude ,like this
` public virtual Vector3 GeoToWorldPosition(Vector2d latitudeLongitude, double altitude)`
For example，I would show a aircraft in 3D map, and altitude  of the aircraft is always vary, or place some object at certain altitude.
I hope I had explained it clearly.

**Comment by brnkhy** [comment]
@IfnoLee ah so you're looking for a method to convert altitude into unity space elevation 🤔 
actually that would be useful because conversions are haaard. 
I believe `posY = altitude * map.WorldRelativeScale;` should return the correct value in this case though. But I like the idea, I'll try to remember and try this out 👍 
closing this for now but let me know if you have any follow up questions :)

**Comment by bytemaus** [comment]
@brnkhy hey I have a problem using your mentioned calculation. i try to visualize a flight, but it doesn't matter if I use 
`posY = data.Alt * map.WorldRelativeScale` or `map.MapVisualizer.ActiveTiles.TryGetValue(Conversions.LatitudeLongitudeToTileId(data.Lat, data.Lon, (int)map.Zoom), out var tile);`

The planeobject is always way above the ground. My collected GPS data is in meter above normal 0. So if the ground is at 300m and the planes position is on 300m too, the object should be displayed on the ground but it does not work..
Do you have any idea how I can convert my real world altitude into unitys y-coordinate?
