### ISSUE TITLE
There is no Map Editor option found under MapBox bar.

### ISSUE THREAD

**Issue by TINGWEIJING** [mapbox/mapbox-unity-sdk#1525]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.4.15f1
* Mapbox SDK version: v2.1.1
* A description of what you're trying to do: 
Try to follow MapBox tutorial from here https://youtu.be/sK3lr3Yh6XI?list=PL86WBCjNmqh6gMUI3cKW-vZQBWt_-hsqp&t=417
Found out I don't have Map Editor option after I submitted the access token.

![Untitled](https://user-images.githubusercontent.com/55592054/72604867-af586d00-3956-11ea-951d-e52b9f5003df.png)

**Comment by roura-12** [comment]
so you can't find map editor in the location provider? there is not a relationship between them; verify if it exists in the astronaut project

**Comment by brnkhy** [comment]
@TINGWEIJING I'm afraid that's an outdated tutorial and we deprecated map editor (node editor) some time ago. you can control everything through abstract map inspector now. sorry for the confusion.

**Comment by hilkojj** [comment]
The node editor is still mentioned in [the documentation](https://docs.mapbox.com/unity/maps/), which is confusing.
