### ISSUE TITLE
Map Features modification at run time

### ISSUE THREAD

**Issue by roura-12** [mapbox/mapbox-unity-sdk#1526]
Hi guys, 
do you have any idea how can I develop an application that allows the user to modify the map features by spawing objects on top for example without using the related mesh and game object modifiers out of Unity 3D (a separate executable application)
Thanks a lot 
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.4.32f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.1
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 
@brnkhy @jordy-isaac

**Comment by brnkhy** [comment]
@roura-12 you can look into mesh modifier stacks and/or vector factory for even more contol over vector processing. A feature is basically a list of vertices with some extra metadata and a custom vector factory would allow you to construct them any way you want.
