### ISSUE TITLE
Saving direction data in a file 

### ISSUE THREAD

**Issue by Rana-Yehya** [mapbox/mapbox-unity-sdk#1527]
I want the direction between my GPS position and my destination to be saved in file and then get accessed later
I have searched for days to find the data responsible for plotting the line between the source and the destination 
Any ideas?

**Comment by brnkhy** [comment]
I think you're looking for `void HandleDirectionsResponse(DirectionsResponse response)` under `DirectionsFactory.cs`?

**Comment by Rana-Yehya** [comment]
Thanks for the fast response @brnkhy If I am thinking right, this variable I am looking for is 'dat' variable. Just to elaborate you I want these dotted line to be saved in a file to be used later
![Screenshot_20200121_170831](https://user-images.githubusercontent.com/51721428/72816468-db366400-3c70-11ea-880c-62f16a970baa.jpg)

**Comment by Rana-Yehya** [comment]
After days of trying, I found the variable I was looking for. It is 'dat' in the method mentioned by @brnkhy and it is responsible for turn-by-turn directions between way points, and it updates regularly every what 'UpdateFrequency' set to. And if I am right, 'dat' stores the distance between the one of the way points and the next turn. If I am wrong please someone enlighten me.

**Comment by brnkhy** [comment]
@Rana-Yehya yes, directons query result should have a distance value as well. You can check raw response in this page as well; https://docs.mapbox.com/help/tutorials/getting-started-directions-api/

**Comment by brnkhy** [comment]
I hope I was able to help, closing this for now. please feel free to reopen if necessary.
