### ISSUE TITLE
How to apply a material to all layers except "park"

### ISSUE THREAD

**Issue by mym2o** [mapbox/mapbox-unity-sdk#1528]
_Note: If this is a bug or support ticket, please provide the following information:_ support
* Unity version: 2019.2.17f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.0.0
* The platform you're building to: Android Mobile
* A description of what you're trying to do: I'm trying to apply a material to land which is not a park
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 

Hello,
I'm able to apply a green material to "park" layer and to spawn trees on it, but I can't apply a different material to the rest of the tiles.
Is there a way to say (for example): "I want a material A to all tiles except to park"?

Thanks in advance

**Comment by jordy-isaac** [comment]
@mym2o You can apply a material to any layer that you have set up in your `Map Features` section of the `AbstractMap.cs` script. It's in the `Texturing` section. I would check out some other examples in the SDK to see how we've done it. Here's a link to the docs for the city simulator example which has a water layer with a material: https://docs.mapbox.com/unity/maps/examples/city-simulator/#add-a-custom-feature

**Comment by mym2o** [comment]
@jordy-isaac but water and park have different data layers.
Instead, I'd like to assign a material X to data layer "landuse" with filter class which contains "park" and a material Y to data layer "landuse" with filter class which not contains "park".
This means that I have to list all the landuse layer classes in Filters except park and "Combiner Type = Any", is it right?

**Comment by brnkhy** [comment]
`This means that I have to list all the landuse layer classes in Filters except park and "Combiner Type = Any", is it right?`
@mym2o I think combiner type `none` should give you `!contains`.
<img width="372" alt="Screen Shot 2020-01-29 at 4 02 17 PM" src="https://user-images.githubusercontent.com/1465390/73358942-c3825f80-42b0-11ea-8e01-3a9bef319f0f.png">
It means, there's one filter (landuse == park) and I want to render features that fit none of those filters.

**Comment by mym2o** [comment]
@brnkhy a post in your website shows me the way:
`Data Layer: contour`
`ele Is Equal 0`
I didn't use `contour` during the map creation in mapbox studio. I didn't understand the real meaning of `landuse` until now.

Thanks
