### ISSUE TITLE
Autocomplete functionality on search bar - Zoomeable Map

### ISSUE THREAD

**Issue by isassaba** [mapbox/mapbox-unity-sdk#1529]
Hi I'm trying to build a an app with the zoomeable map functionality and I need to know if there is any way to get the autocomplete functionality on the search input ? Investigating for a while I found that ForwardGeocodeResource has the property of autcomplete, but don't know how to use that or display the results of the query.

**Comment by jordy-isaac** [comment]
@isassaba Geocoding in the Unity SDK is s C# wrapper around the Mapbox Search API. It has an optional param that you'd need to add to your request going out from Unity. Then you'd need to display the results on your UI canvas. 

Here's a link to the [playground on the web](https://docs.mapbox.com/search-playground/#{%22url%22:%22%22,%22index%22:%22mapbox.places%22,%22approx%22:true,%22staging%22:false,%22onCountry%22:true,%22onType%22:true,%22onProximity%22:true,%22onBBOX%22:true,%22onLimit%22:true,%22onLanguage%22:true,%22countries%22:[],%22proximity%22:%22%22,%22typeToggle%22:{%22country%22:false,%22region%22:false,%22district%22:false,%22postcode%22:false,%22locality%22:false,%22place%22:false,%22neighborhood%22:false,%22address%22:false,%22poi%22:false},%22types%22:[],%22bbox%22:%22%22,%22limit%22:%22%22,%22autocomplete%22:true,%22languages%22:[],%22languageStrict%22:false,%22onDebug%22:false,%22selectedLayer%22:%22%22,%22debugClick%22:{},%22localsearch%22:false,%22query%22:%22%22}), and there's also a playground scene in the SDK. Here's the documentation for the [autocomplete param](https://docs.mapbox.com/api/search/#forward-geocoding).

**Comment by isassaba** [comment]
Hi Jordy, thanks for the response. Yes, i did what you are saying and it works correctly, but now the problem is that some addresses don't get a result and also don't set the map location correctly. Mostly seems to happen with adresses with numbers.

ej. Alem 556, Tandil, Buenos Aires, Argentina.

**Comment by brnkhy** [comment]
@isassaba not exactly autocomplete but you can check what I did for one of my personal projects here; http://barankahyaoglu.com/map/
it searches for locations, pulls back results and then you click to move location.

**Comment by BabakRaeisi** [comment]
> Hi Jordy, thanks for the response. Yes, i did what you are saying and it works correctly, but now the problem is that some addresses don't get a result and also don't set the map location correctly. Mostly seems to happen with adresses with numbers.
> 
> ej. Alem 556, Tandil, Buenos Aires, Argentina.



> Hi Jordy, thanks for the response. Yes, i did what you are saying and it works correctly, but now the problem is that some addresses don't get a result and also don't set the map location correctly. Mostly seems to happen with adresses with numbers.
> 
> ej. Alem 556, Tandil, Buenos Aires, Argentina.

did you have any luck fix this problem ?I've been struggling with it for days 
I want to show the closest locations when user starts searching . I'm not able to understand the documentation
