### ISSUE TITLE
Get FeatureID from Dataset

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1531]
Hi, 
I'm still working on a feature that lets me delete features from a dataset -> tileset.

I managed to parse the feature id via `_selectedFeature.Feature.Data.Id`
 but the result is what I believe the internal id (index) within the app and not the id within the data base. 

`_selectedFeature.Feature.Data.Id` returns 98 (as in 98/378) instead of dd20b25ce8db044492b01e14cdc257ba as listed in Mapbox studio.

My current approach is to find the function that strips the id down, but no luck so far. 
is the feature id received by unity at all?
Is there a different way to get a feature id?

Thanks for your time!

**Comment by brnkhy** [comment]
I don't think feature ids are packed in the tileset but @jordy-isaac do you have any ideas about server side ids?

**Comment by Schaggo** [comment]
I kind of "solved" the problem by copying the id in mapboxstudio in the properties form as "ID". And call for said ID in my editing method. 

So for existing points i retrieve the ID as a property and use it  as the "featureID". It's clearly not elegant, but it works.
When adding new markers the id is simply an auto increasing number on a free server. 
Also rather ugly but works.

**Comment by brnkhy** [comment]
@Schaggo for the first part; I wouldn't call it ugly really, if the api doesn't server server side ids, that's probably the only way to do it.
For the second part, hard to comment as it all depends on app and implementation but relying on increment doesn't sounds the best for sure.

**Comment by Schaggo** [comment]
Thanks for the tip!
What would be better? A random string?

**Comment by brnkhy** [comment]
@Schaggo oh I couldn't dare to suggest an option, all depends on the project really :)
