### ISSUE TITLE
Lots of issue with Unity 2019

### ISSUE THREAD

**Issue by ti-hardikshah** [mapbox/mapbox-unity-sdk#1535]
Hello , 
i need to use your plugin for Location Base Augmented app , need 2 functionality
1)Point of interest
2)Object place on Coordinate. 
But getting lots-of issue with Plugin.
 
  * Unity version: 2019.2.17
  * Scripting Runtime Version: 
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net 4.0
  * Map-box SDK version: 2.1.1
  * The platform you're building to: Mac
  * A description of what you're trying to do: Just Run your SDK nothing else
  * Steps to recreate the bug if appropriate: create new project and import idk nothing else !!
    >> One more issue even AR Foundation branch is not updated , not working. 
  
Please possible add document , How to use sdk. that will hep us

**Comment by brnkhy** [comment]
@TheIntellify-Hardik even though SDK doesn't use AR Foundation at the moment, some older code depends on classdes which uinty moved to AR Foundation package. So if you import AR folders, you'll need to install AR Foundation package as well, have you tried that?
