### ISSUE TITLE
Hololens and Mapbox Unity build

### ISSUE THREAD

**Issue by antoineheseque** [mapbox/mapbox-unity-sdk#1550]
* Unity version: 2019.2.18f1 ( Also tried with a 2018.x.xx version)
  * Scripting Runtime Version: .Net 4.x Equivalent
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net 4.x
* Mapbox SDK version: 2.1.1
* The platform you're building to: Hololens v1
* A description of what you're trying to do: I'm trying to show a map on the HL1. ( Also it is working inside the editor )
* Steps to recreate the bug if appropriate: Create a new project, follow the steps to install [MRTK v2.3 foundation package](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/download/v2.3.0/Microsoft.MixedReality.Toolkit.Unity.Foundation.2.3.0.unitypackage), install Mapbox SDK (Remove the following folders: Google ARCode, MapboxAR, UnityARInterface, UnityARKitPlugin). Then try to export the Unity project.
* Links to your logs are also helpful: 
![image](https://user-images.githubusercontent.com/31767922/74731065-9a1d7980-5247-11ea-9897-5d128be770d4.png)

**Comment by antoineheseque** [comment]
Got it worked. The DLL wasn't set correctly within Unity, and there was an ambiguous call in 2 different scripts. I leave this here so you can maybe do something about this.

**Comment by IfnoLee** [comment]
- try Unity 2019.2.6f1 ;

- try MRTK version2.1.0;

- try replace Newtonsoft.Json with [JSON .NET For Unity](https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347)

**Comment by evertec82** [comment]
> Got it worked. The DLL wasn't set correctly within Unity, and there was an ambiguous call in 2 different scripts. I leave this here so you can maybe do something about this.

Can you expand on what you did to fix this? What DLL wasn't set correctly within Unity and what did you do to fix the ambiguous calls? Thanks, I appreciate the help.

**Comment by apranvoku** [comment]
Had the same issue. I fixed it by removing the net 4.6 version of the .dlls and keeping the portable 4.5 .net dlls. The .dlls seemed to be colliding and confusing visual studio.

**Comment by mertusta1996** [comment]
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
