### ISSUE TITLE
how to render with mapbox SDK unity

### ISSUE THREAD

**Issue by mingrong2808** [mapbox/mapbox-unity-sdk#1554]
Hi guys, i am new to unity and mapbox. I have already done imported the data source in unity. Is this the correct way??
![image](https://user-images.githubusercontent.com/55277815/75088209-2e0f7e00-5585-11ea-89fa-c60b7f61c859.png)

Can i know how to do like image below.

![image](https://user-images.githubusercontent.com/55277815/75088098-99585080-5583-11ea-8894-e5399422b30d.png)

**Comment by dm67x** [comment]
Hi, the best thing for you is to check the documentation of MapBox Unity SDK. And you can also look at examples, like this https://docs.mapbox.com/unity/maps/examples/poi-placement.

**Comment by mingrong2808** [comment]
thx, but now im currently facing this problem....
![image](https://user-images.githubusercontent.com/55277815/75232545-623ba680-57f2-11ea-9330-b6360fc18ccd.png)
At the game object modifiers, i has created a prefab modifier named earth, but.... as you can see, there were all the same model....Is there any other way to made different model to each points??

**Comment by brnkhy** [comment]
@mingrong2808 you would need a customized version of prefab modifier, with your own logic and prefabs of course, to be able to achieve that.
