### ISSUE TITLE
Drawing a route line on map with elevation

### ISSUE THREAD

**Issue by aglogger** [mapbox/mapbox-unity-sdk#1555]
What I want to achieve is to create a route line on a map with terrain elevation. This line should run through a series of LatLng values. Any hints on how I can achieve this are highly appreciated.

The end result should look like something similar to what is visulized in this image [https://github.com/mapbox/mapbox-scenekit/blob/master/docs/img/scenekit.jpg](url)

**Comment by ivangarrera** [comment]
+1 @aglogger Did you have any progress on that?

**Comment by aglogger** [comment]
Everything I figured out was to draw a line from one latlng to another using the code in DirectionsFactory and using the GeoToWorldPosition Method from the my AbstractMap reference to query the elevation at the corresponding points. But that doesnt look very well especially if you just provide to points, cause the generated line doesn't snap to the terrain between these points.

**Comment by brnkhy** [comment]
@aglogger I'm afraid there's no easy/elegant way to snap roads on terrain at the moment. Roads/lines are created independent of terrain so their resolution etc won't match. 
You can use `SmoothLineModifier` to increase the resolution of lines, then query map object for elevation on each point. You will most likely still have clipping though so my final suggestion for that is, if you have a top down-ish view, renders roads/directions on another camera and draw it on top of terrain, which will fix all clipping but of course will cause other issues if you camera gets closer to terrain.
I guess the ultimate solution would be to cut terrain mesh using line mesh and elevate that, but that will be costly (relatively) and depending on you application, it might not be a good solution either (snapping roads in a big city and loading lots of tiles etc).

**Comment by anyway2019** [comment]
I use linerender draw the line on map with elevation,but i came into another issue.the line has 22000 points which cause low frame, so i want to only render points in carmera or in current tile range.any api or help?
