### ISSUE TITLE
Building feature - Missing parts inside the meshes

### ISSUE THREAD

**Issue by dm67x** [mapbox/mapbox-unity-sdk#1557]
* Unity version: **2018.2.17f**
* Mapbox SDK version: **2.1.1**
* The platform you're building to: **Windows**

I update my mapbox version to the latest version but got some issues with the buildings feature.
My buildings are cutted, see the screenshot below. I check the tiles and I saw that buildings meshes are cut in half, or some parts are missings.

![problem_mapbox](https://user-images.githubusercontent.com/1593334/75352663-67f4c300-58aa-11ea-9ab4-59574232015f.png)

**Comment by dm67x** [comment]
When i use 100 as unity tile size everything is fine.

**Comment by brnkhy** [comment]
@dm67x great catch!
I checked the `TextureSideWallModifier`, class which creates side walls and noticed there's a bad magic number at line 378
`_currentMidHeight -= Math.Max(0.1f, (_scaledFloorHeight * _midUvInCurrentStep));`
This line means a single floor cannot be smaller than 0.1 units in Unity space. It's a very small number when tile size is set to `100`, but when you set it to a much smaller number like `1`, it fails.
I'll check for a proper fix and try to understand what that magic number was supposed to do there but meanwhile, you can just remove that `Math.Max` or change the number with something much smaller (like 0.00000001) to fix the issue temporarily.

**Comment by vishwah13** [comment]
i have the same problem and i followed you advise @brnkhy it worked but after some time it crashed please fix this issue quickly

**Comment by brnkhy** [comment]
@vishwah13 
`it crashed`
I'll definitely need more data on that. Why did it crash? Any log? What were you trying to do? I'm closing this ticket but feel free to open a new one for the bug.
