### ISSUE TITLE
Map Tiles don't always load on mobile

### ISSUE THREAD

**Issue by MichaelTGood** [mapbox/mapbox-unity-sdk#1559]
* Unity version: 2019.3.1f1
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net 4.x
* Mapbox SDK version: 2.1.1
* The platform you're building to: iPhone XR iOS 13.3.1

Hey guys, 

Starting as of a day or two ago, it is almost (but not always) the case that many of my map tiles will not show. I've been working Mapbox since Oct/Nov, but this is the first time I've seen this problem. I've tried searching around online, and looked at similar issues posted here, but not sure if it's related to any of those. 

I have not updated any software in the time before the issue started, and I haven't even changed anything in that scene, or with the Abstract Map, that I can recall.

Originally, I had been running the map set to `Camera Bounds`, but noticed a significant framerate drop whenever the camera was moved, and the next row of tiles was loaded. After experimenting with different options, I decided to go with `Range Around Transform`. The game loads a file from the network, and based on the players city/game, sets the centerTransform based on a Lat/Lng from the network file. It will then set the centerTransform and the visible buffer for the `ExtentOptions`. 

If the visible buffer was above 5, it would cause the game to crash 100% of the time, due to memory limits. After adjusting to that, no problems.

Then, after a new build with no changes to the abstract map, I started seeing the missing tiles randomly, but regularly. The issue happens on the iPhone, and not in the editor on PC, so I'm guessing this might be a memory issue again...? But it's not 100% of the time (on the phone). Sometimes, I do get all tiles loaded correctly. 

I experimented with clearing the cache before loading the map scene, and I've tried using a smaller visible buffer but saw little to no difference from these. I do not see any pattern in which tiles would be missing, or the amount.

A side question: I clear the cache by having a button delete: `Application.persistentDataPath + "/cache/cache.db"` Is there a better way? I couldn't find a Mapbox function for it (outside the dropdown menu in the Unity Editor), but I might be missing it. 

I can provide the log from Xcode if need be, but here is the last part, when the map loads. I don't really understand it, as I always have a solid data connection, sometimes on 4G, sometimes WiFi, and I think I see this also when the map tiles load properly. Or is it referring to a connect with Mapbox?

```
2020-03-02 15:17:12.732623+0100 CityApp[16529:4120370] Task <F4BCA5E5-A478-48D0-968C-C98A51FA9720>.<253> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
2020-03-02 15:17:12.734825+0100 CityApp[16529:4120370] Connection 22: unable to determine interface type without an established connection
2020-03-02 15:17:12.734915+0100 CityApp[16529:4120370] Connection 22: unable to determine fallback status without a connection
```
And then it's followed by this, repeated many, many times:
```
no 'ETag' header present in response for https://api.mapbox.com:443/v4/mapbox.mapbox-streets-v7/18/134342/86517.vector.pbf?access_token=[my correct access token]&sku=105k7ajrupxe7742a6beb794a8e9ef06bc87abb22c9
Mapbox.Platform.Cache.<>c__DisplayClass13_0:<requestTileAndCache>b__0(Response)
System.Action`1:Invoke(T)
Mapbox.Unity.Utilities.<DoRequest>d__12:MoveNext()
Mapbox.Unity.Utilities.Routine:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

Any help is greatly appropriated! 

----------------------------------------------------------------------------------

In the photos below, the blueish-gray sections are missing/un-rendered tiles. (The black sections are just empty space). The round island is the location of the centerTransform. These screenshots are taken at separate times, on separate loads. Missing tiles did not match from different loads

![IMG_3608](https://user-images.githubusercontent.com/61695214/75680622-46bd1980-5c92-11ea-82c8-00e9c1b3b620.PNG)
![IMG_3610](https://user-images.githubusercontent.com/61695214/75680620-458bec80-5c92-11ea-941b-3688092982d5.PNG)
![abstractMap](https://user-images.githubusercontent.com/61695214/75685433-d5359900-5c9a-11ea-971e-c37259293567.png)

**Comment by brnkhy** [comment]
@KkachiGames I'm not sure about the exact problem but on top of my head, you're loading too many tiles and some of them are failing due to network issues (and sdk doesn't retry). If I remember correct, visible buffer of 5 means a map of 11x11 tiles and you're downloading all three imagery, elevation and vector for each. I would highly suggest trying to lower zoom level and reduce tile count.

**Comment by MichaelTGood** [comment]
Hi @brnkhy, thanks for the reply! I also thought visibleBuffer was the problem at first, but now I'm not sure. I tested with smaller sizes; the pictures above are from a load with visibleBuffer size 3. 

Is there a way to check at runtime for the error, and have it retry the missing tiles? Or, even better, is there a way to us `Camera Bound` and not have the framerate drop with every bit of movement? The app is quite lean, with only a few GUI elements and one player model. It seems weird that it can run a constant 60fps, and then need to dip to <30 every time the user drags the camera a tiny bit. I feel like this framerate dip for each tile load on Camera Bound might be a setting I have wrong, but I don't know what.

**Comment by brnkhy** [comment]
Hey @KkachiGames,
Sorry I missed your last post here. SDK doesn't automatically retry on failures. You can find error callbacks in the code but that would require some coding to re-request them etc.
Performance issues are still a thing mainly because Unity doesn't have async texture operations (Texture2D.Load for example). We are working in that recently but don't have a good solution right this moment.
