### ISSUE TITLE
Rotate the map inside the plane

### ISSUE THREAD

**Issue by dm67x** [mapbox/mapbox-unity-sdk#1560]
I wanted to know if Mapbox have a functionality to let me rotate the map  (3D environment) inside a plane without rotating the plane.  For now i use blend mask to do that, maybe there are some alternatives who works better.

**Comment by brnkhy** [comment]
@dm67x we don't have anything like that but is moving map under a child object and rotating that not an option?

**Comment by dm67x** [comment]
I found something similar to what i want to do, it's the example TableTopAR.
