### ISSUE TITLE
Raycast not hitting in map.OnInitialized

### ISSUE THREAD

**Issue by aglogger** [mapbox/mapbox-unity-sdk#1561]
I have created a simple scene in which an AbstractMap is created with elevation. Above the map there is a cube. I created a script in which I try to determine the elevation of the map by raycasting down from the cube by calling a method with the raycasting using _map.OnInitalized. But I don't get any hit here. If I do the raycasting in the _map.OnUpdated or the scripts Update() Method I get a raycast hit. Any thought on this?

**Comment by jordy-isaac** [comment]
Do you have a terrain with a collider specified? There are also several example scenes that have recasting to a point on the map that I would have a look at to make sure that you're implementing it properly. I hope that this helps.

**Comment by aglogger** [comment]
I have collider selected on my map and the only problem I have is raycasting works except when called by the map.OnInitalized callback. I have to e.g zoom the map first, so map.OnUpdated callback is called where I do the same raycasting. And here it is working as intended.

**Comment by aglogger** [comment]
I just saw that the method map.GeoToWorldPosition(latng, true) also returns 0.0 for the y-value when called in map.OnInitalized. So it seems that the map (elevation) is not yet fully set up when map.OnInitalized is called.

**Comment by brnkhy** [comment]
@aglogger `OnInitalized ` is used for some map properties/settings initialization. You're doing a raycast, which requires collider, which means you need some tiles with colliders first. Have you tried something like;
```
Map.MapVisualizer.OnMapVisualizerStateChanged += (state) =>
		{
			if (state == ModuleState.Finished)
			{

			}
		};
```
