### ISSUE TITLE
Having trouble using GeoToWorldPosition(), version 2.1.1

### ISSUE THREAD

**Issue by highpockets** [mapbox/mapbox-unity-sdk#1562]
Hello,

I'm having a tough time trying to place POI's after initialization. This is what I'm trying:

`
private void Start(){
            
            _map.OnInitialized += () => {
                _latLong = Conversions.StringToLatLon(_latitudeLongitude);
                transform.position = Conversions.GeoToWorldPosition(_latLong, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz();
            };
        }
`

The object in question is being placed at `(-414920, 0, -551711.9)` which I'm quite sure is right beside the Milky Way, but I'm passing the following coordinates as _latitudeLongitude, 41.3825, 2.17694, which is in my camera view.

How do I get the correct position in world space in Unity?? I must be missing something, but I have studied all the related issues and tried to solve it with no luck.

I'm using the location based game prefab with custom scaling options and unity tile size set to 100. The zoom is set to 16 and the map is at the world origin.

I would really appreciate some help if anyone has ideas.

Thanks in advance,

Kris

**Comment by highpockets** [comment]
OK, this was my silly mistake.. Since the location based game prefab does not, by default, have the 'EditorLocationProvider' script as a reference of the LocationProviderFactory and instead it references a log file, when I added the EditorLocationProvider to the scene, I forgot to set it as the reference and therefore, as a result, the default location for the map was Helsinki (when I had it set to Barcelona) and the object I was trying to set was going to Barcelona... So, this is confirmation that the above code works, but sometimes the programmer that wrote it doesn't cross all of his t's or dot his i's.

**Comment by jordy-isaac** [comment]
Thanks for the feedback on this one. If you see some improvements that can be made we do review all PRs. Thanks again!
