### ISSUE TITLE
Buildings are crushed

### ISSUE THREAD

**Issue by dm67x** [mapbox/mapbox-unity-sdk#1563]
* Unity version: 2018.2.17f
* Mapbox SDK version: 2.1.1
* The platform you're building to: Windows/Oculus

I got the buildings crushed, when they suppose to have the same height.

![problem_mapbox](https://user-images.githubusercontent.com/1593334/76492999-dd779c00-6431-11ea-8908-d81c18fff00c.png)
![problem_mapbox2](https://user-images.githubusercontent.com/1593334/76493009-e36d7d00-6431-11ea-8095-9e1ffba4faa5.png)
![option](https://user-images.githubusercontent.com/1593334/76493032-f2ecc600-6431-11ea-9d83-9e1569bb449b.PNG)

**Comment by brnkhy** [comment]
@dm67x can you show the building visualizer settings as well? It's also possible that our data source doesn't have the building height in that region of course. So are you having same issue in other locaitons as well?

**Comment by dm67x** [comment]
@brnkhy by building visualizer you mean map layers > building information ? And i didn't try for a different zone. If the height information is missing for this zone, can i complete them manually ? Is it possible ?

Thank you for your answer.

**Comment by brnkhy** [comment]
make sure `property height` is selected here;
![Unity_2020-03-30_14-34-01](https://user-images.githubusercontent.com/1465390/77908093-81b36c80-7293-11ea-9396-af183aacc664.png)
I'm afraid adding building height data yourself wouldn't be easy.

**Comment by dm67x** [comment]
@brnkhy yes it's selected but i have the same issue.

**Comment by brnkhy** [comment]
@dm67x sorry I think I missed your last post here but I guess that means we don't have elevation data on that region :(
