### ISSUE TITLE
Add `FeatureBehaviour` with `GameObjectModifier`

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#157]
This will allow optimization as the data will not be cached and `Component` will not be added if developers do not need it.

This likely means changing how we pass data into `GameObjectModifier`.

Ideally, we can attach via this: https://github.com/mapbox/mapbox-unity-sdk/issues/156

**Comment by brnkhy** [comment]
feature behaviour modifier is merged into develop
