### ISSUE TITLE
How to place gameobjects only on road mesh?

### ISSUE THREAD

**Issue by viktorrrrr** [mapbox/mapbox-unity-sdk#1576]
I want to place out objects semi-randomly, but only only on where there is a road. since the whole roadgrid is one gameobject with a mesh defining where the road is. If I place it on top/in the middle of the gameobject, it would be placed on the road object, but not necessarily where there is a road. What should I be doing instead?

https://imgur.com/a/ssZ0RFk

**Comment by viktorrrrr** [comment]
I think I solved it!

       Vector3[] roads;
        roads = gameObject.GetComponent<MeshFilter>().mesh.vertices;
        Debug.Log(transform.TransformPoint(roads[2]));
Gives me something like this: (287.8, 0.1, -42.9) in world position.

**Comment by brnkhy** [comment]
Hey @viktorrrrr!
Road network will be one huge mesh if you enable `combine meshes` feature under `modelling` section. If you disable that, you'll get one gameobject per section. That being said, I wouldnt suggest doing that for performance reasons as well.
But actually reading it again, I think you have that disabled but `feature position` set to `tile center`. If you change that to `Center of Vertices`, pivot point of the road will be in the middle of it an you'll be able to use that position to spawn stuff right away.
Hope that helps!
