### ISSUE TITLE
How to Spawn Buildings From AbstractMap Using String Filter as Feature

### ISSUE THREAD

**Issue by caraneel** [mapbox/mapbox-unity-sdk#1577]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.1.14f
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET standard 2.0
* Mapbox SDK version: v 2.1.1
* The platform you're building to: iOS
* A description of what you're trying to do: 

Hi, I am using a custom tileset from Mapbox studio in my Unity project that has information on all the public schools in New York City. I'd like to create a feature layer that shows schools based on a string variable called "method1". Is there a way to do this? The filter layer is only set to accept number values, which I have used for other visualizations (e.g. grad rate) but I want to be able to filter what buildings show up based on whether the value of "method1" is test, audition, transfer, etc. Is there a way to do this? Can I re-encode the string values as a number and call those values instead? Thank you!

**Comment by brnkhy** [comment]
Hey @caraneel!
If I understand the issue correct, I believe you should be able to filter strings like this;
![AsPowerBar_2020-03-30_14-04-17](https://user-images.githubusercontent.com/1465390/77905684-5c246400-728f-11ea-89ba-d29233916349.jpg)
this of course just uses standard `type` property but I think it should work with custom stuff you have as well?
If `method1` is a enum by any chance and normally encoded as numbers, you probably can use `equals` to number?

**Comment by caraneel** [comment]
Hi @brnkhy ! You totally solved my problem, thank you so much!
