### ISSUE TITLE
Have you considered using sharedMaterial, sharedMesh wherever possible, for optimization?

### ISSUE THREAD

**Issue by horatiu665** [mapbox/mapbox-unity-sdk#1578]
Hi! 

Edit: context: I'm on the ar-foundation-port branch, so this may not be relevant at all :( (minor off-topic: this branch is pretty broken)

I'm using the Enable Preview functionality on the AbstractMap, and it's great! I can explore the map at design time without being in play mode. However, I am spammed with the following errors,. from multiple scripts:

```
Instantiating mesh due to calling MeshFilter.mesh during edit mode. This will leak meshes. Please use MeshFilter.sharedMesh instead.

Instantiating material due to calling renderer.material during edit mode. This will leak materials into the scene. You most likely want to use renderer.sharedMaterial instead.
```

My question is: why not use sharedMaterial and sharedMesh everywhere?

So I figured I'll just try to replace the references myself and see what happens, cause maybe it's an improvement in stability & performance, however it does mess stuff up, for instance in the ElevatedTerrainWithSidesStrategy.cs file, I suspect that is the one creating the sides of the tiles, and those sides are now appearing above the terrain (see image below). So I obviously shouldn't touch that without closer investigation.

Perhaps it would be good to document with //comments why in some places it is advisable to use .mesh instead of .sharedMesh

![image](https://user-images.githubusercontent.com/5824753/77821726-bc2ed500-70ec-11ea-9812-0f73ea8839ec.png)

Hope this issue helps someone figure out stuff or perhaps just document things better! Cheers!

**Comment by brnkhy** [comment]
@horatiu665 I thought we change all calls to sharedMesh for editor preview 🤔 maybe we missed a few. Are you using the latest version?
Thanks for letting us know! 🙇
