### ISSUE TITLE
Buildings color on Android is different than the Unity Editor

### ISSUE THREAD

**Issue by Flavio1997** [mapbox/mapbox-unity-sdk#1579]
Hi, in my Unity scene I see this buildings color, however when I build the Android Version colors are more darker. It seems that is only a buildings "bug". Do you have any idea on what cause this problem?

![Annotazione 2020-03-29 212206](https://user-images.githubusercontent.com/31081120/77858461-0656aa00-7204-11ea-85ca-21c902a3f3d7.png)

![Screenshot_20200329-212810_Seeties](https://user-images.githubusercontent.com/31081120/77858497-59c8f800-7204-11ea-8980-05b237b8e9a1.jpg)

**Comment by brnkhy** [comment]
@Flavio1997 I never did android builds before but it kinda looks like a material issue. Like they have different metallic/smoothness property somehow. Sorry I couldn't help much but there are a lot of android devs though, maybe someone can answer.

**Comment by Flavio1997** [comment]
Yes, I changed the rendering mode to "Opaque" and now is ok. Thank you!
