### ISSUE TITLE
Fit map to bounding box - calculate target zoom

### ISSUE THREAD

**Issue by SkylinR** [mapbox/mapbox-unity-sdk#1580]
I'm trying to fit map view to bounding box created by some markers on map.
I've already calculated center of that target box. I've got problem with calculating target zoom of map in case of containing that target bounding box on screen. Of course I need to calculate zoom value for X and Y axis to pick smaller value (which is further view) because target bounds can be different ratio than screen bounds.

**I want to achieve effect like this**: [mapbox-gl fit bounds](https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/)

I've got target bounding box and screen bounding box values. Screen bounding box I'm calculating by this method.
```
private Vector2dBounds GetScreenBounds()
{
      var screenWidth = UnityEngine.Screen.width;
      var screenHeight = UnityEngine.Screen.height;

      var sw_world = _mainCamera.ScreenToWorldPoint(new Vector3(0, 0, _mainCamera.transform.position.z));
      var sw = _map.WorldToGeoPosition(sw_world);

      var ne_world = _mainCamera.ScreenToWorldPoint(new Vector3(screenWidth, screenHeight, _mainCamera.transform.position.z));
      var ne = _map.WorldToGeoPosition(ne_world);

      return new Vector2dBounds(new Vector2d(sw.x, sw.y), new Vector2d(ne.x, en.y));
}
```

When I've got all those values I'm calculating lat and lon deltas on target bounds and screen bounds aswell. 

```
var targetLonDelta = targetBounds.East - targetBounds.West;
var targetLatDelta = targetBounds.North - targetBounds.South;

var screenLonDelta = screenBounds.East - screenBounds.West;
var screenLatDelta = screenBounds.North - screenBounds.South;
```
And now I know if I need to zoom in or zoom out (because of differential between screen and target deltas). Of course I want to chose smaller zoom value (because then I know that entire target bounding box is visible on screen)

I know that each zoom level multiplie/divide screen delta by 2 
_(it's only example not real values)_
_if_      zoom 5 = 0.50 delta 
_then_ zoom 6 = 0.25 delta
_then_ zoom 4 = 1.00 delta
_etc._

For now I am iterating in loop by zoom levels and each iteration checking if my target delta is smaller then current screen delta. (and add or subtract zoom levels) But it's unnecessary iterating and only can get integer value (of course i can iterate by 0.1 of level or even smaller value but still it's not accurate and it gives me more iterations). 

I've tried to find any equation to calculate it like dividing target delta by screen delta and then do some other calculations but each time it fails in some cases. 

**THERE IS MY QUESTION:
How to calculate that target zoom which I need to set to fit map view to target bounding box?
I just want to receive target zoom or value by which zoom should be modified (ex. _-2_ means i should zoom out by 2)** 
_It could be really nice functionallity built in sdk. :D_

_PS. 
I saw those topics but they do not helped me too much_
[#1422](https://github.com/mapbox/mapbox-unity-sdk/issues/1422) [#478](https://github.com/mapbox/mapbox-unity-sdk/issues/478) [#1125](https://github.com/mapbox/mapbox-unity-sdk/issues/1125) [#1279](https://github.com/mapbox/mapbox-unity-sdk/issues/1279)

**Comment by SkylinR** [comment]
I've found the answer. Here it is :)
```
 private void SetZoomToFitBounds(Vector2dBounds targetBounds, Vector2dBounds screenBounds)
{
      var targetLonDelta = targetBounds.East - targetBounds.West;
      var targetLatDelta = targetBounds.North - targetBounds.South;

      var screenLonDelta = screenBounds.East - screenBounds.West;
      var screenLatDelta = screenBounds.North - screenBounds.South;

      var zoomLatMultiplier = screenLatDelta / targetLatDelta;
      var zoomLonMultiplier = screenLonDelta / targetLonDelta;

      var latZoom = Math.Log(zoomLatMultiplier, 2);
      var lonZoom = Math.Log(zoomLonMultiplier, 2);

      var zoom = (float)(_mapAbstract.Zoom + Math.Min(latZoom, lonZoom));
       
      _mapAbstract.SetZoom(zoom);
      _mapAbstract.UpdateMap();
}
```
Also worth mentioning is that I'am using Orto camera.
I had problem with centering view to target bounds (even when center lat, lon values were correct). It was because of my `z` camera position (I had -10). You can adjust code to camera `z` position or just set it to 0 :)

I hope it will help :)

**Comment by PeipeiBordeaux** [comment]
Hello. According to the effect you want to achieve, you may zoom the map and keep the map staying in the bounds. But why you set the zoom, the zoom is getting from the mouse I think. How you pan or zoom the map? I am using QuadTreeCameraMovement.cs. I am trying to realize the effect you shown in the link with Unity, but I am in trouble now.

**Comment by SkylinR** [comment]
@PeipeiBordeaux If You're asking about "fly to" effect. I'm lerping position and zoom (for position `Vector2d` class has extension method `Vector2d.Lerp` and for zoom there is `Mathf.Lerp` for floats).

**Comment by nilsk123** [comment]
Thanks, this is the correct approach.

For my use case, I am rendering 'off screen' into a rendertexture, so I had to change the function to get screen bounds to not use ScreenToWorldPoint (as the map isn't exactly on screen)

Came up with this:

```
private Vector2dBounds GetScreenBounds()
    {
        var screenWidth = UnityEngine.Screen.width;
        var screenHeight = UnityEngine.Screen.height;

        var sw_world = m_Cam.ViewportToWorldPoint(new Vector3(0, 0, 200));
        var sw = m_Map.WorldToGeoPosition(sw_world);

        var ne_world = m_Cam.ViewportToWorldPoint(new Vector3(1, 1, 200));
        var ne = m_Map.WorldToGeoPosition(ne_world);

        return new Vector2dBounds(new Vector2d(sw.x, sw.y), new Vector2d(ne.x, ne.y));
    }
```

**Comment by tomCarnevale** [comment]
> I've found the answer. Here it is :)
> 
> ```
>  private void SetZoomToFitBounds(Vector2dBounds targetBounds, Vector2dBounds screenBounds)
> {
>       var targetLonDelta = targetBounds.East - targetBounds.West;
>       var targetLatDelta = targetBounds.North - targetBounds.South;
> 
>       var screenLonDelta = screenBounds.East - screenBounds.West;
>       var screenLatDelta = screenBounds.North - screenBounds.South;
> 
>       var zoomLatMultiplier = screenLatDelta / targetLatDelta;
>       var zoomLonMultiplier = screenLonDelta / targetLonDelta;
> 
>       var latZoom = Math.Log(zoomLatMultiplier, 2);
>       var lonZoom = Math.Log(zoomLonMultiplier, 2);
> 
>       var zoom = (float)(_mapAbstract.Zoom + Math.Min(latZoom, lonZoom));
>        
>       _mapAbstract.SetZoom(zoom);
>       _mapAbstract.UpdateMap();
> }
> ```
> 
> Also worth mentioning is that I'am using Orto camera.
> I had problem with centering view to target bounds (even when center lat, lon values were correct). It was because of my `z` camera position (I had -10). You can adjust code to camera `z` position or just set it to 0 :)
> 
> I hope it will help :)

Make sure that your `zoomLatMultiplier` and `zoomLonMultiplier` are positive with `Math.Abs` because otherwise you get `NaN` values in your zoom calculation, and therefore the map cannot update.

**Comment by hrasto** [comment]
I haven't tested this, but I'm wondering @nilsk123 @SkylinR is the function working also further away from the equator for a given "latitude delta"? I think it shouldn't, as Mapbox tiles are using mercator projection, so you might want to work with latitudes in that space, rather than equi-rectangular (which is what you work with when you leave latitude as-is).

For the conversion between mercator and equi-rectangular projection, the functions that you need: https://wiki.openstreetmap.org/wiki/Mercator#C.23
