### ISSUE TITLE
Is it possible to draw polygons of local level neighborhood boundaries?

### ISSUE THREAD

**Issue by gangstageek** [mapbox/mapbox-unity-sdk#1585]
So I've been trying to figure this out if it's possible. I am trying to visually show neighborhoods using Map Features. After doing some research I assumed I should be using the Admin data layer but nothing seems to work. Any help would be great if it's even possible.

Also is it possible to change the name of Map Feature in the GUI? Having a bunch of Untitled Names isn't helpful at first glance. 

Unity 2019.34f1
Mapbox v2.1.1

**Comment by brnkhy** [comment]
@gangstageek I don't think there's neighborhoods information anywhere, including admin layer.
`Mapbox Boundaries v3` might have something close but I haven't checked it myself yet either.
![chrome_2020-04-13_17-31-22](https://user-images.githubusercontent.com/1465390/79128673-9ec85f00-7dac-11ea-8e01-427f9a2684c4.png)
https://docs.mapbox.com/vector-tiles/reference/mapbox-boundaries-v3/

`Also is it possible to change the name of Map Feature in the GUI? Having a bunch of Untitled Names isn't helpful at first glance.`

I believe they are named after their layer. So you probably have layer named `Untitled` which is default name when you add a new one.

**Comment by gangstageek** [comment]
So it seems like out the box this can't work. Can I get a confirmation on that. I tried using that Titleset id and I get this error. It also seems like mapbox boundaries has it out separate token and product? 
<img width="883" alt="Screen Shot 2020-04-22 at 10 27 52 PM" src="https://user-images.githubusercontent.com/11141830/80062532-d8097900-84e8-11ea-9455-caa82560d67a.png">

**Comment by gangstageek** [comment]
Okay I solved one problem. I can't believe I just thought about this. Change your inspector to debug and you'll be able to rename your Vector Sub Layer in the inspector. 
![Screen Shot 2020-04-23 at 3 23 31 PM](https://user-images.githubusercontent.com/11141830/80155383-7b549f80-8576-11ea-85c8-8e3a93184770.png)
![Screen Shot 2020-04-23 at 3 23 15 PM](https://user-images.githubusercontent.com/11141830/80155391-7db6f980-8576-11ea-987f-d4d94c67393c.png)


So this is where I'm at now. I'm still waiting to hear back about mapbox boundaries and unity3d. It seems to be kinda pricey but I want to see if it works or not. So in the mean time I created my own Tileset. Now I'm having an issue with how the polygon is being created. It seems have not weld any vertices. I'm trying to figure out where the mesh is being generated so I can see if I can wield them myself via code. Any suggestions on where to start?

![Screen Shot 2020-04-23 at 3 19 21 PM](https://user-images.githubusercontent.com/11141830/80155114-da65e480-8575-11ea-801b-d0a1b8578037.png)

**Comment by gangstageek** [comment]
And another strange issue. All my buildings have the same direction as the Target Transform including the mesh bounds. So my box colliders are rotated. Any help with this as well?
![Screen Shot 2020-04-24 at 2 45 10 AM](https://user-images.githubusercontent.com/11141830/80199057-c0f48500-85d5-11ea-9427-cc94cc0ea9fd.png)

**Comment by brnkhy** [comment]
Hey @gangstageek,
I think merging those polygons would not be easy at all. I probably would have created a whole new visualizer for that but that would require a lot of work and SDK knowledge. I cannot think of an easy way to do it using existing SDK and SDK UI I'm afraid.
Also I believe colliders are created axis aligned when you do it in code and there's no way arounnd it. Unity probably does a simple min/max checks in all axises and creates a cube, which of course comes up axis aligned.
