### ISSUE TITLE
Get current location by clicking on button

### ISSUE THREAD

**Issue by dluigi** [mapbox/mapbox-unity-sdk#1586]
Hey guys new here so hope to fit in fast :)
Well, i'm using mapbox with Unity3D, and I'm willing to know and understand how can I make a button so I will be able to press it and the screen will take me to my location on the map.
Just like the current location button on Google Maps.
Thanks in advance!

**Comment by brnkhy** [comment]
Hey @dluigi !
You can use, `AbstractMap.UpdateMap` method to change current location by passing latlng and zoom level :)
Hope that helps!
