### ISSUE TITLE
Is mapbox for Unity abandoned ?

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1588]
Since 14th febraury no news, updates or improvements.
I receive every month an email from mapbox with news of new products, and i get info about 

    Mapbox GL JS – v1.9.0
    Maps SDK for iOS – v5.8.0
    Maps SDK for Android – v9.1.0

No news from mapbox for unity.

Thanks in advance

**Comment by brnkhy** [comment]
@ejgutierrez74 I believe we almost never followed other SDK releases (maybe except one or two versions) and indeed our release cycles slowed down a lot but no it's not abandoned.
I just PRed a fix last week and will merge that in soon. Issues board is very active as well. 
We don't have any big release coming up soon though :(

**Comment by ejgutierrez74** [comment]
Im happy about hearing that is not abandoned i received from newsletter@mapbox.com, 
Mapbox Product Updates with activity and updates on other platforms, and important things like mutlithreading in mobile ( some people have made its own code and shared here, so it only have to be tested and optimized) and allow some quantity of MB to cache map, so you can save internet connection or avoid lags or interruptions, are not being developed or a defined roadmap...Seems we are the ugly duck in mapbox platforms....

Thanks and hope bugs and new feautres would be released soon... also with some tutorials updated.

**Comment by brnkhy** [comment]
@ejgutierrez74 
I totally understand how you feel, I'm sorry about that. 
I'll try to do some tutorials, maybe some unofficial ones just to be faster. 
We already have caching by the way, tiles are cached by default after being downloaded once. I think prepackaging map data in app might be against ToS though if that's what you mean. But again I'm not 100% sure of that either, might depend on size. Mapbox help can answer that much better.
Unfortunately threading is a huge issue and we're not able to just use a working example as they generally are using another asset or work with some conditions etc. Also we have to test it on a dozen different platforms (unless it isn't a unity core based solution like jobs or something) to ensure we're not breaking anything for a customer as well. So I totally agree it's important but I'm afraid we're just not able use reuse what I have seen so far :(
