### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by Lnaydun** [mapbox/mapbox-unity-sdk#1589]
Water isn't displaying until i turn it into lines then a polygon :/ nothing loads on start or preview until those changes are made, tried almost anything I can think of but it just isn't displaying it until I change the values. 
Not too sure what to do and well no use not having water lol.

**Comment by gangstageek** [comment]
I am currently having the same issue as well.

**Comment by Lnaydun** [comment]
> I am currently having the same issue as well.

Inside the Vector Example it displays. I managed to copy the settings into my scene map and it worked for me, just got clipping as an issue, BUT this issue is still an issue because we shouldn't have to use other examples to get it working lol it should just work when we declare it inside the map features. Looking at the project, tons of it is corrupt and either makes unity crash or lags into 3fps. I've got a fairly decent set up too for my PC so it isn't my PC that is the issue. Hopefully they reply soon

**Comment by brnkhy** [comment]
Hey @Lnaydun, @gangstageek 
I'm afraid I'll need more info about this. I tried it myself, using settings below and it worked as expected. I don't have a guess what's wrong at your side but maybe the `buildings with unique ids` checkbox is checked? (admittedly it's not a very intuitive setting)?
![Unity_2020-04-13_16-42-40](https://user-images.githubusercontent.com/1465390/79124820-cd8f0700-7da5-11ea-920d-9055557148ac.png)

**Comment by Lnaydun** [comment]
Yes that was the issue, thanks :)

**Comment by Lnaydun** [comment]
It fixed my lag issue too so god knows what it was doing and the curruption issues we're to do with AR so i removed them all and it seems fine although I do have clipping. any suggestions @brnkhy

**Comment by brnkhy** [comment]
@Lnaydun umm what do you mean by clipping? I'll need more info on that :( maybe a screenshot or something?
incase you mean z-fighting (flickering) with tile plane, you can push it upwards using extrusion type and a fixed number.

**Comment by Lnaydun** [comment]
@brnkhy so basically when I make roads on my map layers, if I attach the 'road' texture some are clipping over the top of others and it doesn't wrap around it properly, I done as you suggested but it looks ugly lol so an example would be Road A is going Right, then we have road be coming upwards, when it over laps it doesn't round the corner off. It will display the texture going straight up and then across if that makes any sense? I can post a screenshot if you want but think i covered it above haha.

**Comment by Lnaydun** [comment]
![image](https://user-images.githubusercontent.com/63206656/79338942-0357fb00-7f20-11ea-9e6d-2c60182a7931.png)

This is what I mean, like I don't mind fully as much as when I overlay a seamless texture and alter it, it seems to blend together quite well but I don't wanna have to ghetto fix something incase it causes more issues later, I'm already having some issues with the Buffer Settings not loading the texture when it loads a new area... lol I'm starting to think im either not using the SDK properly or it's actually broke on side because I've looked at loads online about it and it isn't fixing my issues and honestly diving into the SDK core isn't something I wanna do. I wanna use its resources not recode it lol I already have my core game design and thought adding mapbox would be easy as it says on all the tutorials but at this point it's giving me a massive headache. I'm starting to think against using it.

**Comment by cha-hin** [comment]
Hey @Lnaydun 

Could you tell me how you applied a seamless pattern on your roads please?

Thanks.

**Comment by heath3n** [comment]
@Lnaydun There's no easy fix for this. If you want non-intersecting roads, you will need to either style the map in Studio and accept the raster image or write an intersection solver to generate a nice-looking mesh for every case that roads meet.

On a side note, how did you get that interesting blended brown/green look on your terrain? Or is that just the lighting?

**Comment by Lnaydun** [comment]
@heath3n Made it inside Sketchbook using the Gradient tool, its the underlayer, they is about 4 more layer thats go on top but the road issues has been slowing progress down, so I decided to just use a seamless splatter texture. I have a few ideas, so I'll see what I can do inside the studio to make it less broken inside unity ha

**Comment by Lnaydun** [comment]
![image](https://user-images.githubusercontent.com/63206656/80311330-fc11d680-87d6-11ea-962a-70bbb0b45c61.png)

A quick follow up after the following was suggested:
- buildings with unique ids for water not displaying switching off
- intersection solver to generate a nice-looking mesh for roads

Problem solved, not sure how you close the issue.

**Comment by cha-hin** [comment]
@Lnaydun Hey

how did you manage to set up this intersection solver?

Thank you.

**Comment by Lnaydun** [comment]
@cha-hin I made a script which checks if any vertices are inside any of the road pieces, and if they is it takes away the ones inside, then snaps the closest ones outside it to the nearest edge, with some offset input i managed to make it look like the above, then just applied a seamless texture onto the road mesh with an outline shader.

**Comment by cha-hin** [comment]
Oh what a nice result! Thank you for your explanation @Lnaydun. 

Would it work with the road seamless pattern you had set in the first place though? 

Thanks.

**Comment by Lnaydun** [comment]
@cha-hin It would work yeah but on corners where it turns they might look odd it did for me anyway so thats why I just made them have a seamless texture and then added an outline colour

**Comment by brnkhy** [comment]
@Lnaydun those roads looks awesome! Are you doing this as a post processing (after all roads are created) or as a part of a custom mesh modifier? Is the performance good? I really love the result!

closing this issue but I believe it doesn't prevent posting so we can keep talking
