### ISSUE TITLE
ChamferHeightModifier Bug

### ISSUE THREAD

**Issue by gokugen** [mapbox/mapbox-unity-sdk#1590]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.4.20f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version:  v2.1.1
* The platform you're building to:
* A description of what you're trying to do:

First of all, sorry for my bad english...
I'm trying to use the ChamferHeightModifier but when I add it, all my current buildings disappear. I did not change anything else I already look at this #878 but it didn't help me.

* Steps to recreate the bug if appropriate:

**Step 1:** Create a new abstract map and get to a point where you can vizualize buildings.

**Step 2:** Add Features -> Buildings

**Step 3:** Add mesh modifier named "ChamferHeightModifier"

* Links to your logs are also helpful:

**Comment by gokugen** [comment]
Find the solution !

In _Map Layer_ use **Custom** and in _TileSet Id_ add:

**mapbox.3d-buildings,mapbox.mapbox-streets-v7,mapbox.mapbox-traffic-v1,mapbox.mapbox-terrain-v2**

After, add buildings in _Features_.
Use **Custom** for _Primitive Type_ in the _Modeling_.
In Mesh Modifiers add:
- **PolygonMeshModifier**
- **UvModifier**
- **ChamferHeightModifier**

And finally in _Game Object Modifiers_ add:
**MaterialModifier** => ATTENTION !!! In Texturing use only **CUSTOM** for _Style Type_

<img width="534" alt="Capture d’écran 2020-04-12 à 18 37 00" src="https://user-images.githubusercontent.com/14259676/79074432-a45e7000-7cec-11ea-8cc5-4c7533184b3e.png">

You're Welcome !

**Comment by vitalik23** [comment]
> Find the solution !
> 
> In _Map Layer_ use **Custom** and in _TileSet Id_ add:
> 
> **mapbox.3d-buildings,mapbox.mapbox-streets-v7,mapbox.mapbox-traffic-v1,mapbox.mapbox-terrain-v2**
> 
> After, add buildings in _Features_. Use **Custom** for _Primitive Type_ in the _Modeling_. In Mesh Modifiers add:
> 
> * **PolygonMeshModifier**
> * **UvModifier**
> * **ChamferHeightModifier**
> 
> And finally in _Game Object Modifiers_ add: **MaterialModifier** => ATTENTION !!! In Texturing use only **CUSTOM** for _Style Type_
> 
> <img alt="Capture d’écran 2020-04-12 à 18 37 00" width="534" src="https://user-images.githubusercontent.com/14259676/79074432-a45e7000-7cec-11ea-8cc5-4c7533184b3e.png">
> 
> You're Welcome !

Hello! I tried but unfortunately it doesn’t work for me. Meybe I need to write some script for this files?
