### ISSUE TITLE
How to handle rendering of co-located prefabs?

### ISSUE THREAD

**Issue by caraneel** [mapbox/mapbox-unity-sdk#1591]
Unity version: 2019.1.14f
Scripting Runtime Version: .NET 4.x Equivalent
Scripting Backend: IL2CPP
Api Compatibility Level: .NET standard 2.0
Mapbox SDK version: v 2.1.1
The platform you're building to: iOS
* A description of what you're trying to do:

Hi, I am using a GeoJSON dataset that has several co-located data points (the data is on different schools, many of which share a building). I am spawning different colored cubes for each school, but because many of them share a location, I am getting an unpleasant flickering effect as each building is trying to render. Is there a way for me to offset the prefabs slightly so this flickering stops?

![IMG_6798](https://user-images.githubusercontent.com/15758690/79073917-3c416700-7cb7-11ea-985a-3389ff1421a9.jpg)

**Comment by brnkhy** [comment]
Hey @caraneel, can you please try `NoiseOffsetModifier`? It might be the exact thing you're asking for. Just add it to your building's game object modifiers list and it should work.

**Comment by caraneel** [comment]
Hi @brnkhy , I added it to all the different layers but I am still experiencing the flickering.

**Comment by brnkhy** [comment]
@caraneel hmm maybe the value wasn't enough? I'm not sure why this isn't parameterized but can you try changing the `0.01f` value in the `NoiseOffsetModifier.cs` and try? If that doesn't work either, issue might be different I guess.
