### ISSUE TITLE
Reveal effect with maps

### ISSUE THREAD

**Issue by unidorno** [mapbox/mapbox-unity-sdk#1592]
Hey, I just wanna know, how I can make the reveal effect with this “pop-up” animation of the buildings like in that one from the video: 

https://youtu.be/wcvAVTvpNto

Could you please tell me in which script and how I can do it? Maybe you have any examples I can download

I actually don’t need shaders, only this buildings appearing effect.

**Comment by brnkhy** [comment]
@unidorno that video is pretty old and I used unity animations for that one (if I remember correct) which was painfully slow. I highly suggest not doing that, if you want that effect, go for shaders.
anyway, trick is, 
- load map as usual, have you shader or animation to collapse scaleY to 0.
- start a timer, increase a range value by that timer
- check buildings if they are in that range
- if they are in range, slowly increase scaleY to 1

hope that helps!

**Comment by unidorno** [comment]
@brnkhy but how I can get the objects to animate? For example my map loads in x position and I need to animate buildings in camera bounds. Is there any way to get those buildings by script or animation? How can I get script which spawns that buildings?

**Comment by brnkhy** [comment]
@unidorno Gameobject modifiers does exactly that, it recieves a gameobject, buildings one by one for example. Then you can add animation scripts on it. But as I said, that approach will be incredibly slow.
