### ISSUE TITLE
Custom buildings in unity

### ISSUE THREAD

**Issue by unidorno** [mapbox/mapbox-unity-sdk#1593]
Hey, I do not want to replace special building, I want to use custom 3D models, not just polygons-created boxes. I would like to spawn one of 5-6 prefabs if it has special height, width and so on. How can I use custom buildings and how I can spawn them if they match height, width with given parameters?

Google maps have custom 3D models in their maps: 

https://youtu.be/PaCJPQkTG34

**Comment by brnkhy** [comment]
@unidorno Our SDK doesn't support something like that out of box at the moment and it would be rather hard to make that happen as well considering the variety of building shapes in real life.
I would suggest looking into mesh and gameobject modifiers. Mesh modifiers get raw vector data to create mesh so you can use them to check height of building and spawn prefabs for example. Gameobject modifiers are more like post processing to add material and stuff.
Hope that helps!

**Comment by unidorno** [comment]
> @unidorno Our SDK doesn't support something like that out of box at the moment and it would be rather hard to make that happen as well considering the variety of building shapes in real life.
> 
> I would suggest looking into mesh and gameobject modifiers. Mesh modifiers get raw vector data to create mesh so you can use them to check height of building and spawn prefabs for example. Gameobject modifiers are more like post processing to add material and stuff.
> 
> Hope that helps!
> 
> 

So can I use gameobject modifiers to create something like balconies? Or it is not impossible ?

**Comment by brnkhy** [comment]
@unidorno gameobject modifiers only recieve gameobject/mesh created by mesh modifiers, so at that point it'll be hard to calculate where balconies would be. 
You can do that in mesh modifier, as you'll get points for all walls but I guess it wouldn't be a trivial task at all.
