### ISSUE TITLE
Custom cars

### ISSUE THREAD

**Issue by unidorno** [mapbox/mapbox-unity-sdk#1594]
Hello, could you tell me how I can customize cars (traffic) in unity mapbox project? I want to reduce maximum amount of cars and change their 3D models. Is it possible? And by using which script I can get that variables?

**Comment by brnkhy** [comment]
@unidorno SDK doesn't support street decorations at the moment. It's possible to achieve something close by doing line decorations but it gets very difficult on junctions/corners.

**Comment by unidorno** [comment]
> @unidorno SDK doesn't support street decorations at the moment. It's possible to achieve something close by doing line decorations but it gets very difficult on junctions/corners.

Ok can you answer about reveal effect?
