### ISSUE TITLE
[Time Sensitive] Access Property Name data in features to color prefabs?

### ISSUE THREAD

**Issue by caraneel** [mapbox/mapbox-unity-sdk#1595]
Unity version: 2019.1.14f
Scripting Runtime Version: .NET 4.x Equivalent
Scripting Backend: IL2CPP
Api Compatibility Level: .NET standard 2.0
Mapbox SDK version: v 2.1.1
The platform you're building to: iOS
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 

Sorry for posting so often, I am using Mapbox for my graduate thesis and it is due in two weeks. I built my project off this tutorial https://docs.mapbox.com/unity/maps/overview/custom-maps/#use-a-custom-style and I am using a variable "graduation rate" as the Property Name under modeling. My hope is to create buildings of different sizes / colors based on the graduation rate, using this gradient: 

<img width="362" alt="Screen Shot 2020-04-13 at 11 34 04 AM" src="https://user-images.githubusercontent.com/15758690/79133872-be469400-7d7a-11ea-9a8d-e90d6e6f86fb.png">

How is it possible to do this (e.g. use the Property Name variable "graduation rate" to change the colors of the buildings spawned by the abstract map?) I did this previously by getting the height of th generate mesh, but I have since discovered it is not accurate.

Thank you!

<img width="261" alt="Screen Shot 2020-04-13 at 11 33 05 AM" src="https://user-images.githubusercontent.com/15758690/79133746-8c353200-7d7a-11ea-95b1-9820bcf2c473.png">

**Comment by brnkhy** [comment]
Hey @caraneel ! Have no worries about posting too much or something, I happily answer them as much as I can and as fast as I can :)
There's a bunch of stuff you can do here, two simplest would be;
(1) if you just want to categorize and have low number of categories (5 colors?), you can use filters. You can create 5 layers, add filter to each to target one category, then set the material/color below accordingly for each.
(2) if you need more control, you can create a custom game object modifier. `Run` method in it will recieve each object separately with the feature/data it uses. So you can do a lot of customization using that. `ve.Feature.Properties` will contain all properties you have.
i.e.
```
if(ve.Feature.Properties["someValueName"].ToString() == "Something Building")
{
//change material
//animate
//etc
}
```

hope that helps! good luck with your thesis!

**Comment by caraneel** [comment]
Hi @brnkhy , thanks so much for your response! So, I think I would need to use the second option as I am using the value of "graduation_rate" to change to color. Is there a way to evaluate the numeric value of "someValueName"?

I am hoping to write code like:
if(ve.Feature.Properties["graduation_rate"] < 0.75) {
//change color to orange
}
else{
change color to green
}

but I get the error that operators cannot be applied to operands of type "object" and "double".

**Comment by caraneel** [comment]
@brnkhy I was able to do it with the following code:

 public override void Run(VectorEntity ve, UnityTile tile)
        {
            GameObject building = ve.GameObject;
            Renderer buildingRenderer = building.GetComponent<Renderer>();
            Material  sideMat = buildingRenderer.materials[1];
            Material  topMat = buildingRenderer.materials[0];

            float gradRate = float.Parse(ve.Feature.Properties["graduation_rate"].ToString());
            Debug.Log("Property Values: " + gradRate);

            Color tileCol = FindObjectOfType<GradientScript>().gradient.Evaluate(gradRate);
            sideMat.color = tileCol;
            topMat.color = tileCol;
        }

thank you so much for all your help!
