### ISSUE TITLE
Draw a polygon on map in runtime

### ISSUE THREAD

**Issue by SkylinR** [mapbox/mapbox-unity-sdk#1601]
Is there any way to draw polygons on map in runtime with mapbox? 
Somethin like this would be great: [Android draw polygon](https://docs.mapbox.com/android/maps/examples/draw-a-polygon/)

**Comment by brnkhy** [comment]
@SkylinR We don't have a helper for that at the moment. I guess we have the tools for it, like triangulation etc., maybe you can use them. But we don't have a solution for snapping polygon on bumpy terrain, which has been the biggest issue with them.

**Comment by brnkhy** [comment]
@SkylinR We don't have a helper for that at the moment. I guess we have the tools for it, like triangulation etc., maybe you can use them. But we don't have a solution for snapping polygon on bumpy terrain, which has been the biggest issue with them.
