### ISSUE TITLE
Update doc : recommended version

### ISSUE THREAD

**Issue by Makio64** [mapbox/mapbox-unity-sdk#1603]
I try to make it work in URP and HDRP under unity 2020.1.xx and it doesnt work out of the box.

It would be nice to specify a recommended version ( a bit newer than 2017.. ), to test on it with the different renderer pipeline and specify in the doc and tutorial the type of render to use ( URP / HDRP ? ) cause its currently a very frustating experience.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2020.1.0b4
* Mapbox SDK version: Latest
* The platform you're building to: Windows
* A description of what you're trying to do: having a normal rendering / easier jump in project

**Comment by brnkhy** [comment]
@Makio64 I haven't checked the 2020.1 yet but just curious, isn't it using the standard rendering pipeline as default?
In case you haven't found it, it's about settings the main texture in `UnityTile.cs` file. SDK uses `Material.mainTexture` which doesn't work with HDRP and others. Changing that to `Material.SetTexture(name, texture)` fixes the issue.

@jordy how can we add `recommended version` to docs?

**Comment by Makio64** [comment]
It allows standard / URP / HDRP ( they don't offer default ) but the Universal Rendering Pipeline Project is recommended officially for all new project which are no HDRP Project.

Thanks for the step by step fix 👍

**Comment by ahmedassal** [comment]
Can you provide detailed information about how to change code to make it work with HDRP. I commented every reference to MainTexture and changed to MeshRenderer.material.SetTexture( "_BaseMap", _rasterData ); for example. In some other places to null. Which shader should I be using.

**Comment by brnkhy** [comment]
@ahmedassal I believe texture name should be `_BaseColorMap` in HDRP (on regular hdrp material). You can check the name of the field (on any material/shader) by going to debug mode on inspector. 
![Unity_2020-05-20_15-45-20](https://user-images.githubusercontent.com/1465390/82447407-ee3b3280-9ab0-11ea-91f3-4b0e2a305cd1.png)
