### ISSUE TITLE
Handle intersection when using custom LoftModifier

### ISSUE THREAD

**Issue by cha-hin** [mapbox/mapbox-unity-sdk#1606]
Hello,

I changed the roads on my map the same way it was done in the _Astronaute Game_ example. I used a `LoftModifer` with a custom  road slice that has sidewalks on both sides and a `MaterialModifier` with a road seamless pattern. But I'm facing a problem with the road intersections, here is a picture:

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/28860681/79694025-3d056a80-826e-11ea-84ca-449def6c0625.png">

Is there a way to handle that and make it look better?

By the way when I took this screenshot I was using the `Retina` option in the `Image` component but the quality still look the same as when the option was off, is there a fix for this?

Thank you.

**Comment by brnkhy** [comment]
Hey @cha-hin!
Roads look awesome but I'm afraid there's no way to handle intersections properly. We tried it in the past but it's a very difficult subject and gets worse and worse with birdges, tunnel, underpasses, uncommon/strange intersections etc etc. That's pretty much the only reason why we haven't made this type of road modeling and decorations default :(

Retina option isn't stored in database so it's possible that system is still using non-retina ones from cache. If you clear cache and run with retina enabled, you will probably see the quality change.

**Comment by cha-hin** [comment]
Thank you, I understand this must be hard to fix, knowing there is an uncountable number of situations.

I did your trick for the Retina option though and it worked thank you @brnkhy!
