### ISSUE TITLE
Readme doc out of date?

### ISSUE THREAD

**Issue by jasonhbartlett** [mapbox/mapbox-unity-sdk#1609]
Following instructions to clone this rep. After cloning instructions say to:
cd mapbox-unity-sdk
update-mapbox-unity-sdk-core.bat

There is no **update-mapbox-unity-sdk-core.bat** file?

**Comment by brnkhy** [comment]
Ah yes! We used that bat file in previous versions to pull submodules and stuff but they are all merged in now so it's not there anymore. We should fix the doc, thanks!

cc @jordy-isaac
