### ISSUE TITLE
Setting Map layer does not persist to children

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-unity-sdk#1611]
* **Unity version:** `2019.3.9f1`
  * Scripting Backend: `Mono`
  * Api Compatibility Level: `.NET Standard 2.0`
* **Mapbox SDK version:** `v2.1.1`
* **The platform you're building to:** MacOS
* **A description of what you're trying to do:** Change the scene layer of the Map
* **Steps to recreate the bug if appropriate:** 

1. Drop the `Map` prefab into an empty scene. 
2. In the Inspector, change the `Layer` to anything other than `Default`
3. `Run` the Scene. Note that all children/tiles of the `Map` parent do not match the parent layer.

Have also tried modifying this in a `Start` event from a script attached to the object using:

```
public class SetLayer : MonoBehaviour
{
  [SerializeField, Layer] int m_EditorLayer;

  void Start()
  {
    foreach (Transform child in transform)
    {
      child.gameObject.layer = m_EditorLayer;
    }
  }
}

[CustomPropertyDrawer(typeof(LayerAttribute))]
class LayerAttributeEditor : PropertyDrawer
{
  public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
  {
    property.intValue = EditorGUI.LayerField(position, label,  property.intValue);
  }
}

public class LayerAttribute : PropertyAttribute { }
```

but it seems to have no effect, as at the point of running, no children exist. Possibly, the way around this is to run in Update until children are found, then change the layer, but I'd argue that the children, when created should match the parent layer.

* **Links to your logs are also helpful:** No logged errors.

**Comment by jasonhbartlett** [comment]
I assume you are aware of the properties on the Map prefab  under TERRAIN that supposedly allows you to add new tiles to a selected layer.
![image](https://user-images.githubusercontent.com/22244576/81309639-28d4b200-9051-11ea-83e9-3b8a61773b6b.png)
I also found that even after using that, new tiles didn't always get put the the selected layer so I ended up checking and changing in Update().

**Comment by brnkhy** [comment]
@jdp1g09 I'll check this, `add to layer` should work but meanwhile you can have a custom script which registers to `TileFinished event and change the layer of incoming tile objects.

**Comment by jasonhbartlett** [comment]
Just FYI - The `Add to Unity` layer property of the Map seems to be working fine for me.  But it's also nice to know about the `TileFinished` event as well.  Thanks.

**Comment by ghost** [comment]
Thank you both - wasn't aware of either option, and now have a working solution.

**Comment by gisinator** [comment]
This is still an issue when working with features. I ticked the "add to unity layer" property and the tiles themself are indeed added to the specified layer - but their features are not. So, the terrain is in the correct layer, but buildings for example are still in "default" layer. Would be nice if this "add to unity layer" tickbox could also be applied in "features" :)
