### ISSUE TITLE
Build error in Unity 2018.4 when Targeting UWP (The type or namespace name 'MapboxAccountsUnity' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by jasonhbartlett** [mapbox/mapbox-unity-sdk#1612]
* Unity version:
2018.4.20f1

 * Scripting Runtime Version:
 .NET 4.x Equivalent

 * Scripting Backend:
.NET

 * Api Compatibility Level:
 .NET Standard 2.0

* Mapbox SDK version:
 v2.1.1 (official release from Mapbox)

* The platform you're building to:
 UWP

* A description of what you're trying to do:
 Add Mapbox to a HoloLens 2 app

* Steps to recreate the bug if appropriate:
1. Create new project in Unity 2018.4.20f1
2. Download and import mapbox-unity-sdk_v2.1.1.unitypackage from Mapbox website
3. Delete these folders (GoogleARCore, MapboxAR, UnityARInterface, UnityARKitPlugin)
4. Switch Platform to UWP
5. Set scripting backend to .NET, and capability to .NET Standard 2.0
6. Click Build

* Links to your logs are also helpful: 

```
Assets\Mapbox\Unity\MapboxAccess.cs(1,7): error CS0246: The type or namespace name 'MapboxAccountsUnity' could not be found (are you missing a using directive or an assembly reference?)
Assets\Mapbox\Unity\MapboxAccess.cs(332,27): error CS0246: The type or namespace name 'MapboxAccounts' could not be found (are you missing a using directive or an assembly reference?)
Error building Player because scripts had compiler errors
```

Note: I do not get these errors when targeting Standalone.

**Comment by brnkhy** [comment]
@jasonhbartlett I think this is the same problem you mentioned in other ticket, right? Has changing dll settings fixed this one as well?

**Comment by jasonhbartlett** [comment]
Oh.  No, not same issue. I just realized I posted the reply to my own issue but for the wrong one.  Please close this one, but reopen the other.  That comment was meant to go here:

> Okay, just FYI - I just found that if I drill down to Mapbox\Core\Plugins\Mapbox\MapboxAccounts\net4x and select the MapboxAccountsUnity .dll and add a check for WSAPlayer (currently is not checked), then these errors go away.
> Simple fix I guess.
