### ISSUE TITLE
Custom runtime datasets WITHOUT using Mapbox studio?

### ISSUE THREAD

**Issue by douglasg14b** [mapbox/mapbox-unity-sdk#1616]
I have a need to overlay a grid (https://eng.uber.com/h3/) over a map, with data provided at runtime. Like: 
![image](https://user-images.githubusercontent.com/1400380/82762632-f64be880-9db6-11ea-8489-0a4e345ffdc2.png)

This data would just be GeoJSON

This data is provided to the client by me, and has restrictions on it's visualization as it's a gameplay element that is improved as the player progresses, meaning I will have many different manipulations of this data. It's lazily generated when users request data in an area that has not been generated yet (Largely because pre-generating the entire planet of ~9m hexagons is TB's of data). I would expect to generate, process, and return this manipulated datset to the requesting client in a couple hundred ms. And of course the game has to know about every one of these grid items, as gameplay features and interactions depend on them. 

Can datasets like this (Just a bunch of GeoJSON) be rendered at runtime without having to rely on mapbox studio?

**Comment by brnkhy** [comment]
@douglasg14b technically it shouldn't be too hard I guess. `AbstractMap` class has events for tile loading/unloading so you should be able to;
- register to those from another script
- get new tile coordinates (you have both latlng and unity space object position)
- request corresponding data from other server
- visualize it on the tile object

I haven't used that api but if it's hex based, it might be a little harder to find `corresponding` dat of course.
Actually I think whole thing is pretty much same as one of my old side project you can find here; http://barankahyaoglu.com/dev/cloud-visualization-in-unity3d/
I just realized that post needs more tech details/code but I guess the idea is same?
