### ISSUE TITLE
Self-hosted/3rd party tiles for the Unity SDK

### ISSUE THREAD

**Issue by douglasg14b** [mapbox/mapbox-unity-sdk#1617]
This is a new issue stemming from this 2018 question: https://github.com/mapbox/mapbox-unity-sdk/issues/1139

<hr>

I want to host my own tiles so I have more control over costs and customization. Being able to host my own tiles, from my own infrastructure, would keep costs down.

Can I direct this SDK to use tiles from another source? Such as a self hosted [Tegola](https://tegola.io/), or [OpenMapTiles Server](https://openmaptiles.com/server/). If so, how?

From what I could find, other mapbox SDKs (Ie. [mapbox-gl-js](https://docs.mapbox.com/mapbox-gl-js/example/third-party/), [mapbox-android](https://docs.mapbox.com/android/maps/examples/add-a-vector-tile-source/), and [mapbox-ios](https://docs.mapbox.com/ios/maps/examples/source-custom-vector/))  support 3rd party tile sources. While [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) (I assume the Unity SDK uses mapbox-gl-native?) appears to not care where the tiles come from as long as they are conforming to the expected specification.

**Comment by brnkhy** [comment]
@douglasg14b I'm afraid Unity SDK doesn't support that at the moment and Mapbox URLs are hardcoded into some lower level stuff. I think whole `Tile` class (`Tile.cs`) is built upon Mapbox stuff but maybe (just maybe), if you clone `DataFetcher` classes and change them to use your own data fetching implementation instead of the `Tile.Initialize`, it would work.

**Comment by douglasg14b** [comment]
Can this be a feature request to bring the Unity SDK in line with the other major Mapbox SDKs?

**Comment by brnkhy** [comment]
@douglasg14b we probably won't have a chance to look into that any time soon. I think it wouldn't be trivial with vector data either (tho much easier with raster data). I'm sorry.
