### ISSUE TITLE
Change Color

### ISSUE THREAD

**Issue by 3rdgradewelder** [mapbox/mapbox-unity-sdk#1628]
Hello! How can I change a color only of "Hero"(enclosed is an image) from script? If I change prefub color of "Hero" than both colors of "Hero" and "Data" change (I use FindGameObjectWithTag).
![error](https://user-images.githubusercontent.com/66948635/84649893-f9e31300-af0f-11ea-948b-a1b485314107.png)

**Comment by brnkhy** [comment]
Hey @3rdgradewelder!
I think you're using same prefab modifier and prefab and that's the issue. Have you tried using two different prefab modifiers and two different prefabs (with two different materials on them)? That would probably work.

**Comment by 3rdgradewelder** [comment]
The problem really was with similar materials. Thank you!
