### ISSUE TITLE
Does mapbox AR sdk supports unity version 2019.3

### ISSUE THREAD

**Issue by shubhamguptak** [mapbox/mapbox-unity-sdk#1632]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@shubhamguptak I believe it was in 2019, Unity moved some core classes into `ArFoundation` package in PackageManager. So even though we don't use ArFoundation, you would need that package to compile and run AR stuff. Hope that helps!
