### ISSUE TITLE
Instructions in Traffic and directions example

### ISSUE THREAD

**Issue by Rana-Yehya** [mapbox/mapbox-unity-sdk#1633]
I am trying to find a way to instruct the user to go left, right, or forward while trying to reach the destination. I can't find anything useful like 'Direction API' in JS. Does it exceed in unity SDK?

**Comment by dm67x** [comment]
Hi, you can check the "Traffic and directions" example. 
https://docs.mapbox.com/unity/maps/examples/traffic-and-directions/

**Comment by Rana-Yehya** [comment]
Yes, I am working on this example. I need to access the routes information. I found the `void HandleDirectionsResponse(DirectionsResponse response)`  method in 'DirectionFactory.cs'. All I can find that the 'DirectionsResponse' variable can access all the information about  waypoints, but not the routes. I need the routes information. Should I call the 'Direction API' somewhere, or is there a variable storing this information?

**Comment by brnkhy** [comment]
@Rana-Yehya I haven't used the JS version so I'm afraid I don't understand what exactly you're looking for. You can find the route informations under `response.Routes` list. If you're looking for guidance/turn commands, yes we don't have something like that in unity sdk.
