### ISSUE TITLE
To get lon lat when clicking with the mouse

### ISSUE THREAD

**Issue by VladGluschenko** [mapbox/mapbox-unity-sdk#1636]
Hello everyone. I need to get coordinates of the click place of the map (lon, lat) when clicking with the mouse for creating new marker at this location. How can I get these lon, lat?

**Comment by dm67x** [comment]
Use your main camera then create a ray with ScreenPointToRay, then when it intersect with the map get the world position of that point. Then you need to use WorldToGeoPosition method of AbstractMap class.

**Comment by brnkhy** [comment]
@VladGluschenko what @dm67x suggested should work. I'm closing this for now but feel free to reopen if you have further questions.
