### ISSUE TITLE
Mapbox studio export doesn't render the same in Unity

### ISSUE THREAD

**Issue by Silloty1** [mapbox/mapbox-unity-sdk#1639]
Hello everyone
I am trying to use  MapBox studio to create maps for my Unity application. I have something rendered in Unity which is not exactly the same as in MapBox Studio.
Indeed, for example, I've set building colors in Mapbox studio for a 3D Rendering (with elevation), POI such as train stations, and streets in colors.
The problem in Unity when I am importing is that I don't have my 3D buildings rendered per default. I have to go to the features section and add it manually again. Concerning the POI, they are not displayed in 3D as in the studio version, but stuck in 2D on the image. Last, I don't have the update from my street when I am changing the color, even 10 minutes after the update.
Does it mean that Studio is just here to custom the map in 2D and for the 3D content we have to add it manually in Unity in the feature section ?

Thanks a lot

* Unity version: Unity 2019.3.2f1
  * Scripting Runtime Version: 
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: mapbox-unity-sdk_v2.1.1
* The platform you're building to: UWP / HoloLens 2
* A description of what you're trying to do: Mentionned above
* Steps to recreate the bug if appropriate: 
 - Create a custom Map in mapbox studio with 3D building
 - Add the map prefab in the Unity Scene
 - Copy / Paste the Style URL in the Map Prefab in Unity -> Image -> Tileset ID/ Style URL

![Mapbox Unity](https://user-images.githubusercontent.com/17072780/86446327-1951ac80-bd14-11ea-9fe7-c44352239b86.PNG)
![MapboxStudio](https://user-images.githubusercontent.com/17072780/86446330-19ea4300-bd14-11ea-9401-c41a89b79f5c.PNG)

**Comment by brnkhy** [comment]
Hey @Silloty1 
Indeed studio and unity integration doesn't work like that and it just support images using them as terrain texture. 
Anything else (buildings, pois etc) should be created on Unity side.

**Comment by madhugk** [comment]
Hi, 

I have been experiencing similar issue where in the land base colour doesn't look as the same colour used in Mapbox studio styling. I see the streets, building reflects with the colour given( attached the clip of the mapview) but not the land. 
![mapboxLandColor](https://user-images.githubusercontent.com/48920986/92530273-fc5dbc00-f223-11ea-8594-1c4650420e84.png)
I am using unity version 2020.1.2f1 and mapbox-unity-sdk_v2.1.1 
Please help me on this as I am going through project deadlines and I need to understand why it is not showing the land colours and need to resolve it soon. Thank you!

**Comment by brnkhy** [comment]
@madhugk as you know, Unity is a 3d engine and by default it's using lighting, shading etc. for any object and texture. Your problem is most likely due to that. You might want to try an unlit material/shader and it'll probably help.
