### ISSUE TITLE
To get height

### ISSUE THREAD

**Issue by VladGluschenko** [mapbox/mapbox-unity-sdk#1642]
It is not clear how to get the height in accordance with the given coordinates. Maybe there is an example code? I would appreciate that.

**Comment by VladGluschenko** [comment]
Mapbox offers methods for obtaining real elevation data in Unity units at a given latitude and longitude. For example `QueryElevationInUnityUnitsAt(Vector2d latlong)`. How can I convert height data in Unity3d units to real height data?

**Comment by brnkhy** [comment]
@VladGluschenko there is another method `public virtual float QueryElevationInMetersAt(Vector2d latlong)` right below the one `QueryElevationInUnityUnitsAt` :)
