### ISSUE TITLE
Identifying POI instances spawned by SpawnPrefabAtGeoLocation

### ISSUE THREAD

**Issue by baris-cincik** [mapbox/mapbox-unity-sdk#1643]
I wish to spawn custom POIs on the map. I follow the instructions in POIPlacementScriptExample. https://github.com/mapbox/mapbox-unity-sdk/blob/b574bcfacdd3cb1833fdba0499b5ae55fee6e2b5/sdkproject/Assets/Mapbox/Examples/3_POIPlacement/POIPlacementScriptExample.cs#L10 
The code in that example looks something like:

```
                void Start()
		{
			map.VectorData.SpawnPrefabByCategory(prefab, LocationPrefabCategories.ArtsAndEntertainment, 10, HandlePrefabSpawned, true, "locationItemName");
			map.Initialize(new Vector2d(37.784179, -122.401583), 16);
		}

		//handle callbacks
		void HandlePrefabSpawned(List<GameObject> instances)
		{
			if (instances.Count > 0)
			{
				Debug.Log(instances[0].name);
			}
		}
```

I use a copy of this with SpawnPrefabAtGeoLocation and it seems to work fine. My questions is, how do I name the instances and identify them in the call back method? My guess is to use the locationItemName property but I'm not sure how to access that variable. So in the HandlePrefabSpawned method I want to to something like:

```
if(instance.???.locationItemName = "someName"){
//do configuration
}
```

Thanks!

**Comment by muhammedyusuf-sermet** [comment]
I think that callback just returns all the created POI game objects which you can traverse as you already pointed out. If that is the case, modifying the label or other specifics of each POI just depends on the design of your game object. If you simply used the POI prefab (e.g. FoodPoiLabelPrefab), I think you can set its label by something like this:

```c#
instances[i].GetComponent<Mapbox.Examples.PoiLabelTextSetter>().SetText("yourCustomLabel");
```

and you can add a simple function to the PoiLabelTextSetter as:

```c#
public void SetText(string textParam) {
	_text.text = textParam;
	RefreshBackground();
}
```

**Comment by baris-cincik** [comment]
Hey there.

I see your point. The problem  is I need to identify the instances by using a key. The key should be assigned to the prefab during spawning process. So ideally when spawning:

`map.VectorData.SpawnPrefabByCategory(prefab, LocationPrefabCategories.ArtsAndEntertainment, 10, HandlePrefabSpawned, true, "Location_Item_Key");`

and then in the callback function or any other function I should identify the instance using that key.

```
if(instance.name == "Location_Item_Key"){
//do something
}
```

I think SpawnPrefabByX functions assign the Location_Item_Key to the name of the parent object of the instances in the callback function. So as a temporary solution I use the following in the callback function: `GameObject.Find(instance.name).transform.parent.gameObject.name;`
which includes the Location_Item_Key. But I'm pretty sure there must be a more straight forward way to do it.
