### ISSUE TITLE
Zooming in to greater than 16 causes Satellite tile color to be washed out in certain locations

### ISSUE THREAD

**Issue by athenaj** [mapbox/mapbox-unity-sdk#1645]
Zooming in to about a 16 zoom level, the satellite tiles come out in this high contrast black and white look and feel as opposed to satellite view and the resolution is never seemingly very sharp.

![image](https://user-images.githubusercontent.com/7002376/87270023-e4282580-c49c-11ea-88d5-44b8d9789586.png)

**Comment by brnkhy** [comment]
Hey @athenaj 
I'm afraid this isn't a Unity issue but satellite imagery is just like that. Satellite imagery contains shots from different times, different cameras (satellite, airplane, drone etc) etc etc. they are generally processed to blend but in higher zoom levels are rural areas, this happens :(
