### ISSUE TITLE
Loading Custom style

### ISSUE THREAD

**Issue by dagerob** [mapbox/mapbox-unity-sdk#1646]
* Unity version:  2019.3.0f6
* Mapbox SDK version: v2.1.1
* The platform you're building to: Android
* A description of what you're trying to do: I want to use a custom style. In mapbox studio the style appears to not have any buildings labels. I already published and saved it in mapbox studio. But when I copy the URL in Unity, the map shown there has all the labels, although they should not appear. Is this an issue in the mapbox server, on the Unity project??

this is the style as shown in mapbox studio
![image](https://user-images.githubusercontent.com/40010687/87668703-dd373680-c76c-11ea-940e-df7b15d6ecff.png)

this is the style as it appears in Unity
![image](https://user-images.githubusercontent.com/40010687/87668751-f9d36e80-c76c-11ea-8877-39a58ae38640.png)

these are the settings regarding the style
![image](https://user-images.githubusercontent.com/40010687/87668791-0eb00200-c76d-11ea-8d94-27475ceac0f3.png)

It also happens when I build the project and run in on the Android device

**Comment by brnkhy** [comment]
@dagerob this is most likely due to caching. You can clear Unity cache from Mapbox menu (there is also a `check for updates` checkbox in mapbox settings window). 
If it doesn't work, you can try saving it under a new name in mapbox studio, that would guarantee an update.

**Comment by dagerob** [comment]
Ok, thank you, I will try that

**Comment by brnkhy** [comment]
closing this for now then, please feel free to open again if issue persists.
