### ISSUE TITLE
Getting multiple errors

### ISSUE THREAD

**Issue by JuanFHaretche** [mapbox/mapbox-unity-sdk#1648]
Also Mapbox tab isnt appearing.
![image](https://user-images.githubusercontent.com/63614406/87730510-5dc25b00-c79e-11ea-8873-7041db1538aa.png)

**Comment by brnkhy** [comment]
@JuanFHaretche you're missing some classes which Unity moved to `ArFoundation` package recently (starting from 2019 I think). So if you're using AR, you should install ArFoundation (even though our sdk doesn't use ar foundation yet). If you're not doing AR, you can just delete all ar folders inside mapbox package as well.
