### ISSUE TITLE
[question] Is there a way with this sdk to update our mapbox tileset? 

### ISSUE THREAD

**Issue by Epsil0ne** [mapbox/mapbox-unity-sdk#1650]
For the moment, in unity I press a button to generate new geojson data and I put them by hand into my dataset in the mapbox web page. Then with this dataset I update my tileset (which is the tileset  I use on my unity map). 

However I know there should be a way to update my tileset with new data by code and not by hand. According to what I found here (https://docs.mapbox.com/help/glossary/tileset/) I could use Mapbox tiling service or the Upload API to update my tileset, but I'm not sure how to use them inside my unity game.

Does the mapbox skd for unity can help me communicate with these service or directly help me update my tileset with my new geojson?  

(I'm in Unity 2019.3 with mapbox sdk 2.0.1 )

**Comment by brnkhy** [comment]
@Epsil0ne You can definitely do it using the api but I'm afraid Unity SDK doesn't have any layers or helper methods for that. You would have to do the http calls yourself :(

**Comment by Epsil0ne** [comment]
Ok, thanks for your answer =)
