### ISSUE TITLE
How to access Map Layers in Abstract Map script. 

### ISSUE THREAD

**Issue by JonFaull** [mapbox/mapbox-unity-sdk#1656]
Hi, I am trying to gain access to control specific map layers that are in the features section of the map layers part of the Abstract Map script. I've taken the entire script apart but unfortunately I can't see how to access it. Specifically I am trying to toggle them on and off with on screen buttons. 

Any help would be great, thanks!

**Comment by DevNMY** [comment]
This is how we handle it in our project :

```
        /// Toggle Layer (for example buildings) by name (string). 
        ///Check your layer names in the AbstractMap Layer section to decide which one to call
        public void ToggleLayer(string layername)
        {
            VectorSubLayerProperties subLayerProperties = map.VectorData.FindFeatureSubLayerWithName(layername);
            subLayerProperties.SetActive(!subLayerProperties.coreOptions.isActive);
        }
```

**Comment by Markovicho** [comment]
This is how we handle it in our project :

```
        /// Toggle Layer (for example buildings) by name (string). 
        ///Check your layer names in the AbstractMap Layer section to decide which one to call
        public void ToggleLayer(string layername)
        {
            VectorSubLayerProperties subLayerProperties = map.VectorData.FindFeatureSubLayerWithName(layername);
            subLayerProperties.SetActive(!subLayerProperties.coreOptions.isActive);
        }
```

**Comment by JonFaull** [comment]
> This is how we handle it in our project :
> 
> ```
>         /// Toggle Layer (for example buildings) by name (string). 
>         ///Check your layer names in the AbstractMap Layer section to decide which one to call
>         public void ToggleLayer(string layername)
>         {
>             VectorSubLayerProperties subLayerProperties = map.VectorData.FindFeatureSubLayerWithName(layername);
>             subLayerProperties.SetActive(!subLayerProperties.coreOptions.isActive);
>         }
> ```

Hi, that looks like it will work for me, thanks!

**Comment by brnkhy** [comment]
Thanks a lot @Markovicho !
@JonFaull Another thing I might suggest is, depending on your performance needs (and frequency of this toggle being used), you might want to try creating al labels, placing them under a certain game object (labels under canvas in this case) and enabling/disabling that container game object. It might be much faster for frequent toggling.
