### ISSUE TITLE
Terrain Height Tile Seam Issue

### ISSUE THREAD

**Issue by DevinWatson** [mapbox/mapbox-unity-sdk#1659]
Unity version: 2019.4.7f1
Mapbox SDK version: 211.1
The platform you're building to: Windows x64
A description of what you're trying to do: View 3D buildings on a map.
Steps to recreate the bug if appropriate: Open a scene with terrain with elevation, navigate to Atlanta, Georgia

There seems to be some bad terrain height data running through the heart of Atlanta, Georgia,

![image](https://user-images.githubusercontent.com/1735588/89854602-4c345f00-db62-11ea-9823-6de5f354d729.png)

**Comment by brnkhy** [comment]
@DevinWatson I'm not exactly sure what's the problem. I initially thought it might be a data issue but then I found textures look fine. Then I realized if I change elevation resolution, it actually works as intended. Default terrain resolution setting is `10`, if you increase that to 32 or 64, it should look fine. At least it did on my machine. I'll try to find out what's wrong as well but you can get over it quickly doing that.
thanks for letting us know!


![Unity_2020-08-12_04-08-14](https://user-images.githubusercontent.com/1465390/89963965-b37d0c80-dc51-11ea-91b5-57a5e24dbb88.png)
