### ISSUE TITLE
Bug: Sidewalls not constructed as expected when Sample count is 255

### ISSUE THREAD

**Issue by pampas93** [mapbox/mapbox-unity-sdk#1666]
## Bug description
While I have the sample count on the Abstract map set to max (255), the sidewalls show up as bars.

![image](https://user-images.githubusercontent.com/8945788/90347924-841f2480-dff0-11ea-8d90-ed32bf92c5a9.png)

## Steps to recreate the bug: 
With sample abstract map component, with ElevationLayer type as "Terrain with elevation", and sample count = 255. If I enable "Show sidewalls", the walls show up as bars below the map. As attached below,

* Unity version: 2019.3.15
  * Scripting Runtime Version: .NET 4.x
  * Scripting Backend: IL2CPP
* Mapbox SDK version: 2.0.1
* The platform you're building to: Editor for now

**Comment by pampas93** [comment]
![image](https://user-images.githubusercontent.com/8945788/90347986-eed06000-dff0-11ea-929f-f4ade4312122.png)

**Comment by brnkhy** [comment]
Hey Pampas!
Nice catch. It's an annoying issue but luckily very simple fix.
What happens is, when you set it to 255 it needs `(255 * 255) + (255*8)` vertices (first part is top vertices, second part is side walls).  That equals to 67065 which is above 65536 limit of 16bit indexing for mesh triangles.
Fix is simply setting mesh indexing setting to 32 bit like this;
`ElevatedTerrainWithSidesStrategy.cs` line 232
![rider64_2020-08-20_21-48-00](https://user-images.githubusercontent.com/1465390/90812511-e2b90b00-e32e-11ea-99fd-e8cc27d76a90.png)

I'll create a fix&PR soon as well.

That being said, do you really need full res terrain? Unless you really need that level of precision, I would highly suggest lowering that number as it's really not noticable at all above roughly 100-ish  levels.

Anyway, hope this helps!

**Comment by pampas93** [comment]
@brnkhy That was perfect. I was just playing around with the sample count and jumped into this bug. Learnt it just by experimenting that i don;t require anything above 80. But thanks for looking into it
