### ISSUE TITLE
White Tiles in ARKit Export

### ISSUE THREAD

**Issue by alperdincer** [mapbox/mapbox-unity-sdk#167]
Thanks to @brnkhy , I compiled MapBox Unity SDK from development branch and start ARKit demo from beginning. No matter what I tried, I always get white tiles on ARKit even I changed the map tiles. The tiles are working OK on Unity Scene but white on ARKit.  

Also I still got the maps above the ground, they do not fit on the tables. Is there anything to fix this problem?

**Comment by david-rhodes** [comment]
@alperdincer White tiles could be related to #42. Please see if this is also your problem by increasing the `TileSize` a great deal (to validate).

For snapping your map to a surface with ARKit: you will need to implement the ARKit Hit API (Unity shows an example of how to do this in their ARKit repo). At this point, you'll need a component and some mechanism for which to perform a "PhysicalRaycast." When you get that point back from ARKit, you can simply offset your map root with that value.

**Comment by alperdincer** [comment]
Hi David,

I'm using maps at level 15 with Tile Size 0.1 which is working fine with previous build. I checked the #42 , but increasing the tile size results in unexpected behaviour for AR, like room size maps :)

**Comment by david-rhodes** [comment]
Fixed: 032466b58ca6418d61f285a91f28c2d65ae7e54b
