### ISSUE TITLE
how to build area to plant tree by road line

### ISSUE THREAD

**Issue by 55hhhh** [mapbox/mapbox-unity-sdk#1677]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:I want to build a buffer area by road, can you teach me ?
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
there is a little discussion about that here; https://github.com/mapbox/mapbox-unity-sdk/issues/1672
