### ISSUE TITLE
Possiable to get all features within a tile set regardless of rendered or not

### ISSUE THREAD

**Issue by Reddevildragg** [mapbox/mapbox-unity-sdk#1678]
Is it possible to get a list of all features on a tile set within unity or via a rest API.

I looked though the documentation and found the following request "/v4/{tileset_id}/tilequery/{lon},{lat}.json" but looks like the limit can not be more than 50 which means i can not collect all the data points even if i set the radius to infinity.

Reason im wanting a whole list is to work on some clustering logic that can pre-caculate what needs to be turned on/off depending on the users Zoom level, rather than having to figure it out every time the user zooms in (similar to how the supercluster logic work)

Thanks for any pointers.

**Comment by brnkhy** [comment]
@Reddevildragg there isn't a direct way I guess. Easiest thing would be creating a mesh modifier. It'll receive all features in its layer. You can store them, then process all after map finished event maybe? It would be super clean as well.

You can also interject much earlier, on vector layer visualizer or vector factory level but that would require a lot of changes in SDK code.
Using a `mesh modifier` might sound strange but it's only the name. I think that's the best way actually.

**Comment by Reddevildragg** [comment]
Hi @brnkhy thanks for the help. Just wondering with this mesh modifier this would only trigger when the object is spawned if im thinking correctly (sorry if im mistaken).
The ultimate goal in what im looking to do is to create a clustering system when zoomed out that splits down as the user zooms in. Was trying to think if i know all the objects to being with then could look to do some distance checks and go from there.
Unless there is a nicer way to cluster that is built in but could not see anything around this, just trying to mimic the supercluster behaviour that is present on web client
