### ISSUE TITLE
Control map's Zoom Level with a UI slider.

### ISSUE THREAD

**Issue by HanBaichuan** [mapbox/mapbox-unity-sdk#1686]
* Unity version: 2018.4.17f1
* Mapbox SDK version: v2.1.1
* The platform you're building to: iOS 13

Hi there. I have a UI slider that is supposed to change the Zoom Level of the Map by setting SetZoom() with that UI slider. Now, when I drag my UI slider in play mode, the slider in the inspector changes accordingly, but it doesn't affect the map tiles in play mode. Directly changing the Zoom slider in the inspector works fine, which is my desired outcome. [Here's my video that shows what I described above.](https://youtu.be/WQ_dvVIeCaQ)

My desired outcome is: In play mode, when I drag the UI slider (slider min value: 0 ; slider max value: 22), the Zoom Level changes accordingly. Hope someone can help me with this problem :)

Thank you.

**Comment by brnkhy** [comment]
@HanBaichuan If I remember correct, set zoom function doesn't update the map, just sets the value and wait for `execute` call. Can you try `update map` method for this? It takes latlng and zoom level. You can get the center latlng from AbstractMap object but of course you'll need to do this through a script.

**Comment by HanBaichuan** [comment]
Thank you @brnkhy ! You are right. All I had to do was using the `UpdateMap()` after `SetZoom()`. Or as you said, pass the zoom parameter to the `UpdateMap()` method. [My video after fix](https://youtu.be/xvOYf6opLZ0)

Thanks again!

Bryan
