### ISSUE TITLE
Where is the TerracedWorld Example???

### ISSUE THREAD

**Issue by Narrenschlag** [mapbox/mapbox-unity-sdk#1688]
I use the new v2.1.1 version for Unity. 
But this version does not contain the TerracedWorld example.
I really love the idea behind it and wanna work with it! 
Somebody help me out? :P

**Comment by brnkhy** [comment]
Hey @Narrenschlag ! 
That was a favorite of mine but we had to remove it after some data/api chances made it much more difficult. It's still possible using terrain vector api and contour line layer but might be tricky. Sorry couldn't help much.
