### ISSUE TITLE
Floating buildings after zooming

### ISSUE THREAD

**Issue by rbyjoswald** [mapbox/mapbox-unity-sdk#1693]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.4.4
  * Scripting Runtime Version: Editor: .NET 4.x, Mobile: .NET Standard 2.0
  * Scripting Backend: Editor: Mono, Mobile: IL2CPP
  * Api Compatibility Level: Android: API level 24, iOS: 10
* Mapbox SDK version: 2.1.1
* The platform you're building to: Editor, Android, iOS
* A description of what you're trying to do:

When adding buildings to a zoomable map and then zooming and panning around the camera I rather consistently manage to somehow make buildings floating. Am I the only one?

* Steps to recreate the bug if appropriate:

Just enable buildings on the Features layer and zoom and pan around in the gameworld. At some point buildings appear strangely overallping or flying

* Links to your logs are also helpful: 

![mapbox_floating_buildings](https://user-images.githubusercontent.com/20922523/96117039-bc0bf080-0ee9-11eb-89d6-39c039d673e4.JPG)

**Comment by brnkhy** [comment]
Hey @rbyjoswald,
I think it might be the same issue with this one; https://github.com/mapbox/mapbox-unity-sdk/issues/1557 
can you have a look at that and let me know if it fixes the issue?

**Comment by rbyjoswald** [comment]
That seemed to fix the issue for now.
