### ISSUE TITLE
Remove PoiVisualizer

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#170]
Poi Visualizer was a layer visualizer created specifically for pois and it simply placed gameobjects on poi positions.
Few weeks ago we introduced Prefab Modifier, which does exact same thing and can be used under VectorLayerVisualizer as well. With that, we don't need PoiVisualizer anymore and is pretty much deprecated.
We can remove the class (didn't want to rush it before) or add an Obsolete tag on it in case some devs are still using it (conversion to vector layer vis would take 2mins though).

So should we just delete it? Any reasons not to?

**Comment by david-rhodes** [comment]
@brnkhy I think we can mark as obsolete this round and remove in a future update.
We can name it obsolete in the create menu and also log a warning encouraging developers to make a switch to the new one. I'm doing the same for `MeshFactory` versus `VectorTileFactory`.

**Comment by brnkhy** [comment]
pushed directly on dev branch
