### ISSUE TITLE
IOS Build ERROR

### ISSUE THREAD

**Issue by walidalbabi** [mapbox/mapbox-unity-sdk#1700]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 2019.4.3LTS
* Mapbox SDK version: LAST
* The platform you're building to: IOS
* A description of what you're trying to do: When i build to iphone i get This Error (Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead.) and when i open the project in xcode and Try to Build it i GET
(ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/.../ios/UnityExport/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "OBJC_CLASS$_ARAnchor", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_ARImageAnchor", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_AROrientationTrackingConfiguration", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_ARPlaneAnchor", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_ARReferenceImage", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_ARSession", referenced from:
      objc-class-ref in ARSessionNative.o
  "OBJC_CLASS$_ARWorldTrackingConfiguration", referenced from:
      objc-class-ref in ARSessionNative.o
  "Geo::GetiOSAppDocumentsDir()", referenced from:
      Geo::PathUtils::GetSandboxDataPath() in libiPhone-lib.a(GeoPathUtils.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation))

**Comment by brnkhy** [comment]
@walidalbabi I'm afraid I don't know much about iOS so I'm not able to help. I'll keep this open though, hopefully some other dev might be able to answer it.

**Comment by brnkhy** [comment]
@walidalbabi I just found this fixes the issue;
https://github.com/mapbox/mapbox-unity-sdk/issues/1552

shortly using `GetUnityFrameworkTargetGuid()` instead of `TargetGuidByName("Unity-iPhone")`

**Comment by walidalbabi** [comment]
Nicee thxxxx
