### ISSUE TITLE
Incompatible install with Unity 2019 and 2018

### ISSUE THREAD

**Issue by janweigel** [mapbox/mapbox-unity-sdk#1702]
When installing the mapbox-unity-sdk 2.1.1 according to the steps described here: [www.mapbox.com/install/unity](https://www.mapbox.com/install/unity/) then no Unity toolbar entry with a Mapbox menu is created and therefore no registration of the Mapbox credentials is possible.

* Unity version: 2019.4.13f1 and 2018.4.28f1
* Mapbox Unity SDK version: 2.1.1
* Windows 10

For testing purposes I downgraded the project to Unity 2018.4.28f1 but the Mapbox menu entry isn't created there as well.
Instead I get the following error message:
`Cannot resolve parent rule: .ToolbarPopup`
`UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)`

I couldn't find any in information about incompatibilities in the documentation.
Which versions of Unity are compatible with the current mapbox-unity-sdk 2.1.1 and install all required components correctly?
Any help appreciated.
Thank you!

**Comment by ashleyjamesbrown** [comment]
This is the same for me using 2019.4 and Mac OSx.
Furthermore there are ARCORE errors in the console too.

**Comment by janweigel** [comment]
@ashleyjamesbrown 
I managed to fix it by installing the AR Foundation package.
As soon as it was installed and Unity was restarted, the Mapbox menu appeared.
Hope this helps.

**Comment by ashleyjamesbrown** [comment]
I installed ARCORE package and it fixed it for me. Thanks :-)
