### ISSUE TITLE
 Change Building materia

### ISSUE THREAD

**Issue by 55hhhh** [mapbox/mapbox-unity-sdk#1704]
How to change the building materia ?I want to simulate the real scene,but I can not solve this problem.
![微信图片_20201027101947](https://user-images.githubusercontent.com/49355232/97249034-07a19100-183e-11eb-8b2e-fb5f3447694c.png)

**Comment by brnkhy** [comment]
This is a big question but you can start here;
![Unity_9iHemPFRd6](https://user-images.githubusercontent.com/1465390/99390176-3cf34900-28e9-11eb-973a-22cb924919c0.png)
