### ISSUE TITLE
Alternative world scaling

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#171]
At the moment, we're using 1unit = 1meter and scaling the world only by the transform.scale of the root object.
This causes lots of issues when the scaling value is too low. Most noticably, textures go black (or white in AR) and some gameobjects seems getting lost. 
This gets even worse with ArKit as it uses real world units as well. Our default tile size is 100 and if you want a small map on your table, you'll have to change that to 0.1 as the tutorial suggest. Which means, depending on the zoom level, system is scaling 500m+ tiles (generally a few dozen km) down to 0.1meters and that's around 10^-4 scale value.

Most straight forward alternative to this is, applying part of this scaling to vertex positions. I expect unity to handle small vertex positions much better than small scale values. So instead of using 1-2-3 values, we'll use 0.01-0.02-0.03 for positions and scale down the world by just 10^-2. Or simply do it all on vertices and don't scale the world at all.
How? We probably can do it in ModifierStack, right before assigning vertices to Mesh. It'll take yet another iteration an all vertices so will be costly but should be good for a quick test to see if it works at all. Then we can push it into another existing loop to save performance.

#167 and #42 is an outcome of this problem.

**Comment by brnkhy** [comment]
![unity_2017-07-26_16-46-47](https://user-images.githubusercontent.com/1465390/28624527-0e45c4e2-7222-11e7-8530-312083c83cc0.png)
I tried the solution I mentioned above and it looks quite good on first tests. I had to implement preinit/init for whole mesh generation tree to begin with (I think it doesn't have a ticket at the moment, will check again  and open one after this).
good news is, it's easy & works. bad news is, this means multiplying bunch of v3 with world scale value which we didn't need before (in mesh generation structure) and that's something easy to forget for developer. Actually I only did this for flat terrain so far, I should try with terrain with height as well. Might be even more confusing there.
Anyway, so proposed solution works. Now I'll try to polish it for performance and see if it's good enough.

**Comment by brnkhy** [comment]
![unity_2017-07-26_17-00-51](https://user-images.githubusercontent.com/1465390/28625140-012d7a1e-7224-11e7-872d-81ccf0fed4ea.png)
it works with height as well. again this was easy but one v3 I forgot to scale confused me for a while for example. 
I think scaling the root object made everything simpler but other than that, this is much better in almost every other aspect (so far).

**Comment by david-rhodes** [comment]
Fixed: 032466b58ca6418d61f285a91f28c2d65ae7e54b
