### ISSUE TITLE
spawn a prefab objects in multiple positions and to add different type of prefab models in each location marker

### ISSUE THREAD

**Issue by 7grajesh** [mapbox/mapbox-unity-sdk#1714]
Hi, I'm using SpawnOnMap.cs script to spawn a prefab in multiple positions. i am try to add different type of prefab models in each location marker. this script to add n number of location strings but only one prefab of all location marker. so i need to add each location marker different models and also to control zoom levels to fix the models. How could I do?

**Comment by brnkhy** [comment]
@7grajesh you probably can create two arrays, one for positions (latlng) and other for prefabs. Then create them one by one in the script, using matching index prefab for each latlng.

**Comment by 7grajesh** [comment]
@Baran Kahyaoğlu, Thanks its working to add multiple prefab in each locations

**Comment by Zerik-ICAN** [comment]
Hi, can you post your scrip please ? I failed to correctly integrate two arrays into the SpawnOnMap.cs script
