### ISSUE TITLE
Help: Problem after turning on the GPS

### ISSUE THREAD

**Issue by mym2o** [mapbox/mapbox-unity-sdk#1716]
Support
* Unity version: 2019.4.0f1
  * Scripting Runtime Version: 
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.0.1
* The platform you're building to: Android
* A description of what you're trying to do:
Sometimes my players forget to turn on the GPS and start the game. When it happens, an in-game alert asks them to turn it on. 
If the player turn on the GPS and come back to the game, Mapbox still does not show the map.
Is there a way to "reload" Mapbox?

Regards,
Domenico

**Comment by brnkhy** [comment]
@mym2o I never worked with location/gps so I'm not sure but have you checked the relevant location provider scripts? Unregistering and registering to events might help. But then how will you detect the GPS state 🤔 Sorry couldn't help much.

**Comment by mym2o** [comment]
Hi @brnkhy thanks for your answer.
Luckily, it's a small game with only a scene. At the end, I have decided to reload the entire scene when the player reactivates the gps and now it works.
