### ISSUE TITLE
Problem with Mapbox Menu : no Map Editor

### ISSUE THREAD

**Issue by averpoort** [mapbox/mapbox-unity-sdk#1717]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.4.4f1
* Mapbox SDK version: v2.1
* The platform you're building to: Desktop
* A description of what you're trying to do: I would like to have acces to the Map Editor as described in the available features. When I import the package and resolved the bugs of import, I have acces to the Mapbox Menu but I have only access to the 
Atlas Template Generator, Clear file Cache and Setup.
I have tried on another project and the same things happen. There is no error in the log for that.

**Comment by brnkhy** [comment]
@averpoort Map editor removed from the SDK some time ago, I'm afraid most of our documentation is outdated at this point. I'm really sorry for the confusion.
