### ISSUE TITLE
converting unity location/transform to lat/long paramater.

### ISSUE THREAD

**Issue by Reddevildragg** [mapbox/mapbox-unity-sdk#1718]
Does anyone know the best way to get a map to center on a clicked item spawned in the world.

currently i am getting the clicked object and trying to convert it to a lat/long location by using the following:

`var latLon = transform.GetGeoPosition(map.CenterMercator, map.WorldRelativeScale);`

however this does not appear to be giving me the correct lat long for the object which i can then enter into the maps lat long field and update.

What makes it more odd is when debugging out the results of the above function, as i move the map the geo position changes, which does not sound right as the lat/long should be consistent and not change. maybe i have the wrong function to do the conversation, but effectivly i want to say my unity vector3 location of (x,y,z) is equilivant to the latlong location(x,y). Does anyone know best way to do this.

Thanks

**Comment by mym2o** [comment]
Hi @Reddevildragg , 
to convert a Vector3 to a Vector2d (lat/long) I use the following:
`map.WorldToGeoPosition(playerTransform.position)`
