### ISSUE TITLE
new vector tiles loaded with wrong data

### ISSUE THREAD

**Issue by janweigel** [mapbox/mapbox-unity-sdk#1720]
We're developing an android location based game using Unity and Mapbox. 
We're experiencing problems when the player moves and Mapbox is loading new tile data.
At first when the map and the position is initialized the loaded data is correct but when the player moves out of the initially loaded area and Mapbox SDK fetches new data then this new data is often completely not related to the correct features in this new area.
Buildings are loaded which don't exists and random roads are crossing the actually existing roads.
Please see the attached screenshot.

* Unity version: occurs both in 2020.1.11f1 and 2019.4.13f1
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.1.1
* The platform you're building to: Android

![Screenshot_20201106-185000_Neyon Clash Unity](https://user-images.githubusercontent.com/4882318/98689880-a5cc4580-236c-11eb-9d54-b4aa49e36524.jpg)

Around 50 percent of the buildings on this screenshot don't even exist.
If the App is closed and reopened then the data is correctly loaded and displayed as long as the player doesn't move too far in an area where the Mapbox SDK has to fetch new data. 
Sometimes the newly loaded data is correct as well but many times it's just random roads, buildings and so on. 

Any help appreciated how to get Mapbox reliably fetching new data dynamically.
Thanks a lot!

**Comment by brnkhy** [comment]
@janweigel it's probably leaking features from another tile. I believe we don't have this fix merged in yet but can you give this fix a shot;
![msedge_5cSp9OESpS](https://user-images.githubusercontent.com/1465390/99397501-31594f80-28f4-11eb-8338-627eca7c15ee.png)
I'm sorry for sharing it as a screenshot but it was the fastest way possible at the moment :)

**Comment by janweigel** [comment]
Hi @brnkhy,
thanks a lot for the info!
I already found this branch a few days ago and tested it yesterday.
It completely eliminates the problem and should definitely be merged into the master.
Problem solved for me.
