### ISSUE TITLE
Question: Is there a list of categories (poi/places) that can be addressed?

### ISSUE THREAD

**Issue by Schaggo** [mapbox/mapbox-unity-sdk#1721]
I'm in the early stages of designing a new location-based game and haven't chosen a map service yet. 
The idea is to find places by category and enable content when the user is at the closest location of that type. 

The app is supposed to find the closest bus stop set a marker on its location.
Is there a list of categories that can be addressed, so I can get narrow down the possibilities for content?
Thanks for your time!

**Comment by brnkhy** [comment]
@Schaggo There isn't a list of types as it's just a string field. But I believe those strings are generally consistent with each other and you shouldn't have problems with typos, caps etc.
