### ISSUE TITLE
Map not showing on certain devices

### ISSUE THREAD

**Issue by olemidEON** [mapbox/mapbox-unity-sdk#1722]
Hi,

We are developing a multiplayer experience in Unity, centered around a Mapbox map. On our office computers we have had no problems like this one. But on one of my colleagues laptops, the map just doesn't show up at all. We're gonna be looking further into the logs etc but for now it doesn't seem like anything out of the ordinary is happening in the console.

The PC is not a gaming one, so my question would be, is there a known issue about low-end computers failing to load maps? Is there anything in particular we should be looking for while debugging?

If any further information is required please let me know

Further information:
Unity 2019.4.11
Scripting runtime: Mono
API compatability: .NET Standard 2.0
Mapbox version 2.1.1 (But also older)
Platform: Cross-platform; Windows, Mac, Mobile VR, HoloLens

PC specs:
Processor: Intel Core i7 1.80 GHz
RAM: 8GB
Graphics: Intel UHD Graphics 620 and 2048MB ATI Radeon RX 550X
Software: Windows 10 Pro

**Comment by brnkhy** [comment]
@olemidEON I can't remember hearing an issue like this before. If it doesn't show up at all, I wonder if it might be a connection issue. 
Basic demo scenes doesn't even use custom shaders or anything if I remember correct. Workload shouldn't be trouble with stuff like `zoomablemap` demo scene for example.
So yeah, I'm afraid I have no idea :(

**Comment by alexandre-root** [comment]
Same here!
The map works fine in the Unity Editor (2020.2) but not in the Android build (Android 8), the map is just invisible.

**Comment by Shivansh0309** [comment]
Hey did anyone find a solution to this?

**Comment by brnkhy** [comment]
@Shivansh0309 what's `this` exactly? Original post and issue is most likely device-related issue. and I guess we can close this at this point since we haven't heard from the original poster.
Other issue mentioned about android is totally different and we can discuss it in another ticket.
