### ISSUE TITLE
How to set a pre defined lat/long as origin and spawn player around this(instead spawning player at origin)? 

### ISSUE THREAD

**Issue by saszer** [mapbox/mapbox-unity-sdk#1724]
currently(like in most examples) , when the game starts the player is at origin and map is built around it. 

Instead I would like to set the map origin (0,0,0) at a fixed/predefined lat/long , and thus so player then spawns according to its long/lat(through its GPS) around this predefined long/lat( instead of spawning at origin and defining lat/long around it)

**Comment by saszer** [comment]
Aight, not sure if this the right way(or if there's a better-inbuilt way)

but I've added the provided PositionWithLocationProvider.cs on the player with a predefined fixed map attached to this script. 

and I have added this line in its update: 

LocationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;

seems to be working ( at least in the editor)

**Comment by cavanju** [comment]
Hi @saszer, I am having the exact same problem could you show me a part of the script to help me out please. Because I don't really understand it in full detail.

**Comment by saszer** [comment]
@cavanju 

You can use one of the examples provided in mapbox to create a fixedmap( i used data explorer). 

There's a script which comes with mapbox named PositionWithLocationProvider.cs
just add this line in its update method : `LocationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;`
attach this script to your player/object and your map(gameobject) in the field of this script(in editor). 


ps - if you want to spawn an object with a predefined location on this map, you can use spawnonmap.cs



moded PositionWithLocationProvider.cs >> 
```
namespace Mapbox.Examples
{
	using Mapbox.Unity.Location;
	using Mapbox.Unity.Utilities;
	using Mapbox.Unity.Map;
	using UnityEngine;

	public class PositionWithLocationProvider : MonoBehaviour
	{
		[SerializeField]
		private AbstractMap _map;

		/// <summary>
		/// The rate at which the transform's position tries catch up to the provided location.
		/// </summary>
		[SerializeField]
		float _positionFollowFactor;

		/// <summary>
		/// Use a mock <see cref="T:Mapbox.Unity.Location.TransformLocationProvider"/>,
		/// rather than a <see cref="T:Mapbox.Unity.Location.EditorLocationProvider"/>. 
		/// </summary>
		[SerializeField]
		bool _useTransformLocationProvider;

		bool _isInitialized;

		/// <summary>
		/// The location provider.
		/// This is public so you change which concrete <see cref="T:Mapbox.Unity.Location.ILocationProvider"/> to use at runtime.
		/// </summary>
		public ILocationProvider _locationProvider;
		public ILocationProvider LocationProvider
		{
			private get
			{
				if (_locationProvider == null)
				{
					_locationProvider = _useTransformLocationProvider ?
						LocationProviderFactory.Instance.TransformLocationProvider : LocationProviderFactory.Instance.DefaultLocationProvider;
				}

				return _locationProvider;
			}
			set
			{
				if (_locationProvider != null)
				{
					_locationProvider.OnLocationUpdated -= LocationProvider_OnLocationUpdated;

				}
				_locationProvider = value;
				_locationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;
			}
		}

		Vector3 _targetPosition;

		void Start()
		{
			LocationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;
			//_map.OnInitialized += () =>
			_isInitialized = true;
		}

		void OnDestroy()
		{
			if (LocationProvider != null)
			{
				LocationProvider.OnLocationUpdated -= LocationProvider_OnLocationUpdated;
			}
		}

		void LocationProvider_OnLocationUpdated(Location location)
		{
			if (_isInitialized && location.IsLocationUpdated)
			{
				_targetPosition = _map.GeoToWorldPosition(location.LatitudeLongitude);
			}
		}

		void Update()
		{	
			transform.localPosition = Vector3.Lerp(transform.localPosition, _targetPosition, Time.deltaTime * _positionFollowFactor);
			LocationProvider.OnLocationUpdated += LocationProvider_OnLocationUpdated;
		}
	}
}

```

**Comment by cavanju** [comment]
Great thank you so much!!! Ill try it out!
