### ISSUE TITLE
I used the official Demo but it not worked

### ISSUE THREAD

**Issue by yhhyueye** [mapbox/mapbox-unity-sdk#1726]
I have submited a right token and open the Demo,but i cant get the Map,after loading the game is full of dark,i can just see the mapbox Logo and when i click the scene,it was a empty scene except the Logo.And when i creat a new scene and pull the map alone, i just can see a black standard.I can't see anything about the real Map,what should I do?

**Comment by yhhyueye** [comment]
![mmexport1606222682630](https://user-images.githubusercontent.com/53588252/100097792-02b11b00-2e98-11eb-9e12-cf0567d8d68a.jpg)

**Comment by yhhyueye** [comment]
just like this, i cant see the map data ......TAT

**Comment by yhhyueye** [comment]
![image](https://user-images.githubusercontent.com/53588252/100231611-3fe1df80-2f62-11eb-8356-fc62873bd82b.png)

my raster data state is error like this,and my shader is black,it cause the problem?

**Comment by brnkhy** [comment]
@yhhyueye are you getting any errors on unity? are you sure your access token is correct? Is it same on all demo scenes? It looks like web stuff isn't working (tiles are there, textures are not) but hard to say what's wrong exactly.

**Comment by yhhyueye** [comment]
> @yhhyueye are you getting any errors on unity? are you sure your access token is correct? Is it same on all demo scenes? It looks like web stuff isn't working (tiles are there, textures are not) but hard to say what's wrong exactly.

Thanks for your feedback!! I'm beginner of unity and mapbox ,i dont change or add some setting for demo.I'm sure I used the correct token,it show valid and i could chose any demo scenes,but it was same on all demo scenes,but the Globe demo show
![image](https://user-images.githubusercontent.com/53588252/100243947-61969300-2f71-11eb-9873-d2832a2ba95f.png)
except Globe demo caugth this error,all the demo have not error
I guess the network will be one of the reason,but i dont sure,beacuse i change my network some times and i install the mapbox sdk in my other PC but the same situation happened. Did the network casue the error about the raster data state?
I see some issues talk about LWRP,and change the tile.cs code, but i have not used LWRP....
So you think it's the Internet problem? or you need any other infomation about my project?
Looking forward your feedback! thank you

**Comment by yhhyueye** [comment]
Thanks for your feedback!! I'm beginner of unity and mapbox ,i dont change or add some setting for demo.I'm sure I used the correct token,it show valid and i could chose any demo scenes,but it was same on all demo scenes,but the Globe demo show
except Globe demo caugth this error,
all the demo have not error
I guess the network will be one of the reason,but i dont sure,beacuse i change my network some times and i install the mapbox sdk in my other PC but the same situation happened. Did the network casue the error about the raster data state?
I see some issues talk about LWRP,and change the tile.cs code, but i have not used LWRP....
So you think it's the Internet problem? or you need any other infomation about my project?
Looking forward your feedback! thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mapbox/mapbox-unity-sdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上10:30
收件人:&nbsp;"mapbox/mapbox-unity-sdk"<mapbox-unity-sdk@noreply.github.com&gt;;
抄送:&nbsp;"唐黑虎"<497021366@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mapbox/mapbox-unity-sdk] I used the official Demo but it not worked (#1726)





 
@yhhyueye are you getting any errors on unity? are you sure your access token is correct? Is it same on all demo scenes? It looks like web stuff isn't working (tiles are there, textures are not) but hard to say what's wrong exactly.

**Comment by yhhyueye** [comment]
it's the network problem ,thanks
