### ISSUE TITLE
Load new tiles in Coroutine or even better a Job in separate thread

### ISSUE THREAD

**Issue by janweigel** [mapbox/mapbox-unity-sdk#1727]
Currently when Mapbox is loading new tiles the GUI/main thread has quite a huge performance problem and frame drops depending on the number of tiles and the geometry of buildings. Depending on this circumstances the experience for the user is that bad, that it's impossible to use it for production right now.

We already changed the mapbox code for loading new tiles to load a maximum of one tile per frame but it's still not sufficient and is still producing ugly frame drops.

Would it be possible to refactor the tile loading code to use a Coroutine or probably even better, a Unity Job on its own thread to load a new tile and its geometry?
Usually it's not that crucial if the new tiles take some time to be loaded completely if the tile buffer isn't set too small, but it's crucial if loading new tiles is blocking the main thread as all animations and user interactions become laggy and unresponsive.

We think it would be a great improvement if new tiles could be loaded in a thread separate from the main UI thread.
Do you think that could be an option to be implemented in the near future?
Thank you!

**Comment by Markovicho** [comment]
Hey @janweigel,

check this out: https://github.com/mapbox/mapbox-unity-sdk/issues/1701

**Comment by brnkhy** [comment]
Hey @janweigel,
we are working on async texture operations for raster layers at the moment (imagery and elevation). After that, I'm planning to switch to vector maps asap. 
Indeed we'll have to thread everything there and I'm afraid that'll lead to a huge refactor that'll take some time. So my guess is, it won't be ready soon, I'm sorry :(

**Comment by janweigel** [comment]
Hey @brnkhy,
thanks for the info. It's great to hear that you're working on threaded tile loading. I hope it won't take too long as this is currently a real problem to get Mapbox in Unity production ready for our products.

A little off topic but I don't know where to ask:
We realized that in Mapbox Streets V8 loads of buildings are completely missing or have wrong height information. Especially in rural areas Mapbox almost has no buildings at all while google has quite exact building information even in the smallest villages.
Do you have any recommendation where to ask regarding the current state and future plans of building data in Mapbox?
Thank you!

**Comment by brnkhy** [comment]
@janweigel I really want to get image performance stuff out as soon as possible, even in alpha/beta state. 

I can't say much about data I'm afraid, I know nothing about that part. My only suggestion might be that if you ever suspect, check and compare buildings with mapbox studio to ensure it's not a SDK bug or anything on Unity side.
I think Mapbox support would be the best to answer that questions.
I'll close this ticket if you don't mind, feel free to post again for further questions though.
