### ISSUE TITLE
Can i use the personal image or tile data in unity sdk?

### ISSUE THREAD

**Issue by yhhyueye** [mapbox/mapbox-unity-sdk#1732]
it can use the personal source (not studio style) in mapbox webGL,can i do it in unity sdk?
because i want to use it offline or in local Area network,does the sdk support this demand?
just like the webGL:
"sources": {
  "osm-tiles": {
    "type": "raster",
    'tiles': [
          "http://my server link......"
      ],
    'tileSize': 256
  }
}

**Comment by brnkhy** [comment]
@yhhyueye technically, you can. But SDK doesn't have helper methods or anything for it at the moment so you'll have to do bunch of custom coding to make it work.

**Comment by tadpoleai** [comment]
but how to implement it, any detail method can supply, thanks very much
