### ISSUE TITLE
Add example for map clustering?

### ISSUE THREAD

**Issue by ik-dev** [mapbox/mapbox-unity-sdk#174]
As a part of my project I have been asked to explore clustering of points.  I know the GL JS api supports this method and I'm wondering what thoughts folks might have about implementing it using Unity.  Also, I think this might be common enough to warrant an example scene?

**Comment by david-rhodes** [comment]
@ik-dev This is something that would be very cool to explore, but I don't think it's priority for us right now. That said, you could probably port [Supercluster](https://github.com/mapbox/supercluster) to C# to get this type of functionality.

**Comment by navenedrob** [comment]
@david-rhodes I've actually been thinking about it some more (that was me @ik-dev), without porting Supercluster just yet. My current thought is that I will use a sphere and attach the scale of the sphere to mouse zoom. I'll use the collider for the sphere to judge what points are inside it and then pull or push the points together using the zoom level. That way I can mimic the clustering.

Only issue I have right is that I'm using 3d terrain with the rgb layer for my map, so adjusting the coordinates of the points might get interesting in combination with the "sphere clustering".

**Comment by david-rhodes** [comment]
@navenedrob Sounds interesting! The great thing about Unity and Mapbox both is that it's pretty simple to prototype and iterate.

> Only issue I have right is that I'm using 3d terrain with the rgb layer for my map, so adjusting the coordinates of the points might get interesting in combination with the "sphere clustering".

This should be trivial with a raycast + layer mask.

**Comment by FDDdan** [comment]
Is there any updated regarding map clustering? I can't figure it out how to make it work in Unity.

**Comment by adikhel** [comment]
Do you have any plans to support clustering in unity3d?

**Comment by yosun** [comment]
Checking back

**Comment by brnkhy** [comment]
@yosun I'm afraid it's not planned for any time soon, sorry :(

**Comment by tomires** [comment]
In case somebody is still looking for a solution, here is one with O(n^2) complexity. The function should be called when user finishes the pinch-to-zoom gesture.

https://gist.github.com/tomires/bba62ef7949018ee4d75cebefb0f69c3

**Comment by WaseemAbbas-DevCrew** [comment]
Please check the **[SuperCluster-CSharp](https://github.com/DevCrew-io/SuperCluster-CSharp)** library available on [GitHub](https://github.com/DevCrew-io/SuperCluster-CSharp) and [NuGet packages](https://www.nuget.org/packages/DevCrew.SuperCluster). It is a port of the SuperCluster javascript library by MapBox. 

You can implement clustering in your Unity3D map with Mapbox.
