### ISSUE TITLE
Editor GUI messed up when inheriting AbstractMap

### ISSUE THREAD

**Issue by pampas93** [mapbox/mapbox-unity-sdk#1741]
### Steps to recreate the bug if appropriate
- Create new class and inherit the `abstractMap` class. And adding this component to a gameObject in the editor does not show up the nice GUI which we usually see on abstractMap

![abstractMapBug](https://user-images.githubusercontent.com/8945788/102457408-f2f0a680-3fff-11eb-8f7c-9d0ee09155f1.PNG)

* Unity version: 2019.3.7
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET 2.0 standard
* Mapbox SDK version: 2.1.1
* The platform you're building to: Editor (Windows)

**Comment by brnkhy** [comment]
SDK uses `MapManagerEditor` class for `AbstractMap` editor. 
Shortly, if you clone that and change `[CustomEditor(typeof(AbstractMap))]` line, you should get the same inspector.
Closing it for now but please feel free to reopen if you have follow up questions.
