### ISSUE TITLE
Black tiles with no texture

### ISSUE THREAD

**Issue by PooyaRahimian** [mapbox/mapbox-unity-sdk#1750]
I have an attached Map prefab (AbstracMap) to my scene. The map correctly load the terrain at initialization (Start) but when I set a new coordinate and zoom via calling  `UpdateMap` it correctly sets the coordinate in general section but all tiles turn to black.  In Unity Tile parameters, Raster Data State is Error, height Data State is Loaded, and Vector Data State is None. 
How can I load a map via script for a given coordinate?

 Unity version 2019.3.12f1
 API comp Level .NET Standard 2.0
Mapbox Version 2.1.1
Platform Windows 10

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by Jamesfleming1** [comment]
I had this exact same issue so I'm not sure why the author closed this issue
