### ISSUE TITLE
Building Unity App for Windows will not load Mapbox

### ISSUE THREAD

**Issue by sugatena** [mapbox/mapbox-unity-sdk#1751]
When building Unity application to Windows target platform that includes Mapbox and distributing out, the map does not seem to load when run on a "non-developer" machine (no Unity installed/configured). If we load Unity and Mapbox SDK onto that targeted "non-developer" machine, then everything will load and run correctly in the previous deployed exe.

Is there some setting or configuration that is needed in order to include and deploy Mapbox within the built exe for distribution?

Unity version: 2020.1.0f1
OS: Windows 10 
Build Settings: Target Platform Windows, x86_64
Mapbox SDK version: v2.1.1

**Comment by DarioEsteinou14** [comment]
mapbox-unity-sdk_v2.1.1 tiene errores de codificación.

**Comment by Joo918** [comment]
Issue fixed!
For others that may experience the same problem:

Make sure .NET Framework 3.5 is installed on the Window 10 machine.
They are not installed by default.
