### ISSUE TITLE
Question:How can I get lowest height in map?

### ISSUE THREAD

**Issue by katsuwo** [mapbox/mapbox-unity-sdk#1755]
I'm using mapbox-unity-sdk V2.1.1
how can I get lowest and highest point in map?
I want to know cordinates and Height.

thank you.

**Comment by brnkhy** [comment]
@katsuwo 
I don't think there's an easy solution here.
but the first thing comes to my mind; 
- get `AbstractMap.MapVisualizer.ActiveTiles`
- iterate over that list, find the lowest value in `Tile.HeightData`.

**Comment by katsuwo** [comment]
thank you.
I will try it.
