### ISSUE TITLE
Won't load at all with 2021.0b8

### ISSUE THREAD

**Issue by smhk** [mapbox/mapbox-unity-sdk#1759]
If you try putting mapbox-unity-sdk_v2.1.1 in a fresh 2021.0b8 project, you just get a pile of errors.

I tried both iOS and droid target.

I did try adding ARFoundation from Unity, etc, as sometimes suggested. No difference.

Is this known behavior?  Thanks.

![Screen Shot 2021-02-28 at 11 40 46 AM](https://user-images.githubusercontent.com/3938526/109427865-e43c4d80-79b9-11eb-8020-d730fb22763d.png)

TBC if I completely remove / don't install all AR related folders, it does work great as plain (non-AR) mapbox.

PS I was using Unity on a Mac at the time.

**Comment by brnkhy** [comment]
@smhk installing ArFoundation used to fix this issue as some libraries, like `SpatialTracking` (if I remember correct) is in that package now. 
I don't do AR so I'm not really sure but checking the messages, it looks like code inside `GoogleARCore` and `XR.ArCore` package are having some trouble. Have you tried uninstalling `XR.ArCore` package?

**Comment by buggyGlitch** [comment]
> If you try putting mapbox-unity-sdk_v2.1.1 in a fresh 2021.0b8 project, you just get a pile of errors.
> 
> I tried both iOS and droid target.
> 
> I did try adding ARFoundation from Unity, etc, as sometimes suggested. No difference.
> 
> Is this known behavior? Thanks.
> 
> ![Screen Shot 2021-02-28 at 11 40 46 AM](https://user-images.githubusercontent.com/3938526/109427865-e43c4d80-79b9-11eb-8020-d730fb22763d.png)
> 
> TBC if I completely remove / don't install all AR related folders, it does work great as plain (non-AR) mapbox.
> 
> PS I was using Unity on a Mac at the time.

Facing the same issue on Unity 2020.3.11f1, Have you got it working by deleting the AR Related files ?

**Comment by brnkhy** [comment]
@buggyGlitch yes it should work when you delete all AR folders.
closing this for now but feel free to reopen tickets if you have further questions.
