### ISSUE TITLE
Modifier Stack generates broken meshes

### ISSUE THREAD

**Issue by dikadk** [mapbox/mapbox-unity-sdk#176]
I tried to create Modifier Stack for Mesh Factory through menu Assets -> Create-> Mapbox ->Modifiers -> Modifier Stack. And it seems to generate broken meshes. I've used MeshGenerationOnTerrain example as well as my own.
DefaultBuildingStack works without any problems.
Unity 2017.1.0f3Personal, MacOS Sierra, OpenGL4.1. MacBookPro 2015

Steps:
1. Open MeshGenerationOnTerrain example scene
2. Create new Modifier Stack for Mesh Factory
3. Add same modifiers as in DefaultBuildingStack
4. Replace DefaultBuildingStack to New Modifier Stack in BuildingVisualizer
<img width="1678" alt="screen shot 2017-07-23 at 1 29 23 pm" src="https://user-images.githubusercontent.com/15266737/28501503-024cc5e2-6fab-11e7-8636-9ebb699f6036.png">

**Comment by brnkhy** [comment]
@dikadk can you try with height modifier being 4th, after polygon and uv modifiers. Ordering matters in the stacks but unfortunately we're not forcing/checking it someway. If it works normally when ordered properly, let's close this and open a ticket for checking/forcing modifier ordering etc

**Comment by dikadk** [comment]
It did worked. Thanks! And opening ordering issue.
