### ISSUE TITLE
layer data not loading fully via script that we edited in mapbox studio.

### ISSUE THREAD

**Issue by Sailendrakc** [mapbox/mapbox-unity-sdk#1762]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2020.2.3f1
  * Scripting Runtime Version: 
  * Scripting Backend: mono
  * Api Compatibility Level:  .netstanderd 2.0
* Mapbox SDK version:  2.1.1
* The platform you're building to: android
* A description of what you're trying to do: 

IN SHORT: I am trying to get property of a dataset that i set in mapbox studio inside unity3d via scripting in runtime.

DETAIL:
 I created a dataset in mapbox studio (poligon dataset). After that i created a new style and went to the layer section and added a tileset based on that polygon dataset. Then I published it and shared it. I copied the link and access token from mapbox studio into the unity. Now I changed the source via script doing (abctractmap.imagelayer.setlayersource(url)). Now when i play, the map was showing my polygon. all good until now. 

 But, I want to extract the info like position, etc about that polygon and want to instantiate custom game object. How to do this? 

What is the approach needed to be taken to instantiate a game object to the position of custom dataset we make in mapbox? 

Please dont say "look at this example" as none of the scripts have any comments nor they make sense until you are elite programmer.  However you can ask to look an example with a direction on how to solve this problem.

 also dont need the exact code, what i need is something like "Get the data from unity tile, there should be 'this' function or "Read data from vectordata and extract using name of layer something like that". 

If my approach is wrong what should be the approach? Also the gameobjects that holds "Unity Tile " Scripts, which are children of gameobject to which abstract map is attached, dont have any sub childrens like your examples do. that polygon is permanently drawn in the tile itself.

Also i am trying to do this via scripting not via editor.

Thnx.
* Steps to recreate the bug if appropriate:
* 
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@Sailendrakc so if I understand it correct, you created polygons in mapbox studio probably with some properties. And you managed to draw them in Unity SDK. but now you are looking for a proper way to spawn objects inside those polygons/areas?

don't hate me for saying this but I think it's similar to `interactive styled vector map` demo scene and parks layer where we spawned trees in `landuse` polygons.
Basically, you can create a gameobject modifier (`SpawnInParkmodifier`in layer mentioned above) which will receive every feature in the layer one by one. Then for each feature, you can check the points/polygon and spawn anything inside, on, around etc. 

`that polygon is permanently drawn in the tile itself.`
ah I think I got it now, you are seeing that polygon in imagery, not as a vector mesh. You used the style id in `image` section of the map so SDK downloaded and final imagery and applied that on terrain. What you need to do is, use your tileset id in `mpa layers` section.
<img width="351" alt="Screen Shot 2021-04-16 at 12 07 52 PM" src="https://user-images.githubusercontent.com/1465390/115001527-64f0d380-9eac-11eb-94f6-99185f58fb7c.png">

**Comment by Sailendrakc** [comment]
Yes, i eventually found out we can use game object modifier. Without proper docs and commenting it was difficult to find at first.

And thank you very much for your reply. Yes the problem was it was part of mesh (imagery), i changed it to tileset and it worked.
