### ISSUE TITLE
Black tiles without map data in Examples

### ISSUE THREAD

**Issue by otterpop1991** [mapbox/mapbox-unity-sdk#1763]
Hi, I'm currently on:
Unity Version: 2020.3.0f1
Mapbox SDK: mapbox-unity-sdk_v2.1.1
I'm building on and to my Macbook Pro (OS 10.13.6)

I imported the mapbox-unity-SDK package to Unity, then went to "Mapbox -> Setup" and entered my Token, which was "Valid".  Then, when I try to click on the example Scene, "Location-Based Game" and Play it in Editor mode, it just shows black tiles for the mapped area (picture attached).  It remains like this even when I change the lat,lon coordinates.  I didn't edit the SDK at all, so I figure that it must be something obvious that I'm overlooking.  

I've also noticed that the Warning, "Remote device not connected via 'Unity Remote" comes up, but figured this may be unrelated since I am not building to IOS/Android.  Any assistance would be greatly appreciated!
![Screen Shot 2021-03-23 at 4 49 50 PM](https://user-images.githubusercontent.com/81276217/112247802-04e27680-8bf9-11eb-81e3-db5160f31dfb.png)

**Comment by brnkhy** [comment]
Hey @otterpop1991 is this happening on all demo scenes? Looks like it's not able to connect server and download images for some reason. I would suggest checking `zoomablemap` demo scene for example, if that also has same problem it's probably due to network somehow.

**Comment by dinukapj** [comment]
We have the same issue. All demo scenes are 'blacked out' and not loading on iOS targeted project (MapBox SDK 2.1.1)

**Comment by dinukapj** [comment]
Just solved it by changing the access token
