### ISSUE TITLE
Mapbox costum style not updating. Using '/draft' also not working.

### ISSUE THREAD

**Issue by Sailendrakc** [mapbox/mapbox-unity-sdk#1764]
_Note: If this is a bug or support ticket, please provide the following information:_
 Unity version: 2020.2.3f1
 Scripting Runtime Version:
 Scripting Backend: mono
 Api Compatibility Level: .netstanderd 2.0
 Mapbox SDK version: 2.1.1
* The platform you're building to: Android
* A description of what you're trying to do: When i change the custom style in mapbox studio and publish it. The changes are not reflected in the unity editor. Even after clearing cache in "Mapbox > clear file cache". Also appending '/draft' is not working as told in the previous issue #1364.
* Steps to recreate the bug if appropriate: Create a custom style in mapbox and use it in unity3d. Now make some changes in style and publish again. That is not reflected in unity editor. When i build it and run it in android it is updated. 
* Links to your logs are also helpful:

**Comment by Amrazyan** [comment]
@Sailendrakc how you manage to fix this
