### ISSUE TITLE
How to make a game like PokemonGO in first person (and not top down perspective with only map showing)

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-unity-sdk#1767]
There is no tutorial on your website about making a game like Pokemon GO. I want to spawn 3D objects at a GPS location and see them in front of my android camera and not on a map. How do I do that? Is that even possible using your Unity plug-in. You need to clarify whether his can be done using mapbox and, if yes, how?

**Comment by brnkhy** [comment]
@iAmJuan550 our AR components and support is admittedly lacking at the moment. We are focusing more on visualization and performance than AR so I won't be able to help much :(
