### ISSUE TITLE
Why don't you guys have more detailed tutorials on doing very basic things?

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-unity-sdk#1769]
I have searched all over the internet and found only two tutorials. Your documentation also doesn't explain very basic stuff like spawning something on a map such that it appears in front of the user holding the android phone (in first person). When are you going to upload tutorials?

**Comment by brnkhy** [comment]
@iAmJuan550 I'm afraid most of the tutorials are updating and lacking at the moment. There probably won't be new ones any time soon, especially on AR. I'm sorry :(
