### ISSUE TITLE
Will object spawned on map also appear in front of android camera?

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-unity-sdk#1770]
If I put an object on a map, will it also appear in front of the android camera? This is not explained in any of your documentation.

**Comment by Markovicho** [comment]
What kind of application are you building ? It seems you're refering to augmented reality via ARCore ? I don't think anyone can help you out with so little information.

**Comment by ghost** [comment]
I solved my problem by  switching to ARCore on Android.
