### ISSUE TITLE
How do you get the Map Bounds

### ISSUE THREAD

**Issue by HenryBrown0** [mapbox/mapbox-unity-sdk#1772]
* Unity version: v2019.4.12f1
* Mapbox SDK version: v2.1.1

Is there an equivalent `getBounds()` method to the JS SDK? https://docs.mapbox.com/mapbox-gl-js/api/map/#map#getbounds

I have a static map that the player can move around. I need to get the bounds to make an HTTP request to get data points to place onto the map. 

Thanks

**Comment by MRKDaGods** [comment]
I have written these 2 methods to get the min and max lat, lng of a static map visible on screen where `m_Map` is an `AbstractMap`
```
        Vector2d GetMinGeoPos() {
            return m_Map.WorldToGeoPosition(Camera.main.ScreenToWorldPoint(new Vector3(0f, 0f, Camera.main.transform.localPosition.y)));
        }

        Vector2d GetMaxGeoPos() {
            return m_Map.WorldToGeoPosition(Camera.main.ScreenToWorldPoint(new Vector3(Screen.width, Screen.height, Camera.main.transform.localPosition.y)));
        }
```

You can get the width&height of the region in lat, lng by subtracting both methods, `GetMaxGeoPos() - GetMinGeoPos()`
I hope the above information helps you, good luck!

**Comment by brnkhy** [comment]
@HenryBrown0 there isn't a built in `MapBounds` method as you described but especially if your map is static, you should be able to convert any unity space point to latlng using `AbstractMap. WorldToGeoPosition` as @MRKDaGods suggested.
I'm taking a note for `Bounds` method though, would be useful. Thanks a lot!
I'll close the ticket but feel free to ask if you have any follow up questions.
