### ISSUE TITLE
Is the Mapbox Unity SDK still being worked on? 

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#1774]
It doesn't seem to be released any new versions, and very little action in this repo. Is this still being worked on, or is it basically dead?

**Comment by brnkhy** [comment]
Hey @JorgenEngenNapstad !
SDK is still improving but indeed it's in a little unorthodox way. We haven't launched a new version for a long long time now and there probably won't be a new one soon.
We are working on SDK though, especially on the performance issues. You can check those from this branch; https://github.com/mapbox/mapbox-unity-sdk/tree/performance

That's a minimal branch (a lot of features cut off) that changes almost everything from original SDK but has huge performance gains on imagery&elevation maps. Vector performance work will follow soon.

**Comment by JorgenEngenNapstad** [comment]
Thanks for your reply @brnkhy. We use the Mapbox Unity SDK extensively in one of our software products, and it's a bit scary when there seems to be little action. It would not be good for us if it is discontinued.

**Comment by brnkhy** [comment]
@JorgenEngenNapstad 
`We use the Mapbox Unity SDK extensively in one of our software products, and it's a bit scary when there seems to be little action.`
I would strongly suggest keeping in touch with Mapbox (sales etc) in that case. I am very actively working on it but future of the SDK, expectedly, depends on other things like interest in it, user count etc.
