### ISSUE TITLE
How to get width of a particular road? Image attached to see the issue.

### ISSUE THREAD

**Issue by Sailendrakc** [mapbox/mapbox-unity-sdk#1775]
Hello, 
I am trying to perform navigation in unity3d. I looked into traffic and direction scene and direction scene. There seems to be no way of knowing the width of road in order to set the width of mesh (navigation). 

This is the screenshot. You can clearly see the road is fat and big. How to adjust this? 

Main Question: **Where is the data related to the width of the road?**

#1715 says there is no data related to road width in vector data. Has this been fixed yet? @brnkhy 

![image](https://user-images.githubusercontent.com/46669902/114863173-c1171180-9e32-11eb-93e9-9e759bd8af25.png)

**Comment by brnkhy** [comment]
Hey @Sailendrakc! I'm afraid there is simply no data related to real road width or lane count etc. It's always based on estimates and/or road type. This is not a SDK thing, as I mentioned there is no data for it so I don't expect that to change any time soon either :(

**Comment by Sailendrakc** [comment]
Is there any workaround that you suggest ?

 I mean user can always zoom in or out so the width of road always changes. How do other professional project handle so that the navigation overlay in road matches the road and does not overflows? 
Screenshot from google maps attached to see what am i expecting. (Blue line perfectly matching with road).

Thanks!

![Screenshot_2021-04-16-20-13-59-687_com google android apps maps](https://user-images.githubusercontent.com/46669902/115010225-7f4ca080-9ef0-11eb-96d6-449745b230cd.jpg)
