### ISSUE TITLE
How to zoom out the map in unity

### ISSUE THREAD

**Issue by syedali1621** [mapbox/mapbox-unity-sdk#1776]
My project is displaying the map with too much zoom that is a reason my places markers are not visible because they are set as km, so they are far and not displaying. I want to know how to zoom out the map kindly let me know.

Thank you
<img width="186" alt="Screen Shot 2021-04-23 at 5 53 40 PM" src="https://user-images.githubusercontent.com/14038234/115846584-048a0500-a45d-11eb-80c8-c6d81b708319.png">

**Comment by MRKDaGods** [comment]
the `AbstractMap` class contains the method `public virtual void UpdateMap(float zoom)` where zoom is a float in the range 0-21, simply call it with the desired zoom level

**Comment by syedali1621** [comment]
Thank you for your answer.
I am trying to call it from another script but nothing is happening, Am I doing anything wrong?

 mapboxMap.UpdateMap(center, 5f);

**Comment by brnkhy** [comment]
@syedali1621 it can be a number of different things really. I think you are using a render texture and you have a map& camera somewhere else, is that correct? You should have `AbstractMap` component on that map so you should be able to set zoom level easily there. Then you camera frustum might be too narrow?

**Comment by syedali1621** [comment]
Thank you all, my issue is solved. It takes some time to change map zoom.
