### ISSUE TITLE
Fix C# warnings.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#178]
When you open the SDK in Unity it will give out a ton of warnings, around 40 or so.

In general most of the warnings are harmless, e.g. `Variable X is assigned but never used` etc... But this is still a quite big problem that should be dealt with.

The issue with this is:

1. The warnings are annoying.
2. Your own warnings can and will get lost between all of Mapbox's warning.
3. They are **really** annoying.

I've usually just "cleaned up" (e.g.: `#pargma warning disable 414`) before updating my project, but it should be solved at the source.

So with that in mind... Most of the warnings can be easily fixed, delete a variable here, add a `#pragma` defenition there... But a few warnings are not in the actual mapbox project, but in it's dependencies.

More precisely, 4 are in the [vector-tile-cs](https://github.com/mapbox/vector-tile-cs) project and two are in the [Mapbox.IO.Compression](https://github.com/mapbox/Mapbox.IO.Compression-unity) project (off-topic observation, MB has like 23 pages of repositories on GitHub! Wow, talk about giving back to the community!)

I'm hesitant to fix this & submit a pull request myself, as I don't know what you guys left unfinished and will come back to at some point.

Is there anything I can do to help? Using common sense and just clean everything up? I'm probably one of the few devs out there who loves a good code-cleanup job at the end of the day.

Probably not a priority, but seeing as how version 1.0 is already out, this should probably be fixed asap, preferably before the next official release IMO.

**Comment by mihakrajnc** [comment]
Pull requests for vector-tile-cs and Mapbox.IO.Compression for completeness:

- https://github.com/mapbox/vector-tile-cs/pull/33
- https://github.com/mapbox/Mapbox.IO.Compression-unity/pull/1

**Comment by david-rhodes** [comment]
@mihakrajnc You are absolutely right--we need to fix these. We'll try to address these before the next release. Cheers!

**Comment by BergWerkGIS** [comment]
merged https://github.com/mapbox/mapbox-unity-sdk/pull/182
