### ISSUE TITLE
Is the project abandoned or new updates are planned?

### ISSUE THREAD

**Issue by Mitko88** [mapbox/mapbox-unity-sdk#1781]
I've seen that there are no updates for long time. For example, do you plan to have new updates this year? If not, it is better to have this in mind. 

I think the project is great, but without new updates it won't be used.

**Comment by gangstageek** [comment]
I would like to know the same. I plan on launching an app in the next couple of months.

**Comment by brnkhy** [comment]
@Mitko88 @gangstageek official releases slowed down as you noted, but we are stille working on the sdk, especially on the performance lately. 
You can check some of that in this branch; 
https://github.com/mapbox/mapbox-unity-sdk/tree/performance

and there is some discussion about it here; 
https://github.com/mapbox/mapbox-unity-sdk/issues/1671
