### ISSUE TITLE
How to get the area of a polygons dataset entry

### ISSUE THREAD

**Issue by naseWei** [mapbox/mapbox-unity-sdk#1789]
Hi everyone, 

I'm currently looking for a way, to get the area a polygon dataset entry is covering. In the mapbox dataset editor online i can actually see the value for it. Here an example:
![image](https://user-images.githubusercontent.com/84955668/123209440-dfe3f500-d4c0-11eb-80fb-0038ba0086d0.png)
I found the turf.js, which can be used for js applications, but i'm not sure if this works in unity as well. 
Maybe I'm just missing it. Any suggestions?

**Comment by MRKDaGods** [comment]
Try converting the polygon's geo coords to mercator meters then follow the approach provided here: https://stackoverflow.com/questions/2034540/calculating-area-of-irregular-polygon-in-c-sharp

**Comment by brnkhy** [comment]
we don't have such a method in yet but I think using lat/lng based calculation would be better than mercator based one. 
quick googling yielded this;
https://stackoverflow.com/questions/2861272/polygon-area-calculation-using-latitude-and-longitude-generated-from-cartesian-s
