### ISSUE TITLE
Personalized Location Point 

### ISSUE THREAD

**Issue by SergioGarciaC** [mapbox/mapbox-unity-sdk#1790]
**HELP!!!**

Hello Guys, i was integrated the mapbox-unity-sdk and used the example of Directions but , i want to create a personalized location point , to configurate "Point A (myself) to Point B ( any location with coordinates)

**Comment by brnkhy** [comment]
you can check `Directions.cs` and a sample script using it `AstronautDirections.cs`. Latter uses two custom points for query so you can change those points easily.
Hope that helps!
