### ISSUE TITLE
[Location-based game] Buildings have 0 height and their textures not rendering

### ISSUE THREAD

**Issue by mniebieski** [mapbox/mapbox-unity-sdk#1791]
Hi

I'm trying to add height to buildings in the default Location Based Game that comes together with Unity SDK. I am following the video form Mapbox: https://www.youtube.com/watch?v=-RMdkG0VL4A.

I have setup the Map as follows:
![image](https://user-images.githubusercontent.com/36455861/124276922-b708d300-db44-11eb-8294-edb6a12e1a71.png)

I have added a feature regarding building height, as per the video:
![image](https://user-images.githubusercontent.com/36455861/124276978-ca1ba300-db44-11eb-8df8-daaf535a6eef.png)

RESULT: Nothing happens (building dont have height, and building textures are not loaded, screenshot below).
![image](https://user-images.githubusercontent.com/36455861/124277064-eae3f880-db44-11eb-9c00-6db563a7bf24.png)

Also, I get an error in my console:
![image](https://user-images.githubusercontent.com/36455861/124277230-1b2b9700-db45-11eb-9e58-1fb9836314f8.png)

Can you please advise on next steps? What am I doing wrong?

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2020.3.13f1
  * Scripting Runtime Version: what is this?
  * Scripting Backend: Visual Studio 2019
  * Api Compatibility Level: what is this?
* Mapbox SDK version: 2.1.1.
* The platform you're building to: Android
* A description of what you're trying to do:
I'm trying to add height to building in the default Location Based Game that comes together with Unity SDK.

* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by MRKDaGods** [comment]
The unity version you are currently using is having problems processing vector tiles sent by the mapbox server, and that's why you're experiencing such problem. Using an earlier Unity version such as 2019.x should fix it

**Comment by MRKDaGods** [comment]
Same as #1778

**Comment by mniebieski** [comment]
Thx

Wow, so the issue is almost 3 years old and they didnt update the SDK? If that's how Mapbox approaches all their products, then I'm not inpressed.

**Comment by brnkhy** [comment]
Hey @mniebieski,
I tried to explain what's going on in other ticket, I'm afraid we'll (most likely) have to wait for Unity fix for this.
I'm closing this one if you don't mind (other ticket will be open).
