### ISSUE TITLE
Complier error

### ISSUE THREAD

**Issue by shanshan1405** [mapbox/mapbox-unity-sdk#1794]
When i use Unity2020.3.12, the Mapbox unitypackage have no a toolmenu like i use Unity2020.4.40 with mapbox-unity-sdk_v2.1.1.unitypackage.

![image](https://user-images.githubusercontent.com/57471768/126112451-0a26f97e-ac81-46f1-adf2-c53754114867.png)

![image](https://user-images.githubusercontent.com/57471768/126112391-3d9c8451-63d0-4b0a-92a1-af1f15a4e267.png)

And when i use play mode by Unity2020.3.12, it shows a complier error:

![image](https://user-images.githubusercontent.com/57471768/126112556-fefe34a1-c5db-4e53-82e0-fca8c7e24810.png)

What's the reason?

**Comment by Markovicho** [comment]
Can't confirm that anything is wrong combining Unity 2020 LTS and Mapbox_2.1.1. @shanshan1405 But i think to get help you need to provide detailed logs of the compile errors mentioned in your last screenshot. Open Unity Console and copy everything you can find refering the issue

**Comment by brnkhy** [comment]
@shanshan1405 what's the error? a common, similar issue is caused by AR folders for example so we suggest deleting all AR folders but I think you already did that with the other unity version, right?
