### ISSUE TITLE
Features not loading : Curl Deprecation Error: Unrecognized content encoding type

### ISSUE THREAD

**Issue by Markovicho** [mapbox/mapbox-unity-sdk#1798]
* Unity version: 2020.3.15f
* Mapbox SDK version: Performance branch
* The platform you're building to: Android
* GIT changeset: 61ca05a (28th July)

@brnkhy 

Console is throwing several curl issues when loading map and building layers are not working anymore (maybe not related to that issue but i think it's worth to notice):

`Curl error 61: Unrecognized content encoding type. libcurl understands identity content encodings.`

It seems like the maptiles are still loaded correctly but no features can be loaded from remote. I also tried to disable compression for map tiles but no success.

Some information from a unity thread:

`The issue seems to be that from Unity 2021.1.3f1, UnityWebRequest no longer supports data compression. The error "Curl error 61: Unrecognized content encoding type. libcurl understands identity content encodings." states that it only accepts the identity content encodings, other encoding such as "gzip" may not work, this does not only apply to PlayFab's SDK, but also other websites that uses data compression. Please ask the Unity team for help and see if this is intended or a bug from Unity side.`

**Comment by Markovicho** [comment]
I don't know if this is making any sense but i used "re-import all" for the project and it seems to work be working again oO

But anyways the above deprecation could be an interesting point regarding tile-loading and compression

**Comment by Markovicho** [comment]
Reverting back to Unity 2020.3.7f and using "Re-Import All" solves the issue for now. But it seems that there is an api change included between 2020.3.7 and 2020.3.15 which triggers this deprecation issue

**Comment by brnkhy** [comment]
Hey @Markovicho,
there's a ticket for this issue here; https://github.com/mapbox/mapbox-unity-sdk/issues/1778
I'm afraid this is a Unity issue and we have no chance other than to wait for their fix :(
