### ISSUE TITLE
Android Build Error: 'AbstractMapVisualizer' does not contain a definition for 'GetInactiveTiles'

### ISSUE THREAD

**Issue by Markovicho** [mapbox/mapbox-unity-sdk#1799]
- Performance Branch
- Android Build Plattform

@brnkhy 

`Assets\Mapbox\Unity\CustomLayer\ImageFactoryBehaviour.cs(98,44): error CS1061: 'AbstractMapVisualizer' does not contain a definition for 'GetInactiveTiles' and no accessible extension method 'GetInactiveTiles' accepting a first argument of type 'AbstractMapVisualizer' could be found (are you missing a using directive or an assembly reference?)`

is still thrown when building the app for android plattform. No device needed to reproduce. It's okay to uncomment the precompile flags, but the fix should be easy. 

![image](https://user-images.githubusercontent.com/11967926/127441236-f057dd87-cb8a-42fe-a931-63065aab5286.png)

**Comment by brnkhy** [comment]
@Markovicho ah I think I misunderstood this before, removed the directive now and it should be fine. Fix pushed.

**Comment by Markovicho** [comment]
looks fine :-) thx!
