### ISSUE TITLE
AR camera shows black screen.

### ISSUE THREAD

**Issue by ruymaster** [mapbox/mapbox-unity-sdk#1803]
* Unity version: 2019.4.12f1
  * Scripting Runtime Version: 
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: 29
* Mapbox SDK version: 
* The platform you're building to: Android
* A description of what you're trying to do: I am trying to make AR game using this SDK.
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by Markovicho** [comment]
@ruymaster 

The AR part of mapdox sdk is deprecated and outdated. It's based on legacy AR-plugins for ARKit/ARCore which needs to replaced by Unity's ARFoundation in the future. We ran into the same situation and get rid of the whole AR folder in mapbox to avoid compatibility issues with other plugins. If you just want to show AR-Content at GPS-locations i can really recommend this plugin : https://assetstore.unity.com/packages/tools/integration/ar-gps-location-134882#releases

**Comment by brnkhy** [comment]
@ruymaster as @Markovicho noted, AR features are outdated at the moment and we cannot suggest using them. Sorry about this.
