### ISSUE TITLE
Module communication

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#181]
This is a generic problem with all somewhat modular systems. We also need something for this but our case, for now, is quite limited. 
At this point, our biggest problem is sharing some properties/settings between modules. 
i.e. We have 2-3 checkboxes to enable satellite imagery for roofs at the moment as modules cannot communicate. What should have been is just one checkbox in ImageFactory and other smaller modules reading&respecting that.

I didn't want to do a static class/structure, mainly because statics. I also think it would be an overkill to implement something like message bus for this (which I personally love and we might get in the future). 

What I'm thinking about is something with two tree iteration phases. first one is PreInit where everyone sets some flags and values they want to share inside a `WorldProperties` object. Second is Init where this object is sent to all modules yet again, to cache&use this time.

Basically this;
```
foreach (var factory in _factories)
{
	factory.PreInitialize(wp);
}
foreach (var factory in _factories)
{
	factory.Initialize(wp, fileSource);
}
```

Obvious problem here is that we're introducing a new dependency in WorldProperties class. Also everything inside WorldProperties class is hardcoded at the moment and that's horrible (again open/closed principal). That's not hard to fix but still, a problem for now.

Some use cases here might be;
-one checkbox for use satellite imagery for roofs
-sending world scale down to modifier stack for scaling #171 
-modifier synchronization?
-enable/disable snap to terrain modifier depending flat/height terrain
-enable/disable uv modifier depending satellite imagery for roofs setting
-move some basic settings to higher in hierarchy (map viz?) 

I'm open to suggestions for this. We can totally do message bus or something else as well.

cc @david-rhodes @isiyu

**Comment by david-rhodes** [comment]
@brnkhy we good to close in favor of #268?

**Comment by brnkhy** [comment]
@david-rhodes that's different now, we probably should keep this open for message bus tests&implementations.
