### ISSUE TITLE
Installing Performance Branch Guide

### ISSUE THREAD

**Issue by RomanAtBrief** [mapbox/mapbox-unity-sdk#1813]
Hey guys,

After one night trying to find a way to install Performance branch, I think I got it to work. If you need step by step guide, please see below. @brnkhy please correct me if I am wrong.

1. Download zip file [https://github.com/mapbox/mapbox-unity-sdk/tree/performance](url)
![Screenshot 2021-09-14 at 11 45 21](https://user-images.githubusercontent.com/15308495/133247458-02ee0785-f381-414b-b593-9d63208677dd.png)

2. Open project file using Unity Hub
![Screenshot 2021-09-14 at 11 48 52](https://user-images.githubusercontent.com/15308495/133247527-bf321063-fa54-44cb-9962-7d8c09c83614.png)

3. Insert Access Token 
![Screenshot 2021-09-14 at 11 52 09](https://user-images.githubusercontent.com/15308495/133247567-977d2aed-720a-4f75-979e-cd58aaec2a19.png)

4. Install Universal RP
![Screenshot 2021-09-14 at 11 54 08](https://user-images.githubusercontent.com/15308495/133247601-e69e2389-7900-460e-9cef-79c629686fde.png)

5. Assign MapboxURP Asset
![Screenshot 2021-09-14 at 11 58 52](https://user-images.githubusercontent.com/15308495/133247636-77c9e47a-6494-4277-9970-63c463206db0.png)

6. Choose ZoomableMap Example and hit play 
![Screenshot 2021-09-14 at 11 59 31](https://user-images.githubusercontent.com/15308495/133247657-a2425cb3-41fb-4f17-b6f1-b15944960a96.png)

In some cases you might get a pink Map after you hit play.

It might be two things:
1. You haven't installed URP
2. Tile Material in Abstract Map is Default. You need to choose CustomLayerElevatedTerraineMaterial

**Comment by brnkhy** [comment]
@TheBriefTeam thanks a lot for the write-up! 
As you noted URP is the default renderer for this branch and in case you are upgrading from an older version of the map, you'll most likely lose your map settings and have to recreate them.

**Comment by cappelnord** [comment]
Hello quick question: Is it also possible to use the performance branch without URP/the classic 3D renderer? If so what would be the steps needed to do?

**Comment by duartebarbosadev** [comment]
Is the performance branch the latest version of MapBox for Unity?

**Comment by duartebarbosadev** [comment]
Why do I get only pink buildings?
![Screenshot 2021-11-13 at 19 20 57](https://user-images.githubusercontent.com/13065435/141656535-11630e4a-2292-46f4-a2b1-cc671dfa5cf4.png)

**Comment by tplester** [comment]
Anyone been able to get the branch working on Unity 2021.3? The editor just crashes when I press play on the ZoomableMap example. The error according to the crashdump is in Unity.exe!DownloadHandlerTexture::OnFinishReceiveData(void) which apparently has to do with this issue: https://issuetracker.unity3d.com/issues/downloadhandlertexture-crashes-if-it-downloads-invalid-texture-data

After some more testing, it doesn't happen if I have Map Layers->Data Source set to None, so it must be something in the Vector data

**Comment by RomanAtBrief** [comment]
I think you would have to test what works. Mapbox for Unity is not supported anymore and some confirmed employees where moved to other tasks almost two years ago.
So I would not recommend it for any production work unfortunately
