### ISSUE TITLE
How to change Abstract Map Parameters at Run time with separate Monobehaviour 

### ISSUE THREAD

**Issue by RomanAtBrief** [mapbox/mapbox-unity-sdk#1814]
I have a separate Monobehavior script. MapController.
I want it to have a bunch of public functions to control the map.
For example UI button will switch on/off 3D buildings, or Drop down menu to choose different map styles.

I found this documentation 
https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.IImageryLayer.html

Can anyone give me a hand how to use it? Looks like all properties are only "get" and functions are private?

**Comment by RomanAtBrief** [comment]
So basically this does not work
abstractMap.ImageLayer.SetLayerSource(ImagerySourceType.MapboxSatellite);

**Comment by brnkhy** [comment]
Hey @TheBriefTeam !
I think we solved this via DM? I'm closing it, please feel free to reopen if I remember wrong. 🙏

**Comment by RomanAtBrief** [comment]
Yes.All good thank you for help
