### ISSUE TITLE
Mapbox menu not appearing in Unity 2021.1.21f1 after importing package #1349

### ISSUE THREAD

**Issue by Florian-crg** [mapbox/mapbox-unity-sdk#1818]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2021.1.21f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: mapbox-unity-sdk_v2.1.1.unitypackage
* The platform you're building to: MAC
* A description of what you're trying to do: Import mapbox unity and use it.
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by RomanAtBrief** [comment]
Hi Florian-crg,

Unfortunately you probably will not get any response anytime soon from Mapbox team.
Mapbox v2.2.1 does not officially support lates Unity versions.
I haven't tried 2021 yet, but it works more or less in 2020. With lots of warnings and errors. 

You can't try Performance branch it works faster and has support for URP.

**Comment by brnkhy** [comment]
@Florian-crg well error log would have helped for sure but your problem is most likely due to outdated AR folders. If you are not planning to use AR, please try deleting all Mapbox AR folders and it should compile.

**Comment by ashokdube** [comment]
Great
