### ISSUE TITLE
Manually requesting tiles with SKU token

### ISSUE THREAD

**Issue by hilkojj** [mapbox/mapbox-unity-sdk#1819]
Hey,
I'm using the Mapbox SDK for Unity (v2.1.1) and I'd like to manually retrieve [vector](https://docs.mapbox.com/api/maps/vector-tiles/#retrieve-vector-tiles) and [static](https://docs.mapbox.com/api/maps/static-tiles/#retrieve-raster-tiles-from-styles) tiles from the Mapbox API with `UnityWebRequest.Get()`.

This works fine with requests that look like this for example: `https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/10/533/334.vector.pbf?access_token=MY_API_KEY`. But I noticed these requests are billed _differently_ than the requests that the Mapbox SDK internally does.

My manual requests are billed _per request_, while the SDK's requests are billed _per monthly user_. This is because the SDK adds an additional URL parameter to their requests that enables the mapbox API to track the session/user. This parameter is called the [SKU token](https://docs.mapbox.com/help/glossary/sku-token/) and is added to the request urls like this: `&sku=SKU_TOKEN`.

I noticed I can retrieve the current SKU token in Unity by calling [`MapboxAccess.Instance.Configuration.GetMapsSkuToken()`](https://docs.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.MapboxConfiguration.html#methods).
Now I have two questions:
1. Is it okay if I use this method and add the `&sku=` parameter to my manual API requests? So that all my manual requests are billed the same way the requests of the SDK are billed.
2. Can I be sure this `GetMapsSkuToken()` method stays public and available for use in the future?

I hope you can answer these questions,
Thanks in advance :)

**Comment by brnkhy** [comment]
Hey @hilkojj !
I'm afraid manually using SKU library like that is definitely not suggested or supported. The library is also planned to change in the future.

what's your use case here? If you want to process data yourself and if you are an advanced user/developer, I might suggest checking `performance` branch in this repo. It's a big overhaul mainly aiming better performance but we are also trying to provide better customizability. It's still heavily work in progress though and definitely not finished product. (We started vector layer only last month though, it's working but not polished/tested etc)

**Comment by hilkojj** [comment]
Thanks @brnkhy for your reply.

Our use case is as follows:
We want to display a zoomable map with vector tiles, and optionally static or satellite tiles. The map should be highly customizable and we should be able to place things on the map (like detailed 3D buildings, from other sources than Mapbox). Also, being able to display maps/layers from other sources than Mapbox (ArcGIS for example) in the map viewer _would be nice_.

I found that the (zoomable) map that the Mapbox SDK offers is not performant enough, and customization is quite cumbersome.

It sounds like the `performance` branch you're talking about is trying to solve these issues, however; we need a production-ready solution. But I'll definitely check it out, thanks!

So for now I am working on my own map-viewer in Unity, and it fetches the tiles from the Mapbox API with my `access_token` and `sku` token which I get from calling `MapboxAccess.Instance.Configuration.GetMapsSkuToken()`.

So now I have these 2 questions:
- I understand from your reply that using the `sku` token like that is not suggested, but is there something (like the Terms of Service for example) that would be holding us back from using it? The method to get the `sku` token is publicly exposed, so I would assume I can use it.
- Do you have any estimate on when we can expect the `performance` branch to be a (near) finished product? Because it sounds promising.

Thanks in advance.

**Comment by brnkhy** [comment]
Hey @hilkojj,
Indeed `performance` branch is a work-in-progress. There are some popular store apps using it at the moment but still it's definitely not a finished product yet. Image part is there but we are on the early stages for vector part.

- I'm afraid I can't answer ToS questions, as a developer I don't know much about ToS myself and wouldn't want to misguide you. I would suggest asking this to mapbox support.
- hard to say because it's impossible to definite `finished`. at the moment I'm happy with image/terrain layer and started working on vector layer. then there'll be a lot of core quality improvements I guess. like a real quad tree solution.

a custom solution might be a good idea as well and you can always use our code for reference/guidance if/when necessary.

**Comment by hilkojj** [comment]
Hey,
Thanks for your help and suggestions. I understand you cannot answer ToS questions.
I think this issue can be closed for now.
