### ISSUE TITLE
How do i use this in a plain c# project ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#1820]
Im developing a server for my unity client... however i need to use mapbox on my server instead of unity... the server is written in c#. 

How do i use this on my server ? Any guides ?

**Comment by brnkhy** [comment]
@genaray you can't as almost everything, from data fetching to image processing, relies on a Unity library. also I don't think user ToS would allow such a usage of mapbox services (use it on you server and distribute yourself) but you should talk to support on that.
