### ISSUE TITLE
Mapbox for UWP in Unity 2019.4

### ISSUE THREAD

**Issue by made3** [mapbox/mapbox-unity-sdk#1823]
Hello everyone,

is it possible to get Mapbox working on the HoloLens 2 in Unity 2019.4? As far as I found out, Unity does not support the .net scripting backend anymore. So I have to use the IL2CPP scripting backend, which on the other hand, is not supported by Mapbox.
Are these assumptions correct or is there a way around it? 
I can build and deploy my project but I don't see the map on the HoloLens 2.

Thank you already in advance!

**Comment by brnkhy** [comment]
Hey @made3 
I haven't tried UWP for a long time now I guess and I remember it wasn't the easiest but I believe SDK should work with IL2CPP, have you tried that?
If you haven't already, I would also suggest checking other UWP tickets in issues section, I remember some people discussing and solving their problems.
Hope that helps, sorry I couldn't help more.

**Comment by made3** [comment]
> 
> 
> Hey @made3 I haven't tried UWP for a long time now I guess and I remember it wasn't the easiest but I believe SDK should work with IL2CPP, have you tried that? If you haven't already, I would also suggest checking other UWP tickets in issues section, I remember some people discussing and solving their problems. Hope that helps, sorry I couldn't help more.

Hello @brnkhy 
Thank you for the answer! I tried it with IL2CPP, the map only showed in the Unity editor but not on the HoloLens. Then I found [this issue from over a year ago where you answered that the SDK does not support IL2CPP](https://github.com/mapbox/mapbox-unity-sdk/issues/1644#issuecomment-658984729) and [since Unity 2019 the IL2CPP support ](https://stackoverflow.com/a/58275477) has been removed. 
But I have not found any issue here regarding any Unity 2019+ version sadly. And going back to a 2018 version is not possible for me.

**Comment by brnkhy** [comment]
@made3 oh you made me doubt myself for a second but I'm only quoting original posters sentences there :) then I follow with `I believe this is just for Hololens builds. IL2CPP shouldn't be a problem on other platforms.`
I don't think IL2CPP should be a problem itself but yes I remember Hololens users had problems with some other stuff in the past (for example external dll settings was a thing at some point). 
Since I never used hololens before, I'm not able to help much but are you able to at least get a log/error or something?

**Comment by made3** [comment]
@brnkhy Ooooh, sorry! :D I misread it in that case. I don't have any logs/errors sadly. I am currently using a self-coded version to download map tiles from OpenStreetMap. And I just need an offline version of that now.
So I pretty much got working what I needed, so I don't think I will continue trying to fix this problem here with Mapbox and the HoloLens, but I might come back to it one day.
Thanks for your help though, I appreciate it!

**Comment by brnkhy** [comment]
@made3 ah cool. hopefully I'll finish with my refactoring and other stuff by then and will be able to help more :) sorry for the confusion and all issues!

**Comment by mertusta1996** [comment]
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
