### ISSUE TITLE
mapbox world scale ar map editör

### ISSUE THREAD

**Issue by mehmetedx** [mapbox/mapbox-unity-sdk#1824]
I am trying to make an AR application where infrastructure data is displayed using mapbox unity sdk. When I use mapbox's old version SDK for world scale ar solution, I don't know how to add my tileset data in mapbox studio in unity. help please
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
[CODING-STYLE.md](https://github.com/mapbox/mapbox-unity-sdk/files/7288602/CODING-STYLE.md)
[CONTRIBUTING.md](https://github.com/mapbox/mapbox-unity-sdk/files/7288603/CONTRIBUTING.md)
[README.md](https://github.com/mapbox/mapbox-unity-sdk/files/7288604/README.md)

* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
@mehmetedx if you already have you data in mapbox (as a tileset), you can use that tileset for data source in `map layers` tab under abstract map object. SDK then will download your vector data and you can do your visualization with settings below that section.

**Comment by mehmetedx** [comment]
I asked a question before. There is no abstract map in mapbox unity version 1.3. I cannot download my vector data (included in tileset) in this version. I know there is no tileset support. I couldn't transfer my work to version after 1.4. help

**Comment by ashokdube** [comment]
Good job
