### ISSUE TITLE
SpawnOnMap doesn't scale correctly on zoomable maps

### ISSUE THREAD

**Issue by jaidhyani** [mapbox/mapbox-unity-sdk#1826]
On Zoomable Maps, zooming doesn't change the scale on prefabs placed with SpawnOnMap, functionally making them Very Big when the map is zoomed in and Very Small when the map is zoomed out (instead of having size fixed to map scale).

**Comment by brnkhy** [comment]
Hey @jaidhyani 
Thanks a lot for the PR!! 🙇 
I'm afraid I will not be able to accept this into current version though as we are working on a separate, new and vastly changed version at the moment (performance branch in this repo). I haven't tested this case on that but I'll try to do that as soon as possible!
I'll close the ticket but leave PR on so anyone needs it can find it there.
