### ISSUE TITLE
Remove previous tiles only when new tiles arrived when zooming

### ISSUE THREAD

**Issue by hrasto** [mapbox/mapbox-unity-sdk#1827]
I am working with Mapbox 2.0.1, and I am very unhappy with the way the tiles load **when zooming**. It seems that tiles are removed as soon as the zoom level snaps to another one, and then there is the default tile material until the new tiles arrive. This is extremely annoying, and I don't see a reason for not leaving the old tiles in the scene until the new ones have arrived. 

I have read the [issue #1701](https://github.com/mapbox/mapbox-unity-sdk/issues/1701) which is related and does not seem to progress. I understand that tile blending is more laborious to implement, but I see this would be a really cheap and quick semi-solution. 

In the meantime I will try to figure it out myself, but I would appreciate any hints and pointers.

**Comment by Markovicho** [comment]
Hey @hrasto,

tile loading in the release 2.0.1 has very poor performance. You should consider switching to the performance branch which includes a major update regarding tile loading. It can take a while until a new official release arrives. Therefore we are also using this branch for our projects. It's a large improvement :-)

Installation guide:
https://github.com/mapbox/mapbox-unity-sdk/issues/1813

**Comment by brnkhy** [comment]
Hey @hrasto !
As @Markovicho mentioned, this is one of the improvements we have been working on `performance` branch. It's a branch mainly focusing performance as the name suggest but has all other sorts of UX improvements as well. Only problem is it's a work-in-progress branch, even the tile management there is far from finished at the moment and will change/improve soon.
If you want to check it yourself though, I would suggest starting with `AbstractMap.TriggerTileRedrawForExtent` and checking TileProviders.
Hope that helps!

**Comment by hrasto** [comment]
Thanks for the replies @brnkhy and @Markovicho ! I tried the performance branch, and it does look much better. 👍
