### ISSUE TITLE
Map Transform Reset in Build

### ISSUE THREAD

**Issue by idClip42** [mapbox/mapbox-unity-sdk#183]
Hello,

My team has been working on a project using Mapbox, creating terrain maps using the AbstractMap.cs script and example resources, and we've run into an issue.

In the Unity Editor, changing the position and rotation of a map object using the AbstractMap.cs script creates a map oriented with the expected new position and rotation when the scene is played.

However, when a Windows Standalone build is made, no matter where the map object is or how it's rotated, the map tiles are always generated flat on the ground, as if the map object were at the world origin with no rotation.
This issue has been found with both my team's current project and with the Mapbox example scene "MeshGenerationOnTerrain.unity" included in the SDK, in both Unity 5.6.1 and Unity 2017.1.

To replicate: Create a new Unity project, import the mapbox-unity-sdk, open the MeshGenerationOnTerrain example scene, move and rotate the "Map" object, and make sure the camera is pointing at it. Playing this scene in Unity should generate the map where one would expect it to be generated, but building it to a Windows Standalone should generate the map back at the origin, facing up.

I haven't found any mention of this issue online so I figured I should say something, but it's also possible that I've just missed something or am misunderstanding the map functionality.
I've never submitted an issue for anything before, and apologize if this was posted in the wrong place or has already been covered elsewhere.

**Comment by idClip42** [comment]
As a follow-up, it appears that Map Tiles are not parented to the map object in the standalone player, as they are in the editor player.

**Comment by idClip42** [comment]
Our workaround was to find the tiles at runtime and parent them to the map object

**Comment by david-rhodes** [comment]
@idClip42 Apologies for this issue. It has been fixed in `develop` (9900c0d728330853d363ca5516b982a0651676b3) and will be included in our next release.

**Comment by idClip42** [comment]
Ah, I see!
Thank you for the quick reply
