### ISSUE TITLE
Modify ReloadMap for array of static points

### ISSUE THREAD

**Issue by lukeholmes1986** [mapbox/mapbox-unity-sdk#1846]
Hey All,

Hopefully this is a simple problem that I have over complicated, the documentation says to raise support requests  on stackOverflow which I have done [here](https://stackoverflow.com/questions/70801228/mapbox-unity-reloadmap-modification-for-static-points) but haven't had much luck with responses so far, my post includes all the scripts and logs (Happy to type these out again if required)

All I am trying to do here is manipulate the built in reloadmap script/prefabs to take in an array of a few static locations (Major cities for testing purposes) and remove any user input, on the reload my static zoom value is reloaded correctly but the camera remains in the same geo location (Just zooms out on the button trigger). Am i missing something simple? Thanks alot!   

Unity version: 2020.3.21f1
Scripting Runtime Version:
Scripting Backend: Mono
Api Compatibility Level:
Mapbox SDK version: Mapbox 2.11
The platform you're building to: Desktop/iOS/Adroid
A description of what you're trying to do:
Reload Map based on an array of various static locations.

**Comment by brnkhy** [comment]
Hey @lukeholmes1986 !
I think I don't understand the use case properly here. You should use `AbstractMap.UpdateMap` to change locations. It's a method that takes latlng and zoom level. so if you have a list of those values, and pass them to abstract map using that method, map should update.

**Comment by lukeholmes1986** [comment]
Hey @brnkhy thanks for coming back to me ! so yes I was in fact over complicating it and thats all i had to do, all working, cheers !
