### ISSUE TITLE
Tile-Texture Preview representation

### ISSUE THREAD

**Issue by Markovicho** [mapbox/mapbox-unity-sdk#1847]
![image](https://user-images.githubusercontent.com/11967926/151361954-5081172e-1025-4b96-9307-9558ba137544.png)

Hey @brnkhy :-)

Since we are using more customized shading on our tiles it's getting more obvious that the preview of loading tiles is visualized by somewhat like an pretty low zoom-level texture showing whole europe. This tile seems to be hardcoded as it's also appearing if we clear the tile cache and never load a tile like that.

I checked out other map services and came to the conclusion that they are keeping the last known texture (stretched / blurry) while the new texutre hasn't arrived.

Is this something which will be sorted out ? Otherwise it would be nice to get an insight on what script we could manipulate to force another loading tile. This could sort of our visual glitch for now :-)

by the way we are using latest commit from performance branch.

best regards and keep up the really solid work !

Mark

**Comment by Markovicho** [comment]
I came across the fact that this is only happening when using custom styles from mapbox studio. I guess that those styles are using api levels which are not compatible with unity sdk. For other sdk's there are warning and dropdowns. What should we configure for mapbox unity sdk?

![image](https://user-images.githubusercontent.com/11967926/151371037-5178f300-60e4-4a83-89d5-3ba7d1e58502.png)

**Comment by brnkhy** [comment]
Hey @Markovicho 
I'm afraid I don't understand the issue. when the system is loading new tiles, it uses a temporarily textures, generally with a much lower quality. and are you having with this temp texture on custom layers?
scene view in your first screenshot looks bugged for example. Street level image and that one below; that's definitely a bug.
does it work fine when you use satellite imagery for example? or how did you set up custom layer? I'll need some more data here :)

**Comment by Markovicho** [comment]
Hey @brnkhy ,

i think we figured out what goes wrong and why it goes wrong by design :-)

- **case 1:** 
for completely unknown tiles mapbox is always loading a fallback texture (world map / europe map) like you can see in below screenshot. But using builtin shaders this texture will never appear. but why ? 
Mapbox is setting the texture-tiling to a very small level which results in showing only a small percentage of the original texture. In this case black. This could also being achieved by simply setting a black texture as fallback but this solution is more dynamic for different color themes of mapstyles. Actually very smart :-)

![image](https://user-images.githubusercontent.com/11967926/152340759-1c3546b5-1a9a-4a00-ab8b-2f569f3bb57f.png)

The reason why our custom shader is showing the glitch mentioned in the first post is that we ignored the tiling and displayed the whole texture...

- **case 2:** Tiles which are already cached: 
Mapbox will show a low res preview until the full-res texture is loaded 



The fact that the tiling of the tile-textures differs between the loading situation should be documented. I think a lot of people writing their own shaders could run into this issue.

anyways thx @brnkhy
