### ISSUE TITLE
I hope to keep the road above the terrain，But they are separated

### ISSUE THREAD

**Issue by kris-w-dev** [mapbox/mapbox-unity-sdk#1852]
* Unity version: 2020.3.3
* Mapbox SDK version: 2.11
* The platform you're building to: mac  |  android

I hope to keep the road above the terrain，But they are separated，The road is not affected by the terrain

What I want to do is create hillsides in areas where there are no roads

<img width="623" alt="image" src="https://user-images.githubusercontent.com/704748/153818742-8484b79b-285a-4e7c-93ae-a1d7d26b8af5.png">

**Comment by kris-w-dev** [comment]
I found the 'snap to terrain' option. It works, but it's not that good

![image](https://user-images.githubusercontent.com/704748/155272744-ed0d5f28-15a8-4b6c-9344-5b644751b556.png)

**Comment by ProYoran** [comment]
Hello, 
Make te roads higher. You can change this under features then select road and then under modeling.

**Comment by brnkhy** [comment]
@wei-kris You can use `smooth line modifier` to increase the point density on lines/roads.
so try custom styling and add `smooth line modifier`, `snap terrain modifier` and `line mesh modifier` under mesh modifiers list and give it a shot.
