### ISSUE TITLE
Citation for the mapbox unity sdk?

### ISSUE THREAD

**Issue by memeQueenPaulaDeen** [mapbox/mapbox-unity-sdk#1854]
I am using the SDK in my thesis and would like to cite it. I currently have:

 @misc{mapbox-unity-sdk, url={https://github.com/mapbox/mapbox-unity-sdk}, publisher={MapBox}} 

Is this sufficient? Is there anything else I should include? Thanks for the help!

**Comment by brnkhy** [comment]
it should be enough for the sdk code.
for the data, you can check the `attribution` prefab inside the SDK, it has correct references.
Thanks!
