### ISSUE TITLE
TileSize vs real world distance not matching

### ISSUE THREAD

**Issue by Markovicho** [mapbox/mapbox-unity-sdk#1868]
**useful informations / sdk version**

* Mapbox SDK version: latest commit on performance branch (using 2D only)

**Settings in AbstractMap**
![image](https://user-images.githubusercontent.com/11967926/168010856-77263c4a-5651-4464-bae5-fb57fa8e3bd3.png)

**Scenario**

- Let's take a place in real world where we exactly know the size. In this case i took a hockeyfield which measures 90 meters in length. This can be confirmed by google maps measure tool (center to field border --> ~45m):
 
![image](https://user-images.githubusercontent.com/11967926/168011263-589d2574-70b3-4170-abee-6bfb6a3e546d.png)

**Test setup**
- Placing an object in mapbox at the center point of the field while visualizing a circle with 45m radius 
- Conversion to match unity-units vs. mapbox tilescale has been applied to the circle localscale
- Calculating the the distance in meters between player position and center of the hockeyfield based on LON/LAT

**Expectation**

- A:standing at the border of the field with player should result in ~90m distance to the circle center
- B:standing at the border of the circle should result in ~45m distance to the circle center
- C:the circle should match the field size exactly encapsulating the borders of the fields long side

**Whats the result?**

![image](https://user-images.githubusercontent.com/11967926/168012122-f0067df7-e313-447d-b1df-c0f1370c988f.png)
![image](https://user-images.githubusercontent.com/11967926/168014306-9adc8b73-5540-4d19-9416-1dd69447f505.png)

- A --> correct
- B --> correct
- C --> the underlying tiletexture is larget than the distance informations from A and B. 

I don't really get the issue here. Is there something fundamentally wrong in my assumptions or is this an bug in the framework? 
@brnkhy @Entryist 

by the way setting the Scaling-Option to WorldScale results in gaps between the tiles:
![image](https://user-images.githubusercontent.com/11967926/168010710-5514c4f2-1846-4b05-938c-27282b1adf73.png)

best regards and thanks in advance for any help

**Comment by brnkhy** [comment]
@Markovicho I should look into distance calculations properly some time but on top of my head, I think the difference here might be `mercator meters` vs `real world meters`. or in other words, impact of `latitude` on the distance calculations. a quick test for this might be trying it somewhere close to equator and then somewhere at extreme latitude.

Is that circle 90 units wide in unity space? maybe you can try to scale it by;
`Mathf.Cos(Mathf.Deg2Rad * (float)map.CenterLatitudeLongitude.x)`
If I'm not wrong, this was the latitude compensation formula 🤔

**Comment by brnkhy** [comment]
@Markovicho can you contact me via email; `baran.kahyaoglu@mapbox.com` or twitter `brnkhy`?

**Comment by Markovicho** [comment]
> @Markovicho I should look into distance calculations properly some time but on top of my head, I think the difference here might be `mercator meters` vs `real world meters`. or in other words, impact of `latitude` on the distance calculations. a quick test for this might be trying it somewhere close to equator and then somewhere at extreme latitude.
> 
> Is that circle 90 units wide in unity space? maybe you can try to scale it by; `Mathf.Cos(Mathf.Deg2Rad * (float)map.CenterLatitudeLongitude.x)` If I'm not wrong, this was the latitude compensation formula 🤔

this did the trick. Fits now perfectly :-) thx @brnkhy
