### ISSUE TITLE
Can't access the mapbox server

### ISSUE THREAD

**Issue by tensmyo** [mapbox/mapbox-unity-sdk#1882]
Hi there

Problem I have 
- map object shows "waiting for location ... "  and showing nothing
- trying to change the location and search "tokyo" and no results.

seems the mapbox asset can not to access the mapbox server.
I appreciate that if you can help me figure out what I missed. 
thank you .

Unity version: 2019.4.40f1
mapbox version: mapbox-unity-sdk_v2.1.1
Imported assets : mapbox only, no AR related packages
Compile: no errors
Access Token: default permissions: Public scopes only
Access token status : Valid.
![image](https://user-images.githubusercontent.com/38588243/193409773-12b43add-735b-4c2b-8812-dc5b73a8daad.png)

**Comment by brnkhy** [comment]
@tensmyo is this same in all demo scenes and are you getting any errors? Is location search working for example or did you set Tokyo latlng yourself? I'm trying to understand if it's whole connection or just imagery.

**Comment by tensmyo** [comment]
Thank you @brnkhy 
It works great now. not really understand why, maybe the version of unity.
