### ISSUE TITLE
Mapbox building:levels property support of Unity SDK

### ISSUE THREAD

**Issue by KAlO2** [mapbox/mapbox-unity-sdk#1921]
Dear Mapbox developers,
I found that some building's height data is not correctly displayed under the Unity SDK (left) but Android SDK (right).
![image](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/d942dd9a-f3af-4590-8021-287946e13502)

I work nearby Shenzhen Kexing Science Park (深圳科兴科学园), and the height data is not correct. I know that 3m is the default height if no one edits and uploads the data.

I've checked OpenStreetMap, the building:levles data is updated 2 years ago.
![image](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/231c03cb-ec63-43b5-a6a1-a9e9948c5fa2)

Mapbox Studio deduces the building's height to be approximate 48m by levels x 3, here levels=16.
![image](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/7765af27-c599-4f66-965f-caf9b3bf17c4)

So I guess that Android SDK has used building:levels info to render correctly (correct me if I'm wrong).
After I debug VectorTile data under Unity (the image below), no building:levels property is found in json, or HighlightBuilds.cs demo (the first image above).
![DZM4OgLBCv](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/8d752cdc-baa4-41c4-ad6d-ff7bbf20af1f)
Here comes the question: Are there any plans to support building:levels property? If Mapbox supports this feature already, what URL get request format should I send? 
https://studio.mapbox.com/tilesets/mapbox.mapbox-streets-v7/#{z}/{x}/{y}

Looking forward to your reply.

**Comment by brnkhy** [comment]
Hey @KAlO2,
I think this might be a tileset issue. I believe mapbox studio uses v8 at the moment while unity sdk defaults to v7. 
Can you please try changing data source as seen below? I think this will fix the issue.
<img width="400" alt="Screenshot 2024-05-17 at 12 53 32 PM" src="https://github.com/mapbox/mapbox-unity-sdk/assets/1465390/20669105-9ae4-4219-b407-9ada9ec4cd08">

**Comment by KAlO2** [comment]
Hello @brnkhy, you saved my day.😃

I've tried option **Mapbox Streets V8 with Building Ids**, but I didn't try **Mapbox Streets V8** since the former name seems to bring more things. From the image below, **V8 with Building Ids** (still with wrong height) is not well supported? 
![img_v3_02av_6510709d-9dcf-47e7-8456-514b130a978g](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/4cc8ab0e-c90f-475b-a111-89f8a73635b0)
![image](https://github.com/mapbox/mapbox-unity-sdk/assets/4133213/9b3bafde-7ddf-48d8-98b6-0fa283db3b9b)

**Comment by brnkhy** [comment]
@KAlO2 happy to hear it worked!
I'm not exactly sure what's wrong with the second one but it's probably due to that second tileset breaking something. maybe the v8 doesn't override it in that region for some reason. "with ids" should be deprecated really.
