### ISSUE TITLE
Change filters at runtime

### ISSUE THREAD

**Issue by gsommers** [mapbox/mapbox-unity-sdk#193]
I have a type filter in my `VectorLayerVisualizer` that I want to control dynamically at runtime. So depending on user input, a different feature of the map is shown. Is there a way to do this using the current API? Do I have to reinitialize the map every time I change the filter, and if so, where should I perform this re-initialization?

Alternatively, what I really want is to be able to generate a bunch of static maps, where each one has the same background but filters out a different feature. Then depending on the user's input, a different map will be loaded from my assets. I've gotten this to work manually on another part of my project, but now I'm dealing with over 30,000 features, and generating that many static maps manually is obviously not practical. This isn't a question for the Unity SDK per se, but does Mapbox Studio have any tools for systematically generating static maps?

**Comment by david-rhodes** [comment]
@gsommers I suspect a better approach would be to add a component to each object the `VectorLayerVisualizer` creates that registers itself to some controller that notifies when filters are engaged (UI, perhaps). When the event is received, the gameobject would toggle on/off. You could do this with a custom `GameObjectModifier`or an `AddMonoBehavioursModifier` that uses some sort of singleton pattern.

This would ensure you only have to initialize the map once and "changing filters" would be instantaneous.

**Comment by gsommers** [comment]
I used your strategy and made a custom `GameObjectModifier` that goes through the game objects and calls a public method in a `MonoBehaviour` script that adds the objects to a `SortedDictionary` keyed by an int id. (The id is what gets inputted by the user to filter the map.) The `MonoBehaviour` script, which I named VisibiltyController, has another public method that gets called when the id changes. Or at least that's what I want to do. Now my problem is, when I try referring to VisibiltyController from the gameobject modifier (I instantiate it in OnEnabled), I get the message "type mismatch." I can see from debugging that items are being added to the dictionary, but when I try accessing them, the dictionary returns a count of 9, almost as if I have two copies of the script, where one is getting called from the modifier and the other is getting called from user input. Any ideas on how to fix this?

**Comment by gsommers** [comment]
Whoops, I meant it has

**Comment by david-rhodes** [comment]
@gsommers It would be easier to help you debug if you could share your code. That said, please keep in mind that `GameObjectModifiers` are scriptable objects--that is, they retain their internal values between play session and between use by each feature that uses the modifier. Therefore, ensure you are resetting internal fields as necessary, or you could very well get excessive registrations, for example.

**Comment by gsommers** [comment]
I hope this works:
[Filtering.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1194597/Filtering.zip)

**Comment by gsommers** [comment]
Scripts: [Filtering.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1194626/Filtering.zip)
Visualizers, factories, and such: [Visualizers.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1194627/Visualizers.zip)
This is part of a larger project so let me know if it doesn't work by itself.

**Comment by david-rhodes** [comment]
@gsommers Try making `VisibilityController` a monobehaviour singleton, rather than using `GameObject.Find`. Any chance you have duplicate components/game objects with that name in the scene?

**Comment by gsommers** [comment]
@david-rhodes  Making it a monobehaviour singleton seems to work (although I had to Google "singleton" first). Still working out the kinks but I think I'm on the right track. Thanks for all your help!

**Comment by david-rhodes** [comment]
My pleasure! Have fun!
