### ISSUE TITLE
Question: Convert Unity world coordinate to WGS84 lat/lng

### ISSUE THREAD

**Issue by xwu93** [mapbox/mapbox-unity-sdk#195]
In Conversions class, you can Converts WGS84 lat/lon to x/y meters in reference to a center point by using `GeoToWorldPosition`. 
How about vice verse? I want to convert Unity world coordinate to WGS84 lat/lng. I looked at doc and found `MetersToLatLon(Vector2d)` which doesn't work. After I click somewhere on map, the lat/lng it gives me is wrong. I tried to search lat/lng in Google Map, it shows different location compare to where I clicked on the map.

I used this: 
`Conversions.MetersToLatLon(map.GetComponent<AbstractMap>().CenterMercator + new Mapbox.Utils.Vector2d(aimLocation.x, aimLocation.z) * map.GetComponent<AbstractMap>().WorldRelativeScale);`
which aimLocation is the world coordinate on the map in Unity.

Thanks.

**Comment by david-rhodes** [comment]
I think you want [`VectorExtensions.cs`](https://github.com/mapbox/mapbox-unity-sdk/blob/ddd6cd4bece9b2a25a8e3337597cad17a65de5fd/sdkproject/Assets/Mapbox/Unity/Utilities/VectorExtensions.cs#L128). Sorry about the confusion.

**Comment by brnkhy** [comment]
@xwu93 I haven't tried this out but from first look, I think you should divide by scale, not mulitply (as we're going backwards here). So;
`Conversions.MetersToLatLon(CenterMercator + (currentPos/scale));`

Also as a side note, I'm not sure if you wrote it like that for example but GetComponent is a very costly operation and shouldn't be used like that. I highly suggest doing that once in awake or start, cache the component and use that instead.

**Comment by xwu93** [comment]
@brnkhy I think you are right. I tried and it works. 

Another related question is once I get the lat/lng. Right now I am using Google Map API to convert lat/lng to physical address. Does Mapbox have similar function that can convert lat/lng to address?

Thanks for you suggestion. Will get component in awake / start.

**Comment by david-rhodes** [comment]
> Does Mapbox have similar function that can convert lat/lng to address?

Yes, this is called [geocoding](https://www.mapbox.com/api-documentation/#geocoding). Check our geocoding examples in the example for reference usage.

**Comment by xwu93** [comment]
@david-rhodes @brnkhy 
Thanks for all explanations. Closed this issue.
