### ISSUE TITLE
Mapbox Configuration Window does not appear to save token

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#196]
An exception is thrown and the button gets stuck on, "Token Verifying." Note that this is a UI refresh bug, **but the token is indeed saved**. If you close the window (or in worst case, Unity), everything should work fine.

If you can reproduce this reliably, please post repro steps here.

Current guesses:
- Web request times out
- Bad internal state due to static fields

**Comment by unitycoder** [comment]
happened here
- new unity project
- import sdk package
- open examples Drive.scene
- try to play the scene (without setting token)
- go to configuration, try to verify.. stuck

but without playing first, it worked..
(used 5.6.1p1)

**Comment by david-rhodes** [comment]
@unitycoder Thank you for the reproduction steps!

**Comment by unitycoder** [comment]
some error here:
![image](https://user-images.githubusercontent.com/5438317/29403213-41dc059c-836a-11e7-908d-e7c70d5dbe34.png)
`MapboxAccess.Instance = System.TypeInitializationException: An exception was thrown by the type initializer for Mapbox.Unity.MapboxAccess
`
which seems to cause IEnumerator ValidateToken(string token) never to go on that `_validating = false;` line.

*also noticed that when it creates *.json output file, it causes script re-compilation, *.bytes wont, but that instance error is still there..
