### ISSUE TITLE
Get player and set objects position as real world coordinates.

### ISSUE THREAD

**Issue by HNKMaster** [mapbox/mapbox-unity-sdk#197]
I'm working using the LocationProvider example, and want to set some objects on realtime coordinates (lat,long), and also get the player real world coordinates. I tried getting the player position using GetGeoPosition (with the properties shown in the documentation example), but I always get [0,0] at start (maybe should be using another reference center). How can I get some real world results based on what's happening ingame?

**Comment by david-rhodes** [comment]
@HNKMaster I think I need some more information to assist you.

Is this issue just at start? Are you waiting for the `IMap` `OnInitialized` event before querying the position? If not, you should.

`GetGeoPosition` is definitely the appropriate method for finding the lat/lon of a unity position, relative to the map object.

FWIW, if you are using GPS to position your player, you don't need to convert, as you already have those coordinates from the `DeviceLocationProvider`, right?

**Comment by HNKMaster** [comment]
I'm working using the mock positions before going mobile.

I'm doing some tests by using UI buttons to change the object position and get the player position in real world coordinates, so it wasn't at start.

I'm converting the player Vector2d to string using this:

`string pos = transform.GetGeoPosition(new Vector2d(0, 0), 1).ToString();`

But it returns (0.000, 0.000) if I don't move the player object, otherwise I get very low numbers, but nothing resembling the initial coordinates (-33.4443741, -70.6160039).

About setting positions, I'm using MoveToGeocoordinate on one of the objects I want to translate like this:

`transform.MoveToGeocoordinate(c, new Vector2d(0, 0), 1);`

("c" being the Vector2d with the target coordinate)

But for some reason, it went so far that Unity got some float warnings on the inspector, with positions bigger than 10000.

That's all the info I can get, don't know if something is missing. By the way, how can I check the OnInitialized event?

Thanks for your help.

**Comment by david-rhodes** [comment]
@HNKMaster The reference point you need for `GetGeoPosition` needs to be in mercator meters (real world coordinates). Therefore, you should pass in `IMap.CenterMercator` as the value (you can get this with a reference to `AbstractMap`).

Same thing with `MoveToGeocoordinate`.

**Comment by HNKMaster** [comment]
That really did it, now it's working as I wished!

Thank you very much!

**Comment by david-rhodes** [comment]
Glad I could help.
