### ISSUE TITLE
Default vector styles and restructuring demos

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#198]
I'll be working on some default styles this week and thought it would be better to share this idea first.
At the moment we have bunch of demo folders, all containing every single style and resource they use. So for example, most of the mesh generation demos use very basic flat white building style but they all have their own copy of that.
Advantage of that is every demo is self sufficient so you can delete all folder except one and start your project by editing that.
Disadvange is obviously the considerable amount of duplicate files and styles.

Alternative is to create another folder called `Shared Styles` or something, then have all default styles here and let demos use these ones for basic stuff and only have their own when it's something really special. Pros and cons should be obvious but I'm just not sure how usable it'll be due to parent/child relationship between some modules.

What can we have there (some most popular stuff);
-Height/Flat/Low Poly factories
-Satellite/Streets/Dark theme image factories
-terrace terrain vector factory
-contour line vector factory
- basic 3d flat white building/road/park/water layer visualizers (with default stacks)
- 2d version of all those above?
-chamfered building stack
-smooth roads

Also maybe we can add tags to modules and classify them with those tags while selecting, i.e. when you click to attach a layer viz, you'll get a window showing only layer viz and they have tags on them like 2d,3d,basic,textured, high perf, better look etc. to describe how they actually behave. This would be helpful as layer viz for example has lots of children and would be hard to read what it does and how it behaves. On the other hand, tag manitenance might be annoying as well.

One another problem I can think of is; what happens if these default styles doesn't have snap to terrain for example and dev enables terrain height. It'll look totally broken and we can't have duplicate styles for each property like that.
I believe module initialization work (preinit/init stage, there's a branch and PR for that) will solve this issue.

Let me know if you have any ideas on this. I think this is quite related with the editor work as well. Both can be considered as "ease of use" and can be refactored/evaluated together.

**Comment by david-rhodes** [comment]
@brnkhy Good to close? Most of this was included in node editor merge?

**Comment by brnkhy** [comment]
@david-rhodes yep this is merged.
