### ISSUE TITLE
Are there docs describing the rendering model used by Mapbox/Unity?

### ISSUE THREAD

**Issue by turner** [mapbox/mapbox-unity-sdk#199]
Sorry if this is not the forum for this question. I saw David Rhodes Unity Europe 2017 talk on Unity + Mapbox https://www.youtube.com/watch?v=houwMdHj-v8. I am a rendering nerd and would like to learn more about the Mapbox rendering model and how it is mapped to Unity. Where should I go for this.

Thanks.

**Comment by david-rhodes** [comment]
@turner Well, for our Unity SDK, we use standard Unity objects for rendering (meshes, shaders, materials, etc.). However, the data used to form those meshes are stored in Mapbox Vector Tiles. You can see the specification for these here: https://github.com/mapbox/vector-tile-spec.

In Unity, we construct meshes from this data using [Earcut](https://github.com/mapbox/mapbox-unity-sdk/blob/5619fe205be6506d835ff1dc77b31cc31b6b25db/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/Earcut.cs). Take a look at an example in [PolygonMeshModifier](https://github.com/mapbox/mapbox-unity-sdk/blob/8a328e6832ca2b2d7a8088b6859a7c53092c08a7/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/PolygonMeshModifier.cs).

Does this answer your question, or are you looking for something specific?

**Comment by turner** [comment]
Thanks David. Almost there. I saw some lovely rendering from Baran Kahyaoglu - https://twitter.com/brnkhy/status/875509102256041984/photo/1 - using AO, edge chamfering. Very nice. Was that all done with Unity (OpenGL/Metal) shaders or was the shading cooked/baked in the Mapbox service before retrieval and final rendering on the device?

**Comment by brnkhy** [comment]
@turner it's all unity, even basic materials and shaders. Chamfer is created while processing the geometry while ao (and a few others) are post process effects. We aren't getting anything visual from server at all, except map (satellite etc) imagery of course.

**Comment by turner** [comment]
Very nice. Thanks guys.
