### ISSUE TITLE
Node editor for mesh generation

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#200]
So we started working on this and I'm creating this ticket to show progress and stuff. Also everyone, please don't hesitate to jump in at any point if you don't like how it is or think there's a better way etc.

I started with testing out a few libraries out there to see how they work. 
One possibility is to make something to like this to replace everything we have (inspector) at the moment;
![unity_2017-08-05_01-54-03](https://user-images.githubusercontent.com/1465390/29035161-4a2b7490-7ba3-11e7-811d-bd47e9198b4b.png)
That's a test shot but as you can see it has nodes with all details/options in them. So they pretty much have their inspector thing in those nodes. Then they would have linked from properties to child nodes etc, not in that shot.
Problem with that is it's a complicated system and will probably take a lot to make it work properly and polish. At least a lot more then the second option below.
So shortly, this is superior but high effort & challenging option.

Second opiton is to use node editor just as a hierarchy/relation map, especially for the begining. 
![unity_2017-08-07_03-36-16](https://user-images.githubusercontent.com/1465390/29035526-9b3872ec-7ba4-11e7-9e60-65ef52a1c350.png)
As you can see, this one only has module name/type on nodes and simply shows what's there and where. Then you can click on them to select the related scriptable object and change it's properties through the inspector like usual (so same thing we have at the moment).
This solves the biggest problem we had in navigation and seeing the big picture. But it lacks some details, especially with those links between modules. You can't see which modules connects to which property at the moment and it'll get confusing with some complex modules in the future. Should be fine for now though.

Anyway, I'm prioritizing the second one at the moment. Even have the basic functionalities working but it's based on some samples I found so I'll refactor them to a better structure first etc. Then I'll try to add some more details, maybe like labels on links to show which property do they connect.

@david-rhodes @isiyu @BergWerkGIS

**Comment by brnkhy** [comment]
![unity_2017-08-09_02-23-38](https://user-images.githubusercontent.com/1465390/29098757-c52ae520-7ca9-11e7-83c0-b1ecc238dbca.png)
pushed first version at node editor branch. It draws whole tree, have zoom in/out and option to hide modifiers which reduces tree size quite a lot.
Zoom is buggy at the moment, clipping is wrong as you can see in the pic top&right edges.

It might be nice to have "Click to expand" on nodes I guess. And maybe some color coding.
I'll most likely change those huge boxes to regular short boxes as well. I'm still using this just for debugging purposes (using same rect for calculation&draw functions).

**Comment by mihakrajnc** [comment]
This is awesome! Can't wait for the final result.

Took a quick look, and I know it's an early preview, but a few comments and bugs i noticed:

- Default stack should probably be identified as such, currently, having a default stack and a few others, there's no difference between them.
- Connections are sometimes funky:
![image](https://user-images.githubusercontent.com/8857844/29099502-1e118594-7ca6-11e7-8466-30d04bda9e28.png)
- It would be nice to support multiple maps in one scene.

One idea off the top of my head, it would be really cool to be able to see which modifiers / stacks are shared. For instance, if you hover over modifier, it would change color, along with other modifiers that use the same instance.

For a first look, this is really cool!

**Comment by brnkhy** [comment]
@mihakrajnc wow thanks for the quick feedback! 
You're totally right about that stack thing. Same goes for modifiers as well for example. Since all connections come out from same point and not from a property/row inside that box, it's kinda hard to tell them apart. I'll think something for this.
Haven't saw that connection thing before, any idea how can I recreate that? I'm not getting it in default demo scenes I think.
Multiple maps shoudn't be hard but as we generally don't do that, I guess I overlooked that. But yes that's a good idea and shouldn't be too hard either.

I also pushed a fix regarding node selection. Also this is how it looks with regular render rects;
![unity_2017-08-09_02-50-23](https://user-images.githubusercontent.com/1465390/29099726-d7d748e8-7caf-11e7-9d4b-ff1f713b2162.png)

**Comment by brnkhy** [comment]
it has properties inside nodes and multiple out-points now.
![unity_2017-08-09_21-08-57](https://user-images.githubusercontent.com/1465390/29136961-7f621574-7d47-11e7-8677-fe4c8ae672a8.png)

**Comment by brnkhy** [comment]
@mihakrajnc just added multiple map thing, can you please let me know if/when you try it out? I simply threw another one into the scene but didn't have a proper test case with multiple maps. 
![unity_2017-08-11_02-01-32](https://user-images.githubusercontent.com/1465390/29196277-fee160e4-7e3b-11e7-8a00-342bcb211507.png)

**Comment by brnkhy** [comment]
does github support animated gif? anyway, posting this as a progress update. I think we're rather close to first version at this point.
![2017-08-17_01-35-09](https://user-images.githubusercontent.com/1465390/29673299-7bc6afb8-88f7-11e7-9ac8-61df5970a2da.gif)

**Comment by david-rhodes** [comment]
This was merged!
