### ISSUE TITLE
Some of the keys for VectorTileFactory are not working in 1.1.0

### ISSUE THREAD

**Issue by Garshishka** [mapbox/mapbox-unity-sdk#203]
When I hopped from 1.0.0 to 1.1.0 version to look at SpawnInside feature I noticed that VectorLayerVisualizer that used "barrier_line" as key doesnt work anymore, though it worked on 1.0.0. Also some of the landuse types like "grass" or "parking" doesnt appear to work. Is it just something I borked up or is it a bug in 1.1.0?

**Comment by isiyu** [comment]
@Garshishka this isn't something we're aware of, are you able to share your unity project or screenshots of what you're seeing?

**Comment by david-rhodes** [comment]
@Garshishka One thing you can check is that all your `modifiers` are set correctly. Some parameters may have been changed/lost after upgrading. We will publish upgrade instructions soon.

**Comment by Garshishka** [comment]
I think I got it. Its zoom. It shows everyting on 16, but on 15 some things like "barier_line" dissapear

**Comment by david-rhodes** [comment]
Closing this since you figured it out! 😄
