### ISSUE TITLE
Comments for 1.1.0 upgrade

### ISSUE THREAD

**Issue by Alexphauge** [mapbox/mapbox-unity-sdk#204]
Hey everyone,

I just wanted to jot down some things I observed with our upgrade to 1.1.0. 

First of all, the method (It's in Mapbox/Unity/Utilities/Conversions.cs)
`public static Vector2d LatitudeLongitudeToTileId(float latitude, float longitude, int zoom)` - Is it supposed to use floats? Wouldn't double be more appropriate and not lose precision? 

Second, this is of course not something you can't do anything about I believe, but I'd like to point out that "Multiple plugins with the same name 'sqlite3' (found at 'Assets/Plugins/x86_64/sqlite3.dll' and 'Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll'). That means one or more plugins are set to be compatible with Editor. Only one plugin at the time can be used by Editor." could be a thing for some people. We just deleted the one we had under 'Assets/Plugins/x86_64/' and it worked out. 

Not sure if it's something that went wrong or i'm just tired, but it seems Geocoder.cs/Geocode with the reverseGeocodeResponse is broken. It throws a "Cannot cache without a map id" exception from CachingWebFileSource.cs. As far as I can understand, it seems the IAsyncRequest Request requires the optional parameter string mapId. And the Geocoder.Geocode does not provide the call with this id. 

Maybe you can use this information for something useful, just wanted to throw these things out there. :)

**Comment by david-rhodes** [comment]
@Alexphauge First of all, thanks for the report! Second, we will definitely investigate on our end.

Lastly, what was your upgrade process? Did you remove Mapbox entirely and then add the new SDK via unity package? There are some upgrade instructions here: https://www.mapbox.com/mapbox-unity-sdk/docs/05-changelog.html.

**Comment by david-rhodes** [comment]
Oh, and `public static Vector2d LatitudeLongitudeToTileId(float latitude, float longitude, int zoom)` is float because float is the highest precision we get back from `LocationService` in Unity, anyway. Technically, we should fix this anyway. 👍

**Comment by david-rhodes** [comment]
@Alexphauge For geocoding, are you using `MapboxAccess.Instance.Geocoder`? I ask because it sounds like you are using the incorrect `IFileSource` for your own Geocoder instance.

> "Multiple plugins with the same name 'sqlite3' (found at 'Assets/Plugins/x86_64/sqlite3.dll' and 'Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll'). 

Interesting. I don't see this. What platform are you on?

**Comment by Alexphauge** [comment]
Yeah, removed Mapbox entirely and then added the new SDK via the unity package from the website. 

Ahh, that makes sense then, it just felt weird because everything else that had anything to do with latitude/longitude was in double. 

I'm thinking the multiple plugins might be because, well, we have multiple plugins that uses SQLite3.dll, which imports it on their own. It worked deleting one of them, so didn't really occur to me as a big problem. I'm guessing multiple different plugins can use the same SQL plugin. But for arguments sake, I'm developing between iOS and Android. 

Correct about the MapboxAccess.Instance.Geocoder, previously we used `var geocoder = new Geocoder(MapboxAccess.Instance);`. Changing it to the above fixed it, thanks for the tip. :)

**Comment by Alexphauge** [comment]
I see I made a typo in the top comment, I changed it now, but I meant that you probably _can't_ do anything about the SQLite3.dll... As it's a clash between multiple plugins, as written above, having only your instances of the file in the project, works like a charm for us though.

**Comment by david-rhodes** [comment]
@Alexphauge Good point! The `MapId` for a vector tile (in this case) should be `mapbox.mapbox-streets-v7`. For this demo, you just search for a place and it will print the raw vector tile GeoJSON.

**Comment by Alexphauge** [comment]
Yep, that got it working! Thanks, I'll close this as I don't have any more to say, well, other than nice work 👍

**Comment by david-rhodes** [comment]
I'll keep this open as a reminder to address some of these issues. :smirk:

**Comment by Alexphauge** [comment]
Heeh, sure 👍

**Comment by Alexphauge** [comment]
Discovered a thing with Android builds. 

We have a plugin which contains a AndroidPicker.jar. Because this file contains no '-' characters, the Mapbox/Unity/Editor/Build/Mapbox_Android_prebuild_checks throws an "ArgumentOutOfRangeException: Cannot be negative" in the AndroidLibInfo(string fullPath) method at the BaseFileName line.

**Comment by BergWerkGIS** [comment]
> Discovered a thing with Android builds.

quick fix PR: https://github.com/mapbox/mapbox-unity-sdk/pull/211

**Comment by david-rhodes** [comment]
All the things fixed! Now in `develop`.
