### ISSUE TITLE
New Release: v1.1.0

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#205]
Please read the [Changelog](https://www.mapbox.com/mapbox-unity-sdk/docs/05-changelog.html) to see what's new. It is important to follow the upgrade instructions.

If you find bugs, please open relevant issues. Thank you!

**Comment by isiyu** [comment]
test slack integration

**Comment by Alexphauge** [comment]
@david-rhodes I see that you have a 1.2.0 release branch up and running. 
If we were to update our mapbox version during this week, could I just take a snapshot of the current v1.2.0 branch or should I wait until you make an official release?

**Comment by david-rhodes** [comment]
@Alexphauge I recommend waiting until it has been merged into develop and tagged as `1.2.0`. We are still testing and fixing bugs (which is why it's not quite merged yet). Should be ready very soon!

**Comment by david-rhodes** [comment]
1.2 released!
