### ISSUE TITLE
Get StyleOptimisedVectorTile data from an AbstractMap implementation [Question]

### ISSUE THREAD

**Issue by Alexphauge** [mapbox/mapbox-unity-sdk#209]
Hello,

I was wondering if it would be possible to grab the vector data from the already build map, instead of doing as per the VectorTileExample where we create a new map and it has a specific MapId and is of type VectorTile. We're only interested in what is actually used (Therefore the StyleOptimisedVector was really nice for us 👍) but we're also interested in skinning using the data. 

I might just have missed how it works, but well, if you have time to explain how I would appreciate it a whole bunch. :)

Thanks!

**Comment by david-rhodes** [comment]
@Alexphauge I'm a bit confused by this question. Style-optimized vector tiles are a way of requesting "filtered" vector tiles from our servers (using a style). Read more here: https://www.mapbox.com/api-documentation/#retrieve-tiles.

It sounds like you want to access vector tile data in Unity after you've already had the factories build the map? Well, if you have a reference to a UnityTile, it contains the VectorData. Alternatively, you can request data from any `FeatureBehaviour` generated.

If I misunderstood your question, can you please clarify? Thank you!

**Comment by david-rhodes** [comment]
Elaborating on style-optimized vector tiles: let's say you create a style and the only layer you add is `building`. When you use that style's MapId with a `StyleOptimizedVectorTileFactory`, you will only get the `building` layer from the returned vector tile.

**Comment by Alexphauge** [comment]
Yep, that was exactly what I was looking for, both with regards to the style optimized and the vectordata on UnityTiles. Thanks a lot!

**Comment by david-rhodes** [comment]
@Alexphauge Uhh, I just remembered that `VectorData` is not currently hooked up. IIRC, this was by design as we didn't want to cache the entire JSON string (and string operations are slow). We can and should improve this, however. Can you describe your use-case?

**Comment by Alexphauge** [comment]
Right now, I think we're just at a stage where we are trying to get the right look in our application. The designers thought we might need the entire JSON for this, so I was just planning ahead, making sure we actually could access the JSON. There'll be some design meetings for the next weeks time, so I might be able to come back to you with a specific use-case. :) 

And that other error just took my attention, so I'm in no hurry with this anymore.

**Comment by BergWerkGIS** [comment]
Little reminder: tile data shouldn't be converted or stored in GeoJSON format at all - these strings can get real huge real fast.

Addtionally, the `ToGeoJson()` methods of the underlying [`vector-tile-cs`](https://github.com/mapbox/vector-tile-cs) library are going to be removed some time in the not too distant future.
Probably during the next (already looming) refactor.
They are by no means properly coded and only served for debugging during early development of `vector-tile-cs`.

**Comment by Alexphauge** [comment]
Yeah, that was also my immediate concern looking at the VectorTileExample. Getting a string for my location brought the string to 28000 characters, I can't even imagine a place where there's proper information.

**Comment by david-rhodes** [comment]
I'm sure you could cache the pieces you are interested in or the raw data itself.

**Comment by Alexphauge** [comment]
Yeah, i'm thinking the same. - I am still interested in grabbing the style optimized GeoJSON though, if that's possible, and then possibly serialize that to what we need. It seems they would like to put in some form of ruined buildings in certain building spaces. I'm not entirely sure how to go about this as it's not a final design or anything, but having access to the style optimized GeoJSON was probably a good start. At least in my head... Could probably end up being able to use your modifiers/layers/factories setup. Feel free to close this down though, as I can't provide a specific use-case right now, I can just open a new thread when I get one ^^

**Comment by david-rhodes** [comment]
@Alexphauge Let me know when you have a more concrete use-case and we can help guide you in the right direction/update the SDK.
