### ISSUE TITLE
Unity Cloud Build fails iOS

### ISSUE THREAD

**Issue by Alexphauge** [mapbox/mapbox-unity-sdk#210]
13961:        [xcode] ld: warning: object file (/BUILD_PATH/wedoo.wedoo-app.ios-development-build/temp.vylZo0/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/libMapboxMobileEventsStatic.a(MapboxMobileEventsStatic_vers.o)) was built for newer iOS version (8.0) than being linked (7.0)
13962:        [xcode] Undefined symbols for architecture arm64:
13963:        [xcode]   "_SecKeyCopyExternalRepresentation", referenced from:
13964:        [xcode]       -[TSKSPKIHashCache(Unified) getPublicKeyDataFromCertificate_unified:] in libMapboxMobileEventsStatic.a(TSKSPKIHashCache.o)
13965:        [xcode] ld: symbol(s) not found for architecture arm64
13966:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
13967:        [xcode] ** BUILD FAILED **
13968:        [xcode] The following build commands failed:
13969:        [xcode] 	Ld build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/app normal arm64
13970:        [xcode] (1 failure)
13971: ! build of 'ios-development-build' failed. compile failed

Is this something anyone have seen/worked around before? It's a new error for us, after the 1.1.0 upgrade. Local builds works fine.

**Comment by david-rhodes** [comment]
@Alexphauge I believe you need to set your tarter minimum iOS version to 8 in Unity player preferences. It's documented here: https://www.mapbox.com/mapbox-unity-sdk/docs/02-known-issues.html (even if a bit hidden :smirk:).

**Comment by Alexphauge** [comment]
My colleagues said this works, so I trust them. Thanks! 👍
