### ISSUE TITLE
How does the dynamic change zoom value display the map

### ISSUE THREAD

**Issue by sunwayhe** [mapbox/mapbox-unity-sdk#214]
When I was in unity with the demos StylingDemoMeshGeneration changed the value of the zoom to refresh, overlap generated map shows that excuse me what method can be changed dynamically zoom after map can display properly?

**Comment by david-rhodes** [comment]
Dynamic zoom is not yet natively integrated into the SDK. We are actively working on it. In the meantime, please see this related issue: https://github.com/mapbox/mapbox-unity-sdk/issues/121

**Comment by sunwayhe** [comment]
Ok.When can I expect to use this feature?
Thanks!

**Comment by david-rhodes** [comment]
@sunwayhe We can't estimate concretely because it's not a trivial feature, but we are aiming for it to be in the SDK by the end of September.

**Comment by mdragan69** [comment]
hi David,
thanks for the comments on this topic.
I was wondering if you have any updates on the release date for dynamic zoom in the SDK.
thanks in advance
Massimo

**Comment by david-rhodes** [comment]
@mdragan69 We're still on track for this feature to be released this month. A new release should be available soon.

**Comment by david-rhodes** [comment]
This is now in `develop`. Please see both `DynamicZoom` and `MapReload` scenes!
