### ISSUE TITLE
How do you convert longitude and latitude into screen coordinates?

### ISSUE THREAD

**Issue by sunwayhe** [mapbox/mapbox-unity-sdk#216]
I use in untiy ResterTileExample method shows a 2 d map, also want to add some models on the map, to achieve through the longitude and latitude put into 2 d screen coordinates are shown on the map the location of the corresponding, could you tell me which method should be used?

**Comment by brnkhy** [comment]
Hey @sunwayhe,
First of all, you can find almost everything about converting lat/lng to mercator (meters) here; https://github.com/mapbox/mapbox-unity-sdk/issues/123
Once you have meter values, you can use it for 2D directly as well. You'll most likely need a reference point though, i.e. snap your first lat/lng value to center of screen and substitute its coordinate (in meters) from all other points etc.

**Comment by david-rhodes** [comment]
@sunwayhe did @brnkhy's suggestion work for you?

**Comment by brnkhy** [comment]
closing this for now, let us know if you have any further questions @sunwayhe
