### ISSUE TITLE
Mapbox's version of Wolfulus Line Ending is not compatible with Unity 2017.1

### ISSUE THREAD

**Issue by thefoofighter** [mapbox/mapbox-unity-sdk#218]
Hi Guys,

I have had to move to 2017.1 0p4 from 5.5 and the Thirdparty asset "LineEnding" from Wolfulus in the current Mapbox SDK is not compatible with Unity 2017.1

Wolfulus has already made a fix in his [repo](https://github.com/WoLfulus/Unity-LineEndingFixer/commit/8e3b2ea82e1bd92b5e2a6350f0aaf4f90ad145b0)

Its not a big issue I just thought I would mention it since you will eventually have to move to supporting  newer versions.

I would have made a pull request but i figured this might be something you need to decide on and test internally. The changes do not seem too extensive and should port back to 5.5, 5.6.

It could be made a submodule or is that a bad idea since the source is out of your control?

All the best

**Comment by david-rhodes** [comment]
@thefoofighter Thanks for pointing this out! We'll be doing a 2017 upgrade soon, and this fix will be included in that.

**Comment by david-rhodes** [comment]
In `develop`.
