### ISSUE TITLE
Gaps/ Seams between tiles on Android

### ISSUE THREAD

**Issue by brianjkd** [mapbox/mapbox-unity-sdk#219]
There appear to be gaps/ seams between tiles as a result of the tiles not completely touching.

I am only noticing this on Android (have not tried on iOS). There are no seams/gaps in the Unity Editor.

Here is a recorded video which highlights the issue. 

https://youtu.be/Zrzmw3qqPEU?t=139

**Comment by david-rhodes** [comment]
@brianjkd Thanks for bringing this to our attention. Unfortunately, we will need some more information from you to help debug the issue. 
- Please attach a screenshot of your `IMap` and `ITileProvider` components to this ticket
- How far away from the origin are you in this video? 
- What version of the SDK are you using?
- What device are you using? Do you see this issue on all Android devices? OS version?

**Comment by brianjkd** [comment]
Thank you for your response.

The issue appears to be correlated to the lat, lon string.

There are no seams at 5.838417, -2.419549
but there are seams at 42.273488888889, -71.80735

I have uploaded a unity package which can be imported into an empty project and built for Android. It is available here:

https://drive.google.com/open?id=0B8Y-MOGYNaRmMWtlc205R2tqWVU

I have only tested this on a single Android Phone (Droid Turbo 2) with OS Android 7.0

**Comment by david-rhodes** [comment]
@brianjkd Haven't had a chance to look at your project yet, but I just noticed this today with my own project. I suspect floating point imprecision is at fault. We will investigate very soon!

**Comment by BergWerkGIS** [comment]
@brianjkd haven't tested if this helps in your case but you could try to

change `EarthRadius` to `6372798.2` here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L20

and remove the `(float)` casts here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L269-L270

and here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L277

**Comment by BergWerkGIS** [comment]
Able to reproduce:
![image](https://user-images.githubusercontent.com/4549888/29924780-632b71a2-8e5e-11e7-8fa4-bdf5616868b2.png)

**Comment by BergWerkGIS** [comment]
Changes suggested [above](https://github.com/mapbox/mapbox-unity-sdk/issues/219#issuecomment-326264616) don't show any gaps:
![image](https://user-images.githubusercontent.com/4549888/29925018-54573552-8e5f-11e7-9ae4-7d52993a8b59.png)

**Comment by brianjkd** [comment]
@BergWerkGIS 
That worked, thank you.

**Comment by BergWerkGIS** [comment]
perfect!

**Comment by J450NP13** [comment]
This is still not working.  I am Using the Abstract map for locations and the initial map is fine but the next location has gaps.

**Comment by lukemadera** [comment]
I'm still having the same issue too, as @J450NP13 noted. I wrote a function to reposition the tiles to remove the gaps:

```
void FixTileGaps(int numExtentsX, int numExtentsZ, Transform mapT) {
    	// Assumes first child is TileProvider, 2nd is center tile, and the rest go in order
    	// starting from minX and maxZ corner, along z to minZ then along x to maxX.
    	float xOffset, zOffset, xOffsetTotal, zOffsetTotal;
    	// Extend from center in both directions, so total rows and columns are each double plus 1.
    	int numX = (numExtentsX * 2) + 1;
    	int numZ = (numExtentsZ * 2) + 1;
    	// -1 because 0-indexed.
    	int indexCenterX = numExtentsX + 1 - 1;
    	int indexCenterZ = numExtentsZ + 1 - 1;
    	int childCount = mapT.childCount;
    	// Figure out offset.
    	int childStartOffset = 2;
    	Transform childCenter = mapT.GetChild(1);
    	int indexOffsetX = numZ * (indexCenterX - 1) + (indexCenterZ) + childStartOffset;
    	Transform childOffsetX = mapT.GetChild(indexOffsetX);
    	int indexOffsetZ = numZ * (indexCenterX) + (indexCenterZ - 1) + childStartOffset;
    	Transform childOffsetZ = mapT.GetChild(indexOffsetZ);
    	Bounds childCenterBounds = childCenter.GetComponent<Renderer>().bounds;
    	Bounds childOffsetXBounds = childOffsetX.GetComponent<Renderer>().bounds;
    	Bounds childOffsetZBounds = childOffsetZ.GetComponent<Renderer>().bounds;
    	xOffset = childCenterBounds.min.x - childOffsetXBounds.max.x;
    	// z goes from max to min.
    	zOffset = childCenterBounds.max.z - childOffsetZBounds.min.z;
    	int xx = 0, zz = 0;
    	print ("offsets " + xOffset + " " + zOffset + " " + childCenter + " " + childOffsetX + " " + childOffsetZ + " " + indexCenterX + " " + indexCenterZ + " " + indexOffsetX + " " + indexOffsetZ);
    	for (int ii = 2; ii < childCount; ii++) {
    		if (xx > numX && zz > numZ) {
    			Debug.LogWarning("Unexpected extra children, stopping..");
    			break;
    		}
    		// Skip center tile, which is listed first (and is already in correct spot).
    		if (xx == indexCenterX && zz == indexCenterZ) {
    			zz++;
    		}
    		xOffsetTotal = (indexCenterX - xx) * xOffset;
    		zOffsetTotal = (indexCenterZ - zz) * zOffset;
    		print (ii + " " + xx + " " + zz + " " + xOffsetTotal + " " + zOffsetTotal);
    		mapT.GetChild(ii).position = mapT.GetChild(ii).position +
    			new Vector3(xOffsetTotal, 0, zOffsetTotal);

    		zz++;
    		if (zz >= numZ) {
    			xx++;
    			zz = 0;
    		}
    	}
    }
```
<img width="556" alt="Screen Shot 2021-03-28 at 11 44 21 AM" src="https://user-images.githubusercontent.com/1377076/112765088-5ce5f800-8fc0-11eb-8d96-7b75786f29ed.png">
