### ISSUE TITLE
How to add list of coordinates and display on map as marker

### ISSUE THREAD

**Issue by cjloh** [mapbox/mapbox-unity-sdk#220]
I have a list of coordinates and i wanted to display them on the map as custom marker. Can you give me some advices on it?

Currently, i just use the Conversions.GeoToWorldPosition to place each marker on the map. But its not the best way to do it as some coordinates are very far away from my current position.

**Comment by brnkhy** [comment]
`Currently, i just use the Conversions.GeoToWorldPosition to place each marker on the map. But its not the best way to do it as some coordinates are very far away from my current position.`
@cjloh What kind of problem are you having with that?

**Comment by cjloh** [comment]
@brnkhy for instance, my current location is at new york and i have some coordinates somewhere in malaysia. When i use GeoToWorldPosition on those coordinates, it will have very large value on the GameObject's transform position and unity show below warning on these game objects:

"Due to floating point precision limitations, it is recommended to bring the world coordinates of the GameObject within a smaller range."

**Comment by david-rhodes** [comment]
@cjloh Unfortunately this floating point precision issue is a limitation of Unity transforms. You can try to work around this by changing your `Unity Tile Size` so that you your conversions lead to positions closer to the origin.

We are working on a streaming world implementation, but I am unsure how much it will help with this specific problem.

What zoom level are you working with? Current Unity tile size?

**Comment by BergWerkGIS** [comment]
@cjloh some other things for you to try, although I'm not sure if they help in your case.

Change `EarthRadius` to `6372798.2` here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L20

and remove the `(float)` casts here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L269-L270

and here:
https://github.com/mapbox/mapbox-unity-sdk/blob/86282c925c823941498939c2ed14151a662be31f/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L277

**Comment by david-rhodes** [comment]
@cjloh Did the Unity tile size adjustment help?

**Comment by cjloh** [comment]
@david-rhodes hey man, currently i am using the method use in the example scene "PoiGeneration"  where i put all my coordinates into a GeoJSON file and create a new tileset with it. Then i use 
VectorTileFactory to display those coordinates on the map like the image below.
 
<img width="787" alt="mapboxpoi" src="https://user-images.githubusercontent.com/31430092/30414216-042cb678-9955-11e7-9ef9-00f779f41ece.png">

**Comment by david-rhodes** [comment]
Awesome--great idea! Closing now.

**Comment by cobaltplay** [comment]
Hey guys. I just came across this thread as I'm trying to do a similar thing and I need some help to point me in the right direction. I'm using Unity. What I'm trying to do is allow users to place markers on a map as they are walking around. These markers would then appear to other users on the map in the same location.

I believe I'll have to create a separate server to handle the lat and long data and pull that down whenever the user is within a specific radius. Or is this something that mapbox provides through your marker API?

@cjloh - it looks like you have something similar to what I'm trying to achieve. Could you give some clearer process on how you achieved it? That would be awesome. The PoiGeneration example scene doesn't go in to much detail and I can't tell how those markers get added to the map.

Thanks for any help guys :)
Martin

**Comment by avinash018** [comment]
Hey guys, Can anyone help me how to start the process. I am very new to SDK and i want to achieve the same.. @cjloh @david-rhodes @brnkhy 
I would be a great help for me.
Thanks in advance.
