### ISSUE TITLE
Load Map from config file lat long saved in json file

### ISSUE THREAD

**Issue by Rawjesh** [mapbox/mapbox-unity-sdk#221]
need to load mapbox abstractMap from a json file which contains lat long information ,
i think need to inherit abstractMap class, but no idea how to do this please help

**Comment by Rawjesh** [comment]
i think need to inherit abstractMap class, but no idea how to do this please help

**Comment by david-rhodes** [comment]
@Rawjesh I recommend you look at `BuildMapAtLocation` for reference. Simply load your lat/lon from the json file, then use that to set the value in `AbstractMap` before enabling the component.

A better alternative would be to make `AbstractMap` abstract and have an abstract method to `Initialize` the map. Perhaps this takes location as a parameter.

**Comment by Rawjesh** [comment]
thanks for your comments david . created new CustromAbstractMap class from  MonoBehaviour and IMap
which accepts lat long from a json, is it correct way ? now it is working fine .

**Comment by david-rhodes** [comment]
@Rawjesh Yep--that sounds like a good starting point! 👍
