### ISSUE TITLE
how to find height of a point using  lat long to place object on map, Conversions.GeoToWorldPosition gives x and z values need y value.

### ISSUE THREAD

**Issue by Rawjesh** [mapbox/mapbox-unity-sdk#222]
how to find height of a point using  lat long to place object on map, Conversions.GeoToWorldPosition gives x and z values need y value.

**Comment by brnkhy** [comment]
@Rawjesh you can check the `QueryHeightData` function in UnityTile for this. It takes x&y as float values in range 0-1 though, so you'll have to convert that lat&lng to that first And you can do it by converting lat&lng to meters first, then calculating its position in tile `Rect` (it's in meters as well) min/max values.

**Comment by santoshkumar918** [comment]
Hi atripathi

 i followed this

**values which i am getting for Y is not proper**

 UnityTile reqTile = getTileForGivenLatLong (point, 16);
Vector2d datRequired = Conversions.LatLonToMeters (point);
var height = reqTile.QueryHeightData (datRequired.x,datRequired.y);

**For getting X and Z it is proper**

Vector2d convData = Conversions.GeoToWorldPosition (point.x, point.y, _map.CenterMercator, _map.WorldRelativeScale);
Vector3 geoToWorldPos = convData.ToVector3xz ();

**Comment by nataraj-angadi** [comment]
Hi Santosh,

Even I'm facing the same issue. Please let me know if you find any solution.

**Comment by david-rhodes** [comment]
`QueryHeightData` requires x and y to be in tile coordinate space. Please see `SnapTerrainModifier` and `SnapTerrainRaycastModifier` for reference on how to use this query. In the future, we will add an API for retrieving height at a latitude/longitude.

**Comment by santoshkumar918** [comment]
@David Rhodes @Abhishek Tripathi Thanks for your response.
 i am getting correct height data after converting to tile coordinate space and using QueryHeightData.

**Comment by JorgeVelez** [comment]
Tile coordinate space of the point(lat lon) can be calculated with the help of the tile's Rect. 

Took me a while to figure out.

```
void spawnPrefabWithHeight(double lat, double lon)
{
	//get tile ID
	var tileIDUnwrapped = TileCover.CoordinateToTileId(new Mapbox.Utils.Vector2d(lat, lon), (int)_map.Zoom);

	//get tile
	UnityTile tile = _map._mapVisualizer.GetUnityTileFromUnwrappedTileId(tileIDUnwrapped);

	//lat lon to meters because the tiles rect is also in meters
	Vector2d v2d = Conversions.LatLonToMeters(new Mapbox.Utils.Vector2d(lat, lon));
	//get the origin of the tile in meters
	Vector2d v2dcenter = tile.Rect.Center - new Mapbox.Utils.Vector2d(tile.Rect.Size.x / 2, tile.Rect.Size.y / 2);
	//offset between the tile origin and the lat lon point
	Vector2d diff = v2d - v2dcenter;

	//maping the diffetences to (0-1)
	float Dx = (float)(diff.x / tile.Rect.Size.x);
	float Dy = (float)(diff.y / tile.Rect.Size.y);

	//height in unity units
	var h = tile.QueryHeightData(Dx,Dy );

	//lat lon to unity units
	Vector3 location = Conversions.GeoToWorldPosition(lat, lon, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz();
	//replace y in position
	location = new Vector3(location.x, h, location.z);

	var instance = Instantiate(_markerPrefab);
	instance.transform.position = location;
	instance.transform.SetParent(transform);
}
```

![screen shot 2018-01-23 at 4 18 05 pm](https://user-images.githubusercontent.com/2000930/35301428-802e4186-0059-11e8-8488-5d4d032c5a65.png)
