### ISSUE TITLE
[Setup] Slippy Map + User Location

### ISSUE THREAD

**Issue by Twelve57** [mapbox/mapbox-unity-sdk#223]
Hi ! First thank a lot for the support, you do a great job for Unity Mapbox.
I've just started with Mapbox a couple days ago, I've seen all unity tutorials for MapBox.

I want to make a project with the Slippy Demo and also the Location Démo, provided in the example folder. 
So I've tried to start with the Slippy Demo and add LocationProvider to it.
But it's not working, really don't understand why. Even if I use a 'GPS Controller' class with a static Instance..
Could you give me some informations to help me to set it up please ? Or just tell me what I'm doing wrong here. 

Because there are a lot of things wrote for JS, for a MapBox Unity beginner like me it's not easy.

**Comment by david-rhodes** [comment]
@Twelve57 Welcome to the community. First, could you help me understand what aspects of slippy you are interested in with regards to combining with LocationProvider? Are you looking to build a map that loads more tiles when your physical location changes? If so, I recommend taking a look at this comment: https://github.com/mapbox/mapbox-unity-sdk/issues/127#issuecomment-316326478. The idea is that you control the player's avatar position with `PositionWithLocationProvider` and then request new tiles based on that reference transform's position (with a buffer).

Can you elaborate on what precisely did not work in your case?

**Comment by Twelve57** [comment]
Thanks !
Yes I want something based on the user location and only display a portion of the Map, that's why I've started with the Slippy and Location projects.
But I can't setup a basic scene with both, obviously I miss something about MapBox concepts.

**Comment by Twelve57** [comment]
So, I've done that:
- Load the LocationProvider example Scene
- create the TransformTileProvider as in the #127 comment.
- link it to the map object in the hierarchy.

But nothing happened.
Also I've noticed if I changed the lat/lng (in runtime) on device, the screen just go black.
(Just by using the LocationProvider example, nothing more added)
Is it a bug ? or something I don't understand ?

**Comment by david-rhodes** [comment]
@Twelve57 The `TransformTileProvider` `_locationMarker` should be targeting the player transform, not the map. How are you changing lat/lon at runtime? This should be handled by the device location provider. Can you record a video on your device of what is happening?

**Comment by Twelve57** [comment]
Ok great ! Thank a lot ! It was my first mistake :)
In fact, I make my tests on an Android device. I used an app that change the LatLng value, but obviously MapBox doesn't like it. 

I'm not really sure what I've done is working now, I should go outside and test it. The LatLng is ok, now I have to make sure the map is building along the user movement/location.

**Comment by Twelve57** [comment]
I'm sure that question has already an answer, but I cannot find it.
I've noticed the camera still rotate even if the user stand on the same location.
Do you have any solution for that ?

This is the video to show you what I'm talking about. (in zip file)
[device-2017-08-30-202456.mp4.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1264650/device-2017-08-30-202456.mp4.zip)

**Comment by david-rhodes** [comment]
@Twelve57 There is a "RotateWithLocationProvider" component on the player transform. The camera is a child of the player, therefore the camera will appear to rotate as you rotate your device.

**Comment by Twelve57** [comment]
Ok thank for your answer. But the device is not rotating/moving, simply on the table I don't even touch it.

**Comment by david-rhodes** [comment]
@Twelve57 It sounds like your device's magnetometer has some inaccuracy or you are near interference (metal, for example). Perhaps you should adjust the `_rotationFollowFactor` so that this is less noticeable or add a filter so that rotation is ignored unless so many degrees have changed since last update.

**Comment by Twelve57** [comment]
Ok ! You're great, thank a lot for your support !

**Comment by Twelve57** [comment]
Hello it's me again.. ^^"
Still not working, I've tried a lot of different things to make it works. 
Map never refresh and so my user is on a black default map (out of bounds)
May you provide me a example project with that ? Or I can send you mine to see what's wrong. 
I'm so confused, MapBox looks great with styles features and more, and I cannot even setup the basics :/

**Comment by david-rhodes** [comment]
@Twelve57 Yes, please package up your example project and I can take a look. I prefer a github repo, if possible.

**Comment by Twelve57** [comment]
Ok thanks David !
I've packaged my example : 
https://github.com/Twelve57/MapBox_GeolocUser

It's basically inside the LocationProvider project, I just created one file : PlayerTileProvider like the TransformTileProvider in #127 .

**Comment by david-rhodes** [comment]
@Twelve57 this is an easy one :smirk:

You made the new tile provider and even added the component to the map game object, but you did not serialize that instance in the `TileProvider` field of `AbstractMap`. You're still using a reference to the `RangeTileProvider`.

Also, FWIW, the whole reason `ILocationProvider` exists is to mock and test in the editor. For example, you can verify this solution works by changing the `EditorLocationProvider` lat/lon at runtime to see new tiles loading as the player moves, without building to device!

**Comment by Twelve57** [comment]
Ok,
so should I remove the RangeTileProvider and add my CustomTileProvider in the AbstractMap class ?

Thx for the explanations, but may I use the LocationProvider for devices or it's just for testing in the editor ?

**Comment by david-rhodes** [comment]
Yes, remove `RangeTileProvider` and add your new tile provider in that field.

The type of location provider used depends on what platform you're on. For devices, it will use a different concrete implementation (`DeviceLocationProvider`). For editor, you can use `EditorLocationProvider` or `TransformLocationProvider`.

**Comment by Twelve57** [comment]
Ok it works like a charm! Bravo ;)
Thx a lot for your help and your patience.
I'm going to continue by watching and repeating your 'Europe Unite 2017' tutorial.

**Comment by sumitsingh47** [comment]
Hey there ! i want to play walking and running animation in my player how can i play that in real time location?? where should i code ? i am using c# basically but not getting the function which shows the changes in player transform...
