### ISSUE TITLE
Unable to filter road elements

### ISSUE THREAD

**Issue by Itemshopp** [mapbox/mapbox-unity-sdk#224]
Hi everyone,

After studying the tutorials about rendering 3D buildings with different heights, I wanted to make my own 3D map. I decided to begin with Roads. Everything seemed fine. Everything worked, one stack with 3 meshmodifiers and 1 go modifier for the texture. Since I decided to show only the roads I wanted, pedestrians for example, and no railways. I added a filter with keywords and selected "exclude". None of the keywords I tested worked [ except pedestrian ].

I can't find any keys and Filter Types. Based on the mapbox streets v7 , none of the keys I tested were working. Where can I find a kind of lexic with all those keywords that would allow people to customize their roads ?

Thanks a lot

**Comment by brnkhy** [comment]
Hey @Itemshopp,
You probably are using TypeFilter for this right? Type filter actually checks `type` property but road data mainly uses `class` property for classification.
You can checek this easily by changing "type" in TypeFilter line 20 to "class" and use "pedestrian" for key for example. Can you let me know if that works or not?
This is an important issue though, there's really no way of knowing this and UI doesn't help at this stage.

**Comment by Itemshopp** [comment]
Thanks a lot @brnkhy !!!

Usually I take multiple days to find out the solution before asking on github, but here it was really frustrating. I focused on the idea that Mapbox is currently complete but I realize I'll need some custom elements I guess. Again, thanks a lot.

Here is the code [ it is basically changing the two words "type" in "class" : 

`namespace Mapbox.Unity.MeshGeneration.Filters
{
    using UnityEngine;
    using Mapbox.Unity.MeshGeneration.Data;

    [CreateAssetMenu(menuName = "Mapbox/Filters/Type Filter")]
    public class TypeFilter : FilterBase
    {
        public override string Key { get { return "class"; } }
        [SerializeField]
        private string[] _types;
        [SerializeField]
        private TypeFilterType _behaviour;

        public override bool Try(VectorFeatureUnity feature)
        {
			var check = false;
			for (int i = 0; i < _types.Length; i++)
			{
				if (_types[i].ToLowerInvariant() == feature.Properties["class"].ToString().ToLowerInvariant())
				{
					check = true;
				}
			}
            return _behaviour == TypeFilterType.Include ? check : !check;
        }

        public enum TypeFilterType
        {
            Include,
            Exclude
        }
    }
}`

**Comment by david-rhodes** [comment]
@Itemshopp Thanks for sharing the new class! This should be included in the SDK. 👍

**Comment by vetvennarost** [comment]
@david-rhodes @Itemshopp Thanks for the code! Please tell me, is it possible to add some other filters beside type and class properties of mapbox-streets-v7? For example, can I make a filter for OSM's IDs or some tags?

**Comment by atripathi-mb** [comment]
@vetvennarost new filtering system will be available in v1.4.0 . Releasing pretty soon.
