### ISSUE TITLE
The map doesn't load

### ISSUE THREAD

**Issue by sunwayhe** [mapbox/mapbox-unity-sdk#225]
In the case of the network situation, I cannot load the map in unity. Is there a way to write the map data locally?If not, is there any other solution?

**Comment by BergWerkGIS** [comment]
The SDK has transient caching built it, meaning if you have loaded a map at a certain location before it will be available offline.
The cache will be pruned (first in first out) after a certain number of tiles has been reached. 
This number is in accordance with our terms of service https://www.mapbox.com/tos

**Comment by sunwayhe** [comment]
Did in fact, I want to ask is offline map package concept, I use other map app, there is a kind of offline map mechanism, can I put my map data downloaded to the local, I can choose to use when I don't have a network of offline maps.So does Mapbox have a similar approach?

**Comment by BergWerkGIS** [comment]
Currently this SDK does not offer any support for map package concept.
