### ISSUE TITLE
Loft Modifier

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#228]
Edit: you can find it all here; https://github.com/mapbox/mapbox-unity-sdk/tree/loftModifier

So I created this last week mainly because of two reasons; 
(1) Even for basic roads, I think line mesh modifier isn't good enough and should be improved. One of the biggest problems with it at the moment is that it doesn't maintain the width value at corners
![unity_2017-08-14_03-47-17](https://user-images.githubusercontent.com/1465390/30022165-d72b4af2-9172-11e7-8640-6ea3e78349e6.png)
you can notice that issue at top left & bottom right edges for example.
(2) loft modifier has lots of other much more complex uses as well. Not only for complex/better road segments but basic building facade, coastline, landuse fences etc etc.

So how it works in general;
-Loft modifier takes a prefab, which defines the shape/slice to apply on the line. So you create a gameobject with bunch of child elements like this and save it as a prefab;
![unity_2017-08-30_14-28-49](https://user-images.githubusercontent.com/1465390/30022228-2243aa84-9173-11e7-8e19-18597c2863dd.png)
then using the transform.position of each child (parent object is at the origin and everything else is relative to that), loft modifier creates the points and connects them;
![unity_2017-08-30_14-28-11](https://user-images.githubusercontent.com/1465390/30022251-41655f5c-9173-11e7-9c59-0df45537959d.png)
You probably can see that wave-like shape turned into a huge wave there. And it also maintains width on sharp corners but has some other troubles (will add them in the end).

another example;
![unity_2017-08-30_14-42-21](https://user-images.githubusercontent.com/1465390/30022295-713d7200-9173-11e7-8b9d-42d0e9128067.png)
shapes can be confusing like this, I'll draw debug lines in between them so make it obvious I guess but using old development shots at the moment. That's a road segment with a separator in the middle and pavements at both sides. And yields;
![unity_2017-08-30_14-42-02](https://user-images.githubusercontent.com/1465390/30022324-94583e96-9173-11e7-975c-cb859c75bbf3.png)

I like other type of applications better actually, they are much more fun;
![unity_2017-08-30_19-20-34](https://user-images.githubusercontent.com/1465390/30022351-ae80674e-9173-11e7-95e1-ccd76470c3e6.png)
this has cliffs for example. There's a depth buffer issue at top of cliff, don't mind that for now. 
A better shot with simpler shape not causing depth issues;
![unity_2017-08-30_19-42-42](https://user-images.githubusercontent.com/1465390/30022571-8cdfc1e2-9174-11e7-87d0-945986c13226.png)
![unity_2017-08-30_19-27-48](https://user-images.githubusercontent.com/1465390/30022398-dd141204-9173-11e7-8fbc-2c4d65f2566d.png)
just realized that shot has triangulation problem at top. that's because the coast mesh in that shot is too wide and messing it up in bottlenecks. No easy way to fix it other than not making it too wide.

problems/todo
-we don't to tile edge detection at the moment so it doesn't work properly on huge polygon which don't fit the tile. i.e. if you apply that to sea, you'll see that beach at coast AND other edges of the tile (so 4 sides)
-it maintains road width at sharp edges by using intersections of parallel lines, which is quite a nice formula but has a side effect; sharp edges creates huge corners. 
notice how good it looks in general;
![unity_2017-09-04_13-32-07](https://user-images.githubusercontent.com/1465390/30022784-87b86bb4-9175-11e7-9e2e-aeb7ea249318.png)
and this is the huge corner issue;
![unity_2017-09-04_13-33-23](https://user-images.githubusercontent.com/1465390/30022926-1fbc1bf4-9176-11e7-9d20-c2a7329d5ea9.png)
proper fix for that would be cutting that corner into two smaller ones but that makes vetex indexing quite complex as it break `n new vertices per corner` thing. (n is the point count in slice) so can be done but might not be easy.
-performance will be worse then line mesh modifier. shouldn't be too much but haven't run any tests on that.

**Comment by Garshishka** [comment]
Hello, great modifier, but when I tried it on a fresh version of Mapbox 1.1 from the site and I get this problem:
when you look from the upside, you cant see any roads
![loftmod2](https://user-images.githubusercontent.com/30876362/31015630-c8387c5c-a529-11e7-9041-d9598487c321.PNG)

but when you look from the below you can see them
![loftmod](https://user-images.githubusercontent.com/30876362/31015661-f13c59b6-a529-11e7-9f46-47cb9338e6a7.PNG)

Its like modifier creates the shape, but the heights of the points are inverted or something?

**Comment by brnkhy** [comment]
@Garshishka Hmm I'm not sure why you're having that but that means your triangles are ordered wrong. Easy fix though, all you need to do is find this part;
```
					md.Triangles[0].Add(co);
					md.Triangles[0].Add(co + 2);
					md.Triangles[0].Add(co + 1);

					md.Triangles[0].Add(co + 1);
					md.Triangles[0].Add(co + 2);
					md.Triangles[0].Add(co + 3);
```
and change it to;
```
					md.Triangles[0].Add(co);
                                        md.Triangles[0].Add(co + 1);
					md.Triangles[0].Add(co + 2);
					

					md.Triangles[0].Add(co + 1);
                                        md.Triangles[0].Add(co + 3);
					md.Triangles[0].Add(co + 2);
					
```

your triangles should look up now.

**Comment by brnkhy** [comment]
I took another shot at this yesterday as a part of #313;

-I'm not really sure what's the correct way to do this, maybe we can check some of the loft assets around but for now, I believe there's two ways to do this; 
(1) place and rotate "slice" on each point, then connect with previous/next slice
(2)  place and rotate slices on each point, create lines parallel to the original and take their intersection points.

OK here is a ridiculous drawing to explain it, I promise it'll be better next time :(
![line mesh](https://user-images.githubusercontent.com/1465390/32246764-20fa2748-be91-11e7-809e-ec9edb5d6434.jpg)
so original line mesh modifier is using (1) and loft modifier post before in this ticket (all those screenshots etc) uses (2). I recreated loft modifier to use (1) yesterday mainly because it's much cheaper, simpler and less prone to bugs (i.e. as angle goes lower, intersection point goes further and further and now you have to handle and clip that etc).

As far as I know, for 2d maps, they just calculate miter value (that corner size) and that fixes the issue with (1) you can see above. but I don't think that would work with 3d slices as that miter should only effect xz plane and not y value of those points.

I think keeping line mesh modifier is a good idea as it's hardcoded to create roads so easier and faster. then we can have a loft mod using (1) for complex shapes. It'll take some polishing and UI stuff to make it easier to use though as it's not really straight forward. I'll do a few more tests but I think we can add this new one to dev branch soon if it doesn't have the issues loft mod (2) had.

**Comment by brnkhy** [comment]
loft modifier using (1) thing pushed here; https://github.com/mapbox/mapbox-unity-sdk/tree/loft1Modifier
loft mod using (2) was here for comparison; https://github.com/mapbox/mapbox-unity-sdk/tree/loftModifier

**Comment by brnkhy** [comment]
loft (1) is merged into develop now

**Comment by Narrenschlag** [comment]
I really love the idea and potential behind this, but can somebody tell me why the Vector3 points I get from feature.Points aren't really in worldspace?

I am trying to remove the ocean edges bug
(When you use the loft modifier with the water layer the modifier thinks that the edges of the tile belong to the shore aswell)
Green: Edges of the tiles
Red: strange position of the points I get from feature.Points
![image](https://user-images.githubusercontent.com/71547522/94780739-35272600-03c9-11eb-9e49-482b3e966bc2.png)

**Comment by Narrenschlag** [comment]
I get the edges by simply using the bounds of the tile meshfilter

```
#region Get Bounds and Edges
                Bounds bounds = tile.MeshRenderer.bounds;
				Vector3 center = bounds.center; // tile.transform.position;
				Vector3 size = bounds.size;

				Vector2 c = new Vector2(center.x, center.z);
				Vector2 s = new Vector2(size.x, size.z);

				Vector2[] _edges = new Vector2[4];
				_edges[0] = c + s * .5f;
				_edges[1] = c + -s * .5f;
				_edges[2] = c + new Vector2(-s.x, s.y) * .5f;
				_edges[3] = c + new Vector2(s.x, -s.y) * .5f;
                #endregion
```

**Comment by Narrenschlag** [comment]
@brnkhy could you help me out here? :)

**Comment by brnkhy** [comment]
hey @Narrenschlag,
I think vertices are in tile space, right? Isn't that better though? Then you should be able to check if they are close to tile bound?
Either way you should be able to convert it to world/tile space by `position + tile.position`, well of course if you have the tile as well.
Positioning is really not easy though, I mean there are a lot that can go wrong so I'm not able to tell what it is this time on top of my head. The difference in Y axis might be a clue though (there is one right? red lines seems in air. why?)

**Comment by Narrenschlag** [comment]
@brnkhy Ok that is getting closer to the result but they points are still quite off. 
Do you maybe have an other idea how to detect the edges so we can remove those horrible edges on the map? ^^

Greetings
Max

**Comment by Narrenschlag** [comment]
They y axis isnt relevant and there isn't a difference just looks that way because the raycasts dont stop at the map

**Comment by Narrenschlag** [comment]
Other way around,

do you know how to convert world space into tilespace?
