### ISSUE TITLE
Landuse Visualizer

### ISSUE THREAD

**Issue by Twelve57** [mapbox/mapbox-unity-sdk#229]
Hello, I have some issue regarding the landuse generation with visualizer and factories.
I've tried to implement the solution provided in the Europe Unit (Part 6) to add grass and stuff.
I've done exactly the same, but when I click on play, Unity just freeze and the only option I got it's to force exit Unity..

So basically I use a Landuse Vector Tile and inside I define grass with a Grass Stack Modifier.
The only difference I can noticed is on my Map object. Inside the Visualizer, I use a TerrainFactory instead of your TerrainWithLayersFactory (doesn't exist ? maybe replaced by something new ?)

POI_Label works perfectly.

Do you know what happened ? Or why this could happen ?
I can provide a packaged example if needed. 
Thank a lot for your support ! #

**Comment by david-rhodes** [comment]
@Twelve57 First, please ensure your landuse objects have proper colliders. If you don't have colliders, the prefab spawning (for grass, in this case), will result in an infinite loop.

If that doesn't fix your problem, please provide an example package.

**Comment by Twelve57** [comment]
Oh ok ! Thanks you're right, I had a mesh collider instead of a box collider, that's why I've had this infinite loop. Now it's ok !

I have just one more question about the generation process. I have to make some additional tests before rendering the real object. So I've started by looking at your "POILabelHelper" class to create a LanduseGrassHelper for example.

So inside this Helper, I instantiate the real object with a prefab and set his parent to the Helper class transform. 
But nothing happened. Helper reminds empty. 

Maybe this approach isn't good with Mapbox ? Do you know what's wrong here ?

**Comment by Twelve57** [comment]
Currently I can make it works by setting a tag to the Landuse...Prefab and in a Controller just using a foreach loop on this tag to destroy and replace the prefab by the real object.
But that could ended with a lot of foreach loops, it should be better to do that at the moment Mapbox creates the Landuse...Prefab, no ?

**Comment by david-rhodes** [comment]
@Twelve57 I'm afraid you'll have to more thoroughly explain your use-case/rule system to me. It is not clear to me what you are trying to accomplish here.

**Comment by Twelve57** [comment]
Ok no prob.
Basically my goal is to give opportunity to users to custom the environment at their proper real world location. 
I want to restrict user actions by making the difference between which Mapbox object (park, school, water, ...) is triggered. 
I also use a GameSparks Database or a Firebase to save Mapbox object status and some extra properties I need.

So my mainly problem is about how I can interface my database with the Mapbox objects generation process. 

My first idea was to retrieve all the Mapbox objects.
For each one make a database request, then: 
--- create the "real" object in Mapbox container.
--- remove the mapbox one from Mapbox container.

So I've started by creating a UserLocationTileProvider to build the map along the user movement in real world. 
I've created a LanduseVectorLayerVisualizer to register Mapbox objects I want to use.
Then use a LanduseHelper for creating prefab (like your POILabelHelper in demo) and storing Mapbox Object info.
At this point, I want to use my database to retrieve extras properties about each Mapbox Object and create my own object.

I think it would be better to create my own object as child of the Mapbox Object. (I currently remove) Otherwise my unique unworking solution for now is to create/call a Controller after a UserLocationTileProvider.Update()... I really have to change that. 

I also need to update each object present in the displayed Tile along his model in database. 
These objects are clickable/interactable. 

A lot of fun !

**Comment by david-rhodes** [comment]
@Twelve57 If I understand correctly, your best solution may be to implement a custom `VectorLayerVisualizer` that can communicate directly with your database. This way, you parse Mapbox data and your custom data in the same object (to filter, aggregate, etc.).

Perhaps @brnkhy can offer another possible solution?

**Comment by Twelve57** [comment]
For the moment it's a working solution:

- tag all Mapbox_Object (Landuse, water, ..)
- call a MapboxDataController method (setObject()) in the start method of MapboxObject_Helper

in MapboxDataController,
- create arrays for Mapbox_Object_Tag and MyOwnObject_Tag
- use setObject() to create my own object (with a tag) and replace the mapbox one.
- use another method to check if MapboxObject_Tag count is equal to MyOwnObject_Tag => at this point the map is initialized.

This solution works perfectly till now but I should definitely make a custom VectorLayerVisualizer.

The only problem I encounter now is that Mapbox detects schools or stuff don't exist in real. It's really weird !

Maybe I could work with Mapbox Database for this ? For the moment I cannot estimate the amount of data I need, that's maybe my biggest problem. 
But I'm thinking about creating my own object in real time with Mapbox Database.
Is it possible ?

**Comment by david-rhodes** [comment]
> The only problem I encounter now is that Mapbox detects schools or stuff don't exist in real. It's really weird !

Can you elaborate on this? 

> But I'm thinking about creating my own object in real time with Mapbox Database.
Is it possible ?

Yeah, this is technically possible with our [Datasets API](https://www.mapbox.com/api-documentation/#datasets). You might have to write your own C# wrapper to access that API, however.
