### ISSUE TITLE
Use explicit access modifiers where possible

### ISSUE THREAD

**Issue by ahokinson** [mapbox/mapbox-unity-sdk#231]
Frequently, I find myself creating duplicate classes within my own namespace in order to specify access to a member.  Often, members are marked neither `private` or `public` and their access is left vague (possibly indicated by naming conventions).

As an example, I load my Mapbox Style from a configuration using,

```
yield return new WaitUntil(() => ConfigurationManager.Instance.Configured);
var mapImageFactory = (MapImageFactory) _mapVisualizer._factories[1];
mapImageFactory._mapId = ConfigurationManager.Instance.StyleConfiguration.MapboxStyle;

_mapVisualizer._factories[1] = mapImageFactory;
```

Obviously, `_mapId` and`_factories` were intended to be private, but I don't believe they should be.

Since this is an SDK, wouldn't it make sense to favor `public` access wherever possible and justify the use of `private` when it is considered dangerous to modify?

**Comment by brnkhy** [comment]
@ahokinson I agree that there's no need to keep factories, layer visualizers, modifier etc private really. I think it's a habit from the earlier development days where I was trying to keep everything as private unless I'm convinced it has to be public, mainly to be able to map dependencies/connection and keep it all from turning into a spagetti.
I think lots of properties like those can be converted to public soon, but I'm still not a fan of going `public` by default. In our case most properties are quite straight forward so should be easy to tell public/private anyway though.

**Comment by david-rhodes** [comment]
This is a good use-case to consider, but I agree that public by default is not the best direction to move in. Rather, I would prefer that we initialize a map factory with a `Configuration` or something. This configuration would hold any settings/data that the `Map Factory Framework` objects need.

Regardless, thank you for bringing this to our attention!

**Comment by david-rhodes** [comment]
Factories and MapIds are now public (in `develop`)!
