### ISSUE TITLE
Question: Vector2d as a public property not showing in Unity inspector

### ISSUE THREAD

**Issue by lgzajac** [mapbox/mapbox-unity-sdk#232]
Hi!
I would like to know if there is any special reason for leaving struct without [System.Serializable] (which fixes using vector2d in inspector) ?
.. or this is just a bug? ;) 
(I remember that some time ago there were problems with using structs in Unity)

```
namespace Mapbox.Utils
{
    using System;
    using System.Globalization;

    [System.Serializable]
    public struct Vector2d
```

**Comment by david-rhodes** [comment]
@lgzajac Just an oversight on our part--thanks for pointing it out!
