### ISSUE TITLE
Embedding unity/mapbox view in ios app

### ISSUE THREAD

**Issue by etown** [mapbox/mapbox-unity-sdk#234]
I've been attempting to embed a mapbox/unity view into an existing ios app, following these instructions:
https://github.com/blitzagency/ios-unity5

I have been successfully able to add a unity view with the arkit plug-in into an existing app. however when attempting to use the map box unity plug-in I get this runtime error at the initialization:

call: 
[[MMEEventsManager sharedManager] initializeWithAccessToken:[NSString stringWithUTF8String:accessToken] 
                                                  userAgentBase:[NSString stringWithUTF8String:userAgentBase]
                                                  hostSDKVersion:[NSString stringWithUTF8String:hostSDKVersion]];

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSDateFormatter rfc3339DateFormatter]: unrecognized selector sent to class 0x1b1622d40'

0x1065cf710 <+60>: b      0x1065cf6e4               ; <+16> at MMEEventsManager.m:39

I have been able to debug no further. any suggestions?

Thanks

**Comment by david-rhodes** [comment]
@etown Did you add the `ObjC` linker flag to your project?

**Comment by etown** [comment]
@david-rhodes  yes, thank you that resolved it and I was able to successfully embed the Mapbox/Unity view!  

However I do experience some pretty bad performance issues on initialization, if I cannot improve it I will open a new issue regarding that. Thanks again.
