### ISSUE TITLE
3D buildings not extruding 

### ISSUE THREAD

**Issue by Yaffa1607** [mapbox/mapbox-unity-sdk#235]
I've followed the Mapbox-Unity tutorial to the dot . 
The Part 1 works well , where the map shows up , but the 3D buildings do not show up at all. 
Can someone tell me If Im doing something wrong here , or if somethings broken?
Ive attached images of the UI.

[Document1.pdf](https://github.com/mapbox/mapbox-unity-sdk/files/1294882/Document1.pdf)

**Comment by david-rhodes** [comment]
@Yaffa1607 Please check that your texture modifier has texture sides and top checked and that you have assigned materials for those. Do you have gameobjects in your map hierarchy?

**Comment by Yaffa1607** [comment]
Hey @david-rhodes  , Yeah , I have materials assigned to both. And the Gameobject in heirarchy is present. 
Attached images. 
![screen shot 2017-09-13 at 2 31 23 pm](https://user-images.githubusercontent.com/15791187/30368902-41be53cc-9890-11e7-9420-8c9565004339.png)
![screen shot 2017-09-13 at 2 31 28 pm](https://user-images.githubusercontent.com/15791187/30368900-4175efec-9890-11e7-8024-f4c3c6a7cc84.png)

**Comment by Yaffa1607** [comment]
![screen shot 2017-09-13 at 2 32 34 pm](https://user-images.githubusercontent.com/15791187/30368947-68bb4098-9890-11e7-856b-b730924c6486.png)


This is what it looks like on playing.

**Comment by Yaffa1607** [comment]
My bad, The ZOOM WAS 15 ! It works now. sorry for the trouble!

**Comment by david-rhodes** [comment]
No worries--I'm glad you got it all worked out. 😄
