### ISSUE TITLE
Error on Hololens (Screen position)

### ISSUE THREAD

**Issue by taszilvo** [mapbox/mapbox-unity-sdk#239]
Hi.

After i build and try to deploy on Hololens device the example scene (MeshGenerationBasic), before the Unity splash screen my app just stopped working. (Ofc i did the options for UWP and Hololens as in the description).
The error message is: "Screen position out of view frustum (screen pos 0.000000, 0.000000) (Camera rect 0 0 1268 720)"

I use: Unity 5.6.0.f3 and visual studio 2015.  (Mapbox is not working in 2017)

**Comment by david-rhodes** [comment]
@taszilvo >Mapbox is not working in 2017
For Hololens, or in general? Can you elaborate, please?

@BergWerkGIS have you ever seen this? Any ideas?

**Comment by taszilvo** [comment]
I tried only for Hololens (UWP project).
The generated project by Unity5.6.0f3 build successful in VS 2015, but in 2017 i cant build, get this error at building the UWP project:
[https://ibb.co/f7G3w5](url)

**Comment by BergWerkGIS** [comment]
As for the error: I don't have any ideas.

As for VS2017: 
* generally speaking the SDK does work with VS2017 - I'm even on ` VS2017 15.4.0 Preview 2.0`
* I ran into a different problem before: I couldn't build HoloLens projects with VS2015 but only with VS2017.
In your case I think it boils down to Unity not being able to work with the W10/UWP SDK you have installed - the one coming with VS2017 probably being too new.

**Comment by taszilvo** [comment]
But i think, you tried Mapbox on Hololens (or just emulator) successfully (because you made a tutorial to Hololens).  But how? :D    Unity version, VS version, etc..

**Comment by BergWerkGIS** [comment]
@taszilvo I don't have a physical HoloLens to test.

This combination works for me with `Mixed Reality Portal`:

* Unity 2017.1.1f1 
* VS2017 15.4.0 Preview 2.0
* WinSDK 10.0.16278.0

Unfortunately there's an error with  `HoloLens Emulator 10.0.14393.0`:
`The program has exited with code -1073741819 (0xc0000005) 'Access violation'.`

Currently I don't have any idea where and why this is happening.
We'll have to do keep digging.

**Comment by taszilvo** [comment]
Yes, i have HoloLens Emulator 10.0.14393.0
I tried with newer Unity and VS versions too, and i got this error too...
So that's the problem. :(

**Comment by jordy-isaac** [comment]
If you're still having trouble with version 1.4 please re-open this ticket.
