### ISSUE TITLE
Node Editor Improvements/Fixes after initial merge

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#241]
Node editor is merged into dev branch but there are a few improvements/fixes we can do, I'll list them here instead of making a ticket for each.

~~-new inspectors are fine but "Add New" button (and the selection wndow) can be a little hard to use. another button for creating an empty object right away, so you can drag&drop stuff in would be good.~~

-would be nice to have drag&drop like arrays in general. for arracys, for example, you can drop an object at the header and it'll add it to the end of the list. not having drag&drop hurts a little after using it for so long I guess.

~~-there's a bug in mesh factory where layer visualizer keys are disabled. actually not only that but most of the object fields are disabled, they still work with double click but I think it would be better to have them enabled. Not sure if it'll support drag&drop but it probably will and that's good as well.~~

-asset selection window is a little hard to read. looks way cluttered at the moment, even though there isn't much going on there really. Needs a UX pass here. i.e. align names/types of all assets

**Comment by david-rhodes** [comment]
> -there's a bug in mesh factory where layer visualizer keys are disabled. actually not only that but most of the object fields are disabled, they still work with double click but I think it would be better to have them enabled. Not sure if it'll support drag&drop but it probably will and that's good as well.

MeshFactory is obsolete, right?

**Comment by brnkhy** [comment]
@david-rhodes ah that's just a typo, was talking about vector factory.

first and third ones are fixed here; https://github.com/mapbox/mapbox-unity-sdk/pull/256

won't rush for second and forth yet as they are harder and not sure what/how to do yet.

**Comment by brnkhy** [comment]
this is how new buttons and enabled fields looks like;
![unity_2017-09-26_15-46-52](https://user-images.githubusercontent.com/1465390/30860983-ef121f9a-a2d1-11e7-9eb0-7bcfb44c77a0.png)

**Comment by brnkhy** [comment]
also did some simple alignment stuff for the editor to improve readability. unfortunately that font isn't monospace so char count based alignment doesn't align properly but still helps a lot. we can consider adding a custom mono space font for this kind of stuff later.
![unity_2017-09-26_15-47-36](https://user-images.githubusercontent.com/1465390/30861008-08ce053e-a2d2-11e7-84d3-3b5ca29dc022.png)

**Comment by brnkhy** [comment]
released with v1.2 last week! Horaaayyy
