### ISSUE TITLE
Excessive TileSet Object Duplication

### ISSUE THREAD

**Issue by MarkProjectRepo** [mapbox/mapbox-unity-sdk#242]
Using a custom tile set that contains latitude, longitude, height info, as well as a string descriptor, when loaded into the map there are a Large number of duplicate objects that get created from a standard VectorLayerVisualizer stack based off of the poi example. The dataset that the tileset is based off of has been extensively cleaned of any duplicates, but has points which are close together, but still separate.

Is there any type of known bug for this, or fix that may be implemented? Does this maybe have something to do with the details provided at the standard zoom level?

**Comment by david-rhodes** [comment]
@MarkProjectRepo If you are using the example's MapVisualizer, there are two `poi_label` VectorLayerVisualizers, which could explain your duplicates. 

Another thing to check is that your implementation of `ITileProvider` is not requesting duplicate tiles for any reason. 

Can you provide more information, please?
- What TileProvider are you using?
- What is the layer name for your custom tileset? 
- Are you also using `streetsv7`?

**Comment by MarkProjectRepo** [comment]
The issue happens in both the Camera Bounds Tile Provider, as well as Range Tile Provider. The layer name is a bit messy but I have it exactly copied over to the name (Cleaned_Tower_Info-2q9j47), and I am using streetsv7 as well. Nothing but the custom data is being duplicated, and I can't find anything the ITileProvider may be doing.

I should also mention I only intended to mention the poi example to state that I followed it as an example for creating a new custom map.

Thanks, let me know if there's anything more that needs clarification, or of any wanted screenshots/files.

**Comment by david-rhodes** [comment]
@MarkProjectRepo Yeah, if you're willing share screenshots (of both the results and the Unity inspector for the factory hierarchy), that would helpful!

**Comment by MarkProjectRepo** [comment]
Additional piece I think may help, the custom tileset zoom extent is 2-8, but I need/have the standard zoom at 15.

**Comment by MarkProjectRepo** [comment]
![modstack](https://user-images.githubusercontent.com/7595234/30600641-07816814-9d2e-11e7-85dd-bb12e7a27878.PNG)
![runtime](https://user-images.githubusercontent.com/7595234/30600644-0788f944-9d2e-11e7-89f5-98d79ae44503.PNG)
![tilefact](https://user-images.githubusercontent.com/7595234/30600643-07848a8a-9d2e-11e7-8baf-6587a20a9d7b.PNG)
![vectorvis](https://user-images.githubusercontent.com/7595234/30600642-0783dc7a-9d2e-11e7-80c8-b1d6ebe4705b.PNG)

I hope these provide some insight.

**Comment by BergWerkGIS** [comment]
> Additional piece I think may help, the custom tileset zoom extent is 2-8, but I need/have the standard zoom at 15.

Hm, there's no reason I can think of why overzooming (getting data at z15 even when tileset range is just up to z8) would result in duplicate features.

Nevertheless it might be worth to try and create a tileset that has z15.
The procedure would be to create a tileset (MBTiles) locally and upload that.

Two tools that allow more control over zoom levels and what goes into a tileset:
`tippecanoe`: https://github.com/mapbox/tippecanoe
`Mapbox Studio Classic`: https://www.mapbox.com/mapbox-studio-classic/

Is it possible to share your tileset map id so we can take a look?
If the data is confidential you could share via email ( my-firstname AT mapbox DOT com).

**Comment by david-rhodes** [comment]
@MarkProjectRepo I'm not seeing any duplicate names in the scene hierarchy.

This is unrelated, but you can actually composite your tileset with streetsv7 in one VectorTileFactory with `,` concatenation. If you are using the style json for optimized vector tiles, just make sure to add your custom tileset to that style.

**Comment by MarkProjectRepo** [comment]
The dataset is available publicly so shouldn't be a problem, I've just been using the studio built in CSV processing for it. I'll start trying to work with tippecanoe.


The tileset
- marktraquair.1xclwhwp

**Comment by MarkProjectRepo** [comment]
Solved! I wasn't aware of the possibility of concatenation in one visualization layer, and that resolved the issue entirely somehow! Great, thank you guys so much. Very fast responses.

**Comment by BergWerkGIS** [comment]
> Hm, there's no reason I can think of why overzooming (getting data at z15 even when tileset range is just up to z8) would result in duplicate features.

@MarkProjectRepo  A side note: 
overzooming 7 levels (z8->z15) is quite a lot and you _might_ see POIs appearing not exactly at their expected location due to precision loss.
In that case you might want to look into the tools mentioned above.
