### ISSUE TITLE
example of setting new latitude longitude at run time for abstract map

### ISSUE THREAD

**Issue by etown** [mapbox/mapbox-unity-sdk#247]
@DanielRakh I have a unity/mapbox embedded into my ios application. I can successfully send a message to an initialized abstract map. I would like to change the map center, however setting _mapCenterLatitudeLongitude seems to have no effect. can you point me in the direction of the proper way to change the map center at runtime?

thanks so much!

**Comment by david-rhodes** [comment]
@etown Example coming very soon with the next SDK release!

**Comment by etown** [comment]
@DanielRakh that's great, thank you for all your great work!

do you have an eta for the next release?

**Comment by david-rhodes** [comment]
My guess is later this week/early next week.

Think you are mentioning the wrong github handle, too 😄 .

**Comment by etown** [comment]
Oops 😭

Anyway, eagerly awaiting! Thanks for the info!

**Comment by david-rhodes** [comment]
In `develop` as of now. Please see the new example `MapReload` and the `ReloadMap.cs` script.

**Comment by etown** [comment]
@david-rhodes I just cloned, updated dependencies and imported package. I can run it successfully in unity, but when i've built to ios I get the following xcode error. unity 2017, xcode 9

'MapboxMobileEvents/MapboxMobileEvents.h' file not found

I searched around but couldn't find the solution. if I am importing incorrectly I apologize, do you have any advice?

**Comment by david-rhodes** [comment]
@etown I'm assuming you've brought this into your own project? What do you mean imported package? Did you create the package yourself?

Ensure you have the file here: `Assets/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/MapboxMobileEvents` and ensure iOS is checked in the inspector. 

If that doesn't work for you, can you paste your xcode project `Other Linker Flags` and `Header Search Paths` please? Thanks!

**Comment by etown** [comment]
@david-rhodes I imported the package by first exporting it according to theinstructions in the readme.

the files are present. I'm not sure where to find the ios checkbox in the inspector. could you tell me where to find it?

I was able to get it to build following the changes described here:
https://github.com/mapbox/mapbox-unity-sdk/issues/101

![screen shot 2017-09-26 at 4 48 37 pm](https://user-images.githubusercontent.com/357244/30889356-ab4b25e6-a2da-11e7-9a48-4268fc00e39a.png)
![screen shot 2017-09-26 at 4 48 12 pm](https://user-images.githubusercontent.com/357244/30889357-ab627dea-a2da-11e7-9749-cc810a8a2fce.png)

**Comment by david-rhodes** [comment]
@etown Which change specifically? [Delete and reinstall?](https://github.com/mapbox/mapbox-unity-sdk/issues/101#issuecomment-326034721)

**Comment by etown** [comment]
@david-rhodes basically this:
![5292853365571584](https://user-images.githubusercontent.com/357244/30889694-22bf4600-a2dd-11e7-9f33-6bfb7b5e0196.png)

**Comment by david-rhodes** [comment]
@boundsj Are you able to offer any insight here? Should this have to be done given the header search path?

**Comment by boundsj** [comment]
> Should this have to be done given the header search path?

No. As I understand it, we have a script in our Unity SDK that should set up the generated Xcode project correctly so the steps noted above do not need to be done. We have an internal repo to test Unity cloud builds that (I think) needs this to sort itself out correctly in order to pass tests.

**Comment by david-rhodes** [comment]
It looks to me, based on the screenshots provided, everything was set properly based on our build script. In other words, looks like the build script did its job, yet manual code changes were still required?

**Comment by boundsj** [comment]
Yeah if someone can provide the steps required for me to reproduce this issue I'm happy to take a look. I'm foggy on the Unity bits and can't remember where to start atm! 😬

**Comment by thehen** [comment]
I'm having the same issue as well, instructions above fixed it. Simply create a new project, import MapBox, build iOS Xcode project, deploy to device.

**Comment by apavani** [comment]
I discovered that this error occured for me because I had the Symlink Unity Libraries checkbox turned on while building for iOS.
Please make sure this is unchecked before building
![33154796-e62110da-cf9f-11e7-8010-c7e488e81b6b](https://user-images.githubusercontent.com/8422708/33285901-8ea5b690-d368-11e7-94ee-ddd110507b9b.png)
