### ISSUE TITLE
Set map sectors for instancing prefabs.

### ISSUE THREAD

**Issue by HNKMaster** [mapbox/mapbox-unity-sdk#250]
Hi everybody.

I'm wondering, if is possible for Mapbox to set parts of the map, in which someone can generate some GameObjects, for example, a park with trees. I can do it setting coordinates manually, but when there are too many objects, I think it could be done faster based on a certain area. I'm working with LocationProvider by the way.

**Comment by brnkhy** [comment]
@HNKMaster we have random decorations (trees in park) in "MeshGenerationStyles" demo, is that what you're looking for?

**Comment by david-rhodes** [comment]
Please check `SpawnInsideModifier` for an example of how to accomplish this. As an alternative, see this comment: https://github.com/mapbox/mapbox-unity-sdk/commit/944966f4da715fa3bf95c747090de7d065303e77#commitcomment-23144298.
