### ISSUE TITLE
Mapbox.Unity.MapboxAccess.Instance.ClearCache() Can't clear all map cache.

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-unity-sdk#251]
use clear caches can clear current scene map cache, not all scene.

**Comment by BergWerkGIS** [comment]
This is by design: only the caches the currently active `MapboxAccess` knows about are cleared.

**Comment by david-rhodes** [comment]
@veyvin What are you trying to do, exactly?

**Comment by veyvin** [comment]
@david-rhodes @BergWerkGIS  I have written a server,the server is draw line in map by mapbox js API. In one scene I need to upload the Latitude and longitude to the server. If not clean the cache, In other scene it will not show the new map.I need clean cache by code . I can clean the folder not use MapboxAccess.Instance.ClearCache(), but it too rude.

**Comment by david-rhodes** [comment]
@veyvin If I understand the problem correctly, I can recommend 4 options:
1. Consider if you truly need caching at all (you can disable this with the mapbox configuration window).
2. Consider if you are approaching your problem with the best possible solution. For example, are there other ways to draw your line that don't require new tiles to be fetched?
3. Nuke the entire cache directory, as you suggested.
4. Extend the caching on your own. Perhaps set a "ForceRefresh" property in `CachingWebFileSource.cs` that will force a web request, even if the tile exists in cache?
