### ISSUE TITLE
Earcut crashes in certain cases.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#252]
I'm having problems loading a map with the _new_ Earcut dependency. In some cases, the map loads ok, but in other cases it crashes with a NPE.

The crash occurs on this line:

https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/Earcut.cs#L490

It looks like there is a null check there, but it does nothing. This seems to be the issue: https://github.com/mapbox/earcut/issues/87

A simple fix for this is to modily the EliminateHoles method like this:
```csharp
// process holes from left to right
for (i = 0; i < queue.Count; i++)
{
	EliminateHole(queue[i], outerNode);

	Node filterPointsNode = FilterPoints(outerNode, outerNode.next);

	if (filterPointsNode == null) break;

	outerNode = filterPointsNode;
}
```
But I don't know how correct is this, or what the implications of the change are... Any suggestions?

**Comment by david-rhodes** [comment]
cc @brnkhy

**Comment by brnkhy** [comment]
@mihakrajnc I never had such a problem, can you share a sample lat/lng to test it out as well?

**Comment by david-rhodes** [comment]
@mihakrajnc any updates here? 

> Can you share a sample lat/lng to test it out as well?

**Comment by david-rhodes** [comment]
@mihakrajnc closing for now. Please let us know if you find a specific feature that breaks Earcut!
