### ISSUE TITLE
MapBoxMetricsClient.o error

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-unity-sdk#254]
Original issue opened in https://github.com/mapbox/mapbox-gl-native/issues/10052 by @indejun

**Platform:**
Unity (iOS)
**Mapbox SDK version:**
MapBox Unity 1.1.0
### Steps to trigger behavior

 1. By using MapBox Unity 1.1.0, we were try
![mapbox_arm64error_2_20170925](https://user-images.githubusercontent.com/32251629/30789393-3f915f82-a1e0-11e7-912f-b968fa5ad2d3.jpg)
![mapbox_arm64error_1_20170925](https://user-images.githubusercontent.com/32251629/30789394-3f91e330-a1e0-11e7-9a95-1f5baec4b88a.jpg)

ing to export to iOS build
 2. During the process, after exporting by xcode and linking process, we've received the error message
    "MapBoxMetrixClient.o cannot be defined".
 3. Our developer said that file(MapBoxMetrixClient.o) is not in MapBox API which Imported from Unity

**Comment by david-rhodes** [comment]
@indejun I suspect you do not have the entire SDK installed properly. I recommend importing the `.unityPackage` again to ensure you have all necessary files. Please let us know if that does not resolve the issue. Thank you!

**Comment by boundsj** [comment]
@indejun

Can you provide more information about your dev environment? Specifically:

* What version of Unity are you using?
* What version of Xcode are you using?
* What version of iOS are you attempting to build and run on?

The screenshot above makes this seem like it might be related to attempting to build for and run on an iOS version lower than 8 (which is not supported). The error says that MapBoxMetricsClient.o _is_ found but that symbols are not available for a file it references for the architecture you are building for. But, we cannot reproduce this issue and I'm not entirely sure so getting more information from you would probably help.

**Comment by david-rhodes** [comment]
@indejun I think we saw this with another developer. Removing the entire mapbox folder (SDK) from Unity and then doing a fresh install from the `.unityPackage` seems to have resolved the error.
