### ISSUE TITLE
Pool vector tile child objects and their components 

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#263]
Similar to the way we are pooling tile game objects and `UnityTile` components in `AbstractMapVisualizer`.

We need to pool these objects because creating/destroying gameobjects and adding components is a very costly operation at runtime. This will make vector tile-based slippy maps much faster to load.

**Comment by brnkhy** [comment]
we can cache gameobjects (with monobehaviours, meshes and all others attached to it) in scriptable objects. When you think about it, there's only a few module actually create game objects;
-Map Visualizer creates tile game object and UnityTile monobehaviour. (already pooled)
-Mod Stacks (both normal & merged) create almost everything.
-Some game object modifiers, like prefab modifier, creates decorations.
And that's all if I'm not missing something.

At this point, it should be fairly straight forward to add pooling into these, which would save huge amount of time, especially for mod stacks and modifiers.
There was a very basic pooling helper class I used back when we were working on tile caching actually. Would be nice to have something like that, handling all lists itself so we won't have to deal with those separately. And with everything using same pooling class/logic, it would be easier to maintain. It should be very basic, just a wrapper over active/inactive object list anyway.

**Comment by MiroMuse** [comment]
This ticket looks done, so closing out! Feel free to reopen at any time.
