### ISSUE TITLE
Style List does not Update

### ISSUE THREAD

**Issue by markgrossnickle** [mapbox/mapbox-unity-sdk#265]
I recently cleaned up our stylelist:
![image](https://user-images.githubusercontent.com/16213480/30929569-237562c4-a37c-11e7-9fcd-5268a118c292.png)

However, in Unity they do not update:
![image](https://user-images.githubusercontent.com/16213480/30929634-4355f360-a37c-11e7-817b-3b5e33569afb.png)

Does it require creating a new token each time we make changes?

**Comment by david-rhodes** [comment]
@markgrossnickle I just tested this with my own account. The styles are cached on server for ~15 minutes. If you wait and then search, the results should be accurate.

**Comment by markgrossnickle** [comment]
Thanks!  I think one I didn't hit publish and the other is now updated.  Cheers
