### ISSUE TITLE
TextureModifier rework

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#266]
Texture Modifier is one of my least favorite modifier in the SDK at the moment. I think I rushed it back when I originally created that and couldn't get back to fix it. Here's the issue;

![unity_2017-09-28_16-39-51](https://user-images.githubusercontent.com/1465390/30969636-abd4d830-a46b-11e7-81a6-4baf6a6339cc.png)

First of all, we're trying to work on an abstract level and this modifier clearly is not. TopMaterials & SideMaterials is a bad way to do it and obviously targeted at a certain type of entities; polygons with height. And that kinda assumes your side walls will be a second submesh as well.
But what if your structure is all different? what if you have a very complex feature with 20 submeshes?

My short term solution is just taking a step back and simplifying this to something like;
![unity_2017-09-28_16-42-43](https://user-images.githubusercontent.com/1465390/30969775-0f651aae-a46c-11e7-9e20-33453e174c1b.png)

that one has a list of materials and depending on the submesh count, it'll just add materials from that list to object. So if you have 20 submeshes, you can add 40 materials there, first 20 will be assigned to object. This removes everything like top, side etc as well. This assumes you know which submesh you have at which index but these are features you create in mesh generation system so I think it's a fair assumption.
One thing that shot is lacking is randomization. It'll just assign that one material to one submesh. I'll try list of list as well, that would solve this issue (but might be a UX nightmare maybe?).

this will also break all demos and working projects and will require materials to be reassigned into that list. Shouldn't take more than 5 minutes even for the biggest projects though.

oh an actually, while we're at it; what if we rename it to "material modifier"?  That's a much better name but renaming will actually break even more stuff and people will need to recreate asset and assign materials etc. But even with that, it's a 15 minute work or something. 

We probably should keep but deprecate current implementation, add an info box with a link to a document showing how to upgrade to new "Material Modifier" etc.

**Comment by brnkhy** [comment]
![2017-10-02_14-22-05](https://user-images.githubusercontent.com/1465390/31075220-27a559e4-a77d-11e7-9b7d-0a30f6a9e598.png)
just finished this and will be testing next few days/weeks. No need to rush this for 1.2.0 release I believe.
Would love to get some feedback on this. Does it look intuitive? Can you think of any cases where it might not be enough?

**Comment by brnkhy** [comment]
As always I lost that thing I did above and had to do it again from scratch. Pushed it on https://github.com/mapbox/mapbox-unity-sdk/pull/292 this time, you can try it out there.

**Comment by MiroMuse** [comment]
@brnkhy can you close this ticket if #292 closes it? 👍

**Comment by brnkhy** [comment]
@MiroMuse ah yes we merged this 👍
