### ISSUE TITLE
Convert from globe world coordinates to geo lon/lat coordinates

### ISSUE THREAD

**Issue by zachyale** [mapbox/mapbox-unity-sdk#267]
I'm trying to use the globe example, and use a raycast hitpoint on the surface of the globe to convert that hitpoint into a set of longitude and latitude coordinates. I've tried calculating the lon/lat by converting from  a set of Cartesian coordinates, while accounting for the scale/radius of the planet, but the result is not accurate.
Here is what I have so far (where rendererComponent is a mesh rendered for the globe map):
```
float radius = rendererComponent.bounds.extents.magnitude;
float radLon = Mathf.Atan2(hitPoint.z, hitPoint.x);
float radLat = Mathf.Asin(hitPoint.y / radius);
float lon = Mathf.Rad2Deg * radLon;
float lat = Mathf.Rad2Deg * radLat;

Vector2 globeCoords = new Vector2(lon, lat);
```
I know that in one of the most recent commits there was GeoToWorld functionality added, but I'm wondering if you have any tips on achieving this conversion? Thanks!

**Comment by david-rhodes** [comment]
@zachyale What you have is correct, according to: https://vvvv.org/blog/polar-spherical-and-geographic-coordinates (I tested and confirmed). I suggest you pull `develop` (if you haven't already) and use a reference to the terrain factory's radius, rather than the renderer. This also assumes the map root transform is identity.

> Vector2 globeCoords = new Vector2(lon, lat);

Latitude is first!

```
float latitude = Mathf.Asin(position.y / _globeFactory.Radius);
float longitude = Mathf.Atan2(position.z, position.x);
var latLon = new Vector2d(latitude * Mathf.Rad2Deg, longitude * Mathf.Rad2Deg);
```

**Comment by david-rhodes** [comment]
Added to `release 1.2.0`: 9064151f8c144c7e277cddbabca9bd91961bacf3
