### ISSUE TITLE
long initialization time which blocks ui thread

### ISSUE THREAD

**Issue by etown** [mapbox/mapbox-unity-sdk#270]
I have an ios application with an embedded unity/mapbox view. it works well,except that the initialization is very long(about 15 seconds),and worse the a completely blocks the ui thread thus freezing the whole application. this pretty much kills my exciting use case,is there a way for me to speed this up or keep it from blocking the ui thread?

I know it's a map box issue because I can run in embedded and embedded unity arkit plug-in example and it starts fine without taking too long or blocking. it's only when adding mapbox does the problem surface.

I am on the latest unity and the latest map box plug-in from the develop branch.

@david-rhodes any suggestions? thanks!

**Comment by david-rhodes** [comment]
@etown Well, the first thing you should do is silently load your unity view in the background, before it is required (if you are not already doing so). Do this without loading a scene that has a map.

Then, it mostly comes down to being smart about your map resources. How many tiles are you requesting? What zoom level? Are you using vector data to build 3d meshes or spawn prefabs? All of these things take time.

That said, we do have plans to speed some of these things up (at least so they don't block the thread): #262

**Comment by etown** [comment]
Thanks!

I’m already initializing the view ahead of time. Also I’m not requesting many tiles at all,  And have reduced my vector data although The improvement was negligible.

It totally makes sense that this all takes time,  the major problem Is that it totally blocks the entire app. Obviously this makes it unmanageable from the user experience perspective.😔  I will wait until nonblocking loading arrives. Thanks for all your help!

**Comment by david-rhodes** [comment]
Closing in favor of #262
