### ISSUE TITLE
Labeling GameObjects with data sets

### ISSUE THREAD

**Issue by thedrummeraki** [mapbox/mapbox-unity-sdk#273]
Hello Mapbox Unity developers,

Using Mapbox's online tool for importing CSV data, we were able to generate data structures complementary (ie: cellular towers) to the buildings and road generated by Mapbox within Unity. The towers are positioned using their latitude and longitude provided by the CSV file, which works great.

However, we are trying to find a way to access the other data provided by the CSV data (such as: names, etc.). Knowing that this data is available on Mapbox's online style editor, we think there is a way access the same within Unity.

Is this functionality implemented? If so, are there any ways of accessing the data?

Let me know should supplementary information is needed such as screenshots or clarification on the issue.

Thank you, 
thedrummeraki

**Comment by david-rhodes** [comment]
@thedrummeraki If I understand correctly, you now have a custom tileset associated with your account, right (in Studio)? If so, use a `VectorTileFactory` just like we do for buildings in the included examples. You then change the `MapId` to your tile set's MapId. Lastly, you use the tile set's name for your `VectorLayerVisualizer` (name == layer, in this context). 

Finally, you can "composite" tiles on the server by concatenating MapIds with a `,`. Therefore, you only need one `VectorTileFactory`, even if you want your custom data **and** Mapbox Streets v7.

**Comment by thedrummeraki** [comment]
Yes, that's right, I do have a custom tileset in Studio. We were definitely able to use a `VectorTileFactory` for building both buildings and towers using different `VectorLayerVisualizer`, by concatenating the map ids in the factory. 

However, what we're trying to accomplish is finding a way to access the data that is used to build the custom dataset. Let me illustrate with an example: let's say the towers are built using **latitude** and **longitude** points. These coordinates are somehow read by the `VectorTileFactory`, which makes sense. But is there any way to access these **latitude** and **longitude** points without having to calculate them, after that have been built?

I was also thinking that this may be possible only by building the map exclusively using C#. What do you think?

Thank you,
thedrummeraki

**Comment by david-rhodes** [comment]
@thedrummeraki Maybe you could help me understand what you intend to do with these points, once they are extracted? Of course you can do what you're wanting--but where and how you should do that really depends on your use-case. You could explicitly add each latitude/longitude as properties in the dataset. Then, you simply access these values from the `VectorTileFeature` `Properties` property. Otherwise, what's the issue with using the `Conversions` calculations?

You can build maps in C# if you want, but we're provided this `Map Factory Framework` as a way to get started without any coding necessary.

**Comment by thedrummeraki** [comment]
@david-rhodes Oh, I am sorry, the latitude and the longitude was just an example. But what we're trying to accomplish is to identify each custom object separately. Here is a little screenshot of the tileset we have imported into Studio:

![image](https://user-images.githubusercontent.com/14348784/31100211-96684972-a796-11e7-871a-66ce059cd06b.png)

According to the image above, each object (so tower) is identified by LICENSEE, SERVICE, and STRUCT_HT. So, in Unity, we are trying to identify all towers given a LICENSEE.

Here is a little code snippet of what I am hoping to achieve:

```
VectorTileFactory factory = ....;
GameObject[] towers = factory.GetGameObjectsWithName("LICENSEE", "value here");
foreach (GameObject tower in towers) {
     // play with towers here...
}
```

As it stands, we were not able to find a method similar to `GetGameObjectsWithName`. Also, all towers generated in Unity have the tileset's name (here **Cleaned_Tower_Info_Short**). I will send a screenshot of what is generated once I have access to Unity.

Sorry about the confusion earlier.

**Comment by david-rhodes** [comment]
You will want to access the data inside a custom vector layer visualizer or in a custom modifier. Again, the vector data lives in the `VectorTileFeature` and `VectorFeatureUnity` `Properties` property. So, accessing this data would look something like:

```cs
var properties = feature.Properties;
object licensee;
properties.TryGetValue("LICENSEE", out licensee);
```

Alternatively, you can fetch the data (`VectorFeatureUnity`) directly from the `FeatureBehaviour`, which is a component added to each procedurally generated object that the vector tile factory is responsible for creating.

**Comment by thedrummeraki** [comment]
Alright, I figured out a way to extract the data from each tower. It was actually easier than I thought, I just had to dig it out.

I did something similar to the following:

```c#
if (CurrentNearest.GetComponent<FeatureBehaviour> () != null && ...) {
    FeatureBehaviour fb = CurrentNearest.GetComponent<FeatureBehaviour> ();
    Tower towerComp = CurrentNearest.GetComponent<Tower> ();
    VectorFeatureUnity data = fb.Data;
    towerComp.Populate (data.Properties);
}
```

This seems pretty efficient to me, so I don't think changes to this snipper are necessary. @david-rhodes Would it be okay if I made a pull request adding a bit of documentation (ie: comments) to some of the code's sections?

**Comment by david-rhodes** [comment]
@thedrummeraki Pull requests are always welcome--please do! Glad this worked for you!
