### ISSUE TITLE
Map not loading whan changing scenes

### ISSUE THREAD

**Issue by saniac18** [mapbox/mapbox-unity-sdk#274]
Hello ! I am developing with Mapbox for Android devices, I have several scenes and one of them is LocationProvider.

In my apk , the  first time I load that scene everything works fine, when I change to another scene and move back to LocationProvider, the map wont load. This happens in my  android device and bluestacks Emulator.

During playmode in Unity it all works fine

**Comment by david-rhodes** [comment]
@saniac18 Can you provide device logs, please? Are any objects in your scenes using `DoNotDestroyOnLoad`? Any other special circumstances you can think of?

**Comment by saniac18** [comment]
Not a single DoNotDestroyOnLoad in my project, I just have UI eelemnts and two 3D models. Also nothing specil in my logs. Everything works, just the map wont show again
