### ISSUE TITLE
Mapbox not showing on import

### ISSUE THREAD

**Issue by taroofizonfire** [mapbox/mapbox-unity-sdk#276]
When I import mapbox into Unity the menu item isn't appearing. I also get no error messages in the console regarding mapbox.

**Comment by brnkhy** [comment]
@taroofizonfire there must be something wrong with the import process. I'll have some questions first though;
(1) are you using the official release packages?
(2) can you see the `Mapbox` folder in Project folder, under `Assets` folder
(3) which version of Unity3d Editor you're using?

**Comment by david-rhodes** [comment]
@taroofizonfire Are you using Unity 2017.2?

**Comment by courtsimas** [comment]
@taroofizonfire did you completely remove the existing mapbox asset directory before importing the new sdk?

**Comment by brnkhy** [comment]
closing this for now.

**Comment by suraj1988** [comment]
Has this issue been resolved? Im experiencing the same problem. Mapbox menu refuses to show up in Unity 2017.1.
Tried the solution suggested by Berg to delete the AR folders from the assets but the overall instructions are clear as mud. once the bat file is updated, what needs to actually be done to get the menu to show up in Unity?
