### ISSUE TITLE
add error callbacks to AbstractTileFactory//MapVisualizer

### ISSUE THREAD

**Issue by isiyu** [mapbox/mapbox-unity-sdk#278]
Add to AbstractTileFactory or MapVisualizer an OnError event that we could register to. This event would be fired whenever data retrieval or rendering has failed for any reason, and it could pass an error code.

**Comment by david-rhodes** [comment]
@brnkhy @BergWerkGIS @apavani Do you have any specific implementations for this in mind? How far up should these errors bubble up?

**Comment by apavani** [comment]
One implementation that I could think of was to use a bubbling system from Tile to Factory to MapVisualizer to AbstractTileProvider. I need help understanding the flow of data and class hierarchy for that.

We can have a linked event model set up in each of the classes through a bubbling up system as follows:

    public event EventHandler EventFired
    {
        add { this.instance.EventFired += value; }
        remove { this.instance.EventFired -= value; }
    }

**Comment by isiyu** [comment]
PR here -> https://github.com/mapbox/mapbox-unity-sdk/pull/317
