### ISSUE TITLE
Missing references (json and VectorTile) in unity project on fresh download

### ISSUE THREAD

**Issue by mikaelhogstrom** [mapbox/mapbox-unity-sdk#279]
I just downloaded latest master and develop. When opening the unity project lots of references are missing. One of them is json so I just copied that into the project but there are still others missing like VectorTile. Is this just me missing an instruction to import a dll somewhere or did something break recently?

**Comment by BergWerkGIS** [comment]
@mikaelhogstrom downloading the repo as `zip` does not work.
You need to clone it and follow the instructions outline here: https://github.com/mapbox/mapbox-unity-sdk#dependencies

We could me more clear about that. I'll open a separate ticket to track that.

**Comment by mikaelhogstrom** [comment]
I must be misunderstanding the instructions then... 

_NOTE: As of May 16, 2017, the https://github.com/mapbox/mapbox-sdk-cs repo has been merged into this repo. These source files are now located here: /sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs. Core cs changes will be backported on a case-by-case basis._

I interpret this as I do not need to download mapbox-sdk-cs as it has been merged?

**Comment by BergWerkGIS** [comment]
Steps to get running from the repo.

Depending on how you've setup git on your machine:
```
git clone git@github.com:mapbox/mapbox-unity-sdk.git
```
or 
```
git clone https://github.com/mapbox/mapbox-unity-sdk.git
```

then

```
cd mapbox-unity-sdk
```

then

Windows: `update-mapbox-unity-sdk-core.bat`
Linux/Mac: `./update-mapbox-unity-sdk-core.sh`

**Comment by mikaelhogstrom** [comment]
Thanks I get it now, I just misunderstood the note as applying to all the dependencies :) 

I noticed that you also have the option to download some dll:s from Nuget. I really appreciate that, when possible would be great if more parts could be moved to nuget. I understand the issues with Unity's asset references and nuget packages with dll:s for different build targets makes it hard to do though. (Not impossible, one can always use a thin layer with monobehaviours inheriting from stuff inside the different dll:s)

**Comment by david-rhodes** [comment]
@mikaelhogstrom What significant advantage does nuget offer that that repo/unity package downloads do not offer? In our opinion, having full source code readily available is the best way to work with an SDK.

**Comment by mikaelhogstrom** [comment]
Disadvantages for me in my current project:

- Large project with many scripts. Adding more code gives longer compile times.
- I could put this in "plugins" folder but then will need to manually add new files in future updates when I update asset packages
- More files (on the order of thousands) makes the project view unwieldy to handle
- I really want to change something in Mapbox it's better to do a pull request and make sure I don't start diverging from main branch rather than having future merge conflicts. 
- Submodules and Unity seem to always screw up at some time for me. There's something with asset guids and stuff that doesn't play nice. This seems to show up after a while, at the worst possible time, and you end up losing lots of prefab/scene references.

Regarding compile times, it is possible to put mapbox in plugins instead but then if I import a new version of mapbox via an assetpackage any new files will manually have to be moved tio their corresponding plugins location.

I understand my needs are not universal and you guys need to find the best possible middle ground. If everyone else is happy then you're probably doing something right :)

Keep up the good work!

**Comment by BergWerkGIS** [comment]
@mikaelhogstrom thanks for your thoughts.

We used nuget packages in the beginning (hence the currently outdated packages on nuget.org) but we had to realize that this slowed down fast iteration cycles tremendously.

As you noticed we even moved [`mapbox-sdk-cs`](https://github.com/mapbox/mapbox-sdk-cs) directly into `mapbox-unity-sdk` to be able to even iterate faster.

From my point of view long term goal is to provide nuget packages/binaries again like we currently do for [Mapbox.Json-unity](https://github.com/mapbox/Mapbox.Json-unity).

But don't expect that to happen anytime soon for `mapbox-sdk-cs` and `vector-tile-cs` as they are still moving fast or planed refactorings are looming.

Short term we might at least provide binaries for [Mapbox.IO.Compression-unity](https://github.com/mapbox/Mapbox.IO.Compression-unity).

I've created a ticket for that https://github.com/mapbox/mapbox-unity-sdk/issues/284

**Comment by david-rhodes** [comment]
@mikaelhogstrom Thanks for the feedback. 

> Regarding compile times, it is possible to put mapbox in plugins instead but then if I import a new version of mapbox via an assetpackage any new files will manually have to be moved tio their corresponding plugins location.

We recommend users fully remove any existing Mapbox SDK before installing a new version 😉.
