### ISSUE TITLE
MapImageFactory "map id" -> "style url" on

### ISSUE THREAD

**Issue by isiyu** [mapbox/mapbox-unity-sdk#286]
![screen shot 2017-10-13 at 11 31 00 am](https://user-images.githubusercontent.com/8055815/31560685-20797f8e-b00a-11e7-9f93-d01285cbef4d.png)

to make @danswick 's eye stop twitching. Let's rename `Map ID` on "MapImageFactory" to `Style URL` this reflects the proper name for this identifier 

## Next Steps:
- [ ] Update MapImageFactory in SDK
- [ ] Update screenshots in tutorials

**Comment by brnkhy** [comment]
![unity_2018-01-22_15-28-53](https://user-images.githubusercontent.com/1465390/35220855-fce0086c-ff88-11e7-98b2-d418dd5ff0d6.png)
@danswick should we change the "Style Id" and/or "Id" in this panel as well? This is the "Custom" style options section.

**Comment by brnkhy** [comment]
fixed this on https://github.com/mapbox/mapbox-unity-sdk/tree/mapImageEditor
I'll merge after that possible custom style panel changes.

**Comment by MiroMuse** [comment]
@brnkhy should we close this ticket per your comment above?

**Comment by atripathi-mb** [comment]
Implemented in v1.4.0
