### ISSUE TITLE
Object not positioned correctly in in the DynamicZoomMapVisualizer

### ISSUE THREAD

**Issue by mdepak** [mapbox/mapbox-unity-sdk#287]
I am trying to use DynamicZoomMapVisualizer (zoom 16) with RangeTileProvider (all values set to 1). I tried to position game object with the script provided by @brnkhy in the issue https://github.com/mapbox/mapbox-unity-sdk/issues/123 but the game object is positioned way beyond the location. Is there any thing needs to be done for this DynamicZoomMapVisualizer. I tried creating a 'MapVisualizer' as mentioned in the tutorial but that option is not available in the menu. 
  
`	// Use this for initialization
	
void Start () {
		Map.OnInitialized += () =>
        {
            foreach (var item in Coordinates)
            {
                var latLonSplit = item.Split(',');
                var llpos = new Vector2d(double.Parse(latLonSplit[0]), double.Parse(latLonSplit[1]));
                var pos = Conversions.GeoToWorldPosition(llpos, Map.CenterMercator, Map.WorldRelativeScale);
                var gg = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                gg.transform.position = new Vector3((float)pos.x, 0, (float)pos.y);
            }
        };
	}
`

Map is centered at location (33.4483771,-112.07403729999999) and I'm trying to plot the game object at location (33.45448510816479,-112.07022428512573). Also map is positioned at location (0, 0, 0). Thanks.

**Comment by david-rhodes** [comment]
@mdepak At a glance, I think you should use the `DynamicZoomTileProvider`, rather than `RangeTileProvider`. Your map should of type `DynamicZoomMap`, as well. Please see the example scene: `DynamicZoom` to understand how all these components work in relation to one another.

**Comment by mdepak** [comment]
@david-rhodes I would be really helpful if you could redirect me to the examples of using mapbox 1.2 with unity. Thanks

**Comment by david-rhodes** [comment]
Apologies, but the only specific documentation we have for 1.2 are the changelog and list of examples:
- https://www.mapbox.com/mapbox-unity-sdk/docs/05-changelog.html
- https://www.mapbox.com/mapbox-unity-sdk/docs/03-examples.html

But, if you open the `DynamicZoom` scene, you should be able to see the components used in the scene. Additionally, if you use the new `Map Editor` (from Mapbox menu dropdown), you should see each scriptable object used for the map.

That said, we're also working on improving this specific example. I've also filed in an internal ticket for tracking potential conversions issues.

**Comment by david-rhodes** [comment]
This example is being replaced. Should be possible with the new example in `develop`.
