### ISSUE TITLE
Mapbox menu doesn't appear

### ISSUE THREAD

**Issue by SalmaBesbes** [mapbox/mapbox-unity-sdk#288]
i'm using Unity 5.6.2f, after importing the mapbox package i get these errors
Any fix for this? 
![capture](https://user-images.githubusercontent.com/27620651/31589056-29717f54-b1fb-11e7-95c6-de7f64ac072d.PNG)

**Comment by BergWerkGIS** [comment]
@SalmaBesbes 

* It means you have selected `Windows Store` as platform (`File --> Build Settings ...`) => **(1)** 
and that cannot be run directly in the editor (at least with 5.6, 2017 allows you to do it)
* You have to select another another platform => **(2)**
* And then click `Switch Platform` => **(3)**


![image](https://user-images.githubusercontent.com/4549888/31601134-110109cc-b259-11e7-94de-1f4fbb238d7a.png)

**Comment by BergWerkGIS** [comment]
@SalmaBesbes `5.6` is not supported by the latest version of the SDK:
https://github.com/mapbox/mapbox-unity-sdk#for-unity-20171

You _might_ get it to run by making the changes outlined below, **but it's not supported** as there were [quite some changes being made](https://github.com/mapbox/mapbox-unity-sdk/commit/5bf5aab7b9e1063e8432dfbe2fd1f222dfcc2626#diff-4d555e86f50b1343b5b0682b838b7d86) for 2017.

Please use an older version of the SDK or update Unity (recommended).

-------------

* Replace
  ```
  #if UNITY_2017_1_OR_NEWER
  ```
  with
  ```
  #if UNITY_EDITOR || UNITY_STANDALONE || UNITY_ANDROID || UNITY_WP_8_1 || UNITY_WSA || UNITY_WEBGL || UNITY_IOS || UNITY_PS4 || UNITY_SAMSUNGTV || UNITY_XBOXONE || UNITY_TIZEN || UNITY_TVOS
  ```
  [here](https://github.com/mapbox/mapbox-unity-sdk/blob/ae217436ea40fd8090c97f5f863566a21f5dec2e/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Response.cs#L7)
* Replace `apiResponse.isNetworkError` with `apiResponse.isError` [here](https://github.com/mapbox/mapbox-unity-sdk/blob/ae217436ea40fd8090c97f5f863566a21f5dec2e/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Response.cs#L243)
