### ISSUE TITLE
Changing map location at runtime

### ISSUE THREAD

**Issue by thedrummeraki** [mapbox/mapbox-unity-sdk#289]
Hello there,

What I am trying to accomplish is very simple. Let's say I first load my map at the coordinates `45.33, -75.66` (Ottawa, Canada). Everything is perfect.

If I want to go to coordinates `43.65, -79.38` (Toronto, Canada) **at runtime**, is this possible?

I have had a look at other issues. From I could understand, I need a `MapImageFactory`. I am not too sure if I can just create an instance like `MapImageFactory fact = new MapImageFactory()` or get it from somewhere else.

Also, I have tried getting the current `AbstractMap`, a `MapVisualizer` and an `AbstractTileProvider` (the same instances used for the `AbstractMap`) and did the following:

```c#
public AbstractMap map;
public MapVisualizer mapVis;
public AbstractTileProvider tileProv;

public void Method() 
{
    // make sure everything is set
    if (map == null || mapVis == null || tileProv == null) return;
    tileProv.Initialize(map);
    mapVis.Initialize(map, MapboxAccess.Instance);
}
```
As you can see, I basically just tried to re-initialize the map. I anticipated it wouldn't work, so...
Finally, I saw that I can use the `Dispose/LoadAllTiles` method to basically dispose of all tiles and just redraw them, which make perfect sense. I have a feeling this might get the job done, although in a hacky way. That always works well! If so, where would be the best to have access to these methods? I looked at the doc and couldn't find anything helpful.

Any thoughts? Am I missing something? Is it even possible?

Thank you for your input,
thedrummeraki

**Comment by thedrummeraki** [comment]
I forgot to add additional information about my Mapbox Unity version: according to the README:
`Current version: 1.1.0, as of 08/01/2017`

I downloaded this version on https://www.mapbox.com/install/unity/.

Also, I just thought of something: maybe I can dispose of the current instance of `AbstractMap` from a `GameObject`, create a new `AbstractMap` (with the new coordinates) and attach it to the same `GameObject` using the same `MapVisualizer` and `AbstractTileProvider`.

Any thoughts? I will try on my side and fire any updates. Thank you

**Comment by david-rhodes** [comment]
@thedrummeraki Just download and install v1.2.0 (from the same link you posted above). Inside, there is a new example: `MapReload`. This example shows how to accomplish precisely what you want. Essentially, you initialize a map with a latitude/longitude, and a zoom level. The tile recycling is handled automatically.

**Comment by thedrummeraki** [comment]
@david-rhodes Wonderful. Thank you for the update. I am now able to change locations, _very_ easily. Also the automatic tile recycling process is very helpful, thank you!

**Comment by reubenkcoutinho** [comment]
Is there a way I can see the MapReload example in v1.3.0?

**Comment by atripathi-mb** [comment]
@reubenkcoutinho MapReload is integrated with most of the examples in v1.3.0. Check for `ReloadMapCanvas` in the scene hierarchy  or a script called `ReloadMap`.
