### ISSUE TITLE
Inaccurate conversions

### ISSUE THREAD

**Issue by thedrummeraki** [mapbox/mapbox-unity-sdk#294]
Hello there,

I am having trouble with geo coordinates since I upgraded to v.1.2.0 from https://www.mapbox.com/install/unity/.

Basically, given a Unity `Vector3` position (ex: `-15.625, 0, 18.75`, from the `AbstractMap.Root.Transform.position`), the expected latitude would be something like `45.4192, -75.692`, but gives something like `45.4159, -75.6923`.

On our side, we haven't changed anything that changes the precision of the conversion.

I should also specify that the map is not positioned correctly for a given latitude, so that might be part of the issue. Any ideas?

Thank you,
thedrummeraki

**Comment by david-rhodes** [comment]
@thedrummeraki When you request a map for a specific latitude/longitude, you are requesting that the center map tile contains those coordinates--nothing more. The center of the tile is not likely to be the coordinates that you requested. If you want this functionality, you should either use `DynamicZoomMap` or `MapAtSpecificLocation` components. These actually offset the map transform to center at your specified location.

However, if you use this approach, you must be sure to include the root's offset when performing conversions. In other words, perform your conversion and subtract the root position.

**Comment by thedrummeraki** [comment]
@david-rhodes That makes sense. I am actually already using `MapAtSpecificLocation`. But just to clarify, was the old `AbstractMap` initializing the map similarly to `MapAtSpecificLocation` or to `BasicMap`? If the latter, then I think I was not converting positions properly on v.1.1.0. I basically converted the `AbstractMap` script to `MapAtSpecificLocation`.

I just replaced `MapAtSpecificLocation` with `BasicMap` and it gave to the desired output.

**Comment by david-rhodes** [comment]
`AbstractMap` in v1.1.0 was more akin to `BasicMap`. It sounds like all you need to do is account for your root transform offset, and `MapAtSpecificLocation` will still work.

**Comment by david-rhodes** [comment]
Tracking here: https://github.com/mapbox/mapbox-unity-sdk/issues/296

**Comment by thedrummeraki** [comment]
Great @david-rhodes if it's a bug, I'll have a look at it when I get back home! Thanks for the tips.

**Comment by 1701Tiberius** [comment]
Hi - I have been working with v 2.0.0 and cannot find MapAtSpecificLocation (using Map Manager with script AbstractMap attached). I am seeing the same inaccuracy when restoring lat longs and converting them to transforms. Thank you for any help you can offer.

Kindest Regards,
Garry
