### ISSUE TITLE
Is it possible to get the landmarks position

### ISSUE THREAD

**Issue by aiursrage2k** [mapbox/mapbox-unity-sdk#295]
Is it possible to get landmarks position for example in the texture raster tile it generates markers like subway, restaurants, etc what we want to do is have images land in these positions but we had to do this manually rather then dynamically. Seems like a waste if you guys already have the data.

**Comment by MiroMuse** [comment]
@aiursrage2k going to close this ticket - feel free to reopen if you need further help 👍
