### ISSUE TITLE
Map Root Transform should be taken into consideration for Conversions

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#296]
Currently, conversions rely on the map root being at (0, 0). If the map is offset, additional calculations must be performed. I propose that we simply pass `IMapReadable` to any method that needs map aspects in order to perform a conversion. Since this includes the root, those additional operations can be performed implicitly. 

New methods should be overloads and old methods can optionally be marked as obsolete.

**Comment by brnkhy** [comment]
I'm not sure about passing IMap to conversion methods. I feel like conversion methods should be as agnostic as possible (I know we're passing ref point and scale but still). I feel like it doesn't really assume map is on (0,0), it just does conversion in a regular space and turns you the value. Then you can modify those values further if you have different logic, like offset maps. So I think that part should be on game logic or something.
so correct me if I'm wrong but, 
- this shouldn't be trouble if they create new objects as map root's child
- if not they can simply add map root pos to offset their custom objects as well.
So it shouldn't be a problem anyway.

**Comment by david-rhodes** [comment]
Fair point @brnkhy. What if we create an overload that takes an optional offset `transform`? This transform would be queried for position offset and additional scale?

**Comment by david-rhodes** [comment]
Partially handled in #387. We need the inverse. cc @atripathi-mb 😏 ?
