### ISSUE TITLE
Unity Crashes When using Mesh Collider on SpawnInsideModifier

### ISSUE THREAD

**Issue by AliasSCM** [mapbox/mapbox-unity-sdk#299]
Im trying to add simple 3d objects (trees , bushes etc) for my "landuse" layer. To do this im using the ParkLayerVisualizer provided by the SDK. Here's how ive set it up...
![screen shot 2017-10-17 at 11 37 09 pm](https://user-images.githubusercontent.com/15645920/31682207-0a9ad114-b397-11e7-8a20-2890b9d89e08.png)
![screen shot 2017-10-17 at 11 37 17 pm](https://user-images.githubusercontent.com/15645920/31682213-0ec47cfe-b397-11e7-9038-61f93910dd44.png)
![screen shot 2017-10-17 at 11 37 21 pm](https://user-images.githubusercontent.com/15645920/31682219-130ebd60-b397-11e7-815a-b5a59f919922.png)
![screen shot 2017-10-17 at 11 58 53 pm](https://user-images.githubusercontent.com/15645920/31682283-376f6a2e-b397-11e7-9c18-b6545456caf8.png)

When i run this Unity itself crashes. @david-rhodes mailing you the crash log for you this...

In the crash log i could see some issues with the MeshCollider so i changed the collider from "Mesh" to "Box" in my "ColliderModifier" Component on my "ParkModifierStack". This stopped unity from crashing, but i dont see any of the 3d objects that is supposed to be placed. Here is a screengrab of the output...
![screen shot 2017-10-17 at 11 55 09 pm](https://user-images.githubusercontent.com/15645920/31682480-cbc92e1c-b397-11e7-9e04-0e92004b1419.png)

The location im trying to render is : 12.941848, 77.585459

Im using Unity 2017.3.0b2

**Comment by david-rhodes** [comment]
@AliasSCM at a glance, you need to specify your layer mask. Without a proper layer mask, you will never spawn an object, and the modifier will never succeed (infinite loop).

**Comment by AliasSCM** [comment]
@david-rhodes thanks for the response.

I just tried setting the SpawnModifiers layer mask to a number of options but the results were the same. I can see that the GO has been created as you can see from the Scene Editor, but the prefab (Tree) just does not show up...

**Comment by david-rhodes** [comment]
The game object being created (that you see in the hierarchy) has nothing to do with the actual prefabs that you are trying to spawn (other than acting as a placeholder parent). So, your raycasts are likely not succeeding. 

Did you also change the `layer modifier` to the same layer as the `layer mask`?

If you open the SDK example `StylingDemoMeshGeneration` does everything work as expected? What if you change the location?

**Comment by AliasSCM** [comment]
@david-rhodes thanks for the response. I had not set the `layer modifier`  and `layer mask` to the same. But when i did do so, there was no difference. This is how ive set it up

![screen shot 2017-10-18 at 2 42 34 pm](https://user-images.githubusercontent.com/15645920/31710592-15e50b08-b413-11e7-89b2-b3108f139530.png)
![screen shot 2017-10-18 at 2 42 45 pm](https://user-images.githubusercontent.com/15645920/31710595-18055c62-b413-11e7-8f91-fe9a79627617.png)

Even in the `StylingDemoMeshGeneration` i do not see any of the 3d objects, heres a screengrab of what im seeing
![screen shot 2017-10-18 at 2 33 26 pm](https://user-images.githubusercontent.com/15645920/31710648-470f09e0-b413-11e7-82bd-bde64495816c.png)

But i should mention that when trying to get this to work i could see the 3d objects for my location once, i have not been able to reproduce that again!

**Comment by david-rhodes** [comment]
Is this our SDK in your own project, or our `sdkproject`? Also, have you tried a non-beta version of Unity?

This is what I see at your location from the example scene.
![screen shot 2017-10-18 at 9 05 41 am](https://user-images.githubusercontent.com/23202691/31726216-8e56c048-b3e3-11e7-976e-e4317bca7775.png)

**Comment by AliasSCM** [comment]
I re-imported the mapbox package and tried the StylingDemoMeshGeneration and this is the result i am seeing..
![screen shot 2017-10-19 at 4 39 45 pm](https://user-images.githubusercontent.com/15645920/31769168-0535489e-b4f0-11e7-8184-edff37cf1e2c.png)

The 3d objects do not get rendered. Also, i have changed the `ParkColliderModifier` to `Box` as using `Mesh` was crashing it. Not sure if this is the reason its not showing up...

**Comment by david-rhodes** [comment]
A box collider just will not work. You'll end up spawning objects where they do not belong. I recommend you switch back to mesh collider (now that you've specified layers--although I recommend you use a custom layer that is not `default`). Then, use an official unity release (non-beta). If that doesn't work, I cannot debug unless you give me a unity project in which I can reproduce this issue.

**Comment by AliasSCM** [comment]
I downloaded the latest stable version of unity (2017.2.0f3) and everything works as expected. Seems like the issue was with the beta version of unity and mesh collider works now. @david-rhodes have sent you a crash log for the crash on 2017.3.0b2 anyway. Thanks for the help!

**Comment by david-rhodes** [comment]
@AliasSCM Glad to hear! Unity betas for 2017+ have had quite a few issues so far. Please keep that in mind for the future.
