### ISSUE TITLE
What coordinates to use in UnwrappedTileID?

### ISSUE THREAD

**Issue by Sajdkick** [mapbox/mapbox-unity-sdk#305]
I've dug through the documentation and managed to get a tile using pngRasterTile.Initialize, but i can't figure out what coordinates to use. I've inserted some random values and i've managed to get something, but i can't find any information on how to get the coordinates for a specific location. 

Here's a pastebin of my code:
https://pastebin.com/pbjaquUF

Thanks!

P.S. A discord where i could ask these simple questions would be amazing ;)

**Comment by BergWerkGIS** [comment]
@Sajdkick check out
* [`MetersToTile`](https://github.com/mapbox/mapbox-unity-sdk/blob/d0f4f6c9c5380a6aa89f54822357450064647d04/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L123-L142) in case you are using WebMercator coordinates
* [`LatitudeLongitudeToTileId`](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L164-L178) for WGS84

**Comment by Sajdkick** [comment]
Worked like a charm! Thanks for the fast response!

**Comment by david-rhodes** [comment]
@Sajdkick You can also use `TileCover` (especially useful if you want to get a geographic bounds with many tiles): https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/TileCover.cs.
