### ISSUE TITLE
Draw a dot on a latitude longitude coordinate within a RawPngRasterTile

### ISSUE THREAD

**Issue by Sajdkick** [mapbox/mapbox-unity-sdk#307]
I've managed to render a grid of tiles and i can move the map around by updating these tiles. Now i want to draw a red dot on the exact position of the players GPS. I see no options for getting a more precise position from the RawPngRasterTile, do i have to switch to something else?

This is what i want to achieve: https://imgur.com/a/KWtgL

Thanks in advance!
Pontus Björkberg, Crunch Studios

**Comment by david-rhodes** [comment]
@Sajdkick A couple questions to help me better answer your question:

1. Are you are using the built-in Map Factory Framework? Factories and tile providers?
2. Raw png raster tiles are usually associated with our global elevation (terrain) model, is this what you are referring to? Or just a simple raster map?

There are a few examples of how to accomplish this conversion in our SDK (see `DirectionsFactory.cs`). But, the gist is to have a reference to your map object (`IMap`). With this, you can use our `Conversions` library to convert from geo coords to unity coords:

```cs
var position = Conversions.GeoToWorldPosition(37.808596, -122.412537, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz();
```

**Comment by Sajdkick** [comment]
1. No i'm writing my own stuff for that.
2. When digging through the examples, i was looking for a way to get a hold of the height maps and found that i could do it with the RawPngRasterTile.Initialize. And because i could fetch all kinds of maps with it i decided just to use this for getting all my tiles. 

Here's a link to my repository if you want to look at the code:
https://github.com/Sajdkick/Fishing-Time-Golf

I'll look into the GeoToWorldPosition, and see if i can do something with IMap. Thanks!

**Comment by Sajdkick** [comment]
I solved it, kind of. I now fetch the coordinates in meters from the closest tile and the coordinates i want the position for. I then take the difference between them and use Conversions.GetTileScaleInMeters to calculate  the position in unity.

    Vector3 Coordinate_To_Position(float latitude, float longitude)
    {

        TileObject closestTile = GetClosestTile(latitude, longitude);
        UnwrappedTileId closestTileId = closestTile.tileID;
        Vector2d centerCoords = Conversions.TileIdToCenterLatitudeLongitude(closestTileId.X, closestTileId.Y, closestTileId.Z);
        Vector2d meterOffset = Conversions.LatLonToMeters(new Vector2d(latitude, longitude)) - Conversions.LatLonToMeters(centerCoords);

        float tileScale = Conversions.GetTileScaleInMeters(latitude, zoom);
        Vector2d pixelOffset = meterOffset / tileScale;
        Vector2d worldOffset = pixelOffset / 256.0f;

        return closestTile.transform.position + new Vector3((float)worldOffset.x/2, (float)worldOffset.y/2, 0);
        
    }

It works, but for some reason i have to divide the offset by two before applying it.

Thanks for the fast answers, i'm having a really great time playing around with Mapbox!
