### ISSUE TITLE
Unable to add AbstractMap component to the Map object

### ISSUE THREAD

**Issue by williamgurney** [mapbox/mapbox-unity-sdk#309]
Error "Can't add script behaviour AbstractMap. The script class can't be abstract!"

Using Unity 2017.2.0f3
Following this guide https://www.mapbox.com/help/unity-mesh-pt-1/

Thank you for your help

**Comment by david-rhodes** [comment]
As per the changelog (https://www.mapbox.com/mapbox-unity-sdk/docs/05-changelog.html): 

> AbstractMap has officially been abstracted! This means that you must substitute, in your own scenes, a concrete implementation. We offer BasicMap, MapAtSpecificLocation and DynamicZoomMap.

We'll update tutorials soon. Just use one of these concrete classes for now, please.
