### ISSUE TITLE
Remove `HideInInspector` attributes from DynamicZoom components

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#311]
These components prevent assignment of necessary dependencies (camera, for example). These should either be assignable via `SerializeField` or injected from a central component (`DynamicZoomMap`, perhaps?).

**Comment by BergWerkGIS** [comment]
> injected from a central component (DynamicZoomMap, perhaps?).

That was the reasoning behind using `[HideInInspector]`: to expose the reference camera in one spot in the GUI and pass it on to the other parts that need it.

Somehow that one spot seems to have get lost during the countless refactorings.
Currently it gets auto-assigned along these lines in [`DynamicZoomCameraMovement.cs`](https://github.com/mapbox/mapbox-unity-sdk/blob/55a553cdd247f0494bb30ef72e100943b9f11b5c/sdkproject/Assets/Mapbox/Examples/Scripts/DynamicZoomCameraMovement.cs#L28-L32).
