### ISSUE TITLE
Add additional procedural decoration modifiers/factories

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#313]
**Context:** Developers would like the ability to procedurally decorate their virtual worlds based on Mapbox data (Landuse, for example).

**Problem:** Current `SpawnInsideModifier` is limited, slow, and requires quite a bit of setup. 

**Solution:**  Perhaps something like [this]( https://github.com/mapbox/mapbox-unity-sdk/commit/944966f4da715fa3bf95c747090de7d065303e77#commitcomment-23144298)? We could try to create these in tile coordinates for efficiency and access to raw data (for flexibility). Discuss?

**Next Steps**
- [ ] Discuss/brainstorm? 
- [ ] Any developers want to chime in with their specific requests/use-cases here?
- [ ] Port the above implementation to our SDK

**Comment by MiroMuse** [comment]
Love the formatting 😃  🎊

**Comment by brnkhy** [comment]
OK I read the title and misinterpreted this yesterday. started with #228 and posted my findings there, I'll check spawn stuff later as well.

**Comment by mihakrajnc** [comment]
Here are some of the custom ones I'm using:

- RandomPrefabTileFactory (AbstractTileFactory)
  - Has a list of prefabs, places them evenly on a tile, randomly selecting one from the list each time (e.g. for grass or shrubs)
- AreaPrefabModifier (GameObjectModifier)
  - Modifies the size of the object based on the size of the area (e.g. big church = big crystal)
- ColorFilteredPrefabModifier (GameObjectModifier)
  - Pff, this one triangulates an area (e.g. landuse/park), evenly distributes prefabs in that area based on a density value, then raycasts to get the color of the texture beneath a prefab, and either places it or not (e.g. doesn't place prefabs on roads that go through a park and are colored differently). Could probably be done with vector data instead.
- PositionModifier (GameObjectModifier)
  - Moves the GO by a Vector3 amount.

**Comment by brnkhy** [comment]
@mihakrajnc awesome ideas!

I did PositionModifier for demos before but we never released it. It's just a one line modifier but I think would be good to have.
I like the ColorFilteredPrefabModifier  idea, would probably be quite slow but would enable some fun stuff.
AreaPrefabModifier sounds to specific, maybe we can generalize it somehow.
we really need RandomPrefabTileFactory asap, only problem with that is I want to find a good, fast, reliable random point generator before diving into that. And this should be a well-solved problem so I don't want to roll my own either. Gotta do some research on that (random points in polygon/triangle)

**Comment by mihakrajnc** [comment]
Hmm, for the `RandomPrefabTileFactory` I just used this:

```csharp
private void CreatePrefabs(UnityTile tile)
{
    for (int i = 0; i < count; i++)
    {
        double tileSizeX = tile.Rect.Size.y;
        double tileSizeY= tile.Rect.Size.y;
        
        float randomX = Random.value;
        float randomY = Random.value;

        float posX = (float) (tileSizeX * randomX - tileSizeX / 2);
        float posY = (float) (tileSizeY * randomY - tileSizeY / 2);
        
        Vector3 randomPos = new Vector3(
            posX,
            tile.QueryHeightData(randomX, randomY),
            posY);

        randomPos += tile.transform.position;

        GameObject go = Instantiate(prefabs[Random.Range(0, prefabs.Length)], randomPos, Quaternion.identity);
        go.transform.localScale = Vector3.one * scale;
        go.transform.SetParent(tile.transform, true);
    }
}
```

I also hooked this to `OnHeightDataChanged`. It works perfectly for my cases, but it might look weird with steep terrains, as each tile will only get X prefabs, regardles of it's area, so it might be a better idea to actually triangulate the area of a tile and use that.

As for the `ColorFilteredPrefabModifier` I used Earcut to triangulate the vector data and went from there. For random points in a triange and triangle area I used this:

```csharp
public static Vector3 RandomPointInTriangle(Vector2 v1, Vector2 v2, Vector2 v3)
{
    float r1Sqrt = Mathf.Sqrt(Random.value);
    float r2 = Random.value;

    float x = (1 - r1Sqrt) * v1.x + (r1Sqrt * (1 - r2)) * v2.x + (r1Sqrt * r2) * v3.x;
    float y = (1 - r1Sqrt) * v1.y + (r1Sqrt * (1 - r2)) * v2.y + (r1Sqrt * r2) * v3.y;

    return new Vector2(x, y);
}

public static float TriangleArea(Vector2 v1, Vector2 v2, Vector2 v3)
{
    float a = Mathf.Sqrt((v2.x - v1.x) * (v2.x - v1.x) + (v2.y - v1.y) * (v2.y - v1.y));
    float b = Mathf.Sqrt((v2.x - v3.x) * (v2.x - v3.x) + (v2.y - v3.y) * (v2.y - v3.y));
    float c = Mathf.Sqrt((v1.x - v3.x) * (v1.x - v3.x) + (v1.y - v3.y) * (v1.y - v3.y));

    // Heron's formula for area calculation
    // area = sqrt( s * (s-a) * (s-b) * (s-c))
    float s = (a + b + c) / 2;

    return Mathf.Sqrt(s * (s - a) * (s - b) * (s - c));
}
```

If I remember correctly that formula will distribute points evently in a triangle (as evenly as you can that is, with _complete randomness_).

You can check out the complete modifier here: https://gist.github.com/mihakrajnc/c7f46ba9a136c1dab1ee36c5cd7dfc47

Could probably use some work :)
