### ISSUE TITLE
Map not loading on Android devices (LocationProvider)

### ISSUE THREAD

**Issue by kvdesa** [mapbox/mapbox-unity-sdk#314]
Hello!
I am developing with Mapbox for iOS and Android devices, I have just one scene which uses LocationProvider.

The problem is that when I build on my Android device to test, the map does not load. However, when I build it on my iOS device, the map loads just fine! In the Unity Editor it works fine as well...

I based my project on both the LocationProvider and the SlippyTerrain examples. My LocationProvider gameobject has the LocationProvider Factory script:

https://imgur.com/vBW0kml
![image](https://user-images.githubusercontent.com/12987977/31868602-935449b8-b77f-11e7-8635-a738f8cde1b0.png)

The Map gameobject has the BasicMap, Camera Bounds Tile Provider and Initialize Map With Location Provider scripts:

https://imgur.com/gh3JAsD
![image](https://user-images.githubusercontent.com/12987977/31868609-a830b70e-b77f-11e7-967b-59092ab82691.png)

Finally, my Player object has the Position With Location Provider script:

https://imgur.com/hZwBvvy
![image](https://user-images.githubusercontent.com/12987977/31868612-afc900f2-b77f-11e7-9601-142fd6e18352.png)

I have always tested my project on my iPhone 6 and never tested it on Android. This was the first time and it is not working! I am trying everything but it just won't load the map.

The device I am trying to test is Samsung A5 2017 and my Unity version is 2017.1.0f3.
I was using the v1.1.0 of Mapbox SDK and it did not work on Android devices. Updating to the latest version (v1.2.0) does not resolve the problem.

Can anyone help me, please?

Here is the link to download my project: https://drive.google.com/open?id=0ByCfjMusATy3a0lyRjNFSFhPTlE

**Comment by david-rhodes** [comment]
@kvdesa Honestly, the best thing you could provide to help us debug are the android device logs (see logcat). My guess is that you need to give your application access to location data (could be a permissions issue).

**Comment by kvdesa** [comment]
@david-rhodes When the app starts on the device, I am prompted about allowing the use of Locations, so I guess that is not the problem. Also, to be sure, I checked on the Android settings and  the app is marked as allowed to use it.

I will generate the logs and attach here then, because I am losing my mind trying to figure what I did wrong.

**Comment by kvdesa** [comment]
@david-rhodes Here is the log:
[log.txt](https://github.com/mapbox/mapbox-unity-sdk/files/1408470/log.txt)

I used the Unity tag to filter it.

**Comment by kvdesa** [comment]
I really don't know what is wrong. Right now I am trying to use a custom AndroidManifest file with these INTERNET, ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION permissions. Still, the map does not load...

**Comment by kvdesa** [comment]
@david-rhodes Ok, I think I found the issue. I was testing on my father's phone (Moto G) and I noticed that on the Upper bar (where you can enable all the options like celular data, auto-rotation and such) there was a option called Location. After enabling it there, the map starts to load.
I guess I am obliged to manually enable Location so that my app may use it?

I will try this on the Samsung A5 2017 as well. I am sorry if forgetting to manually enable Location on the upper bar was the problem, but I am an iOS user, so I had no idea this was an obligation for it to work. I thought that when asking for permissions the app automatically requests Android to turn it on. Is this the correct way? Or is there a way to manually, via code, to enable the Locations so that the user does not need to enable it manually?

**Comment by david-rhodes** [comment]
I suspect this is an android manifest issue, but I've never worked much with those. I've also never seen this issue when I build to my Pixel (but I don't use any custom manifests).

@zugaldia Are you aware of any (recent?) Android development practices that would require manually enabling location services?

**Comment by BergWerkGIS** [comment]
> I thought that when asking for permissions the app automatically requests Android to turn it on. Is this the correct way? Or is there a way, via code, to enable the Locations so that the user does not need to enable it manually?

@kvdesa 
If location is disabled you cannot activate it via code.

@david-rhodes 
We should definitely add a check if location is available.
I add the enhancement and bug labels.

**Comment by zugaldia** [comment]
As @BergWerkGIS points out, even if the user has granted the app access to location, if the user has also manually disabled location system-wide (e.g. in the settings) the app (any app) won't be able to access any location data.

> The strange thing is that although I added 3 permissions, only Location is showing in the Settings on the Device. 

This is to be expected, both `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION` are under the "location" category. In fact, once you have included `ACCESS_FINE_LOCATION` you don't need to include `ACCESS_COARSE_LOCATION` in your manifest because it includes permissions for `ACCESS_COARSE_LOCATION` providers too.

**Comment by david-rhodes** [comment]
From Unity docs: https://docs.unity3d.com/ScriptReference/LocationService.Start.html

> On Android using this method in your scripts will automatically add ACCESS_FINE_LOCATION permission to the android manifest.

As for checking if location services are available, we do this, we just don't log the exception. I'll add this now, since I'm working in those files.

**Comment by kvdesa** [comment]
@BergWerkGIS Facebook does provide a way to turn on Location after the user has allowed the app to use it. If I open Facebook and try to check-in a place, a button asking the permission for Location appears. After allowing, the button changes and now it asks if the user wants to turn on Location, and if the user taps it, the location is turned on without the user needing to manually do it.

The same happens with Tinder, it first asked whether the user allows the app to use Location and then it asks if the user allows the app to turn on Location.

Does Mapbox provide a way to do this? It only asks for permission on Location, but does not ask whether the user wants to turn it on.

Furthermore, I would like to know if there is a method or something that detects if the user has manually turned on Locations while using the app. If I open the app with Location off and, while using the app, turn Location on, the map does not load. I must close and open it with Location already on so the map can load properly.

**Comment by david-rhodes** [comment]
@kvdesa We are simply using Unity's `Input.location` wrapper to access this stuff. You can see the note here about how iOS is handled: https://docs.unity3d.com/ScriptReference/LocationService-isEnabledByUser.html.

> On iOS, if this property is false and you start location updates anyway, the CoreLocation framework prompts the user with a confirmation panel asking whether location services should be reenabled. The user can enable or disable location services altogether from the Settings application by toggling the switch in Settings>General>LocationServices.

It doesn't seem the same is provided for Android (or least I don't see it). I'm guessing this is due to varying OS requirements. Therefore, this implementation would probably fall to you. Usually, you should query if location is enabled, and if it is not, prompt the user to manually enable via OS settings.

> Furthermore, I would like to know if there is a method or something that detects if the user has manually turned on Locations while using the app. If I open the app with Location off and, while using the app, turn Location on, the map does not load. I must close and open it with Location already on so the map can load properly.

I don't think this is available out of the box unless you have a loop checking (see `DeviceLocationProvider` as a starting point). However, you could implement https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationPause.html to check if location is enabled (if it previously was not).

**Comment by daniel-bogdoll** [comment]
Hey @david-rhodes any updates on this topic? I have the same issue: The map is not loading during the first start of the app, when the user is asked for location permissions (Android).

**Comment by k3ndro-valari** [comment]
Same here. They have to restart the app to make it work
