### ISSUE TITLE
First iteration: VT parsing with 'BackgroundWorker'

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#318]
### synopsis

* pros
  * low hanging fruit:
    * easy to implement transparently
    * doesn't come with the hassles `clipped-vt-branch` would (new cache format, binary serializer)
  * performance improvement greater than `clipped-vt-branch`: **~13.6sec => ~9.4secs (~30%!!!)**
  * drops lazy loading of layers and geometries and pre-caches those: other Unity specific code might become faster, too
* cons
  * not final implementation
  * distributes work **within _one_ frame** across several processors but not across several frames
 

tested with **`StylingDemoMeshGeneration`** on
* ✅ Unity Editor on Windows
* ✅ Windows native x64
* ✅ Android

### technical details

* branch [`brackgroundworker`](https://github.com/mapbox/mapbox-unity-sdk/compare/brackgroundworker?diff=split&name=brackgroundworker)
* scene **`StylingDemoMeshGeneration`**

**current implementation:**
First frame takes `~13.6 seconds`, ~5 seconds being spent on `ParseTileData()`:
![image](https://user-images.githubusercontent.com/4549888/31942591-1f36a272-b8c6-11e7-9e36-3db4c8d34b40.png)

**`BackgroundWorker`:**
On my 4 CPU laptop first frame drops to `~9.4 seconds` and `ParseTileData()` drops to `~762ms(!)` shaving off **~4 seconds (almost 30%)**:
![image](https://user-images.githubusercontent.com/4549888/31942778-c6dfed6c-b8c6-11e7-970b-e6a85ecc89fa.png)

### try for yourself

actual code is pretty short and I've left original implementation in there for easy comparison (just un/comment the part you are interested/not interested in):

* previous implementation: [VectorTile.cs#L221-L233](https://github.com/mapbox/mapbox-unity-sdk/blob/d4d7b3444ae321213cf781706cdf864dc55dee1e/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/VectorTile.cs#L221-L233)
* with `BackgroundWorker`: [VectorTile.cs#L175-L213](https://github.com/mapbox/mapbox-unity-sdk/blob/d4d7b3444ae321213cf781706cdf864dc55dee1e/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/VectorTile.cs#L175-L213)

**Comment by david-rhodes** [comment]
@BergWerkGIS So, I tried testing (and timing) this, but did not find any conclusive gains. Here is the script I used:

```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mapbox.Unity.Map;

public class LogMapBuildTime : MonoBehaviour 
{
	[SerializeField]
	AbstractMapVisualizer _mapVisualizer;

	void Awake()
	{
		_mapVisualizer.OnMapVisualizerStateChanged += _mapVisualizer_OnMapVisualizerStateChanged;
	}

	float _startTime;

	void _mapVisualizer_OnMapVisualizerStateChanged(Mapbox.Unity.Map.ModuleState obj)
	{
		if (obj == ModuleState.Initialized)
		{
			_startTime = Time.realtimeSinceStartup;
		}
		else if (obj == ModuleState.Finished)
		{
			Debug.Log("LogMapBuildTime: " + (Time.realtimeSinceStartup - _startTime));
		}
	}
}
```

On my iPhone 6s+ the old version actually finished first (59 seconds versus 61 seconds for 121 tiles in MeshGeneration.unity--within a margin of error). I should add that I pulled `develop` in to get other performance improvements and to test compatibility. Unsure if this matters ATM.

In any case, I'm wondering if the gains you see are due to the profiler not attempting to profile threaded tasks, and therefore **appears** to take less time. I did a simple timer, so profiler had no overhead. Thoughts?

**Comment by brnkhy** [comment]
@BergWerkGIS I'm not sure about this but I think profiling single frame here might be misleading. That should be just the thread start in that frame and all other work would be in following frames right (even if it's profiled)? I think start/finish timer, like @david-rhodes suggested, would be a better figure.

**Comment by BergWerkGIS** [comment]
> That should be just the thread start in that frame and all other work would be in following frames right (even if it's profiled)?

Not sure, I'm [not breaking out of the frame: `while (!done) { }`](https://github.com/mapbox/mapbox-unity-sdk/blob/a46a15e0f1469004995922280a5b2c2b0f9e0a77/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/VectorTile.cs#L208) (I think???).

-----

I pulled in latest `develop` and I'm able to reproduce @david-rhodes 's results: **no gain** 😭 😭 😭 
 
Using `BackgroundWorker` even seems to be tad slower (maybe the overhead of creating threads).


Probably the other improvements made to latest `develop` outweigh the gain of `BackgroundWorker`.

Visualization (eg how buildings appear, one by one instead of all at once) definitely looks different than yesterday before merging latest `develop`.

**Comment by BergWerkGIS** [comment]
Did some more digging around our low level stuff.

1.
Within `vector-tile-cs`: no gains.

2.
Withing `mapbox-unity-sdk`.

As inflating the VTs seemed to use quite some CPU cycles

![image](https://user-images.githubusercontent.com/4549888/31992983-1c1dd860-b97c-11e7-9fc1-17a531757861.png)

I changed `CachingWebFileSource.cs` to save inflated tiles instead of gzipped ones.
With that `Compression.Decompress()` is completely gone from hot path:

![image](https://user-images.githubusercontent.com/4549888/31993336-1cb5aefa-b97d-11e7-9e24-9386c056d7f9.png)

but overall map load time was still the same: eg ±0.5s with an overall map load time (measured with @david-rhodes 's script above) of ~16s.

Only thing that changed was the size of the cache files (~2x times the size) - and that's only for 10 tiles:
![image](https://user-images.githubusercontent.com/4549888/31993601-f9c6f254-b97d-11e7-8a7e-42d731d12bc5.png)

I suppose we are going to keep gzipped cache 😏 

----

Currently I don't see any way to improve performance of lower level parts of the SDK as lion's share of used CPU cycles seems to originate from other parts.

I see that the one frame pause in `CachingWebFileSource.cs` seems to have gone away again.
**Is there something similar happening in other places, too?**
Trying to understand why freeing up quite some CPU cycles doesn't reduce overall time.

**Comment by david-rhodes** [comment]
@BergWerkGIS BTW, with @brnkhy's recent coroutine changes, we reverted the one frame delay from disk cache tiles. The delay is now built into the map factory framework, which means no issues with dynamic map zoom, for example. 👏
