### ISSUE TITLE
Make VectorLayerVisualizer Coroutines optional and parameterized

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#324]
We merged VectorLayerVisualizer coroutines into the dev branch but it's actually hardcoded at the moment. It should be optional and `feature per coroutine` property we're using should be available in the inspector.
This will allow devs to switch between distribute feature generation over bunch of frames or not. And indirectly control how many frame will it take.

It looks like this at the moment;
![unity_2017-10-26_01-52-54](https://user-images.githubusercontent.com/1465390/32027309-04048e0c-b9f1-11e7-8f72-61e687a20da7.png)

**Comment by david-rhodes** [comment]
Pretty sure this was in #355
