### ISSUE TITLE
Set Access of MonoBehaviour Messages to Protected

### ISSUE THREAD

**Issue by ahokinson** [mapbox/mapbox-unity-sdk#325]
In order to avoid directly modifying the SDK, I routinely inherit from the base / abstract classes that are provided.  Sometimes, in addition to adding my own methods, I need to access the MonoBehaviour messaging methods.

For example, when I inherit from AbstractMap to build a GlobeMap, I need to add cap meshes to the globe (a limitation of LatitudeMax).

```
public class GlobeMap : AbstractMap
{
    private override void Start()
    {
        var localScale = Root.localScale;
        base.Start();
        Root.localScale = localScale;
        FindObjectsOfType<SphereCapper>().ToList().ForEach(sc => sc.GenerateCapMesh());
    }
...

public abstract class AbstractMap : MonoBehaviour, IMap
...
    protected virtual void Start()
    {
        if (_initializeOnStart)
        {
            Initialize(Conversions.StringToLatLon(_latitudeLongitudeString), _zoom);
        }
    }
...
```

Without the AbstractMap Start method being made `protected`, I am unable to invoke `base.Start()`.

To accommodate better inheritance from the base classes in the SDK, it would be great if anytime these methods are used, they are given the `protected` and `virtual` access modifiers.

**Comment by david-rhodes** [comment]
Fixed in `develop`
