### ISSUE TITLE
Mapbox.VectorTile.VectorTileData not resolved

### ISSUE THREAD

**Issue by thedrummeraki** [mapbox/mapbox-unity-sdk#328]
**Scenario**
When I did a clean clone of the repo (branch `develop`) on my personal laptop, I find that there are a couple of compile errors.

**Screenshots**
Here is a screenshot of what I am getting in the console. I am currently investigating the situation.

![image](https://user-images.githubusercontent.com/14348784/32080424-855387a6-ba7d-11e7-81fd-9c2fcc5585de.png)

A quick search all of `VectorTileData` usages from the project tree give the following:

![image](https://user-images.githubusercontent.com/14348784/32080561-6204d60a-ba7e-11e7-98a7-02016154b3ee.png)

Haven't found any definitions for this class.

**Specifications**
I am currently running Unity 2017.1 on Linux. I thought this would be an issue because Unity is a beta build on Linux, but I run into the same issue on a Windows VM with a stable Unity build.

**What I understand**
From the information I gathered, I found that something had to be renamed...:

![image](https://user-images.githubusercontent.com/14348784/32080598-a807dbf2-ba7e-11e7-86d7-6b997ba8b98c.png)

Was a definition renamed but not the references?

Thank you for your input.

**Comment by david-rhodes** [comment]
@thedrummeraki Please remember to run the update scripts when pulling from `develop` as dependencies may have been updated (as in this case): https://github.com/mapbox/mapbox-unity-sdk#dependencies.

**Comment by thedrummeraki** [comment]
@david-rhodes Ohh I see, I totally forgot about this, thank you for pointing it out!
