### ISSUE TITLE
Scaling -  again. SDK 1.2

### ISSUE THREAD

**Issue by colin-young** [mapbox/mapbox-unity-sdk#329]
I recently upgraded the SDK from 1.1 to 1.2 in my project. Previously I was inheriting from the `AbstractMap` class and had a zoom of 14 and tile size of 100 and found that gave me 1 Unity unit = 1m on imported SketchUp models = 1m on map. After upgrading I switched to inherit from `BasicMap` but I've found that I needed to change the zoom to 15 and the tile size to 550 in order to maintain the same scaling.

I get that the SDK is under development and things will change, but is there some definitive explanation of the relationship between zoom, tile size and Unity units? According to an answer in #50 setting `WorldScaleFactor` to 1 and later ensuring localScale of worldRoot (?) is 1 will give a 1:1 Unity to real world scale and take tile size out of it, but that's clearly not the case, or at least that's not what I'm seeing. Perhaps tĥere is some additional steps I need to take, but it's not obvious to me what those might be. A sample implementation of `BasicMap` or `AbstractMap` showing a couple scenarios (e.g. 1:1 and a case where you want to scale down for gigantic worlds) would probably clear up a lot of confusion.

**Comment by david-rhodes** [comment]
@colin-young Sorry to hear you're having issues. First of all, it sounds like you want real world scale (1 unit = 1 meter)? In this case, z14 would certainly never have produced such a scenario. For what it's worth, `UnityTileSize` is the number of units wide each tile in the map will be. As for zoom and meters per pixel relationship, please see: https://wiki.openstreetmap.org/wiki/Zoom_levels.

The good news is that if you grab this file: https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Map/MapAtWorldScale.cs, you'll have what you need. You can disregard `UnityTileSize` as it's ignored in this implementation.

**Comment by colin-young** [comment]
Awesome! That's perfect and exactly what I needed. And there's enough info in that file that I will eventually be able to puzzle through exactly how it works (or, at least, enough to satisfy me).

I don't recall the exact zoom and tile size settings I had before, but my expectation was that whatever they were should have remained the same even if I swapped in a different `AbstractMap` implementation. But, given that my understanding of exactly how it all worked would have been adequately covered by "it's magic," it's quite likely I was seriously abusing some of the available settings.

**Comment by MiroMuse** [comment]
Looks like this ticket was resolved, so I'll close for now. @colin-young let us know if you need anything else!
