### ISSUE TITLE
Create a complete Map Visualizer

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#333]
Our vector data isn't really open to exploration inside SDK and only way to know about different layers and features is to go through the vector data documentation.
Demo scenes for example have only one or two layer visualizers, strictly created for those demos.

The idea is to create a huge node graph and demo scene, with all layers and features. With a graph like that, developers will be able to enable/disable layer visualizers to explore vector data, see how it's visualized and organized.

One problem here is that it's not easy to reuse nodes in different scenes because "Active" property of nodes are kept inside them so if you enable a node for one scene, it'll be enabled in all scenes/graphs with that node. Maybe we can think of a way to save "Active" property in scene files afterwards which would boost reusability. 
For real applications though, developers will be able to just copy this one and work on it as they most likely won't have multiple graphs inside one project.

cc @atripathi-mb @david-rhodes

**Comment by david-rhodes** [comment]
This is awesome! I imagine this could also help streamline our demo scenes and add clarity.

**Comment by brnkhy** [comment]
@david-rhodes actually we can make a demo where you can check few boxes and rebuild everything to show those layers etc. similar to last unite demo. would be interesting

**Comment by MiroMuse** [comment]
@brnkhy Could we also use this to open up a ready example the moment someone downloads the SDK? The goal being to increase the amount of people that actually send in a turnstile event after downloading the SDK (currently about 25% of people; we want to get that to 80-100%).

**Comment by brnkhy** [comment]
@MiroMuse I think chaning scene would be too annoying/pushy but I think I remember some assets creating popups for tutorials, website links etc so maybe we can do something like that. It would send an event, shot tutorials and have links etc etc. would be better than a scene I guess.

**Comment by MiroMuse** [comment]
@brnkhy awesome, once I'm on this task, I'd love to hear more of your thoughts here. Look out for a meeting invite:)

**Comment by david-rhodes** [comment]
#407
