### ISSUE TITLE
Duplicate event registration in AbstractMapVisualizer

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#335]
Events are registered for in `Initialize` method, but only unregistered in `Destroy` method. Most `Map` implementations call `Initialize` but never invoke `Destroy`. This can lead to possible duplicate registrations and memory leaks!

**Comment by apavani** [comment]
We can resolve this by just calling the Destroy() method wherever we are calling Initialize(). Isn't it?

**Comment by apavani** [comment]
Would it make sense to call Destroy() at the very beginning of Initialize()?
That way all the previously initialized map tiles would be destroyed before the next Initialize() request is serverd

**Comment by david-rhodes** [comment]
> Would it make sense to call Destroy() at the very beginning of Initialize()?

I do not recommend this approach. Game object destruction creates garbage and leads to frame rate drops. However, we can extract the event unregistration and call that method in both `Destroy` and `Initialize`?
