### ISSUE TITLE
SnapTerrainRaycastModifier layer bug sdk 1.2

### ISSUE THREAD

**Issue by LastMonopoly** [mapbox/mapbox-unity-sdk#340]
I am experimenting example project (https://blog.mapbox.com/building-a-location-based-game-in-20-minutes-7ae94e9affd1), part 5.
Inside part_05_POI: terrain mask for Part_05_BuildingSnapRaycast should be same as layer of Part_05_Terrain.
Everything works fine until upgrading sdk to 1.2, buildings no longer snap to terrains
<img width="774" alt="screen shot 2017-11-01 at 5 37 21 pm" src="https://user-images.githubusercontent.com/839799/32268766-482b07de-bf2b-11e7-80dd-accc28d52ef8.png">
If you set two layers differently, snapping happens, which is odd.

Please take a look, thank you so much.

**Comment by LastMonopoly** [comment]
My minimal bug report unipackage, https://drive.google.com/file/d/0BxSVxZzIRMHIMVlyeGo1Y0JnenM/view?usp=sharing

**Comment by david-rhodes** [comment]
In our embedded SDK project, the layer masks appear to be working correctly for raycasts, but there is certainly an offset. Because this is a different project, please delete layers and reapply. 

For your use-case, would a simple `SnapTerrainModifier` work?

**Comment by LastMonopoly** [comment]
#341 is accurate.
"one thing you can try is to delete layers and add them again, then set the layers manually for each modifier (and the terrain factory)" I have tried to add/set layers/modifiers several times, but...

Can you create **any** sdk 1.2.0 SnapTerrainRaycastModifier unitypackage for me to test?

**Comment by david-rhodes** [comment]
Not sure what you are referring to @LastMonopoly. What is your use-case? Will a simple SnapTerrainModifier work (as seen in `MeshGenerationOnTerrain`)?

**Comment by LastMonopoly** [comment]
A simple SnapTerrainModifier (as seen in MeshGenerationOnTerrain) **does not** work, as show in #341, this is the result in my unity project
<img width="1119" alt="screen shot 2017-11-02 at 4 27 35 am" src="https://user-images.githubusercontent.com/839799/32296068-166453b2-bf86-11e7-8181-390585b7e64b.png">

**Comment by david-rhodes** [comment]
This is what it looks like for me using `SnapTerrainModifier` (default).
<img width="386" alt="screen shot 2017-11-01 at 2 52 06 pm" src="https://user-images.githubusercontent.com/23202691/32297278-530efef6-bf14-11e7-8940-7048bb88fb75.png">

Note that this is not the same as `SnapTerrainRaycastModifier`!

**Comment by LastMonopoly** [comment]
Yep. After changing  `SnapTerrainModifier` to `SnapTerrainRaycastModifier` as described in #341 , offset appears.

**Comment by david-rhodes** [comment]
Ok, so back to the original question, why does `SnapTerrainModifier` not work for your use-case?

**Comment by LastMonopoly** [comment]
Sorry for the wrong message in previous comment. 
In my use-case,`SnapTerrainModifier` works, `SnapTerrainRaycastModifier` doesn't.

**Comment by david-rhodes** [comment]
So can we close this ticket?
