### ISSUE TITLE
SnapTerrainRaycastModifier is broken

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#341]
To reproduce: replace `SnapTerrain`Modifier for building stack in `MeshGenerationOnTerrain` with `SnapTerrainRaycastModifier` and ensure you add a collider and layer to the terrain factory. Match the layers.

<img width="403" alt="screen shot 2017-11-01 at 9 49 39 am" src="https://user-images.githubusercontent.com/23202691/32283500-213728ec-beea-11e7-91f7-9317e9c05914.png">

@brnkhy any ideas off the top of your head?

**Comment by LastMonopoly** [comment]
Please create **any** sdk 1.2.0 SnapTerrainRaycastModifier unitypackage for me to test. I have no idea how to fix this bug.

**Comment by david-rhodes** [comment]
@brnkhy For clarification, this specific issue is still valid. 😏

**Comment by mihakrajnc** [comment]
Hmm, I'm not sure if this is the case here, but I've had problems with raycasting before, because the mesh was not yet generated when the raycasting was done.

Right now, one of my scripts that does it's own raycasting looks something like this:

```csharp
public class ColorFilteredPrefabModifier : GameObjectModifier
{
   public override void Run(FeatureBehaviour fb, UnityTile tile)
    {
        switch (tile.RasterDataState)
        {
            case TilePropertyState.Loaded:
                UpdatePrefabs(fb, tile);
                break;
            case TilePropertyState.Loading:
            case TilePropertyState.None:
                tile.OnRasterDataChanged += rTile => UpdatePrefabs(fb, tile);
                break;
        }
    }

	private void UpdatePrefabs(FeatureBehaviour fb, UnityTile tile)
    {
        //FIXME: Should remove OnRasterDataChanged callback instead somehow.
        if (!fb) return;
		
		// DO THE RAYCAST
    }
}
```

**Comment by LastMonopoly** [comment]
If you increase zoom to 18+, the bug disappears :open_mouth:

**Comment by brnkhy** [comment]
@mihakrajnc I might be missing something here but vector factory should run after terrain and image factory completed, so you shouldn't have a problem like that. If I'm missing something and there's something async there somehow, that's totally way to go though.

**Comment by david-rhodes** [comment]
> If you set the height multiplier of the terrain factory to 0, you won't see the offset.

That's because you're just left with a flat map and all ray hit points will be multiplied by 0. 😏

**Comment by mihakrajnc** [comment]
@brnkhy Hmm, is that a "new" feature? I wrote this code a while back, somewhere between 0.5 and 1.0 releases, and it was definitely a problem back then. Just did a quick test and it seems like `RastedDataState` is never None / Loading. Interesting...

**Comment by brnkhy** [comment]
@LastMonopoly 
this was an interesting issue and a combination of bunch of small stuff but I think this PR fixes it;
https://github.com/mapbox/mapbox-unity-sdk/pull/368

waiting for reviews before merging it in.

**Comment by david-rhodes** [comment]
Fixed: https://github.com/mapbox/mapbox-unity-sdk/pull/368
