### ISSUE TITLE
Performance: look into Conversions.GetAbsoluteHeightFromColor()

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#346]
Depending on use case (elevation via `terrain-rgb`) `GetAbsoluteHeightFromColor()` shows up quite high during profiling as it is called **65,536** (256^2) times per tile:

![image](https://user-images.githubusercontent.com/4549888/32372384-e1c42d3e-c094-11e7-81ae-2ca32473ddea.png)

Investigate if the formula can be made faster, because of number of times it gets called every millisecond counts.

Maybe bitshifting?

**Comment by david-rhodes** [comment]
Best approach would be to have elevation encoded in a different format :trollface: (seriously doubt we need color at all).

`LoadImage` is also costly, and we should be able to extract color data from the raw byte array without using a `Texture2d` object.
