### ISSUE TITLE
Refactor Events

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#348]
Work on technical debt and implement some good practices:

* inherit from `EventArgs`
* replace `Action<> delegate {}` with `EventHandler<>`
  eg `public event Action<TileErrorEventArgs> OnTileError = delegate { };` => 
  `public event EventHandler<TileErrorEventArgs> OnTileError;`
* make them thread safe (we'll never know what the future brings :smirk:)
  instead of
  ```c#
  public event Action<MyEventArgs> TheHandler = delegate { }; 
  if (TheHandler != null) 
  { 
    TheHandler(new MyEventArgs(parameter)); 
  } 
  ```
  use
  ```c#
  public event EventHandler<MyEventArgs> TheHandler;
  EventHandler<MyEventArgs> handler = TheHandler;
  if (handler != null)
  {
    handler(this, new MyEventArgs(parameter));
  }
  ```

References:
*  [`Microsoft Docs: How to: Raise and Consume Events`](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-raise-and-consume-events)
* [`Microsoft Docs: EventHandler<TEventArgs> Delegate`](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler-1?view=netframework-4.7.1)

**Comment by brnkhy** [comment]
I don't know why are we going with the Action in the first place. It's not the most common practice but maybe more performant for Unity? @david-rhodes

**Comment by david-rhodes** [comment]
I used to use `EventHandler` with `EventArgs` but `Action` often saves writing code and memory. For example, you can pass objects and value types directly without wrapping inside another object. Every time you use `new` in Unity, a Panda cries 🐼. The fewer of those we have, the better.

Also, with `Action`, you can assign an empty delegate and avoid null checking the event invocation.

**Comment by BergWerkGIS** [comment]
@david-rhodes do I understand correctly that your recommendation is to keep things as they are?

> For example, you can pass objects and value types directly without wrapping inside another object.

From my experience events almost always contain more information than just a single value, eg # of tiles in the queue, tiles left, progress %, errors, ...
And if they don't during initial implementation later refactorings might, forcing changes in a lot of places.
I personally prefer being prepared from the beginning to make things easier down the road (eg multithreading).

But if implementing good practices comes with a performance penalty we might want to steer clear of that for once.

> Also, with `Action`, you can assign an empty delegate and avoid null checking the event invocation. 

Hm, interesting thinking.
So, instead of checking for null your preference is to always fire the event, even when no client has subscribed (empty default delegate).

Curious if and how that would get optimized away and which approach might be faster:
* checking for null
* or always firing

Any takers for a little side project to investigate?

**Comment by BergWerkGIS** [comment]
> often saves writing code and memory

That's might get easier when Unity finally updates the runtime:

```c#
TheHandler?.Invoke(this, new new MyEventArgs(parameter));
```

**Comment by david-rhodes** [comment]
@BergWerkGIS I have no objections to switching to `EventArgs`, other than the performance cost when sending many thousands of events. For an SDK, it makes more sense and will reduce the risk of breaking changes.

**Comment by brnkhy** [comment]
@david-rhodes @BergWerkGIS can we do a basic test project testing both for one million calls or something? might be easier to decide if we have concrete time&memory numbers

**Comment by BergWerkGIS** [comment]
> > Any takers for a little side project to investigate?

> can we do a basic test project testing both for one million calls or something?

So @brnkhy, we do have a volunteer? :smirk:

**Comment by david-rhodes** [comment]
If we do a test, it should only focus on memory allocations. But, like I said, it really only depends on those cases where many thousands of events are sent. Not really worth testing at this point.

**Comment by brnkhy** [comment]
@BergWerkGIS sure why not. You probably have a better, clear view of what to test though so I'll post it and you can check it etc.

@david-rhodes I'm not sure about that. I mean we don't have anything like that at the moment but we might have stuff like events on particle collusion or feature creation in the future for example. So no harm logging which one is faster as well.

**Comment by atripathi-mb** [comment]
I have used `EventArgs` extensively in the past. They work especially well from an SDK point of view as the API signatures don't change. 

As far as I am aware, there are no/negligible performance implications of using one over the other, but I might be wrong. Is there a known performance difference that you guys are concerned about?

**Comment by david-rhodes** [comment]
As mentioned above, only performance difference I know of is the cost of generating garbage (and subsequently collecting it). The `new` keyword is especially bad for mobile devices. But again, this is only a concern if we're creating several thousand event args in a single frame. With simple arguments, there's often no need to nest inside another object just to pass around in a delegate (other than to assist in extending in the future).

**Comment by atripathi-mb** [comment]
@david-rhodes totally agree with this
> With simple arguments, there's often no need to nest inside another object just to pass around in a delegate (other than to assist in extending in the future).

**Comment by david-rhodes** [comment]
Handling on a case-by-case basis.
