### ISSUE TITLE
Satellite Texture Top Material of TextureModifier is distorted and displayed to incorrect scale

### ISSUE THREAD

**Issue by stevenroach7** [mapbox/mapbox-unity-sdk#350]
I’m using version  v1.2.0 of the Mapbox SDK. 

I have a MergedModifierStack which I am using to layer polygons representing neighborhoods on my map. The stack consists of a PolygonModifier, UVModifier, SnapTerrainModifier, HeightModifier, and a TextureModifier. When setting Use Satellite Texture to true of the TextureModifier, the imagery displayed on top of the polygons is distorted and shown at an incorrect scale. This effect varies as the tile size changes but is distorted significantly in all cases I’ve tried. Here is an example of the output I get:
<img width="1205" alt="distortionexample1" src="https://user-images.githubusercontent.com/14096122/32389004-6a86c67a-c097-11e7-9b93-85a81638f7b4.png">

I am pretty new to both Unity and the Mapbox SDK so I’m not certain if this is the right approach to produce my desired effect of extruded neighborhood polygons with the map imagery as their top material. 

I’m not sure if this is related to [Issue 304](https://github.com/mapbox/mapbox-unity-sdk/issues/304). 

Thanks!

**Comment by brnkhy** [comment]
@stevenroach7 It looks like an UV issue, can you check UVModifier and see if "Use Sattelite Roof" option is checked? It's really easy to miss and bad UX on our side but that checkbox switches between tile/local UV.

**Comment by stevenroach7** [comment]
@brnkhy Thank you. I totally missed that. Now, the distortion is not as bad, but the scale is way off and the tiles don't form cohesive imagery. 

<img width="1191" alt="distortionexample2" src="https://user-images.githubusercontent.com/14096122/32397145-5e8bfd76-c0b6-11e7-9f42-4515fde99b8a.png">

I tried varying the tile size and scale in the TextureModifier and the top layer changes but is still off in each case.

**Comment by brnkhy** [comment]
@stevenroach7 I can't clearly say what's going on in that shot but are those huge buildings there? or landuse or something?

**Comment by stevenroach7** [comment]
@brnkhy Each polygon is the shape of a neighborhood. The height of the extrusion is a function of the median property value in the neighborhood. The imagery is a map created in Mapbox Studio. I can confirm that the imagery displayed on top of the layers is the map I created because the far left tile which looks like part of a white "a" is from a label in this custom map. 

This image might help. I forced the heights to the same value. You can see that the imagery on top of the layer is identical to the previous image. 
<img width="1188" alt="example3" src="https://user-images.githubusercontent.com/14096122/32401334-30e5d2e2-c0da-11e7-9088-fdbd30c1fe55.png">

**Comment by brnkhy** [comment]
@stevenroach7 that's interesting, we must be missing something here but I cannot be sure. That last shot has the data needed to recreate the scene so I'll try to test it myself and see what's wrong. Either we're missing something very basic or this is a different case & bug.

**Comment by stevenroach7** [comment]
@brnkhy Great, Thank you. Let me know if you want any more details about my setup.

**Comment by brnkhy** [comment]
@stevenroach7 I realized you're using custom data so couldn't recreate it properly but when I tested with landuse layer, it worked for me;
![unity_2017-11-06_23-47-44](https://user-images.githubusercontent.com/1465390/32463157-005938e2-c34d-11e7-87df-3488fe26a902.png)
I'm still playing with some options to see if I can break it.

**Comment by stevenroach7** [comment]
@brnkhy I did some more tests to no avail. This is using the Streets imagery and land use polygons (so no custom data):
<img width="1423" alt="example4" src="https://user-images.githubusercontent.com/14096122/32476987-a8bc8a5a-c340-11e7-8a1b-ffd6bc9aa9c2.png">
Perhaps its a problem with my setup elsewhere. In your tests, you used the same MergedModifierStack and Texture Modifier config as me?

**Comment by brnkhy** [comment]
@stevenroach7 yep I'm using the same values but I actually checked with the latest from repo, not v1.2.
Another thing might be the material settings by the way, can you check if the tiling values are (1,1) for example (for landuse top material). If that doesn't work I'll try with v1.2 as well.

**Comment by stevenroach7** [comment]
@brnkhy What do you mean by tiling values? The top and side materials of the texture modifier?

**Comment by brnkhy** [comment]
@stevenroach7  I mean the values on the applied material itself;
![unity_2017-11-07_18-23-02](https://user-images.githubusercontent.com/1465390/32501319-bdfcee0c-c3e8-11e7-8aa5-34aa28db907c.png)
You can craete the world, go into scene view and select your object. Then find the material from the inspector (while correct gameobject is selected).

**Comment by stevenroach7** [comment]
@brnkhy I see. Here is what I have for the top material.
<img width="417" alt="material" src="https://user-images.githubusercontent.com/14096122/32502901-8a0f3c68-c3a1-11e7-9300-757366600601.png">

**Comment by brnkhy** [comment]
@stevenroach7 I managed to recreate this on v1.2 and turns out it's a scaling bug with the UvModifier that's fixed after v1.2 release. Sorry about that. I'm pasting the code fixing that issue below but this will also have issues if you use regular mesh modifier (non merged) and change the "Feature Position" property. Latest on dev branch has all these issues fixed.

```
namespace Mapbox.Unity.MeshGeneration.Modifiers
{
	using System.Collections.Generic;
	using UnityEngine;
	using Mapbox.Unity.MeshGeneration.Data;
	using System;
	using Mapbox.Utils;

	/// <summary>
	/// UV Modifier works only with (and right after) Polygon Modifier and not with Line Mesh Modifier.
	/// If UseSatelliteRoof parameter is false, it creates a tiled UV map, otherwise it creates a stretched UV map.
	/// </summary>
	[CreateAssetMenu(menuName = "Mapbox/Modifiers/UV Modifier")]
	public class UvModifier : MeshModifier
	{
		public override ModifierType Type { get { return ModifierType.Preprocess; } }
		public bool UseSatelliteRoof = false;

		private int _mdVertexCount;
		private Vector2d _size;
		private Vector3 _vert;
		private List<Vector2> _uv = new List<Vector2>();

		public override void Run(VectorFeatureUnity feature, MeshData md, UnityTile tile = null)
		{
			_uv.Clear();
			_mdVertexCount = md.Vertices.Count;
			_size = md.TileRect.Size;

			for (int i = 0; i < _mdVertexCount; i++)
			{
				_vert = md.Vertices[i];
				if (UseSatelliteRoof)
				{
					var fromBottomLeft = new Vector2((float)(((_vert.x) / tile.TileScale + _size.x / 2) / _size.x),
						(float)(((_vert.z) / tile.TileScale + _size.x / 2) / _size.x));
					_uv.Add(fromBottomLeft);
				}
				else
				{
					_uv.Add(new Vector2(_vert.x, _vert.z));
				}
			}
			md.UV[0].AddRange(_uv);
		}
	}
}
```

**Comment by stevenroach7** [comment]
@brnkhy That fixed it. Thank you so much!

**Comment by brnkhy** [comment]
@stevenroach7 no problem! I'll close this as it should be merged with dev already. Let me know if you have any further issues/questions :)
