### ISSUE TITLE
Lon/Lat at mouse click

### ISSUE THREAD

**Issue by koedijk** [mapbox/mapbox-unity-sdk#356]
I want to get the  lon/lat when i click on the map,for now i use map at specific location and i can update the map to a new lon/lat manually so i want it to do with the mouse. 

what i think i need is getting a position on a other tile and convert it to lonlat?

**Comment by koedijk** [comment]
Got it

**Comment by neftosis** [comment]
did you get an answer?

**Comment by atripathi-mb** [comment]
@neftosis You can get lat/long of a mouse click using the code here
https://github.com/mapbox/mapbox-unity-sdk/blob/85fef42a7135b86751895722aa9b89a900751891/sdkproject/Assets/Mapbox/Examples/Scripts/QuadTreeCameraMovement.cs#L157

It comes with an example script in the SDK.

**Comment by neftosis** [comment]
Thank you so much my friend!

**Comment by Flameshot** [comment]
@atripathi-mb I understood the example, but I think that just gets the lat lon of camera bounds, so when you move the map the lat long will change. But how can mouse pointer real be made? 

Like this one? https://www.mapbox.com/mapbox-gl-js/example/mouse-position/

**Comment by neftosis** [comment]
Thanks I'm going to try that!! That will probably help me so much! I'll let you know!

**Comment by hexbyteinc** [comment]
> @neftosis You can get lat/long of a mouse click using the code here
> [mapbox-unity-sdk/sdkproject/Assets/Mapbox/Examples/Scripts/QuadTreeCameraMovement.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/85fef42a7135b86751895722aa9b89a900751891/sdkproject/Assets/Mapbox/Examples/Scripts/QuadTreeCameraMovement.cs#L157)
> 
> Line 157 in [85fef42](/mapbox/mapbox-unity-sdk/commit/85fef42a7135b86751895722aa9b89a900751891)
> 
>  if (Input.GetMouseButtonUp(1)) 
> It comes with an example script in the SDK.

I changed my username this is neftosis

**Comment by hexbyteinc** [comment]
Reading https://github.com/mapbox/mapbox-unity-sdk/issues/123
and https://github.com/mapbox/mapbox-unity-sdk/issues/441 first thanks man

**Comment by hexbyteinc** [comment]
Ok I have read everything and everything I have tried above fails. I can place objects fine with spawnonmap
but my attempt to simply place something on mouse click is failing horribly. 
Please please help me - all the tutorials are referencing factories that I don't even see anymore, please let me know what I'm doing wrong!
@atripathi-mb 
@brnkhy

**Comment by hexbyteinc** [comment]
Or alternately if I could get the tile or map position on mouse click from a raycast please advise!?

**Comment by StarKing777** [comment]
> n't even see anymo

Hey if you would like to instantiate and place objects on the fly have a look at the following code.

This code is to be added to a new game component called something like (PlacePrefabScript)

attach the following script to the game object and then make sure to serialize you desired spawnable prefab.

make sure that your map has relevant mesh colliders enable otherwise your object will not spawn or snap to grid.

 P.S.(I am still trying to figure out how to save that prefab in that position forever / any advice would be highly appreciated - either way this placement script is a good place to start)

 using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
using Mapbox.Utils;
using Mapbox.Unity.Map;
using Mapbox.Unity.MeshGeneration.Factories;
using Mapbox.Unity.Utilities;


public class PlacementControllerScript : MonoBehaviour
{
    [SerializeField]
    private GameObject placeableObjectPrefabs;

    private GameObject currentPlaceableObject;

    private KeyCode ObjectHotKey = KeyCode.B;

    private float mouseWheelRotation;
    private int currentPrefabIndex = -1;

    [SerializeField] public AbstractMap _map;

private void Update()
    {
        HandleNewObjectHotkey();


        if (currentPlaceableObject != null)
        {
            MoveCurrentObjectToMouse();
            RotateFromMouseWheel();
            ReleaseIfClicked();
        }
    }

    private void HandleNewObjectHotkey()
    {
            if (Input.GetKeyDown(KeyCode.B))
            {

                    if (currentPlaceableObject != null)
                    {
                        Destroy(currentPlaceableObject);
                    }
                    else
                    {
                        currentPlaceableObject = Instantiate(placeableObjectPrefabs);
                        Debug.Log("OBJECT INSTANTIATED");
            
                    }
            }
    }


    private void MoveCurrentObjectToMouse()
    {
        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);

        RaycastHit hitInfo;
        if (Physics.Raycast(ray, out hitInfo))
        {
            currentPlaceableObject.transform.position = hitInfo.point;
            currentPlaceableObject.transform.rotation = Quaternion.FromToRotation(Vector3.up, hitInfo.normal);
        }
    }

    private void RotateFromMouseWheel()
    {
        //Debug.Log(Input.mouseScrollDelta);
        mouseWheelRotation += Input.mouseScrollDelta.y;
        currentPlaceableObject.transform.Rotate(Vector3.up, mouseWheelRotation * 5f);
    }

    private void ReleaseIfClicked()
    {
        if (Input.GetKeyDown(KeyCode.N))
        {

            currentPlaceableObject = null;
           
        }

    }

}
