### ISSUE TITLE
Add class documentation to map factory framework

### ISSUE THREAD

**Issue by isiyu** [mapbox/mapbox-unity-sdk#358]
**context** : need a refresh of documentation

**solution** : @brnkhy will go through factory system documentation an add inline and descriptive documentation.  @atripathi-mb / @apavani  will help review and point out 

### Next steps:
- [ ] [Map factory framework written](https://www.mapbox.com/mapbox-unity-sdk/docs/06-map-factory-framework.html) - src [here](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/06-map-factory-framework.md) update and expand
- [x] API documentation inline to code for [Mesh Generation](https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.MeshGeneration.Components.html) add per class documentation

**Comment by david-rhodes** [comment]
Possibly useful reference: https://www.mapbox.com/mapbox-unity-sdk/docs/06-map-factory-framework.html
