### ISSUE TITLE
Failed to load 'Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll

### ISSUE THREAD

**Issue by gannebamm** [mapbox/mapbox-unity-sdk#361]
Hi there,
I am unable to develop with Unity 2017.1.1f1 and Mapbox SDK 1.2 on a Win10 OS x64 with Visual Studio 2017 Community Edition. I later want to deploy the app to a Hololens (x86). If I start a completly new project with the mapbox sdk 1.2 and try to 'play' the MeshGeneration.uniy example it gives me the following error:

`Failed to load 'Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll' with error 'Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
'.
Mapbox.Platform.MbTiles.MbTilesDb:openOrCreateDb(String) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:134)
Mapbox.Platform.MbTiles.MbTilesDb:openOrCreateDb(String) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:132)
Mapbox.Platform.MbTiles.MbTilesDb:.ctor(String, Nullable1) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:32)
Mapbox.Platform.Cache.MbTilesCache:initializeMbTiles(String) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:101)
Mapbox.Platform.Cache.MbTilesCache:Get(String, CanonicalTileId) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:124)
Mapbox.Platform.Cache.CachingWebFileSource:Request(String, Action1, Int32, CanonicalTileId, String) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:112)
Mapbox.Unity.MapboxAccess:Request(String, Action1, Int32, CanonicalTileId, String) (at Assets/Mapbox/Unity/MapboxAccess.cs:157)
Mapbox.Map.Tile:Initialize(IFileSource, CanonicalTileId, String, Action) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:139)
Mapbox.Unity.MeshGeneration.Factories.MapImageFactory:OnRegistered(UnityTile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/MapImageFactory.cs:89)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory:Register(UnityTile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:50)
Mapbox.Unity.Map.AbstractMapVisualizer:LoadTile(UnwrappedTileId) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:158)
Mapbox.Unity.Map.AbstractMap:TileProvider_OnTileAdded(UnwrappedTileId) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:152)
Mapbox.Unity.Map.AbstractTileProvider:AddTile(UnwrappedTileId) (at Assets/Mapbox/Unity/Map/AbstractTileProvider.cs:33)
Mapbox.Unity.Map.RangeTileProvider:OnInitialized() (at Assets/Mapbox/Unity/Map/RangeTileProvider.cs:20)
Mapbox.Unity.Map.AbstractTileProvider:Initialize(IMap) (at Assets/Mapbox/Unity/Map/AbstractTileProvider.cs:22)
Mapbox.Unity.Map.BasicMap:Initialize(Vector2d, Int32) (at Assets/Mapbox/Unity/Map/BasicMap.cs:20)
Mapbox.Unity.Map.AbstractMap:Start() (at Assets/Mapbox/Unity/Map/AbstractMap.cs:131)`

**Comment by BergWerkGIS** [comment]
@gannebamm I just tried and I'm not able to reproduce with the 1.2.0 SDK.

Coud you check if your settings look like this:
for `Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll`
![image](https://user-images.githubusercontent.com/4549888/32790687-64a33d9e-c95f-11e7-86fd-65aaa7b2961e.png)

for `Assets/Mapbox/Core/Plugins/sqlite/x86/sqlite3.dll`
![image](https://user-images.githubusercontent.com/4549888/32793601-b4d65164-c966-11e7-8a36-3c4420f065c1.png)


-----

Also check if you have `Microsoft Visual C++ Redistributable runtime` installed.
From the top of my head I think `2013` is required.

You can get them here:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

----

If you got past this, remember to install `SQLite for Universal Windows Platform` into your UWP project for HoloLens:

https://www.mapbox.com/mapbox-unity-sdk/docs/windowsstore-uwp-hololens.html

**Comment by gannebamm** [comment]
I have found the issue: It was due to a not installed .net Framework 3.5. I had to install it by the dsim command with the win10 image.

**Comment by BergWerkGIS** [comment]
Interesting.
Glad you found the solution.
Thanks for posting back     ❤️
