### ISSUE TITLE
Trying to change material color of polygon at runtime based on tileset feature

### ISSUE THREAD

**Issue by stevenroach7** [mapbox/mapbox-unity-sdk#363]
I’m using version v1.2.0 of the Mapbox SDK to create a 3D data visualization.

I am visualizing a custom tileset that has polygons in the shape of city neighborhoods. These neighborhood polygons have properties relating to that neighborhood (i.e. average housing price). I previously modified the HeightModifier to extrude the polygons based on this value. I would also like to vary the color of the material for each polygon based on a data property in my tileset. I am using a TextureModifier to create the materials for my polygon but as a GameObjectModifier, I don't have access to the VectorFeatureUnity feature that holds my custom data. How can I vary the material color of the polygons at runtime based on the custom feature data in my tileset?

Thanks!

**Comment by david-rhodes** [comment]
@stevenroach7 We hope to streamline modifiers in the future (all modifiers receive same data), but for now, `GameObjectModifiers` do get a `VectorEntity` passed to them, which also contains the `VectorFeatureUnity` property. You can fetch your data from this.

**Comment by stevenroach7** [comment]
@david-rhodes It looks like a FeatureBehaviour is passed in instead in v1.2. Can I fetch the data from this? Should I be using the dev version instead?

**Comment by stevenroach7** [comment]
Oh, it looks like the FeatureBehaviour has a VectorFeatureUnity property as well.

**Comment by david-rhodes** [comment]
Yes, apologies. Sometimes I forget what is in `develop` versus the official release package. Either way, it seems you have access to what you need? 😏

**Comment by stevenroach7** [comment]
@david-rhodes The FeatureBehaviour Data property is null when I try to access it in the Texture modifier.

**Comment by david-rhodes** [comment]
Hmm, that is peculiar! @brnkhy any ideas why this might be?

**Comment by brnkhy** [comment]
@stevenroach7 are you using `Merged Modifier Stack` by any chance? It might be empty if you're using it as it merged multiple features into one so original data is lost during that.

**Comment by stevenroach7** [comment]
@brnkhy Yes, I'm using a Merged Modifier Stack. I now see the note about losing individual entity data. I'll try switching to a Modifier Stack.

**Comment by stevenroach7** [comment]
@david-rhodes @brnkhy It is working now. Thank you!
