### ISSUE TITLE
Unable to build to Xcode simulator, Symbol not found: _OBJC_CLASS_$_MMEEventsManager

### ISSUE THREAD

**Issue by edwardpotter** [mapbox/mapbox-unity-sdk#366]
I am trying to build my unity project to Xcode with the simulator SDK.  The unity build is successful, but when attempting to run to simulator in Xcode, receiving the following message:

dyld: Symbol not found: _OBJC_CLASS_$_MMEEventsManager
  Referenced from: /Users/epotter/Library/Developer/CoreSimulator/Devices/98992156-89CA-452F-8C42-1F367DC2634E/data/Containers/Bundle/Application/018BAE61-CCD7-40CA-9F08-625FAF087003/Adventure.app/Adventure
  Expected in: flat namespace
 in /Users/epotter/Library/Developer/CoreSimulator/Devices/98992156-89CA-452F-8C42-1F367DC2634E/data/Containers/Bundle/Application/018BAE61-CCD7-40CA-9F08-625FAF087003/Adventure.app/Adventure

I am able to build using the device SDK in unity and build/run on a physical device in Xcode fine, but need to run in simulator in order to fulfill screenshot requirements for app submission, etc.

Have tried the following:
- Ensured the Target minimum iOS Version in player settings is set to 8.0
- Removed entire mapbox sdk and re-imported custom package using SDK 1.2.0
- Ensured the Mapbox folder is in default location, directly under the Assets folder
- Ensured "$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include" is included in the Header Search Paths for the Xcode project

**Comment by david-rhodes** [comment]
cc @boundsj Any idea why simulator would not work with our libraries?

**Comment by david-rhodes** [comment]
@edwardpotter Apologies, but our internal libraries do not support the Xcode simulator. That said, neither does Unity: https://docs.unity3d.com/Manual/iphone-basic.html.

I would recommend that you simply deploy to your primary target device and capture your screenshots there. Is there any reason this approach would not work?

**Comment by edwardpotter** [comment]
That can work - at least until apple starts requiring iPhoneX screenshots or such.  Thanks for looking into it

**Comment by david-rhodes** [comment]
@edwardpotter You can also use screen capture from inside the Unity Editor. You can set your target aspect ratio and supersample to hit the resolution you need.

**Comment by boundsj** [comment]
fyi https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.3.0 is available and is built with an iOS simulator architecture slice. If the Unity SDK were updated with this new version it should eliminate the error noted originally here. However, that still does not change the fact that Unity itself does not support the iOS simulator, yet, afaik. cc @isiyu
