### ISSUE TITLE
get near by locations list mapbox unity

### ISSUE THREAD

**Issue by veeru412** [mapbox/mapbox-unity-sdk#369]
i just started using mapbox.
i need a list of locations near by my location. how can i get that.

**Comment by david-rhodes** [comment]
This depends on what type of locations you need. If you want points of interest, you can use the `poi_label` layer inside the `streetsv7` vector tileset. See `PoiGeneration` scene for reference. https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#poi_label

If you want to search for places by name, then you can use forward geocoding. If you want to see whats nearby, you can use reverse geocoding (search by location). See our `Playground` examples for geocoding. More info: https://www.mapbox.com/geocoding/.

**Comment by veeru412** [comment]
Let me explain what I need. I want place some treassures along 10k .m range
from my current location. So I may have use reverse geocoading right.

**Comment by david-rhodes** [comment]
It depends. Where do you want to spawn treasure? Randomly? At cafes or parks? More information is needed to answer this question.

**Comment by veeru412** [comment]
At shopping malls and cafes.

**Comment by david-rhodes** [comment]
In that case you're probably better off using `poi_label` and filtering by their `type` or `maki` properties. You can spawn your treasure (prefabs) using the `PrefabModifier`.
