### ISSUE TITLE
Create 3D simulator 

### ISSUE THREAD

**Issue by unknowncode** [mapbox/mapbox-unity-sdk#371]
Hello, Id like to create a project and I would like to know if your asset makes the following possible.
1) Import a map of a Caribbean island. This map I would like to include buildings, mountains(hills), and rivers(dept if supplied by google)
2) "Fill" the rivers, with water(fluid material) and have it flowing.
3) Can a fluid material be used as sea around an island.
4) Can I change the "material" of "slipperiness" of a part of a mountain,  to mimic a landslide.( Lets say change the mountain material to muddy and let gravity to the rest.
I don't expect your asset to "generate water" for rivers. but looking at many models in unity3D it only shows a blue waterline that represents a river but i want a real river or real area for the river water to run, where I can raise water levels and cause it to over flow flood areas.
Also Ability to edit "liquidity" of a selected area of mountain to mimic a landslide.
Regards

**Comment by david-rhodes** [comment]
@unknowncode Sounds like an interesting project! You can certainly consume Mapbox data to assist with your simulation, but you will need to provide your own simulation technology.

The general idea is that you would consume the data layer you are interested in (see https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#waterway, for example), and construct a mesh from this data. Then, you could feed this mesh into your simulation "engine" (plugin) to produce your physics objects and visuals.

Our global elevation data should assist greatly with regards to "flood" simulation.

**Comment by unknowncode** [comment]
@david-rhodes Hi, thanks for the reply, I was going to use unity3D however the unity/mapbox tutorial has issues(out dated) which I pointed out to mapbox so Im hoping they address it soon.

Also, would my point number 4 be possible?

**Comment by david-rhodes** [comment]
Again, this depends on your simulation technology. If it supports complex physics materials and their interactions, then you can use mapbox data to feed the system. For example, you can use `landuse:wood` polygons as areas that might not be as muddy, where `landuse:rock` would represent regions more prone to flooding.

I recommend that you use Mapbox Studio to inspect all the different data types that Mapbox provides. This may give you ideas.

**Comment by unknowncode** [comment]
Thanks for the idea I’ll look at it.
But I know unity3D has a physics engine, so I can simulate rain and expect rivers levels to rise and over flow thanks to built in physics, is there one in Mapbox studio? I have no experience with it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by david-rhodes** [comment]
I don't think Unity physics is well suited to creating liquid (flow-based) simulations. You will probably need external assets to create something compelling.

I recommended Mapbox Studio to visualize the data that we offer, not for simulation reference.

**Comment by MiroMuse** [comment]
@unknowncode Let us know if you need anything else here. Going to close the ticket in the meantime.
