### ISSUE TITLE
Using Device Location Provider with Unity Remote

### ISSUE THREAD

**Issue by ProfHorse** [mapbox/mapbox-unity-sdk#372]
Hi,

Using a Unity Remove device to get GPS data for Device Location Provider currently results in errors. This is because LocationProviderFactory uses the conditional for Unity Editor or Not Unity Editor, as because the Unity Remote counts as being in the editor, it chooses to inject the _editorLocationProvider, which in my case doesn't exist, as I am trying to use my device.

Whilst you can manually change the script to always inject the device location provider, I instead tried changing the lines from ~127 in LocationProviderFactory.cs detect whether a Remote is connected, and if it is, to use the _deviceLocationProvider.
`
if(UnityEditor.EditorApplication.isRemoteConnected){
    UnityEngine.Debug.Log("LocationProviderFactory: " + "Injected DEVICE(REMOTE) Location Provider");
    DefaultLocationProvider = _deviceLocationProvider;
} else {
    UnityEngine.Debug.Log("LocationProviderFactory: " + "Injected EDITOR Location Provider");
    DefaultLocationProvider = _editorLocationProvider;
}
`
but for some reason isRemoteConnected returns false when using a Unity Remote - perhaps some sort of a delay needs to be introduced to allow the Remote connection to be fully established?

If all else fails, a manual toggle for using a Unity Remote to get GPS data would be useful, as having to build an app to test device functionality isn't the quickest!

**Comment by david-rhodes** [comment]
@ProfHorse Excellent--thanks for your feedback! Last time I checked, I was not properly getting location updates from remote. Is this working again?!

**Comment by ProfHorse** [comment]
@david-rhodes Was working for me today, aside from the _deviceLocationProvider problem - using an Android device, can't comment on any others.

**Comment by david-rhodes** [comment]
I'll see how this can be improved. Thanks again!

**Comment by david-rhodes** [comment]
@ProfHorse b2bd573fddacec1d7d2762b766e11960baaa4db4

You can now assign the `DeviceLocationProvider` into the `Editor` field and everything should work with Unity Remote.

**Comment by ProfHorse** [comment]
Hi,
The editorLocationProvider is still called as default by:
```
		/// <summary>
		/// Injects the editor location provider.
		/// Depending on the platform, this method and calls to it will be stripped during compile.
		/// </summary>
		[Conditional("UNITY_EDITOR")]
		void InjectEditorLocationProvider()
		{
			UnityEngine.Debug.Log("LocationProviderFactory: " + "Injected EDITOR Location Provider");
			DefaultLocationProvider = _editorLocationProvider;
		}

		/// <summary>
		/// Injects the device location provider.
		/// Depending on the platform, this method and calls to it will be stripped during compile.
		/// </summary>
		[Conditional("NOT_UNITY_EDITOR")]
		void InjectDeviceLocationProvider()
		{
			UnityEngine.Debug.Log("LocationProviderFactory: " + "Injected DEVICE Location Provider");
			DefaultLocationProvider = _deviceLocationProvider;
		}
```

which throws an error (NRE) unless manually changed to force _deviceLocationProvider even when the UNITY_EDITOR conditional is true. Changing this allows Remote GPS to work, although interestingly has introduced a new bug. (I think) that by using the WaitForRemoteConnection coroutine, the first GPS result returned by Remote is used (which it wasn't before), but this first result is always 0,0. Then, when the actual GPS data starts coming in, the tiles are loaded into the scene at a huge offset (as the tiles are in relation to 0,0 GPS position).

**Comment by david-rhodes** [comment]
@ProfHorse So, what I intended was that you should use the `LocationProviderFactory` and assign the `DeviceLocationProvider` instance to both the `device` and `editor` fields. In doing so, not code needs to change.

I'm not sure why your device would report 0,0 first, and I cannot reproduce this. Perhaps it depends on the device generation or OS? I'll try testing with Android today.

**Comment by ProfHorse** [comment]
Even with device in both fields of the LocationProviderFactory, Editor is still being injected.

I'll look further into the GPS 0,0 issue and see if I can give you something more solid.

**Comment by david-rhodes** [comment]
Yes, editor is still being injected, but "editor" is an instance of device location provider. Sneaky, eh? 😉

**Comment by ProfHorse** [comment]
Ah I see! Not sure what I was doing first time round but that's working now!

As for the 0,0 issue, I found that when the map is initialized from Initialize Map With Location Provider, the value of location.LatitudeLongitude that is passed into _map.Initialize is 0.000000,0.000000. Could this be causing the offset?

**Comment by david-rhodes** [comment]
Yes, you are correct. I suspect this is just an OS-level issue. Will post my findings soon.

**Comment by ProfHorse** [comment]
Alright - I'll close this issue as it has been solved. Cheers!

**Comment by david-rhodes** [comment]
```cs
namespace Mapbox.Unity.Location
{
	using System.Collections;
	using UnityEngine;
	using Mapbox.Utils;

	/// <summary>
	/// The DeviceLocationProvider is responsible for providing real world location and heading data,
	/// served directly from native hardware and OS. 
	/// This relies on Unity's <see href="https://docs.unity3d.com/ScriptReference/LocationService.html">LocationService</see> for location
	/// and <see href="https://docs.unity3d.com/ScriptReference/Compass.html">Compass</see> for heading.
	/// </summary>
	public class DeviceLocationProvider : AbstractLocationProvider
	{
		/// <summary>
		/// Using higher value like 500 usually does not require to turn GPS chip on and thus saves battery power. 
		/// Values like 5-10 could be used for getting best accuracy.
		/// </summary>
		[SerializeField]
		float _desiredAccuracyInMeters = 5f;

		/// <summary>
		/// The minimum distance (measured in meters) a device must move laterally before Input.location property is updated. 
		/// Higher values like 500 imply less overhead.
		/// </summary>
		[SerializeField]
		float _updateDistanceInMeters = 5f;

		Location _currentLocation;

		Coroutine _pollRoutine;

		double _lastLocationTimestamp;

		double _lastHeadingTimestamp;

		WaitForSeconds _wait;

		void Awake()
		{
			_wait = new WaitForSeconds(1f);
			if (_pollRoutine == null)
			{
				_pollRoutine = StartCoroutine(PollLocationRoutine());
			}
		}

		/// <summary>
		/// Enable location and compass services.
		/// Sends continuous location and heading updates based on 
		/// _desiredAccuracyInMeters and _updateDistanceInMeters.
		/// </summary>
		/// <returns>The location routine.</returns>
		IEnumerator PollLocationRoutine()
		{
#if UNITY_EDITOR
			yield return new WaitWhile(() => !UnityEditor.EditorApplication.isRemoteConnected);
#endif
			if (!Input.location.isEnabledByUser)
			{
				yield break;
			}

			Input.location.Start(_desiredAccuracyInMeters, _updateDistanceInMeters);
			Input.compass.enabled = true;

			int maxWait = 20;
			while (Input.location.status == LocationServiceStatus.Initializing && maxWait > 0)
			{
				yield return _wait;
				maxWait--;
			}

			if (maxWait < 1)
			{
				yield break;
			}

			if (Input.location.status == LocationServiceStatus.Failed)
			{
				yield break;
			}

#if UNITY_EDITOR
			yield return _wait;
#endif
			while (true)
			{
				_currentLocation.IsHeadingUpdated = false;
				_currentLocation.IsLocationUpdated = false;

				var timestamp = Input.compass.timestamp;
				if (Input.compass.enabled && timestamp > _lastHeadingTimestamp)
				{
					var heading = Input.compass.trueHeading;
					_currentLocation.Heading = heading;
					_lastHeadingTimestamp = timestamp;

					_currentLocation.IsHeadingUpdated = true;
				}

				var lastData = Input.location.lastData;
				timestamp = lastData.timestamp;
				if (Input.location.status == LocationServiceStatus.Running && timestamp > _lastLocationTimestamp)
				{
					_currentLocation.LatitudeLongitude = new Vector2d(lastData.latitude, lastData.longitude);
					_currentLocation.Accuracy = (int)lastData.horizontalAccuracy;
					_currentLocation.Timestamp = timestamp;
					_lastLocationTimestamp = timestamp;

					_currentLocation.IsLocationUpdated = true;
				}

				if (_currentLocation.IsHeadingUpdated || _currentLocation.IsLocationUpdated)
				{
					SendLocation(_currentLocation);
				}

				yield return null;
			}
		}
	}
}
```

Try this, please. I added a simple delay to avoid the bad first update on Android.

**Comment by ProfHorse** [comment]
Yep, that's fixed it for me!

**Comment by Ariel-Feldman** [comment]
Hi @david-rhodes   Sorry to bring this topic again - 2 years later :)
But I'm hitting a wall and it seems like you are the only one who can help...
I using" MapxBox V 2.0.0| unity 2018.4 | Android (Pixel2) | Unity Remote 5
The Mobile builds work fine and everything but when I play under Unity Remote it does not show me any map image - I've tried to set the Editor Location Provider to 
1) AndroidDevice LocationProvider - I've got no error or warning - but it doesn't work
2 )DefaultDevice LocationProvider  - I've got a warning with a typo (?): "UniAndroidPermission works only Androud Devices".

Any Idea What to Do?.... 
Thanks!
