### ISSUE TITLE
Dynamic Zoom with location provider repositions the player transform

### ISSUE THREAD

**Issue by sonalranjit** [mapbox/mapbox-unity-sdk#373]
Hello, I am trying to implement a PinchZoom functionality in an application i am building. I have successfully got it zooming in and out with a 2 finger pinch to zoom. I am following the `mapreload` example scene where the map is re-initialized after the zoom value is updated. I have this running in conjunction with the LocationProvider, what is happening after a zoom in and out is that it is repositioning the PlayerTransform to the middle of the screen, which is not what i want even though i have explicitly defined the player transform position to be the location from the `devicelocationprovider`. Is there a better way to honor the devicelocation from the devicelocationprovider?

**Comment by david-rhodes** [comment]
@sonalranjit What `AbstractMap` component are you using? What component are you using to place your player avatar?

So long as you use `PositionWithLocationProvider` and update the map's `CenterMercator` and `WorldRelativeScale` properties correctly, everything should align properly.

Most of the logic you need is right here: 
```cs
_targetPosition = Conversions.GeoToWorldPosition(
					location.LatitudeLongitude,
					_map.CenterMercator,
					_map.WorldRelativeScale).ToVector3xz();
```

**Comment by sonalranjit** [comment]
@david-rhodes I am using a `BasicMap` AbstractMap component. to place the player avatar i have tried  the logic you provided, it is still centering the player avatar in the middle of the screen.

**Comment by david-rhodes** [comment]
@sonalranjit I just tested by creating a prefab of `Player` and `LocationProvider` from `LocationProvider.unity` scene. Then I went into the `MapReload` scene, changed the map to `BasicMap`, added the location provider and player prefabs and hooked up required fields.

When changing zoom level and pressing `Load` button, everything worked as expected (player avatar relocated to stay in the same relative location).

<img width="667" alt="screen shot 2017-11-21 at 11 32 48 am" src="https://user-images.githubusercontent.com/23202691/33090204-61f10bb6-ceb0-11e7-87e0-42bb313ad36e.png">
<img width="666" alt="screen shot 2017-11-21 at 11 32 39 am" src="https://user-images.githubusercontent.com/23202691/33090205-62062b72-ceb0-11e7-83e3-f9954c09c50d.png">

**Comment by david-rhodes** [comment]
The latency probably comes from a few places. Check the `PositionFollowFactor` value of the `PositionWithLocationProvider` component on `Player`. If that value is small, it will lerp slowly to its target position. Increase this value.  

There was also a bug where iOS did not seem to report location updates properly after the first update. Wifi could be a possible source of confusion for the OS, here (disable Wifi and test?). Note that the way iOS location services work (with Unity, at least), is that new locations are not generally reported until you've moved a certain distance. See `updateDistanceInMeters` here: https://docs.unity3d.com/ScriptReference/LocationService.Start.html. This means you must walk around before getting more location updates. Please let me know if these solutions help.

**Comment by sonalranjit** [comment]
Thank you for all your help @david-rhodes i believe the root issue for me was the location not being updated or initialized on iOS. I believe i am on the same issue as #384 . I'm trying to wrap my head around why the device isn't localizing in a reasonable amount of time. When i test with the LocationProvider example there is no latency on initializing the location. But when i try on a new scene with the same components as the LocationProvider scene, the latency on initialize is very noticeable and sometimes it won't get a location until i start another location app such as  google maps on the iOS device then go back my unity application.

**Comment by mecadiego113** [comment]
It seems iOS location services don't run good enough with Unity. If you test it while developing (sit in front of your PC eating Pringles) it will fail most of times. But if you go out and try to run it outdoors, while you keep moving, it gonna work much better.

**Comment by sonalranjit** [comment]
@mecadiego113 thank you for your advice, i completely understand the technology behind how gps works. this issue is regarding me not being able to recreate the example provided in the unity-sdk, where the locationprovider example is able to initialize in a reasonable time vs. me recreating the same scene with the same components but failing.

**Comment by david-rhodes** [comment]
@sonalranjit Something fishy is definitely happening with iOS + Unity with regards to location services. Have you tried launching the app and walking around outside to see if the map ever loads?

**Comment by sonalranjit** [comment]
@david-rhodes I have solved my issue. One of my scripts was trying to access the devicelocationprovider before it was initialized which was causing the location to not update. Thank you for the great support. Feel free to close this issue.

**Comment by mecadiego113** [comment]
@sonalranjit are you sure you fix the location update issue? I'm interested in how this could be done.

**Comment by sonalranjit** [comment]
@mecadiego113 im not sure if it applies to your issue. But i mentioned how i fixed my issue. I had a script trying to access the Location from the devicelocationprovider before the location was acquired. so thats why it wasn't updating the transform when the map was initialized.
