### ISSUE TITLE
UnityTile destroyed when scene switching

### ISSUE THREAD

**Issue by mecadiego113** [mapbox/mapbox-unity-sdk#374]
Hello there!

I'm using the latest @david-rhodes implementation of LocationProviderFactory.
I have a "map scene" where the Mapbox magic is done and many other standard scenes.
When I perform a scene switch I get this error:

```
MissingReferenceException: The object of type 'UnityTile' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
```

If I come back to the "map scene", I can't reinitialize the map (I'm using `BasicMap` with `InitializeMapWithLocationProvider`).

What's wrong with this?

Thank you!

**Comment by mecadiego113** [comment]
I think those lines are the problem (`AbstractMapVisualizer`): 

```
// Cleanup gameobjects and clear lists!
// This scriptable object may be re-used, but it's gameobjects are likely 
// to be destroyed by a scene change, for example. 
foreach (var tile in _activeTiles.Values.ToList())
{
        Destroy(tile.gameObject);
}
```

**Comment by david-rhodes** [comment]
@mecadiego113 Thanks. I swear this is a bug I've fixed at least 3 times now. I imagine there is some temporal coupling issue with unity object lifecycle. We'll take another look.

**Comment by mecadiego113** [comment]
Does the commit #362 fix this?
I also had problems with **iOS** location services.
At the beginning of the scene, the `InitializeMapWithLocationProvider` script is disabled until I have verified that the location of the device is enabled (`Input.Location.isEnabledByUser`). In case the location is activated, the initializer of the map activates, and it should be created with the position it receives from the GPS of the device. However, the map is not initialized, as a change of position is not executed (`OnLocationUpdate`)

**Comment by david-rhodes** [comment]
#362 is not related to this at all. You should not disable `InitializeMapWithLocationProvider` at all, otherwise it will not register to the location provider events. `DeviceLocationProvider` already ensures that location services are enabled by user, so your check is redundant.

**Comment by mecadiego113** [comment]
Roger that!

I'gonna delete all my redundant location checks, but... did you pay attention to the following use case: 

> start the app/game with the location disabled -> go to the "map scene" -> enable the location

Should this work with the current implementation of `DeviceLocationProvider`?

**Comment by david-rhodes** [comment]
@mecadiego113 Yes. Unity will ask the user for permissions (if they are not already granted for that application) upon requesting the location service to start. This location provider is in the map scene, but you could move `LocationProvider` to your main scene and allow location permission before  needing it, if you desire.

**Comment by mecadiego113** [comment]
Thank you @david-rhodes!

I like the way the AbstractLocationProvider is going :D

**Comment by david-rhodes** [comment]
Keeping open until we merge the scene change fix. 😉

**Comment by david-rhodes** [comment]
#381

**Comment by Rahulxx01** [comment]
How to save position of the player when switching the scenes and when I return to that previous scene it should return to the same position back???
