### ISSUE TITLE
Initialize turns off map tiles

### ISSUE THREAD

**Issue by HNKMaster** [mapbox/mapbox-unity-sdk#377]
I'm trying to change the style of my map in-game by modifying the MapUI on the Factory. Everytime I call Initialize() on my map (for example, by pressing Space), my map dissapears. I noticed in hierarchy that every map tile is turned off. When I meddle with the Zoom slider and Initialize again the map (with Space), it works like I want. What's the reason for dissapearing my map?

**Comment by david-rhodes** [comment]
I'm not sure what you mean by map disappearing. But, tiles will be recycled and reloaded with new data when calling `Initialize` on a map object. If you change the style (MapId) of your raster map, a new set of tile requests must be sent to Mapbox servers. This means that we must unload the current tiles and wait for data to be returned from the server to show the new tiles. We use object pooling for this case to save resources and avoid `Instantiate` and `Destroy` calls, which wreak havoc on the GC.

Do you have a code snippet you can share?

**Comment by HNKMaster** [comment]
This is my script for changing syles:

```
void ChangeMapStyle()
{
        factory.MapId = "mapbox://styles/mapbox/" + mapIDs[mapIDCount];
        mapIDCount++;
        if (mapIDCount > 1) mapIDCount = 0;
        map.Initialize(map.CenterLatitudeLongitude, map.Zoom);
        //UpdatePointPosition
}
```

[And this is how my hierarchy looks after using it.](http://oi68.tinypic.com/wukolu.jpg)

**Comment by david-rhodes** [comment]
I just changed `ReloadMap.cs` to the following and everything works as expected:

```cs
using Mapbox.Unity.MeshGeneration.Factories;
using System.Linq;
namespace Mapbox.Examples
{
	using Mapbox.Geocoding;
	using UnityEngine.UI;
	using Mapbox.Unity.Map;
	using UnityEngine;

	public class ReloadMap : MonoBehaviour
	{
		Camera _camera;
		Vector3 _cameraStartPos;
		AbstractMap _map;

		[SerializeField]
		ForwardGeocodeUserInput _forwardGeocoder;

		[SerializeField]
		Slider _zoomSlider;

		[SerializeField]
		Button _button;

		[SerializeField]
		MapImageFactory _factory;

		[SerializeField]
		string[] _mapIds;

		void Awake()
		{
			_camera = Camera.main;
			_cameraStartPos = _camera.transform.position;
			_map = FindObjectOfType<AbstractMap>();
			_forwardGeocoder.OnGeocoderResponse += ForwardGeocoder_OnGeocoderResponse;
			//_zoomSlider.onValueChanged.AddListener(Reload);
			_button.onClick.AddListener(Reload);
		}

		void ForwardGeocoder_OnGeocoderResponse(ForwardGeocodeResponse response)
		{
			_camera.transform.position = _cameraStartPos;
			_map.Initialize(response.Features[0].Center, (int)_zoomSlider.value);
		}

		void Reload()
		{
			_factory.MapId = _mapIds[Random.Range(0, _mapIds.Length)];
			_camera.transform.position = _cameraStartPos;
			_map.Initialize(_map.CenterLatitudeLongitude, (int)_zoomSlider.value);
		}
	}
}
```

What `AbstractMap` implementation are you using?

**Comment by HNKMaster** [comment]
At first I used the BasicMap found on the LocationProvider example, but because I don't need to move the player with my device, I disabled everything related to it.

**Comment by david-rhodes** [comment]
Did you try the above script the `MapReload` scene?

**Comment by HNKMaster** [comment]
I tried and it worked. After some testing, I discovered it was the camera the main problem. I'm using the Camera Bounds Tile Provider, and if the camera stays in the same position when initializing the map, nothing happens until I move the camera. I need that provider, but I can't find anything that allows refreshing it.

**Comment by david-rhodes** [comment]
Ah, good catch! 

Add this line to `OnInitialized` of your tile provider:
`_cachedTile = new UnwrappedTileId();`

The issue is that the cache tile was never cleared to tiles are never requested again.

**Comment by HNKMaster** [comment]
Great! Now it's working pretty good. Thanks a lot!
