### ISSUE TITLE
Mapbox Tiles With Texture: How can I flatten the surface of my generated map?

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#378]
Cheers!
I am trying to position a character inside a map I have generated in my Unity project. But the map generated has inconsistent texture (not flat) and so the character, when it moves, overlaps with the map. Can I flatten the map? Thank you so much in advance.

**Comment by david-rhodes** [comment]
What type of `TerrainFactory` are you using with your `MapVisualizer`? If you're using a `TerrainFactory`, switch to `FlatTerrainFactory` instead.

**Comment by AkaneMikazuki** [comment]
Thank you, sir!
But if I choose to maintain TerrainFactory (which I'm using now), would it be okay to attach a rigidbody component to the Map Gameobject?

**Comment by david-rhodes** [comment]
You can still add a collider to a `FlatTerrainFactory` if that is your question. Just check the box in the inspector. What do you need a rigidbody for?
