### ISSUE TITLE
Mapbox in Unity: Can I view the map while in edit mode?

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#379]
Hello! As the question said, I want to know if I can view the map while in edit mode. Thank you in advance.

**Comment by david-rhodes** [comment]
We do not currently support this feature. Please see https://github.com/mapbox/mapbox-unity-sdk/issues/113 for reference.

**Comment by AkaneMikazuki** [comment]
Thank you for the answer, Mr, David.
