### ISSUE TITLE
How do I get the background / ground layer?

### ISSUE THREAD

**Issue by gerardsimons** [mapbox/mapbox-unity-sdk#383]
Hello,

I am trying to use the Mapbox Unity SDK to create a 3D virtual world for a boat simulator. I have been able to get all the layers, including the water layer to create meshes from. See picture below. The problem is that I want to get the ground surface layer, which according to Mapbox Studio is called `background`, because I want to raise the surface above the water (I know for a fact this area in Rotterdam has quays all around the water which I want to simulate). 

Unfortunately using `background` as a key in my TileFactory, doesn't seem to work when trying to attach a `VectorLayerVisualizer`. How would I go about doing this? Can I get this background layer, or is there another approach I can take to get the ground surface?

<img width="1440" alt="screen shot 2017-11-22 at 13 07 05" src="https://user-images.githubusercontent.com/4247845/33126978-d99b3818-cf86-11e7-878f-4e1d9b08533a.png">

Thank you

**Comment by david-rhodes** [comment]
> because I want to raise the surface above the water

First of all, are you using a terrain factory? Secondly, what do you want the `background` to look like? You can simply use a `MapImageFactory` and set your MapId accordingly. This will create imagery underneath your vector tile geometries.

**Comment by gerardsimons** [comment]
Thanks for the response. I am using a terrain factory, but this will change the entire terrain including the water (also the difference in water and surrounding quay is not reflected in the actual height measurements). I am also concerned the water is actually on top of background so any change to background would also put a mesh on the water? In any case, if you see the dark surface underneath the buildings, that should be raised, so there is basically a wall between the water and the shore. Not sure if it's possible to get that part of the map on a layer selection basis.

If not, I would have to manually generate boundaries of the water in a separate script.

**Comment by david-rhodes** [comment]
Let me to summarize what you'd like--please correct me if I'm wrong.

You want 3D elevated terrain, but with water height at a "constant" level? I'm guessing accuracy of elevation data is the main issue here? I don't think it's trivial, but you could use vector tile data (waterway and water layers), to cut out the 3D terrain mesh (boolean mesh operation). 

@brnkhy may have some additional suggestions.

**Comment by gerardsimons** [comment]
Exactly so. The difference in height would only be a meter or so (or even less at high tide, it's close to the sea). Aesthetically it would be nice if I would have the cityscape slightly elevated. This does not need to be accurate. You approach of boolean mesh operation sounds interesting, and might be the way to go if no "easy" way exists. Thanks for the quick help
!

**Comment by david-rhodes** [comment]
@brnkhy All yours, now. This is your area of expertise. 😏

**Comment by brnkhy** [comment]
@gerardsimons I think easiest way to make it is simply cutting water out of tile as discussed. If I remember correctly I used Clipper library back when I did this. It worked good but you might have some small precision issues while converting back&forth to int value type which Clipper uses.

This is what I did earlier this year. That space background is a skybox so all "water" cut out. I remember having lots of small issues though, like precision as I mentioned.
![unity_2017-01-09_05-17-19](https://user-images.githubusercontent.com/1465390/33172580-c68a37ca-d061-11e7-92b1-d29fd8a90afb.png)

Clipper; http://www.angusj.com/delphi/clipper.php

**Comment by brnkhy** [comment]
@gerardsimons I did it on runtime. Vector factory actually waits for terrain and image factory to load so once you have vector data, you can assume terrain and imagery is already loaded. Then you can simply pass water layer from the vector data and the terrain data/gameobject to a function to do the boolean operations. As I said I used Clipper for that, wasn't the easiest thing but should be doable I guess.

**Comment by gerardsimons** [comment]
Great I'll try that, thanks for the help!
