### ISSUE TITLE
Mapbox for Unity: Why is my map not displaying correctly?

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#385]
Hello! I'm creating a game using Mapbox in Unity, though the map is displayed too bright like the one below:
![image](https://user-images.githubusercontent.com/28637958/33159072-b6a84cb4-d04a-11e7-9835-58dc09df9aa1.png)
How can I fix this? I tried altering the Directional Light but to no avail.
Thank you!

**Comment by brnkhy** [comment]
@AkaneMikazuki hard to tell what's going on from that shot but it looks like terrain is loaded. Maybe you don't have an image factory and flat white material shines too much under light?
Are you having same issue with demo scenes?

**Comment by AkaneMikazuki** [comment]
The demo scenes work fine. This used to work fine (at least better than that - gray, not too bright) but upon tweaking values (which I don't exactly remember which), it got worse. Thank you! I'm gonna post another screenshot. I'm sorry.

**Comment by brnkhy** [comment]
I'm closing this one for now, please re-open it if you need.
