### ISSUE TITLE
Mapbox in Unity: Can I use GPS values that are accurate to 20+ meters ?

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#396]
Hi again! I'm sorry for opening too many issues. I just have to ask if it's okay to use GPS readings accurate to 20 meters or higher? It's for placing objects on the map. Thank you in advance!

**Comment by BergWerkGIS** [comment]
@AkaneMikazuki you can use any values you want for positioning objects, but be aware that they most likely won't appear on the map where they should be.

> if it's okay to use GPS readings accurate to 20 meters or higher?

Also be aware that the documentation of [`LocationInfo.horizontalAccuracy`](https://docs.unity3d.com/ScriptReference/LocationInfo-horizontalAccuracy.html) and [`LocationInfo.verticalAccuracy`](https://docs.unity3d.com/ScriptReference/LocationInfo-verticalAccuracy.html) does not specify the units of the accuracy.

I highly suspect that they are **_not_ in meters** but represent horizontal/vertical dilution of precision (H/V-DOP).
And a HDOP of `20` is a really bad value:

https://en.wikipedia.org/wiki/Dilution_of_precision_(navigation)#Meaning_of_DOP_Values
> 20:  Poor - At this level, measurements are inaccurate by as much as 300 meters with a 6-meter accurate device (50 DOP × 6 meters) and should be discarded.

**Comment by AkaneMikazuki** [comment]
Can I do something so I could place objects at certain latitude&longitude on the map? I'm sorry. I'm trying to develop a location-based game. Thank you again, sir!

**Comment by david-rhodes** [comment]
@AkaneMikazuki You want to use Conversions.cs or VectorExtensions.cs: https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Utilities/Conversions.cs#L105. Keep in mind that these rely on the map root being at `(0,0)`. If your map is not at the origin, you must manually add your offset.

**Comment by MiroMuse** [comment]
Let us know if you need more help - closing this issue for now 👍

**Comment by jchimento** [comment]
@david-rhodes  I'm using the dynamic zoom map and trying to reposition element on the map.  You mentioned that if the map moves from the origin you need to add an offset. How would one go about calculating that offset?

**Comment by atripathi-mb** [comment]
@jchimento With version 1.3.0 , there are helper methods on `AbstractMap` called `WorldToGeoPosition` & `GeoToWorldPosition` which take care of that offset.
