### ISSUE TITLE
Map Reinitialization causing Extraneous TileSet Objects

### ISSUE THREAD

**Issue by stevenroach7** [mapbox/mapbox-unity-sdk#397]
I’m using version v1.2.0 of the Mapbox SDK to create a 3D data visualization. 

The visualization uses different neighborhoods polygons with economic properties (i.e.property value at different times) created in Mapbox Studio. I created a slider to allow users to dynamically change the time period of the data visualized (i.e. housing price in 2009, 10, 11, etc). This means that the Modifier Stack I am using (specifically the HeightModifier and TextureModifier) needs to update at runtime as the data visualized is being encoded with the height and side material of each neighborhood polygon. 

My current approach is based off of the ReloadMap example. I have a ReloadMapTime script that is added to the panel containing the slider. When the slider value is changed, the script updates a global singleton and reinitializes the map. The height and texture modifiers read from this singleton to determine which data to visualize. This is working for the most part, but when I change the slider value, excessive TileSet Objects are being created.

Before changing slider value:
<img width="1433" alt="screen shot 2017-11-25 at 11 15 00 am" src="https://user-images.githubusercontent.com/14096122/33232926-30d2bb3e-d1d4-11e7-94c8-22074a889622.png">

After changing slider value:
<img width="1440" alt="screen shot 2017-11-25 at 11 15 43 am" src="https://user-images.githubusercontent.com/14096122/33232931-3d05d0a8-d1d4-11e7-80ed-601218604e3c.png">

I figured out that these TileSet Objects are the shapes of the neighborhoods about 2 tiles left and 2 tiles above but with the imagery of the location it is being placed in. I tried using a MapAtSpecificLocation instead of BasicMap and the problem persisted. 

Extraneous TileSet in bottom right corner
<img width="1170" alt="screen shot 2017-11-25 at 11 38 10 am" src="https://user-images.githubusercontent.com/14096122/33232994-604befd8-d1d5-11e7-8646-64cc7ab97faf.png">

Same as correct TileSet in middle of map
<img width="1178" alt="screen shot 2017-11-25 at 11 38 53 am" src="https://user-images.githubusercontent.com/14096122/33233002-6ff36542-d1d5-11e7-816e-4dccd8f8ceb4.png">

I've determined that the first HousingNeighborhoodData Container for each neighborhood is extraneous and persists when the slider value changes again. The second and correct container for each neighborhood is destroyed and a new container is created. Related, when I change the value of the slider, an offset map (I think the same offset) with no heights displays for a split second which feels quite clunky. This seems very similar to this issue [242](https://github.com/mapbox/mapbox-unity-sdk/issues/242).

Any ideas for where these extraneous TileSet objects are coming from? Is there a better approach to updating the heights and side materials without reinitializing the whole map?

Thanks!

**Comment by david-rhodes** [comment]
Re-initializing the entire map to support dynamic features is something I would recommend. As you mentioned, it is slow and clunky. Rather, I suggest making some sort of dynamic manager that caches the components you are interested in (do this at build time via singleton or something). Then simply modify the data directly through that manager, as needed.

This suggestion may help: https://github.com/mapbox/mapbox-unity-sdk/issues/364#issuecomment-344698525. 

All that said, this definitely seems like a bug with the way we cache features internal to each scriptable object. cc @brnkhy, any ideas?

**Comment by stevenroach7** [comment]
@david-rhodes Thanks for your suggestion. I'm not quite sure how to update the components dynamically. I basically want to rerun the height and texture modifiers for each of the neighborhood polygon components. I'm trying to cache these components and run a height modifier on them to update the mesh data but it isn't affecting the game object. Do I need to rerun the entire modifier stack on these components?

**Comment by david-rhodes** [comment]
I'm suggesting that you cache your gameobjects in a separate component (singleton?) that you can reference at runtime. Then, you simply iterate through the vertices (or simply scale transforms, depending on your use-case and object pivots) to change the size. I **do not** suggest trying to reuse modifiers once a map has already been generated.

**Comment by stevenroach7** [comment]
Okay I got it to work using your suggestion. Much better UX! Thank you!

**Comment by david-rhodes** [comment]
Glad we could help!
