### ISSUE TITLE
Mapbox configuration with proxies

### ISSUE THREAD

**Issue by sabienAmb** [mapbox/mapbox-unity-sdk#401]
The gist is that there are several ways to issue HTTP request in Unity (WWW class, UnityWebRequest, etc.) and the implementation they were using were not actually following the proxies and therefore being blocked. After changing the class to use HTTPWebRequests, I am now able to get the API key to validate and pull the right textures.

Step-by-step instructions on how to fix it to work with windows store build:
1.	Set Raytheon’s proxy
a.	Click the start menu
b.	Search for ‘Environment Variables’
c.	Select ‘Edit environment variables for your account’
d.	You’ll need to enter 3 new variables
i.	Under ‘User variables for …’ hit ‘New…’
1.	Variable name: HTTP_proxy
2.	Variable value: http://proxy.ext.ray.com:<httpPort>
ii.	Next variable
1.	Variable name: HTTPS_proxy
2.	Variable value: https://proxy.ext.ray.com:<httpPort>
iii.	Next variable
1.	Variable name: NO_PROXY
2.	Variable value: "127.0.0.1, localhost,*.ray.com,10.250.*"
2.	Edit the Mapbox code
a.	Unzip the attached file
b.	Move ‘MapboxConfigurationWindow.cs’ to ‘Assets\Mapbox\Unity\Editor’
i.	This will allow you to validate your token
c.	Move ‘HTTPRequest.cs’ to ‘\Assets\Mapbox\Unity\Utilities’
i.	This makes the HTTP request go through the proxy
d.	Move ‘Response.cs’ to ‘\Assets\Mapbox\Core\mapbox-sdk-cs\Platform’
i.	This is a helper for the HTTPRequests
3.	Validate your key
4.	Hit play

[HTTPRequest.txt](https://github.com/mapbox/mapbox-unity-sdk/files/1507604/HTTPRequest.txt)
[MapboxConfigurationWindow.txt](https://github.com/mapbox/mapbox-unity-sdk/files/1507605/MapboxConfigurationWindow.txt)
[Response.txt](https://github.com/mapbox/mapbox-unity-sdk/files/1507606/Response.txt)

Now, at this point there are still two errors in Request.cs when trying to build to UWP (but this works currently with windows store). The x509 certificates aren't available, as well as the line: ```HttpWebResponse http_response = (HttpWebResponse)_request.GetResponse();```
This seems to be an issue dealing with which .Net version is being compiled to, and the compiled version is quite limited by this.

**Comment by BergWerkGIS** [comment]
@sabienAmb I was able to export to UWP with your files by changing the player settings to:

* Scripting Runtime Version: Stable Net 3.5
* Scirpting Backend: IL2CPP
* Api Compatibility Level: .Net 4.6

Would that work for you?

**Comment by sabienAmb** [comment]
Let me test it quick

**Comment by sabienAmb** [comment]
IL2CPP/.Net 4.6 do not show up as options for those two settings. What version of unity are you using?

**Comment by BergWerkGIS** [comment]
I'm on `2017.1.1f1`.

**Comment by sabienAmb** [comment]
odd. I'm on the same version. Not sure what I changed, but they showed up after a restart. Testing the build now

**Comment by sabienAmb** [comment]
What settings did you use for the UWP build? I have what is in the picture below
![uwpbuildsettings](https://user-images.githubusercontent.com/34042428/33499635-47ed7306-d69b-11e7-96c2-28958475ab04.PNG)

**Comment by BergWerkGIS** [comment]
You have to click on `Player Settings ...`

**Comment by sabienAmb** [comment]
I changed them to what you recommended:
![uwpplayersettings](https://user-images.githubusercontent.com/34042428/33499736-d0451dbc-d69b-11e7-8990-fffd5cb0a8ae.PNG)

**Comment by BergWerkGIS** [comment]
does it work?

**Comment by sabienAmb** [comment]
no, it gives me the error list I sent you

**Comment by BergWerkGIS** [comment]
Which version of the SDK are you using?
Is updating an option?

**Comment by sabienAmb** [comment]
Are you referring to the mapbox sdk? I’m using 1.2... if you’re referring to the windows sdk it’s set on latest which is like 0.16 something ... I’m not at my pc right now I can give you the exact version in a bit

**Comment by sabienAmb** [comment]
UWP sdk: 10.0.16299.0

**Comment by sabienAmb** [comment]
If I use .Net as the scripting backend I get a separate, single error:
![uwpneterror](https://user-images.githubusercontent.com/34042428/33506746-cb5fb3aa-d6b6-11e7-84d5-41995064b072.PNG)

**Comment by MiroMuse** [comment]
@BergWerkGIS @atripathi-mb did we end up solving this?

**Comment by jordy-isaac** [comment]
@sabienAmb If you're still having issues with this on version 1.4 please re-open the ticket.
