### ISSUE TITLE
Creating LineStack as one continuous object

### ISSUE THREAD

**Issue by rslevin** [mapbox/mapbox-unity-sdk#406]
Is there a modifier im missing which makes a line object continuous? I see mention of a 'Smooth Line Modifier, but cant seem to make it work. This geomerty example has a few lines with different geometry heights, would be great to make this flow as one.

![image](https://user-images.githubusercontent.com/9067513/33306510-d4e2051a-d44d-11e7-9819-c3af996b1ffc.png)

**Comment by brnkhy** [comment]
@rslevin I'm afraid there's no easy, builtin solution for this. We already create continuous mesh for road segments but data consists of lots of small road segments like that. 

There's two things you can try;
-create custom road layer visualizer, merge all road segments and create mesh for whole network at once afterwards
-create mesh for all individual road segments as usual, then merge the creates meshes together (still there'll be discontinuities)

latter is technically easier. former would be much harder but you'll be able to customize and detail everything with full control.

**Comment by david-rhodes** [comment]
@rslevin Is this custom data?

**Comment by david-rhodes** [comment]
It looks like the custom data is just incomplete. Are you able to share a screenshot or a link to the dataset?

**Comment by rslevin** [comment]
Sure, is the map ID ok? - rslevin.4o2wd1nw, Layer Road-0zvml5

**Comment by david-rhodes** [comment]
I recommend that you add your custom tileset to a style for preview in Mapbox Studio. From there, you can verify if this is a data issue or not. To me, it just looks like data is missing.

**Comment by MiroMuse** [comment]
Let us know if you need more help - closing this issue for now 👍
