### ISSUE TITLE
Location Provider Visulaization with dynamic zoom map

### ISSUE THREAD

**Issue by tahoorpirzada** [mapbox/mapbox-unity-sdk#409]
How to use location provider visualization with dynamic zoom map?

**Comment by david-rhodes** [comment]
Example coming soon! 😄

**Comment by tahoorpirzada** [comment]
Thanks, please upload it soon

**Comment by david-rhodes** [comment]
It should be included in the next release (1.3). We anticipate this will be available in 1-2 weeks. Alternatively, you can follow along with this PR: https://github.com/mapbox/mapbox-unity-sdk/pull/414.
