### ISSUE TITLE
Scene switching changes overall lighting

### ISSUE THREAD

**Issue by thedrummeraki** [mapbox/mapbox-unity-sdk#410]
Let`s assume we have two scenes with two maps. Before switching scenes, our map (normally) looks like this:

![image](https://user-images.githubusercontent.com/14348784/33388153-252158fa-d4fd-11e7-99dc-ac1722ec76f1.png)

After changing switching scenes with `SceneManagement.LoadScene("NewScene")`, we end up with something like the following: 

![image](https://user-images.githubusercontent.com/14348784/33388049-d48fa432-d4fc-11e7-98f8-bb270f0502c5.png)

I looked up online if there is any other clean to switch scene in Unity, and this seams to be the cleanest way of doing it. I also looked for PRs/issues discussing in issue similar to mine and didn't find anything interesting.

Any thoughts?

Thanks,

**Comment by david-rhodes** [comment]
I'm pretty sure this is a Unity lighting bug. I've experienced it before (without Mapbox). One thing you can do is simply bake lights in your scene. You don't actually need to create lightmaps, but for some reason the light baking process fixes this bug. 

More info: https://answers.unity.com/questions/919940/applicationloadlevel-changes-lighting-for-some-rea.html

**Comment by thedrummeraki** [comment]
Wonderful! I've never actually experienced anything like this with Unity, but just building our application "fixed this issue". Thanks for the link!
