### ISSUE TITLE
Part 2 tutorial for unity 

### ISSUE THREAD

**Issue by sarahabdalfatah** [mapbox/mapbox-unity-sdk#411]
In the unity tutorial in the part where it says 
"in your CityDefaultBulidingStack directory, create a TextureModifier called CityBuildingTexture, then check the TextureTop and TextureSides parameters and assign a material to the TopMaterials and SideMaterials lists."
it attach CityBuildingMaterial in the topmaterial and sidematerials.
I cant find that anywhere in the package, any help please?

**Comment by jellena** [comment]
@sarahabdalfatah Creating materials in Unity is super easy. Just right click in any of your asset folders and select `Create` then `Material`. Once done you can use that material in any way you'd like.

**Comment by sarahabdalfatah** [comment]
Im sorry it was innocent mistake, i thought that was the probelm, but i followed all the steps and i still havent got the 3D builds in, please see the image
![map](https://user-images.githubusercontent.com/33529143/33394508-9269ec16-d510-11e7-9282-ce1ab79deac2.jpg)

**Comment by jellena** [comment]
Is there a 'SnapTerrainModifier' in your building stack? Could you attach a screenshot of your map editor window like the one here? That would help us show how you've built your project out.

![screen shot 2017-12-01 at 1 52 35 pm](https://user-images.githubusercontent.com/4824060/33498349-fd2e8ab8-d69e-11e7-84a8-8e360b2052ec.png)

**Comment by jordy-isaac** [comment]
@sarahabdalfatah Sorry that you've had some trouble. This was probably due to the documentation being out of date. We just updated the tutorials and if you follow the steps as they are [here](https://www.mapbox.com/help/unity-mesh-pt-2/) you should see those buildings render.

**Comment by sarahabdalfatah** [comment]
you guys are so nice, i followed the new documentation but im still not getting the 3D building, dont know what im doing wrong
![issue 2](https://user-images.githubusercontent.com/33529143/33579472-ee1b3ed8-d917-11e7-8b24-529f3502cee4.jpg)

**Comment by brnkhy** [comment]
@sarahabdalfatah I'm ashamed to ask this but can you try not using capital letter on layer name, so "building" instead of "Building"? that might be it.

**Comment by jordy-isaac** [comment]
Hi @sarahabdalfatah! Thanks for the kind words. We're happy to help. It also looks like you need to add a `Game Object Modifier` as you have 2 `Mesh Modifiers` in your `City Merged Building Stack`.

Please see this section of pt. 2:
https://www.mapbox.com/help/unity-mesh-pt-2/#create-a-stack-for-your-building-layers

To make this setting:
1. Select your CityMergedBuildingsStack.
2. Under Game Object Modifiers select Add New Empty.
3. Find and select your CityBuildingTextureModifier

I hope this helps!

**Comment by brnkhy** [comment]
@jordy-isaac actually I think that "two mesh modifier" thing is a bug on our side. second one should say "game object modifier".

**Comment by jordy-isaac** [comment]
@saisriskandarajah Disregard my last message. @brnkhy has it right about the case sensitive parameter for `building`. This should clear it up for you.

**Comment by sarahabdalfatah** [comment]
OMG you guys are awesome, thank you so much for trying to help me, im so sorry to keep bothering you but im trying to convince my boss to use your model to create something awesome within unity.


Ok so in the CityBuildingLayerVisualizer i did change "building" to lower case and thats the result i got, why the building are not solid?
![issue 3](https://user-images.githubusercontent.com/33529143/33626460-a7370450-d9c8-11e7-97aa-e74c75ad1457.jpg)

**Comment by brnkhy** [comment]
@sarahabdalfatah no problem at all :)
Now you have your buildings and you have height modifier pushing polygons up ( to become roofs). There are two possibilities;
(1) You don't generate side walls
    - There's a checkbox in the HeightModifier for that
(2) You generate the side walls but don't apply material so they are invisible
    - Check your texture modifier to see if there's any material set for side walls. You can check other texture modifiers in the project to see how it works.

hope that helps!

**Comment by edyvice** [comment]
Unity2017.3.1f1 
Tutorial2 and Tutorial3,  can't get 3D building. : (

<img width="716" alt="80dcd527-08d0-4bce-9242-89a7e27bfb99" src="https://user-images.githubusercontent.com/17284887/36561001-6f8c7404-184d-11e8-8fec-6525e84aa53d.png">
<img width="1163" alt="2018-02-23 3 56 49" src="https://user-images.githubusercontent.com/17284887/36561074-a752bde4-184d-11e8-99d5-70d7188ad0de.png">

**Comment by brnkhy** [comment]
@edyvice I think your mesh modifier ordering is off. Yes ordering matters and it's kinda hard to work with that at the moment but we're working on that. They should go like 
-snap terrain
-poly modifier
-uv modifier
-height modifier

can you try that and let me know if it works or not?

**Comment by edyvice** [comment]
@brnkhy Thank you! Your solution works! Maybe the tutorial should mention the modifier ordering :)
Anyway, your project is great!
<img width="617" alt="b6f7e4f6-94f9-4de3-921c-0169c1415123" src="https://user-images.githubusercontent.com/17284887/36575683-393915ee-1887-11e8-806e-ab4d35b0c43c.png">

**Comment by MiroMuse** [comment]
Hey @jordy-isaac, check this out for our documentation sprint 👍 Closing for now - please reopen if you need anything @edyvice !
