### ISSUE TITLE
ModifierStack.cs null material error

### ISSUE THREAD

**Issue by LastMonopoly** [mapbox/mapbox-unity-sdk#416]
After `var mr = go.AddComponent<MeshRenderer>();`,
please add `mr.materials = new Material[0];` to make sure the mesh renderer have no material at all, rather than have 1 null material like this:
<img width="726" alt="screen shot 2017-11-30 at 6 44 12 pm" src="https://user-images.githubusercontent.com/839799/33426940-8a5fa0a8-d5fe-11e7-8a16-c514504b6f8a.png">

**Comment by brnkhy** [comment]
@LastMonopoly I just realized we haven't answered this. We even discussed it but forgot to reply here obviously, sorry about that.
I personally like errors or missing components not hiding themselves, so I like that bright pink color as you'll surely notice it and fix whatever was missing. You can say it would be like a default material and that would be OK but still doing that in code like that doesn't feel right.
This is more of a personal preference though, I'm open to other ideas.

**Comment by brnkhy** [comment]
Closing this for now but feel free to reopen it if you want to discuss.
