### ISSUE TITLE
Tile texture goes pitch black when y-axis scaling is an extremely low value

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#42]
This especially happens if you load the world in low zoom levels like 1 to 5. Root world object y-axis scale goes extremely low and unless TileSize is increased proportionally (i.e. using default 100), Unity cannot render the tile texture. 
It renders if world scale y-axis is set to 1 (breaks heights of features&terrain) or TileSize increased to a much bigger number (like 1000 or 100000 depending on zoom level).

**Comment by david-rhodes** [comment]
@brnkhy Think we could just set a minimum y scale value?

**Comment by Spaxe** [comment]
I just bumped into potentially this issue ... but only on Windows 10, Unity 5.6.2f1. Pitch black.

On MacOS with Unity 5.6.1f1 this issue doesn't happen, although I did notice that at small tiles (say 0.5 TileSize), lighting doesn't quite work and I get a dim terrain. 

Unlit is a workaround for now.

**Comment by BergWerkGIS** [comment]
So far I've only come across that issue on one of my Android devices using `Slippy` demo.
Spent some hours fiddling with various settings and the combinations thereof.

Hope I haven't forgotten anything but these are the only changes needed for `Slippy.unity` to consistently reproduce the issue on `Samsung Tab S2 8"`.

**Does not occur on `OnePlus 3` or `Windows native` or `Windows Store/UWP`.**

`Camera` position:
![image](https://user-images.githubusercontent.com/4549888/27584457-6b43034a-5b38-11e7-9720-f8270c74e23e.png)


`Map`
* at `47.04071, 12.83326`
* `Zoom`: `14`

results in:

![z14](https://user-images.githubusercontent.com/4549888/27587254-f2694158-5b43-11e7-9efd-ccfa3acfa69f.gif)

If I change `SlippyTerrain/Factories/Resource/TerrainMaterial -> Shader` to `Unlit/color` everything is white.
If I change it to `Unlit/Texture` ✅ 
If I change it to `Unlit/Transparent` ✅ 
If I change it to `Unlit/Transparent Cutout` ✅ 


If I change the shader back to `Standard` but set map zoom to `15` it also works:

![z15](https://user-images.githubusercontent.com/4549888/27587284-1427fad2-5b44-11e7-9654-c420b47e4ffc.gif)

**Comment by david-rhodes** [comment]
This is almost certainly related to a floating point precision issue, specifically in how lighting is calculated when the tiles are scaled so far down.

Another workaround is to increase the tile size when using lower zoom levels (this results in less transform scaling).

**Comment by david-rhodes** [comment]
Fixed: 032466b58ca6418d61f285a91f28c2d65ae7e54b
