### ISSUE TITLE
Positioning character on map (Android)

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#421]
Hello!
I've been trying to have my character move as the device's GPS changes. But I'm having a hard time basically because I haven't read docs supporting this. Can the map's tileset's GPS coordinates be extracted? I am going to get the device's location, find the coordinates on the map, and move accordingly.
PS. If how I worded it's messed up, please let me know. I really need help. TYIA!

**Comment by david-rhodes** [comment]
The `LocationProvider.unity` example shows how to use accomplish this. At the root of the problem, you must convert a lat/lon to a unity coordinate using `Conversions.cs`. See `PositionWithLocationProvider.cs` as an example.

**Comment by AkaneMikazuki** [comment]
Thank you! I've been working on that now. But I've noticed that the position isn't that accurate. I've also seen threads discussing about the combination of GPS and cellular network to provide more accurate lat and long. Could this be implemented in this situation?

**Comment by david-rhodes** [comment]
Mobile devices are already doing this for you, based on the desired accuracy that you set in the `DeviceLocationProvider`. But, your accuracy will vary based on your location, local interference or signal bounce, and your individual device.

**Comment by david-rhodes** [comment]
Closing for now. Please let us know if need additional clarification.
