### ISSUE TITLE
Preventing Floating point issues while keeping smooth experience

### ISSUE THREAD

**Issue by lukacat10** [mapbox/mapbox-unity-sdk#422]
So this week I tried to implement something similar to the LocationProvider example, which positions the player according to provided GPS and Compass data.

The most obvious issue in this case is the floating point precision. When I start my emulated gps coordinates in North America and than set it to Europe, everything becomes distorted. So maybe its not problematic for small distances, but I am trying to make my system work better at "distance infinity" from the starting position.

So I found the Dynamic Zoom example, and although it did the job, after looking in the code I saw that they unloaded the tiles, and set the CenterMercator every time the user moved. This caused the map to disappear and reappear on every move, and not only ruin user experience, but also use significant bandwidth. The comment above the specific line of code even states:

//panning
//TODO: move active tiles on pan
//HACK: just deactivate all active tiles

My question is, how:
1.  To offset the currently loaded memory tiles 
2. Make the map reposition the tiles according to their offset or the Center Mercator without unloading them.

**Comment by lukacat10** [comment]
Just found that the version that I downloaded from mapbox's website is outdated........

The new method mapVisualizer.RepositionTile(tileId) should work. I will test it out.

**Comment by david-rhodes** [comment]
If you intend to load tiles that are very far away from your current location, I suggest you reinitialize your map with the new lat/lon and zoom level (see `AbstractMap.Initialize()`). After all, you probably don't want to request all the tiles needed to get to that location.

**Comment by brnkhy** [comment]
@lukacat float precision is an annoying issue really but you shouldn't have this unless you want both scenes, visible in screen at the same time at high zoom level. And that's highly unlikely.
If you want to switch scenes/cities, just reinitialize as @david-rhodes suggested. That'll reset world center and keep everything in float range.
If you want to be able to move from NA to EU, you'll have to shift all existing tiles and world center gradually as camera moves etc.

**Comment by MiroMuse** [comment]
Let us know if you need more help - closing this issue for now 👍
