### ISSUE TITLE
Accuracy issue between my current lat and long and the mapbox lat and long

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#423]
Hi 
First of all I appreciate you guys for making an extraordinary sdk . This package is very helpful to work with real Map data. 
The problem I'm facing is some time there is difference between my actual latitude and longitude and latitude and longitude capture by mapbox. You can say upto 5-10 meter distance. If you guys know any thing that I'm missing or not implementing please guide me. Thanks in anticipation.

**Comment by david-rhodes** [comment]
How are you validating the difference in GPS coordinates? In other words, how do you know what you see in Unity is "wrong?"

I ask because we're simply using [Unity's location services](https://docs.unity3d.com/ScriptReference/LocationService.html).

**Comment by asadali26** [comment]
I'm using another GPS location detector APP to check my current lat and lon. 
Moreover the other APP shows Lat and Lon in six digits decimal or sometime more than six. Where as while using Mapbox lat and lon value not go further than five digit decimal place. 
I'm wandering may be this is the issue.

**Comment by david-rhodes** [comment]
That could be the case. Unity converts lat/lon to float for some reason. That said, this would only lead to a maximum offset of ~4 meters.

See here for possible workaround: https://feedback.unity3d.com/suggestions/gps-accuracy-double.

**Comment by asadali26** [comment]
thanks will look at it. 
Can you help me out what is TransformLocationProvider script does. and also what is the difference to check or uncheck the Use Transform Location Provider in Position With Location Provider script. Thanks

**Comment by david-rhodes** [comment]
If you don't check `Use Transform Location Provider`, the default `EditorLocationProvider` will be used to position that object (in the Unity Editor). If checked, the transform location provider will be used. This has a target transform that will send out lat/lon updates based on it's position in the map. So, you can mock locations by using the position of the transform.

**Comment by asadali26** [comment]
sounds good. One more issue I'm facing right now is that.  
I have two devices Samsung Galaxy J3, Android 6.01 and Samsung Galaxy S8, Android 7.0. 
Rotate with location provider works fine on Samsung Galaxy S8 but not work at all on  Samsung Galaxy J3.

**Comment by david-rhodes** [comment]
Unfortunately the compass accuracy will vary greatly with each device. In general, the compass should never be trusted. 😞 

You may also need to check that the the location permissions are enabled on the J3?

**Comment by asadali26** [comment]
Yes the location permission is enabled on J3.
So may be I'll make rotation a variable value and change at runtime

**Comment by asadali26** [comment]
By the way thanks a lot for your time. I really appreciate it. I'm closing the issue now.

**Comment by david-rhodes** [comment]
Our pleasure!

**Comment by msnmkh** [comment]
@david-rhodes 
 Hi David,
I want to develop a location base  vr  app that  have a centimeters accuracy gps  but when I use https://docs.unity3d.com/ScriptReference/LocationService.html or mapbox  the accuracy more than 10 meters.
Is there any way to increase accuracy of GPS??

**Comment by BergWerkGIS** [comment]
> Is there any way to increase accuracy of GPS??

@msnmkh only way to get **centimeter** GPS precision is to use a professional grade GPS device (these cost several thousands of $$$).

Take a look at the specs of your device (I suppose a mobile phone) and you'll see that you won't get better precision than 3 to 10 meters - under perfect conditions.

Perfect conditions are eg on a mountain top and not in a city with sky scrapers distorting the GPS signal.
