### ISSUE TITLE
Locationprovider demo doesn't show map on device (only on editor)

### ISSUE THREAD

**Issue by spinteractive** [mapbox/mapbox-unity-sdk#432]
Hi guys,
The Locationprovider demo does not show a map on my iOS devices. It only shows a map on the editor.

**Comment by david-rhodes** [comment]
This likely means that you do not have location permissions for your application. Please check your Xcode logs and ensure your application has access to location services in settings.

My guess is that you have not specified a "reason for location access" in the Unity iOS build settings. Without this, iOS will not allow location as there is no prompt for the user to enable at first launch/access.

**Comment by david-rhodes** [comment]
No problem!
