### ISSUE TITLE
VectorExtensions Reference Point doesnt change anything ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#434]
Hello there !

I just noticed that the ref_point parameter from the most VectorExtensions methods doesnt change the returned result.

`Vector3 pos = VectorExtensions.AsUnityPosition(new Vector2(-70, -70), new Vector2d(-70,-70));`

Does return  (-7792250.0, 0.0, -11068160.0)
The same happens with a ref point of new Vector2d(0,0)... so for what exactly is a ref point ?

**Comment by brnkhy** [comment]
Hey @genaray,
Reference point is not in lat/lng but in mercator meters. So when you call same function with (-70, -70) and (0,0), you'll get (70,70) difference between two results.
We're using reference point to keep everything in floating point range, so if reference point is in the middle of SF for example, everything in SF will be quite close to origin etc.

**Comment by genaray** [comment]
@brnkhy Ahh alright, i understand now... that explains the extremly high map.CenterMercator value... So if i want to set a new reference point it also needs to be in mercator meters, right ? 
If i want to have my new reference point at lat/lng 70;70 what exactly do i need to do ? Is there a way to convert lat/lng ? :)

Thanks for your fast answer and help ! ^^

**Comment by brnkhy** [comment]
@genaray yes it has to be in mercator meters and you can find functions to convert lat/lng to mercator meters in conversion.cs. 
Your usecase sounds interesting though, do you have to do this manually? we're already managing all that when you request tiles.

**Comment by genaray** [comment]
@brnkhy Im currently trying to implement an chunk system on my own ^^. And my chunks should be a bit bigger than the actual tiles. So i thought i could calculate the chunks using the lat/lng of my player and convert this into a unity position to calculate my chunks... Because of the mercator projection those unity positions are stretched. I thought when i use an other reference point i could solve this iusse :).
