### ISSUE TITLE
Directions don't show the shortest way

### ISSUE THREAD

**Issue by mecadiego113** [mapbox/mapbox-unity-sdk#435]
Today I started using the `DirectionsFactory`, but it seems it doesn't create the shortest (most optimized) way to get the end point. 

Is it bugged or I'm missing something?

**Comment by mecadiego113** [comment]
Just noticed that Unity uses `Directions` by vehicle, instead of walking routes. So, I'm gonna update my question: is it possible to request `walking` waypoints?

**Comment by david-rhodes** [comment]
You can change the `RoutingProfile` inside the `DirectionsResource` to `Walking`.

**Comment by mecadiego113** [comment]
Done. Thank you @david-rhodes!
