### ISSUE TITLE
Dynamic zoom with terrain

### ISSUE THREAD

**Issue by raggnic** [mapbox/mapbox-unity-sdk#436]
Hi

I'm trying to have a scene with a terrain mesh that takes into account terrain height, imagery and zoom level.
With the DynamicZoom sample i only get flat terrain,even when i change FlatTerrainFactory to TerrainFactory. 
Moreover, with TerrainFactory instead of FlatTerrainFactory i have tiles with a wrong size when zoom increases (see picture).

I've tried the Slippy terrain sample but it doesn't support dynamic zoom.
 
I think that I'm doing something the wrong way... Could you tell me what?
Thank you 
Nicolas

![dynamiczoom](https://user-images.githubusercontent.com/28299760/33565202-c0dc4d2c-d91c-11e7-9dea-c81a4e09f36a.png)

**Comment by david-rhodes** [comment]
We have a new release coming soon that will have a new `ZoomableMap` implementation. You likely won't see this issue with the new version.

**Comment by raggnic** [comment]
thank you for the information. I'll wait for the next release then

**Comment by david-rhodes** [comment]
Fixed in 1.3 (currently available in `develop`, too).
