### ISSUE TITLE
Question: Converting real world coordinates to game position

### ISSUE THREAD

**Issue by Cyrelc** [mapbox/mapbox-unity-sdk#441]
I have reviewed numerous documents and other posts, but I am unable to locate the error with my real-world positioning. Any assistance would be appreciated.

I have created a basic map, centered on 53.5344, -113.5065, with a range tile provider set to 9 in every direction. 

![2017-12-05_111213](https://user-images.githubusercontent.com/15618831/33623124-3049454e-d9ad-11e7-9d8f-d97f5ae36947.png)

I am attempting to place real world geo-coordinates (ex. 53.523219,-113.526319 or 53.522515,-113.624191) onto this map, using Conversions.GeoToWorldPosition to no avail.

![2017-12-05_111038](https://user-images.githubusercontent.com/15618831/33623147-4534fb42-d9ad-11e7-92c6-64820f59c126.png)

where MapCenter is 53.5344, -113.5065, and 0.04088333f is the WorldRelativeScale as reported by the simple map script on creation.

![2017-12-05_111420](https://user-images.githubusercontent.com/15618831/33623202-73835ad4-d9ad-11e7-8982-648863503767.png)

Thanks in advance for any assistance, please let me know if you require further information about my build. And yes, I have read https://github.com/mapbox/mapbox-unity-sdk/issues/123 backwards and forwards before posting here :-P

**Comment by genaray** [comment]
Did you already tried VectorExtensions.AsUnityPosition(); ?

**Comment by Cyrelc** [comment]
I believe it may be related to the fact that the center latitude longitude input by me ( 53.5344, -113.5065) is NOT necessarily the center of the map, since the center of the map is the center of the tile containing ( 53.5344, -113.5065) and my coordinates are only slightly off. @Genaray I am looking into your suggestion now, just wanted to add that information

**Comment by genaray** [comment]
Oh and i see you just did the same mistake as i did some time ago.

Conversions.GeoToWorldPosition(Vector2d latLong, Vector2d refPoint, float scale = 1);

Vector2D latlong = the lat/lng position you want to convert.
Vector2D refPoint = Not a lat/lng position, its a value of the meters your reference point is away from the mercator projection center.
float scale = Your map scale, you could use map.worldRelativeScale for example.

**Comment by genaray** [comment]
Reference point is not in lat/lng but in mercator meters. So when you call same function with (-70, -70) and (0,0), you'll get (70,70) difference between two results.
We're using reference point to keep everything in floating point range, so if reference point is in the middle of SF for example, everything in SF will be quite close to origin etc.

**Comment by atripathi-mb** [comment]
@Cyrelc ,

I would suggest changing your method call to
`Conversions.GeoToWorldPosition(convert , _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz()`

where `_map` is the instance of the map you are using. GeoToWorld uses the map's center in meters & the relative scale of the map to convert latitude longitude into map coordinate space. 

Note that `GeoToWorld` assumes the map root is at origin.  
The next release will add methods to take into account the map's transform.

**Comment by Cyrelc** [comment]
@atripathi-mb The problem is when I use _map.CenterMercator as a parameter, I receive HUGE numbers for my positions:
![capture](https://user-images.githubusercontent.com/15618831/33627307-5aaba48c-d9ba-11e7-867a-19ed6a5e138c.PNG)
![capture1](https://user-images.githubusercontent.com/15618831/33627310-5c6f6c72-d9ba-11e7-8cf7-406506b9025c.PNG)

**Comment by Cyrelc** [comment]
@Update - just an example of the slide I'm trying to fix:

![capture](https://user-images.githubusercontent.com/15618831/33627783-c64b7112-d9bb-11e7-81a8-caa923703051.PNG)

Using Conversions.GeoToWorldPosition(convert - mapCenter, Vector2d.zero, worldRelativeScale).ToVector3xz(); gets me this close

**Comment by atripathi-mb** [comment]
@Cyrelc 
Is your `convert` parameter in latitude longitude ? so something like 
```
Vector2d latLong = new Vector2d(53.523219, -113.526319);
Debug.Log(Conversions.GeoToWorldPosition(latLong, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz());
```

This gives me `(-191.8, 0.0, -211.7)` for a map centered at `53.5344, -113.5065`

**Comment by Cyrelc** [comment]
53.523219,-113.526319 gives me -90.2,0.-50.9

I assume @atripathi-mb  you were at a very different scale than I was?

Here is a list of my coordinates and their calculated component position in game world

![capture](https://user-images.githubusercontent.com/15618831/33644442-ec63d3a8-da01-11e7-836c-9207f8113cc6.PNG)

**Comment by atripathi-mb** [comment]
@Cyrelc Your `Unity Tile Size` might be different than what I am using (mine was 100). Does this solve the issue for you?

**Comment by Cyrelc** [comment]
@atripathi-mb thanks for all the help! My unity tile size is 100 though, as you can see in my original post :-(

**Comment by atripathi-mb** [comment]
@Cyrelc I tried using Zoom 14 & UnityTileSize = 100 and I get the following 
<img width="343" alt="screen shot 2017-12-06 at 1 07 51 pm" src="https://user-images.githubusercontent.com/32286016/33685499-a7ab9c7a-da86-11e7-9872-f6abe67427db.png">
Here is the code snippet I have been using to test your issue.  
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mapbox.Unity.Map;
using Mapbox.Unity.Utilities;
using Mapbox.Utils;

public class TestConversions : MonoBehaviour
{

	[SerializeField]
	AbstractMap _map;

	// Update is called once per frame
	void Update()
	{
		if (Input.GetMouseButtonUp(0))
		{
			Vector2d latLong = new Vector2d(53.523219, -113.526319);

			Debug.Log("Map Center : " + _map.CenterMercator.ToString());
			Debug.Log("Map World Relative Scale : " + _map.WorldRelativeScale.ToString());
			Debug.Log("World Position : " + Conversions.GeoToWorldPosition(latLong, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz());
			GameObject go = GameObject.CreatePrimitive(PrimitiveType.Sphere);

			go.transform.localPosition = Conversions.GeoToWorldPosition(latLong, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz();
		}
	}
}

```
Could you send me a code snippet of what you are doing for me to better understand your issue.

**Comment by edwardpotter** [comment]
May not solve your specific problem, but... here's my code for taking a lat/lon and instantiating a game object off a basic map (such as the one from the location provider example):

`AbstractMap _map;
Vector2d mapRef = _map.CenterMercator;
float worldRelScale = _map.WorldRelativeScale;
double objectLat;
double objectLon;
string objectPrefab;
var rotation = Quaternion.identity;

Vector3 mobWorldPosition = Conversions.GeoToWorldPosition(objectLat, objectLon, mapRef, worldRelScale).ToVector3xz();

int zrotation = UnityEngine.Random.Range(0, 360);
rotation.eulerAngles = new Vector3(-90, 0, zrotation);

GameObject newObject = (GameObject)Instantiate(Resources.Load(objectPrefab), mobWorldPosition, rotation);`

My experience so far is the game object is nailed spot-on location wise to the map, at least down to my default zoom level of 15 which looks closer than your above examples.

**Comment by Cyrelc** [comment]
@atripathi-mb I tried linking to the abstractMap as you did, and it made every result (0,0,0). I believe my map object is destroyed after being created, even when stored in a serialized field. I will PM a link to my project.

**Comment by atripathi-mb** [comment]
@Cyrelc I tried using the script I shared above to test the conversions ( attached the script to the map component) and I get the same results as the screenshot above. I don't see why the conversions are not working for you. 

Could you make sure the input lat/long is correct and the conversions are being used correctly?

Also, could you create an isolated test case for us to investigate any conversion bugs that you might be seeing. Navigating through your project without any context is difficult.

**Comment by atripathi-mb** [comment]
<img width="801" alt="screen shot 2017-12-11 at 2 52 30 pm" src="https://user-images.githubusercontent.com/32286016/33855741-2230df28-de83-11e7-84a2-d3870a07a37c.png">

@Cyrelc Is this your expected result?

One thing I noticed was you had temporal coupling in your Main class. It was dependent on the map but wasn't waiting for the map to be initialized. 

I made the following changes to `Main.cs` to get the results above.

```
	void _map_OnInitialized()
	{
		createOverlayMenu = GameObject.Find("CreateOverlayMenu");
		DisableCreateOverlayWindow();

		centerMercator = new Vector2d(7082349.29279, -12634735.02743);
		worldRelativeScale = 0.04088333f;

		//Get the terrain object, and calculate the required dimensions and position. Then apply them
		Terrain terrain = GameObject.Find("Terrain").GetComponent<Terrain>();
		float tileSize = terrain.GetComponentInChildren<BasicMap>().UnityTileSize;
		float mapSize = tileSize * 2 * mapRange + tileSize;
		terrain.terrainData.size = new Vector3(mapSize, 1, mapSize);
		GameObject.Find("Map").transform.position = new Vector3(mapSize / 2, 0.1f, mapSize / 2);
		GameObject.Find("Terrain").GetComponent<Terrain>().transform.position = new Vector3(-mapSize / 2, 0, -mapSize / 2);
		//Find the appropriate position to center the map on the terrain object. Set the terrain empty game object AND the camera to this position.
		Camera.main.transform.position = new Vector3(0, 100f, 0);
		//Set Camera bounds based on map size
		CameraController cameraController = Camera.main.GetComponent<CameraController>();
		cameraController.northSouthBoundary = cameraController.eastWestBoundary = mapSize / 2;

		//foreach mapOverLay found
		LoadOverlaysFromXml(Application.dataPath + "/Resources/overlays.xml");
		//foreach Delivery found
		LoadDeliveriesFromXml(Application.dataPath + "/Resources/deliveries.xml");
		if (overlayList.Count > 0)
		{
			currentOverlay = 0;
			SwitchOverlay();
		}
	}


	private void Awake()
	{
		_map.OnInitialized += _map_OnInitialized;
	}

	/* The start function sets up the map, the world, and calls the loading of the predefined xml files. It also calculates and assigns the appropriate size for the terrain object,
     * and centers the map, and sets the initial camera position */

	void Start()
	{

	}
```

Hope this resolves your issue.

**Comment by edwardpotter** [comment]
Excellent point! I forgot I to mention that as well.

My scripts check to ensure that not only the map is initialized, but that centermercator and worldrelscale are realistic numbers as well (just in case), since when I instantiate a random game object I end up persisting it to a DB on the backend as a geopoint.
