### ISSUE TITLE
Need some help while trying to understand the TileCover formulas.

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#442]
Im currently trying to understand the way mapbox calculates the tiles by taking a look at the TileCover methods and formulas. 
So i took a look at the following website : http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

There two pseudo methods, lat/lon to tile numbers and the other way around.

Until now i think the actual tile sizes are depending from the zoom modificator (im not totally sure about this).
But is there a way to modify the actual tile sizes in the formulas to calculate bigger tiles ? 
Or do i just need to change the zoom variables ?

**Comment by david-rhodes** [comment]
When you say "bigger tiles" are you referring to the size of the quad of each tile in Unity? If so, can't you change the `UnityTileSize`? You can also ignore UnityTileSize and send your own `WorldRelativeScale` value down, which will affect the scale of all objects in the hierarchy.
