### ISSUE TITLE
VectorLayerVisualizer Key parameter is case sensitive

### ISSUE THREAD

**Issue by jordy-isaac** [mapbox/mapbox-unity-sdk#445]
VectorLayerVisualizer Key parameter is case sensitive. It should allow for upper and lower case parameters.

Users are unable to complete [part 2](https://www.mapbox.com/help/unity-mesh-pt-2/) of tutorial due to case sensitive requirements.

**Comment by BergWerkGIS** [comment]
@jordy-isaac not sure I understand why users are unable to complete the tutorial, could you detail?

-----

 The key parameter has to be case sensitive (differentiate between upper/lower case) as it refers to the layers in a  vector tile (VT).
The names of layers in VTs are also sensitive.
eg a VT could have a layer `building` and a layer `Building`, both not being the same and containing different data.
Of course that is not recommended but it could happen when users use their custom data.
