### ISSUE TITLE
Mapbox SDK problem with android merger

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#446]
Hello.
I imported a project from Unity 5.6 to 2017.1 so I could use the Mapbox SDK. But upon building I stumble upon an error saying main android manifest says the minSDK uses 14 while the other one (from mapbox) uses 15. How should I resolve this? Does any of this anything to do with the re-importing I did? thank you.

**Comment by david-rhodes** [comment]
Are you using other android libraries in your project? I suspect you need to modify your target OS version. This may help: https://answers.unity.com/questions/1283008/android-unable-to-merge-android-manifest-error.html.

**Comment by AkaneMikazuki** [comment]
That helped me resolve the issue. Thank you.
