### ISSUE TITLE
How to get elevation data ? 

### ISSUE THREAD

**Issue by santoshkumar918** [mapbox/mapbox-unity-sdk#447]
I want to draw path on terrain but i am getting x and z properly but 
Conversions.GeoToWorldPosition (point.x, point.y, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz () will give y coordinate as zero.

How can i get Y coordinate to draw the path accurately.

**Comment by atripathi-mb** [comment]
@santoshkumar918 You could refer to this ticket for a solution #222 . Let me know if you need more information.
