### ISSUE TITLE
Ensuring map tiles load

### ISSUE THREAD

**Issue by edwardpotter** [mapbox/mapbox-unity-sdk#451]
Hey there - using map box in a game (https://itunes.apple.com/us/app/adventure/id1313495866?mt=8), and the map is pretty key to the main experience.  While it doesn't happen very often, I have observed a couple times on player devices where a map tile is not loaded.  The map being used is basically the Location Provider example, with the range around transform tile provider being assigned to the player model object.

I didn't see this behavior happen at all in test, so darn near impossible to get logs of it happening, etc.

Any idea of where to start on diagnosing and remediating?  Or has anyone else encountered this?

Oh, and I'm using v1.2.0 of the sdk and unity 2017.1.2p3

Thx!

**Comment by david-rhodes** [comment]
1. Make sure you specify a reasonable request timeout in the mapbox configuration settings. You will want to account for devices will slow speed or no access.
2. We are adding exceptions with 1.3 (coming soon) which will allow you to identify failed tiles and enable you to write code that will issue a new request as needed.

**Comment by edwardpotter** [comment]
Gotcha.  Timeout right now is 10sec (I think that was the default) - would you suggest more, perhaps 30sec or even 60sec?

**Comment by david-rhodes** [comment]
I recommend at least 30 seconds. We've changed this to be the default for v1.3.

**Comment by david-rhodes** [comment]
Tile exceptions are now sent via events, as well. You can can listen to these events and handle them as you need (re-request, display error, etc.)
