### ISSUE TITLE
Accessing point data outside of modifiers

### ISSUE THREAD

**Issue by DarrenBangsund** [mapbox/mapbox-unity-sdk#453]
Hey I'm looking to create a prefab that requires some custom configuration at run time based off of the congestion data, and was trying to figure out the most mapbox-idiomatic-solution to doing this. My initial thought was to start developing my own custom mesh/go modifiers, but considering if there was a way to do this without integrating one-off modifiers, I'd rather do that personally! 

So I guess my question is there a way to access point data from the API outside of integrating custom modifiers? 

Also forgive me, my Unity knowledge is very limited. I only just started using Unity with the mapbox-sdk.

**Comment by david-rhodes** [comment]
We have a modifier called `FeatureBehaviour` which can optionally be added to each feature through the map factory framework. This would allow you to query this feature data at runtime. Is that what you're looking for?

**Comment by DarrenBangsund** [comment]
Yes this is exactly what I needed, thank you @david-rhodes! - I have one more question now that this is working: it looks like the line data is all there and in position, but it's in reference to the camera frustrum. Is there a reference to the formula for translating the points to tile positions?

**Comment by brnkhy** [comment]
@DarrenBangsund all feature vertex positions are relative to their parent tile center unless you change it from the modifier stack (`Feature Position` setting).

**Comment by DarrenBangsund** [comment]
Thanks for the reply @brnkhy - I've recorded a gif of the behavior that I'm encountering [here.](https://gyazo.com/9e725ecf8250c6f7d70220553359284d)

I'm drawing gizmos spheres at the feature points I'm receiving from the FeatureBehaviour script, they all tend to draw directly underneath camera viewport. I can modify the position by adding the parent tile transform Vector to the position of the feature point I receive, but as soon as I scale the map, all of the points become displaced.

Here's the code that I'm using to draw the points.

```cs
private void OnDrawGizmos()
    {
        var points = this.gameObject.GetComponent<FeatureBehaviour>().VectorEntity.Feature.Points;

        Gizmos.color = Color.red;

        foreach (var roadSeg in points)
        {
            Vector3 p1 = roadSeg[0];
            Vector3 p2 = roadSeg[roadSeg.Count - 1];

            Gizmos.DrawSphere(p1, 10);
            Gizmos.DrawSphere(p2, 10);
        }
    }```

**Comment by brnkhy** [comment]
@DarrenBangsund ah it's not the camera position, but world origin they are using in that gif. As I said feature points are relative to tile center so if try placing those points to `(p1 + this.transform.parent.transform.position)` , they should be in right place. Or you can set your new gameobject as children to that tile, which would automatically take care of that calculation.

**Comment by DarrenBangsund** [comment]
Yeah this is what I was doing before, [another gif](https://gyazo.com/5499dc6e1adb9e65cd2da31cd73f7670), when the tiles scale the points aren't scaling with the tile. But you can see when it snaps to the next zoom point the points are fairly accurate. As soon as I were to zoom that though, the points would remain static.

**Comment by david-rhodes** [comment]
If you want to scale those points with the map, I suggest you make them a child of the map tile that they belong to. Otherwise, you can use the new conversion methods we have added to `AbstractMap` to take entire map root transform matrix into account when converting.

**Comment by david-rhodes** [comment]
No worries--glad we could help!

**Comment by jellena** [comment]
@DarrenBangsund Sounds like our Developer Program would be something you'd be interested in. Checkout mapbox.com/unitydev and sign up if you're keen.

**Comment by DarrenBangsund** [comment]
@jellena Thanks! Application sent 👍
