### ISSUE TITLE
Placing 3D Objects on Map

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#458]
Hello.
I don't know if this issue has already been resolved here, but I should ask: How can I put 3D Objects on my map? Thank you.

**Comment by AkaneMikazuki** [comment]
I've found the POI example but I can't figure out how to place POIs in specific lat and lon. Is this possible?

**Comment by brnkhy** [comment]
@AkaneMikazuki you can convert lat/lng to unity world position using `AsUnityPosition` extension method.  We'll also have better examples showing exactly this and some additional (and easier) helper function in the next release (coming very soon).

**Comment by AkaneMikazuki** [comment]
Thanks. I have tried a gist you have posted in Github, sir. https://gist.github.com/brnkhy/dcff0ba425303a69b995296a90dea4fe
Making the spheres a set of models in a list

`       //var gg = Models[i];
                //gg.transform.position = new Vector3((float)pos.x, 12, (float)pos.y);
                //gg.transform.localScale = new Vector3(30F, 30F, 30F);`
I know it's not a good way to do this.

But upon building the project the models stop abiding by the code.

Could there be anything I could do about it or I just have to use a different way (not following your AddPOI.CS)

**Comment by AkaneMikazuki** [comment]
Also, I have read about AsUnityPosition on Mapbox's docs but they don't explain each method thoroughly. Like, for what is the reference point and the scale in their params? Thank you.

**Comment by brnkhy** [comment]
@AkaneMikazuki you mean it works in editor but not when you build to a device? What kind of a build is it, mobile or desktop or any others?
