### ISSUE TITLE
Facing issue while using rotate with location provider.

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#459]
I'm using rotate with location provider script on my character. When I'm heading towards north it looks good. But when I start moving towards east or west the character is always looking towards north. I'm just wandering what is the issue. 
If there is any help from Mapbox community it'll be much appreciated. Thanks

**Comment by atripathi-mb** [comment]
@asadali26 Sounds like a transform issue to me. Could you give me some more details ?
Are you applying some transform to the map?
Are you using this in an AR scenario?

**Comment by david-rhodes** [comment]
Did you confirm that this works in the editor by using one of the "mock" location providers? If it works in the editor, then this suggests an issue with your device magnetometer/compass. Do you have location services initialized correctly on your device?

**Comment by asadali26** [comment]
@david-rhodes in unity editor we can adjust heading value according to our desire.  So it works good. But when use in device it cause problem. Let suppose I'm heading towards north my character also move towards north but when I heading towards east/west it still moving in the same direction as the previous one

**Comment by asadali26** [comment]
@atripathi-mb No I haven't apply any transform to the map. 
Still I'm not using in VR scenario just for simple single player platform

**Comment by atripathi-mb** [comment]
@asadali26 Could you make sure the device has correct permissions and is reporting the compass values accurately. Logging the compass state and heading value might give help in debugging this issue.

**Comment by asadali26** [comment]
@atripathi-mb yes I'm debugging heading value in my device. 
I have checked Snap Map height to zero.

**Comment by asadali26** [comment]
I'm wandering is snap map height to zero causing an issue

**Comment by david-rhodes** [comment]
@asadali26 I don't see how snap map height and no compass data could be related. If your mock heading works in editor (to rotate your player avatar correctly), then I can almost certainly guarantee that your compass is not being enabled correctly on device.

**Comment by asadali26** [comment]
@david-rhodes  mock heading works on editor perfectly. If you help me or guide me how to enable compass heading on device correctly or how I can detect that my device compass actually not work correctly . Thanks

**Comment by atripathi-mb** [comment]
@asadali26 Our sdk should log errors if location services are not enabled on device. If your compass gives you zero values always or gives garbage values, that is an indication of compass not working properly. I would suggest referring to https://docs.unity3d.com/Manual/android-manifest.html to ensure your device permissions are set properly.

**Comment by MiroMuse** [comment]
Let us know if you need more help - closing this issue for now 👍
