### ISSUE TITLE
Horrible Camera stuttering via your script ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#461]
Good evening !

Just noticed that when i use the mapbox "Camera Movement" script the camera stutters/lags at some point. Mostly after just holding down without moving and/or when you are far away from the camera start position.

Any idea why that happens ? Or any solution ?

    public class CameraMovement : MonoBehaviour
	        {
		[SerializeField]
		float _panSpeed = 20f;

		[SerializeField]
		float _zoomSpeed = 50f;

		[SerializeField]
		Camera _referenceCamera;

		Quaternion _originalRotation;
		Vector3 _origin;
		Vector3 _delta;
		bool _shouldDrag;

		void Awake()
		{
			_originalRotation = Quaternion.Euler(0, transform.eulerAngles.y, 0);

			if (_referenceCamera == null)
			{
				_referenceCamera = GetComponent<Camera>();
				if (_referenceCamera == null)
				{
					throw new System.Exception("You must have a reference camera assigned!");
				}
			}
		}

		void LateUpdate()
		{
			var x = 0f;
			var y = 0f;
			var z = 0f;

            if (Input.GetMouseButton(0))
			{
				var mousePosition = Input.mousePosition;
				mousePosition.z = _referenceCamera.transform.localPosition.y;
				_delta = _referenceCamera.ScreenToWorldPoint(mousePosition) - _referenceCamera.transform.localPosition;
				_delta.y = 0f;
				if (_shouldDrag == false)
				{
					_shouldDrag = true;
					_origin = _referenceCamera.ScreenToWorldPoint(mousePosition);
				}
			}
			else
			{
				_shouldDrag = false;
			}

			if (_shouldDrag == true)
			{
				var offset = _origin - _delta;
				offset.y = transform.localPosition.y;
				transform.localPosition = offset;
			}
		}
	}

**Comment by david-rhodes** [comment]
A few things:
1. Are you using vector tile maps with lots of game objects or meshes (buildings, roads, etc.)? If so, keep in mind that these are generated with every tile request and are being done on the main thread. This will cause frame rate drops if you do not use coroutines in your Vector Layer Visualizer objects.
2. If you move your camera too far away from the origin of the scene (and map), you will experience floating point imprecision. This will lead to a stutter effect as the camera position begins clipping values. This camera script is an example and not meant for production. In a real scenario, you would want to reinitialize your map if you know you will be going quite some distance away. Or, use a quad tree map, instead. This actually uses tile scaling to mimic zoom. Tiles are offset rather than the camera itself. Note that this may not work for your use-case, however.

**Comment by genaray** [comment]
@david-rhodes 

1. Nope
2. I bet that isnt a map problem, because it also happens without mapbox 2D. So it needs to be a Script problem i guess...

**Comment by david-rhodes** [comment]
> Without mapbox 2D?

What does this mean? Anyway, for production you really should be using your own camera controller scripts. This is in the examples namespace for a reason. 😉 

A video of the problem may be helpful, too.

**Comment by atripathi-mb** [comment]
@genaray As @david-rhodes said 
>If you move your camera too far away from the origin of the scene (and map), you will experience floating point imprecision.

Unity transforms are stored as floats, so if you move too far you will start seeing precision errors.

**Comment by genaray** [comment]
@david-rhodes  @atripathi-mb 

Im going to do a Video later :-). Width mapbox 2D, i mean the Basic mapbox visual map.
Also i want to mention that my camera starts stuttering at 1000 Pixels away from origin. So normally i shouldnt experience Floating Point iusses.

**Comment by david-rhodes** [comment]
What device are you testing on? Is this in the editor?

**Comment by genaray** [comment]
@david-rhodes In editor and also on my phone :-/

**Comment by ahokinson** [comment]
I've had similar results in editor. I spent a long time attempting to optimize the camera movement in my own script only to find out when built, everything was smooth as butter. Try building. This is likely a Unity Editor issue and not a Mapbox issue.

**Comment by genaray** [comment]
@ahokinson The problem is i also encounter this iusse on my device ...

**Comment by david-rhodes** [comment]
Unfortunately, we don't have enough information to understand why you are experiencing this behavior. How many tiles are you requesting? How many are you rendering at once? What is your dispose range? Anything else happening your end to cause frame rate drops? Have you tested in basic examples to compare?

**Comment by ahokinson** [comment]
@genaray What device are you building for?

In case anyone winds up here through a search, I've included the difference between my Editor and Build movement.

Editor: https://gyazo.com/d7f57f9a89b1902aec8acf54ce3c659b
Build: https://gyazo.com/58ad6df2aeb4f8d9617e25be8354ecc0

**Comment by genaray** [comment]
@david-rhodes As i said, i experience the same iusse even without mapbox. The framerate is very high, somewhere at 1200 in the editor or about 400 at  my phone.

@ahokinson For mobile devices. Here you can see what i mean : https://youtu.be/N5sirZjFQPY It looks the same on mobile.

**Comment by david-rhodes** [comment]
I've never seen this behavior before, but it looks like some other system is also trying to update your camera transform. Either that, or there's simply a bug in the example camera controller. That said, I recommend you write your own or use a standard camera controller from the Unity asset store. This example was meant for showing off our example scenes and not much more. :)

**Comment by genaray** [comment]
@david-rhodes I guess i solved it for now... modified the existing code a bit :-)

**Comment by david-rhodes** [comment]
Awesome! Mind sharing what the solution was?
