### ISSUE TITLE
Transparency Shader doesn't make tiles transparent?

### ISSUE THREAD

**Issue by XPav** [mapbox/mapbox-unity-sdk#475]
I'm using the SDK 1.30, and Unity 2017.3.0f3, and trying to get the new transparency shader to do as the update says... "this enables you to convert black to alpha from Mapbox studio styles (to render just road labels, for example)."

But I'm unable to figure out the combination of style colors/shader config to do just that.   I've tried styles with the background set to black, as well as transparent, but the renderer tile in Unity stays black.

**Comment by atripathi-mb** [comment]
@XPav You need to use this shader with material on `Terrain Factory` in your project. Currently this shader will convert black to transparent regardless of what color you chose in the shader ( An improvement on this shader is coming soon - to allow any color to be transparent. )

**Comment by atripathi-mb** [comment]
Shader updated to work with any color. @XPav Please let us know if you have further questions.
