### ISSUE TITLE
Problem with control the map in Vuforia 7

### ISSUE THREAD

**Issue by basaratracy** [mapbox/mapbox-unity-sdk#477]
Hi guys, thanks for the great work on mapbox. I got some problems when I using it in an AR scenario. Hope I can find the answer here. 

I want the function like this. But use the marker instead of ARKit.
[https://www.youtube.com/watch?v=ySSBkZVMxOQ](url)

I put the map on a marker with vuforia7. It works well. Now I want to add the gestures on the map object to change the center location or zoom in. I learned from the dynamicZoom sample that mapbox use moving the camera to zoom in or change the center. But vuforia use ARCamera replace the camera. 

I tried to put use a camera as the child of ARCamera. It doesn't work. So the question is how can I zoom in the map without a camera in AR scenario?

@david-rhodes

**Comment by david-rhodes** [comment]
@basaratracy v1.3 of the SDK contains a new example (ZoomableMap) that actually uses a static camera (tiles resize, rather than camera moving).

**Comment by basaratracy** [comment]
@david-rhodes Thanks dude. That's exactly what I want. Happy new year.

**Comment by emorling** [comment]
@basaratracy can you give some clues to what setup you ended with?
Did you use QuadTreeCameraMovement and set the Reference Camera to Vuforias ARCamera?
