### ISSUE TITLE
How can I get a proper zoom value from a region

### ISSUE THREAD

**Issue by debuggenius** [mapbox/mapbox-unity-sdk#478]
I have some GameObjects placed on a BasicMap, each of them have a coordinate with latitude and longitude. Their locations are not constant, so I need a dynamic zoom level value to show them. 

Now I have a region with left&right longitude and top&bottom latitude, how can I calculate a zoom value to display it, thanks.

**Comment by atripathi-mb** [comment]
@debuggenius 
Could you give me some more information about the problem you're trying to solve?
Usually you decide the zoom level at which you want to display the map or you can use the QuadTreeBasicMap for a runtime zoomable map.  
>Their locations are not constant, so I need a dynamic zoom level value to show them.

What do you mean by this? Do you want your object to display only at certain zoom levels? 

>Now I have a region with left&right longitude and top&bottom latitude

Do you mean you have a rectangle bounding box of the region of interest?

Mapbox tiles use the following convention for zoom levels. You could use the meters per pixel math to determine the zoom level. 
http://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by jordy-isaac** [comment]
Please re-open this ticket if we can be of any further help or email help@mapbox.com
