### ISSUE TITLE
How to insert or update a feature inside a dataset using Unity

### ISSUE THREAD

**Issue by cobaltplay** [mapbox/mapbox-unity-sdk#483]
@Hey guys. I need some help on this point as the Unity documentation for mapbox is quite light and I can't find any examples in the main api documentation.

I'm trying to insert a feature in to an already existing dataset which I have created in my mapbox account. The documentation shows how to achieve this using javascript and cURL here: https://www.mapbox.com/api-documentation/?language=JavaScript#insert-or-update-a-feature

But I would like to know how to do this inside Unity. Could you give some advice on how to construct the http put request in unity or point to an example. The goal of the app is that users can add in messages at a specific point on a map and that data would then appear to any other user using the app.

Thanks for any help guys,
Martin

PS, I've managed to pull down the information from a dataset and display is using the 3dPoi prefab. Next step is to allow data to be added from unity to the dataset:

![screen shot 2018-01-03 at 11 24 45 pm](https://user-images.githubusercontent.com/34491781/34544283-56b80a52-f0dd-11e7-84ff-19e8dc11f346.png)

 By the way, Louis is my dog incase you noticed that test message at the bottom ;)

**Comment by cobaltplay** [comment]
Hey again all. I tried this below:

```
IEnumerator PostNewDatasetFeature()
	{
		string postURL = "https://api.mapbox.com/datasets/v1/[myID]/[myDatasetID]/features/[myFeatureID]?access_token=[myAccessToken]";

		string geoJSONstring = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-2.3626667261123657,53.45663959042344]}}]}";
		//string jsonStringTrial = JsonUtility.ToJson(Resources.Load("knowsleyRoad1"));
		UnityWebRequest www = UnityWebRequest.Put(postURL, geoJSONstring);
		www.SetRequestHeader("Content-Type", "application/json");
		yield return www.SendWebRequest();

		if (www.isNetworkError || www.isHttpError)
		{
			Debug.Log("www error: " + www.error);
		}
		else
		{
			Debug.Log("www = " + www.downloadHandler.text);
		}
	}
```


But I get a 'Generic/unknown HTTP error' response from the return.

Any ideas what the issue could be? Thanks for any advice.

Martin

**Comment by jordy-isaac** [comment]
@cobaltplay Studio maintains a web cache for 10-15 minutes and there is an indicator to show when it's been updated. This might help you with a workaround.

Studio has an indicator to show when it has been updated. I also know that there is web -cache maintained for 15 minutes.

As for your http request, maybe @bergwerkgis can provide a little insight on how to formulate that the proper way for you use case. Thank you!

**Comment by BergWerkGIS** [comment]
This should be one individual GeoJSON? feature and not a GeoJSON FeatureCollection.

**Comment by BergWerkGIS** [comment]
Edited above - accidentally commented too early 🙈

**Comment by cobaltplay** [comment]
@ jordy-isaac, @BergWerkGIS , 
Thanks for the reply guys :)
I tried adjusting the string to just be a Feature, but it still gives me the error message and doesn't update the dataset. Here's the new code:

```
	IEnumerator PostNewDatasetFeature()
	{
		string postURL = "https://api.mapbox.com/datasets/v1/[myID]/[myDatasetID]/features/[myFeatureID]?access_token=[myAccessToken]";

		string geoJSONstring2 = "{\"type\":\"Feature\",\"properties\":{\"name\":\"Null Island\"},\"geometry\":{\"type\":\"Point\",\"coordinates\":[-2.3626667261123657,53.45663959042344]}";

		UnityWebRequest www = UnityWebRequest.Put(postURL, geoJSONstring2);
		www.SetRequestHeader("Content-Type", "application/json");
		yield return www.SendWebRequest();

		if (www.isNetworkError || www.isHttpError)
		{
			Debug.Log("www error: " + www.error);
		}
		else
		{
			Debug.Log("www = " + www.downloadHandler.text);
		}
	}
```

I've also created a new token which includes write permissions to datasets. Is there any other permission it might need to solve the problem? Does the code above look ok to you?

Thanks again for the help guys
Martin

**Comment by BergWerkGIS** [comment]
Looking into it now ...
1st observation: Your code produces HTTP response code 400 which means `Invalid request`.

**Comment by BergWerkGIS** [comment]
> I've also created a new private token which includes write permissions to datasets. Is there any other permission it might need to solve the problem?

No, `DATASETS:WRITE` is enough.

You are missing a curly brace `}` at the end of `geoJSONstring2` - add that and it should work now:

![image](https://user-images.githubusercontent.com/4549888/34614267-230635f8-f231-11e7-908a-6e26b78e1c97.png)

**Comment by cobaltplay** [comment]
@BergWerkGIS - Works great, thanks for the help :) I was able to upload the dataset feature and see the changes through my mapbox editor.

I'm wondering now how can I see those changes within unity without needing to 'export' the dataset to a tileset. Because in the mapbox editor i need to save and then export the changes to see then applied in a childset. Is there a way to access the dataset directly?
At the moment I'm using the PoiGeneration example and using the PoiVectorTileFactory like this:

![screen shot 2018-01-06 at 2 05 05 pm](https://user-images.githubusercontent.com/34491781/34640448-ba12a896-f2ea-11e7-9c04-c3b06e51cdd9.png)

- Could you give some advice on how to either apply the dataset directly to the tileset (export) without me needing to go in to the editor and clicking the 'export' button?
- Or could you give some advice on how to just access the dataset directly in unity and apply a poi object to them in the scene.

Thanks again for the help, super useful :)
Martin

**Comment by cobaltplay** [comment]
Hey again guys. About the question above. I saw the section in the API documentation here (https://www.mapbox.com/api-documentation/?language=cURL#create-an-upload). I've tried to do this in Unity. Instead of uploading to an AWS S3 bucket, I'm just trying to apply a dataset to a tileset. Updating the dataset works well now, but next step is to apply that dataset to a tileset so I can see the changes applied in Unity. Here's what I came up with so far but I get a www error: Generic/unknown HTTP error.

```
	IEnumerator ApplyDatasetToTileset()
	{
		string postURL = "https://api.mapbox.com/uploads/v1/[my mapbox ID]?access_token=[my access token]";

		string datasetTilesetInfo = "{\"tileset\":\"[my mapbox id].[ID of the tileset I want to update]\",\"url\":\"mapbox://datasets/[my mapbox ID]/[ID of the dataset I want to apply to the tileset]\"}";

		UnityWebRequest www = UnityWebRequest.Put(postURL, datasetTilesetInfo); 
		www.SetRequestHeader("Content-Type", "application/json");

		yield return www.SendWebRequest(); 

		if (www.isNetworkError || www.isHttpError)
		{
			Debug.Log("ApplyDatasetToTileset www error: " + www.error);
		}
		else
		{
			Debug.Log("ApplyDatasetToTileset www = " + www.downloadHandler.text);
		}
	}
```
I've tried a few different combinations of tileset name, tileset ID, dataset ID, dataset name because the docs mention name as opposed to ID for the tileset property field. But I still get the same error.

Can anyone see any errors with what I'm doing above, or let me know if this approach is completely wrong.

Thanks all
Best regards
Martin

**Comment by BergWerkGIS** [comment]
Hm, there's something weird going on within Unity and I'm still investigating ...

But, at first make sure
* you use `UnityWebRequest.Post` instead of `Put`
* your access token has `TILESETS:WRITE` and `UPLOADS:WRITE` permissions
  It might take a few minutes till permissions update after you change them

----

If I use the code below from within Unity I still get HTTP response code 400.
But if I `Debug.Log` the variables `postUrl` and `datasetTilesetInfo` and use those strings on the console via `curl` as described in the API docs it works.

```c#
		IEnumerator ApplyDatasetToTileset()
		{
			string postURL = string.Format(
				"https://api.mapbox.com/uploads/v1/{0}?access_token={1}"
				, myId
				, accessToken
			);

			string datasetTilesetInfo = string.Format(
				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}""}}"
				, myId
				, tilesetId
				, datasetId
			);

			UnityWebRequest www = UnityWebRequest.Post(postURL, datasetTilesetInfo);
			www.SetRequestHeader("Content-Type", "application/json");

			yield return www.SendWebRequest();

			if (www.isNetworkError || www.isHttpError)
			{
				Debug.Log("ApplyDatasetToTileset www error: " + www.error);
			}
			else
			{
				Debug.Log("ApplyDatasetToTileset www = " + www.downloadHandler.text);
			}
		}
```

-----

> I've tried a few different combinations of tileset name, tileset ID, dataset ID, dataset name because the docs mention name as opposed to ID for the tileset property field. But I still get the same error.

The tileset name refers to the name you see here: https://www.mapbox.com/studio/tilesets/
If you are exporting to an existing tileset and use a different name in the `name` property of the JSON this will overwrite/update the existing name.

Tileset id and dataset id are the strings you get when you click on `Menu`.


![image](https://user-images.githubusercontent.com/4549888/34667063-a1018830-f467-11e7-88ba-b685c99612ad.png) ![image](https://user-images.githubusercontent.com/4549888/34667024-7e64037a-f467-11e7-8e44-b2159f5a7b8d.png)

**Comment by BergWerkGIS** [comment]
Oh boy, there really seems to be a Unity bug, but I was able to crack that nut and hack it:

Solution:
* use `UnityWebRequest.Put`
* pass JSON as byte array
* but override it to `POST` via `www.method = "POST"` later on

This code works for me:

```c#
		IEnumerator ApplyDatasetToTileset()
		{
			string postURL = string.Format(
				"https://api.mapbox.com/uploads/v1/{0}?access_token={1}"
				, myId
				, accessToken
			);

			string datasetTilesetInfo = string.Format(
				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}""}}"
				, myId
				, tilesetId
				, datasetId
			);

			byte[] bytes = System.Text.Encoding.UTF8.GetBytes(datasetTilesetInfo);
			// initialize as PUT
			UnityWebRequest www = UnityWebRequest.Put(postURL, bytes);
			www.SetRequestHeader("content-type", "application/json");
			// HACK!!! override method and convert to POST
			www.method = "POST";

			yield return www.SendWebRequest();

			if (www.isNetworkError || www.isHttpError)
			{
				Debug.Log("ApplyDatasetToTileset www error: " + www.error);
			}
			else
			{
				Debug.Log("ApplyDatasetToTileset www = " + www.downloadHandler.text);
			}
		}
```

**Comment by cobaltplay** [comment]
@BergWerkGIS - Thanks again for the quick feedback. It's working on my side, great :) I would never have figured out that hack. The only edit I made was to not include my user name in the tilesetId field because we already include that in the myId field. So I just needed to copy the part which came after my user name and the '.' in my mapbox account.

I've now been able to update the tileset from Unity and see the changes applied. Next step is to allow users to place markers around the map as they walk along with a message field. I don't think this should be too hard as the main functionality is already in place. I'll let you know how it goes or if I come across any other issues. Thanks for all the help so far man, you've been awesome :)

Martin

**Comment by BergWerkGIS** [comment]
Great that is works for you too. Happy we solved this. 😄 

> Next step is to allow users to place markers around the map as they walk along with a message field.

Just remember that those markers will not appear instantaneously:
Updating the dataset might take a few minutes as well as exporting dataset to tileset.

----

Another caveat to be aware of: our SDK features ambient caching of tiles per default.
Tiles are only re-requested when the maximum cache size has been reached thus you might not see your updates at all.
We are working on improving that and are aiming for a auto-refreshing cache for (hopefully) the next release.

Till then I can think of two different ways to approach your scenario:

1.
Go to `Mapbox -> Setup -> Configuration` in Unity Editor and set both 
* `Mem Cache Size`
* and `MBTiles Cache Size`

 to `0`:
![image](https://user-images.githubusercontent.com/4549888/34717048-05862e80-f532-11e7-95d4-b95ccceed588.png)

Although that comes with the disadvantage that no tiles are cached at all, which might slow things down - especially for mobile users with bad connections.

2.

Expose a `Refresh` button in your app that clears caches on demand.
See here: https://github.com/mapbox/mapbox-unity-sdk/issues/212#issuecomment-323806314

-----

If you have questions about that please open dedicated issues.

**Comment by cobaltplay** [comment]
@BergWerkGIS - thanks for the advice. Yeah this was something I also considered as it takes a few minutes for the tileset to update. 

I tried the '**Mapbox.Unity.MapboxAccess.Instance.ClearCache();**' call from script but it never shows the '**deleting /Users/[name]/Library/Application Support/DefaultCompany/MapboxTest/cache/**'  debug like when I clear caches from the menu in Unity. So at the moment I'm stopping Unity and then clearing through the menu, then Playing again to see the changes. Is this a normal issue or do I just need to wait longer for the tileset to be updated?

For a 'refresh' / 'clear caches' button I'm thinking of doing it automatically every 1 minute so that eventually any new data in a tileset would be applied to the map in Unity.

Looking forward to the new release :)

**Comment by BergWerkGIS** [comment]
Interesting that you don't see the `deleting ...` message because the menu item also calls `Mapbox.Unity.MapboxAccess.Instance.ClearCache()` - so it should be the same.

> So at the moment I'm stopping Unity and then clearing through the menu, then Playing again to see the changes.

You don't have to stop Play Mode, you can clear caches "on the fly".
Then you'd just have to pan away from your current location and back again: for the tiles to be discarded and re-requested.

**Comment by cobaltplay** [comment]
@BergWerkGIS - I see. I'll give that a try. Will let you know how it goes.

Martin

**Comment by cobaltplay** [comment]
@BergWerkGIS and all. So far so good. I changed both the cache settings to zero and I'm also calling 'Mapbox.Unity.MapboxAccess.Instance.ClearCache()' on start just to be sure. Its working well. I walk the transform away from the tile until it unloads, then walk back a few minutes later and the new dataset markers appear.

![screen shot 2018-01-10 at 9 39 12 pm](https://user-images.githubusercontent.com/34491781/34796911-12defd46-f64f-11e7-8991-f2302ff20cf5.png)

In order to get a unique feature name each time I've used the 'SystemInfo.deviceUniqueIdentifier' and 'System.DateTime.Now.ToString();'. This way its a unique feature in the dataset each time as opposed to overwriting an old one. I'm not sure if it will continue this way as I'm not yet clear on what the app will do but the foundation is getting there.

Do you know if there's a manual way to get an updated dataset for a tile without needing to unload and reload the tilemap by walking away?

Thanks again, let me know if there's anything I can share guys.
Martin

**Comment by BergWerkGIS** [comment]
For checking if a tileset has been updated you could poll the TileJSON metadata API 
https://www.mapbox.com/api-documentation/#retrieve-tilejson-metadata
and check the `Modified` property (it is null if the tileset hasn't been modified since it's creation).

The TileJSON wrapper is not yet merged into the SDK but you could carry over the new files and the changes (`MapboxAccess.cs` & `UnixTimestampUtils.cs`) to your project from this PR: https://github.com/mapbox/mapbox-unity-sdk/pull/493

```c#
using Mapbox.Platform.TilesetTileJSON;

MapboxAccess.Instance.TileJSON.Get(
    "<YOUR_TILESET_ID>"
    , (TileJSONResponse response) =>
    {
        if(response.Modified.HasValue){
        {
        // check against previous modified date and update if necessary
        }
    }
);
```

For in place updating of loaded tiles in Unity you could add and expose something like [this](https://github.com/mapbox/mapbox-unity-sdk/blob/8ee580e15f7c67fa3f4b6d360427c1298e070d1c/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainFactory.cs#L76-L91) in the factory your are using and call it after checking the tilesets metadata (TileJSON).
Should work - haven't tested though.

**Comment by cobaltplay** [comment]
@BergWerkGIS - thanks for the details, i'll give this a try soon. I've been looking in to the in-place loading more. At the moment I'm checking the DynamicZoom scene too so that users can navigate anywhere on the map to see markers. It looks all the necessary parts are there its just a case of putting them together in a single scene.

By the way, in the new unity sdk (ver 1.3) does it include in-place reloading already?

Thanks again
Martin

**Comment by BergWerkGIS** [comment]
@cobaltplay 
> By the way, in the new unity sdk (ver 1.3) does it include in-place reloading already?

No, SDK 1.3 doesn't have that yet.

Currently working on it in this branch: https://github.com/mapbox/mapbox-unity-sdk/tree/auto-cache-refresh

Highly experimental at the moment and it's probably going to take a few more weeks till we get it merged into `develop`.

**Comment by cobaltplay** [comment]
@BergWerkGIS -ok, thanks for the details. Will keep an eye on the new branch.

**Comment by mujtaba-kiani** [comment]
> Oh boy, there really seems to be a Unity bug, but I was able to crack that nut and hack it:
> 
> Solution:
> 
> * use `UnityWebRequest.Put`
> * pass JSON as byte array
> * but override it to `POST` via `www.method = "POST"` later on
> 
> This code works for me:
> 
> ```cs
> 		IEnumerator ApplyDatasetToTileset()
> 		{
> 			string postURL = string.Format(
> 				"https://api.mapbox.com/uploads/v1/{0}?access_token={1}"
> 				, myId
> 				, accessToken
> 			);
> 
> 			string datasetTilesetInfo = string.Format(
> 				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}""}}"
> 				, myId
> 				, tilesetId
> 				, datasetId
> 			);
> 
> 			byte[] bytes = System.Text.Encoding.UTF8.GetBytes(datasetTilesetInfo);
> 			// initialize as PUT
> 			UnityWebRequest www = UnityWebRequest.Put(postURL, bytes);
> 			www.SetRequestHeader("content-type", "application/json");
> 			// HACK!!! override method and convert to POST
> 			www.method = "POST";
> 
> 			yield return www.SendWebRequest();
> 
> 			if (www.isNetworkError || www.isHttpError)
> 			{
> 				Debug.Log("ApplyDatasetToTileset www error: " + www.error);
> 			}
> 			else
> 			{
> 				Debug.Log("ApplyDatasetToTileset www = " + www.downloadHandler.text);
> 			}
> 		}
> ```

Hello I am following this thread, everything is going fine but my tileset is named as "original.geojson" every time I create new tile set, I just want to update my previous tileset with same name, I am giving the tileset id in arguments.

**Comment by Schaggo** [comment]
> Hello I am following this thread, everything is going fine but my tileset is named as "original.geojson" every time I create new tile set, I just want to update my previous tileset with same name, I am giving the tileset id in arguments.

I am having the same issue.
Any workaround?

**Comment by Schaggo** [comment]
ok got it: 
you have to add a _name_ preference to the link.

`string datasetTilesetInfo = string.Format(
				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}"",""name"":""{3}""}}"
				, myId
				, tilesetId
				, datasetId
				, tilesetName
			);`

**Comment by Lestark728** [comment]
Hey guys, I've been following this thread as well and have a super basic question.
Is everyone creating the basemap and adding the dataset or tileset through the gui, by entering the custom url under terrain? 

2nd question would be where is everyone adding the scripts above?
sorry for the super noob questions. I am beyond frustrated and I figure it can't hurt to ask.
Thanks in advance.

**Comment by Schaggo** [comment]
> Hey guys, I've been following this thread as well and have a super basic question.
> Is everyone creating the basemap and adding the dataset or tileset through the gui, by entering the custom url under terrain?
> 
Yes. 
> 2nd question would be where are is everyone adding the scripts above?

You need to create your own script with linked inputs.
> sorry for the super noob questions. I am beyond frustrated and I figure it can't hurt to ask.

If you can’t figure it out, I can go into more detail.

**Comment by Lestark728** [comment]
@Schaggo I would greatly appreciate that. 
Very frustrating. I am trying to use the script above but I ended up with more questions that answers lol

**Comment by Schaggo** [comment]
> @Schaggo I would greatly appreciate that.
> Very frustrating. I am trying to use the script above but I ended up with more questions that answers lol

lets start with where you are right now. 
I assume you are able to display a map in game.
Can you display markers (POI defined by you)?

**Comment by Lestark728** [comment]
@Schaggo sorry for the late reply. Things were very busy and started looking at a bunch of other solutions to this. However, we came back to this. If you are still available to help i would greatly appreciate it. 

To answer your question Yes I am able to display a map. I have not defined ay poi markers.

**Comment by Schaggo** [comment]
Hey,

No problem. 
Well then let’s start with the following:
Create a dataset, add a point preferably close to your location with a couple of values (name, place description and ID)
Save it and Export to a tileset.
Go to your map style and add a new layer with the tileset as a datasource.

In unity enter style I’d and tileset(might be the actual dataset) for custom data. Instantiate a 3d prefab connected to certain values (like If Name contains [name of your entry]) and see what happens

**Comment by Lestark728** [comment]
Thanks! 
I uploaded the custom GeoJSON (contains features) to a dataset then exported it to a tileset. Imported that into Mapbox studio and added a new layer with the tileset as my data source. 

Where am I putting this data? 
I am assuming  you mean under the IEnuerator?
		```
IEnumerator ApplyDatasetToTileset()
		{
			string postURL = string.Format(
				"https://api.mapbox.com/uploads/v1/{0}?access_token={1}"
				, myId
				, accessToken
			);

			string datasetTilesetInfo = string.Format(
				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}""}}"
				, myId
				, tilesetId
				, datasetId
			);

```

**Comment by Schaggo** [comment]
yep. pretty close already. 

To add a entry into the dataset my IEnumerator  looks like this. 
IEnumerator PostNewDatasetFeature()
	{
		string postURL = string.Format(
            "https://api.mapbox.com/datasets/v1/{0}/{1}/features/{2}?access_token={3}"
            , myId
            , datasetId
            , featureid
            , accessToken
        );


	
		string geoJSONstring = 	
		 "{\"type\":\"Feature\",\"properties\":{\"Aufgabe\":\""
				 +MarkerAufgabe 
			 	 +"\",\"Ort\":\""
				 +MarkerOrt
				 +"\",\"Seite\":\""
				+MarkerSeite
				+"\",\"Tipp\":\""
				+MarkerTipp  
				+"\",\"ID\":\""
				+featureid  
				 +"\"},\"geometry\":{\"type\":\"Point\",\"coordinates\":["
				 +latlon
				 +"]}}"; 
		
			
				
		UnityWebRequest www = UnityWebRequest.Put(postURL, geoJSONstring);
		www.SetRequestHeader("Content-Type", "application/json");
		yield return www.SendWebRequest();

		if (www.isNetworkError || www.isHttpError)
		{
			Debug.Log("www error: " + www.error);
		}
		else
		{
			Debug.Log("www = " + www.downloadHandler.text);
		}
	}
After that you need to update the dataset and apply the data to the tile set: 

IEnumerator ApplyDatasetToTileset()
		{
			string postURL = string.Format(
				"https://api.mapbox.com/uploads/v1/{0}?access_token={1}"
				, myId
				, accessToken
			);

			string datasetTilesetInfo = string.Format(
				@"{{""tileset"":""{0}.{1}"",""url"":""mapbox://datasets/{0}/{2}"",""name"":""{3}""}}"
				, myId
				, tilesetId
				, datasetId
				, tilesetName
			);

			byte[] bytes = System.Text.Encoding.UTF8.GetBytes(datasetTilesetInfo);
			// initialize as PUT
			UnityWebRequest www = UnityWebRequest.Put(postURL, bytes);
			www.SetRequestHeader("content-type", "application/json");
			// HACK!!! override method and convert to POST
			www.method = "POST";

			yield return www.SendWebRequest();

			if (www.isNetworkError || www.isHttpError)
			{
				Debug.Log("ApplyDatasetToTileset www error: " + www.error);
			}
			else
			{
				Debug.Log("ApplyDatasetToTileset www = " + www.downloadHandler.text);
			}
		}

**Comment by Lestark728** [comment]
Thanks for the reply. I'll try it after this meeting. 
I am not sure where to find the feature ID to enter into the script. 
I am confirming that I do have layers in mapbox.

**Comment by Schaggo** [comment]
The feature ID sadly isn’t sent via the api you have to create one from scratch. Random char array might do the trick.
