### ISSUE TITLE
On Texturing and UV Mapping

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#486]
So I've pushed my UV mapping work on a branch today (https://github.com/mapbox/mapbox-unity-sdk/tree/uvMapping) but I think it would be good to discuss it here about its usage, shortcomings, possible issues and improvements.

First of all, this is mainly for the side walls of buildings so I created a height modifier alternative for this. You can use good old HeightModifier for basic uv mapping and textures or this one for more detailed window/floor texturing. 
Goal of this new modifier is to;
- enable using texture atlas
- different styles for different types of buildings in one atlas
- ability to texture walls without too much stretching
- work on all types of buildings, short/tall/narrow/wide etc.

It's named "TextureSideWallModifier" and it fully replaces height modifier, so you can swap it in for height modifier in any existing project/style.

TextureSideWallModifier does bunch of things in one module (that's both good and bad);
- cuts wide walls into smaller ones (cut walls in x axis)
- create floors sections on walls (cut walls in y axis)
- create first and top floors separately
- create wall sections and assign uv maps properly

That's the mesh, now what does texture looks like. Remember the goal here is to use textures atlases, which means we'll have a huge texture sheet and each building/style will only use a small segment of that texture. Think of it like this;
![atlas2](https://user-images.githubusercontent.com/1465390/34591598-cbd325cc-f1cf-11e7-8d1a-ba24eb4bf482.jpg)
That's an extremely simply example and you'll probably have 10+ on a sheet on a real atlas but this should be enough for now. 
You can see there are two rectangles in that texture, red and blue, representing two different building styles. Both have 3 window columns.
Then we want first&top floors right? If you look carefully, you'll see there's a lighter section at top (little taller than one tile) and darker section at the bottom (with doors).
Then we have mid section consists of 6 floors.
By the way both have same properties in this case (3 window columns, same first/top floor height etc) but it really doesn't have to be.

So we have the mesh and that texture, now how it works?
TextureSideWallModifier uses AtlasInfo objects to know about these atlas sections (red/blue sections above). AtlasInfo is a scriptable object and looks like this for now;
![unity_2018-01-05_04-39-53](https://user-images.githubusercontent.com/1465390/34592047-7f9787ae-f1d2-11e7-8f0c-5ef5770fd548.png)
Ugly and cluttered (it doesn't have editor script for now) but it's actually simple.
It contains a list of AtlasEntity, which is a plain old c# class and they correspond to atlas section. Which means AtlasInfo itself corresponds to the texture itself.  So for that atlas above, we'll have one AtlasInfo with two AtlasEntities.

So what are those parameters in AtlasEntity objects; (not in order as that order is pretty bad)

-Texture Rect. As the name suggests, it's just the rect position in the atlas. First one is the left half of the texture, second one is the right side.

-Preffered Edge Section Length; maximum length of a wall section. So if this value is 4 and the wall is 10meter wide, it'll cut down to three segments with 4-4-2 width.

-Column Count. How many window columns does this section has. Using it to cut texture from a good point if wall section is too narrow. i.e. show only one window if wall is too narrow (remember it can't be too wide as we cut it down)

First Floor Height & Top Floor Height; as the name suggest, height of these special floors. One thing to notice though, in the texture we have one floor in bottom and top section while there are six in the middle. So bottom and top sections are fixed to be one floors. Not a big limitation anyway but brings us to;

Floor Height; bad naming in that screenshots, I'll change this asap. This is the height of a mid section. And of course depending on the building height, we can have more than one mid section. In that case we simply repeat it. 
But why does the mid section in textuer have multiple floors? It's only to break the repetetiveness. It would look good to have exact same window 20 times in a row so this helps prevent that.
Mid Floor Count; floor count in texture mid section. similar to column count above, it's necessary when/if you end up with short wall segments and need only a part of that tall mid section. helps cutting it from a good point (not in the middle of a window)

Top section ratio, Bottom section ratio; again bad naming I guess. Top&bottom sections in texture are rects as well right? instead of having a rect there, I just put this float field which represents the section height ratio to all texture height. so top floor texture is 0.125 of that texture etc. Might sound silly but this is how code know which rect to apply on bottom and top floors.

Consider this building for example; (using parameters above)
![unity_2018-01-05_05-07-25](https://user-images.githubusercontent.com/1465390/34592592-572d7860-f1d6-11e7-9207-ef5a14c253f7.png)
That long wall section is cut down vertically to three roughly 8meter wide walls. Then each wall cut down horizontally into three segments; first (3meters), mid (24meters) and top (3meters).
then it selects one texture segment randomly, let's say left (red) texture segment above.
then it applies; 
top 0.125 of that texture segment to top floor.
bottom 0.125 of that texture segment to bottom floor.
and rest of it to mid floors.
And it looks like this;
![unity_2018-01-05_05-11-46](https://user-images.githubusercontent.com/1465390/34592681-f4e39404-f1d6-11e7-98b7-31f3d7537b60.png)
Top and bottom floors looks good but notice mid section has 4 floors. Texture had 6 floors right? This means that mid section was much shorter then the 24meters (defined above again) full height so it applied only 4/6 of that texture segment to that polygon. 
Why even bother? Because if I tried to fit all 6, they would be squished down and looks silly. If I just cut randomly, it might have cut in the middle of window and switch to bottom floor which again would look horrible.

I think those parameters are necessary but they can probably be simplified. UI will definitely improve as well.

So this is how it works, let me know if you have any question. Next thing to do is testing with bigger atlas and corner cases I guess.

**Comment by atripathi-mb** [comment]
@brnkhy Thanks for the detailed write-up. Super helpful and easy to understand. 
quick question before I start digging through the code . 

>Then we have mid section consists of 6 floors.
>Why even bother? Because if I tried to fit all 6, they would be squished down and looks silly. If I just cut randomly, it might have cut in the middle of window and switch to bottom floor which again would look horrible.

Have you tried using just one floor in the texture instead of 6? Saves texture space & gives you repeatability + easier to fit based on number of floors in mid section ( no cutting, only adding required)

>top 0.125 of that texture segment to top floor.
bottom 0.125 of that texture segment to bottom floor.

If you specify the number of top , mid & bottom floors - could you not calculate this ratio directly?

**Comment by brnkhy** [comment]
@atripathi-mb 
`Have you tried using just one floor in the texture instead of 6? Saves texture space & gives you repeatability + easier to fit based on number of floors in mid section ( no cutting, only adding required)`
You can actually do that as well by simply passing 1 as mid floor count (so it still works) but two problems with that;
(1) you'll have exactly same window repeated 20+ times on top of each other for tall buildings and it'll look way too repetitive. When you have 6 floors on texture and repeat them, you'll have a chance to customize each a little and add details to break that repetetiveness.
(2) since we're using atlas, we can't simply repeat texture so you'll need 6x quads (compared to 6 floor texture) to be able to repeat that window.

`If you specify the number of top , mid & bottom floors - could you not calculate this ratio directly?`
You can if all your floors have same height. This kinda allows you to have huge stores at the first floor for example, or maybe billboards or art deco stuff on top floor. Not totally necessary as you noted, but improves customization.

**Comment by brnkhy** [comment]
![t123](https://user-images.githubusercontent.com/1465390/34696865-6fe85768-f4e1-11e7-8684-3e34df0acdf9.png)
here's another image explaining how atlas works.
- you create it any way you want, only restriction is that building facades has to be rectangular. Other than that it doesn't matter where it is and how big it it as you'll be defining those in the atlat info file anyway.
- that atlas above has 4 textures. reddish one on top left is (x = 0, y = 0.5, WIDTH = 0.5, HEIGHT = 0.5). I wrote last two in caps because it's easy to mistake those for max point. It's not. It's size.  (only because Unity rect class default inspector does it this way. can change that when I do inspector if necessary)
- notice values in the "texture rect" are relative to the whole texture.
- Another important part is that, bottom and top ratio parameters, 0.125 in that shot, are relative to its own section, not whole texture. There's 8 floors in that top left section so 1/8th is top floor, 1/8th is bottom.
- other parameters like edge length, floor height, first floor height and top floor height are about mesh itself more than the texture. They are useful for finding the optimal floor height balance to prevent stretching though.

So let's say you want to create a huge atlas, with 8 rows and 8 columns. That means 64 building textures so you'll need 64 entries in the atlas info file. BUT if you're just following the same structure in all of them (3m first floor with same area in texture etc), all you have to change is the first rect parameter. everything else is relative to that section anyway (like 0.125 stuff) so it'll just work.

**Comment by brnkhy** [comment]
![test](https://user-images.githubusercontent.com/1465390/36432457-4d184a58-166b-11e8-8b00-11e27ad69628.jpg)
I suggest adding a column&row with empty wall texture to minimize stretching. We can decorate narrow and/or short wall segments with those instead of windows.

**Comment by roura-12** [comment]
Hey guys I like this documentation first of all it is vary helpful. My question is then is it possible to change the windows materials ?

**Comment by brnkhy** [comment]
@roura-12 I'm afraid not. We don't do detailed mesh generation at the moment so all walls (of a buildings)are one submesh&material. Technically you should be able to use a map/mask to do fancy shader stuff on windows though, if that's what you're looking for. I think `simple` texturing materials/style does something similar for example.
