### ISSUE TITLE
Styling a single building in MAPBOX and unity.... please help

### ISSUE THREAD

**Issue by joelin1415** [mapbox/mapbox-unity-sdk#487]
I followed the tutorial from mapbox https://www.mapbox.com/help/unity-mesh-pt-3/ 
but i need styling a single building in the map ..like image
<a href="https://ibb.co/ncO6cG"><img src="https://preview.ibb.co/k5nXHG/dsa.png" alt="dsa" border="0"></a>

i tried using CityBuildingUsingVisualizer but not works
<a href="https://imgbb.com/"><img src="https://image.ibb.co/nd6gBb/dsa2.png" alt="dsa2" border="0"></a>

please help

**Comment by jordy-isaac** [comment]
@joelin1415 Thanks for the ticket. Happy to help. As of now selecting a particular building is hard to do. In the future we'll have building ID's. 

This will be easier once we have building IDs in the future, but one thing you can do is filter on the first coordinate of the building footprint. You can also check other building properties to see if there is anything unique you can use to filter it. For

i.e. if your building has "address=101 California" it can be possible to find and select the building. Then you'll have to hardcode it to use a different modifier stack on that object by checking if the address contains contains "101 California".

I hope this helps!

**Comment by joelin1415** [comment]
Omg Many Tanks Jordy!!!!
