### ISSUE TITLE
Road signs possible?

### ISSUE THREAD

**Issue by floidtv** [mapbox/mapbox-unity-sdk#489]
Hi everyone, 
i'm working for a few months on a mapbox-unity project to visualize real map data to a driving simulation. Buildings, roads and landuse areas are realized but i want some more details in the scenario.
So, is it possible to get road sign positions and properties from mapbox-sdk directly? 
Or is it possible to add a provider to get the road signs informations from osm? When, how and where do i implement this?

It would be great, if anyone has a solution or some tips how i can do that.
Thanks

* Unity version: 2017.2.0f3
* Mapbox SDK version: 1.2
* The platform you're building to: Windows

**Comment by BergWerkGIS** [comment]
Our data does not include traffic signs.
For what's available see https://www.mapbox.com/vector-tiles/mapbox-streets-v7/ 

A way to achieve what you want might be to obtain traffic signs from another source, create a custom tileset with that data and consume it from within Unity.

eg Mapillary:
https://www.mapillary.com/developer/api-documentation/#traffic-signs

or OpenStreetMap: https://wiki.openstreetmap.org/wiki/Key:traffic_sign
extract data via `Overpass API`: https://wiki.openstreetmap.org/wiki/Overpass_API
or from a OSM dump via `Osmium Tool`: http://osmcode.org/osmium-tool/
