### ISSUE TITLE
[Feature request] Implement delegate for when all HTTPRequests are finished

### ISSUE THREAD

**Issue by Naphier** [mapbox/mapbox-unity-sdk#49]
Currently there's no built-in way to determine when all HTTPRequests are completed.

Developers can, of course, put in their own method, but this requires modifying the internal HTTPRequest class. 

Consider adding a class with a delegate that will fire when all requests have completed. I did this with a simple static Action and int where the int increments with every HTTPRequest construction then decrements in the end of the DoRequest coroutine and when the int is 0 it fires the delegate. However, there's probably a more elegant way of doing this (I was in a rush ;)). 

Thanks!

**Comment by david-rhodes** [comment]
@Naphier Great request! This is similar to: https://github.com/mapbox/mapbox-unity-sdk/issues/35. We're thinking of creating an `IProgressReporter` interface and implementing that throughout the SDK, starting with the originating request (`HTTPRequest` or `MapboxAccess`, in this case).

In the meantime, please be encouraged to fork and submit pull requests! 

/cc @BergWerkGIS something to think about for threaded requests

**Comment by Naphier** [comment]
What I did was not worthy of a PR. ;)
I think #35 is overall a better plan. Progress would be perfect. Feel free to close this if you like.

**Comment by BergWerkGIS** [comment]
@david-rhodes @Naphier 

First idea:
* callback when a request has finished, has the number of remaining requests as parameter
* callback when the request queue has finished

https://github.com/mapbox/mapbox-sdk-cs/blob/d2f632ef8ddc65d4217bf8b0679de9f9f876151f/test/UnitTest/FileSourceMockApiTest.cs#L166-L177

Would that work?

**Comment by Naphier** [comment]
My problem with this is that you'd need to hook in to every request's callback. Likely more elegant, but might be sort of complex to newer Unity devs as it requires a bit of work to set up a custom callback. My idea was just a static class that retains the request count:

https://gist.github.com/Naphier/44a63d8d07be52e589e387c642e572fd

Of course, this doesn't have progress, but it would be simple to implement. And I'd ultimately think this should be done at a higher level (maybe at Mapbox.Map.Tile.Initialize() ?). Each MapController.Execute() would  reset the static total requests, a new count of requests would get registered via each Mapbox.Map.Tile.Initialize(). Each Mapbox.Map.Tile.HandleResponse() would increment a static number of responses. Then a static action could be used to report progress. Just my thoughts on it and what I think would be simplest for the developer to interface with.

**Comment by david-rhodes** [comment]
@BergWerkGIS As mentioned, I was thinking we could have an `IProgressReporter`. `IAsyncRequest` could implement this (as well as all our mesh factories and visualizers), and this could report a normalized value of completion (maybe as an event?). Then, as a developer, you get a reference to whatever `IProgressReporter` you want and handle its notifications. 

Using this approach would also let us build composite progress reporters to chain progress all the way through a complex map generation.

**Comment by david-rhodes** [comment]
First pass progress reporting has been implemented: #89.

The `AbstractMap` has an initialized event, but this is used for doing conversions that require specific map attributes (reference tile and world scale, etc.). The `MapVisualizer` now has state changed events, as well as all the `TileFactories`. Use these to know when specific factories, or the entire map are done loading.
