### ISSUE TITLE
Tilemap Zoom Extent

### ISSUE THREAD

**Issue by ahokinson** [mapbox/mapbox-unity-sdk#490]
This may be more of a question related to the use of Mapbox in general, but let's say I have two tilesets...

I have one tileset for a simplified data view which is considered any zoom from z0 - z6.
And I have another tileset for detailed viewing which appears at any zoom from z7 - z16.

The following happens:
https://streamable.com/lsag3

What's the point of setting an upper limit to the zoom if the following is true?
```
Data will be visible above zoom 6, but may appear simplified.
```

I could easily hide the states when the zoom is 7, but those are wasted requests.

Any ideas or advice?

**Comment by atripathi-mb** [comment]
@ahokinson I am not sure if I understand your question completely. 

>What's the point of setting an upper limit to the zoom if the following is true?

Are you referring to upper limit to the zoom of your tileset? or something else?

Could you give me some more detail on what you are trying to do?

**Comment by ahokinson** [comment]
I can try to explain below with screenshots.

The first tileset is to simplify calls to my own personal API because there is a call per object loaded. So at lower zooms, I am querying less.

<img width="1259" alt="screen shot 2018-01-09 at 5 25 39 pm" src="https://user-images.githubusercontent.com/1762048/34746489-309f051c-f562-11e7-942e-00d899df9865.png">

It is added to a VectorTileFactory as follows:

![screen shot 2018-01-09 at 5 26 25 pm](https://user-images.githubusercontent.com/1762048/34746529-4e88c518-f562-11e7-9534-d3687300971e.png)

Similarly, at higher zooms, less objects are loaded and therefore, queries are still manageable.

<img width="1251" alt="screen shot 2018-01-09 at 5 25 54 pm" src="https://user-images.githubusercontent.com/1762048/34746491-3260bd64-f562-11e7-925d-9af5de66234a.png">

![screen shot 2018-01-09 at 5 26 37 pm](https://user-images.githubusercontent.com/1762048/34746533-5498eb90-f562-11e7-849a-0df66e219b20.png)

In the video, however, you will see that when the map becomes zoom level 7, both tilesets are added to the map, despite the upper limit of the tileset being set to 6.

![screen shot 2018-01-09 at 5 32 06 pm](https://user-images.githubusercontent.com/1762048/34746708-0b0e7098-f563-11e7-9eaa-e1823ec631b6.png)

Yellow: States
Pink: Cities

![screen shot 2018-01-09 at 5 31 56 pm](https://user-images.githubusercontent.com/1762048/34746721-1bf6a1aa-f563-11e7-97e2-c457cd58ab8a.png)


Hopefully that helps clarify things?

**Comment by BergWerkGIS** [comment]
> Data will be visible above zoom 6, but may appear simplified.

@ahokinson That's a feature of our vector tile API and it's called overzooming: https://www.mapbox.com/help/define-overzoom/


https://github.com/mapbox/vector-tiles/issues/21#issuecomment-240169793 :

> Overzooming is a vector-tile specific technique that allows a specific tile to be rendered beyond its intended zoom level, so it continues to be visible on the map. If a tileset had a minzoom of 6 and a maxzoom of 12, those are the valid ranges calculated by the tile generator (more on that below). If you were to zoom your map beyond zoom level 12, the map renderer can continue to use zoom 12 by scaling the vector data upwards. This, of course, can result in gross simplifications of data if geometries are rendered too far above their actual level of detail.

-----

@brnkhy any ideas how tilesets can be limited to a certain zoom range?

* z0 => z6 use simplified tileset `GIOSimple`
* z7 => z16 use detailed tileset `GIODetailed`

**Comment by david-rhodes** [comment]
Without looking at the code, I suspect you could inherit from `FilterBase` and use zoom level as your filter condition. Then you could apply this filter to the `VectorLayerVisualizer`.

**Comment by brnkhy** [comment]
@david-rhodes Filters doesn't get map/tile data so won't be able to filter based on zoom level.

Easiest way to achieve this would be creating both tileset and enable/disable their parent objects depending on the zoom level. This will increase loading time and memory usage of course but you'll be able to switch between them instantly on runtime. But it's still the best way to do it if you're expecting a lot of zoom in&out in your usecase. From what I could see in that video, you're only rendering pois and it shouldn't be a problem to render both (and hide).

**Comment by brnkhy** [comment]
Another option would be to have a custom script and attach your vector factory to that, change mapid depending on the zoom level and reinitialize/reset the map. But that would mean creating and destroying vector objects every single time you go through that separation level z6-z7.
