### ISSUE TITLE
Factory improvements

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#491]
So there are a few problems and possible improvements about factories I wanted to discuss, I'll dump them all here I guess.

1) All factories inherit from AbstractTileFactory which makes it hard to differentiate terrain/image/vector factories

If we implement base classes for all three types, like TerrainFactoryBase, ImageFactoryBase and VectorFactoryBase, we can check MapVisualizer for each those catefories individually. So we can do MapVisualizer.GetTerrainFactory and it'll return one regardless it's flat or globe or standard.

![chrome_2018-01-10_23-10-01](https://user-images.githubusercontent.com/1465390/34793138-6a7f1796-f65b-11e7-9d10-7d0dfe6af66c.png)

Another advantage of this, we can remove the list of factories inside the map visualizer and change it to have one of each type. So one terrain, one image and one vector fields. That'll cover over 99% of the cases and will be much easier to maintain and UI/UX (fields are much easier to work with than lists). They can be null of course so you'll still be able to have just vector factory for example. We're just limiting max number to 1 of each (terrain and image factories are already limited to max of 1 anyway). 
Then we can have another version of map visualizer with a list as well.

2) Factories doing data fetching themselves is limiting

At the moment factories fetch and start the data processing and since they don't have events or any outside connection, it's not possible to get that data from any other module in a easy/intuitive fashion.

I'm considering to extract data fetching part to another class/module. Then factories will have a reference (or not. I'll come to that) to those modules, register to them and request tiles from them. So when a vectortile or image is recieved, it'll fire an event and factory will get its data. Advantage of this approach is that now every module can simply register to those new modules and get those data. 
i.e. a game object modifier can register to image factory, save references to images and then use them for roof tops (instead of getting it from unitytile object as we're doing at the moment).
Another (and probably better) case would be classes outside the mesh generation system. So for example, you can have a UI panel which registers to image factory and shows all downloaded images as a 2D UI map.

![fact](https://user-images.githubusercontent.com/1465390/34793573-ecfbb53e-f65c-11e7-8e8d-e5516f792181.png)

Also we don't have to have a reference and use events here either. We can also go for something like message bus / observer pattern which would 100% decouple these new modules from everything else. Might be an overkill and I would prefer to go for whatever has higher performance (event count here will be rather low, even big maps have only a few dozen tiles at the moment) but still a nice option to consider.

**Comment by brnkhy** [comment]
I did some quick testing today about the 1st issue. Implemented base classes for each three factory types, inherited all existing factories from them. Them created three fields n Map visualizer for them. Everything worked quite smoothly, haven't encountered any issues in editor/inspectors/compatibility stuff etc.

![unity_2018-01-18_17-43-40](https://user-images.githubusercontent.com/1465390/35103523-23c5307a-fc77-11e7-96b0-12f560b3ec03.png)

So you can see the current factory list at the bottom and simpler, 3 factory fields on top. 
Question is, do we replace the bottom list with those three fields above.

Only negative thing I can think of about this is that you won't be able to add multiple vector factories. Two questions about this issue would be; 
(1) How frequently (or at all) do we need that?
(2) What if we replace just vector field with vector factory list?

I quite like this for a few reasons;
(1) much easier UI/UX
(2) much easier to query for a certain factory 
(3) save us from all the complexity of that factory list creates (in inspector/node editor etc)

**Comment by brnkhy** [comment]
Oh and actually we can simply create this 3 factory thing as an alternative without even touching the MapVisualizer class itself.... 🤦‍♂️ 
I'll just do that and PR I guess.

**Comment by brnkhy** [comment]
One problem though, three field thing means blocks like this;
```
if (TerrainFactory != null && TerrainFactory.Active)
			{
				TerrainFactory.Register(unityTile);
			}
			if (ImageFactory != null && ImageFactory.Active)
			{
				ImageFactory.Register(unityTile);
			}
			if (VectorFactory != null && VectorFactory.Active)
			{
				VectorFactory.Register(unityTile);
			}
```

and not to do that, I created a private list and added existing active factories to that internally. So a list again but in the background and just to simplify syntax.

```
foreach (var factory in _factories)
			{
				factory.Register(unityTile);
			}
```

**Comment by brnkhy** [comment]
current map visualizer
![unity_2018-01-18_18-36-32](https://user-images.githubusercontent.com/1465390/35106637-c53e4614-fc7f-11e7-87ea-1f79ab163d76.png)

new basic map visualizer
![unity_2018-01-18_18-36-22](https://user-images.githubusercontent.com/1465390/35106650-ccf2a814-fc7f-11e7-8afa-0620f91a00f1.png)

unfortunately I had some issues to keep both and had to make some changes to base classes;
![visualizers](https://user-images.githubusercontent.com/1465390/35106675-e3192a5a-fc7f-11e7-9f5e-bbd96b964de0.png)
green marked classes are new (so I had to change the base class, turns out "abstractmapvisualizer" which we used as base class, has way too much stuff. new base class is just few empty methods). purple marked ones are existing classes with small changes to make them work with new base class.

**Comment by brnkhy** [comment]
pushed all these changes here for testing; https://github.com/mapbox/mapbox-unity-sdk/tree/mapVisualizerStructureChanges

**Comment by MiroMuse** [comment]
Update: @atripathi-mb has implemented part 1, not yet part 2.

**Comment by atripathi-mb** [comment]
Part 1 done, part 2 in #622 .
