### ISSUE TITLE
Unfinished coroutine on destroyed GameObject results in VectorLayerVisualizer failure.

### ISSUE THREAD

**Issue by ahokinson** [mapbox/mapbox-unity-sdk#498]
I am using the following stack during Mesh Generation:
![screen shot 2018-01-12 at 2 33 00 pm](https://user-images.githubusercontent.com/1762048/34891985-8d3a72f8-f7a5-11e7-8cee-42b31112c2ce.png)
![screen shot 2018-01-12 at 2 33 37 pm](https://user-images.githubusercontent.com/1762048/34891998-9d115a0c-f7a5-11e7-9ff3-6c3ecdb1f229.png)
![screen shot 2018-01-12 at 2 34 03 pm](https://user-images.githubusercontent.com/1762048/34892016-ab1d84a4-f7a5-11e7-80d9-c4c1a0034f95.png)
![screen shot 2018-01-12 at 2 34 23 pm](https://user-images.githubusercontent.com/1762048/34892029-b8fd4596-f7a5-11e7-8a79-4665dffda0b7.png)

The spawned `State` prefab has the following on a parent object,

```
using System.Collections.Generic;
using Mapbox.Unity.MeshGeneration.Interfaces;
using UnityEngine;

namespace Akamai.Map
{
	public class POIPrefab : MonoBehaviour, IFeaturePropertySettable
	{
		public void Set(Dictionary<string, object> props)
		{	
			foreach (var prefabComponent in GetComponentsInChildren<IPrefabInitializable>())
			{
				prefabComponent.Initialize(props);
			}
		}
	}

	internal interface IPrefabInitializable
	{
		void Initialize(Dictionary<string, object> props);
	}
}
```
The `Initialize` routine ends up getting information about that object from my API using a coroutine. The reason for doing this is shown in the development screen shot below.

![unity-screenshot](https://user-images.githubusercontent.com/1762048/34891828-02e6def2-f7a5-11e7-8ed0-17ff5508932f.png)

When panning the map or zooming through a level quickly, the following missing reference exception occurs.

```
MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.GameObject.GetComponent[T] () (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs:38)
Mapbox.Unity.MeshGeneration.Modifiers.PrefabModifier.Run (VectorEntity ve, Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/GameObjectModifiers/PrefabModifier.cs:39)
Mapbox.Unity.MeshGeneration.Modifiers.ModifierStack.Execute (Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData meshData, UnityEngine.GameObject parent, System.String type) (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/ModifierStack.cs:218)
Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer.Build (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, UnityEngine.GameObject parent) (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:229)
Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer+<ProcessLayer>c__Iterator0.MoveNext () (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:146)
Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

I would imagine my API coroutine is breaking mesh generation, but I may be wrong. I am wondering if there is either a safer way to destroy tiles with active coroutines or, better yet, if you have any ideas of how I can work around this in the mean time?

Unity version: 2017.3.0p1
Mapbox SDK version: 1.3.0

**Comment by jordy-isaac** [comment]
@ahokinson Thanks for your patience. We're looking into this one for you.

**Comment by jordy-isaac** [comment]
If you're still having trouble with this in version 1.4 please open and update the ticket so that we can check into it. Thank you!
