### ISSUE TITLE
[Unsolved] Problem when converting positions to tiles and vice versa.

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#499]
I recently tried to calculate the tile on which a special gameobject stands on, like this : 

`TileCover.CoordinateToTileId(new Vector2d(52.5229059402781, 13.3428955078125), ChunkData.zoomForChunkCalculation)`

The tile was : "16/35197/21491"

Later i executed the same method with the SAME lat/lng but i received a result of "16/35197/21492" instead.

Why does this happen ? Normaly it should return the same result when i use the same parameter right ? Everything stood the same, even the ChunkData.zoomForChunkCalculation... 

Heres a better explanation of my iusse =

 The player walks to a specific tile -> he builds something there -> the building calculates on what tile the player stands on -> the building spawns in the middle of the tile. The lat/lng coordinates of the building are pushed into the Database. Everything is fine.

The player logs in -> building with lat/lng coordinates is loaded out of the database -> calculating tile with the lat/lng coordinates -> building spawns directly on the calculated tile.  Suddenly the building stands on an completly different tile 

But the lat/lng coordinates are the same...

**Comment by atripathi-mb** [comment]
@genaray I tried running a test for `CoordinateToTileId` with the values you provided and I get the same tileid back every time. Ran the test for over 2k iterations. 

This is the code I used to test 
```
	void Update()
	{
		var test = TileCover.CoordinateToTileId(new Vector2d(52.5229059402781, 13.3428955078125), 16);
		Debug.Log("returned id : " + test.ToString());
	}
```
![image](https://user-images.githubusercontent.com/32286016/35005391-769d6db2-fab0-11e7-9aeb-147741972d5a.png)

The coordinates have to be different for the tileId to be different at the same zoom level. Are you sure the coordinates being passed are exactly the same? Converting a float to double ( or vice-versa) may introduce precision errors. 


Could you provide us with a sample test case or steps to reproduce the problem easily?

**Comment by genaray** [comment]
Thanks for the support, i think i solved it for now. I just restarted my pc. Maybe it was some kind of memory iusse O.o
