### ISSUE TITLE
Is it possible to use custom vector map service ?

### ISSUE THREAD

**Issue by dingfengboo** [mapbox/mapbox-unity-sdk#500]
like openmaptiles or mapzen. Thanks a lot.

**Comment by BergWerkGIS** [comment]
@dingfengboo OpenMapTiles should work as they are also using the [Mapbox Vector Tile Specification](https://github.com/mapbox/vector-tile-spec) for their tiles - untested though.

You shouldn't opt for the MapZen route as they will be shutting down their services in two weeks:

* https://mapzen.com/blog/shutdown/
* https://mapzen.com/blog/migration/
* https://blog.mapbox.com/migrating-your-mapzen-unity-project-8e8b80d7d352

If you are looking for a way to use your own data in a custom tileset you can do that with Mapbox too.
Two links that might help you get started:
https://www.mapbox.com/help/how-uploads-work/
https://www.mapbox.com/help/uploads/

**Comment by tetreum** [comment]
I don't see where i can set the custom source in MapBox SDK to point it to any of OpenMapTiles services (GL, TileJSON, WMS, WMTS, Raster, Vector, etc..):
![Imgur](https://i.imgur.com/w0bxM0M.png)

Everything in this sdk points to a "mapbox://" protocol and fails to load anything else :S
