### ISSUE TITLE
Rotating the camera in Location Provider example removes tiles

### ISSUE THREAD

**Issue by apavani** [mapbox/mapbox-unity-sdk#511]
**Context:** 

A developer reported this problem where rotating the camera removes already active tiles

**Problem:** 
Here's a detailed preview of the issue
https://www.youtube.com/watch?v=Egn3LIXqsZQ

**Solution:** 

My guess is that there is something wrong among the lines 129 through 135 in the `QuadTreeTileProvider.cs`script

**Comment by mjakupi** [comment]
Bump! Hello did you find any solution for this bugg?

**Comment by atripathi-mb** [comment]
@mjakupi #527 Should fix it.
