### ISSUE TITLE
Setting resolution when using RasterTile

### ISSUE THREAD

**Issue by yashiro32** [mapbox/mapbox-unity-sdk#512]
Is it possible to set the resolution of the texture downloaded when using RasterTile? For example 1024x1024 pixels or 2000x2000 pixels instead of the usual 512x512 pxiels.

**Comment by BergWerkGIS** [comment]
@yashiro32 512x512 (aka `retina tiles`) is the maximum size offered by the API:
https://www.mapbox.com/api-documentation/#retina
