### ISSUE TITLE
[Support] Convert Mouse Click Location to Lat/Lon

### ISSUE THREAD

**Issue by tgaldi** [mapbox/mapbox-unity-sdk#514]
I'm trying to get the Lat/Lon of a point on the dynamic zoom map with a mouse click.

The coordinate is not correct / will change when clicking on the same point in the map after moving it.

In QuadTeeCameraMovement LateUpdate:
```
if( Input.GetMouseButtonUp( 1 ) )
{
    float factor = Conversions.GetTileScaleInMeters( (float)0, _dynamicZoomMap.AbsoluteZoom ) * 256.0f / _dynamicZoomMap.UnityTileSize;

    var mousePosScreen = Input.mousePosition;
    mousePosScreen.z = _referenceCamera.transform.localPosition.y;
    var pos = _referenceCamera.ScreenToWorldPoint( mousePosScreen ) * factor;

    var latlongDelta = Conversions.MetersToLatLon( _dynamicZoomMap.CenterMercator + pos.ToVector2d() * _dynamicZoomMap.WorldRelativeScale );
    Debug.Log( "Latitude: " + latlongDelta.x + " Longitude: " + latlongDelta.y );
}
```

Thanks.

**Comment by atripathi-mb** [comment]
@tgaldi We added convenience methods on `AbstractMap` to make these conversions simpler. 

Changed your code snippet slightly to get correct results:
```
			if (Input.GetMouseButtonUp(1))
			{				
				var mousePosScreen = Input.mousePosition;
				mousePosScreen.z = _referenceCamera.transform.localPosition.y;
				var pos = _referenceCamera.ScreenToWorldPoint(mousePosScreen);

				var latlongDelta = _dynamicZoomMap.WorldToGeoPosition(pos);
				Debug.Log("Latitude: " + latlongDelta.x + " Longitude: " + latlongDelta.y);
			}
```
Please note that the values might not be exactly the same because of precision loss.

**Comment by tgaldi** [comment]
Ah great! Thanks.

**Comment by ShyamBarange** [comment]
@tgaldi  Hi, 
were you able to get latitude/longitude from mapbox map on mouse click?
I am looking for the same solution.
Thanks.

**Comment by atripathi-mb** [comment]
@ShyamBarange Did the code snippet mentioned in https://github.com/mapbox/mapbox-unity-sdk/issues/514#issuecomment-359894190 not work for you? 
Can you give us more details on what you're trying to achieve?
