### ISSUE TITLE
Putting 3D road models on top of road meshes for a more realistic experience.

### ISSUE THREAD

**Issue by ufktvfk** [mapbox/mapbox-unity-sdk#515]
I am trying to learn the world postions of road meshes so that I can instantiate 3D road models at wherever there is a road object to make my Mapbox AR  project more realistic but I am unable to get meshes's positions since all road objects's transform.position is (0,0,0). I investigated navigation meshes and Drive example but couldn't find any solution. Can you help me with that? 
I am using Mapbox v1.2 and Unity 2018.2.0p1.

**Comment by brnkhy** [comment]
Features, by default (for performance reasons), are placed at tile center and vertices are offsetted to their positions. 
You can change this behaviour using the `Feature Position` property in the modifier stack.

**Comment by brnkhy** [comment]
@ufktvfk I think this is good to close.
