### ISSUE TITLE
Get height from a point

### ISSUE THREAD

**Issue by MitchEff** [mapbox/mapbox-unity-sdk#516]
Hey guys,

I know this has been covered [here](https://github.com/mapbox/mapbox-unity-sdk/issues/222#issuecomment-350666693), but the answer is... rather cryptic (a Google for " tile coordinate space" only returns that comment. What is 'tile coordinate space'?).

Anyways, I'm just trying to get a Unity height value for a given Vector3, and am sort of going in circles. So far, I'm looping through all the children of my map object to find the closest "tile", then I guess I use QueryHeightData with some "tile coordinate space" values, then I get a value metres, then I convert the metres back to Unity units? 

Any help will be greatly appreciated, I'm so lost and there's just no documentation for this. 

```
    public static float GetBaseHeight(GameObject map, Vector3 centrePoint)
    {
        int key = 0;
        int currentClosestIndex = -1;
        float closestDistance = 0;

        foreach(Transform mapTile in map.transform)
        {
            float distanceFromCentrePoint = Vector3.Distance(mapTile.transform.position, centrePoint);

            if(currentClosestIndex == -1 || closestDistance > distanceFromCentrePoint)
            {
                currentClosestIndex = key;
                closestDistance = distanceFromCentrePoint;
            }

            key++;
        }

        UnityTile tileObject = map.transform.GetChild(currentClosestIndex).gameObject.GetComponent<UnityTile>();

        return new float();
    }
```

**Comment by brnkhy** [comment]
Hey @MitchEff, 
Sorry for the confusion, we're planning to add this query to BasicMap class soon which hopefully will simplify whole process.
I think you're on right track though, 
- you should find the tile containing your point (or closest)
- then convert your point to 0-1 range in that tile (think of it like a UV map, (0,0) for min (1,1) for max. So to query the middle of it, it should be (0.5,0.5))
- then pass those two to QueryHeightData method

I believe returned height value should be scaled down/up to your world and ready to use.
SnapTerrainModifier also does something similar to this, you can check that as well. 
Let me know if you have any problems!

**Comment by JorgeVelez** [comment]
Tile coordinate space of the point(lat lon) can be calculated with the help of the tile's Rect. 

Took me a while to figure out.

```
void spawnPrefabWithHeight(double lat, double lon)
{
	//get tile ID
	var tileIDUnwrapped = TileCover.CoordinateToTileId(new Mapbox.Utils.Vector2d(lat, lon), (int)_map.Zoom);

	//get tile
	UnityTile tile = _map._mapVisualizer.GetUnityTileFromUnwrappedTileId(tileIDUnwrapped);

	//lat lon to meters because the tiles rect is also in meters
	Vector2d v2d = Conversions.LatLonToMeters(new Mapbox.Utils.Vector2d(lat, lon));
	//get the origin of the tile in meters
	Vector2d v2dcenter = tile.Rect.Center - new Mapbox.Utils.Vector2d(tile.Rect.Size.x / 2, tile.Rect.Size.y / 2);
	//offset between the tile origin and the lat lon point
	Vector2d diff = v2d - v2dcenter;

	//maping the diffetences to (0-1)
	float Dx = (float)(diff.x / tile.Rect.Size.x);
	float Dy = (float)(diff.y / tile.Rect.Size.y);

	//height in unity units
	var h = tile.QueryHeightData(Dx,Dy );

	//lat lon to unity units
	Vector3 location = Conversions.GeoToWorldPosition(lat, lon, _map.CenterMercator, _map.WorldRelativeScale).ToVector3xz();
	//replace y in position
	location = new Vector3(location.x, h, location.z);

	var instance = Instantiate(_markerPrefab);
	instance.transform.position = location;
	instance.transform.SetParent(transform);
}
```

![screen shot 2018-01-23 at 4 18 05 pm](https://user-images.githubusercontent.com/2000930/35301428-802e4186-0059-11e8-8488-5d4d032c5a65.png)

**Comment by MitchEff** [comment]
Thanks so much for sending your code over @JorgeVelez , but it just seems to return zero for me, despite my Dx and Dy appearing correct.

I _was_ eventually able to get it going by doing a raycast directly downwards at the ground, but this only works once the terrain's initialised - I can't work out how to wait for this, so it's currently waiting 2 seconds before casting. Obviously not a reliable workaround... 

@brnkhy, I don't suppose you're aware of why @JorgeVelez 's approach would always be zero, or if there's some sort of callback for when the terrain is loaded?

Sorry for all the questions, Google and the docs aren't being too helpful here.

**Comment by MitchEff** [comment]
Okay, plot twist! I can hook into OnHeightDataChanged for the tile (so I know when the heights are in), so I can then theoretically raycast to it and get a meaningful value.

..._but_ OnHeightDataChanged, the object position is at -38, for some reason. I tried adding 38 to it (to make it zero), but then on render, the tile is 38 points above everything else, haha. 

Good grief this is difficult. Anyone have any idea what's going on here?

**Comment by alexandru-borsevici-plunge** [comment]
Hello, for the height offset issue you might have the **Snap Map Height To Zero** checked, try disabling that so that all your tiles remain on the same level.

**Comment by brnkhy** [comment]
I pushed a helper function here; https://github.com/mapbox/mapbox-unity-sdk/tree/queryHeight
But I might overlooked the "Snap Map Height to Zero" thing as @alexandru-borsevici-plunge  mentioned, I'll check that first and then we'll probably merge that in soon.

**Comment by brnkhy** [comment]
@MitchEff MapVisualizer should have an event for everything finished loading, you can try that as well. But that -38 thing (object position) sounds like moving map to world origin (snap map height to zero). That's one feature/property even I tend to forget and look over sometimes.
