### ISSUE TITLE
Prohibit meshes from being split between tiles

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#517]
* Unity version: 2017.1.1f1
* Mapbox SDK version: v.1.3.0
* The platform you're building to: Win (only in editor so far)

When generating a mesh with a VectorTileFactory, is there any way/workaround to stop the mesh from being split between the tiles? 

The image below shows a set of oil-fields generated from a vector tileset, which uses the hover effect, and is clickable. However, most of them will end up being split between tiles, like the one circled in red, which will cause a lot of issues. 

![image](https://user-images.githubusercontent.com/35730930/35277888-83374956-0048-11e8-90ee-144b9576aa59.png)

**Comment by JorgenEngenNapstad** [comment]
Thanks @brnkhy. 

If I create them in a lower zoom level, does that affect the resolution of the data and subsequently the mesh object? 

Do you mean merge the GameObjects (or the components from several GO) that should be one object? I guess that could be doable, although it might be a heavy operation if it applies to a lot of data (This would be true across several data-sets in our case). I guess it would only need to happen on startup though, as the gameobjects don't get destroyed and re-drawn when loading in and out of view, if I understand correctly?

**Comment by brnkhy** [comment]
@JorgenEngenNapstad 
`If I create them in a lower zoom level, does that affect the resolution of the data and subsequently the mesh object?`
Hmm technically, it should a little, yes. So I guess merging is a better option.

What I had in mind;
- create a dictionary<edge, feature>
- create all features
- check if it touches the edges of the tile
    - if(true), check dictionary if same edge exists //touching edges
       - if(true), add current feature mesh to the existing one
       - if(false), add new edge&feature to dictionary
    - if(false), finalize feature //not touching edges

I might be missing something as I never tried to implement this. Also merging polygons might require a library or something here. But yea this was what I had in mind. It would get slower as feature count increases (like buildings) but shouldn't be a problem for a dozen or so custom features I think.

**Comment by JorgenEngenNapstad** [comment]
Thanks for sharing @brnkhy. Will have a look at it and keep you updated.
