### ISSUE TITLE
[Support] Best way to get interactable POIs on map

### ISSUE THREAD

**Issue by playtradev** [mapbox/mapbox-unity-sdk#518]
Wondering what the most elegant way to create interactable Points-of-Interest on the map would be.
I'm fairly new to coding, sure you'd all have a heart attack if you saw my project.

Anyway, have managed to spawn a number of random points in a predetermined range around the player's Current Location by hacking apart the `SpawnOnMap.cs` script.

My issue is that normally I would `transform.SetLocation()` the POIs onto the Canvas, so as to use button UI functionality. However, I haven't been able to do so without messing everything up. Was hoping somebody might be able to suggest an alternative of anybody had done something similar.

`Cheers ʕ•ᴥ•ʔ`

If this isn't the right place to ask about this please let me know.
Unity v.2017.3.0f3, Mapbox v1.3.0.

**Comment by brnkhy** [comment]
Hey @playtradev !
To be able to keep it flexible, we're visualizing POIs by placing prefabs in those locations. This means that you can use your own prefab, with all sorts of visual effects, animations and of course interactions, to use for POIs.

If you mean custom pois you create yourself on runtime (without using Mapbox services), I guess same approach would help best. Then you can check about mouse&object interaction stuff online (i.e. raycast or OnMouseDown).

Hope that helps!

**Comment by playtradev** [comment]
@brnkhy Thanks for the advice, just what I needed to know.

I have been using the POI system provided by Mapbox but of course by default they are generated outside of the Canvas, and so far I haven't seen a way of getting them to spawn inside of the Canvas without screwing up the transform.

Was trying to avoid having to use Raycasting and GetTouch() to keep all the interaction in the project uniform but guess I'll have to bite the bullet.

Thanks again!

**Comment by playtradev** [comment]
@brnkhy  Not sure if I should start a new issue or if this sub-question will be seen:

I've been having a lot of issues with Mapbox being oriented 'down' in the Unity scene.
Unity is hard coded to take X/Y plane as the 2D plane, but mapbox has been coded in the Z/X.

This has presented many issues, the latest of which (related to my original question), is when Raycasting in 2D, Mapbox is oriented the wrong way but unity will not allow 2D colliders to be rotated.
`RaycastHit2D rayHit = Physics2D.Raycast(Camera.main.ScreenToWorldPoint(Input.mousePosition), new Vector2(0, -100));`
Being unable to rotate the map means I am going to have to make my project use 3D colliders, not ideal for sprite based POIs.

Any ideas for cleaner solutions would be much appreciated!
`ʕ•ᴥ•ʔ`

Below are my 2D raycasts but they return nothing, waa.
![image](https://user-images.githubusercontent.com/35369227/35342462-0979e5a0-0120-11e8-87ff-d22b25bc08a1.png)

**Comment by atripathi-mb** [comment]
@playtradev I recently helped some one else looking to get the coordinates on mouse-click. This code snippet might help solve your issue too, give it a try. 

```
if (Input.GetMouseButtonUp(1))
{				
	var mousePosScreen = Input.mousePosition;

	//assign distance of camera to ground plane to z, otherwise ScreenToWorldPoint() will always return the position of the camera
	//http://answers.unity3d.com/answers/599100/view.html

	mousePosScreen.z = _referenceCamera.transform.localPosition.y;
	var pos = _referenceCamera.ScreenToWorldPoint(mousePosScreen);

	var latlongDelta = _dynamicZoomMap.WorldToGeoPosition(pos);
	Debug.Log("Latitude: " + latlongDelta.x + " Longitude: " + latlongDelta.y);
}
```

**Comment by brnkhy** [comment]
@playtradev we treat our maps inside the SDK as real world or terrain (so far) so it lays on XZ plane as a terrain would. We had sprite based 2D map in our todo list for a long time, even experimented a little long time ago but couldn't finalize it.
I have no experience with 2D game development at all but have you tried putting those POI labels in UI Canvas? That's what I generally do for labels and icons and I believe POI demo scene also shows it.

**Comment by playtradev** [comment]
@atripathi-mb @brnkhy Thanks for the fast responses!

Yep, putting the POIs in the UI Canvas was my first thought and I did eventually manage to get them spawning in the correct locations, however as soon as I zoomed or panned they would fly off, amongst other issues.
Not 100% but, I think i tracked down one issue to the the update function in `SpawnOnMap.cs`, probably giving me the issues due to the altered transforms.
```  
private void Update() {
            if (_spawnedObjects != null)
            { int count = _spawnedObjects.Count;
                for (int i = 0; i < count; i++) {
                    var spawnedObject = _spawnedObjects[i];
                    var location = _locations[i];
                    spawnedObject.transform.localPosition = _map.GeoToWorldPosition(location); }
```
For now i'll have to see if I can get 3D Raycasting to work.
Let me know if you ever get a chance to have another look over 2D maps!
Thanks again.

**Comment by alagrad94** [comment]
@playtradev  Do you mind sharing how you managed to spawn a number of random points in a predetermined range around the player's Current Location.  This is something I've been trying to do and have been struggling to make it work.

**Comment by playtradev** [comment]
@alagrad94 hi alagrad, sorry for late reply.
I can show you what I did but it's probably really hacky, i'm quite new to coding and certainly new to integrating SDK's into my crappy code. However: I used the SpawnOnMap script provided by Mapbox and altered it slightly.
```
        private IEnumerator RandomLocations()
        {
            //Get GPS location
            Vector2d currentLocation = AbstractLocationProviderRef.CurrentLocation.LatitudeLongitude;

            //If GPS not yet Initialised wait 3 seconds and try again
            if (currentLocation.x == 0)
            {
                yield return new WaitForSeconds(3);
                StartCoroutine(RandomLocations());
            }

            //Wait until it has found the GPS location
            yield return new WaitUntil(() => currentLocation.x != 0);

            //Distance from current location
            float xDistance = (float)currentLocation.x;
            float yDistance = (float)currentLocation.y;
            float distanceConstant = 0.03f;
           
            //Spawn no. of random locations specified in editor
            for (int i = 0; i < RandomLocationCount; i++)
            {
                //Create random location and remove annoying (brackets) from either side that mess up the StringToLatLon() function
                _locationStrings[i] = new Vector2(Random.Range(xDistance + distanceConstant, xDistance - distanceConstant), Random.Range(yDistance + distanceConstant, yDistance - distanceConstant)).ToString("F5").Replace("(", "").Replace(")", "");

                Debug.Log("<color=blue>Made a new Random Location: </color>" + _locationStrings[i]);
            }

            _spawnedObjects = new List<GameObject>();
            for (int i = 0; i < _locationStrings.Length; i++)
            {
                var locationString = _locationStrings[i];
                _locations[i] = Conversions.StringToLatLon(locationString);
                var instance = Instantiate(_markerPrefab);
                instance.transform.localPosition = _map.GeoToWorldPosition(_locations[i]);
                instance.transform.localScale = Vector3.one * _spawnScale;
                _spawnedObjects.Add(instance);
            }
            yield return null;
        }
```
Hope that might help! It's probably trash though...

**Comment by alagrad94** [comment]
@playtradev no problem.  Thanks for sharing this!  It will at least get me started in the right direction.

**Comment by copenhaverjf** [comment]
@playtradev I finally found someone who has experienced the same thing I'm doing! Out of curiosity, did you solve this problem by projecting on the 2d canvas or creating a 3d collider? I'm having some issues getting raycasting to work properly (when I call ScreenToWorldPoint and use that point to draw a ray, the ray is not located over my mouse click as I would expect) which is likely my problem... but I do have to ask..

(This one is for the MapBox devs) Event handling is something I would expect with an out of the box solution, even if that means a 3d raycast solution with a prefab camera/map bundle and event handlers available so it is a plug-in solution. My wheel reinvention is likely not going to be nearly as good as whatever the MapBox devs can create, given less knowledge on the abilities. That and it lacks parity with some of the other MapBox implementations which provide event hooks.

Going to probably bang my head off a wall and try to implement a UI canvas button overlay approach over a 3d collider approach (my 2d sprites are also exhibiting lots of occlusion issues with the map layer itself)

**Comment by alagrad94** [comment]
Hey guys, try out this course on Udemy, it’s actually free and I’ve been going through it.  It shows you a lot of good stuff about Mapbox and it’s based on the new release as well 

https://www.udemy.com/mapbox-unity-3d-essentials/learn/v4/
