### ISSUE TITLE
Multiple roads with the same name in the same tile are created as the same mesh

### ISSUE THREAD

**Issue by Crashthatch** [mapbox/mapbox-unity-sdk#519]
Tile 12/2022/1332 contains several roads, several miles apart, all (confusingly) named "High St". When I create them in Unity using the "road_label" LineMeshModifier, all of them are created as the same mesh. This is confusing since the fact the 2 roads are named the same thing does not make them the same road.

In my case, I want to create convex colliders for the roads, and having 2 different roads on different sides of the tile means my collider spans the whole tile. I can imagine other situations where a user wants to select / move / delete a road, and does not mean to select unrelated roads several miles away.

![image](https://user-images.githubusercontent.com/186067/35291342-f0700a8c-0064-11e8-91a2-47fe9c09e5b3.png)

I'm not sure if this is a bug in the Unity SDK or the backend vector-tiles creation (or even the original data). VectorEntity.Feature.Points seems to include several sets of points, one set for each "road segment", which are combined by LineMeshModifier to create the single mesh, which suggests to me that it's the backend logic that should be improved to create separate road objects in the vector tile instead of assuming they are different parts of the same road? But I couldn't find a public issue tracker for mapbox tile creation.

If not, is there a downside to changing LineMeshModifier to create multiple meshes when FeatureData.Points contains multiple different road segments?

* Unity version: 2017.3.0f2
* Mapbox SDK version: forked from 7519ad5

**Comment by brnkhy** [comment]
@Crashthatch this is actually a feature of the api to reduce the data size; from what I've seen, it merges features together if all their properties are exactly same. It also happens with buildings as well but not really a common case. 
Unfortunately our current approach assumes (wrongly) one feature would contain just one element and system is built upon this; layer visualizer creates features and passes them to modifier stacks one by one etc.
trying to solve this on the sdk side would be a little hacky. for buildings you would have to go through each sublist and see if its clockwise or ccw (to see if it's a hole or another building). But it might be simpler for roads as you noted. maybe with a small change in vector layer visualizer (I suggest creating an alternative for roads, not to break other stuff), you can separate sublists as features as well.
meanwhile we're trying to fix this on server side with a new building and road tileset and I hope we'll be able to release it in next few months.

So on top of my head, I can't think of any issue with separating each vertex sublist as new feature and it would be a good fix for line features. Let's keep this ticket open, and please let me know if you have any problems (or success) with that approach.

**Comment by Crashthatch** [comment]
This is quite a way down my list (efficiency gain mostly). I'll have a go, but if there's a proper server-side fix on the way, you'll probably get there first!

Thanks for confirming the problem / fix.

**Comment by brnkhy** [comment]
@Crashthatch this is an interesting issue so I'll probably try client side fix some time as well and post here if I can manage to make it work.
