### ISSUE TITLE
 Whether to consider adding cache,sometimes the network is very poor.

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-unity-sdk#52]
Like this https://github.com/brnkhy/MapzenGo     this link is not use mapbox, but it use cache

**Comment by david-rhodes** [comment]
Thanks! I'm sure our very own @brnkhy knows a great deal about this 😏.

Anyway, this ticket is a duplicate, covered here: https://github.com/mapbox/mapbox-unity-sdk/issues/34, and here: https://github.com/mapbox/mapbox-sdk-cs/issues/66#issue-222569980.

**Comment by brnkhy** [comment]
@veyvin I couldn't even remember that for a second. But yes it had a very basic caching, based on saving raw data as files and re-loading them when necessary.
We'll probably go for a lower level and better solution for our SDK though. With better tooling as well, which I was hoping to do for MapzenGo back in the days, to see what's cached, how much space it takes etc etc.

**Comment by veyvin** [comment]
@brnkhy so cool

**Comment by david-rhodes** [comment]
@veyvin memory caching is in now: https://github.com/mapbox/mapbox-unity-sdk/pull/77. File caching will come next.
