### ISSUE TITLE
using line collider

### ISSUE THREAD

**Issue by asifnoor123** [mapbox/mapbox-unity-sdk#520]
Hi, First I want to thank you guys for creating an amazing sdk for unity , I am new to mapbox but so far loving it..I ran into this issue and not sure how to proceed further, I checked the resolved issues but did not see anything similar..perhaps you can point me in the right direction. I am trying to using my own custom tileset into the maps, its a line shape , basically showing the water lines in the area, In my application I want to display the properties of the line when clicked by user, but it seems like the collider available is only for Box, sphere and mesh, and I have tried all of them to no avail, Do I need to define my own line collider to achieve something like this? The screen shots below shows some details, I hope I have explained enough but I you need more information or files please let me know .....thanks again ..

**Comment by asifnoor123** [comment]
Hi, First I want to thank you guys for creating an amazing sdk for unity , I am new to mapbox but so far loving it..I ran into this issue and not sure how to proceed further, I checked the resolved issues but did not see anything similar..perhaps you can point me in the right direction. I am trying to using my own custom tileset into the maps, its a line shape , basically showing the water lines in the area, In my application I want to display the properties of the line when clicked by user, but it seems like the collider available is only for Box, sphere and mesh, and I have tried all of them to no avail, Do I need to define my own line collider to achieve something like this?  The screen shots below shows some details, I hope I have explained enough but I you need more information or files please let me know .....thanks again ...


![ss1](https://user-images.githubusercontent.com/35777008/35348102-0a5feb6a-0105-11e8-9ee5-e571475ffb23.png)
![ss2](https://user-images.githubusercontent.com/35777008/35348103-0a67ce20-0105-11e8-8013-b66c6b5b748a.png)
![ss3](https://user-images.githubusercontent.com/35777008/35348104-0a7261c8-0105-11e8-8eda-8a88d032ae28.png)

**Comment by atripathi-mb** [comment]
@asifnoor123 From your screenshot I see you are using a `merged modifier stack`. If you want individual line features selectable, you would want to use `modifier stack` instead. `Merged Modifier Stack` combines all features into one mesh, making them not selectable individually. 

For colliders, I would use capsule or mesh colliders mainly because of the shape of lines. Box collider should work as well but you might get some false positives. 

Hope this helps

**Comment by asifnoor123** [comment]
Hi Atripathi, you are right modifer stack resolved the issue, worked like a charm, exactly what I was looking for......thanks a lot....really appreciate your help....
