### ISSUE TITLE
Make the map "jump" to a specific latitude/longitude position

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#522]
#Hey there ! 

Im using AbstractMap for my game. Because my player will be able to jump to certain latLng coordinates, i need to make the map jump too... Is there a way to do this ? I tried changing the AbstractMap lat/Lng coordinates but that didnt worked. It just stays at the initiated position and i can move it around by using the camera script... Any idea how i can make the map jump to a specific point ?

**Comment by atripathi-mb** [comment]
@genaray Is you're using a `BasicMap` you need to call `map.Initialize` with the new lat/long . Check out `ReloadMap.cs` example script for a code sample. 

If you're using `QuadTreeBasicMap` then you need to call `UpdateMapProperties` on the `QuadTreeTileProvider` with the new lat/long

**Comment by genaray** [comment]
@atripathi-mb Alright thanks for your answer ... im using an AbstractMap... does this count as an basic map too ?

**Comment by atripathi-mb** [comment]
@genaray AbstractMap is an abstract class so you can't use an instance of it directly. BasicMap is a concrete implementation of AbstractMap. Check the GameObject in your scene to see which one you are using.

![image](https://user-images.githubusercontent.com/32286016/35480190-405d8042-03c6-11e8-9309-a1a3f77fb2d2.png)

**Comment by genaray** [comment]
@atripathi-mb Well thats interresting ... i dont have a script called basic map... Where can i see what mapbox version i am using ? And since when this script is included ?

**Comment by genaray** [comment]
@atripathi-mb So i have some problems right here... i updated my mapbox sdk... and heres what i get when using an basic map and the rangearoundtransform tile provider... 

https://imgur.com/a/7ij7t

as you can see theres some sort of pink tiles... but why ?

**Comment by genaray** [comment]
Ok this is solved now... made some stupid mistakes :)
