### ISSUE TITLE
[Unsolved] Reposition a Marker to a new position when the map latitude/longitude is updated.

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#523]
Hey there !

So my player can jump to another position. When the player jumps, the map.Initialize(); method is called with new lat/lng coordinates. The player position is simply set back to Vector3(0,0,0);

My current problem are the other objects in scene... when the map lat/lng position is updated, are staying at the same unity position as before... But they should move to their new updated Unity position which fits the lat/lng position then... Is there an easy way to manage this ? I somewhere saw a ... reposition(); function, but i cant find it ...

Thanks for your time and help !

**Comment by atripathi-mb** [comment]
@genaray 
> My current problem are the other objects in scene 

Are these gameobjects parented to map root? I think making the objects a child of the map root might solve your issue. Also, you can use the map.GeoToWorldPosition or WorldToGeoPosition functions to calculate the position of objects relative to the map.

**Comment by genaray** [comment]
@atripathi-mb  thanks for your support :) I solved it now ! ^^
