### ISSUE TITLE
Custom Vector Tile Layer w/ Prefab modifier positioning issue.

### ISSUE THREAD

**Issue by Havoksien** [mapbox/mapbox-unity-sdk#525]
I created a dataset in Mapbox studio then converted it into a tile set. 
![datasetimage](https://user-images.githubusercontent.com/36059050/35713107-97115ef6-0793-11e8-950f-ef847a94228e.jpg)
Using the Location Provider example I added a custom vector tile layer factory to the "QuadTreeMapVisualizer".  As of right now I'm just creating a prefab using the prefab modifer and on the initial load it works fine.

![loadedprefabs](https://user-images.githubusercontent.com/36059050/35713276-7eea384c-0794-11e8-8534-9ba0b7ce41ae.jpg)

I would expect that when a new tile is loaded due to change in zoom level that the previous prefabs would be destroyed and a new prefab would be placed in the updated location on the new tile.  However when a new tile at a different zoom level loads the prefabs seem to randomly re-position.

![newzoom](https://user-images.githubusercontent.com/36059050/35713467-7342e98e-0795-11e8-821f-85baf2e0b73e.jpg)

 The thing that confuses me the most is that if I return to the previous zoom level that had the prefabs positioned correctly they don't return to the same position.

I'm new to Mapbox so surely I'm just missing something obvious here. Also, after I added the custom factory and pressed play it sticks on the loading screen until I pan over to a tile that contains one of the tile-set points. 

The prefab is just an empty game object with a cylinder in it.

![factorysetup](https://user-images.githubusercontent.com/36059050/35713637-5f559fec-0796-11e8-9acb-e4b9c8214017.jpg)

My Unity and Mapbox versions are both up to date.

**Comment by brnkhy** [comment]
`Also, after I added the custom factory and pressed play it sticks on the loading screen until I pan over to a tile that contains one of the tile-set points.`
I think this is a know issue and you can solve it with one line fix here; https://github.com/mapbox/mapbox-unity-sdk/issues/505 we'll try to merge it in as soon as possible. Just thinking if there's a better way to do it at the moment.

I think @atripathi-mb might help better about the poi positioning in QuadTree

**Comment by brnkhy** [comment]
I'm just looking at that #505 issue and looks like that solution doesn't work anymore. Working on it and will try to fix that asap.

**Comment by atripathi-mb** [comment]
@Havoksien Could you send me a screenshot or details of your VectorLayerVisualizer for me to reproduce the issue, please?

**Comment by Havoksien** [comment]
I've moved away from the vector layer approach and went with loading the prefabs based on lat/long info stored on a custom mongo server then positioning/scaling them using a modified version of Immediatepositionwithlocationprovider. This gave me the desired results as well as the ability to more easily modify the data I'm storing.

**Comment by reubenkcoutinho** [comment]
@Havoksien, can you share an example of how you achieved this. I am looking to do something similar
