### ISSUE TITLE
response.Route returns null or zero when implementing Direction Waypoint in zoomable map using DirectionFactory class.

### ISSUE THREAD

**Issue by arunmozhi9788** [mapbox/mapbox-unity-sdk#526]
* Unity version: 2017.1.0
* Mapbox SDK version: 1.3.0
* The platform you're building to: Android
* A description of what you're trying to do:
I tried to implement the  navigation waypoint using Directions Factory (driver example in mapbox v1.2.0) in zoomablemap in mapbox v1.3.0. I updated the waypoint route at every half change in the zoom level of the quad tree basic map. But sometimes I got zero or null from the response.Route. Is there any alternative methods for waypoint drawing in the zoomable map?.

**Comment by jordy-isaac** [comment]
Hi @arunmozhi9788 and thanks for your patience. Have you checked out the `LocationProvider` example in 1.3? I think this is more along the lines of what you're be looking for. Is there a particular reason that you are wanting to use Zoomable map? The `LocationProvider` example makes it possible to create a zoomable, pannable map that a Player can move around. 

For more info please check out the documentation for this example [here](https://www.mapbox.com/unity-sdk/overview/location-provider/).

**Comment by jordy-isaac** [comment]
Sorry for the late response. If this is still a problem in version 1.4 let us know.
