### ISSUE TITLE
Wrong height in zoomable map

### ISSUE THREAD

**Issue by nolwenn-bigoin** [mapbox/mapbox-unity-sdk#530]
Hello,

I've noticed an error in the height of some tile vertices, somewhere around the city of Nantua (46.156, 5.602), using the ZoomableMap example. It happens at zoom level 13 and above (it's OK at 12).
![image](https://user-images.githubusercontent.com/36228310/35912888-35439cc4-0bfe-11e8-9e51-76cc93b81fef.png)
Could you check this problem ?
Thanks

* Unity version: 2017.1.1f1
* Mapbox SDK version: 1.3.0

**Comment by atripathi-mb** [comment]
@nolwenn-bigoin Are you referring to the big dip in the middle of the terrain in the image above?

**Comment by atripathi-mb** [comment]
@nolwenn-bigoin Duly noted. 
We're currently making improvements to our data pipeline and expect updates on a more consistent schedule in the future. We appreciate you pointing this out to us.

**Comment by nolwenn-bigoin** [comment]
Another question regarding height in the ZoomableMap example. I want to be able to zoom very close and have the best texture quality anywhere in the world. It's working great in places with low altitude, but in places with high altitude my camera is going through the terrain mesh before reaching the maximum zoom level and best quality texture. When the map is scaled, the mesh goes higher since the pivot is in 0, and ends up colliding with the camera. Is there a way of avoiding this ?

**Comment by atripathi-mb** [comment]
@nolwenn-bigoin You can query the height at the location your camera is pointed at and use that to move your camera up or down. 

To queryHeight you can use the following snippet 
```
		public virtual float QueryHeightData(Vector2d latlong)
		{
			var _meters = Conversions.LatLonToMeters(latlong.x, latlong.y);
			var tile = MapVisualizer.ActiveTiles[Conversions.LatitudeLongitudeToTileId(latlong.x, latlong.y, (int)Zoom)];
			var _rect = tile.Rect;
			var _worldPos = GeoToWorldPosition(new Vector2d(latlong.x, latlong.y));
			return tile.QueryHeightData((float)((_meters - _rect.Min).x / _rect.Size.x), (float)((_meters.y - _rect.Max.y) / _rect.Size.y));
		}
```

**Comment by atripathi-mb** [comment]
@nolwenn-bigoin Let us know if you have more questions. closing for now.

**Comment by nolwenn-bigoin** [comment]
Ok, I ended up setting my camera as a child of my quad tree map to solve this scaling / height issue.

**Comment by nolwenn-bigoin** [comment]
I've noticed another error in the height. If I initialize my quad tree map at 40, -3.57, the height is wrong for some tiles at zoom 14 and above : 
![image](https://user-images.githubusercontent.com/36228310/36310565-cf4f0d68-1328-11e8-8b8f-4856c8620bab.png)
(Is this the right place for reporting this issue ? )

**Comment by atripathi-mb** [comment]
@nolwenn-bigoin Duly noted, thanks for pointing this out.
