### ISSUE TITLE
Help with Directions API

### ISSUE THREAD

**Issue by TouqeerAhmad** [mapbox/mapbox-unity-sdk#531]
Hi, I am trying to find a demo/sample where I can use mapbox unity sdk and use directions api. I want exactly what is described in the following link but for unity. Any help in this regards will be great.

https://www.mapbox.com/help/getting-started-directions-api/

**Comment by BergWerkGIS** [comment]
Take a look at the `Directions` scene here:
https://github.com/mapbox/mapbox-unity-sdk/tree/develop/sdkproject/Assets/Mapbox/Examples/7_Playground/Scenes

**Comment by TouqeerAhmad** [comment]
Thank you!
That just give a geojson file but not the route on the map. In iOS native, I was able to use Navigation SDK and get the route from geojson, but I want to do the same using mapbox unity sdk. Like something similar to store locator demo in iOS/android but for unity.

**Comment by BergWerkGIS** [comment]
@TouqeerAhmad this SDK doesn't create a route on the map for you out of the box.
You have to create the game object yourself based on the results of calling the directions API.
You can access the directions API via `MapboxAccess.Directions`.

**Comment by TouqeerAhmad** [comment]
I understand, thanks!

**Comment by david-rhodes** [comment]
@TouqeerAhmad see GameObject `ExampleDirectionsQuery` in `InteractiveStyledVectorMap.unity` scene.

**Comment by TouqeerAhmad** [comment]
@david-rhodes Thank you! that is somewhat relevant but not exactly what I was looking for.

**Comment by BergWerkGIS** [comment]
@TouqeerAhmad what exactly are you looking for?

Example mentioned by @david-rhodes shows how to visualize the response of the directions API:

![image](https://user-images.githubusercontent.com/4549888/36021265-8ed135fc-0d85-11e8-8042-81b2a2647323.png)

And [`DirectionsFactory.cs`](https://github.com/mapbox/mapbox-unity-sdk/blob/v1.3.0/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/DirectionsFactory.cs) that is used by the example scene shows how to work with the strongly typed `DirectionsResponse` that's returned by the query.

Sorry but we don't pass GeoJSON around in SDK.

**Comment by TouqeerAhmad** [comment]
Yes, I understand that -- I am looking into that example and code file you guys have suggested. Thank you both! Is there a plan to release Navigation SDK for unity in future, as I feel that is more mature than Directions API but only available for native iOS/Android.

**Comment by TouqeerAhmad** [comment]
Hi Guys, using your suggested script along with LocationProvider, I am able to hard code start and end lat/long and the path gets high lighted in blue. The location of the user is specified by an anchor. Now, my objective is to get the device location from the location provider -- that gives me one of the lat/long -- the other one i.e. the destination shall be fixed and I want to give directions to the user to reach my asset/destination but using Unity. 

I was wondering if that shall be possible using Directions API and if you can get me some more pointers. 

Essentially want to replicate what is out there using Navigation SDK for iOS

https://github.com/mapbox/mapbox-navigation-ios

I can see some of the same things e.g. Waypoint etc. on both iOS side and Unity side.

**Comment by david-rhodes** [comment]
Instead of using a transform (waypoint) that gets converted to GPS, just use a hardcoded lat/lon for your destination. The queries still operate the same.

**Comment by sahmilcheelan** [comment]
hello,i am a college student and I am working on a project "AR based navigation application for android using unity".since I am new to this field I don't have any idea where and how to start with.and after some research I got to know that mapbox sdk can help me out.and I need almost the same requirements as @TouqeerAhmad wants.like I want the user to enter the desired destination and the application should provide the path to the user as an augmented path on the real world scene captured through the users camera,and I need it in android.
so can anyone help me out?

thanks in advance :)

**Comment by TouqeerAhmad** [comment]
@david-rhodes yes already fixes the two location -- able to get the current location of the user and location I specified for my asset and getting the route highlighter as I shown in the above picture. 

My next step is to get the turn by turn directions displayed to user and with voice as well -- not sure if that is something doable by Directions API -- may be a Navigation SDK for Unity should be there :)

**Comment by david-rhodes** [comment]
@TouqeerAhmad You can get `maneuvers` from the directions response. https://www.mapbox.com/api-documentation/#routestep-object also has lots of information pertinent to navigation. I'm sure the Unity asset store has text to voice assets ready for purchase: https://assetstore.unity.com/packages/tools/audio/rt-voice-48394.

**Comment by TouqeerAhmad** [comment]
Cool, thanks for the continued help!

**Comment by vahidreza** [comment]
hey,
I have downloaded the latest mapbox unity sdk and I could not find a GameObject named ExampleDirectionsQuery in InteractiveStyledVectorMap.unity scene.
I think I have checked almost all scenes but maybe I missed something.

I want to simply draw path on the map based on given coordinates and I do not know how.

thanks

**Comment by richardzzzarnold** [comment]
TouqeerAhmad any chance you could share your code for this? It seems like this is exactly what a lot people are wanting..

**Comment by atripathi-mb** [comment]
@richardzzzarnold @vahidreza 
You can use the files linked below. We no longer have directions in our `Interactive Vector Map` example since we are in the process of creating a new example dedicated to directions. Apologies for the confusion. 

https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Examples/Prefabs/ExampleDirectionsQuery.prefab
https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Examples/5_Playground/Scripts/DirectionsExample.cs
https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/DirectionsFactory.cs

**Comment by richardzzzarnold** [comment]
Hi Abhishek,

Thanks for the swift response.

I managed to get an example going yesterday, the same way you described here, 



which works fin on startup,


however, I am experiencing some difficulty in updating the mesh.
If for example the end point moves, how can I remake the path?

best regards

Richard Arnold

**Comment by atripathi-mb** [comment]
@richardzzzarnold You need to trigger the [Query] (https://github.com/mapbox/mapbox-unity-sdk/blob/f1113fcb89357146209b87880707f79049deafec/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/DirectionsFactory.cs#L52) method when your end points move. Our example is setup to update the direction when map's location/zoom is changed. You will need to write logic to trigger the query when end points move.

**Comment by richardzzzarnold** [comment]
Hi Abhishek,

Thanks for your response, I have it working now.
However, for some reason it works fine in the editor but when I build it to the device it is failing to make the path and I am getting this exception:


NullReferenceException: A null value was found where an object instance was required.
  at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.QueryHeight (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Single& maxHeight, Single& minHeight) [0x00000] in <filename unknown>:0 
  at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.Run (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile) [0x00000] in <filename unknown>:0 
  at Mapbox.Unity.MeshGeneration.Factories.DirectionsFactory.HandleDirectionsResponse (Mapbox.Directions.DirectionsResponse response) [0x00000] in <filename unknown>:0 
  at Mapbox.Platform.FileSource+<proxyResponse>c__AnonStorey1.<>m__0 (Mapbox.Platform.Response response) [0x00000] in <filename unknown>:0 
  at Mapbox.Unity.Utilities.HTTPRequest+<DoRequest>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
In the editor though the map path is there.
Any idea what I am doing wrong here?

-Richard Arnold

**Comment by richardzzzarnold** [comment]
> Hi Abhishek,

Would I be correct in thinking that in unity the scripting backend setting in the Player Settings would need to be selected as Mono instead of IL2CPP?

best regards

Richard Arnold


> Begin forwarded message:
> 
> From: Richard Arnold <richard@impossiblevisions.com>
> Subject: Re: [mapbox/mapbox-unity-sdk] Help with Directions API (#531)
> Date: 15 June 2018 at 12:07:55 CEST
> To: mapbox/mapbox-unity-sdk <reply@reply.github.com>
> 
> 
> Hi Abhishek,
> 
> Thanks for your response, I have it working now.
> However, for some reason it works fine in the editor but when I build it to the device it is failing to make the path and I am getting this exception:
> 
> 
> NullReferenceException: A null value was found where an object instance was required.
>   at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.QueryHeight (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Single& maxHeight, Single& minHeight) [0x00000] in <filename unknown>:0 
>   at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.Run (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile) [0x00000] in <filename unknown>:0 
>   at Mapbox.Unity.MeshGeneration.Factories.DirectionsFactory.HandleDirectionsResponse (Mapbox.Directions.DirectionsResponse response) [0x00000] in <filename unknown>:0 
>   at Mapbox.Platform.FileSource+<proxyResponse>c__AnonStorey1.<>m__0 (Mapbox.Platform.Response response) [0x00000] in <filename unknown>:0 
>   at Mapbox.Unity.Utilities.HTTPRequest+<DoRequest>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
>   at Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () [0x00000] in <filename unknown>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
>  
> In the editor though the map path is there.
> Any idea what I am doing wrong here?
> 
> -Richard Arnold
> 
> 
> 
>

**Comment by BergWerkGIS** [comment]
> Would I be correct in thinking that in unity the scripting backend setting in the Player Settings would need to be selected as Mono instead of IL2CPP?


Yes @richardzzzarnold there currently seem to be some hiccups whenever `JSON` parsing (the directions response from the API) and `IL2CPP` are involved.

Please try again with `Mono`/`.NET` scripting backend.

**Comment by richardzzzarnold** [comment]
Hi 
This is unfortunate as i think you have to have the il2cpp backend to release on ios. 
So does this mean i cant use it on ios ?
-richard

**Comment by BergWerkGIS** [comment]
@richardzzzarnold you are right about IL2CPP and iOS, doesn't work any other way - I mixed that up with UWP/HoloLens where we have troubles with JSON and IL2CPP.

We just did a quick test and directions on iOS worked fined for us.

Could you share your query (start- and endpoint) so that we can check the API response.
Maybe some property is not populated and we are missing a null check.

**Comment by richardzzzarnold** [comment]
Hi Wilhelm,

I just isolated the problem,

in the MeshModifiers array on the DirectionsFactory,I had a LineModifier and a HeightModifier , which I had seen in an example or prefab or somewhere as the way to do it.
I removed the height modifier and it worked.
Not sure if the problem was in the height modifier itself or just that it was in the array without being used.


This is the error message I was getting:



> NullReferenceException: Object reference not set to an instance of an object.
>   at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.QueryHeight (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, System.Single& maxHeight, System.Single& minHeight) [0x00000] in <00000000000000000000000000000000>:0 
>   at Mapbox.Unity.MeshGeneration.Modifiers.HeightModifier.Run (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature, Mapbox.Unity.MeshGeneration.Data.MeshData md, Mapbox.Unity.MeshGeneration.Data.UnityTile tile) [0x00000] in <00000000000000000000000000000000>:0 
>   at Mapbox.Unity.MeshGeneration.Factories.DirectionsFactory.HandleDirectionsResponse (Mapbox.Directions.DirectionsResponse response) [0x00000] in <00000000000000000000000000000000>:0 
>   at Mapbox.Platform.FileSource+<proxyResponse>c__AnonStorey1.<>m__0 (Mapbox.Platform.Response response) [0x00000] in <00000000000000000000000000000000>:0 
>   at Mapbox.Unity.Utilities.HTTPRequest+<DoRequest>c__Iterator0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
>   at Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
>   at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
>   at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
>   at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
> System.Collections.Generic.IList`1:set_Item(Int32, T)
> System.Collections.Generic.IList`1:set_Item(Int32, T)
> System.Collections.Generic.IList`1:set_Item(Int32, T)
>  
> (Filename: currently not available on il2cpp Line: -1)



- best regards


Richard Arnold

**Comment by richardzzzarnold** [comment]
Hi Wilhelm,

Two other queries I have are:

1) The zooming function as demonstrated in  the ZoomableMap scene does not seem to affect a direction waypoint entity.
	Presumably I would need to have to remake the DWE on touch.finished, which isn’t ideal….is it possible to have the DWE scale with the map?

2) I am having a bit of bother updating the device location as I walk around .Does this happen automatically or do I need to make a command to it every second or so? for example in DevciceLocationProvider should I call  PollLocationRoutine every second? Because either way it doesn’t seem to update…. ( its correct on awake though )


best regards 
Richard Arnold

**Comment by BergWerkGIS** [comment]
Maybe @atripathi-mb can chime in on `1.`

@ `2.`

> ... should I call  PollLocationRoutine every second?

No, that should get polled automatically - unless it breaks out of that loop, eg in case Unity couldn't connect to the device's location service.
Check your device logs if you see any errors related to that.


You might want to take a look at the `LocationProvider` example in the `Playground` folder and check if that scene works on your device.

We've seen strange behavior regarding location updates on some devices with wifi on, try this:
* switch off wifi
* reboot the device
* _keep wifi off_ and try again

Also map setup has to be changed when you want continuous updates:
* uncheck `Initialize On Start` under `GENERAL` in `Abstract Map`
* add `Initialize Map With Location Provider` script to your map
* add `Update Map With Location Provider` script to your map


Lastly, could you share your `LocationProviderFactory` and `DeviceLocationProvider` settings?
Eg Unity won't give you location updates if there's a high value in `Desired Accuracy` even when you have a low value in `Update Distance`.

**Comment by richardzzzarnold** [comment]
Hi Wilhelm,, it does seem to work better now that I have followed your instructions, though it is far from perfect.
I think 
> 
> add Update Map With Location Provider script to your map

was the crucial missing bit.

But now I get a new error when zooming in and out from the map .
Also as mentioned before in 1) the directional waypoint entity does not flow with the zoom and pan.

The error I am getting is this:

NullReferenceException: Object reference not set to an instance of an object.
  at Mapbox.Unity.MeshGeneration.Factories.DirectionsFactory.HandleDirectionsResponse (Mapbox.Directions.DirectionsResponse response) [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Platform.FileSource+<proxyResponse>c__AnonStorey1.<>m__0 (Mapbox.Platform.Response response) [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.Utilities.HTTPRequest+<DoRequest>c__Iterator0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Collections.Generic.IList`1[T].set_Item (System.Int32 index, T value) [0x00000] in <00000000000000000000000000000000>:0 
System.Collections.Generic.IList`1:set_Item(Int32, T)
System.Collections.Generic.IList`1:set_Item(Int32, T)
System.Collections.Generic.IList`1:set_Item(Int32, T)
 
(Filename: currently not available on il2cpp Line: -1)


I have no idea what is going on here.

-richard

**Comment by richardzzzarnold** [comment]
Hi Wilhelm,

Also, I should add , that if the app needs to go through these steps
> switch off wifi
> reboot the device
> keep wifi off and try again
in order to function properly, it may not be suitable for this app.
I don’t think I will be able to persuade my customers to do this every time they leave their house.

Perhaps I will need to redevelop my app natively at some time in the future.
 I imagine Mapbox probably prefers Native development.

-best regards
Richard Arnold

**Comment by BergWerkGIS** [comment]
> Also as mentioned before in 1) the directional waypoint entity does not flow with the zoom and pan.

Sorry, I cannot help with that but I already pinged a colleague above. 
He's at a conference this week so will probably get back to you next week.

> Also, I should add , that if the app needs to go through these steps in order to function properly, it may not be suitable for this app.
I don’t think I will be able to persuade my customers to do this every time they leave their house.

Of course not, we don't want to do that either.
I just shared some information we found out the hard way ourselves to save you some trouble and to easily rule out a problem that we've seen pop up intermittently with some Unity versions and some devices.
That's why we even implemented a native Android location plugin: to work around the inconsistent behavior of some 2017.x versions.

>  I imagine Mapbox probably prefers Native development.

Please feel free to take a look at our other SDKs:
https://www.mapbox.com/developers/
https://www.mapbox.com/augmented-reality/

**Comment by atripathi-mb** [comment]
@richardzzzarnold 
> The zooming function as demonstrated in  the ZoomableMap scene does not seem to affect a direction waypoint entity. 

Map and the directions are different entities. Directions response is a set of locations, our example uses the line renderer to draw them for demonstration purpose. You will have to re-draw the direction lines when the map updates, I would suggest using the `OnMapUpdated` event to trigger your direction line redraw.

**Comment by OhioAdam** [comment]
I have a problem that seems fitting for this thread: In the WorldScale AR scene I am able to get the directions route "direction waypoint  entity" to show up in Play mode, but when I build it into an SDK it doesn't show up. Any suggestions?

**Comment by FFilippidis** [comment]
@atripathi-mb 

> we are in the process of creating a new example dedicated to directions

Any update on this by any chance?
Thanks

**Comment by atripathi-mb** [comment]
@FFilippidis Directions example is available in the latest release v1.4.4

**Comment by FFilippidis** [comment]
Hi @atripathi-mb 

Thanks for the fast reply and help. 
Is there an example that shows how to visualise the response of the directions API?

**Comment by OhioAdam** [comment]
@atripathi-mb I tried the new version. The new traffic rendering looks really cool, but the same problems exist in getting the Directions API to show up in WorldScale AR mode on the phone. All of the other map layers I choose to show will show up, just not the Directions route. Do you know who could help with this?

**Comment by atripathi-mb** [comment]
@OhioAdam Could you give me steps to recreate the issue or point me to a sample project/code to help you out. I can't think of any reason why directions will not show up when built on device.

**Comment by atripathi-mb** [comment]
@FFilippidis The traffic and Directions example is visualizing the Directions API response. Are you looking for something else?

**Comment by OhioAdam** [comment]
I'm looking to get the Directions response to show up in AR. I open up the WorldScaleAR Scene, toggle on the Directions GameObject under ArAlignedMap, and get it to the point of showing a directions route from the player's perspective during "Play" mode (it shows up as a GameObject called "directions waypoint  entity"). When I build that scene into an APK and load it on a phone, the building geometries show up, but the "directions waypoint  entity" is nowhere to be seen.

**Comment by FFilippidis** [comment]
@atripathi-mb  Yes it is visualising the responce but i was wondering if there was an example file similar to the earlier one in the InteractiveStyledVectorMap.unity
