### ISSUE TITLE
Re-Add "Drive" example for example usage of Directions API

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#532]
refs #531 

* Unity version: all current
* Mapbox SDK version: 1.3
* The platform you're building to: all
* Steps to recreate the bug if appropriate:
v1.3 is missing the `Drive` example we had in v1.2:
https://github.com/mapbox/mapbox-unity-sdk/tree/v1.2.0/sdkproject/Assets/Mapbox/Examples/Drive

Currently no examples for `Directions` API.

**Comment by david-rhodes** [comment]
Example directions query in: `InteractiveStyledVectorMap`. 😏

**Comment by BergWerkGIS** [comment]
thanks @david-rhodes - your are right:
![image](https://user-images.githubusercontent.com/4549888/36021055-eab6e05c-0d84-11e8-831d-b485f1f56e4a.png)
