### ISSUE TITLE
Performance lags with high values in RangeTileProvider

### ISSUE THREAD

**Issue by morgane** [mapbox/mapbox-unity-sdk#533]
`RangeTileProvider` usually has values of `1,1,1,1` or similar. When you push those to 20+ (`20,20,20,20` or higher), there's a big performance hit and Unity might even crash.

We might want to consider limiting how many tiles we can request, or flashing a warning if we go above a certain threshold.

**Comment by morgane** [comment]
Yes, I thought sliders could work well! I think that would be a better UI than throwing a warning.

**Comment by isiyu** [comment]
👍 to sliders/limiting the max - with built in dynamic loading included in 1.3 there shouldn't be a need to load an area that large.

**Comment by MiroMuse** [comment]
@morgane is this in the current UI design?

**Comment by morgane** [comment]
Closing because this will be added in the latest UI design
