### ISSUE TITLE
I am using Zoomable map configuration to stimulate my plane over real time map. I want to disk cache/store tiles which i have rendered once. I am need to know how i can save those tiles in disk and reload. I am searching for an example or piece of code which implement disk caching.

### ISSUE THREAD

**Issue by husnainyousaf88** [mapbox/mapbox-unity-sdk#535]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by atripathi-mb** [comment]
@husnainyousaf88 Disk caching is built in with the SDK. If you visit an area that was already loaded the tiles will automatically load from the disk.

**Comment by husnainyousaf88** [comment]
1.I am using Mapbox version 1.3
2.Unity 2017.3
3.I am right now building for PC

I am going to explain in detail. I want to fly the plane over a city for example Karachi. I want to download all tiles which map has rendered once, in my disk  i.e resource folder. 
 if I play the game and fly plane over the same location I want to load tiles from disk(i.e resources folder) not from internet. the reason behind this because of high speed of plane sometimes plane fly over tiles but they don't load  textures so I want loading tile fast.

**Comment by atripathi-mb** [comment]
@husnainyousaf88 Disk caching is build-in the SDK, this means when the application is first run the tiles will be cached automatically on your device and the next time you navigate the same area, tiles will be fetched from the disk cache and not downloaded from the internet. You however cannot download tiles and package them in your application, that might not be acceptable for our terms of service. @jordy-isaac can give you details about our ToS.
