### ISSUE TITLE
Location not get updated sometime and after sometime location become good

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#539]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.2.0f3 
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android
* A description of what you're trying to do: 
I'm trying to achieve that location get update after 1 second.
But When I use the app for first 5 minutes location updated perfectly. But after 5-6 minutes location not updated however I'm moving and so device. And after 10 minutes location covered successfully. Why there is a gap of 10 minutes. I didn't understand it.

**Comment by atripathi-mb** [comment]
@asadali26 If you are using the`DeviceLocationProvider` ,  what is the value you are using for `Update Distance In Meters` ?  This setting determines the minimum distance (measured in meters) a device must move laterally before Input.location property is updated. 

If you don't move enough distance the device might not update the location.

**Comment by asadali26** [comment]
@atripathi-mb @MiroMuse  
I'm giving the 0.1 value for distance in meter.
But I can't tell my user to move device laterally to update the location. Is there any other way to overcome this issue.  Thanks
