### ISSUE TITLE
no zooming on slippy map example

### ISSUE THREAD

**Issue by AndrewIK** [mapbox/mapbox-unity-sdk#54]
I've tried to hack it with a _mapController.Execute call from Slippy.cs : Update() and it partially worked but there were a lot of 
MissingReferenceException: The object of type 'UnityTile' has been destroyed but you are still trying to access it.
here and there. I can band-aid it with != null check but I'm afraid it will only mask the actual problem.

If implementing zoom for slippy map is not on the near future roadmap, can you please advise on the right approach to it?

Thank you!

**Comment by david-rhodes** [comment]
@AndrewIK 

>If implementing zoom for slippy map is not on the near future roadmap, can you please advise on the right approach to it?

Thanks for writing the ticket! First of all, a better slippy implementation (including dynamic zoom) is on our roadmap. Currently, though, your best bet to to ensure you reinitialize the factories (as seen in `MapController.cs`). This will clear the internal tile dictionaries. We'll probably add an `Unregister(UnityTile tile)` method to `Factory.cs` to help clean up some of these errors that pop up (remove dependencies of tiles that need to be destroyed or pooled).

We're working on it, but I hope this is enough information to help in the meantime.

**Comment by AndrewIK** [comment]
thanks for the directions, I'll close it now

**Comment by david-rhodes** [comment]
@AndrewIK you may want to look at https://github.com/mapbox/mapbox-unity-sdk/pull/74. There are several performance and architecture improvements. We have not yet implemented zooming, but tiles have a cancel hook now, and the factories should respect that. We will try to add zooming soon!

**Comment by mrgithub** [comment]
+1 for this feature.  Any idea when this will be released?

**Comment by david-rhodes** [comment]
@mrgithub This is already in the SDK in a few forms. You can now reinitialize a `map` component with a different location and zoom level. Additionally, we have a `DynamicZoomMap` which operates much like a basic web map.
