### ISSUE TITLE
Add more links to documentation within Unity

### ISSUE THREAD

**Issue by morgane** [mapbox/mapbox-unity-sdk#540]
As we continue expanding on our documentation, we can start linking to it from within Unity. Specifically:

- in the Config window, we can direct people to tutorials (the same way we direct people to specific examples)
- once an example scene is open, we can use the pop-up to direct people to specific documentation about that example 

This will remain unintrusive for users who don't need extra help, but for those who do this will clarify how to get started and where they can learn more about our SDK.

**Comment by brnkhy** [comment]
also I just realized we don't have reference links (for inspector) set for scripts at the moment;
![unity_2018-02-18_23-29-21](https://user-images.githubusercontent.com/1465390/36356474-92297d1a-1503-11e8-8cf4-7057c39e13f8.png)
you can customize that help button on top right. 
I vividly remember setting that for most classes actually but I guess it's lost somehow, never merged or overwritten somehow :(

**Comment by brnkhy** [comment]
@morgane I found it!
https://github.com/mapbox/mapbox-unity-sdk/tree/helpURLs
so it was never pr'ed and merged. Not sure if we should try to merge now or not (and do it together with all other stuff etc)
