### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by MiroMuse** [mapbox/mapbox-unity-sdk#541]
_Our community has requested more visibility into our product roadmap, so we've published a doc to the repo with detail (PRODUCT_ROADMAP.md). Below is a copy. Feel free to leave comments and thoughts- we'd love to hear them. And as always, we love seeing all of the projects you're building with the SDK, and we're super excited to keep empowering you to do more._

# Mapbox Maps SDK for Unity Product Roadmap

### Overview

The Unity/AR team vision is to enable developers to use Mapbox’s global location data to power immersive, location-based experiences in 3D and world scale AR. 

We want to make our priorities transparent and reliable for our community and we’d love your input. Below is a list of major projects and features currently in active development, upcoming, or we are thinking about long-term.

### Current Roadmap

**Near Term**

*Given the location-based experience and AR fields are new areas of exploration for many developers, our near term goals are to make the process of development in the space intuitive without sacrificing on the full power and flexibility of our tools. In addition, the full potential of AR will be realized at world scale, which will rely on our data to power context. We’re building out the backbone and tools for location context in world scale AR. Expected features include:*

- “Plug and play” templates for major use cases- get a map in a minute or less:
  - Location-based games and experiences
  - City simulation and modeling
  - Location-based AR
- Beautiful out of the box styling templates:
  - Choose from new Mapbox styles or use them as starting points to create your own custom styles for buildings
- More intuitive functionality, less time learning about the SDK and GIS:
  - Surface common functionality into the user interface to speed up the development process and lower the time to ramp up on the SDK and its factories
  - Easier use of POIs for triggering events
  - Easier custom POI import
- Fix split buildings at tile edges
- Improve AR localization as a major step for empowering developers to use our data to create compelling world scale AR experiences
- Continue to improve documentation and tutorials, including creating video-based tutorials

**Medium Term**

- New layers of data designed for location-based gaming & experiences and AR
- Easier procedural and manual mesh & texture styling
- Runtime styling for design efficiency gains
- Simplify external data import and usage
- World scale AR
  - Enable multiuser, persistent AR experiences
  - Optimize for AR drift

**Long Term**

- Computer vision aided world scale AR

___

_Note: This roadmap is for informational purposes only. Placement on the roadmap represents our estimate of when each project will enter production. Items on the roadmap are subject to change or delay, so you shouldn't use this for major planning or purchasing purposes. We'll revise the roadmap at least quarterly to ensure it reflects our most up-to-date thinking._

**Comment by karsnen** [comment]
This is a solid roadmap. Thank you! When can we expect SDK 1.4? I'm excited about it.

**Comment by MiroMuse** [comment]
@karsnen look out for it at the end of the quarter 👍

**Comment by xifarm** [comment]
I'm doning for AR by unity3D.  please tell me ,  when SDK 1.4 will release?
i need to test demo next month.

**Comment by MiroMuse** [comment]
@xifarm it's live now 👌Just go to [mapbox.com/unity](mapbox.com/unity) and follow the install flow.

**Comment by dreamycurrentz** [comment]
I am planning to make AR navigation using Unity. Waiting for it.
