### ISSUE TITLE
Rooftop Uv mapping improvements

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#542]
So far we had two options for polygon UV mapping; (1) tiled uv map and (2) satellite/stretched uv map. And now we're trying to add a third one, atlas texturing. I'll try to briefly explain all here;

![unity_2018-02-19_00-20-52](https://user-images.githubusercontent.com/1465390/36357145-c42d8ba6-150a-11e8-9e16-da1ca4cf345f.png)

Sample texture used in images below;
![atlas5](https://user-images.githubusercontent.com/1465390/36357483-a5c8b082-150f-11e8-96a9-942b216167a0.jpg)

(1) So the first option is `Tiled` which simply assigns x&z value of the vertex position as UV coordinates. This guarantees that the textures will be repeated for each tile seamlessly, so if you create multiple tiles with large landuse polygons and assign grass texture on them using this option, you'll have seamless tiling even at tile edges.
![unity_2018-02-16_15-29-49](https://user-images.githubusercontent.com/1465390/36357369-1d6624e6-150e-11e8-9137-05835b81326c.png)
This image shows it on building roof tops. Each small square you can see there is actually the whole texture on the material and of course this repeating can be tweaking by the `Tiling` property under the material.

(2) Second option is called `Satellite` or stretched. Yea I'm just horrible at naming stuff. This one assumes one corner (of the tile) is (0,0), opposite corner is (1,1) and sets all uv coordinates according to these two. So for example, a point right in the middle of the tile will get (0.5 , 0.5) uv coordinates. This is (at the moment) mainly used for applying satellite imagery on vector feature hence the name `Satellite`.
![unity_2018-02-16_15-30-00](https://user-images.githubusercontent.com/1465390/36357448-2eacdaf0-150f-11e8-85eb-e82090d90512.png)
Base texture (black&white grid) is a little confusing here but that's actually all just one tile and you can clearly see the whole texture applied on all features. If the texture was satellite imagery here for example, those would be satellite building roof tops on those polygons.

(3) And finally we're working on `Atlas` uv mapping these days. It's still experimental but we're hoping to at least release the initial test version as soon as possible. When you choose `Atlas` option, UV modifier will expect an `AtlasInfo` object. This is a new scriptable object we'll be introducing with new styling stuff soon and it simply defines texture segments in an atlas.
So in this  `AtlasInfo` object, you can define which segments are usable for polygons (or rooftops). For simplicity, I defined two uv test segments at bottom right (of that sample texture above) as roof textures. So now system will randomly choose one of those and apply it on each individual polygon (building roof top). 
But how? This is where it kinda gets complicated. It's really not easy to handle and uv map procedurally generated polygons so we needed some simplifications, at least for this initial test and made the assumption that majority of polygons are rectangles. Now it's much easier to apply a square texture on a rectangular polygon. And if assumption is correct and vast majority of buildings in the city are rectangular, all others will just blend in and get lost among others (hopefully).
Unfortunately it's still not easy to fit a texture in a rectangle or a shape close to rectangle (rectangularish? Is that a word?) because of the rotation or additinal sectiongs (i.e. smaller rect on an edge). What we did for this first test is;
- find main axis of the rectangle by v[0] - v[n-1]  (so last edge will be the x axis)
- find the axis aligned bounding box (aabb) using this axis (so it won't be aligned to world x/y, now it's rotated and contains all vertices of the polygon)
- apply texture on this aabb, using minimum vertex (not first!) as (0,0) and max as (1,1)

Result;
![unity_2018-02-16_15-30-49](https://user-images.githubusercontent.com/1465390/36357789-250acfc0-1514-11e8-81da-1cdd3278184f.png)
Ok now I know this looks reaally ugly but I promise it looks quite decent with proper textures instead of that uv test images. I'll try to post something better soon. But still you can see lots of rectangular buildings and their uv mapping clearly. 

Also there are lots of cases it simply doesn't work like; 
- circular buildings (really rare), 
- extremely tall or wide polygons (texture stretches too much) 
- complex shapes

Another interesting case is U or W shaped buidings and you can see a few of them in that shot as well.

@atripathi-mb @greglemonmapbox

**Comment by brnkhy** [comment]
One issue I just realized is, roof tops and side walls are totally independant at the moment and you cannot group them or anything. That's not good and we have to improve that.

**Comment by MiroMuse** [comment]
@brnkhy is a workaround solution ensuring that any sidewall designs match with rooftop designs interchangeably?

**Comment by atripathi-mb** [comment]
@brnkhy 
>One issue I just realized is, roof tops and side walls are totally independant at the moment and you cannot group them or anything. That's not good and we have to improve that.

What do you mean by `group them`? group roof & sidewall into one mesh ?

**Comment by MiroMuse** [comment]
@brnkhy @greglemonmapbox can we close this?

**Comment by atripathi-mb** [comment]
@MiroMuse All functionality already merged into v1.4. Closing this issue.
