### ISSUE TITLE
POI Vector Map does not show POI

### ISSUE THREAD

**Issue by reubenkcoutinho** [mapbox/mapbox-unity-sdk#545]
* Unity version: 2017.3.1f1
* Mapbox SDK version: 1.3.0
* The platform you're building to: iOS/Android
* A description of what you're trying to do:

In the POI Vector map demo, the information canvas says a vector tile map showcasing poi_label markers. But the ClipMapVectorFactory has building as the key instead of poi_label.
Looking at the studio tileset details provided, there is are two different keys: building and poi_label.

How can I see the poi_labels instead of the buildings?

**Comment by reubenkcoutinho** [comment]
So, I replaced "building" with poi_label and it now shows me building shadows on the map. Any way to know what stack to use?

**Comment by jordy-isaac** [comment]
Hi @reubenkcoutinho This can be found in the poi_label source layer of  mapbox-streets-v7  tileset. https://www.mapbox.com/vector-tiles/mapbox-streets-v7/

Also, if you'd like to read a bit more about the examples in the SDK including this one we just launched our new docs page: https://www.mapbox.com/unity-sdk/overview/

I hope that this helps.
