### ISSUE TITLE
TextureSideWallModifier - floor clipping bug?

### ISSUE THREAD

**Issue by demi180** [mapbox/mapbox-unity-sdk#547]
I'm working with the uvMapping branch, and I've run into what seems like a bug. In short, when working with an atlas where the height is divided, for example the included 8-building atlas, there seems to be some "clipping" happening to the mid floors, which seems to correlate to the bottom of the midsection (or the Bottom Section Ratio). The higher up I define the Bottom Section Ratio the more clipping happens. This doesn't seem to be an issue when the texture (the facade) runs the entire height of the atlas.

I've attached example screenshots using the two included atlases unmodified. One shows the 8-atlas in use, highlighting the clipping, and the other shows the 1-atlas, highlighting the correct texture usage.
With the exception of very short buildings that have some intentional extra clipping, building height doesn't seem to affect the amount of clipping that happens.

![sidewall_clip](https://user-images.githubusercontent.com/12224422/36573253-c6923b16-17f4-11e8-8a6d-f403718fa92c.png)
![sidewall_noclip](https://user-images.githubusercontent.com/12224422/36573254-c6aaab4c-17f4-11e8-9e53-076fecdc619a.png)

**Comment by brnkhy** [comment]
@demi180 I thought I replied this before, saw&thought about it earlier but somehow didn't post here.
I think you're right, something looks off. Kinda strange though as it's all based on relative rects anyway so I cannot explain it working with one section but not with multiple.
I suspect maaaybe it's subtracting top or bottom floor offsets twice (from uv coordinates) so cutting out the bottom mid floor. I haven't had a chance to check it though, I'll look into it. Thanks!

**Comment by brnkhy** [comment]
@demi180 I pushed a fix for this on uv mapping branch (https://github.com/mapbox/mapbox-unity-sdk/tree/uvMapping). I think it solves the issue with that mid section uv coordinates but this also reminded me that TextureSideWalls class is quite a mess at the moment and should be rewritten for clarity and stuff. I'll try to look into that soon as well.
Thanks a lot again and please let me know if you find more issues!

**Comment by demi180** [comment]
@brnkhy  Are you sure you pushed it? It's still showing the last commit was on Jan 26

**Comment by brnkhy** [comment]
@demi180 ouch I have no idea what happened to that commit but I couldn't even find that. Pushed it properly this time (admittedly haven't tested it again though). please let me know if it's not working.

**Comment by demi180** [comment]
Works great :)
Side question, is there a way to report buildings with duplicate geometry? Is that even a Mapbox thing?
![duplicate](https://user-images.githubusercontent.com/12224422/36871398-0371aad2-1d57-11e8-996d-0fab3bb781dd.jpg)

**Comment by demi180** [comment]
Another thing, when a building is split between two (or more) tiles, the texturing on it ends up inconsistent. In the example below, the tiny selected piece is on a different tile from the rest. I wonder if there's a way to get and store buildings with a unique ID in order to stay consistent with which facade it gets textured with.

![tile-texturing](https://user-images.githubusercontent.com/12224422/36871822-3f8dd3aa-1d58-11e8-9976-a381e71cabfa.jpg)

**Comment by brnkhy** [comment]
@demi180 unfortunately not at the moment. I think it's more of a mapping problem really. Most stuff in mapping is designed 2d in mind first I guess so we're having such side effects in 3d. We know that issue and working on it though.  Would be great if you can post the lat/lng of that buildings though, I'm trying to keep track a few of those.

That second problem will be solved (hopefully) pretty soon but not much you can do about it at the moment. We'll fix it in such way that you won't need any updates in code or anything though.

**Comment by demi180** [comment]
The building is roughly at:
37°47'33.2"N 122°24'01.6"W
37.792555, -122.400438

I couldn't find a good way to get it from inside Unity so I just pulled up our starting point in Google Maps and set a marker on the building itself, I hope that works. Thanks!

**Comment by MiroMuse** [comment]
Closing this for now, let us know if you need anything else.
