### ISSUE TITLE
Requires internet connection?

### ISSUE THREAD

**Issue by jondyne** [mapbox/mapbox-unity-sdk#548]
Will the apps created using mapbox+unity require an internet connection?

I'm investigating using this plafrom for an App I am developing for Android phone for a pre-defined 3d terrain map. The user may not have access to the internet while using it.

**Comment by jordy-isaac** [comment]
Hi @jondyne thanks for the ticket. With the Maps SDK for Unity you can create offline apps. Our policy for offline maps can be found [here](https://www.mapbox.com/help/mobile-offline/). Please keep in mind that shipping your app with tiles isn't supported in out TOS and your end uses would need to download those tiles to cache.
