### ISSUE TITLE
[Unity]Get list of popular places 

### ISSUE THREAD

**Issue by AlaaDhi** [mapbox/mapbox-unity-sdk#549]
I'm creating a game in unity where i need to spawn objects on map.
I need to get a LatLong list of places like hotels, parks.. ects so i can use the spawnOnMap script.
i know mapbox have this feature but i didn't know how to use it in unity
can someone help me plz

**Comment by atripathi-mb** [comment]
@AlaaDhi `SpawnOnMap` script will be useful if you want to spawn object which are not already available with Mapbox's vector tiles. 

I would suggest looking at the `Explorer` example to see how to use Mapbox data to use places of interest in your application. 

For reference, check out Mapbox vector tiles overview to get an idea of the data that we provide. https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview

If you have further questions, please feel free to contact us.

**Comment by jordy-isaac** [comment]
@AlaaDhi One other good resource would be the `PoiVectorMap` example in the SDK. You can find the documentation for it here: https://www.mapbox.com/unity-sdk/overview/vector-tile-maps/

You'll see that we get the POI data from `poi_label` source layer in the `mapbox-streets-v7 tileset` linked by @atripathi-mb above.

If you want to use your own POI data you can do that as well by adding it by creating a custom [dataset](https://www.mapbox.com/help/add-points-pt-1/#create-a-dataset) in Mapbox Studio

**Comment by AlaaDhi** [comment]
@atripathi-mb @jordy-isaac im sorry if this may look stupid, but i couldn't undrestand what should i do after reading the documentation. im not expert in unity and this is my first project using mapbox.
here is what i did, i imported the mapbox package and i used the location provider example to get the map, then i used the spownOnMap script to spawn few 3D object on it and everything work.
You already know that i should provide lats and Longs to the spownOnMap script so it can do its job, but what i want is to get a list of lats and longs of the near places so i can provide it to the script.
i know its too much to ask for step by step instruction, but it would be much helpful if you can tell me which scripts in the mapbox package that could help me or if there is previous projects in git that have similar fonctions.
thanks a lot

**Comment by atripathi-mb** [comment]
@AlaaDhi 
>what i want is to get a list of lats and longs of the near places

Mapbox Vector tiles provide you this data, you can visualize this data on the map by following this documentation here https://www.mapbox.com/unity-sdk/overview/vector-tile-maps/
For example, as @jordy-isaac pointed out 
>You'll see that we get the POI data from poi_label source layer in the mapbox-streets-v7 tileset

In other words, you don't need to provide the list of lat,longs yourself. `SpawnOnMap` is used for situations when you want to visualize features that are not part of the Mapbox Vector tiles. 

I would suggest looking at examples listed in the documentation above

**Comment by BergWerkGIS** [comment]
@AlaaDhi in case you need more details about POIs you could try `Mapbox.Access.Geocoder` which is a wrapper around: https://www.mapbox.com/api-documentation/#geocoding
