### ISSUE TITLE
Mapbox Meter:UnityUnits

### ISSUE THREAD

**Issue by Regone** [mapbox/mapbox-unity-sdk#550]
Hi there! new to MapBox and I am wondering how can I match the MapBox tile size to unity units so every 1 meter on the map will be equal to 1 Unity unit? (1:1)

tried few other map plugins which i had no problem doing it fast and neatly but because of reasons had to switch up to MapBox

would happy to share any additional information in order to figure it out as fast as we can :)

**Comment by brnkhy** [comment]
@Regone I believe `MapAtWorldScale` is what you're looking for. You can open Basic Vector example and switch `BasicMap` script (on Map object) with `MapAtWorldScale`. It should create a world where 1unit=1meter but becareful you won't be able to load big areas expecially on lower zoom levels because of the floating point precision limit.

And we're working on UI/UX improvements to make this much easier so you'll be able to select this from a dropdown menu or something.

**Comment by Regone** [comment]
@brnkhy Thx for the fast reply!

I did use `MapAtWorldScale` as been suggested in few other issues i've browsed but it gave me unpleasing results and more frustrations as I'm not sure if and how do i set the zoom level right and the unity tile size

but in anyway i try i cannot get to 1:1

**Comment by brnkhy** [comment]
@Regone I don't get what kind of problem are you having. I did a quick test and looked good to me;
![unity_2018-02-27_16-32-28](https://user-images.githubusercontent.com/1465390/36731431-d2b77cb8-1bdb-11e8-82f3-1d46f7ec1eb4.png)
That's a 1unit cube for example.
As far as I remember MapAtWorldScale doesn't use UnityTileSize property, it's a UI mistake I guess.
And zoom level only changes the area size & vector data detail in this case.

**Comment by Regone** [comment]
@brnkhy MapAtWorldScale Does not change the the scaling but does change the amount of tiles it is making all around.
=======

So ill try to visualize it a little more -  lets say for example i want to make a cube between 2 points 
```
(Start - Bottom left)lat: 73.78655  lng: 96.99835 
(End  - Top right) lat: 73.7866 lng: 96.9984 
```
On Mapbox it shows a cube with a scale of x16~ z4.5~ (Meters and or Unity units)
but calculating distance between those points showing that the actual scale of the cube on those coordinates would be **x1.55 z5.6** (Meters and or Unity units)

so i've marked the geo-points with the poi Markers through `SpawnOnMap` referencing my map
and made the cube according  to the distance calculation between those points making sure the cube is aligned to the start point

<img width="534" alt="screen shot 2018-02-27 at 17 01 54" src="https://user-images.githubusercontent.com/454632/36737661-4899dc02-1be4-11e8-85b6-51c5d207af7e.png">

<img width="537" alt="screen shot 2018-02-27 at 17 34 53" src="https://user-images.githubusercontent.com/454632/36737810-9fd69b90-1be4-11e8-928e-7e77dd792098.png">


i hope that helps 😓

**Comment by brnkhy** [comment]
@Regone I'm not able to check it now, I'll probably look into this tomorrow but a quick question, those coordinates are quite up in north right? 
Can you please try with "Use Relative Scale" option in MapAtWorldScale on&off, then maybe same test in a more southern location to see if it's better?

**Comment by Regone** [comment]
@brnkhy Yeah, kinda northish
about here:
<img width="253" alt="screen shot 2018-02-27 at 18 08 52" src="https://user-images.githubusercontent.com/454632/36739787-79a1c0bc-1be9-11e8-8dfe-564fef4206b7.png">

And yeah, I don't know how and why
i was trying to check "Use Relative Scale" **before** Hitting play in UnityEditor (even though i did try to check its effect and saw no changes) it worked like a charm and fits accurately  😬 

Thanks @brnkhy ! 👍

**Comment by brnkhy** [comment]
@Regone ah glad to hear. 
"Use relative scale" takes latitude into account (as tiles actually get smaller and smaller as you move extreme north/south). So I'm not sure but I think it's mercator projection when it's disabled and closer to globe projection when it's enabled or something.
I'm closing this if it's solved for now. Feel free to reopen it if you have any follow up questions. We'll try to make these stuff much more intuitive in next UI improvements.
