### ISSUE TITLE
Issue in Point of Interest Visualization in Unity Mapbox sdk

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#551]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.2.0f3
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android
* A description of what you're trying to do: I'm trying to generate POI on map. I'm also attaching the Mapbox Editor picture. Please let me know If I'm making any mistake. Any help will be much appreciated. Thanks 
![poi mapbox editor](https://user-images.githubusercontent.com/34165125/36786938-10d13088-1caa-11e8-99dc-59bcc6a7773d.PNG)

**Comment by brnkhy** [comment]
@asadali26 I think your layer name is wrong, we don't have a vector layer named `POI` and it probably should be `poi_label`.
I'm not sure if v1.2 has it but latest version includes a "Explorer" demo scene demonstrating how every layer is basically used.

**Comment by asadali26** [comment]
@brnkhy 
thanks let me update the layer name and see what happen.

**Comment by asadali26** [comment]
@brnkhy 
is there a way to add custom POI in my application using mapbox.

**Comment by brnkhy** [comment]
@asadali26 I think best way would be creating a custom tileset on mapbox studio and then consuming that tileset inside the unity sdk and visualizing same way. You can add you custom tileset mapid to vector tile factory (as comma separated value) and use it's layer name for layer visualizer key.

**Comment by asadali26** [comment]
@brnkhy  
Thanks for suggestion. I'll try it. 
By the I update the layer name and it works perfectly 👍 Thanks for the help :)

**Comment by brnkhy** [comment]
@asadali26 no problem! let's close this one then and you can open another issue if you have any problems with other stuff.
