### ISSUE TITLE
MeshCollider components on the map tiles?

### ISSUE THREAD

**Issue by binakot** [mapbox/mapbox-unity-sdk#56]
I use raycasting to place some objects on the 3d map with a correct height. But atm there is no MeshCollider component on the map tiles. That's why raycasting does not work.

![no-mesh-collider](https://cloud.githubusercontent.com/assets/1783893/25829654/3b470f96-3460-11e7-8dd8-46a5c14a7805.png)

If I add MeshCollider in Unity editor when project is playing - everything works. Unity assign the correct mesh in runtime from editor.

![add-mesh-colldider-in-unity-editor](https://cloud.githubusercontent.com/assets/1783893/25829656/40bab2b6-3460-11e7-8d24-efdcfcd2176c.png)

But when I try to add MeshCollider from code, MeshCollider component misses the mesh reference.

![add-mesh-colldider-in-code](https://cloud.githubusercontent.com/assets/1783893/25829661/4a6bf1e4-3460-11e7-9009-fc38dda57895.png)

This code doesn't help.

```
[RequireComponent(typeof(MeshRenderer), typeof(MeshFilter), typeof(MeshCollider))]
public class UnityTile : MonoBehaviour, INotifyPropertyChanged
{
    <...>
    void Start()
    {
        GetComponent<MeshCollider>().sharedMesh = MeshFilter.mesh;
    }
}
```

In earlier SDK versions raycasting worked out of the box. Now I'm using v0.5.1-beta. How can I do it now? 
Thanks.
Cheers.

**Comment by david-rhodes** [comment]
@binakot There are some commented lines in `TerrainFactory.cs` that add `MeshColliders` to the tile game objects. Just uncomment them.

```cs
tile.gameObject.AddComponent<MeshCollider>();
```

Querying tile height is also possible from the `QueryHeightData` method in `UnityTile`.

**Comment by binakot** [comment]
Great thanks! I broke my brain last night. Probably you should to add a check box on terrain factory with "Add mesh colliders" or smth like that? Thanks again. Cheers!

**Comment by brnkhy** [comment]
@binakot `Probably you should to add a check box on terrain factory with "Add mesh colliders" or smth like that?`
I have no idea how I couldn't thought of that before. Doing that right away, thanks!

**Comment by binakot** [comment]
Thanks, guys. Issue may be closed. 🍪

**Comment by brnkhy** [comment]
@binakot not yet! we can keep it till we merge this in; 
https://github.com/mapbox/mapbox-unity-sdk/pull/57
I added both collider and layer settings, will merge it after some testing.

**Comment by binakot** [comment]
@brnkhy Okay-okay. I was not going to do it. Just wanted to say that for my project the problem is solved. 😎

**Comment by david-rhodes** [comment]
Fixed! #57

**Comment by mtbrobotanist** [comment]
hey guys i know this is issue is closed but regarding the QueryHeightData() method, what units does it return? I can't seem to find any info

**Comment by david-rhodes** [comment]
@mtbrobotanist Units are in meters. The returned value will be scaled based on the height modifier of the terrain factory, though.

**Comment by dhruvmodhapp** [comment]
I have added MeshCollider on land-use. But now I have an issue is Mesh Collider 'looks inside hollow'. Due to inside mesh collider is hollow, collision not happening inside. How to make mesh collider solid?
![screenshot 2019-01-24 at 10 24 28 am](https://user-images.githubusercontent.com/46337334/51655524-1f8e1600-1fc3-11e9-91d1-705be4c97aaa.png)
![screenshot 2019-01-24 at 10 30 26 am](https://user-images.githubusercontent.com/46337334/51655525-2157d980-1fc3-11e9-94b7-0cb7bfc0119b.png)
