### ISSUE TITLE
Convert Unity distance (Vector3.Distance) in a real world distance (meters) using DynamicZoomMap

### ISSUE THREAD

**Issue by Maverick87Shaka** [mapbox/mapbox-unity-sdk#562]
Question / Support ticket:

Unity version: 2017.3.0f3
Mapbox SDK version: MapBox 1.3.0 Release
The platform you're building to: Windows Steam VR - HTC Vive and other HMD
A description of what you're trying to do:
I would like to get the real distance in meters between two different game object, and the elevation difference in meter as well. I already know the Vector2d _latLng of both gameobjects, maybe I can query the distance from the mapbox webservices instead converting the current unity Vector3.Distance based on the current zoom level? I can't find any example of that for the Unity SDK, what I would like to create is something like this: https://www.mapbox.com/mapbox-gl-js/example/measure/ in Unity.

Thanks for any idea / tip to achieve this.

**Comment by jordy-isaac** [comment]
Hi @Maverick87Shaka The example you linked is for turf.js. We have cheap-ruler in C# and you can use it for this type of use case. You can find it here: https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/cheap-ruler-cs/CheapRuler.cs#L96-L101

**Comment by Maverick87Shaka** [comment]
I also found in documentation the Distance Method of Vector2d [here](https://www.mapbox.com/mapbox-unity-sdk/api/mapbox-sdk-cs/Mapbox.Utils.Vector2d.html#Mapbox_Utils_Vector2d_Distance_Mapbox_Utils_Vector2d_Mapbox_Utils_Vector2d_).
I made a test with that method and it's returning a double number, it's that a "real world distance"? what is the unit of measurement?
Code:
`Vector2d.Distance (_latLng1, _latLng);` where _latLng1 and _latLng are Vector2d of two different point on map.

**Comment by Maverick87Shaka** [comment]
I take the cheap-ruler-cs from the latest dev build and imported in my projects. It's work and I think I can use it for my purpose.  I just have some "doubt" on how to get other information. I'm taking the distance using the suggested function: `double distMeters = rulerMeters.Distance(new double[] { 12.19531, 43.83663 }, new double[] { 12.22056, 43.83844 });` , how can I get the elevetion in meters of this two point?
Thanks.

**Comment by jordy-isaac** [comment]
We have cheap-ruler-cs in 1.4 of the SDK now. If you're still having issues with this please open this ticket or a new one. Thank you!
