### ISSUE TITLE
#import <MapboxMobileEvents/MapboxMobileEvents.h> 'MapboxMobileEvents/MapboxMobileEvents.h' file not found

### ISSUE THREAD

**Issue by truekit** [mapbox/mapbox-unity-sdk#566]
Hi!

I have created project in Unity with mapbox by this tutorial https://www.mapbox.com/help/unity-mesh-pt-3/ 
in Unity and in android version everything works fine, but in IOS, after building version to Xcode, I have this issue: 

#import <MapboxMobileEvents/MapboxMobileEvents.h> 'MapboxMobileEvents/MapboxMobileEvents.h' file not found 

thanks, for your help

**Comment by atripathi-mb** [comment]
@truekit Check to see in your `PlayerSettings` is the target version is above 8.0 & you use `TargetDevice` as `iPhone Only` or `iPad Only` . Seems like Unity & Xcode issue.

**Comment by apavani** [comment]
@truekit Check if this thread helps
https://github.com/mapbox/mapbox-unity-sdk/issues/301

**Comment by truekit** [comment]
this was helpful thank you!
https://github.com/mapbox/mapbox-unity-sdk/issues/101#issuecomment-305254423

I've added this **header search paths** in Xcode build settings "$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include");

**Comment by RubaXa** [comment]
@truekit Hi, sorry, that writing here, bit I can’t find your a public contact in any way :|
I have a small question for you, please contact me: ibnrubaxa@gmail.com (If it is not hard for you) 🙏
