### ISSUE TITLE
Unity changing map colors

### ISSUE THREAD

**Issue by seddikouaz** [mapbox/mapbox-unity-sdk#567]
I'm creating a game in unity where i need to change colors of streets in map in runtime, or using C sharp scripts, but without using Mapbox studio.
Can someone help me please

**Comment by brnkhy** [comment]
@seddikouaz you can create road mesh & gameobjects using vector data, then change the color of the material from any script you want. As long as the material applied on roads are not `Instanced` (they won't be by default), this'll change the color of all roads.

You can check this on Explorer scene for example. Disable all layers except `road` (you can do that from `Map Editor`) and then change the color of the material applied to roads through inspector.

**Comment by seddikouaz** [comment]
thank you @brnkhy , but im using location provider project.

**Comment by jordy-isaac** [comment]
@seddikouaz You can still use the location provider project and use a custom style you create in Mapbox Studio. Here's a guide on how to do that: https://www.mapbox.com/help/unity-custom-map-style/
