### ISSUE TITLE
Incorrectly reports duplicate Android plugins(and halts build)

### ISSUE THREAD

**Issue by Gusten** [mapbox/mapbox-unity-sdk#570]
Just want to start with saying great work on this SDK!

* Unity version:  2017.3.1f1
* Mapbox SDK version: 1.3.0
* Facebook SDK version: 7.11.0
* The platform you're building to: Android
* A description of what you're trying to do:
The custom prebuild plugin checker in Mapbox_Android_prebuild_checks.cs incorrectly flags Facebook plugins as duplicate due to how AndroidLibInfo.BaseFileName is implemented and Facebook's plugin naming. The issue is on line 84 and the grouping on line 52. In this particular case all Facebook plugins will have the BaseFileName of "facebook".
Is this whole thing really needed btw? My preferred solution would be to just remove this whole file, Since if you actually have duplicate plugins the playresolver will warn you about it. It's not really your responsibility?

* Steps to recreate the bug if appropriate:
Create new project > Import Facebook Unity SDK > Import Mapbox Unity SDK > Build while targeting Android.  

* Links to your logs are also helpful:
DUPLICATE ANDROID PLUGINS FOUND - BUILD WILL MOST LIKELY FAIL!!!
Resolve to continue.
facebook:
	Assets\FacebookSDK\Plugins\Android\libs\facebook-applinks.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-common.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-core.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-login.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-messenger.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-places.aar
	Assets\FacebookSDK\Plugins\Android\libs\facebook-share.aar

UnityEngine.Debug:LogErrorFormat(String, Object[])
Mapbox.Editor.Build.PreBuildChecksEditor:OnPreprocessBuild(BuildTarget, String) (at Assets/Mapbox/Unity/Editor/Build/Mapbox_Android_prebuild_checks.cs:69)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by BergWerkGIS** [comment]
@Gusten 

> Is this whole thing really needed btw? My preferred solution would be to just remove this whole file, Since if you actually have duplicate plugins the playresolver will warn you about it. 

We put the check in there because we faced (pun intended) problems with the Facebook SDK before.

I haven't checked lately but at the time the playresolver just put out some general `CommandInvokationFailure` message and it took some time to trace the failure back to duplicate Android libraries.

> It's not really your responsibility?

Well, I think it kind of is.
If we can provide useful hints of what might prevent you from successfully building I think we should do that.
Saving users and us precious time allowing all of us to focus on our work instead of going back and forth writing/answering tickets.

That said, what do you think about changing the `DUPLICATE ANDROID PLUGINS FOUND` error message to a warning?
Would that work for you?
Or do you have any other suggestions - except removing the whole file  :smirk:

**Comment by BergWerkGIS** [comment]
> Just want to start with saying great work on this SDK!

🙏 Thanks, almost missed that important line 😄

**Comment by Gusten** [comment]
@BergWerkGIS 
Thanks for the fast reply!
I double-checked and you are indeed right about the playresolver. I got it mixed up with the Google Version Handler when adding newer versions of the playresolver. So I apologize about that.

I see what you are getting at with trying to help other developers and I do respect that(Even if it kinda backfired in our case hehe). However, I still believe it might be outside of your scope 😋 But if you can get a properly working check that'd be great ofcourse!

But until it's "perfect" I agree with just making it a light warning or better yet, toggleable. Since it will continue firing a false warning otherwise and I know some will find that confusing.

**Comment by BergWerkGIS** [comment]
@Gusten 
Facebook Unity SDK was the main reason our quick'n'dirty checks were added.
Just tested with the latest version and you are right it now includes Google's Unity Jar Resolver which it didn't have last time I looked and which takes care of resolving duplicates much better.

We also had experimented with the Jar Resolver quite some time ago but were not successful, so we dropped it.

Taking on your suggestion to remove our filename based checks all-together: PR https://github.com/mapbox/mapbox-unity-sdk/pull/574

**Comment by Gusten** [comment]
@BergWerkGIS 
That sounds like a plan 🙂 

Again, thanks for the hard work on this SDK! 👏

**Comment by MiroMuse** [comment]
@Gusten let us know if you need anything else here! Going to close this issue in the meantime.

**Comment by michaelbats** [comment]
@Gusten @BergWerkGIS @MiroMuse  --
So ehrm, I think I'm missing something but what's the actual workaround for this? -- getting the same error about duplicates although I'm sure I have no duplicates. The only plugin installed is a google-sign-in.
