### ISSUE TITLE
What's the deal AR screams errors on new project?

### ISSUE THREAD

**Issue by iiidefektiii** [mapbox/mapbox-unity-sdk#575]
The AR Repository was moved from the old one and says deprecated. I have tried with every attempt and nothing but errors in Unity when trying to incorporate the Mapbox AR files that used to work until it was moved. Mapbox SDK works fine by itself. I am attempting to use the MapboxAR files which are not included in the downloadable version on the site.

* Unity version: 2017.3 F03
* Mapbox SDK version: 1.3
* The platform you're building to: Android (cant even build tho because of all the errors.
* A description of what you're trying to do: Get Mapbox AR to work like the old repository that did.
* Steps to recreate the bug if appropriate: use the instructions on the installation readme
* Links to your logs are also helpful: a ton of different errors on a fresh project.

**Comment by BergWerkGIS** [comment]
> I was doing the update on the wrong directory.

Great, thanks for getting back.

Lets us know when you hit other hurdles.

In case there a lot of errors in the console it makes sense to provide Unity's log files.
They can be found here https://docs.unity3d.com/Manual/LogFiles.html
