### ISSUE TITLE
Coloring specific map sections

### ISSUE THREAD

**Issue by ztdraper** [mapbox/mapbox-unity-sdk#576]
Hello,

I am currently looking into applying colors to specified locations within my custom project and style. Basically, I am attempting to mark certain areas that are enclosed by roads or pathways w/ a color to indicate an affiliation to a custom topic. These markable areas are always bordered on all sides by roads, so the target is the areas within a closed loop of roads, like a city block. I have been messing around with map-box's custom styles and layers and within unity to attempt to recolor these sections and haven't made it very far. My main question is whether this level of detailed control is possible within the layering system and how I may be able to go about it. Would if be possible to create a new tileset that could specify these areas and their current affiliation using a property? 

If I am missing any pertinent information, let me know and I can provide whatever other details or clarification may be needed.

I am unsure if this is the correct venue for this question, but I am working with mapbox in Unity, so I assume this would be a good starting point.

Thank you in advance

![map](https://user-images.githubusercontent.com/35605604/37180516-549efa90-22f7-11e8-930d-5bf5f7e1d87a.png)
![map_marked](https://user-images.githubusercontent.com/35605604/37180519-56477a02-22f7-11e8-8d48-81a531116bbd.png)

**Comment by greglemonmapbox** [comment]
We are planning on adding custom building colorization features into the next version of our SDK which will launch soon. These features may help you achieve what you are trying to do. 

In the meantime, you could try using a polygon modifier to render meshes on top of the map image with a desired color and transparency.

Stay tuned!
