### ISSUE TITLE
Mesh Tangents our of bounds with HeightModifier.

### ISSUE THREAD

**Issue by atripathi-mb** [mapbox/mapbox-unity-sdk#577]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: v1.3.0 develop
* The platform you're building to:
* A description of what you're trying to do:
![image](https://user-images.githubusercontent.com/32286016/37188959-27bc0352-230f-11e8-92b4-a796224a6524.png)

getting this when using `HeightModifier`. Started seeing this after the `uvMapping` branch was merged. 

* Steps to recreate the bug if appropriate:

Use the `InteractiveVectorMap` example to reproduce.

* Links to your logs are also helpful: 

Mesh.tangents is out of bounds. The supplied array needs to be the same size as the Mesh.vertices array.
UnityEngine.Mesh:SetTangents(List`1)
Mapbox.Unity.MeshGeneration.Modifiers.ModifierStack:Execute(UnityTile, VectorFeatureUnity, MeshData, GameObject, String) (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/ModifierStack.cs:191)
Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer:Build(VectorFeatureUnity, UnityTile, GameObject) (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:253)
Mapbox.Unity.MeshGeneration.Interfaces.<ProcessLayer>c__Iterator0:MoveNext() (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:170)
Mapbox.Unity.Utilities.Routine:MoveNext() (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by brnkhy** [comment]
@atripathi-mb I believe we fixed this in SF sprint, before v1.4 release right?

**Comment by atripathi-mb** [comment]
Yup fixed in 1.4
