### ISSUE TITLE
Mapbox Pricing Issue (MAU)

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#581]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.2.0f3
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android
* A description of what you're trying to do:
I'm confuse regarding **MAU** (Monthly Active Users). Because I'm testing Mapbox application in android and I'm only the single user as I'm testing the app before deploy it. 
But when I check the Mapbox statistic it shows me 9 Monthly Active Users. 
Any guidance would be much appreciated thanks

**Comment by jordy-isaac** [comment]
Hi @asadali26. Thanks for the ticket. For account related matters please email us at help@mapbox.com so that we can look into the specifics of your account. For security we can't discuss account matters in a private forum. Thanks!
