### ISSUE TITLE
QueryHeightData

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#582]
* Unity version: 2017.3.1f
* Mapbox SDK version: 1.3.0
* The platform you're building to: Unity
* A description of what you're trying to do:

Hello, I try call QueryHeightData function with my vector2d latlong in my scripts to abstractMap, but fail with the next error:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[Mapbox.Map.UnwrappedTileId,Mapbox.Unity.MeshGeneration.Data.UnityTile].get_Item (UnwrappedTileId key)

Concrete line is: var tile = MapVisualizer.ActiveTiles[Conversions.LatitudeLongitudeToTileId(latlong.x, latlong.y, (int)Zoom)];

I don't understand why, can please help me.
thanks

* Steps to recreate the bug if appropriate:
Only call QueryHeightData(vector2d latlong)

**Comment by atripathi-mb** [comment]
@specsdhdeveloper I am assuming that you are using `FlatTerrainFactory` and that's what is causing the exception. You should be using `TerrainFactory` or `TerrainWithSideWalls` instead. 

We have addressed this issue already in our next release, in the meantime you can change the code to this
```
var _meters = Conversions.LatLonToMeters(latlong.x, latlong.y);
UnityTile tile;
bool foundTile = MapVisualizer.ActiveTiles.TryGetValue(Conversions.LatitudeLongitudeToTileId(latlong.x, latlong.y, (int)Zoom), out tile);
if (foundTile)
{
	var _rect = tile.Rect;
	var _worldPos = GeoToWorldPositionXZ(new Vector2d(latlong.x, latlong.y));
	return tile.QueryHeightData((float)((_meters - _rect.Min).x / _rect.Size.x), (float)((_meters.y - _rect.Max.y) / _rect.Size.y));
}
else
      return 0f;
```

**Comment by specsdhdeveloper** [comment]
Hello, thank you very match for the help.
I have been tested the code, and debug. I understood that "Conversions. LatitudeLongitudeToTileId" return the name of tile to reverse and "MapVisualizer.ActiveTiles.TryGetValue" not find the tile, for exemple if the tiles created into scene is "18/132670/97899" the function "Conversions" return "97899/132670/18".
But I don't see difference if i use FlatTerrainFactory or TerrainFactory, please you can explain me.

Thanks a lot

**Comment by jordy-isaac** [comment]
@specsdhdeveloper, hi there! Please have a look at the `TerrainVectorMap` example in the SDK.

With a `TerrainFactory` a Snap Terrain Modifier is used to snap building meshes to the generated non-linear terrain. Try disabling it by unchecking the Active checkbox on the Snap Terrain Modifier to see what happens. You’ll notice that all the building meshes are rendered under the generated terrain as seen in the image below.

<img width="811" alt="screen shot 2018-03-15 at 11 08 47 am" src="https://user-images.githubusercontent.com/33474236/37482303-4731e8d2-2841-11e8-985d-5cfe0d8ab417.png">
