### ISSUE TITLE
Need to make map static and same location, not dependent on player location

### ISSUE THREAD

**Issue by Jersshhh** [mapbox/mapbox-unity-sdk#583]
Hey there,
I'm looking to create a small scale, static map location game.
So I have my map png here and I need the mapbox map/player location to sync up with this static one.
![capture](https://user-images.githubusercontent.com/9066356/37399836-ad141008-27ce-11e8-948b-914512531181.PNG)
![2](https://user-images.githubusercontent.com/9066356/37399839-af5cca58-27ce-11e8-8d50-d889d7db7fdf.PNG)

Is there anyway to achieve this?

Thanks in advance :)

**Comment by jordy-isaac** [comment]
Hi @Jersshhh Have you tried setting up a NavMesh to constrain the player to the area you want to allow them to go? You could define and set the navigable paths and areas. Here's the Unity documentation on [NavMesh](https://docs.unity3d.com/ScriptReference/AI.NavMesh.html). 

You could also set bounds by restricting the [Transform.position](https://docs.unity3d.com/ScriptReference/Transform-position.html). For example:

```
 if (transform.position.x > 100)
        {
            transform.position = new Vector3(100, transform.position.y, transform.position.z);
        }
```

Hope this helps!

**Comment by Jersshhh** [comment]
Thanks for the response Jordy, however this isn't exactly what I was looking for.

The problem I'm having is that the mapbox map is dynamically loaded in on the app start and places the player at the centre of the screen and generates the map around him. 
I'm looking to create a location game set only in a small area and don't want the game(or map) to work if the player isn't near the games location.

I have created my own custom map which I'd like to use in conjunction with Mapbox to show the player location and to unlock different things based on the player location, but I'm having trouble making sure both maps are always aligned.

I imagine this is achievable I'm just not seeing the solution!
Thanks for any help

**Comment by Skyemou5** [comment]
I am also looking for this solution

**Comment by spaceowlproductions** [comment]
I see this was closed, but was there ever a solution to this?  I know there's a way to "fake" position in the Unity editor, so maybe we can see how this is done in AbstractEditorLocationProvider.cs and reverse engineer it a bit.  My coding skills are definitely a bit low for understanding the complexities of these systems but I will give it a shot!
