### ISSUE TITLE
It's not working on Samsung 8 SM-G950F

### ISSUE THREAD

**Issue by stars66** [mapbox/mapbox-unity-sdk#588]
Unity 2017.3.1
Mapbox 1.3.0
Windows 10

I have built it with only AutomaticWorldSynchronization scene, camera isn't open. I checked camera permission. Other arcore apk(atom visualizer) is working on my phone. Please teach me. thanks

**Comment by BergWerkGIS** [comment]
Which version of ARCore do you have installed on your device?
This SDK is not yet updated to the latest `ARCore SDK v1.0.0` but still has `ARCore SDK Preview 2`.

If you need to downgrade you can find the APK here:
https://github.com/google-ar/arcore-android-sdk/releases

**Comment by stars66** [comment]
Hi Berg Thanks for your reply. I have built your sdk, didn't touch arcore. Should I update ARCore? If so, how can I do it?

**Comment by jordy-isaac** [comment]
Hi @stars66 have you tried again with version 1.4 of the SDK? It's available now: https://www.mapbox.com/unity/

**Comment by BergWerkGIS** [comment]
> camera isn't open.

Have you checked the app's permissions?
Is `Camera` granted?
It should have been requested on first use but maybe that went wrong.

> Should I update ARCore? If so, how can I do it?

Depending on which version of ARCore you are on you might have to downgrade.
The SDK is still on `ARCore SDK Preview 2` and not yet on v1.

As mentioned [above](https://github.com/mapbox/mapbox-unity-sdk/issues/588#issuecomment-373950468) you can get the APK here:
https://github.com/google-ar/arcore-android-sdk/releases

The ARCore version on device should be `0.91.171204143`.

**Comment by nshaposhnik** [comment]
+1, it's not working on Samsung SM-G950F after upgrade to Android 8. Tried both old apk (from mapbox-ar-unity repo), and created new project with version 1.4 of the Mapbox SDK, it's not working. Using  ARCore SDK Preview 2 (version  0.91.171204143). 

I'm trying to launch WorldScaleAR scene (or AutomaticWorldSynchronization for old repo), and what I see is exactly what is seen if launching "play" in Unity Editor, while it should show augmented camera view as I understand (at least that was the case for AutomaticWorldSynchronization in Android 7).

About permissions, APK from old AR repo required "Camera" permission to be granted manually using Settings->Apps->Permissions. Even after granting it manually, it's not working as I already told after update to Android 8. With current 1.4.0 Mapbox SDK, it's different, there's no "camera" permission at all in list, only permission for "Location" can be granted.

**Comment by apavani** [comment]
@nshaposhnik 
Can you confirm if the ARCore supported checkbox is checked in the Player Settings in Unity while building out the apk?
<img width="415" alt="screen shot 2018-04-01 at 4 46 23 pm" src="https://user-images.githubusercontent.com/8422708/38178664-48605dae-35cc-11e8-8a41-ef8744c9b564.png">

**Comment by nshaposhnik** [comment]
That was it, missed checkbox, thank you, 1.4.0 now works. Old APK from mapbox-ar-unity have this enabled and is not working, but that repo is deprecated after all.
