### ISSUE TITLE
Is there a way to use Geocoding in unity applications or server side ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#590]
Hey there !

Im currently struggling with a iusse. I need to do GeoCoding to determine if a LatLng point belongs to a certain country, or if the Lat/Lng point is in the water for example. It would be pretty interresting to get the area temperature aswell. 

I would prefer to do this server side with the mapbox Java api, but otherwise i need to do this client side... Is there a way to do this ?

**Comment by BergWerkGIS** [comment]
@genaray this SDK has wrappers for Mapbox's server side geocoding.
Take a look at the scenes `ForwardGeocoder` and `ReverseGeocoder` here:
https://github.com/mapbox/mapbox-unity-sdk/tree/v1.3.0/sdkproject/Assets/Mapbox/Examples/7_Playground/Scenes
