### ISSUE TITLE
Do custom Map IDs really work in Mapbox SDK for Unity? 

### ISSUE THREAD

**Issue by vetvennarost** [mapbox/mapbox-unity-sdk#591]
Hi!

Unity Personal 2017.3.1f1
Mapbox SDK 1.3.0
Mapbox Studio
WebGL

I'm totally newbie to Mapbox SDK for Unity so I apologise if my question seems silly. 
But when I put my own Map IDs (from any of my custom tilesets made in Mapbox Studio) to VectorTileFactory script instead of, say, "mapbox.mapbox-streets-v7" Map ID in a sample like InteractiveStyledVectorMap and press 'Play' - I always get several mistakes like this one:

1 Exception(s) caused on the tile. Tile ID:16/39603/20527 Tile Type:Mapbox.Map.VectorTile
Status Code 404
UnityEngine.Debug:LogError(Object)
Mapbox.Unity.Map.TileErrorHandler:_OnTileErrorHandler(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/TileErrorHandler.cs:52)
Mapbox.Unity.Map.AbstractMapVisualizer:Factory_OnTileError(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:233)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:72)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:133)
Mapbox.Unity.MeshGeneration.Factories.<OnRegistered>c__AnonStorey0:<>m__0() (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:99)
Mapbox.Map.Tile:HandleTileResponse(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:230)
Mapbox.Platform.Cache.<Request>c__AnonStorey0:<>m__0(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:160)
Mapbox.Unity.Utilities.<DoRequest>c__Iterator0:MoveNext() (at Assets/Mapbox/Unity/Utilities/HTTPRequest.cs:65)
Mapbox.Unity.Utilities.Routine:MoveNext() (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I hope that my secret token has right permissions because my custom Style IDs work great. So I guess the problem is that my tilesets somehow do not match Unity's scripts/samples' demands.

Am I right? Or the problem is bigger and Mapbox SDK for Unity simply does not support custom Map IDs at all?

I derive my datasets from OpenStreetMap as *.geojson via overpass-turbo.eu, edit them in Mapbox Studio and then export them as tilesets. So I prefer to work with them instead of usual (and rather wrong) OSM data.

Or may be there is another way to import my vector data directly into Unity?

Thanks!

**Comment by vetvennarost** [comment]
Hi, guys!

In ver. 1.4 this mistake disappeared, so I can now put ID of my custom tileset made in MapboxStudio into the Vector section of my Map Vizualizer instead of Mapbox Streets or Mapbox Streets With Building Ids.

But now the problem is that it can not fetch any data from my custom tileset.

The idea was to choose only certain OSM objects for my map, to make a dataset with it in MapboxStudio, to export it to a tileset and then to use it here so that Unity could show only chosen objects on my map. But it seems now that my custom tilesets do not match Unity.

How to fix it? May be there is a particular protocol for tilesets or some specific tags which I should mark when making a dataset?

**Comment by BergWerkGIS** [comment]
@vetvennarost the log message in your first post show a `Status Code 404` error which means either the tileset or the requested tile did not exist at that time.

As for your second post: do you get any errors in the console?

**Comment by jordy-isaac** [comment]
Please reopen this ticket if you're still having issues and let us know of any console errors. @vetvennarost
