### ISSUE TITLE
IOS backgroundworker crash or not…

### ISSUE THREAD

**Issue by contactzed8** [mapbox/mapbox-unity-sdk#592]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by contactzed8** [comment]
Hi. Trying to build a simple scene with custom dataset. Crash when launching on the iphone. Sometimes yes, sometimes not and I don't know why. Please help.
<img width="1512" alt="capture d ecran 2018-03-17 a 21 50 51" src="https://user-images.githubusercontent.com/35663042/37580413-d22bb2ba-2b43-11e8-9546-1d99e990055b.png">

**Comment by atripathi-mb** [comment]
@contactzed8 Are you running with `Dynamic Batching` turned on in your player settings? Try turning it off and check if that fixes the crash.

**Comment by contactzed8** [comment]
Thanks for your reply. Dynamic Batching turned off, I did not try before but only working the first time the application is launched and previous version erased. If I quit and try to reopen it, it doesn't work anymore. grrr…

**Comment by ztdraper** [comment]
I have experienced this issue several times recently as well. It usually works again after I run through the build process once or twice more, but this is all with "Dynamic Batching" always off.

**Comment by contactzed8** [comment]
No way, can't resolve the crash…

**Comment by contactzed8** [comment]
Do work now with 1.4
