### ISSUE TITLE
Correlation between height values and real world elevation?

### ISSUE THREAD

**Issue by str11ngfello** [mapbox/mapbox-unity-sdk#598]
I'm finding great success translating between lat/lngs and X,Z coords in unity world space thanks to the many great links I've found and the Conversions APIs that are part of the SDK.  I'm plotting points in the map and having a DJI drone fly them in the real world.  There's only one problem, I am hard-coding the altitude.  :)

I can raycast and determine a scaled height on the terrain. (sometimes negative for example, -.37823) But, how can I actually get the Mean Sea Level height for a lat/long coordinate?  Is this information even available in the SDK? I'm not sure what to make of QueryHeightData.  How does the height data correlate to the real world elevation at that lat/lng?  

I can express my flight altitudes in terms of relative altitude to a known elevation I suppose, maybe even hit the google elevation API to for a particular lat/lng and build relative heights from there using the map's relative scale.  I guess I'm just wondering what, if any, correlation can be made between height values in MapBox SDK and real world elevation.  Or, do you suggest I keep altitude expressed in terms of deltas relative to a known take off elevation.

Thanks for a great SDK btw

**Comment by apavani** [comment]
@str11ngfello We released a new version of our SDK last week.
We added a couple of new methods that might help you:
In AbstractMap we have `QueryElevationInMetersAt` & `QueryElevationInUnityUnitsAt` methods
Also, `GeoToWorldPosition` can return the elevation in unity units for a lat long.

Let us know if that helps
