### ISSUE TITLE
Map at World Scale does not load

### ISSUE THREAD

**Issue by ryanmeasel** [mapbox/mapbox-unity-sdk#599]
* Unity version: 2017.3.0f3

* Mapbox SDK version: 1.3.0, as of 12/08/2017

* The platform you're building to: Unity Editor

* A description of what you're trying to do: 

I am trying to load a vector tile map at world scale using the provided "MapAtWorldScale.cs". The map will not load. The loading screen continuously appears. All the settings were precisely the same as the `BasicMap` component and no other modifications were made. 

![screenshot 2](https://user-images.githubusercontent.com/186849/37677828-66f93994-2c39-11e8-918e-8895972f8e7a.png)

* Steps to recreate the bug if appropriate: 

1. Load `Mapbox/Examples/4_VectorTileMaps/BasicVectorMap`.
2. Replace the `BasicMap` component on the `Map` game object with the `MapAtWorldScale` component.
3. Run the Unity Editor.

**Comment by jordy-isaac** [comment]
Hi @ryanmeasel we recently upgraded to version 1.4. Please let us know if you run into trouble after upgrading. You can get the latest version here: https://www.mapbox.com/install/unity/
