### ISSUE TITLE
ARKit tabletop example in v1.4 - How to set the arkit scene as mentioned in the info panel

### ISSUE THREAD

**Issue by Vinita18** [mapbox/mapbox-unity-sdk#603]
For AR examples to work as expected, please add layers with the following names 

ARGameObject
Map
Path
Both

How to add this???
any idea?

**Comment by atripathi-mb** [comment]
@vinita18 you can add layers in the Unity Editor under Edit->Project Settings ->Tags and Layers.
This might be useful - https://docs.unity3d.com/Manual/Layers.html

**Comment by Vinita18** [comment]
@atripathi-mb  I have added layers there but nothing changes. In unity editor, the map is generating but on the device, just a blue place is there. In the scene they have mentioned in info canvas that For AR examples to work as expected, please add layers with the following names
ARGameObject
Map
Path
Both

But now which layers do I need to add?? wether vector layers under abstract map script in the inspector???

**Comment by atripathi-mb** [comment]
@Vinita18 
>But now which layers do I need to add?? whether vector layers under abstract map script in the inspector???

You need to add Unity Layers. Vector layers are for adding features to your map. 

Could you give us some more details - 
Which device are you using ?
Which Unity version 
Which device OS version. 

Steps to recreate the issue will be helpful as well.

**Comment by jordy-isaac** [comment]
@Vinita18 Are you still having trouble? If so please reopen this ticket and let us also have a look at your build and player settings.

**Comment by Rusnomad** [comment]
Hello Everyone! I have the same problem. 

> I also have added layers there but nothing changes. In unity editor, the map is generating but on the device, just a blue place is there. 

- I am using Macbook Air, IOS Lion
-I use Unity 2018.2.2f1
-MapboxSDK v1.4.4
-Device that I try run on is Iphone 6s ios 11.4.1

Please help? Thanks.

**Comment by sahrilhasan** [comment]
Hello Mr. @abhishektrip can you give me toturial for beginner about worldscale unity mapbox?
