### ISSUE TITLE
What is the values of "Range Height"

### ISSUE THREAD

**Issue by dingfengboo** [mapbox/mapbox-unity-sdk#605]
0.1 - 0.5
10 - 100
Two set values are all the same result.

![svjz _ s c9 koq_ku gus6](https://user-images.githubusercontent.com/34928957/37763910-4fc456b4-2dfb-11e8-8ed1-244796959240.png)

![d22 ecj m cf w irlj0tzc](https://user-images.githubusercontent.com/34928957/37763877-2e44e44a-2dfb-11e8-8f57-f00edc031d22.png)

**Comment by atripathi-mb** [comment]
@dingfengboo Thanks for pointing this out. #613 Will fix the issue.
