### ISSUE TITLE
ARDelta not registering

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#607]
* Unity version: 2017.3.1f1
* Mapbox SDK version: 1.4.0 release (commit db2468047e6a83bd7c21a1a5f3481427102fe06e)
* Building to: ios 11.3 (iPad pro)

Thanks for the updates in sdk 1.4.0! I see some very welcome updates. However I'm having some issues with the provided examples

Trying out the new WorldScaleAR example, It seems the AR synchronization nodes are not registering in the SynchronizationContext. In the console, I constantly get the message:  "minimum movement not met yet (arDelta 0, gpsDelta _somenumber_ )

The gps delta seems to be registered properly and increases as I walk, but the arDelta stays 0.

The terrain does not move according to the detected location and heading (which seem to be correct judging from the logs) so the generated environment does not match the real one. 

I can enclose a video of a test run if necessary.

**Comment by BergWerkGIS** [comment]
@specsdhdeveloper do you see any blue AR planes or yellow dots in the AR view.
Looks like AR cannot find anything to hold on to.

A video would be greatly appreciated. 🙏

**Comment by specsdhdeveloper** [comment]
Here goes : https://youtu.be/ddhPcy99pm4

**Comment by pierotofy** [comment]
Noticing the same problem (using latest `develop` branch). I think the reason is that AR deltas are computed from the AR Root's object transform, but AR Root's transform is never updated?

**Comment by ProfHorse** [comment]
Regarding the blue planes not being detected, I noticed that the default WorldScaleAR scene's Main Camera does not have the culling mask set to show the Unity layer in which the AR planes are drawn on. Checking the ['ARGameObject' layer](https://i.imgur.com/vCDIJ9t.png) shows the planes for me, as shown in the image.

I too am experiencing the ARDelta 0 "Minimum Movement" issue.

**Comment by specsdhdeveloper** [comment]
@BergWerkGIS That did the trick indeed. Thanks!

**Comment by BergWerkGIS** [comment]
@specsdhdeveloper great to hear.
Thanks for getting back.
