### ISSUE TITLE
Mapbox cannot reinitialize map while using unity's builtin network api

### ISSUE THREAD

**Issue by timgoeij** [mapbox/mapbox-unity-sdk#609]
Hi, 

In Unity I have built a server with unity's own network functions, while the server is on and I am trying to reinitialize the map to see another location,  the map dissapears and comes not back. If I look in the hierachy  under the root of the map I cuian see that the childs continuously  changing and never becomes active.

steps to recreate bug:
1: create a host with unity newest networking API
2: create a map with mapbox, set the option initialize from start, and gives it a networkidentity with the setting localplayerauthority
3: press play, start the server and wait for that the map is initialized.
4: Intialize the map again or reset the map.

Unity version 2017.3.0f3
Mapbox-unity-sdk 1.3.0

At the moment building windows standalone, and I got no logs when this is happening.

I hope you can help me.

**Comment by atripathi-mb** [comment]
Hi @timgoeij , Could you provide us with some more details on how to reproduce this issue. 
Screenshots or videos showing the setup will be great.

**Comment by timgoeij** [comment]
hi @atripathi-mb , the first issue I had was when unity start the host and I choose from a dropdown list a new location after the map was initialized. The map dissapears and when I look in the hierachy under the map gameobject I saw the map was continuous adding and removing tiles without setting a tile active.

In the time between creating this is issue and your response I found a workaround to put the new location in the UpdatMapProperties function in the QuadTreeCameraMovement script and that works my very well.

When trying to reproduce the bug for you. The bug changed. T

he map wil initialize without the loading problem I had first. But now the map let see the new location for a short time and goes back to the old location while loading extra buildings. You can see it the video.

https://we.tl/N3buPmjBKm link to a zip file with screenshots of the map gameobject, map editor, networkmanager gameobject and the video with the bug

**Comment by atripathi-mb** [comment]
@timgoeij I see that you're using v1.3 of our SDK. Have you tried using the latest version 1.4?
We made a lot of improvements to our SDK and added a new UpdateMap method to the abstract map which should take care of the workaround that you had to do with `UpdateMapProperties` on CameraMovement Script. 

>he map wil initialize without the loading problem I had first. But now the map let see the new location for a short time and goes back to the old location while loading extra buildings. You can see it the video.

To debug this issue, I would need to know details on how you update map to the new location ? With 1.4 I would encourage you to look at `ReloadMap` script.

**Comment by timgoeij** [comment]
@atripathi-mb I haven't tried 1.4 yet. And I am going to look at 1.4. 

> To debug this issue, I would need to know details on how you update map to the new location ?

This is how I update the map before using the workaround after unity start the host.

` void Awake () {

        basicMap = FindObjectOfType<MapboxQuadTreeBasicMap>();
        mapboxQuadTreeCameraMovement = FindObjectOfType<MapboxQuadTreeCameraMovement>();
        UIDropdown.AddOptions(dropdownValues);
        UIPanel.gameObject.SetActive(false);
        basicMap.OnInitialized += OnMapInitialized;

       
	}

    void OnMapInitialized()
    {
        UIPanel.gameObject.SetActive(true);
        UIDropdown.onValueChanged.AddListener(OnLocationMapChanged);
    }

    private void OnLocationMapChanged(int index)
    {
        string newLocation = dropdownValues[index];
        basicMap.Initialize(Conversions.StringToLatLon(newLocation), basicMap.AbsoluteZoom);


        
    }

    private void OnDestroy()
    {
        basicMap.OnInitialized -= OnMapInitialized;
        UIDropdown.onValueChanged.RemoveAllListeners();
    }`

**Comment by jordy-isaac** [comment]
Closing this issue. If it's still an issue with the latest version of the SDK, please write back and let us know, @timgoeij
