### ISSUE TITLE
Vector Data State suddenly start showing error. Only load few tiles.

### ISSUE THREAD

**Issue by asadali26** [mapbox/mapbox-unity-sdk#611]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.2.0f3
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android
* A description of what you're trying to do: 
I'm using Mapbox Unity sdk. It works fine but now suddenly Vector Data State showing error and load only few tiles. I'm unable to figure out what happen wrong. 
When I build scene in Editor. I also get this error
Assertion failed: Assertion failed on expression: '!(GetPersistentManager().IsStreamLoaded(pathName) && !GetPersistentManager().HasMemoryOrCachedSerializedFile(pathName))'

Any help would be much appreciated. 
Thanks

**Comment by jordy-isaac** [comment]
Hi @asadali26 Thanks for the ticket. Can you let us know how we can reproduce this? Do you have any screenshots of what you have configured in the map editor? You can open the map editor from Mapbox > Map Editor from the Unity Editor at the top menu.

**Comment by asadali26** [comment]
Hi @jordy-isaac 
Yeah I can share the Mapbox Editor Screenshot with you. 
Here you go 
![mapbox editor](https://user-images.githubusercontent.com/34165125/37911121-a518fbe4-3128-11e8-8697-9e3e0b52d194.PNG)

**Comment by BergWerkGIS** [comment]
@asadali26 The error your are experiencing is most likely related to Unity itself and/or your setup and not our SDK. 

If you search the internet for your error you'll find a ton of proposed solutions, eg
* excluding Unity from your Antivirus
* deleting the `Library` folder
* reimporting all your assets
* starting Unity as administrator
* ...

If you find a solution that works for you it would be great if you could post back here for posterity.
