### ISSUE TITLE
`Point` Layers are always placed on tile center

### ISSUE THREAD

**Issue by jim-martin** [mapbox/mapbox-unity-sdk#615]
Layer visualizers with primitive type `point` always appear at tile center, rather than the feature's location. Feature placement options don't seem to have an effect.

Reproduction steps:
1. Create a new abstract map in a new scene
2. Add a new Vector Layer Visualizer
3. Setup the layer visualizer like this:
![screenshot 2018-03-26 17 36 43](https://user-images.githubusercontent.com/9599047/37940212-4c2b3be8-311c-11e8-9244-ad8085180556.png)
*Primitive Type: Point
*Feature Position: First Vertex
4. Play the scene and select any poi_label generated on the map, it should appear at tile center.
5. Exit play mode and adjust the `Feature Position` option, every setting produces the same result.

The feature position options supplied seem focused on polygons, could more clear `Point Position` and `Tile Center` options be provided?

* Unity version: 2017.3
* Mapbox SDK version: 1.4

**Comment by atripathi-mb** [comment]
@jim-martin We should document this 😄

**Comment by MiroMuse** [comment]
@jordy-isaac @morgane see above - we should document this.
