### ISSUE TITLE
Using the location-based game example with free-look camera

### ISSUE THREAD

**Issue by HEATH3N** [mapbox/mapbox-unity-sdk#616]
Can we get an option to load a maximum of X tiles away from our current position instead of whatever the current implementation is that crashes Unity when using a free-look camera because it causes a million different tiles to load?

Changing the player to "walk" with WASD would help also; it's kind of a pain to use the coordinates.

These were both welcome features in MapzenGo

**Comment by jordy-isaac** [comment]
Hi @HEATH3N. Have you tried adjusting the `Extent Options` on the `Map` game object? I would suggest `Range Around Transform`. Then you can set the `Visible Buffer` and `Dispose Buffer for the tiles that are loaded. However, please keep in mind that this example is best for looking at real world map data from a top-down view, like a paper map. It is less appropriate for building 3D scenes with a more flexible camera view. 

Thanks also for the feedback on the character controller.

**Comment by HEATH3N** [comment]
Oh wow, completely missed that. Sorry to waste your time!

**Comment by atripathi-mb** [comment]
@HEATH3N I would also suggest looking at the `RangeAroundCenter` option as well.

**Comment by dulajdanu96** [comment]
i follow a tutorial on location based game in mapbox but when i hit play in unity editor my character move.how to stop it from moving.

**Comment by heath3n** [comment]
A closed issue about a separate topic isn't the best place to ask, but to answer your question anyway: Disable the location scripts on the player object.
