### ISSUE TITLE
Access Token Invalid

### ISSUE THREAD

**Issue by mizhdi** [mapbox/mapbox-unity-sdk#617]
Getting invalid token error.

**Comment by brnkhy** [comment]
@mizhdi I deleted the picture as you shouldn't share your mapbox key publically like that.
Have you checked it you copied it properly without any empty space at the begining or the end?

**Comment by mizhdi** [comment]
@brnkhy 
May be Great Firewall (of China) caused this

**Comment by brnkhy** [comment]
@mizhdi I'm not sure, I believe we have users in China but let's see if someone else knows better about this. 
Thanks for the report!

**Comment by BergWerkGIS** [comment]
@mizhdi any error messages in the console after entering your access token and pressing `Submit`?

**Comment by mizhdi** [comment]
There is a problem with the company’s network and it’s done at home  @BergWerkGIS

**Comment by SixGodZhang** [comment]
The Token is sometimes valid and sometimes unvalid. In China .

**Comment by Programmer9936** [comment]
The problem is still there...trying from last 2 days, deleted my account and made a new one, but no luck...on unity SDK

**Comment by adrianjmejias** [comment]
hey is there any solution for this problem yet??? I live in Venezuela and I have the same issue.
another thing that I did was migrating from old mapbox to new mapbox but I don't think it's related

**Comment by SixGodZhang** [comment]
@adrianjmejias In our place,it's maybe Great Wall,don‘t know if there is wall in Venezuela .But we use the offline map

**Comment by chenaptx** [comment]
Have you solved this? I meet it as well. With the token being checked as invalid, I cannot continue my project.

**Comment by peter-hamilton-MOH** [comment]
I set the HTTPS_proxy environment variable to http://{proxyIP}:{port} (with valid proxy of course) and that fixed it for me.

**Comment by Alvarden15** [comment]
Now it's happening to me now too here in Peru. And that's strange, because days before, it worked just fine.  What may cause it?

**Comment by peter-hamilton-MOH** [comment]
Trying restarting Unity and also if you're behind a firewall setup your HTTPS_proxy environment variable. I've noticed I need to restart Unity every day or so - not sure what's going on there.

**Comment by jefffhaynes** [comment]
I'm in the US.  Same problem.

**Comment by SergeyLibin** [comment]
Ukraine and US also facing this error. 
Created the new account with the new tokens but still get this error.
`Invalid Token" UserInfo={NSLocalizedFailureReason=Not Authorized`

**Comment by StarKing777** [comment]
> I set the HTTPS_proxy environment variable to http://{proxyIP}:{port} (with valid proxy of course) and that fixed it for me.

Hey peter, I am kind of new to this, how would I go about ding this an din particular how would I create or find a valid proxy.

Thanks for the help.

Kind regards,

Jesse

**Comment by hdsb-on** [comment]
Hey Jesse, if you're in a corporate/government environment talk with your network admin otherwise there's online services that you can google.

**Comment by StarKing777** [comment]
> Hey Jesse, if you're in a corporate/government environment talk with your network admin otherwise there's online services that you can google.

Hey there, thanks for your response, I am using this in my own personal capacity.

do you mean there are online services that can help me set up a proxy?

Kind regards,

Jesse

**Comment by hdsb-on** [comment]
Yup - strange that you would need a proxy from your own personal connection though - unless you're in a country with a nation-wide firewall imposed on the citizens. Just google proxy services, and you'll find something - just remember though that the free ones are likely saving your data if you care about that

**Comment by StarKing777** [comment]
> Yup - strange that you would need a proxy from your own personal connection though - unless you're in a country with a nation-wide firewall imposed on the citizens. Just google proxy services, and you'll find something - just remember though that the free ones are likely saving your data if you care about that

Thanks a lot, I really appreciate you taking the time to educate me on this.

I am not even sure if I need a proxy but my MapBox SDK keeps telling me I have an invalid access token so I have spent the last two days trying to trouble shoot this.

I am using my phones hotspot connection for my PC so I wonder if that has anything to do with it.

Ill give that a try.

Kind regards,

Jesse

**Comment by adrianjmejias** [comment]
Well, I solved it using my phone's data instead of my work's internet.
Around that time at work I had to fill a lot of captchas all the time, even for google searches. I my work's IP was blacklisted by google or something like that.
When I switched and used my phone's data it was all fixed.

**Comment by StarKing777** [comment]
> Well, I solved it using my phone's data instead of my work's internet.
> Around that time at work I had to fill a lot of captchas all the time, even for google searches. I my work's IP was blacklisted by google or something like that.
> When I switched and used my phone's data it was all fixed.

Congrats on getting it working bud, I really wish I was you at this moment in time because this is frustrating the hell out of me.

I am using a mobile hotspot and it gives me this invalid token error no matter what I try do.

I wonder if my phone is acting as some sort of proxy that is interfering with the connection.

I have a Gomaps asset which uses Mapbox tokens and it works perfectly well with no errors but when I try use the Mapbox SDK directly it always gives me an invalid token error.

I wonder if using a wifi connection might help this, Mapbox support is so slow...

**Comment by kantarjack** [comment]
Am able to use same access token with browser, but getting response.text
Out[49]: '{"message":"Not Authorized - Invalid Token"}' when trying to access it using python.
