### ISSUE TITLE
Is it possible to make a 3d map of China

### ISSUE THREAD

**Issue by mizhdi** [mapbox/mapbox-unity-sdk#620]
I am a newcomer and have no way to start

**Comment by jordy-isaac** [comment]
Hi @mizhdi! Happy to help. It's very possible. The first thing to do would be to download Unity and Our Maps SDK for Unity.

Mapbox Maps SDK for Unity: https://www.mapbox.com/install/unity/
Unity 2017.3.1: https://unity3d.com/get-unity/update

Then if you check the examples folder for the `InteractiveStyledVectorMap` example where you can enter in any location you want to view. You could also check out this tutorial on how to get started and create your own map https://www.mapbox.com/help/create-a-map-in-unity/
