### ISSUE TITLE
issue in integration of mapbox in unity

### ISSUE THREAD

**Issue by richabwt** [mapbox/mapbox-unity-sdk#621]
hello

recently i am using unity 2017.3.1f1 and mapbox-unity-sdk_v1.4.0 and the problem is that when i am using LocationBasedGame scen (example of mapbox) everything is working perfectly but the thing is that the map is get stuck on mobile screen means its not moving not zoomout , zoomin

so, please suggest me the correct way to do it i invest my two days in working over it .
thanks in advance
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @richabwt Can you let us know what mobile device you are building to?

**Comment by atripathi-mb** [comment]
@richabwt Sorry if I don't understand the issue you're seeing. The `LocationBasedGame` scene does not come with an interaction script attached. Are you seeing this issue after attaching the `QuadtreeCameraMovement` script or your own interaction script?

**Comment by richabwt** [comment]
no i didn't attach QuadtreeCameraMovement  script in it i just used it as an example. But i also tried it out from this link 
http://www.yudiz.com/design-your-map-in-mapbox-and-integrate-it-in-unity-part-1/?fb_comment_id=1336749689769250_1525624974215053#f186effe5f68518 

This link is just the same what i want to do.

but the problem is that i didn't find the so many option in  my inspectorpanel that were shown in tutorial. Please tell what i have to do to achieve the functionality like in that tutorial.

**Comment by richabwt** [comment]
@jordy-isaac  i am using redmi 5.

**Comment by richabwt** [comment]
@atripathi-mb  hey i also attach FlyCamera.cs script but it also not working properly.

**Comment by atripathi-mb** [comment]
@richabwt the tutorial you linked above is built on an older version of the SDK, we released version 1.4 last week. While most of the API’s are the same, there might be features and functionality that have been added or changed from previous releases.

Also, I am not sure what FlyCamera.cs is? It is not part of our Sdk as far as I know.

We can answer specific issues that you have with the SDK.

Hope this helps

**Comment by richabwt** [comment]
@atripathi-mb I also thought this is the problem of version mismatch but how can i achieve that features which are shown in that link with my latest version of mapbox sdk.

**Comment by atripathi-mb** [comment]
@richabwt The tutorial that you have linked is not from Mapbox, unfortunately we cannot update the tutorial, but we will be happy to answer any specific question you have.

**Comment by richabwt** [comment]
@atripathi-mb hey the tutorial i linked is diffinately based on integartion of mapbox. I also reattach the link, and the link is below

http://www.yudiz.com/design-your-map-in-mapbox-and-integrate-it-in-unity-part-1/?fb_comment_id=1336749689769250_1525624974215053#f186effe5f68518

but it is on older version of mapbox. i want to do it with latest one .

**Comment by atripathi-mb** [comment]
> the tutorial i linked is diffinately based on integartion of mapbox
>but it is on older version of mapbox. i want to do it with latest one .

@richabwt The tutorial is about using Mapbox Unity SDK but it not written by someone at Mapbox so we will not be able to update the tutorial. 

From what I can gather from the tutorial, you can easily achieve it by using our `LocationBasedGame` prefab. We have made setting up common use cases as simple as plug and play.  You can add the `QuadTreeCameraMovement` script for zoom/pan.

**Comment by richabwt** [comment]
@atripathi-mb Thanku Abhishekh, yeah i implemnted this feature and am also set the custom dataset in my mapbox but again i am facing a problem, i want to replace these dataset with my gameobject it my be cube ,sphere or any 3d character and for this i follow this one

http://www.yudiz.com/add-custom-dataset-points-to-mapbox-map-and-integrate-them-in-unity/

but again the problem is that i can not find layer map visualizer and vector tile factory option in mapbox sdk  i think this will be now added in abstract map script in newer version but i didn't get how can i manage to achieve this feature.

**Comment by atripathi-mb** [comment]
> the problem is that i can not find layer map visualizer and vector tile factory option in mapbox sdk 

@richabwt `Map Visualizer` gets automatically setup in v1.4, Vector Tile Factory is the same as Vector section in v1.4. You don't need to create a vector tile factory instead just setup parameters that you would have set in a `ModifierStack`.
