### ISSUE TITLE
[Enhancement] Follow strategy pattern for tile factories

### ISSUE THREAD

**Issue by atripathi-mb** [mapbox/mapbox-unity-sdk#623]
As an effort to simplify out API's we should use the strategy pattern to create different tile factories. 
This will reduce the amount of redundant code and also make the factories more modular. 

Terrain Factories are a good example, theres is lot of repeated code across different flavors of terrain mesh generation. 

Separating data fetching from tile factories is part of this effort. #622

**Comment by brnkhy** [comment]
I extracted terrain logics as strategies and create a TerrainFactoryBase using those.
I also changed the TerrainLayer class to utilize these classes and removed old factories afterward. It all works at the moment.

Repo; https://github.com/mapbox/mapbox-unity-sdk/tree/terrainFactoryRefactor

There's only one little part I want to talk so far; 
We have two different type of strategies, elevated ones and flat ones. Obviously flat maps doesn't require web calls but it also doesn't makes sense to do data fetching in terrain strategies.
A good solution would have been having another layer between factory and strategy for both cases but it adds one extra level of abstraction and makes it harder to choose&assign strategies to terrain layer directly. 
I'm also not a fan of sending _fileSource to strategy and do the data fetching there.
Current version adds an interface and does an ugly check like 
`if (Strategy is IElevationBasedTerrainStrategy)`
I'm not a fan of that either but I didn't want to waste too much time on this as extracting data fetching from factories (#622) might change it all together anyway.

**Comment by atripathi-mb** [comment]
@brnkhy Changes look good. Could we combine `ElevatedTerrainWithSidesStrategy` & `ElevatedTerrainStrategy` into one strategy since both can be achieved by turning on/off one parameter. 

> I'm not a fan of that either but I didn't want to waste too much time on this as extracting data fetching from factories (#622) might change it all together anyway.

I agree with you, we need a broader discussion on how to tackle our data fetching calls in general. Let's talk about cleaning up the data fetching part as a separate issue.

**Comment by brnkhy** [comment]
@atripathi-mb  
ouch forgot to update here; latest (side wall factory removed etc) is here; https://github.com/mapbox/mapbox-unity-sdk/tree/sideWalls

so yea side wall factory is removed and "side wall" in an option under regular elevated terrain now. Disregard that first branch (I'm not deleting it for now just in case).

**Comment by atripathi-mb** [comment]
@brnkhy Awesome thanks.
