### ISSUE TITLE
[Enhancement] Integrate UI with tileJSON metadata. (dropdown for layers & properties available)

### ISSUE THREAD

**Issue by atripathi-mb** [mapbox/mapbox-unity-sdk#627]
As a user I want to see all the layers that are available from the tileset source I specified. 

We have tileJson metadata for the tileset, which contains all the information that remove the guesswork from the UI. Integrate the tileJSON information with the AbstractMap UI.

**Comment by MiroMuse** [comment]
We can address this while we

**Comment by MiroMuse** [comment]
Hey @apavani, can you please evaluate the time estimate placed on this?

**Comment by MiroMuse** [comment]
Closing this in favor of: https://github.com/mapbox/unity/issues/574
