### ISSUE TITLE
Change ImagerySourceType of AbstractMap in runtime

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#630]
I am able to load custom tilesets generated from mapbox studio in Abstract Map through the inspector without error. However I would like to be able to switch back and forth between a custom style and, say, mapbox street style. 

Is it possible to use ImagerySourceType to change it in Abstract Map at runtime or does it require a separate GameObject/resetting the program?

Is my question related to #625?

**Comment by jordy-isaac** [comment]
Hi @specsdhdeveloper Thanks for the ticket. Can you let us know a little bit more about your use case and/or what you've tried so far? This will help us get you some useful info.

**Comment by specsdhdeveloper** [comment]
Hi Jordy,

I'm interested in switching between a historical map georeferenced in mapbox studio and mapbox's `street` style in runtime.

I'm using SDK 1.4's `AbstractMap`'s style name dropdown to set the map id. I can switch back and forth between the custom map id and the default style.

Eventually, I'd like to be able to switch between both in runtime with a GUI button.

I've only tried that, looked around in `AbstractMap`'s `SetupMap()`, I'm guessing I could redefine it and add the styles to be loaded on initialize?

**Comment by jordy-isaac** [comment]
That might work. Please let us know how it goes. This also does look related to #625 so please keep an eye on that ticket for updates.
