### ISSUE TITLE
Add using for Vector2d and Mathd

### ISSUE THREAD

**Issue by bourgeoismaxime** [mapbox/mapbox-unity-sdk#631]
Hello,
Using Unity 2017.3.1f1 here, for both Mapbox Unity SDK 1.3 and 1.4 I had to add in some files the following lines :
    using Vector2d = Mapbox.Utils.Vector2d;
    using Mathd = Mapbox.Utils.Mathd;
Otherwise I have an error for ambiguous call between UnityEngine and Mapbox struct/class.
Would it be possible to add them on your side so we do not have to add them at every update ?

Thanks,
Maxime

**Comment by atripathi-mb** [comment]
@bourgeoismaxime Thanks for pointing this out. Do you mind creating a Pull Request for these changes? Will be happy to review and add them to our next release.

**Comment by bourgeoismaxime** [comment]
I'll try to do that when I'll have time
