### ISSUE TITLE
Unloaded Tiles Appear

### ISSUE THREAD

**Issue by husnainyousaf88** [mapbox/mapbox-unity-sdk#633]
I am using Latest Mapbox SDK with Unity 2017. I want to load at least 20 tiles in each Direction ie(NEWS) before scene starts. The issue is sometime the loading canvas disappear and unloaded tiles(with black unload default material) appears on the screen. Is there any check which i can use to see if all tiles are loaded.
Thanks,

**Comment by jordy-isaac** [comment]
Hi @husnainyousaf88 You can specify how tiles load in the `Extent Options` on the `AbstractMap.cs` script. If your still seeing tiles not loading can you screenshot them so that we can have a deeper look?

**Comment by husnainyousaf88** [comment]
I am using Range Tile Provide for loading tiles in bulks. but I resolved the issue by calling OnRegister and Create Height maps in recursions.

**Comment by brnkhy** [comment]
@husnainyousaf88 20 tiles in each direction means 41x41 = 1681 tiles and server requests in one frame. Increasing `Default Web Request Timeout` might help a little but really, you shouldn't need that many tiles at one. 
Have you checked the zommable map demo scenes for example? It changes the zoom level depending camera position/height so you won't need to load too many tiles when camera is zoomed out.
