### ISSUE TITLE
Spawn objects at lat/long

### ISSUE THREAD

**Issue by greglemonmapbox** [mapbox/mapbox-unity-sdk#642]

**Comment by atripathi-mb** [comment]
@jeffrobernard If you have a list of lat/long to spawn the game objects, you could use `SpawnOnMap` script provided with our examples.

**Comment by campeezjesse** [comment]
I would also like more information on this subject. I am searching for a way to use the points in my datasets to spawn objects.
 The goal is to add interactive objects to a map in AR for an iOS app

**Comment by jeffrobernard** [comment]
Hello! This was a huge help. I’m able to spawn on map, but how do I link those game object to the field values for those points of interest, showing what they are. Also, how do I get them to spawn above the map? My 3D game object are snapped onto the map on start. 
Kindest Regard,

Jeff Bernard
