### ISSUE TITLE
'MapboxMobileEvents/MapboxMobileEvents.h' file not found

### ISSUE THREAD

**Issue by campeezjesse** [mapbox/mapbox-unity-sdk#644]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3
* Mapbox SDK version: 4.0
* The platform you're building to: iOS, Xcode last two versions

 I have researched this problem and tried every documented solution I could find. 
* Build target 7.0, 8.0, 9.0.
iPad only, iPhone only, any device.
Manually add framework and embedded Binary 
add new search paths
Check that symlink is not checked
Opened new accounts for Xcode, Mapbox, and Unity
I add directly to the assets, set build settings for iOS then it builds to Xcode and produces the error.
I am happy to show you settings but over the last few days I have changed every one of them I can find with no luck.

**Comment by tboogh** [comment]
I've run into the same problem, for me the generated xcode projects are missing a couple of items. First open the XCode project and go to the **Build Settings** tab and search for **Header Search Paths**, double click to the row and press the **+** button and add a line and paste this into it ```$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/```

I also had to manually link the libz library to the project, that can be done by going to the **Build Phases** tab and expand **Link Binary With Libraries**. Click the **+** button and search for **libz.tbd** and press **Add**

**Comment by campeezjesse** [comment]
I have not tried to link the libz yet. Thank you so much for the suggestion. I will try it this morning and let you know!

Jesse Holt
Jesse@campeez.com<mailto:Jesse@campeez.com>
Www.campeez.com<http://Www.campeez.com>

On Apr 2, 2018, at 11:31 PM, Tobias <notifications@github.com<mailto:notifications@github.com>> wrote:


I've run into the same problem, for me the generated xcode projects are missing a couple of items. First open the XCode project and go to the Build Settings tab and search for Header Search Paths, double click to the row and press the + button and add a line and paste this into it $(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/

I also had to manually link the libz library to the project, that can be done by going to the Build Phases tab and expand Link Binary With Libraries. Click the + button and search for libz.tbd and press Add

**Comment by treasurehunters003** [comment]
Still same error for me... Replaced Header Search Paths, add libz.tbd, build without symlink, and still not working.

**Comment by igaln** [comment]
Is it possible to automate this on the next release and add as an enhancement?

**Comment by unnanego** [comment]
It's $(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/MapboxMobileEvents but this still doesn't help

**Comment by njw275** [comment]
Added: 
```$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/```

I also manually added `libz.tbd` and made sure I wasnt building with symlink

Still nothing....any one with other solutions to this error?

**Comment by TiborUdvari** [comment]
It's important to note that the header search files appy to the `UnityFramework` target and not the `Unity-iPhone` one. At least in `2019.3` that is the case.

**Comment by Nima-Jamalian** [comment]
Mange to get in work in Unity 2019.3.15f1

The problem is that TargetGuidByName() has been deprecated so you need to go and replace it with GetUnityFrameworkTargetGuid() in order to fix 'MapboxMobileEvents.h' file not found in xcode.

There are two scripts that you need to change:

1- Mapbox_iOS_build
    You can find the script at Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs, change line 26 
     `string target = proj.TargetGuidByName("Unity-iPhone");`
     to
      `string target = proj.GetUnityFrameworkTargetGuid();`

2- UnityARBuildPostprocessor
     You can find the script at 
     UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor
     Go to Line 80 and 81 change the code to the following 
      `proj.AddFrameworkToProject(proj.GetUnityFrameworkTargetGuid(), "ARKit.framework", false);`
      `string target = proj.GetUnityFrameworkTargetGuid();`

**Comment by WorldForStory** [comment]
> Mange to get in work in Unity 2019.3.15f1
> 
> The problem is that TargetGuidByName() has been deprecated so you need to go and replace it with GetUnityFrameworkTargetGuid() in order to fix 'MapboxMobileEvents.h' file not found in xcode.
> 
> There are two scripts that you need to change:
> 
> 1- Mapbox_iOS_build
> You can find the script at Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs, change line 26
> `string target = proj.TargetGuidByName("Unity-iPhone");`
> to
> `string target = proj.GetUnityFrameworkTargetGuid();`
> 
> 2- UnityARBuildPostprocessor
> You can find the script at
> UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor
> Go to Line 80 and 81 change the code to the following
> `proj.AddFrameworkToProject(proj.GetUnityFrameworkTargetGuid(), "ARKit.framework", false);`
> `string target = proj.GetUnityFrameworkTargetGuid();`

I don't have UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor but I do have ARKit XR Plugin and found UnityARBuildPostprocessor. Should I edit that file? Line 80 and 81 are comments so I'm not sure what I should be replacing.

**Comment by Nima-Jamalian** [comment]
> I don't have UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor but I do have ARKit XR Plugin and found UnityARBuildPostprocessor. Should I edit that file? Line 80 and 81 are comments so I'm not sure what I should be replacing.

Replace them with what I have written, 
Line 80`proj.AddFrameworkToProject(proj.GetUnityFrameworkTargetGuid(), "ARKit.framework", false);`
Line 81 `string target = proj.GetUnityFrameworkTargetGuid();`
It should work.

**Comment by rod-m** [comment]
Updating the deprecated TargetGuidByName to GetUnityFrameworkTargetGuid fixed error in Unity Build.
In XCode 12.1 I still had errors with the missing MapboxMobileEvents.h
What works is to remove folder paths in MapboxMetricsClient.m since these paths were added to the UnityFramework Header Search Paths.
#import <MapboxMobileEvents/MapboxMobileEvents.h>
to 
#import <MapboxMobileEvents.h>
Then same in MapboxMobileEvents.h
Remove all folder paths:
#import <MMEConstants.h>
#import <MMEEvent.h>
#import <MMETypes.h>
#import <MMEEventsManager.h>

**Comment by MartinMajewski** [comment]
September 2021: error still exists. Still, one has to change to "GetUnityFrameworkTargetGuid()" and still the MapboxMobileEvents.h cannot be found.

Following the advice by @rod-m to remove all folder paths from the imports helps!

But this cannot be the final word. MapBox for Unity needs an overhaul!

**Comment by gbhanuteja23** [comment]
> Mange to get in work in Unity 2019.3.15f1
> 
> The problem is that TargetGuidByName() has been deprecated so you need to go and replace it with GetUnityFrameworkTargetGuid() in order to fix 'MapboxMobileEvents.h' file not found in xcode.
> 
> There are two scripts that you need to change:
> 
> 1- Mapbox_iOS_build You can find the script at Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs, change line 26 `string target = proj.TargetGuidByName("Unity-iPhone");` to `string target = proj.GetUnityFrameworkTargetGuid();`
> 
> 2- UnityARBuildPostprocessor You can find the script at UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor Go to Line 80 and 81 change the code to the following `proj.AddFrameworkToProject(proj.GetUnityFrameworkTargetGuid(), "ARKit.framework", false);` `string target = proj.GetUnityFrameworkTargetGuid();`


Thanks for this solution, doing the option 1 in Unity 2022.3.3f1 also has resolved this library not found issue.

**Comment by TheMehranKhan** [comment]
> Mange to get in work in Unity 2019.3.15f1
> 
> The problem is that TargetGuidByName() has been deprecated so you need to go and replace it with GetUnityFrameworkTargetGuid() in order to fix 'MapboxMobileEvents.h' file not found in xcode.
> 
> There are two scripts that you need to change:
> 
> 1- Mapbox_iOS_build You can find the script at Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs, change line 26 `string target = proj.TargetGuidByName("Unity-iPhone");` to `string target = proj.GetUnityFrameworkTargetGuid();`
> 
> 2- UnityARBuildPostprocessor You can find the script at UnityARKitPlugin/Plugins/iOS/UnityARKit/Editor/UnityARBuildPostprocessor Go to Line 80 and 81 change the code to the following `proj.AddFrameworkToProject(proj.GetUnityFrameworkTargetGuid(), "ARKit.framework", false);` `string target = proj.GetUnityFrameworkTargetGuid();`

Update in 2023: Using XCode 15 Beta and MacOS Sonoma with iOS 17, Unity version 2021.3.29f1 on MacOS M1, I still had same errors but downloading AR package from Unity and also doing the first step that @Nima-Jamalian provided it compiles and installs on my device. thanks

**Comment by oleksiivinogradov** [comment]
terrible!!! 
same error from 2018 year and no fixes at all!!!

**Comment by minghei** [comment]
2024 now. I think it is dead
