### ISSUE TITLE
Smooth zooming with moving camera

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#645]
I'm trying to make a map setup based on the ZoomableMap example, but where the Camera is moving around in the scene, and zooming uses a combination of the Camera's Orthographic Size and Mapbox' Zoomlevel.

I want the map to scale relatively to the content I have drawn out in my scene already, so that the content don't have to be redrawn based on Camera position or Zoom level. I managed to do this in the previous verison of the SDK (1.3.0), using a CameraBoundsTileProvider and the BasicMap, but I'm having issues after the update. 

When I'm using the UpdateMap function in AbstractMap, and send in the Camera's current position and zoom level, the correct tiles (based on Zoom level) is loaded, but the Camera's LatLon position is moved. The scale also seems to be a bit off. Any clues as to how I can achieve this? Do I need to create my own UpdateMap function?

* Unity version: Unity 2017.3.1f1
* Mapbox SDK version: 1.4.0

**Comment by JorgenEngenNapstad** [comment]
I figured out that I needed to use 0,0 as the input coordinate in the UpdateMap function to make it work, instead of sending the current camera position or the maps CenterLatitudeLongitude. I guess it makes sense as the center of the map never changes. 

Not sure if this is a good way to do it though. I feel like I'm doing everything differently than how it's meant to be done.

**Comment by atripathi-mb** [comment]
@JorgenEngenNapstad This is a little tricky situation since your camera moves and your map's center is still the original `CenterLatitudeLongitude`. 
For smooth zoom you need to move your camera such that it always points at the location that you were looking at. I made this simple change to my zoom function to achieve the desired result
```
void ZoomMapUsingTouchOrMouse(float zoomFactor)
{
    var zoom = Mathf.Max(0.0f, Mathf.Min(_mapManager.Zoom + zoomFactor * _zoomSpeed, 21.0f));
    // Get lat long at which camera is looking at. 
    var cameraLatLong = _mapManager.WorldToGeoPosition(_referenceCamera.transform.position);
   // Update the zoom. 
    _mapManager.UpdateMap(_mapManager.CenterLatitudeLongitude, zoom);
   // Get the new camera position. 
    var newPos = _mapManager.GeoToWorldPosition(cameraLatLong, false);
    // move camera so it points at the same location. 
    _referenceCamera.transform.position = new Vector3(newPos.x,														  
                                                                                              _referenceCamera.transform.position.y,
									                   newPos.z);
		}
```
