### ISSUE TITLE
possible Conversions.GeoToWorldPosition miscalculation?

### ISSUE THREAD

**Issue by AndrewIK** [mapbox/mapbox-unity-sdk#65]
![geotoworldposition](https://cloud.githubusercontent.com/assets/17868769/25988103/94bf0b62-36ab-11e7-90b1-5056476f37af.png)
![mapcontroller](https://cloud.githubusercontent.com/assets/17868769/25988104/94c9ed70-36ab-11e7-9ad2-758acca08c3d.png)

I'm using 0.5.1 beta, the issue is that Conversions.GeoToWorldPosition returns non-zero values for the same lat/long the map is centered on.

I.e. MapController is configured to have 37.808596, -122.412537 as Lat Lng. Slippy.Start() has a new line at the end,
Vector2d worldPos = Conversions.GeoToWorldPosition(37.808596, -122.412537, MapController.ReferenceTileRect.Center, MapController.WorldScaleFactor);

For some reason worldPos 40.50900, 41.08352. Am I wrong expecting 0, 0 there?

**Comment by david-rhodes** [comment]
@AndrewIK The map is not technically centered on your requested lat/lon. The map is centered on the middle of the tile that contains your requested lat/lon/zoom.

If you were to move the map root transform the inverse of: `Conversions.GeoToWorldPosition(37.808596, -122.412537, MapController.ReferenceTileRect.Center, MapController.WorldScaleFactor);`, you would essentially align the map with your specific requested lat/lon. Note: this will create bugs will other systems dependent on the position being at world origin.

You can observe what's happening with the `LocationProvider.unity` scene. Set the `EditorLocationProvider` lat/lon and watch where the "player" is positioned inside the map.

**Comment by AndrewIK** [comment]
Thank you for the explanation! Closing it now
