### ISSUE TITLE
Loading POIs from Vector layer or GeoJson

### ISSUE THREAD

**Issue by campeezjesse** [mapbox/mapbox-unity-sdk#651]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3
* Mapbox SDK version: 4.0
* The platform you're building to: Xcode / iOS 11.3
I am attempting to add annotations to a map that is displayed in AR. 
I am trying to add POIs to my map with interactive annotations. Something similar to this https://www.mapbox.com/ios-sdk/examples/runtime-multiple-annotations/ but in a tabletop map.

The idea is to be able to see the map ay table size, search specific vector layers and be able to click on and read the info windows.

 I am very new to Unity and so far all I can manage to do is find little ways to make the maps look different. I am able to place a styled map with my data flat on the surface of the map but not with any kind of interactivity. I am not even able to modify what layers show.
 The other option would be any kind of example to add my map to ARKit without using Unity? I am able to create all of the functionality I need in a basic Xcode map just not display it as part of an ARScene.

 Any help would be much appreciated. I am new to all of this and need as much direction as possible

**Comment by atripathi-mb** [comment]
@campeezjesse Apologies to getting back to you so late. 

I would suggest using our ARTableTop example. It has everything you need to get setup with a table top AR experience. 

For interactivity, I would suggest looking at the `InteractiveVectorMap` example, it shows you how to setup up buildings and show information when you select them. 

Also, I would suggest going through this tutorial to get started with styling your map https://www.mapbox.com/help/create-a-map-in-unity/

Feel free to reach out with any specific questions that you have.
