### ISSUE TITLE
Geocode search windows can incorrectly convert doubles

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#658]
When using the geocode search window to find locations, in some locales the gps coordinates will get formatted with a comma instead of a dot, e.g.:

"42,23551, 33,123555" instead of "42.23551, 33.123555 ".

AbstractMap will then not be able to parse the coordinates.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.0b12
* Mapbox SDK version: 1.4

```
[Exception] ArgumentException: Wrong number of arguments
Conversions.StringToLatLon()    Assets/Addons/Mapbox/Unity/Utilities/Conversions.cs:48
AbstractMap.InitializeMap()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:420
AbstractMap.SetUpMap()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:395
AbstractMap.Start()    Assets/Addons/Mapbox/Unity/Map/AbstractMap.cs:291
```
```
[Exception] NullReferenceException: Object reference not set to an instance of an object
RangeTileProvider.Update()    Assets/Addons/Mapbox/Unity/Map/RangeTileProvider.cs:47
```

**Comment by brnkhy** [comment]
this is probably due to local device culture info so we should parse values with culture info set correct instead of letting .net use device culture.

**Comment by brnkhy** [comment]
I guess this is good to close after @atripathi-mb's fix above.
