### ISSUE TITLE
Unity Crash when importing the library or opening the SDK project in the repo.

### ISSUE THREAD

**Issue by itech4ever** [mapbox/mapbox-unity-sdk#66]
Hi there, I am trying to import the SDK into Unity and tried both the Unity Package and SDK example from the source repo. Unity crashed every time unfortunately. I tried the following platform:

1) Windows 7 Enterprise + Unity 5.3.4
2) OS X Sierra 10.12.4 + Unity 5.3.4

It seems it crashed once it reached the "importing small asset" phase.

Thanks!

Best,
Zhitao

**Comment by isiyu** [comment]
have you installed the dependencies ? To update/install dependencies run these scripts: 

OSX
```
./update-mapbox-unity-sdk-core.sh
```

Windows
```
update-mapbox-unity-sdk-core.bat
```

There are instructions in the [contributing doc ](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CONTRIBUTING.md)


@itech4ever - Let us know if this was it, and we can update the readme to be more explicit. Thanks!

**Comment by itech4ever** [comment]
@isiyu thank you! I tried but unfortunately it did not work. Is there anything else you can think of? or any way I can trace the problem by myself? Any advice would be highly welcomed!

**Comment by BergWerkGIS** [comment]
> Windows 7 Enterprise + **Unity 5.3.4**
> OS X Sierra 10.12.4 + **Unity 5.3.4**

@itech4ever any chance you could try with a newer Unity version?
Our examples are saved with 5.4.

Maybe upgrading could help?
Or try excluding the `Assets\Mapbox\Examples\` folder when importing.

**Comment by itech4ever** [comment]
@BergWerkGIS Thanks! It seems upgrading the Unity solved the problem! I firstly tried to exclude the folder, but no luck.

Anyway, thanks @isiyu and @BergWerkGIS for the help!

**Comment by binakot** [comment]
After this probably should to add minimal Unity version to readme file on repository 🙉

**Comment by david-rhodes** [comment]
> After this probably should to add minimal Unity version to readme file on repository 🙉

Done, thanks!
