### ISSUE TITLE
PositionWithLocationProvider isn't continuous

### ISSUE THREAD

**Issue by utkarshdwivedi3997** [mapbox/mapbox-unity-sdk#661]
I'm trying to move an avatar on a map using the PositionWithLocationProvider. I've also tried ImmediatePositionWithLocationProvider. It seems that no matter what I do, the avatar jumps on the map at different times, instead of constantly updating the position when the device moves. I've tried setting the UpdateDistanceInMeters to 0.1 in the DeviceLocationProvider, but that doesn't work either. It seems to be very inconsistent in how and when it updates the current location of the device.

I know this issue is more on the Unity side, but if someone know a fix for it please let me know!

Thanks!

**Comment by DigohD** [comment]
Hello!

I have the same issue. I get a position update about once every 10 seconds, which is way worse than what is seen in for example Pokemon GO. "Solved" this somewhat by having a separate player object lerp it's position towards the location object, but this means the position on the map is always a bit behind.

If you find out a way to make the actual position more accurate and frequently updated, please let me know.

**Comment by utkarshdwivedi3997** [comment]
I am currently using PositionWithLocationProvider. The issue is that Unity is very inconsistent about updating the position. Sometimes it updates after moving 5m but other times it seems to not update for 15m, even if I have the UpdateDistanceInMeters set to 0.1. Lerping helps a lot, but I was hoping if there was a way to make the updates consistent.

I've used the following devices for testing:
Samsung Galaxy S6 (Android 7.0 Nougat)
Samsung Galaxy S7 (Android 7.0 Nougat)
Nexus 6 (Android 5.1.1 Lollipop)

**Comment by atripathi-mb** [comment]
@utkarshdwivedi3997 we have been seeing similar issues with Unity location updates. We are actively working on improving/mitigating this Unity limitation. Can’t tell you exactly when that would be available though :)
