### ISSUE TITLE
Issue with DirectionFactory building on Android

### ISSUE THREAD

**Issue by dmp5658** [mapbox/mapbox-unity-sdk#664]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.1f1
* Mapbox SDK version: v1.4.0
* The platform you're building to: Android
* A description of what you're trying to do: 
Using Googles ArCore camera I'm trying to build an AR Navigation for walking, right now in DirectionsFactory I set up wp to be two different coordinates. This draws the direction on the map successfully playing it on Unity.
![Scene Image](https://image.ibb.co/eSARcH/Capture.png)
![Game Image](https://image.ibb.co/dk5RcH/Capture2.png)

The issue is when its built on android the direction waypoint does not show up.
After some debugging I found the issue to be inside HandleDirectionsResponse

Inside foreach (MeshModifier mod in MeshModifiers.Where(x => x.Active))
During the loop it stop during mod.Run(feat, meshData, _map.WorldRelativeScale);

Any ideas on what can be causing this and how I can fix it?

**Comment by dmp5658** [comment]
Thank you for the reply Jordy, after checking the console I have an error before that, not sure if it's related. its when I try to update the map to the users coordinates, the coords are printed out under the first error
and the second error at the bottom is the one thats not drawing the Direction.
![capture3](https://user-images.githubusercontent.com/23619073/38656762-9ad9fb82-3dea-11e8-9d32-a8c4d506a17c.PNG)

**Comment by atripathi-mb** [comment]
Looking at the errors, it seems you are using the map while it is still null. I would suggest using the map only after the OnInitialized event is triggered.

**Comment by dmp5658** [comment]
I fixed the first issue in RotateMap.Start() by making sure OnInitialized is trigger. Now I still have this error on Android.
![image](https://user-images.githubusercontent.com/23619073/38783740-3acd1b74-40d4-11e8-9a2c-539ac2d11753.png)

DirectionsFactory already has _map.OnInitialized += Query; so I'm not sure what the issue is now

**Comment by dmp5658** [comment]
After some troubleshooting the issue does not happen using ARCore 1.1 and Mapbox 1.3

**Comment by jordy-isaac** [comment]
@dmp5658 Was this an existing project on 1.3? To use 1.4 and beyond, you'll need to migrate your project. If it's still an issue after migrating, please re-open this ticket. Here's a [migration guide](https://www.mapbox.com/unity-sdk/overview/migrate-version/).

**Comment by dmp5658** [comment]
No, it was a fresh 1.4 project. I deleted 1.4 and the re imported 1.3 which worked
