### ISSUE TITLE
AbstractMap: spawned GameObjects being "shuffled" when changing zoom level

### ISSUE THREAD

**Issue by matteo-interfase** [mapbox/mapbox-unity-sdk#673]
* Unity version: 
2017.3.1f1
* Mapbox SDK version: 
1.4.0
* The platform you're building to: 
Android/GearVR
* A description of what you're trying to do:
When the map is initialized my application loads some attributes from the dataset, specifically, the "name" property which has been set on every Point via Mapbox Studio, as you can see here https://i.imgur.com/S9F9JNd.png
I use that attribute in a text canvas inside the prefab (via prefab modifier) to identify that specific object when I run my application (I have around 50 of them distributed across the map). 
My main issue is that when I change zoom level all the spawned prefabs are being repositioned randomly, and I can't find a way to understand how the various vector entities are being repositioned. The result is that at every zoom level variation my points are being "shuffled".

I made a 15s video in which I constantly switch between two zoom levels, in order to make you better understand my issue: https://youtu.be/-crQ-955n8c

I'm sure I'm missing something obvious, but I don't know how to solve this issue. 
Thanks in advance for any kind of help you can provide!

**Comment by atripathi-mb** [comment]
@matteo-interfase Can you share the Map Settings with us or steps to reproduce this issue?

**Comment by matteo-interfase** [comment]
@atripathi-mb sure:
these two screenshots are taken from the inspector of the abstract map script:
1) https://i.imgur.com/ckfW6jC.png
2) https://i.imgur.com/iLx4DH8.png
while this is screenshot of the map editor https://i.imgur.com/7eHKUC9.png

"TurbineSpawn" is a modifier that handles the instancing of custom gameobjects on the map when a point is found on the Json.
[TurbineSpawn.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1914670/TurbineSpawn.zip)

Let me know if you need anything else, thank you.

**Comment by atripathi-mb** [comment]
@matteo-interfase Looking at the screenshots and `TurbineSpawn` script I don't see any reasons why features will be shuffled. TurbineSpawn looks similar to our PrefabModifier script. Is it possible that the way your label elements are getting shuffled? 

You can attach a FeatureBehaviourModifier to your `Turbine` Layer to debug properties of that feature. 
![image](https://user-images.githubusercontent.com/32286016/38831575-a5dad424-4174-11e8-9246-b04258d22c4d.png)

If that doesn't work, I would need a small sample project to reproduce the issue.
