### ISSUE TITLE
Some POIs disppeared at low level

### ISSUE THREAD

**Issue by dingfengboo** [mapbox/mapbox-unity-sdk#675]
When zoom out to low level, some POIs disppeared.
I think this is good for performent and looking.

I want to make some adjustments, but can not find how to set.
please help.

**Comment by jordy-isaac** [comment]
Hi @dingfengboo. Can you let us know a bit more about your use case? Please let us know what you're building and what you're looking to accomplish with the zoom and POIs. What have you tried so far and where have you gotten stuck?

**Comment by dingfengboo** [comment]
I find it is data problem. so close it
