### ISSUE TITLE
Any beginner level tutorial or documentation for Mapbox AR

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#679]
Hi,
I'm new to Mapbox SDK. I'm trying to build an AR app but can't get started due lack of documentation. Where can I find the complete documentation specifically for AR?
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @tarakinsuide! You can find the documentation for our [Tabletop AR example](https://www.mapbox.com/unity-sdk/overview/tabletop-ar/) and the [World-scale AR example](https://www.mapbox.com/unity-sdk/overview/world-scale-ar/) on our [docs page](https://www.mapbox.com/unity-sdk/overview/).
