### ISSUE TITLE
How to add wall and hallways in mapbox for unity 3D

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#680]
I'm trying to test this AR application given on your blog: https://blog.mapbox.com/indoor-navigation-in-ar-with-unity-6078afe9d958
and I'm confused how to add add wall and hallways in mapbox for unity?
I've built a custom tileset and style of my indoor environment and have used extrusions for polygons in my tileset.
However, when I try to open the map in unity it turns out to be a flat 2D map which I know is because of OpenGL.
Now, how do I build walls and hallways using Mapbox for Unity?

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @tarakinsuide Thanks for writing in. The first thing you should know is that it was built on v1.3 of the SDK. To run it, you'll need to either install v1.3 or migrate the project to 1.4. We'll have a migrating doc up on the [documentation page](https://www.mapbox.com/unity-sdk/overview/) very shortly. 

As for your custom data you'll need to have it properly configured. You can see how to configure your custom data [here](https://www.mapbox.com/unity-sdk/overview/data-explorer/#custom-data). If you're having trouble after that please show us some screenshots of your vector and vector layer visualizer settings.

To create the hallways in the manner that we did for this example you'll need a georeferenced image. We outline how it's done in Phase 1 of the blog post. You can also see the documentation on how to do that in Mapbox Studio [here](https://www.mapbox.com/help/georeferencing-imagery/).

**Comment by IniyanElankavi** [comment]
![screen shot 2019-01-31 at 7 48 01 pm](https://user-images.githubusercontent.com/10937343/52059910-1ee01b80-2591-11e9-9c45-642d09f47396.png)
I have achieved till this point. From here I don't know how to proceed by creating the walls in real size using unity and integrate with the AR Indoor Navigation. If there are any updated documentation please share.
