### ISSUE TITLE
Mapbox AR placing an object on a LatLong

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#681]
Hello,

What tools/script should I use to display an AR object at a latlong using your SDK?
I'm using your SDK for the first time and I didn't find proper resources in your documentation. 
If I use WorldScaleAR scene, what changes should I make to display an object at a latlong in my office?

Regards,
Tarak Shah.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by tarakinsuide** [comment]
Any step by step guide would be really helpful.

**Comment by tboogh** [comment]
There is an example in the zoomable map scene in the script ```SpawnOnMap.cs``` that spawns a prefab at a given location.

Hope that helps.

https://github.com/mapbox/mapbox-unity-sdk/blob/a450ad1a141bac5b54fbbde1eda4f9bf4cfffe03/sdkproject/Assets/Mapbox/Examples/2_ZoomableMap/Scripts/SpawnOnMap.cs

**Comment by tarakinsuide** [comment]
Also, do I need to make any changes to the WorldScaleAR scene to start rendering my camera? I built the example scene, but it shows only a blue and orange map instead of camera and the position of that is also not changing with respect to my phone's position.

**Comment by apavani** [comment]
@tarakinsuide If you are on android, make sure you have checked the ARCore supported checkbox in the XR Setting section of Build Player Settings
On iOS make sure that the Graphics API is set to Metal
Let us know which platform you are building on
The Map you see in the screenshot is a reference to give you a context of where on the map are you placed in AR.

**Comment by tarakinsuide** [comment]
Hi Akash,
Thanks! That worked.
Now the issue is, why am I not able to see the Prefab at the LatLong where I want it to be inspite of giving manual location.
I'm using WorldScaleAR ManualAlignment Scene.
As per the screenshot attached below, the camera is now rendering, thanks to you. But, what is that map which is showing up along with camera feed called? Can I make changes to this map and make it more specific to my office surroundings, like by adding walls and hallways according to my office structure? How to do that? Can you please release a video tutorial? 

![screenshot_20180419-161251](https://user-images.githubusercontent.com/34171415/38987778-963e27b0-43ee-11e8-95cc-d8c4add49fa5.png)
![screenshot_20180419-161411](https://user-images.githubusercontent.com/34171415/38987779-96b23a92-43ee-11e8-9c56-2cb5b69536cf.png)

**Comment by apavani** [comment]
> I not able to see the Prefab at the LatLong where I want it to be inspite of giving manual location.
How did you do this? Can you share the code
For indoor map, we have [this blog post](https://blog.mapbox.com/indoor-navigation-in-ar-with-unity-6078afe9d958) that might help you.
The project on that blog post has been developed with an older version of our SDK. So, I would highly recommend porting that work over to the our latest SDK so that we can help you better.
[Here's a guide](https://www.mapbox.com/unity-sdk/overview/migrate-version/) on how to migrate to the latest SDK.

**Comment by tarakinsuide** [comment]
Hi Adarsh,

Which code should I share specifically? Should I share my Unity project here?

**Comment by tarakinsuide** [comment]
Here are the inspector view of my ArAlignedMap 

![inspector1](https://user-images.githubusercontent.com/34171415/39037837-5865789c-449f-11e8-9883-4049fd52fbca.png)
![inspector2](https://user-images.githubusercontent.com/34171415/39037839-59240ff0-449f-11e8-872c-ec13b3ab51e3.png)
![inspector3](https://user-images.githubusercontent.com/34171415/39037841-5aed888e-449f-11e8-95cf-861219d810ee.png)

**Comment by tarakinsuide** [comment]
![mapbox_issue](https://user-images.githubusercontent.com/34171415/39177304-91349ae2-47cc-11e8-8b9c-a9989e015733.png)
I'm trying to remove or edit those blue building walls so that only the AR GameObject is visible to me, which in this case is a pink box.

**Comment by lauri-rustanius** [comment]
Hi @tarakinsuide, you can disable the buildings from being rendered in the `AbstractMap` script in the editor by removing `building` Vector Layer Visualizer. I recommend reading these examples through to get a sense of the SDK's work flow: https://www.mapbox.com/unity-sdk/overview/city-simulator/

**Comment by tarakinsuide** [comment]
Thanks I tried it and the walls disappeared. But, now I can't change the manual position of my device. It always starts at the same point. Why?

**Comment by lauri-rustanius** [comment]
Can you clarify? Do you mean the map location? If so, the map is spawning to the initial GPS location provided by the `LocationProviderFactory`. You can add your own location for the map to spawn into as you wish. Check the `UpdateMap()` method in the `AbstractMap` class.

**Comment by jordy-isaac** [comment]
@tarakinsuide Have you tried to taking a look at the properties of the buildings in the vector layer visualizers? You can see what each setting does here. You can change the `Extrusion Geometry Type` to remove the walls only.

https://www.mapbox.com/unity-sdk/overview/data-explorer/#buildings

However, as mentioned in previous tickets, you'll face quite a bit of challenges with indoor mapping and the implementation will be up to you. Thanks for understanding!

**Comment by tyrroncondo14** [comment]
hi guys sorry for opening the closed issue. I am reading the guide for mapbox tabletop ar that is in this link  https://www.mapbox.com/unity-sdk/maps/examples/tabletop-ar/  but whenever i build and run the project, the project look like this on my android phone. I followed the steps carefully but it still not working can u help me guys please?? i only start studying AR about a week ago and I really don't know what to do.  I just want  to use my device camera as the main camera

![image](https://user-images.githubusercontent.com/29406798/48942699-996e3880-ef5b-11e8-93b1-9f415cc751a1.png)
