### ISSUE TITLE
Can I get the elevation data through https://www.mapbox.com/blog/terrain-rgb/

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-unity-sdk#69]
In Unity is Height Data, but it gets the elevation data is right?
height = -10000 + ((R * 256 * 256 + G * 256 + B) * 0.1)

**Comment by Spaxe** [comment]
You can see how it's done here: https://github.com/mapbox/mapbox-unity-sdk/blob/6e5ef80510db0a76817c187fc4dd76ff9fb32fd9/sdkproject/Assets/Mapbox/Core/Unity/MeshGeneration/Factories/TerrainFactory.cs#L416

```        
private float GetHeightFromColor(Color c)
{
    //additional *256 to switch from 0-1 to 0-256
    return (float)(-10000 + ((c.r * 16777216 + c.g * 65536 + c.b * 256) * 0.1));
}
```

**Comment by veyvin** [comment]
@Spaxe 3thx
