### ISSUE TITLE
Polygon extrusion types aren't intuitive

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#690]
**Problem**
Extrusion types under polygon settings aren't intuitive and probably need some tooltips. I was looking for the "flat roofs" option we had before and took me a while to realize min/max height options are technically it. 

maybe we can add it to "extrusion type" tooltip?

![unity_2018-04-18_14-52-44](https://user-images.githubusercontent.com/1465390/38930323-2c400454-4318-11e8-98e5-281af1ef3162.png)

cc @atripathi-mb @isiyu

**Comment by MiroMuse** [comment]
1.4.1 now includes a tooltip for this, so it's complete. Thank you for highlighting @brnkhy!

**Comment by brnkhy** [comment]
I think you misunderstood @MiroMuse, issue isn't the tooltip itself but finding how to flatten rooftops. Default option, `PropertyHeight` creates sloped rooftops. Min/Max Height options (pretty much equivalent of old "flat rooftops" settings pre v1.4) creates flat roof tops but there's no way of knowing that.

**Comment by brnkhy** [comment]
@atripathi-mb 
oh wow I had no idea that you can actually hove the dropbox itself for selected item tooltip so I was hovering the "extrusion type" label on the left. Totally my bad, sorry about that @MiroMuse 
closing this again.
