### ISSUE TITLE
Simple Way to Remove Objects at specific lat/long by touching

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#691]
* Unity version: 4.0.1
* Mapbox SDK version: 1.4
* A description of what you're trying to do:
  I'm trying to find a simple way to remove/move objects that I had been putting them at specific 
  lat/long by touching screen on mobile.
  what should I  do??

**Comment by jordy-isaac** [comment]
Hi @willychang21 Without being too certain of your use case I would suggest you check out Unity's docs for [destroying](https://docs.unity3d.com/ScriptReference/Object.Destroy.html) and [moving](https://docs.unity3d.com/ScriptReference/Transform.Translate.html) game objects. 

We might have some better ideas if you let us know some more details about what you're trying to accomplish. Thanks!
