### ISSUE TITLE
Add documetation links to inspectors

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#692]
**Problem**

property names aren't intutive sometimes,.Help boxes clutter the UI and long descriptions doesn't work well with tooltips. Also it's not possible to add tooltips on dropbox menu options.

This occured to me when I was checking #690 and I think we can solve this problem and increase the usability of the SDK quite a lot with a change in the inspector.

**Proposed Solution**

Idea originates from HelpUrl attribute of Unity. If you pust this attribute on top of a monobehaviour, Unity uses that URL for help button int inspector automatically;
`[HelpURL("https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.AbstractTileProvider.html")]`
![unity_2018-04-18_15-05-34](https://user-images.githubusercontent.com/1465390/38930846-f5c600ca-4319-11e8-8d28-5f5b01da77c9.png)
(help button at top right)
we actuall8 even have an old branch trying that out here; https://github.com/mapbox/mapbox-unity-sdk/commits/helpURLs

that's one option but we can improve that even more, it won't be travial but I feel like would solve a lot of problems for us; (photoshopped this show below)
![unity_2018-04-18_15-07-29](https://user-images.githubusercontent.com/1465390/38931033-897437ce-431a-11e8-8158-963d36d92c52.jpg)
we can add a custom attribute on properties and then wrap them in another container with help button in the inspector. Then that button will direct developers to the exact page&point in the online documentation and we'll be able to write pages of explanation if necessary. This helps us a lot as well because writing a few paragraphs of explanation is a lot easier than going into inspector code and try to make it intuitive or add help boxes.

It might be an overkill to have button for individual properties, so we still have that first option (one link at the top of the script). It's so much easier but won't work as good because then people will have to search again in the website to find what they are looking for. i.e. abstract map help link will open the abstract map page but extrusion types might not be in that page at all. So I think per-property option would be a lot more useful.

cc @atripathi-mb @isiyu @MiroMuse @jordy-isaac

**Comment by atripathi-mb** [comment]
@brnkhy with 1.4.1 we should have tooltips for every setting on the UI. If there is still some setting without a tooltip let fix that.

I like the helpURL idea for the panel. We should definitely do that.

We discussed the help url for every setting idea early in our design and decided to go with tooltips because it seemed an overkill to add a button to every setting.
