### ISSUE TITLE
Road Names as Vectors

### ISSUE THREAD

**Issue by emorling** [mapbox/mapbox-unity-sdk#698]
How do you get the road names on the map as vectors? Like we see going on here:

https://www.mapbox.com/designer-maps/#decimal

Thanks

**Comment by brnkhy** [comment]
@emorling there are separate layers for road/place/country etc names. 
In this case, road names can be found in `road_label` layer. You can open DataExplorer scene, active `RoadLabel` layer under Vector data. 
Then you'll see one GameObject modifier in the list but I think there's a mistake here so you'll have to change it to something like `ExplorerCountryLabelPrefabModifier` and it'll create road labels on your map. 

it should look like this;
![aspowerbar_2018-04-19_15-14-31](https://user-images.githubusercontent.com/1465390/38990821-640d769c-43e4-11e8-9402-00fe1552cad7.png)

**Comment by jordy-isaac** [comment]
You can also find out more about roads and other features in the documentation [here](https://www.mapbox.com/unity-sdk/overview/data-explorer/#roads)

**Comment by emorling** [comment]
@brnkhy I did not get the part about "Then you'll see one GameObject modifier in the list". What list exactly?
