### ISSUE TITLE
unity built as Andorid apk crashed

### ISSUE THREAD

**Issue by macro-shen** [mapbox/mapbox-unity-sdk#70]
a developer in China is using Mapbox Unity SDK, he bulit the project in unity as a andorid apk. 
But it crashed when opening it after installed on android phone.
Do you know why? Following is screenshot:
![image](https://cloud.githubusercontent.com/assets/1848550/26101903/5e860cc2-3a65-11e7-95c4-3bfc5a4b3faf.png)

**Comment by david-rhodes** [comment]
@macro-shen Unfortunately, I do not see anything in this log that suggests the Mapbox SDK is at fault. However, if you can provide more details, we may be able to assist.

- What device is this running on? Does it successfully run on any device?
- Was this built from a custom unity project? Or is this built from our included project? If so, what scene is being loaded first?
- What version of the SDK is being used?
- What version of Unity is being used?

Thanks!

**Comment by macro-shen** [comment]
@david-rhodes thanks. The developer can using Mapbox Unity SDK now. I told them the way from @isiyu suggestion: https://github.com/mapbox/games/wiki/Unity-Android-build
