### ISSUE TITLE
How to create `gradient material` by value?

### ISSUE THREAD

**Issue by tayalav** [mapbox/mapbox-unity-sdk#700]
Hey there!
Could you help, please
How to create `gradient material` by value?
Could you share `PopulationMat` which you mention here, please :pray: https://www.mapbox.com/unity-sdk/overview/data-explorer/

**Comment by apavani** [comment]
That project is on this branch
https://github.com/mapbox/mapbox-unity-sdk/tree/PopulationDensityDemo

These lines of code do the gradient
https://github.com/mapbox/mapbox-unity-sdk/blob/PopulationDensityDemo/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Modifiers/MergedModifierStack.cs#L150-L154

**Comment by jaskiratr** [comment]
Hi @apavani,
I'm quite new to Unity and I'm trying to implement data-driven styling by applying a color ramp to buildings based on a property. Not sure how to apply the `MergedModifierStack` with the following setup. 
Unity version: `Unity 2018.13f1`
Mapbox SDK: `v2.1.1`

In the Map prefab, I don't see an option for the MergedModifierStack under Mesh Modifiers or Game Object Modifiers.
![image](https://user-images.githubusercontent.com/8619877/70855903-7719c680-1ea0-11ea-91e3-9ea5c3796886.png)

Any guidance would be appreciated! 🙏

**Comment by jaskiratr** [comment]
Sorry. I figured it out. Had to enable Combine Meshes.
