### ISSUE TITLE
Weird scaling of objects?

### ISSUE THREAD

**Issue by juicef** [mapbox/mapbox-unity-sdk#701]
Hi. I'm trying to use a pool of objects in conjunction with the Unity API. One issue I encounter is that tiles scale gameobjects and while I do reset the transforms of the pooled objects, I still get an offset of the perceived position. Looking closer at the transforms, I see that some scaling has taken place. 

Do you have any experience with something similar to this issue?

**Comment by jordy-isaac** [comment]
@juicef Can you let us know more about your use case, what you're seeing and how we can reproduce the issue?
