### ISSUE TITLE
Rotating the camera in LocationProvider

### ISSUE THREAD

**Issue by UlisesPereida** [mapbox/mapbox-unity-sdk#708]
Unity 2017.3.1
MapBox 1.3

I can't use version 1.4 because the ARCore library tries to overwrite files from the version of ARCore I already integrate. Is there a way to rotate the camera in the scene LocationProvider without having the tiles disappear depending on the angle of the camera?

**Comment by UlisesPereida** [comment]
Can I actually just import the Mapbox folder and ignore the rest if I'm not interested in the AR stuff? Why is the example scene location provider not longer included in this version? Does the location provider prefab works the same?

**Comment by jordy-isaac** [comment]
Hi @UlisesPereida there are some major changes in 1.4 that you'll need to account for. If you want to upgrade we have a [guide for migrating from 1.3](https://www.mapbox.com/unity-sdk/overview/migrate-version/). You'll need to follow that to migrate and not just decline to import the AR folders. 

We still have a location provider example and now it's called `LocationBasedGame`. You can also see the write up of that example [here](https://www.mapbox.com/unity-sdk/overview/location-based-game/).

**Comment by UlisesPereida** [comment]
So I made the upgrade to 1.4, I don't know if I missed something in the migration process (went back to check it) but when I'm testing, the map is loading the incorrect location, is not the default one of San Francisco and also not my current location. I made sure to enable the location permission in my device and is still loading an unknown location (I don't recognize the location the map is loading).

**Comment by jordy-isaac** [comment]
@UlisesPereida Which example scene are you using? You can specify any lat lon on the AbstractMap script on the map.
