### ISSUE TITLE
Remove walls in AR

### ISSUE THREAD

**Issue by nshaposhnik** [mapbox/mapbox-unity-sdk#709]
So the question is self-explanatory, is it possible to remove walls from AR view in WorldScaleAR scene?

**Comment by willychang21** [comment]
@nshaposhnik  I suggest u can take a look https://docs.unity3d.com/ScriptReference/Object.Destroy.html
doc

**Comment by jordy-isaac** [comment]
Hi @nshaposhnik Can you let us know a bit more about what you're trying to accomplish and what you've tried so far? This will help us get you the right info.

**Comment by tarakinsuide** [comment]
Hi @jordy-isaac I think he's trying to talk about the same problem which in mentioned in the last comment on this thread. Please check out and assist: https://github.com/mapbox/mapbox-unity-sdk/issues/681

**Comment by nshaposhnik** [comment]
Yes, that's what I meant, and comment from there worked for me. Thank you!
