### ISSUE TITLE
WorldScaleAR provide custom device position using IndoorAtlas

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#714]
Hello,

I'm using IndoorAtlas to get indoor position of my device. How do I use that position in the WorldScaleAR to build indoor AR. I've tried WorldScaleARManual and it gave satisfactory results. Now I need to give real location of my device at an instant using my location service provider. What changes will I have to make and any resources that might help me?

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
@tarakinsuide IndoorAtlas is a bit out of the scope of our support here, but I did find some documentation on positioning for you: https://docs.indooratlas.com/develop/positioning-api/

You can check this section of our [documentation for World-scale AR](https://www.mapbox.com/unity-sdk/overview/world-scale-ar/#running-in-the-editor) to see how we use GPS to position currently. 

With indoor mapping you'll run into challenges getting accuracy in general with the current state of AR industry wide. It will largely depend on your device, GPS signals, or use of expensive beacons. We talked about this with our indoor mapping demo here: https://blog.mapbox.com/indoor-navigation-in-ar-with-unity-6078afe9d958

Positioning and orientation are things that we're working on improving now and Mapbox is committed to push AR forward.

**Comment by tarakinsuide** [comment]
Let's say I'm getting a latlong from the beacons and my third party location service provider, how can I use it in mapbox AR? Is there any script for it? 
Like for worldscaleAr scene we had a location provider or we also used manual alignment, so in same way can I use those scripts with my location?
