### ISSUE TITLE
How to use custom indoor positioning location

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#715]
Let's say I'm getting a latlong from the beacons and my third party location service provider, how can I use it in mapbox AR? Is there any script for it?
Like for worldscaleAr scene we had a location provider or we also used manual alignment, so in same way can I use those scripts with my location?

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
@tarakinsuide The world scale ar example scene could be used as a starting point. See the blog post to show how we used sync points to localize in our indoor mapping demo.

https://blog.mapbox.com/indoor-navigation-in-ar-with-unity-6078afe9d958

**Comment by haz2017** [comment]
https://blog.mapbox.com/indoor-navigation-in-ar-with-unity-6078afe9d958 
It's getting many compilation errors when trying to open the source code in here with unity ..  :( Please provide any help :(
