### ISSUE TITLE
Zooming with a lot of custom objects

### ISSUE THREAD

**Issue by emorling** [mapbox/mapbox-unity-sdk#719]
I have a Map with a lot of custom GameObjects added to a tile. However, zooming really fast can both congest the map and produce some weird effects.

During zooming between levels OnRegistered() is called in AbstractMap, which in turns is responsible for creating custom GameObjects in a UnityTile using StartCoroutine .

What is the best way for creating lots of custom game objects while zooming? And provide a smooth experience.

Any help would be appreciated

**Comment by jordy-isaac** [comment]
Hi @emorling, and thanks for the ticket. Can you let us know about the GameObjects that you're spawning in and how you're instantiating them into the scene? With a little more info we might have some things to try to help improve performance.

**Comment by emorling** [comment]
@jordy-isaac Thanks. Most of them are GameObject(s) that are using a LineRenderer. Others are just Image(s) functioning as markers on the map. The concern is that they are quite in many in our application. The choking happens when the zoom level changes, because at that time new tiles are created. If you zoom very speedily you may swap between multiple zoom levels. I am uncertain if the map will continue to create game objects for a zoom level already has been discarded? Also thinking that it may be better to not create game objects at all until user has stopped zooming? Ideas?

**Comment by emorling** [comment]
@jordy-isaac I think it would be interesting to be able Zoom in and out using the Tile(s) that already exist. Especially since we're using vector layers. Once the user stops zooming it would be interesting to load in the correct Tile(s) and populate them with gameobjects. Any thoughts? How would we tackle this?

**Comment by atripathi-mb** [comment]
@emorling 
> Most of them are GameObject(s) that are using a LineRenderer. Others are just Image(s) functioning as markers on the map

Are these vector features coming from a mapbox tileset ? Or prefabs/gameobjects that you are spawning at certain lat longs? 

We do object pooling to avoid lot of loading and unloading during zoom in/out but gameobjects are costly to spawn. 

The map updates when the camera script triggers `UpdateMap`, which you can control based on your application needs.
