### ISSUE TITLE
Geolocate one object placed in hierarchy

### ISSUE THREAD

**Issue by asevillanom** [mapbox/mapbox-unity-sdk#721]
Hi! 
I have 2 questions:
1. How can I geolocate in the map (adding latitude and longitude) one object placed in the hierarchy?
2. I've seen the SpawnOnMap.cs script in examples but I have a lot of different prefabs to spawn. How could I do?
Thanks in advance.

**Comment by jordy-isaac** [comment]
From the looks of https://github.com/mapbox/mapbox-unity-sdk/issues/722, it seems you figured out how to use SpawnOnMap. Closing this out and we'll address your other questions on the ticket above.

**Comment by asevillanom** [comment]
Sorry, but I think #721 and #722 are different problems. Could you help me?
