### ISSUE TITLE
2 problems with triggers when I spawn objects

### ISSUE THREAD

**Issue by asevillanom** [mapbox/mapbox-unity-sdk#722]
I have detected 2 problems:

1. I'm using SpawnOnMap.cs script to spawn a prefab in multiple positions. The prefab have a script with OnTriggerEnter to detect the player and make stuffs. The problem is when the scene starts all the triggers enables.  

2. When I use QuadTreeCameraMovement.cs to make zoom like in the ZoomableMap example the colliders of the objects going bigger to make zooming and the trigger radius changes. It can be an issue.

How can I fix these problems?

**Comment by asevillanom** [comment]
Sorry, but I think #721 and #722 are different problems. Could you help me?

**Comment by asevillanom** [comment]
Ok. In my game the player has to found multiple objects in the city. These objects are differents and are geolocated in the map. When the player enters in the trigger of each one the camera of the mobile opens, he can take a photo and gain points.

**Comment by asevillanom** [comment]
Now, I only can spawn one prefab with SpawnOnMap.cs and I need to spawn more. And when I starts the game the camera opens directly before the player going to the object

**Comment by asevillanom** [comment]
And when I use QuadTreeCameraMovement.cs to make zoom, for example, the map size changes but not the colliders of the objects.

**Comment by jordy-isaac** [comment]
@asevillanom Please have a look at the ZoomableMap example in the SDK. You can also see the documentation for it here: https://www.mapbox.com/unity-sdk/overview/zoomable-map/#place-custom-markers

As you can see in the screenshot below, on the script is an array. If you change the `Size` you can add new elements to the array to spawn multiple game objects. Here is also where you specify the lat/lon where it will be instantiated. 

<img width="379" alt="screen shot 2018-05-01 at 10 53 42 am" src="https://user-images.githubusercontent.com/33474236/39485640-3a2def66-4d2e-11e8-96bc-9051a758ac4d.png">

As for the size of your game objects, one approach would be to programmatically change the scale to match what you need based on zoom level.

**Comment by jordy-isaac** [comment]
@asevillanom In that case it would be best to use another instance of `SpawnOnMap` for the other prefab(s).

As for changing the scale to match the zoom level, we don't have a code example but you would need to get the value of `AbstractMap.Zoom` or `AbstractMap.AbsoluteZoom` from the `AbstractMap` script and then change the value of `_spawnScale` on `SpawnOnMap` to the value appropriate for your game object given the zoom level returned.

I hope this helps!

**Comment by asevillanom** [comment]
Thank you very much @emorling ! I've replaced it but this error appears:

transform.localScale assign attempt for 'tesoro_1PUNTO----(Clone)' is not valid. Input localScale is { Infinity, Infinity, Infinity }.
UnityEngine.Transform:set_localScale(Vector3)
Mapbox.Examples.SpawnOnMap_LIST:Update() (at Assets/_TES/Scripts/SpawnOnMap_LIST.cs:73)

**Comment by asevillanom** [comment]
@jordy-isaac And how can I fix the problem when the scene starts all the triggers enables?

> .... And when I starts the game the camera opens directly before the player goes to the object. I think the prefab is instantiating in the same place that the player on starts but after moves to the coordinates I have set.

**Comment by jordy-isaac** [comment]
@asevillanom Can you share a video of whats happening? This might help us get a sense of what's happening.

**Comment by jordy-isaac** [comment]
Closing this for now, but please re-open with additional info or a min test case if you're still having trouble.
