### ISSUE TITLE
Low Poly terrain does not generate side walls. 

### ISSUE THREAD

**Issue by abhishektrip** [mapbox/mapbox-unity-sdk#728]
When choosing the low-poly terrain option with the side walls toggle, no side walls are generated.

**Comment by brnkhy** [comment]
@atripathi-mb Oh I'm afraid this is expected. Low poly terrain triangle indexing was quite confusing so I skipped that but I looked over the fact that option will still be there.
I can look into this but I'm afraid it won't be trivial.
