### ISSUE TITLE
If "Extrusion Type" = None, don't render a mesh

### ISSUE THREAD

**Issue by morgane** [mapbox/mapbox-unity-sdk#732]
In Abstract Map's Vector section:

![screen shot 2018-05-04 at 10 40 45 am](https://user-images.githubusercontent.com/104024/39642783-9ebb3e10-4f87-11e8-8517-5fbf057dc224.png)

If Extrusion Type is none, we can assume we _don't_ want to show a mesh at all (right now it still will, and causes a lot of z-fighting). We can also remove/disable Scale Factor, since it won't do anything.

**Comment by brnkhy** [comment]
We talked about this with @greglemonmapbox before as well. I still think flat features are important, both for 2d maps and for layers like water and landuse. 
Alternative option is to have both flat and none options there but I feel like the option to hide a feature shouldn't be under `extrusion type`.
Maybe we can change "Material Options" title to a checkboxed title and do not render it if it's unchecked?
