### ISSUE TITLE
Order of Vector Layers

### ISSUE THREAD

**Issue by emorling** [mapbox/mapbox-unity-sdk#739]
What is the best way to control the order of vector layers? i find sometimes water is beneath roads, and other times above.

**Comment by jordy-isaac** [comment]
Hi @emorling Can you let us know what tile or show a screenshot of where the water is above the roads? Also, do you have `Group Features` enabled? Here's some more information on our [vector layers](https://www.mapbox.com/unity-sdk/overview/data-explorer/#roads).

**Comment by brnkhy** [comment]
@emorling assuming you're doing 3D, best option here is to use the y axis for layer ordering. 
For example, you can set water layer to `absolute height` extrusion with the value of 1 and road to `absolute height` with 2.
