### ISSUE TITLE
adjust elevation of viewer/player in World-Scale AR?

### ISSUE THREAD

**Issue by thecommonegret** [mapbox/mapbox-unity-sdk#740]
Unity version: 2018.1.0f2
Mapbox SDK: 1.4
Building to: Android

Hi, I am using Mapbox's World-Scale AR scene to test out the building visualizer (to eventually bring in other custom data to visualize). Can one adjust the elevation of the 'player' as I am trying to use it while looking out onto NYC from a 23rd floor balcony but the AR buildings are appearing as if I am at street level?

Thank you,
Matthew

**Comment by jordy-isaac** [comment]
Hi Matthew - 

This would be possible, but the implementation of it would be up to you. Something like this would require some math involved with scale, angle of viewing and the horizontal and vertical distance from the real world ground plane. It would be a bit more involved than adjusting the Y axis of the player.

**Comment by thecommonegret** [comment]
Hi Jordy,

Currently I'm just trying to get the building visualizer to line up (before bringing in custom data such as NYC's street tree dataset). The attached image shows an AR World Scale Manual Alignment view from my balcony. As you can see the blue building material is being displayed as if I am at street level. How might one go about resolving this?

Thank you for your help,
Matthew
![screenshot_20180510-191203_arman2](https://user-images.githubusercontent.com/39036160/39961598-a8712dc6-5607-11e8-90dd-9729aba4d629.jpg)

**Comment by jordy-isaac** [comment]
Hi Matt. As mentioned this would require some custom code/math to adjust scale and angle to get the desired elevation effect. Implementation of this would be up to you.
