### ISSUE TITLE
Example Scenes are not streaming the data

### ISSUE THREAD

**Issue by deltamish** [mapbox/mapbox-unity-sdk#741]
Hey,

Downloaded and set up Map box as per the instructions provided on the website. 
When loaded the scenes the scene remains blank.
In the Citysimulation scene. The scene has just flat grid texture layed out on a plane and reamins that way forever. Similarly the DataExplorer is just displaying the Loading scene.
All while getting the following error 

And Yes I tried clearing the cache. 
`ArgumentException: path
System.IO.DirectoryInfo.CheckPath (System.String path) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.IO.DirectoryInfo..ctor (System.String path, System.Boolean simpleOriginalPath) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:.ctor (string,bool)
System.IO.Directory.CreateDirectoriesInternal (System.String path) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.IO.Directory.CreateDirectory (System.String path) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
Mapbox.Platform.MbTiles.MbTilesDb.openOrCreateDb (System.String dbName) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:156)`

**Comment by BergWerkGIS** [comment]
> * Unity version:  ????
>  * Scripting Runtime Version: ????
>  * Scripting Backend: ????
>  * Api Compatibility Level: ????

@deltamish are you using the experimental .Net runtime 4.6?
There is a known issue that breaks tile downloading and caching.

**Comment by deltamish** [comment]
Yes. I'm using .Net runtime 4.6 since its the only version that supports ML agents

Any workaround for this ?

**Comment by BergWerkGIS** [comment]
This should help: https://github.com/mapbox/mapbox-unity-sdk/issues/653#issuecomment-380494379

**Comment by ophilbinbriscoe** [comment]
Am I missing something? That thread seems to end with the conclusion that 4.6 is out of the question for the time being.

**Comment by BergWerkGIS** [comment]
@ophilbinbriscoe can you elaborate on the problem you are facing (in a new issues please)? 
Latest release has the problem of the OP fixed.
