### ISSUE TITLE
Using WMS with the Mapbox Unity SDK

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#742]
Is it possible to include data from a WMS serves through the Mapbox Unity SDK? How would one go about doing it?

**Comment by BergWerkGIS** [comment]
WMS is not supported out of the box, only WMTS.

But I think it shouldn't be a big problem to write an adapter that takes tile requests `{z}/{x}/{y}` and translates that into WMS requests where the bounding boxes equal the tile extents (helpful methods can be found in the `Mapbox.Unity.Utilities.Conversions` class).
Note: Your WMS would have to serve WebMercator tough.

Or try to integrate an existing solution that does that already, eg:
https://github.com/BruTile/BruTile#supported-tile-service-protocols
> WMS (tiled requests to a regular WMS)

**Comment by JorgenEngenNapstad** [comment]
Thanks @BergWerkGIS I will look into both solutions.

**Comment by BergWerkGIS** [comment]
Sorry @JorgenEngenNapstad but taking a closer look this is a lot more involved than I had anticipated at first glance.
While Mapbox tiles follow the OSM tiling schema our logic is tied to the `mapbox://` protocol.
We don't have anything place to support custom `http(s)://` resources.

You'd have to implement that starting at the lowest levels of the SDK (eg [TileResource.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/TileResource.cs), [ClassicRasterTile.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Map/ClassicRasterTile.cs), ...) through the middle layers (eg [ImageryLayer.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/SourceLayers/ImageryLayer.cs)) up to [AbstractMap.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Map/AbstractMap.cs) to get it exposed in the Inspector.
