### ISSUE TITLE
Smooth(er) zooming

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#743]
Is there any way of achieving the same smooth zoom effects that you have in Mapbox Studio, where the map is being updated based on floats, and not only integer zoom levels?

When comparing the map implemented in Unity with the one in Studio it feels like a lot of the "finesse" of the map disappears.

**Comment by jordy-isaac** [comment]
@JorgenEngenNapstad Thanks for the feedback! Zoom is currently a float value in the SDK, but we'll be working on improving zoom performance in the future.

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad have you looked at the `ZoomableMap` example in the SDK?
That's as smooth as it currently gets.
Studio is using the same (int) based zoom levels as the SDK but you are right the transition there has a lot more "finesse". 😄 
We plan on improving the transition but currently it's low priority will at least be several months out.

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS Yes, we have replicated and modified this example for our own use. I was just wondering if I had missed something which could make it even smoother, but you answered my question, thank you.

**Comment by MohamadMousheimish** [comment]
Is there any smooth zoom functionality now in unity mapbox sdk?

**Comment by MangkorN** [comment]
@JorgenEngenNapstad @MohamadMousheimish I have implemented the smooth movement! Feel free to use this: [QuadTreeSmoothCameraMovement.cs](https://github.com/MangkorN/mapbox-unity-sdk_misc-improvements/blob/develop/sdkproject/Assets/Mapbox/Examples/Scripts/QuadTreeSmoothCameraMovement.cs)

Additionally, I have also included an example scene with the script above in action. Feel free to clone the repo, [here's the commit details](https://github.com/mapbox/mapbox-unity-sdk/commit/e00113df5fbfa558c8f684212ef4a400080687cf)
