### ISSUE TITLE
How to import dataset from CARTODB

### ISSUE THREAD

**Issue by joelin1415** [mapbox/mapbox-unity-sdk#745]
Hi everbody , please how to import points from cartodb, its a simple URL json request 

example
http://andrew.cartodb.com/api/v2/sql?q=SELECT%20*%20FROM%20cambridge_buildings

view
<a href="https://ibb.co/eXiDPS"><img src="https://preview.ibb.co/drQhJn/34544283_56b80a52_f0dd_11e7_84ff_19e8dc11f346.png" alt="34544283_56b80a52_f0dd_11e7_84ff_19e8dc11f346" border="0"></a>

many thanks

**Comment by jordy-isaac** [comment]
Hi @joelin1415 

You can use your own data with a custom tileset using the Maps SDK for Mapbox Unity. To do so, you'll need to first create a dataset and export it to a tileset using Mapbox Studio. Once you do you can specify the tileset as your data source on the AbstractMap script.

You can check out the documentation here: https://www.mapbox.com/unity-sdk/overview/data-explorer/#custom-data
