### ISSUE TITLE
Can't update location in Unity Inspector during runtime

### ISSUE THREAD

**Issue by pytan-coder** [mapbox/mapbox-unity-sdk#751]
I'm new to Mapbox and I can't seem to update the location through Inspector in the examples given, specifically the LocationBasedGame example. I'm updating the coordinates through the Search function in the LocationProvider > Editor. Shouldn't it be straightforward to update the location? Am I assuming it is that simple? Thanks for any feedback. Much appreciated.

**Comment by jordy-isaac** [comment]
@pytan-coder Thanks for the ticket. For the LocationBasedGame example you can change the location in the editor by changing using the `Search` function or specifying the `Latitude Longitude` inside of `EditorLocationProvider` script. 

<img width="644" alt="screen shot 2018-05-14 at 7 58 57 am" src="https://user-images.githubusercontent.com/33474236/40005456-d0a05754-574c-11e8-9e0e-9931d748c0a8.png">

When on a device the location will be the GPS coords of the device running the example. I hope this helps.
