### ISSUE TITLE
Filter poi by type.

### ISSUE THREAD

**Issue by hopyou** [mapbox/mapbox-unity-sdk#753]
Hi,
I want to only display certain types of poi on the map (stores, restaurants, etc).

Can anyone tell me how to achieve this?

**Comment by LeoSonnekus** [comment]
Hi is there a way to do this on web?

I'd like to toggle different types of POI with HTML inputs similar to this 

https://github.com/mapbox/analysis-demos/tree/mb-pages/nyc-attractions/

**Comment by atripathi-mb** [comment]
@LeoSonnekus Have you looked at Mapbox JS SDK ? https://docs.mapbox.com/mapbox-gl-js/examples/
