### ISSUE TITLE
android.speech API

### ISSUE THREAD

**Issue by matteo-interfase** [mapbox/mapbox-unity-sdk#764]
Hello, I'm building an app that has to run on an Oculus Go, which doesn't support the speech API.
The Oculus platform rejected my build for this reason:

> This app uses the speech API, which is not supported on this device.
> Your application is using "android.speech.action.RECOGNIZE_SPEECH","android.speech.action.WEB_SEARCH"

I know mapbox doesn't officially support VR headsets but I was wondering if there's a way to configure it in order to avoid having calls to such API (wich I don't need in my project) in my final build. I've tried searching for those calls inside the mapbox plugin folder but couldn't find any.

Thank you!

**Comment by jeffrobernard** [comment]
Matteo,
I’m interested in this as well. I’m building for he go as well did it reject the build on final submission to oculus or did it reject the build from building it from unity to the GO?

Kindest Regards,

Jeff Bernard

**Comment by matteo-interfase** [comment]
Hi Jeff,
if I build the application directly in the headset via USB I have no issues, the problem is when I upload the apk to the Oculus developer platform, it goes through an automatic service that detects which libraries your application is using in order to tell you what to change in order to be sure that the app will work on the target devices. The alert goes off just for the Oculus Go, for the Gear VR there's no issue (because every android phone supports that API).
The apk is rejected even if you upload it on the alpha channel, I'm not even close to the final submission 😃

**Comment by jeffrobernard** [comment]
Hmmm interesting. Well, when you figure it out, if you don’t mind sharing how your fixed it, that would be a huge help. 

Kindest Regards,

Jeff Bernard

**Comment by BergWerkGIS** [comment]
@matteo-interfase @jeffrobernard 

I'm not aware that any part of our SDK references the speech API.

My only hunch at the moment is that maybe `GoogleARCore` uses it.

For AR (everything in folder `MapboxAR`) we depend on `UnityARInterface` which in turn depends on `GoogleARCore`.

Depending on how your project is setup (not using anything from `MaboxAR`) you could try deleting theses folders:

* `GoogleARCore`
* `MapboxAR`
* `UnityARInterface`
* `UnityARKitPlugin`

**Comment by BergWerkGIS** [comment]
Upon further inspection this might be connected to an undocumented define.
Looking at the generated `*.csproj`s I see a define called `ENABLE_MICROPHONE`.
Unity seems to enable the microphone per default - or the define is being triggered by another setting.
Haven't found a way to get rid of it.

`ENABLE_MICROPHONE` isn't mentioned in the [`PlatformDependentCompilation` docs](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) either but has been observed by other users too: https://forum.unity.com/threads/undocumented-unity-controlled-define-symbols.239232/
