### ISSUE TITLE
Hide object behind building?

### ISSUE THREAD

**Issue by Ben-Tai** [mapbox/mapbox-unity-sdk#770]
Hi there, I'm using the WorldScaleAR example with SpawnOnMap.cs to generate object by lat/long. 

I need some help to try to accomplish a couple of things with a project. 
I'm wondering how I might only make this object visible if its not obstructed by buildings, or vice-versa having if invisible if it is behind a building? Say if I wanted to place a large object the next street over from me, i should only see its top half because the bottom half should be behind the buildings. 
as seen in David Rhodes vid here: https://twitter.com/davidrhodester/status/892501191875190784?lang=en

Also I want to place an object at the top of a mountain, how do I factor in the elevation so that he appears at the top of the mountain? and scale so that if i look at the object from far away it is smaller but huge when up close? 
 
Im very new to the whole stack so any help would be appreciated.

support ticket
Running latest version of unity and mapbox api.
Building out to mobile

**Comment by Ben-Tai** [comment]
Elevation:  So I see that if I set my ``ArAlignedMap``  elevation layer type, to ``terrain with elevation``  then that solves the item spawn problem, but then the AR camera is loading below the map which I'm guessing might be sea level? Any ideas on how to fix this?

Also whats the best way to improve AR camera direction?? would it be possible to manually align with the mountain??

Thanks

**Comment by jordy-isaac** [comment]
@Ben-Tai We're working on localization and are aiming for incremental improvements. Have you tried the [Manual alignment](https://www.mapbox.com/unity-sdk/overview/world-scale-manual-align-ar/) example?

**Comment by atripathi-mb** [comment]
@Ben-Tai 
>I'm wondering how I might only make this object visible if its not obstructed by buildings, or vice-versa having if invisible if it is behind a building?

You can achieve this by rendering building with a transparent material, that way the meshes will occlude the object but not appear on screen. 

> Also I want to place an object at the top of a mountain, how do I factor in the elevation so that he appears at the top of the mountain?

Abstract map has a queryHeight method that you can use to offset your player based on the actual elevation of the terrain. 

> and scale so that if i look at the object from far away it is smaller but huge when up close?

This can be achieved by camera perspective and other computer graphics trick. Not something Mapbox SDK provides.
