### ISSUE TITLE
Unity SDK fails to render key features when using custom map style,

### ISSUE THREAD

**Issue by DavidAPC** [mapbox/mapbox-unity-sdk#779]
We've been creating custom map styles in Mapbox Studio. The maps were displaying fine in Unity until recently. Basically, while the style renders fine in Mapbox HTML map viewer, the exact same style is missing features and simply not displaying correctly when used in Unity.

The exact same problem happens if I use a pristine example project from the SDK and simply change the map style in (for instance) ZoomableMap.

For example, here's our map style displaying just fine in a HTML map:
![mapstyleinhtml](https://user-images.githubusercontent.com/6623549/40074149-c18f1e60-5870-11e8-92b7-fd45da92ad5b.jpg)
And here's the exact same map style when rendering in the Unity engine, same location and zoom level.
![mapstyleinunity](https://user-images.githubusercontent.com/6623549/40074150-c1c41c46-5870-11e8-865b-bc4bc980f27c.jpg)

I've tried downloading the latest SDK through Git, and even using the RasterTile example project, but nothing's working. The map simply isn't displaying properly in Unity.

Runing Mapbox unity SDK 1.4.2, building to Windows.

**Comment by BergWerkGIS** [comment]
@DavidAPC have you changed your style recently?
The Unity SDK has ambient caching built in which might not have updated yet.
Try clearing the cache and let me know if you see the missing features afterwards.

![image](https://user-images.githubusercontent.com/4549888/40101450-becc1206-58e7-11e8-99d0-955019e8d2c5.png)

**Comment by DavidAPC** [comment]
Hey, I've cleared the cache, and even tried completely new maps, the issues persist. It seems that if a feature has their opacity set to go to zero at certain zoom levels, then the feature won't appear at all at any zoom level. That's the only pattern I've found between features that do appear (river, pitches) and features that don't (roads, parks)

**Comment by DavidAPC** [comment]
Thank you: mapbox://styles/pablofinquez/cjh1r5uy20oe72rqm94yygf59

I'm not sure this style is exactly the same as the one used in the above images, but it has the exact same problem (roads and other features appear in HTML, but not in Unity). We had the above bug with multiple maps.

**Comment by jordy-isaac** [comment]
It looks like this style is one that has been migrated to [expressions](https://blog.mapbox.com/studio-expressions-design-81012e2dab55). Support for styles using expressions will be coming soon but for now you'll need to use your old style. When you migrate to expressions it creates a migrated copy but also saves your original. You'll want to use the original as your data source for now.
