### ISSUE TITLE
[Enhancement] Range around transform extent type for world position. 

### ISSUE THREAD

**Issue by abhishektrip** [mapbox/mapbox-unity-sdk#783]
Range around transform extent type currently uses the local position of the transform. In some cases, user might want to use the global position of the transform. Example use case - camera is pointing an angle and the maps needs to spawn around the "lookAt" point. Currently the map is drawn at an offset since the local position is being used.

**Comment by supergra** [comment]
Second this request. Just spent hours trying to figure out why this wasn't working. I can't think of any reason why it should ever use the local position. In some cases "position relative to some other transform" might be correct, but the pure local position is going to be an annoying source of bugs.
