### ISSUE TITLE
ScaleAR POI name management problem

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#784]
![image](https://user-images.githubusercontent.com/38349902/40124196-9708941a-595a-11e8-8cb3-178a8e06b671.png)

I used Poilabel modifier to show poi
but every object named by numbers(1,2,3...) ,it's not convenience to manage individual poi
how do I let the poi object named by their feature names like  poi label text ??

p.s
I used custom data source with my map id ,but in the mapbox studio only seems to allow us create 
one layer tileset rather than mutiple layer tileset like mapbox.mapbox-streets-v7.

**Comment by myong3** [comment]
@willychang21 
I had the same problem too.
@jordy-isaac 
Do you have a better way to do this??

**Comment by jordy-isaac** [comment]
@willychang21 @myong3 [Custom tilesets](https://www.mapbox.com/help/studio-manual-tilesets/#tileset-information-page) can only have one layer. However, you can add multiple custom tilesets as data sources in Unity
