### ISSUE TITLE
"Mapbox" Menu not appearing after importing package

### ISSUE THREAD

**Issue by tfine** [mapbox/mapbox-unity-sdk#786]
Unity 2018.1.02f
Mapbox SDK 1.4.2
macOS 10.13.4

Trying to install the Unity SDK on a Mac, but the menu does not appear after importing. The full asset folder is available.

**Comment by BergWerkGIS** [comment]
@tfine SDK should work with all current versions of Unity, I just tried with latest beta `2018.2.0b4`.

Do you see any error messages in the console?

**Comment by tfine** [comment]
Yes, there are three errors on load (two yellow, one red)

YELLOW: Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs(33,18): warning CS0618: `UnityEditor.Build.IPreprocessBuild' is obsolete: `Use IPreprocessBuildWithReport instead'

RED: Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs(33,18): error CS0535: `GoogleARCoreInternal.BuildHelper' does not implement interface member `UnityEditor.Build.IPreprocessBuild.OnPreprocessBuild(UnityEditor.BuildTarget, string)'

YELLOW: Metal: Fragment shader missing texture binding at index 0 (_MainTex / Hidden/GUITextureBlit2SRGB)

**Comment by BergWerkGIS** [comment]
> RED: Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs(33,18): error CS0535: `GoogleARCoreInternal.BuildHelper' does not implement interface member `UnityEditor.Build.IPreprocessBuild.OnPreprocessBuild(UnityEditor.BuildTarget, string)'

That's why it's not working. A bug in `GoogleARCore` preventing Unity from compiling files.

Two options:

1. if you don't need AR support delete these folders:
  * GoogleARCore
  * MapboxAR
  * UnityARInterface
  * UnityARKitPlugin

2. if you need AR apply this fix to `sdkproject/Assets/GoogleARCore/SDK/Scripts/Editor/BuildHelper.cs`
  https://github.com/mapbox/mapbox-unity-sdk/compare/2018-fixes#diff-21e75b07f3ff813cb6f8195f156b5c25

**Comment by atripathi-mb** [comment]
@suraj1988 
If your application does not need AR - delete the folders mentioned above. No need to reimport the package

If you need AR - do not delete folders and apply the patch linked above.

**Comment by JalalJaberi** [comment]
I had the same problem and simply (and temporary) changed the BuildHelper.cs code. Let it implements both versions `OnPreprocessBuild(BuildReport report)` and `OnPreprocessBuild(BuildTarget target, string path)`.

Everything is good now.

**Comment by Emixam23** [comment]
Hey !

I do need AR (MapboxAR) so what should I do? :/

Max

**Comment by aaronmckeehan** [comment]
It appears that this seems to be a problem again. The link to the fix doesn't work any more. Using Unity  2019.1.3f1:

Assets/GoogleARCore/SDK/InstantPreview/Scripts/InstantPreviewManager.cs(32,23): error CS0234: The type or namespace name 'SpatialTracking' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

**Comment by brnkhy** [comment]
@aaronmckeehan 
Unity 2019 moved some core classes to packages so you're getting that `missing class` error. If you install `ArFoundation` package (which now contains those classes), it should fix that error.

**Comment by aaronmckeehan** [comment]
Thanks! I saw that BuildHelper depended on ARCore. Installing the XR Legacy Input Helpers fixed my issue.

**Comment by caglisto** [comment]
Installing the XR Legacy Input Helpers from Window > Package Manager fixed my issue too.

**Comment by sicwence** [comment]
Thanks @caglisto and @aaronmckeehan. Installing the XR Legacy Input Helpers fixed my issue in Unity 2019.1.6f1

**Comment by Sreee47** [comment]
I can find the same issue in  the new unity 2021 and in Mapbox sdk v2.1.1. I can't find an option to add the XR Legacy Input Helpers. Tried Installing ARFoundation and ARCore XR plugin and reimporting all as found on some forum, but still its not throwing errors and also its not giving me the dialog for mapbox settings to add the API Key.

**Comment by Sreee47** [comment]
> I can find the same issue in the new unity 2021 and in Mapbox sdk v2.1.1. I can't find an option to add the XR Legacy Input Helpers. Tried Installing ARFoundation and ARCore XR plugin and reimporting all as found on some forum, but still its not throwing errors and also its not giving me the dialog for mapbox settings to add the API Key.

The following  is the errors that i have now. 
`Assets\GoogleARCore\SDK\Scripts\ARCoreBackgroundRenderer.cs(43,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\UnityARInterface\ARRemote\Scripts\ARRemoteEditorInterface.cs(40,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\UnityARInterface\Scripts\ARCoreInterface.cs(51,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\UnityARInterface\Scripts\ARKitInterface.cs(26,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)`
