### ISSUE TITLE
NauticalMiles unit is wrong in CheapRulerUnits.cs

### ISSUE THREAD

**Issue by ilmtee** [mapbox/mapbox-unity-sdk#787]
Mapbox sdk 1.4.2

Integer division causes wrong result:

				case CheapRulerUnits.NauticalMiles:
					factor = 1000 / 1852;

Could be fixed as:

				case CheapRulerUnits.NauticalMiles:
					factor = 1000 / 1852.0;

**Comment by BergWerkGIS** [comment]
thanks @ilmtee - good catch.
already PRed: https://github.com/mapbox/mapbox-unity-sdk/pull/788
