### ISSUE TITLE
Getting latitude and longitude from mapbox into unity

### ISSUE THREAD

**Issue by dvaswani2717** [mapbox/mapbox-unity-sdk#789]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version:  2017,3,1p4
  * Scripting Runtime Version:  
  * Scripting Backend:  
  * Api Compatibility Level: 
* Mapbox SDK version:  latest
* The platform you're building to:
* A description of what you're trying to do:  Trying to get latitude and longitude coordinates from mapbox into unity C# script so that I can use them to place my objects in certain radius from the player. 
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by MrMallIronmaker** [comment]
You might be looking for the Conversions class - but I don't know exactly what kind of data you're trying to convert. If you can be more specific, I can help more.

https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Utilities.Conversions.html

**Comment by dvaswani2717** [comment]
Thanks.  I am just looking for gps latitude and longitude degrees that c#
in unity can understand.

**Comment by jordy-isaac** [comment]
Hi @dvaswani2717 Please check out the [SpawnOnMap](https://github.com/mapbox/mapbox-unity-sdk/blob/a450ad1a141bac5b54fbbde1eda4f9bf4cfffe03/sdkproject/Assets/Mapbox/Examples/2_ZoomableMap/Scripts/SpawnOnMap.cs) script. Here's some [documentation](https://www.mapbox.com/unity-sdk/overview/zoomable-map/#place-custom-markers) on it as well.
