### ISSUE TITLE
Spawned prefabs instantly collide with player?

### ISSUE THREAD

**Issue by andyvh** [mapbox/mapbox-unity-sdk#794]
Hi! 
I'm trying to spawn a sort of "checkpoint" on the map in WorldScaleAR using the SpawnOnMap script. I'd like the checkpoint to disappear when the player gets close enough/touches it, but when I try to run the scene in my editor, the player is shown to immediately collide with the checkpoint, despite them being nowhere near each other. Have I done something daft?

Thanks for your time!

Unity 2018.1.0f2
Mapbox 1.4.1

**Comment by jordy-isaac** [comment]
@andyvh Does this also happen when running on a device? Can you send us some screenshots or a video of what's happening so that we can get a better idea?

**Comment by andyvh** [comment]
I haven't checked if it happens on a device yet! I'll try it now!

**Comment by andyvh** [comment]
Here's a screenshot of the scene the moment I start it in the editor, to start with: 

![screen shot 2018-05-24 at 8 36 41 pm](https://user-images.githubusercontent.com/19498379/40524946-43f6af08-5f92-11e8-95f3-7122d68a59c2.png)

For now, I've left it so the script I've attached to the Checkpoint only prints that it's been collided with, and by what. I'm confused by the fact that you see that there's been a collision between the sphere in the Player and the Checkpoint, despite the fact that the Checkpoint is clearly a good distance away.

**Comment by jordy-isaac** [comment]
@andyvh Have you tried changing the `EditorLocationProvider` lat lon settings? How close are the checkpoints to the player in the editor? Did you have a chance to try it on a device?

**Comment by andyvh** [comment]
I'm still playing with the position in `EditorLocationProvider`, because it's showing them colliding at the start on the device, too, but that's because the checkpoint spawns right on top of where I'm testing it...

**Comment by andyvh** [comment]
`EditorLocationProvider`'s lat lon: 37.870654, -122.139449
SpawnOnMap spawns the Checkpoing here: 37.87075, -122.139571

**Comment by andyvh** [comment]
OK, so it turns out the sphere I was seeing was the sphere for the player object, and I don't know that my checkpoint is spawning at all on the device at the moment. The debug log does say that it's colliding with the player sphere at initialization, though.

**Comment by jordy-isaac** [comment]
@andyvh Those two coordinates are only about 10 meters apart from each other. Have you tried adjusting the lat/lon of either? It could be due to GPS accuracy as well.

**Comment by jordy-isaac** [comment]
Closing this one out and please let us know if you need any more help.
