### ISSUE TITLE
WorldScaleAR Bluetooth beacons location data

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#798]
Let's say I'm getting a latlong from the beacons and my third party location service provider, how can I use it in mapbox AR? Is there any script for it?
Like for worldscaleAr scene we had a location provider or we also used manual alignment, so in same way can I use those scripts with my location?

**Comment by jordy-isaac** [comment]
Hi @tarakinsuide You'll need to write their own `LocationProvider` for beacons. The alternative would be to use the `DeviceLocationProvider` as a base and add logic on to how and when you want to use bluetooth beacon location to either augment or replace the location coming from GPS.

Hope this helps.
