### ISSUE TITLE
Mapbox.Json.dll: Android platform is missing

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#80]
This was working before, but `sdkproject/Assets/Mapbox/Core/Plugins/ThirdParty/Mapbox.Json/Net35/Mapbox.Json.dll` has lost its Android attribute again.

![image](https://cloud.githubusercontent.com/assets/4549888/26350997/dd3d4206-3fb5-11e7-88ec-6d44fed1cc9d.png)

![image](https://cloud.githubusercontent.com/assets/4549888/26350940/a749f27a-3fb5-11e7-827e-ce2c1722c2e7.png)

**Comment by david-rhodes** [comment]
@BergWerkGIS In `develop`? What version of Unity? It seems to be checked for me in 5.4.3.

**Comment by BergWerkGIS** [comment]
@david-rhodes just pulled latest `develop` - isn't checked for me.
I'm on `Unity@5.6.0b11`.

**Comment by BergWerkGIS** [comment]
@david-rhodes If you look at the [history of `Mapbox.Json.dll.meta`](https://github.com/mapbox/mapbox-unity-sdk/commits/develop/dependencies/Mapbox.Json/Net35/Mapbox.Json.dll.meta) you'll that the `Android` attribute was added on Apr 26, but removed again on May 12 - maybe overwritten with an old version.

**Comment by david-rhodes** [comment]
@BergWerkGIS beginning of fix here: https://github.com/mapbox/mapbox-unity-sdk/pull/84

**Comment by david-rhodes** [comment]
Fixed: #84
