### ISSUE TITLE
Low resolution / blurry Raster images

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#803]
* Unity version: Unity 2017.3.1f1
  * Scripting Runtime Version: Tried with both 3.5 and 4.6
  * Scripting Backend: Mono
  * Api Compatibility Level: Tried with both
* Mapbox SDK version: Tried with 1.4.0 and 1.4.2
* The platform you're building to: In editor and Windows

We are building an application using a slightly modified version of the ZoomableMap example, and are having issues with the resolution being poor, and seemingly changing between certain zoom-levels. 

We experimented with a clean project containing only the Mapbox SDK, using the ZoomableMap example scene, and the raster / image layer of the map is blurry there as well. It's like the resolution is too low, so the text / labels are hardly readable. It also looks like there is no noticeable difference when using the retina setting. 

Below are two screenshots taken from a Windows build of the ZoomableMap scene, taken one zoom level apart, and you can clearly see the difference in the quality. What is causing this? Could there be any setting in Unity which compresses the images? 

The Executable settings were set to Ultra, and for this example we set the Tile-size to 150 which actually made it seem a bit better than the default 100. 

![image](https://user-images.githubusercontent.com/35730930/40375582-488b0afc-5dec-11e8-9f42-c218eefa35d7.png)

![image](https://user-images.githubusercontent.com/35730930/40375602-52d2f6d2-5dec-11e8-902a-8496d3673b0a.png)

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad please try with

* `Use Retina` checked
* `Use Compression` **not** checked


![image](https://user-images.githubusercontent.com/4549888/40376641-173d272a-5def-11e8-9380-daff7202fee9.png)

**Comment by JorgenEngenNapstad** [comment]
I tried that, and I can't really see any noticeable difference with Retina on or off, which is weird.  

Turning on Compression introduces artifacts, but I guess that could be expected.

**Comment by BergWerkGIS** [comment]
I verified that `Use Retina` works as expected and requests default/high resolution tiles when switched off/on, so no bug in that logic.

In case you ran your scene with default resolution tiles before checking `Use Retina` you might get the locally cached (default res) ones.

Clear all local caches via `Mapbox -> Clear Caches -> All` and then run your scene again.

Do the tiles look different now?

**Comment by BergWerkGIS** [comment]
created dedicated bug ticket #806

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS Yes, thanks that fixed it. It was the cache that didn't get deleted. 

Is there any steps to get it even sharper? It still looks a bit poorer than in Studio.

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad great!

> Is there any steps to get it even sharper?

None that I'm aware of, except un-checking `Use Compression` but we already covered that above.

> It still looks a bit poorer than in Studio.

Slight differences are expected as Studio does client side vector rendering with WebGL whereas in Unity we consume rendered bitmaps of the style which will never be as crisp as vectors.
