### ISSUE TITLE
MapboxUnitTests_FileSource.cs(140,6): warning CS0162: Unreachable code detected

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#805]
Hi,

I'm getting this error:

Assets/Mapbox/Core/mapbox-sdk-cs/Tests/UnitTests/Editor/MapboxUnitTests_FileSource.cs(140,6): warning CS0162: Unreachable code detected

when I try to import latest mapbox Unity SDK

**Comment by BergWerkGIS** [comment]
@tarakinsuide that's just a warning and can be safely ignored.
It only appears with build target set to Android or iOS and is a workaround for a problem I currently don't have a solution for.

Details in the comment above the line causing the warning:

https://github.com/mapbox/mapbox-unity-sdk/blob/d2a85eade7b55375c8476dba025ea4a019eabfe9/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Tests/UnitTests/Editor/MapboxUnitTests_FileSource.cs#L130-L134
