### ISSUE TITLE
Table Top Map Not staying on plane.

### ISSUE THREAD

**Issue by campeezjesse** [mapbox/mapbox-unity-sdk#807]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3
 
* Mapbox SDK version: 1.4.2
* The platform you're building to: iOS

I am trying to build a tabletop map with elevation.

Hello. I brought up this bug with the last SDK version and was told it would be fixed. So i decided to give mapbox another try for our project. It is still not fixed. Here is a few screenshots to try and explain a little better. The set up is the demo for tabletop. the only change is when it is switched to terrain with elevation. Then as soon as you zoom or scroll the map comes off the plane and floats mid-screen.

Here is the setup with flat terrain:
![flat terrain](https://user-images.githubusercontent.com/35813659/40436740-7f01fac4-5e68-11e8-888e-74526655fd43.png)

Here it is zoomed. Works fine
![flat zoomed](https://user-images.githubusercontent.com/35813659/40436806-a4e37588-5e68-11e8-8b4f-e2ebdfdadeb0.png)

now here is terrain with elevation not zoomed or scrolled:

![elevation start](https://user-images.githubusercontent.com/35813659/40436852-be09b086-5e68-11e8-88a5-7d373a0c14cf.png)

And as soon as it is touched:

![elevation broke](https://user-images.githubusercontent.com/35813659/40436892-ce185856-5e68-11e8-8a30-be53ee802249.png)

 We would really like to use this in our app but it is not going to work without the elevation. Please help

**Comment by atripathi-mb** [comment]
@campeezjesse Apologies for not getting back to you earlier. We are working on a solution for this issue. Will keep you updated.

**Comment by igaln** [comment]
Any updates on this issue?

**Comment by atripathi-mb** [comment]
@igaln Will be fixed in the next version - in the meantime you can use the script in this PR #999
