### ISSUE TITLE
POI's vanish when tabletop map is scrolled or zoomed

### ISSUE THREAD

**Issue by campeezjesse** [mapbox/mapbox-unity-sdk#808]
Unity version: 2017.3

Mapbox SDK version: 1.4.2

The platform you're building to: iOS

As soon as I scroll or zoom the tabletop map all the prefab POIs are removed from the scene

**Comment by isiyu** [comment]
@campeezjesse can you include a video or screenshot of what you're seeing? 

when you say prefab POIs are removed? do you mean new ones from map tiles being loaded aren't being populated, or the existing ones are not visible after panning the map

**Comment by jordy-isaac** [comment]
Closing this one for now please feel free to re-open with the additional info.
