### ISSUE TITLE
Can't put material on terrain.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#81]
I'm trying to put a custom material on my terrain, but it's not working.

My visualization only has a TerrainFactory and a MeshFactory on it. If I use a custom material under TerrainFactory -> Material, the material doesn't get applied to the terrain mesh.

Looking at the generated mesh, the material that gets applied is the "Default-Material".

**Comment by mihakrajnc** [comment]
Seems like this might be already fixed in the current repo.

A quick and dirty temporary fix is just to replace

    if (tile.MeshRenderer.material == null)

with

    if (tile.MeshRenderer.material == null || tile.MeshRenderer.material.name == "Default-Material (Instance)")

inside of `TerrainFactory.cs`.

**Comment by david-rhodes** [comment]
@mihakrajnc you are correct, that material injection never worked properly. However, this should be fixed in `develop` (I noticed this during a major refactor). Thanks for the temporary solution for those that have not yet upgraded!
