### ISSUE TITLE
SQLiteException: Could not open database file

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#815]
I tried enter multiple mapIDs separated by commas to fetch all of them.
When I enter mapIDs like this
`willybigdick30.cjftv7qku03k632nuwq4a3d9h-97bdj,willybigdick30.cjfuiarqp0b012wnuhooom5am-05dcl,willybigdick30.cjfuiarqp0b012wnuhooom5am-8k53d`
It will success
but after adding one more mapIDs like this
`willybigdick30.cjftv7qku03k632nuwq4a3d9h-97bdj,willybigdick30.cjfuiarqp0b012wnuhooom5am-05dcl,willybigdick30.cjfuiarqp0b012wnuhooom5am-8k53d,willybigdick30.cjfuiarqp0b012wnuhooom5am-6lry8`

there are some errors
![image](https://user-images.githubusercontent.com/38349902/40546808-ca6b9b7c-6062-11e8-9a47-a277825aecc4.png)

I guess the mapIDs is too long then `.cache` file can't open in unity??

P.S. Sorry the mapIDs's name is Impolite

**Comment by BergWerkGIS** [comment]
@willychang21 please elaborate on

> * Unity version: 
>  * Scripting Runtime Version: 
>  * Scripting Backend: 
>  * Api Compatibility Level: 

This is a known issue with certain combinations of the above.

**Comment by willychang21** [comment]
@BergWerkGIS 
Unity version:2018.1.1
Scripting Runtime  Version:Experimental (.NET 4.6 Equivalent)
Scripting Backend: Mono
Api Compatibility Level: .NET 4.6

**Comment by BergWerkGIS** [comment]
Try deleting this line
https://github.com/mapbox/mapbox-unity-sdk/blob/5d7f0e3a464f4e89272b523225d791364aeed5e3/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs#L154
that should make it work.

**Comment by willychang21** [comment]
@BergWerkGIS 
The error is still the same.
```
SQLiteException: Could not open database file: C:/Users/willy/AppData/LocalLow/DefaultCompany/ar break\cache\willybigdick30.cjftv7qku03k632nuwq4a3d9h-97bdj,willybigdick30.cjfuiarqp0b012wnuhooom5am-05dcl,willybigdick30.cjfuiarqp0b012wnuhooom5am-8k53d,willybigdick30.cjfuiarqp0b012wnuhooom5am-6lry8.cache (CannotOpen)
SQLite4Unity3d.SQLiteConnection..ctor (System.String databasePath, SQLite4Unity3d.SQLiteOpenFlags openFlags, System.Boolean storeDateTimeAsTicks) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/SQLite/SQLite.cs:206)
Mapbox.Platform.MbTiles.MbTilesDb.openOrCreateDb (System.String dbName) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:158)
Mapbox.Platform.MbTiles.MbTilesDb..ctor (System.String tileset, System.Nullable`1[T] maxTileCount) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:38)
Mapbox.Platform.Cache.MbTilesCache.initializeMbTiles (System.String mapId) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:112)
Mapbox.Platform.Cache.MbTilesCache.Get (System.String mapId, Mapbox.Map.CanonicalTileId tileId) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:144)
Mapbox.Platform.Cache.CachingWebFileSource.Request (System.String uri, System.Action`1[T] callback, System.Int32 timeout, Mapbox.Map.CanonicalTileId tileId, System.String mapId) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:122)
Mapbox.Unity.MapboxAccess.Request (System.String url, System.Action`1[T] callback, System.Int32 timeout, Mapbox.Map.CanonicalTileId tileId, System.String mapId) (at Assets/Mapbox/Unity/MapboxAccess.cs:247)
Mapbox.Map.Tile.Initialize (Mapbox.Platform.IFileSource fileSource, Mapbox.Map.CanonicalTileId canonicalTileId, System.String mapId, System.Action p) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:144)
VectorDataFetcher.FetchVector (Mapbox.Map.CanonicalTileId canonicalTileId, System.String mapid, Mapbox.Unity.MeshGeneration.Data.UnityTile tile, System.Boolean useOptimizedStyle, Mapbox.Unity.Map.Style style) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorDataFetcher.cs:16)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.OnRegistered (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:120)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Register (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:101)
Mapbox.Unity.Map.AbstractMapVisualizer.LoadTile (Mapbox.Map.UnwrappedTileId tileId) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:202)
Mapbox.Unity.Map.AbstractMap.TileProvider_OnTileAdded (Mapbox.Map.UnwrappedTileId tileId) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:583)
Mapbox.Unity.Map.AbstractTileProvider.AddTile (Mapbox.Map.UnwrappedTileId tile) (at Assets/Mapbox/Unity/Map/AbstractTileProvider.cs:43)
Mapbox.Unity.Map.RangeTileProvider.Update () (at Assets/Mapbox/Unity/Map/RangeTileProvider.cs:64)
```

**Comment by BergWerkGIS** [comment]
Argh, Unity seems to have changed its behavior (again ☹️).
I'm able to reproduce with `Unity@2018.2.0b4` but all workarounds I'm currently aware of don't work anymore.

Will look into it next week.

-----

Luckily there's a way to get you going in the meantime.

Change
```
Mapbox -> Setup -> Configuration -> MBTiles Cache Size (# of tiles)
```
to `0`.

**Comment by willychang21** [comment]
@BergWerkGIS  
thanks ,It works!!

**Comment by BergWerkGIS** [comment]
@willychang21 I refactored file caching and it should work now with your setup.
Would be great if you could test it.
Branch [`refactor-file-caching`](https://github.com/mapbox/mapbox-unity-sdk/tree/refactor-file-caching)

```
git clone git@github.com:mapbox/mapbox-unity-sdk.git
cd mapbox-unity-sdk
git checkout refactor-file-caching
update-mapbox-unity-sdk-core.bat <-- if you are on Windows
./update-mapbox-unity-sdk-core.sh <-- if you are on Linux/Mac
```

`File Cache Size` should be set to 2,500 automatically.
If it's not please make sure you set it to a value `>0`.

![image](https://user-images.githubusercontent.com/4549888/40987511-fb71af8e-68e8-11e8-845a-8d6a1c404228.png)
