### ISSUE TITLE
Zooming, panning with Direction Meshes is not supported

### ISSUE THREAD

**Issue by itech4ever** [mapbox/mapbox-unity-sdk#818]
* Unity version: Unity 2017 3.1.f1
  * Scripting Runtime Version: Stable (.Net 3.5 Equivalent)
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net 2.0 Subset
* Mapbox SDK version: 1.3.0
* The platform you're building to: iPhone

* A description of what you're trying to do: 
I used the **DirectionsFactory.cs** to generate the line meshes of the route returned by Mapbox and the **QuadTreeCaeraMovement.cs** as the camera script attached to the ZoomableBasicMap (QuadTreeBasicMap). When I pan or zoom, the route meshes won't pan or zoom together with the map. 

I basically used the example code delivered in v1.3.0, which is the same as the one in the new version 1.4.x. 

* Steps to recreate the bug if appropriate:
Use the directionsexample to generate route meshes and then use the left mouse key to pan or use the middle mouse key to zoom. The route meshes won't zoom or pan accordingly. 

* Links to your logs are also helpful:
NA

* Notes:
I made some changes to original code in order to fix the issue, but still could not make it right, so any advice would be highly appreciated.

**Comment by jordy-isaac** [comment]
@itech4ever Thanks for your patience. Happy to help here. This is because the line mesh is not updated after the zoom level has changed. Directions factory will need to be called again after your zoom level has changed to scale the line correctly. I hope that this helps!

**Comment by 2mehr** [comment]
@jordy-isaac Hi
Can you write a sample code?
where is a use code updates?
because I can't find line mesh updates.
thanks @jordy-isaac

**Comment by 2mehr** [comment]
> @itech4ever Thanks for your patience. Happy to help here. This is because the line mesh is not updated after the zoom level has changed. Directions factory will need to be called again after your zoom level has changed to scale the line correctly. I hope that this helps!

@jordy-isaac Hi
Can you write a sample code?
where is a use code updates?
because I can't find line mesh updates.
thanks @jordy-isaac
