### ISSUE TITLE
Choice of filters and modifiers for the streets

### ISSUE THREAD

**Issue by deadpixelsinfo** [mapbox/mapbox-unity-sdk#819]
Hello everyone.

I'm trying to simulate the way to see the streets of mapbox, exactly on unity. I'm not clear which modifiers and filters to add to have the visualization mapbox solution perfectly, on unity.

Currently, for example, I have street labels that do not scale or collide with each other. Very bad visual effects. How can I have a 1: 1 association between the map view on mapbox in unity? Which filters or modifiers do I need?

**Comment by deadpixelsinfo** [comment]
![immagine](https://user-images.githubusercontent.com/34308754/40689875-9501946a-63a4-11e8-8df0-982e51c8ff75.png)
Hi Jordy, thanks for your reply, I try to explain the problem better.

One of the biggest problems in using mapbox on unity is the refreshing of the map tiles which makes the experience not smooth when zooming in and zooming out. At each zoom level the map is rebuilt and this does not take place effectively for my purpose and get worse the experience. Not knowing perfectly the tools available I adapted this solution: the background of the map is a plane (mesh) and then people above it the roads (mesh via the vector field) and the road_laber (render text).

Now the problems I had from this solution are:
-road_label start and disappear with each zoom shot in a smooth way. I do not know what tools to use in order to make the transition smoother, so I've created a script to improve the transition by decreasing the opacity at each level. The advanced section, how can I use it to improve this? What filters can I use? For example, the names collide and overlap. Can I use some solution or do I have to write the solution?

-The roads after a high zoom out make an ugly effect (see attached image). I need not insert them in the map after a certain zoom out. Is it possible to do this with the matbox tools or do I have to build an external logic in some way?

I thank you and if it were possible to organize a skype call I would need a lot

**Comment by jordy-isaac** [comment]
@deadpixelsinfo thanks for the info. Smoothing out the zoom is something that we'll work to improve in the future. 

As for the filters in the advanced section, you can use this to create filters to control what layers are rendered. For more info on what is available to filter, please check out the tileset layer reference documentation: https://www.mapbox.com/vector-tiles/mapbox-streets-v6/#tunnel-road-bridge you can use these filters to only display what works best for your use case. Making this conditional based on zoom level would be up to you. I hope this helps!

**Comment by jordy-isaac** [comment]
Closing this one but feel free to open if you need some more help.
