### ISSUE TITLE
Questions about custom terrain

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#821]
I'm trying to generate a terrain based on some custom DEM / raster terrain data, and I have some problems and questions related to solving this: 

The custom data is only available in a specific area/extent. Is it possible to remove/hide the tiles that don't contain any custom terrain data?

We probably need to use two different map objects:
- The main map, using the Mapbox-terrain and a custom map id for the raster tiles
- Secondary map using the custom terrain, and another custom map id for raster tiles

When I try using two separate custom map id's for the Raster tiles, they seems to override each other. Is it supposed to work like this, am I doing something wrong, or is it a bug?

**Comment by JorgenEngenNapstad** [comment]
I found this link which is kind of answering one of the questions I have related to this: https://www.mapbox.com/help/troubleshoot-raster-transparency-issues/ 

Are there any way of achieving this in Unity, specifically then for the image layer of the custom terrain?

**Comment by JorgenEngenNapstad** [comment]
@jordy-isaac It's not the terrain data in it self that is the problem, it's that it only covers a small area of the world. Is there any way of smoothly "masking" out all of the places where custom terrain isn't available?

**Comment by jordy-isaac** [comment]
@JorgenEngenNapstad At this time we don't support that type of masking. However, thanks for bringing it up as a possible use case for use to consider.
