### ISSUE TITLE
Build failure for MapboxPathUtilities.cs

### ISSUE THREAD

**Issue by citizen12** [mapbox/mapbox-unity-sdk#829]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1
  * Scripting Runtime Version: .NET 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: 24
* Mapbox SDK version: github develop branch
* The platform you're building to: Android
* A description of what you're trying to do: Build for Android
* Steps to recreate the bug if appropriate: Try to build for Android
* Links to your logs are also helpful: 

Assets/Mapbox/Unity/Utilities/MapboxPathUtilities.cs(14,18): error CS0103: The name `AssetDatabase' does not exist in the current context

AssetDatabase is in the UnityEditor assembly, so you need to avoid including it when building.  Something like this should be fine:
```
    public static class MapboxPathUtilities
	{
#if UNITY_EDITOR
		public static string CreateFolder(string parentFolder, string newFolderName, bool saveAssets = false)
		{
			string guid = AssetDatabase.CreateFolder(parentFolder, newFolderName);
			string assetPath = AssetDatabase.GUIDToAssetPath(guid);
			return assetPath;
		}
#endif
	}
```

**Comment by jordy-isaac** [comment]
Please re-open this ticket if you're still having trouble building to android in 1.4.3
