### ISSUE TITLE
A way to use multiple custom datasets within a single map instance in Unity

### ISSUE THREAD

**Issue by DavidAPC** [mapbox/mapbox-unity-sdk#830]
My team is currently creating a sophisticated Unity Mapbox application that will have multiple custom features (a set of points of interest (points), a few areas (polygons) and some transport routes (lines)). Setting up different vector visualization layers make sure each set of features get rendered/portrayed on the map in their own way, as well as letting code be attached to such features

Obviously we wanted to store each category of features in a separate dataset, for clarity and organisation, however each Unity map is only able to draw Vector data from a single Tileset, and Mapbox Studio online doesn't let you apply more than one dataset to a Tileset (even though preset Tilesets do have multiple layers).

The result is we can only use one dataset at a time in a map, meaning we have to make a GEOJSON file that squashes each set of features together in one single file. This is kinda messy, and is likely to lead to mistakes or changes accidentally getting overwritten, especially if multiple people write to the same file.

So my question is, is there a way to let a Unity map visualise features on a map that come from multiple different datasets?

**Comment by atripathi-mb** [comment]
@DavidAPC Unity SDK allows you to use multiple tilesets together by specifying comma separated mapIDs. Currently using datasets directly is not supported.

**Comment by DavidAPC** [comment]
Whoa, that works perfectly well and totally solves my problem. Thank you very much! Wish I'd known that a lot earlier.
