### ISSUE TITLE
Issue Merging Android Manifests 

### ISSUE THREAD

**Issue by NeilOrthrus** [mapbox/mapbox-unity-sdk#831]
* Unity version: 2018.1.1f1
  * Scripting Runtime Version: 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: v1.4.2
* The platform you're building to: Android
* A description of what you're trying to do: Merge Android Manifests
* Steps to recreate the bug if appropriate:

Import Mapbox into Unity project.
Set player settings Minimum API Level to level 23 and Target API Level to Automatic (highest installed).
Made android build.
Receive error about "Unable to merge manifests as one has minimum API level 24" from com.mapbox.android.unity-debug/androidmanifest.xml

Can't find any manifest within the unity hierarchy that affects this API level setting in this xml.

**Comment by jordy-isaac** [comment]
Our native Android GPS Plugin has the min requirement is set to 24 as it uses methods that are not available on earlier versions.

However, there are a couple things you could try. Uncheck `Android` in the inspector for
```Assets/Mapbox/Unity/Location/Plugins/Android/com.mapbox.android.unity-debug```

Or delete the whole folder:
```Assets/Mapbox/Unity/Location/Plugins/Android/```

**Comment by NeilOrthrus** [comment]
Thanks for the reply, your first suggestion fixed the problem :)

I'm a little confused though, https://www.mapbox.com/mapbox-unity-sdk/docs/02-known-issues.html  said it was capable of working with as far back as API level 15. Yet this particular file restricts us to a minimum of level 24. Is this a mistake in documentation, or am I just misinterpreting what each of these numbers refers to?

**Comment by Storm-Develop** [comment]
I deleted the Assets/Mapbox/Unity/Location/Plugins/Android/ folder but still get the error unnable to merge AndroidManifest. Did the same steps from the tutorial. Am I missing something? Thank You
![Uploading Screenshot_17.png…]()

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\projectname\Temp\StagingArea\android-libraries\google_ar_required\AndroidManifest.xml:3] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.ar.core] element:
  <meta-data
      @android:name="com.google.ar.core"
--    @android:value="optional">
  <meta-data
      @android:name="com.google.ar.core"
++    @android:value="required">
]
stdout[

]

**Comment by BergWerkGIS** [comment]
If you don't need AR delete all AR related folders then you should be able to build to a lower version:
![image](https://user-images.githubusercontent.com/4549888/41146918-394a9d7a-6b05-11e8-9f45-3c0ec6d8b5f5.png)

However if you want to want to use AR (as I suppose you do judging from the screenshot) you can't go below 24 as this is the minimum requirement for `ARCore`:
https://developers.google.com/ar/develop/unity/quickstart-android#requirements
https://github.com/mapbox/mapbox-unity-sdk#for-unity-20171

**Comment by Storm-Develop** [comment]
@BergWerkGIS  Thank You.  https://developers.google.com/ar/develop/unity/quickstart-android#requirements helped a lot.
I found that the step for building the package on the map box website is poorly explained. 
I had to update the Google ARCORE and I missed the following settings:
Player Settings > Other Settings > Multithreaded Rendering -> **DISABLE**
Player Settings > XR Settings > ARCore Supported | **Enable**

P.S My suggestion is to add the link for setting up the project (https://developers.google.com/ar/develop/unity/quickstart-android#requirements) into here https://www.mapbox.com/unity-sdk/overview/tabletop-ar/
![screenshot_21](https://user-images.githubusercontent.com/11896104/41168009-4b446db2-6b0a-11e8-8f9d-348dbeb12fd0.png)

**Comment by BergWerkGIS** [comment]
@jordy-isaac ^^ do have resources to add `ARCore` specific information to the docs?
