### ISSUE TITLE
How to request exactly all tiles in Camera View ? 

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#832]
Dear community,

im currently struggling with some iusses... 
My game isnt a top down game, so i have a normal perspective camera.
The problem is that either the transform location provider, neither the camera bounds tile provider requests all tiles in the camera viewport.

Heres a example : 

https://imgur.com/a/2nlUhEW

As you can see only some tiles around the camera are visible. The rest isnt even there. So in my camera i see something like that : 

https://imgur.com/a/XRoaGwt

And honestly that doesnt look good at all... So thats the result of the transform tile provider.

Heres the example of the camera bounds tile provider : 

https://imgur.com/a/TaKOLzq

Better but not perfect... as you can see there still a few tiles missing.
Futhermore the performance of the camera bounds tile provider is awefull... using an update of rate of 0.1 it almost costs me hundred fps...

Any idea what could i else do to improve this ? I basically just want all the tiles in front of the camera..

**Comment by jordy-isaac** [comment]
Hi there, @genaray! Have you tried selecting `Range Around Transform` for the `Extent Options`? I would make the Camera a child of your player and then increase the `Visible Buffer` to load more tiles.

![screen shot 2018-06-01 at 6 26 14 am](https://user-images.githubusercontent.com/33474236/40843085-b5ec0702-6564-11e8-9d45-87c2b7e7bc18.png)

As for performance, you might want to try using `Group Features` on an `Vector Layer Visualizers` that you have set up.  Also, remove any unnecessary colliders on the terrain or geometry. If you have Retina settings or Mip Map checked you might also want to uncheck those settings.

**Comment by jordy-isaac** [comment]
Closing this one out. Please reopen if you need some more help.

**Comment by anyway2019** [comment]
![image](https://user-images.githubusercontent.com/25873946/119597796-4c14ff80-be14-11eb-8551-0061e069183f.png)
same issue,visible buffer and dipose buffer have setted as above ,but cost lots of fps .use camera bounds instead also not work（ps: map with terrain layer）
