### ISSUE TITLE
Question about checking if random point is on water or not?

### ISSUE THREAD

**Issue by NeilOrthrus** [mapbox/mapbox-unity-sdk#833]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.1f1
  * Scripting Runtime Version: 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: v1.4.2
* The platform you're building to: Android, IOS
* A description of what you're trying to do: Check is random point is on water.

In my unity project, I've created a system for faking location data in a basic GPS app. The system states random points of (Latitude, Longitude) in an area around the players location and uses GeoToWorldPosition() to place unity game objects on the map.

I'm wondering though how I might check if these points are being placed on rivers or the sea etc?

I've looked around and haven't found any clear solutions. I know you can check for #waterways or #water using VectorLayerVisualisers but am not certain if/how I could reference this data at specific points.

Thanks a lot for your support :)

**Comment by jordy-isaac** [comment]
Hi @NeilOrthrus You could set up a VectorLayerVisualizer for water and than also create a TagModifier to add tag those game objects with a water tag. Then, you can then add that TagModifier under the Game Object Modifier section of the VectorLayerVisualizer. When those bodies of water are generated at runtime they will all have the tag that you specify. 

<img width="1052" alt="screen shot 2018-06-01 at 1 09 17 pm" src="https://user-images.githubusercontent.com/33474236/40861201-1b026b1c-659d-11e8-81ca-01e6c6852287.png">

**Comment by heath3n** [comment]
I think he was asking: Given an arbitrary lat/lon, does a convenience method exist to determine if said coordinate falls within the bounds of a body of water?

**Comment by NeilOrthrus** [comment]
Sorry for the late reply and thank you for the feedback.

Yeah I was pretty much asking what heath3n put in better words. Would there not be a way I could perhaps raycast down from an object I placed using GetGeoPosition() and find the maps layer at that point?

I did try what was suggested though and created a TagModifier called "Water" and applied it to the VectorLayerVisualizer, setting "water" as the Tag variable. When I run however it the error "Tag: water is not defined" and magenta polygons appear on the screen. Would I need to add any code inside the TagModifier code to align the water layer with this tag?

~~
On another line of thought, one of my friends suggested that I could try finding the pixel colour on the texture at that point. Seeing how most styles use single colours for each layer, I was wondering is there a way to access the colour used by the style for the water layer?

**Comment by atripathi-mb** [comment]
@NeilOrthrus Could you post a screenshot of your VectorLayerVisualizer settings?
I am guessing you are using the [water](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#water) layer for polygons?

> On another line of thought, one of my friends suggested that I could try finding the pixel colour on the texture at that point. Seeing how most styles use single colours for each layer, I was wondering is there a way to access the colour used by the style for the water layer?

You have access to the texture in the Unity TIle, you will have to write your own algorithm to check pixels, the SDK doesn't provide methods to do pixel filtering.

**Comment by NeilOrthrus** [comment]
Yeah I am, would that explain the magenta polygons then?

![vlv](https://user-images.githubusercontent.com/39797635/40930512-cb7d04aa-681f-11e8-9ecb-ef0e22228909.png)
![tagmodifier](https://user-images.githubusercontent.com/39797635/40930514-cb9972e8-681f-11e8-989e-5f0a7ba14291.png)

~~
Thats fair enough, but is there no way to acknowledge the system applying the style and locate the data for a layer?

**Comment by atripathi-mb** [comment]
@NeilOrthrus Your magenta polygons are because you haven't assigned materials to the layer. 
![image](https://user-images.githubusercontent.com/32286016/40931282-58f21b68-67df-11e8-840e-6014ec30adb2.png)

>Thats fair enough, but is there no way to acknowledge the system applying the style and locate the data for a layer?

I am not sure I understand this fully, could you elaborate?

**Comment by NeilOrthrus** [comment]
Ah right, well I applied a cyan material to both those and I now get cyan polygons clipping through my maps whilst still having the Tag undefined error. 
![screenshot_20180604-183521](https://user-images.githubusercontent.com/39797635/40932591-bfee79aa-6826-11e8-8135-159b2cad9da8.png)

~~
I was wondering if there was a way to access the Layer properties in the geoJson file you create and export along these lines (https://www.mapbox.com/help/studio-manual-styles/) through unity?

**Comment by jordy-isaac** [comment]
@NeilOrthrus Shot in the dark about the null tag but have you added the `water` inside of the tag inspector of Unity?
