### ISSUE TITLE
QuadTreeCameraMovement misses InverseTransformPoint

### ISSUE THREAD

**Issue by shedar** [mapbox/mapbox-unity-sdk#835]
QuadTreeCameraMovement uses [x and z](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Examples/Scripts/QuadTreeCameraMovement.cs#L254) coordinates of world points. It wouldn't work if the map is rotated. E.g. I rotated map X -90 and can't drag it vertically. I guess InverseTransformPoint should be applied after ScreenToWorldPoint call.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.1f1
* Mapbox SDK version: 1.4.2
* The platform you're building to: N/A (occurs in the editor)
* A description of what you're trying to do: use rotated map to make it fit my scene.
* Steps to recreate the bug if appropriate: 
  - Put a map on a scene
  - Set X rotation -90
  - Adjust camera to make it visible
  - Start and try to drag the map in both directions (horizontal and vertical)
* Links to your logs are also helpful: N/A

**Comment by jordy-isaac** [comment]
@shedar Can you let us know about your use case. Why do you need to rotate the Map -90 on X rotation?

**Comment by shedar** [comment]
@jordy-isaac I'm playing with an idea of a map as an in-game object (tablet, table, walls, whatever), so it can have any rotation. I decided to take examples as a starting point. It took me quite some time to figure out why dragging is not working. I can fix it in my project, but to my mind, it's an unclear assumption that map is always in a certain orientation. It would be nice to either remove this assumption (modify the code) or to document it so it doesn't confuse other developers. 
If you don't consider it a bug - feel free to close it, as I mentioned, I can make those changes in my project.

**Comment by jordy-isaac** [comment]
@shedar Sounds like a cool project. Unfortunately, due to what you've mentioned rotating the map in that way isn't supported. If you'd like to contribute to the SDK and work on this issue, we gladly accept and review pull requests.
