### ISSUE TITLE
Smooth player movement and tolerance to small deviations

### ISSUE THREAD

**Issue by hopyou** [mapbox/mapbox-unity-sdk#837]
Hi,
I am currently working on a game based on the "located based game' demo, the player's movement is bit jittery and very sensitive to change in geo coordinates as it's position is updated immediately with the location provider. I know I can use interpolation to smooth out the movement but I also want the player to be less sensitive to slight change in geo coordinates, e.g. how the arrow icon moves in Google maps. 

Can anyone tell me how to achieve this?

**Comment by BergWerkGIS** [comment]
@hopyou currently the SDK doesn't have location smoothing built in so you'd have to implement that yourself.

However as a first step the upcoming `v1.4.3` (due in the coming days) will have `Device Orientation Smoothing` (aka compass) and `User Heading Smoothing` (the direction the user is walking) builtin.

Location smoothing is planed for one of the following releases afterwards.

![image](https://user-images.githubusercontent.com/4549888/40928849-07f0581c-6823-11e8-9a13-0488e4486a55.png)

**Comment by hopyou** [comment]
@BergWerkGIS thanks for info. I will have a play with the upcoming new version to see if they meet my needs .

**Comment by dhruvmodhapp** [comment]
Hi... In the world scale-ar example, I have an issue in player movement on the map. Player not moving accurate place. The position of a player not updating as expected. What should do for player smooth movement on the map?

**Comment by anolan23** [comment]
> @hopyou currently the SDK doesn't have location smoothing built in so you'd have to implement that yourself.
> 
> However as a first step the upcoming `v1.4.3` (due in the coming days) will have `Device Orientation Smoothing` (aka compass) and `User Heading Smoothing` (the direction the user is walking) builtin.
> 
> Location smoothing is planed for one of the following releases afterwards.
> 
> ![image](https://user-images.githubusercontent.com/4549888/40928849-07f0581c-6823-11e8-9a13-0488e4486a55.png)

Has the location smoothing been added since you commented?
