### ISSUE TITLE
Some tiles are blank

### ISSUE THREAD

**Issue by foscocorazza** [mapbox/mapbox-unity-sdk#839]
Some tiles are blank: the position of these tiles is seemingly random, and it applies both on Android phone and on Unity Simulator.
Sometimes is just some of the tiles, sometimes is most of them (as in picture)

<img width="533" alt="screen shot 2018-06-06 at 10 45 31" src="https://user-images.githubusercontent.com/16489575/41027473-6f44faea-6977-11e8-802a-208577081c86.png">

I have a custom `TileProvider`, to provide tiles around a radius from the center (but issue is encountered even with the standard one):

```
namespace Mapbox.Unity.Map
{
	using UnityEngine;
	using Mapbox.Map;
	using System.Collections;
	using System.Collections.Generic;
	using System.Linq;
	using Mapbox.Unity.Utilities;
	using Mapbox.Utils;

	public class RadiusTileProvider : AbstractTileProvider
	{
		[SerializeField]
		private int StartUpRadius;
		[SerializeField]
		private int UpdateRadius;
		[SerializeField]
		private int DisposeBuffer;
		[SerializeField]
		Transform UpdateTransform;
		[SerializeField]
		float _updateInterval;

		Plane _groundPlane;
		private int tiles = 0;
		float _elapsedTime;
		bool _shouldUpdate;

		Vector2d _currentLatitudeLongitude;
		UnwrappedTileId _cachedTile;
		UnwrappedTileId _currentTile;


		internal override void OnInitialized()
		{
			_groundPlane = new Plane(Vector3.up, Mapbox.Unity.Constants.Math.Vector3Zero);
			_shouldUpdate = true;

			tiles = 0;
			UnwrappedTileId centerTile = TileCover.CoordinateToTileId(_map.CenterLatitudeLongitude, _map.Zoom);


			AddTiles (centerTile, StartUpRadius);

			Debug.Log ("Generated " + tiles + " tiles");

		}



		void AddTiles(UnwrappedTileId centerTile, int radius) {
			
			tiles++;
			AddTile(new UnwrappedTileId(_map.Zoom, centerTile.X, centerTile.Y));

				for (int c = 1; c <= radius; c++) {
					for (int x = -c; x <= c; x++) {
						for (int y = -c; y <= c; y++) {

							if (!onSquarePerimeter (x, y, c))
								continue;

							if (!inCirclePerimeter (x, y, radius))
								continue;

							tiles++;
							AddTile (new UnwrappedTileId (_map.Zoom, centerTile.X + x, centerTile.Y + y));


						}
					}
				}
		}

		bool onSquarePerimeter(int x, int y, int halfSide) {
			return x == halfSide || x == -halfSide || y == halfSide || y == -halfSide;
		}

		bool inCirclePerimeter(int x, int y, int radius) {
			return (x * x + y * y) <= (radius * radius); 
		}



		void Update()
		{
			if (!_shouldUpdate)
			{
				return;
			}

			_elapsedTime += Time.deltaTime;
			if (_elapsedTime >= _updateInterval)
			{
				_elapsedTime = 0f;
				Vector3 cameraProjection = _groundPlane.ClosestPointOnPlane (UpdateTransform.position);
				_currentLatitudeLongitude = cameraProjection.GetGeoPosition(_map.CenterMercator, _map.WorldRelativeScale);
				_currentTile = TileCover.CoordinateToTileId(_currentLatitudeLongitude, _map.Zoom);

				if (!_currentTile.Equals(_cachedTile))
				{
					AddTiles (_currentTile, UpdateRadius);

					_cachedTile = _currentTile;
					Cleanup(_currentTile);
				}

			}
		}

		void Cleanup(UnwrappedTileId currentTile)
		{
			var keys = _activeTiles.Keys.ToList();
			for (int i = 0; i < keys.Count; i++)
			{
				var tile = keys[i];
				bool dispose = false;
				dispose = tile.X > currentTile.X + DisposeBuffer || tile.X < _currentTile.X - DisposeBuffer;
				dispose = dispose || tile.Y > _currentTile.Y + DisposeBuffer || tile.Y < _currentTile.Y - DisposeBuffer;

				if (dispose)
				{
					RemoveTile(tile);
					tiles--;
				}
			}
		}
	}
}
```

While `MapboxMapRenderer` is the standard one, where` Initialize()` is

    public override void Initialize(Vector2d latLon, int zoom) {

			LatLng = latLon.x + ", " + latLon.y;

			IsInitializing = true;
			IsInitialized = false;

			_worldHeightFixed = false;
			_centerLatitudeLongitude = latLon;
			_zoom = zoom;

			RectD referenceTileRect = Conversions.TileBounds(TileCover.CoordinateToTileId(_centerLatitudeLongitude, _zoom));
			_centerMercator = referenceTileRect.Center;

			_worldRelativeScale = (float)(_unityTileSize / referenceTileRect.Size.x);
			Debug.Log (_worldRelativeScale);
			_mapVisualizer.Initialize(this, _fileSouce);
			_tileProvider.Initialize(this);

			SendInitialized();
			IsInitialized = true;
			IsInitializing = false;
		}

My Mapbox Plan is "pay as you go", and my situation is:

<img width="265" alt="screen shot 2018-06-06 at 10 56 59" src="https://user-images.githubusercontent.com/16489575/41027850-654ce826-6978-11e8-89c1-447538387f0d.png">

I also use a custom map style, but the issue is present even with standard map styles.

Any idea what the issue could be?

Is there any way to at least _detect_ if a tile is blank after load and, if it is, reload it?

* Unity version: 2017.2.0f3
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android N, iOS 10+, Unity Simulator

**Comment by BergWerkGIS** [comment]
@foscocorazza I'm pretty sure tiles don't appear because you are requesting too many of them at once and they get aborted by our servers as you get rate limited. 

Scroll down to `Restrictions and limits` here:
https://www.mapbox.com/api-documentation/#retrieve-a-static-map-from-a-style

You could verify by attaching the `TileErrorHandler` script to your `Map` game object which should give you error messages in the console.

Roughly guesstimating after a quick glance at your screen shot and it looks like you are requesting somewhere between 800 and 1,000 tiles.

Don't know what you are trying to achieve but I cannot think of any use case that would require 1,000 tiles at once.
Maybe reconsider using a lower zoom level and thus less tiles.

`ZoomableMap` from the examples might be good starting point in case you want to have an overview of a large region and then zoom in.

**Comment by foscocorazza** [comment]
The problem is without doubts the one you pointed out. 

The reason why the number of tiles is so big is that I have a third-person perspective, and the player is able to see very far in the horizon. Bigger tiles (as far as I understood) lower the resolution of them, so I did many, small tiles. I will quirk around with the numbers until I have a compromise.

Thank you!
