### ISSUE TITLE
Make 'PlayMode' tests work again with Unity@2018

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#840]
* Unity version: +2018
  * Scripting Runtime Version: 4.x
  * Scripting Backend: Mono
  * Api Compatibility Level: 4.x
* Mapbox SDK version: 1.4.3
* The platform you're building to: Editor, device
* A description of what you're trying to do:
`Unity@2018` seems to have changed they way it handles `PlayMode` tests.
At least current implementation doesn't work anymore.

**TODO:**
* [ ] investigate what's wrong
* [ ] fix 😏

**Comment by dulajdanu96** [comment]
i follow a tutorial on location based game in mapbox but when i hit play in unity editor my character move.how to stop it from moving.

**Comment by newtonyan** [comment]
> i follow a tutorial on location based game in mapbox but when i hit play in unity editor my character move.how to stop it from moving.

encountering same problem
