### ISSUE TITLE
How can I find a 3D POI Marker's longitude and latitude?

### ISSUE THREAD

**Issue by DalinarKh** [mapbox/mapbox-unity-sdk#844]
I know I can use the _props dictionary from the PoiMarkerHelper class to find the values of properties, but these don't include the point's longitude and latitude. Any help would be really appreciated!

**Comment by jordy-isaac** [comment]
Hi @DalinarKh thanks for the ticket! Can you tell us a bit more about your use case and what you're going to do with the lat/lon response? We might have some ideas to accomplish your goals.

**Comment by DalinarKh** [comment]
Thanks for the response! I'd like to use this information to calculate the real world distance between the user and any given marker using the haversine formula.

**Comment by jordy-isaac** [comment]
Hi @DalinarKh For this I would suggest using raycast and then using GeoToWorldPosition.

https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Utilities.Conversions.html

I hope this helps!

**Comment by tudorelu** [comment]
@DalinarKh did you manage to find a way? 

@jordy-isaac Not sure how you mean to solve this using GeoToWorldPosition -> as we don't have the lat/long , but we have the unity world position?
