### ISSUE TITLE
Can't rotate terrain

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#847]
Hi,
We're using a static terrain on top of mapbox tiles that are used for georeference. We'd like to augment the mapbox tiles with terrain elements. However, when localization and heading is updated, the tiles move and rotate, which make it impossible to have terrain elements match the georeferenced game objects that move with the tiles.

What we're doing at the moment is exporting the terrain to a mesh so that it can be moved everytime a new location is generated. As you know Unity terrains can't be rotated for optimization reasons

How could we have it another way? Keeping the terrain/tiles fixed and having the georeferenced prefab  stay in place?

**Comment by jordy-isaac** [comment]
You might try using GeoToWorldPosition whenever you get a location update. This will take the current transform of the map into consideration to keep it in place.
