### ISSUE TITLE
Changing extentOptions.extentType doesn't update map behaviour

### ISSUE THREAD

**Issue by SebastianPietraszek** [mapbox/mapbox-unity-sdk#848]
* Unity version: 2018.1.2f1
  * Scripting Runtime Version: .NET 3.5
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 2.0 Subset
* Mapbox SDK version: 1.4.2
* The platform you're building to: Android, iOS
* A description of what I'm trying to do:
Switch extentType in runtime.
* Steps to recreate the bug:
Switch extentType in runtime.

I'm changing `extentType` from `cameraBounds` to `RangeAroundTransform` in runtime by code.
Initial setting works good. Changing the setting doesn't affect the mechanics.

**Comment by jordy-isaac** [comment]
Hi @SebastianPietraszek Can you include some screenshots, video or steps to reproduce what you're seeing?

**Comment by SebastianPietraszek** [comment]
Sure,

In inspector of `AbstractMap` I set extent options:
![image](https://user-images.githubusercontent.com/40030209/41148487-664916f4-6b09-11e8-98e6-fd32983d4ccc.png)
and
![image](https://user-images.githubusercontent.com/40030209/41148683-e0ed8796-6b09-11e8-8b60-d384306905fc.png)

I set it to be `Camera Bounds`.

I run the application in the editor and I  see, that map is responding to camera view bounds.
![image](https://user-images.githubusercontent.com/40030209/41148854-45fd074c-6b0a-11e8-8a50-c25b8faef0d9.png)

Then, I change `extentType` with this line (it's triggered by button press):
```
map.Options.extentOptions.extentType = MapExtentType.RangeAroundTransform;
```
I can see in inspector that extentType has changed, but map is still responding to camera bounds and not the transform that has been set earlier.

The other way around it works the same - setting extent options to `Range Around Transform` and changing it in runtime by:
```
map.Options.extentOptions.extentType = MapExtentType.CameraBounds;
```
makes no difference - the map is only responding to transform position although the change in inspector is visible.

**Comment by jordy-isaac** [comment]
Hi @SebastianPietraszek. As of now we don't support runtime update of map properties.

**Comment by SebastianPietraszek** [comment]
Ok, thanks for info. Any idea on how to overcome this problem?
Having two instances of map in the scene seems to me to be not a good idea...

**Comment by andrewnakas** [comment]
Any word on what this looks like post 2.0 Mapbox? I read that you now support runtime updates and I can update the visible buffer and disposable in the inspector but when I try to update it via this script line `mapper.Options.extentOptions.defaultExtents.cameraBoundsOptions.SetOptions(Camera.main,3,);`
Nothing happens. Any idea what's going on? Thanks
