### ISSUE TITLE
Find TrueNorthHeading based on Abstract Map?

### ISSUE THREAD

**Issue by qinzitan** [mapbox/mapbox-unity-sdk#849]
I'm trying to determine Unity camera's compass/true north heading based on Abstract Map. Is it possible? Couldn't find it in the API doc. Or if there's any other class can help me get the value? Thanks

**Comment by jordy-isaac** [comment]
@qinzitan I would suggest taking a look at the [LocationProvider](https://www.mapbox.com/unity-sdk/overview/location-based-game/#understand-the-locationprovider-script) in the LocationBasedGame example.

**Comment by qinzitan** [comment]
@jordy-isaac Thanks for your answer! Does it have to work with a device's compass or a "mock" location provider in the editor that I manually setup? 
Basically, I'm pulling up a 3D map using Abstract Map and am trying to define the direction of true north based on the map so I can use it as a reference. Is it possible? Thanks
