### ISSUE TITLE
Reset AR camera position and orientation with manual synchronization points

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#850]
I'm having difficulties resetting the AR camera position when doing manual calibration. 
The question is more related to ARKit than to mapbox, but I thought i'd just ask a question in case someone is facing the same issue.

I implemented some real-world synchronization points that are represented with marker images in the real world. upon recognizing the image, I use a transform location provider to reset alignment and location based on the corresponding gameobject. 

The issue I'm having actually has todo with resetting the camera position and orientation. From my experience, resetting the tracking does not consistently reset the rotation and position of the camera, so I'm having to add an offset to the position and orientation that's given from ARKit.

I've tried adding a rotation and a translation that are the opposite of the main camera's local ones, and that worked only for setting the rotation or the translation separately, but by doing both, I was generating an offset  that made the position wrong.

I know that in ARKit 1.5 I can reset the world origin to the current camera position, but that would mess up the world coordinates that I get from mapbox geoToWorldCoordinates function right?

Any idea what would be a better way to do this?
thanks

**Comment by jordy-isaac** [comment]
It could be that ARKit does not allow you to manipulate the camera and transform. It might be worth trying to manipulate the ARroot

**Comment by specsdhdeveloper** [comment]
Moving the AR Root is what I've been doing all along.  For the life of me I can't figure out how to move it to cancel out both rotation and translation. If I add a positional offset, the rotation is applied on top of that offset and messes up with the position.

If I add an offset directly to the camera transform, then the position and rotation are correctly set, but when I move the camera includes that offset and doesn't move in the direction I'm actually moving.

Anyways this is probably more of an ARKit issue

**Comment by specsdhdeveloper** [comment]
I found the solution. The best way to do this is to use SetWorldOrigin to reset the position and orientation. I don't know if this is available through ARInterface, I'm using the original arkit unity plugin and got the idea from this post :

 https://blogs.unity3d.com/2018/02/16/developing-for-arkit-1-5-update-using-unity-arkit-plugin/
