### ISSUE TITLE
Loading Texture in AbstractMap is not respected

### ISSUE THREAD

**Issue by SebastianPietraszek** [mapbox/mapbox-unity-sdk#857]
Unity version: 2018.1.2f1
Scripting Runtime Version: .NET 3.5
Scripting Backend: Mono
Api Compatibility Level: .NET 2.0 Subset
Mapbox SDK version: 1.4.2
The platform you're building to: Android, iOS
A description of what I'm trying to do:
Trying to use Loading Texture in AbstractMap.
Steps to recreate the bug:
1) Set the field `Loading Texture` in inspector of AbstractMap.
![image](https://user-images.githubusercontent.com/40030209/41150382-26d4c662-6b0e-11e8-8406-e3127d547160.png)

2) The texture of loading tiles is still 'magenta' (texture-less).
![image](https://user-images.githubusercontent.com/40030209/41150556-9602b5da-6b0e-11e8-9210-50d85753fa86.png)

**Comment by jordy-isaac** [comment]
@SebastianPietraszek It doesn't look like you have a texture specified in the first screenshot.

**Comment by SebastianPietraszek** [comment]
@jordy-isaac Sure, by this screenshot I am pointing to a field that I am setting. The screenshot doesn't show it but in the description it's clear that I do set this field.

**Comment by UlisesPereida** [comment]
I'm having a similar issue right now, when using the default loading texture, it works, but when I switch the loading texture to a custom one, the map shows no loading tile, and just shows the map once it loads it.

I'm using the same mapbox sdk version and unity 2017.3.1

**Comment by atripathi-mb** [comment]
@SebastianPietraszek @UlisesPereida Can you check if under the `TERRAIN` section you have a `Terrain Material` assigned? Magenta usually means missing material.
