### ISSUE TITLE
Roads rendered using the Line Vector Layer Visulaiser appear disjointed and under the terrain

### ISSUE THREAD

**Issue by Gzbx** [mapbox/mapbox-unity-sdk#859]
**Unity version:** 
2017.3.1f1

 **Mapbox SDK version:** 
1.4.3

 **The platform you're building to:** 
PC

 **A description of what you're trying to do:**
Create a racing track based on road data that is aligned to the terrain.  I thought the Line Vector Layer Visualiser would do this.

 **Steps to recreate the bug if appropriate:**
The Standard Replace Features example tries to do what I am after, however  roads are often rendered under the terrain and they appear disjointed. Not really suitable for driving on.

note: Issue #801 would also need to be addressed.

 **Links to your logs are also helpful:** 
see images here, though the same is clearly visible in the Replace Features Sample:
![LineVLV](https://i.imgur.com/kO9Izie.png)
![Settings](https://i.imgur.com/5HlmMZ2.png)

 **Other** 
I am happy to get advice on a more appropriate way to achieve what I am after, that is, create road/track that can be raced on that aligns/works with the terrain.

**Comment by jordy-isaac** [comment]
@Gzbx Snapping roads on terrain is difficult and there isn't an easy fix for that. We normally suggest for a use case like this to use flat maps.

As for getting the roads to match better, you might want to try to increase the sample rate in the terrain settings. We also have a `SmooteLineModifier` which may help. These won't have drastic changes, but they can help with this a little.

**Comment by Gzbx** [comment]
Thanks @jordy-isaac . Happy to close this call. I am looking at alternative approaches.
