### ISSUE TITLE
Android build not working

### ISSUE THREAD

**Issue by pikprutogpat** [mapbox/mapbox-unity-sdk#86]
Hi there,

After following the simple [Getting Started](https://www.mapbox.com/mapbox-unity-sdk/docs/00-getting-started.html) steps, I got the 'Location provider' testscene up and running, tried to make an Android build and run it from my device. It only just got to load in the player, then crashed after 1-2 seconds.

Any idea what I'm doing wrong? Tried on 2 phones, both of them crashing.

Cheers
Stig

**Comment by BergWerkGIS** [comment]
@pikprutogpat did you use the `unitypackage`?
If yes, which version?
Or source from this repo?
If you used source could you pull latest `develop` branch and try again?
I just tested with latest `develop` and it worked fine.

**Comment by pikprutogpat** [comment]
Hi BergWerkGIS,
I used the package, version 5.1
My unity version is 5.5.03f

How do I get a hold of the develop branch?


Cheers

**Comment by david-rhodes** [comment]
@pikprutogpat Are you able to share device logs from the crash? This would greatly help us debug.

**Comment by david-rhodes** [comment]
@pikprutogpat Please feel free to re-open if you still need assistance.
