### ISSUE TITLE
Layer Visualizer setting `buildingsWithUniqueIds` isn't available in Custom Visualizer inspector

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#860]
buildingsWithUniqueIds is a setting we use for 3d-building tileset. 
For Point, Line and Polygon visualizers, we have this setting as a checkbox under advanced settings but it's not there for custom visualizers. This means 3d-buildings tileset isn't usable with a custom building visualizer.

cc @atripathi-mb

**Comment by brnkhy** [comment]
@atripathi-mb I think this is merged into dev branch right? good to close?

**Comment by atripathi-mb** [comment]
Yup addressed with this commit https://github.com/mapbox/mapbox-unity-sdk/commit/88394a75fc263a6be60c0ec5bf07479c5efbcf9b
