### ISSUE TITLE
Mapbox > Setup Menu not openning

### ISSUE THREAD

**Issue by jrmistry** [mapbox/mapbox-unity-sdk#868]
DllNotFoundException: sqlite3
SQLite4Unity3d.SQLiteConnection..ctor (System.String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/SQLite/SQLite.cs:200)
Mapbox.Platform.Cache.SQLiteCache.openOrCreateDb (System.String dbName) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/SQLiteCache/SQLiteCache.cs:176)
Mapbox.Platform.Cache.SQLiteCache.init () (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/SQLiteCache/SQLiteCache.cs:94)
Mapbox.Platform.Cache.SQLiteCache..ctor (Nullable`1 maxTileCount, System.String dbName) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/SQLiteCache/SQLiteCache.cs:48)
Mapbox.Unity.MapboxAccess.ConfigureFileSource () (at Assets/Mapbox/Unity/MapboxAccess.cs:170)
Mapbox.Unity.MapboxAccess.SetConfiguration (Mapbox.Unity.MapboxConfiguration configuration, Boolean throwExecptions) (at Assets/Mapbox/Unity/MapboxAccess.cs:105)
Mapbox.Unity.MapboxAccess.LoadAccessToken () (at Assets/Mapbox/Unity/MapboxAccess.cs:158)
Mapbox.Unity.MapboxAccess..ctor () (at Assets/Mapbox/Unity/MapboxAccess.cs:64)
Mapbox.Unity.MapboxAccess.get_Instance () (at Assets/Mapbox/Unity/MapboxAccess.cs:39)
Mapbox.Editor.MapboxConfigurationWindow.OpenWindow () (at Assets/Mapbox/Unity/Editor/MapboxConfigurationWindow.cs:157)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:192)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.4f1 Personal
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 1.4.3
* The platform you're building to: PC
* A description of what you're trying to do: I was taking an online course to learn Mapbox for Unity through Udemy (https://www.udemy.com/mapbox-unity-3d-essentials/learn/v4/overview). I installed Unity on my computer. I tried create run the LocationBasedGame example. After I put in the access token the first time into the Mapbox Setup, it said it was valid, but afterwards never let me go back into the settings menu (when I try to do so, the error message above pops into the console), or update the token. It keeps saying that token is invalid, and when I press play on the demp game, nothing loads. When I press play, the error message below pops into console. I have as to why this is happening. When I reopen Unity same issue happens where I can't go into the Mapbox setup. I even tried to re-create the project, where the first time it can put in my valid token, which it verifies as valid, but all uses after it says the token is invalid. Please help. Thank you.

Plugins: Failed to load 'Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll' with error 'A dynamic link library (DLL) initialization routine failed.
'.
SQLite4Unity3d.SQLiteConnection:Dispose(Boolean) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/SQLite/SQLite.cs:1568)
SQLite4Unity3d.SQLiteConnection:Dispose(Boolean) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/SQLite/SQLite.cs:1567)
SQLite4Unity3d.SQLiteConnection:Finalize() (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/SQLite/SQLite.cs:1556)

**Comment by BergWerkGIS** [comment]
@jrmistry 
Could you please check if you have .Net Framework 3.5 installed?

**Comment by jordy-isaac** [comment]
Closing this for now. Please re-open if you're still having issues once you've confirmed you have 3.5 of .Net installed.

**Comment by YanglanWang** [comment]
If the system is linux, which version of net core should be installed?
