### ISSUE TITLE
Cannot make an UWP build through attribute errors

### ISSUE THREAD

**Issue by timgoeij** [mapbox/mapbox-unity-sdk#875]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.1p4
  * Scripting Runtime Version: stable .NET 3.5 equivalant 
  * Scripting Backend: .NET
  * Api Compatibility Level: .NET 4.6 
* Mapbox SDK version: 1.4.3
* The platform you're building to: UWP Hololens 
* A description of what you're trying to do: Building a C# unity project for visual studio to deploy for the HoloLens
* Steps to recreate the bug if appropriate: Import Mapbox 1.4.3 from the mapbox website in Unity place a map in the scene and try to build for HoloLens or other options for UWP. 
* Links to your logs are also helpful: 
![capture](https://user-images.githubusercontent.com/16646729/41711696-01965e66-7549-11e8-8982-9cee03c0cc4a.PNG)

**Comment by BergWerkGIS** [comment]
@timgoeij I'm actively working on a fix for that problem.

Till that gets into a new release please try the workaround described in this comment and let me know if it works for you:
https://github.com/mapbox/mapbox-unity-sdk/issues/734#issuecomment-396238192

**Comment by jordy-isaac** [comment]
Closing this one out as there is activity in other tickets.
