### ISSUE TITLE
Image tiles don't always load

### ISSUE THREAD

**Issue by Xerios** [mapbox/mapbox-unity-sdk#880]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.2
  * Scripting Runtime Version: 4.6
  * Scripting Backend: Mono
  * Api Compatibility Level: 4.6
* Mapbox SDK version: Latest public and develop ( 1.4.3 and + )
* The platform you're building to: Windows
* A description of what you're trying to do: Trying to navigate map and have the tiles load properly.
* Steps to recreate the bug if appropriate: Happens when navigating the map a bit too fast.
* Links to your logs are also helpful: No logs.

![image](https://user-images.githubusercontent.com/181384/41844004-3a059c20-786f-11e8-943a-e8fd0e54a1eb.png)

Issue here might be related with too many requests or rate-limiting, not quite sure. 

Just a small question, are the image tiles not cached? 
Because if they were cached offline, such thing would never occur.

**Comment by brnkhy** [comment]
@xerios we tracked down this issue and it's a racing condition probably happening because of some new-ish changes. We'll implement a proper fix but until then, you can fix it by adding something like;

UnityTile.cs line 195
```
if(_rasterData != null)
{
    _meshRenderer.material.mainTexture = _rasterData;
 }
```

**Comment by brnkhy** [comment]
@Xerios if I remember correct it should be at the end of the `SetHeightData`. Idea is checking cached image in case image is loaded before terrain .
