### ISSUE TITLE
cannot build webgl solution in unity 2018.1.5f1

### ISSUE THREAD

**Issue by wzy221** [mapbox/mapbox-unity-sdk#888]
Hi,  i have used the sdk in unity and build it sucessfully in the exe versoin. However, when i try to build it in webgl version, it always stuck and tell me the following bugs:

Assets/GoogleARCore/SDK/InstantPreview/Scripts/InstantPreviewManager.cs(32,23): error CS0234: The type or namespace name `SpatialTracking' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
Error building Player because scripts had compiler errors
Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0021f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:182 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:89 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

the unity version is 2018.1.5f1, and i am not sure why it call google AR while it is toatally not used in my project. However, it stucks me to build a webgl solution. 

When I try the examples like VoxelMap in assests folder, it also stucks and report me the same issue. Is there something i need to setup to make a successful webgl solution?

**Comment by BergWerkGIS** [comment]
@wzy221 please delete the folders related to AR:

![image](https://user-images.githubusercontent.com/4549888/41151617-8fa2f0b2-6b11-11e8-9417-b0305e5cd4d0.png)

**Comment by wzy221** [comment]
thanks it works now for my webgl build~
