### ISSUE TITLE
MapboxCitySimulator wont initialized on UWP Unity Build

### ISSUE THREAD

**Issue by JeffreyCKM** [mapbox/mapbox-unity-sdk#889]
Unity Version: 2018.1.4f1
Scripting Runtime Version: .Net 4.x or Equivalent
Scripting Backend: .Net
Api Compatibility Level: .Net 4.x 
 Mapbox SDK version: 1.4.3
The platform you're building to: UWP

A description of what you're trying to do:
I am currently trying to build out CitySimulator for UWP. It is showing the data on the editor but it wont spawn a single tile on UWP build. I would love to be able to see the tiles similar when I was on UnityEditor.

I have done some of these suggestions found online:
Add reference for sqlite universal windows
Check internetclient capabilities
Turn off firewall that may block mapbox

I am currently running out of ideas and any suggestions to ensure the build runs exactly like the editor are welcome

Thanks in advance,
Jeffrey

**Comment by BergWerkGIS** [comment]
Are you seeing any errors that might help pinpoint the problem?
Either in the UWP app when exporting from Unity with `Development Build` checked or when debugging from Visual Studio?

We are aware about problems with HoloLens (also UWP).
You could try the workaround outlined here: https://github.com/mapbox/mapbox-unity-sdk/issues/734#issuecomment-396238192

**Comment by JeffreyCKM** [comment]
Unfortunately, there are no errors mentioned by Unity but there is a worrying notification through the process. 

This is what it says:
MSPDBCMF : fatal error CMF1002: internal error (PDB error code = 0) [C:\Users\JeffreyChua\Downloads\mapbox-unity-sdk-hololens-fixes\sdkproject\UWP\VirtualBallarat\VirtualBallarat.csproj]
0x00000001414EAFA9 (Unity) StackWalker::GetCurrentCallstack
0x00000001414F15B6 (Unity) StackWalker::ShowCallstack
0x000000014138AE3B (Unity) GetStacktrace
0x000000014088532C (Unity) DebugStringToFile
0x0000000141F86498 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000000003FF8FCF0 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
0x000000003FF8FBC3 (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x000000003FF8F445 (Mono JIT Code) [Logger.cs:48] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x000000003FF8F0DC (Mono JIT Code) [Debug.bindings.cs:98] UnityEngine.Debug:Log (object) 
0x000000003FF8EECB (Mono JIT Code) [BuildDeployTools.cs:315] HoloToolkit.Unity.BuildDeployTools:<BuildAppxFromSLN>m__6 (object,System.Diagnostics.DataReceivedEventArgs) 
0x000000003FF8E623 (Mono JIT Code) System.Diagnostics.Process:OutputReadNotifyUser (string)
0x000000003FF8DED4 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:FlushMessageQueue ()
0x000000003FF8CF03 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:GetLinesFromStringBuilder ()
0x000000003FF8B113 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:ReadBuffer (System.IAsyncResult)
0x000000003FF8A1A8 (Mono JIT Code) System.IO.Stream/ReadWriteTask:InvokeAsyncCallback (object)
0x000000003AE13E21 (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000000003AE1379B (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x000000003FF89F9B (Mono JIT Code) System.IO.Stream/ReadWriteTask:System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task)
0x000000003E816EF5 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x000000003E815A03 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x000000003E81DB33 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageTwo ()
0x000000003E81D043 (Mono JIT Code) System.Threading.Tasks.Task:Finish (bool)
0x000000003E81B1C3 (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x000000003E81A3BB (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x000000003E819E23 (Mono JIT Code) System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
0x000000003E661685 (Mono JIT Code) System.Threading.ThreadPoolWorkQueue:Dispatch ()
0x000000003E660E63 (Mono JIT Code) System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
0x0000000013DA9275 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool (object,intptr,intptr,intptr)
0x00007FFA0500A19B (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFA04F91A42 (mono-2.0-bdwgc) [object.c:2915] do_runtime_invoke 
0x00007FFA04FB8151 (mono-2.0-bdwgc) [threadpool.c:366] worker_callback 
0x00007FFA04FBA791 (mono-2.0-bdwgc) [threadpool-worker-default.c:499] worker_thread 
0x00007FFA04FB4D98 (mono-2.0-bdwgc) [threads.c:1033] start_wrapper_internal 
0x00007FFA04FB4B26 (mono-2.0-bdwgc) [threads.c:1092] start_wrapper 
0x00007FFA5F793034 (KERNEL32) BaseThreadInitThunk
0x00007FFA5FA71431 (ntdll) RtlUserThreadStart

I have followed the instruction for the workaround outlined on #734 . It does not seem to help with the situation.
I have also tried to build out scenes such as voxel scene that causes the same issue. For some reason it is not instantiating the tiles on it.

**Comment by BergWerkGIS** [comment]
@JeffreyCKM have you set the `Internet (Client)` permission?

**Comment by JeffreyCKM** [comment]
Yes I did. @BergWerkGIS

**Comment by BergWerkGIS** [comment]
@JeffreyCKM  I'm out of ideas as I cannot see any helpful information in your stacktrace.
Strange that it mentions `ThreadPool` which we don't use.

Some things to check/try though:

* If you followed https://github.com/mapbox/mapbox-unity-sdk/issues/734#issuecomment-396238192 you shouldn't have these folders of other AR implementations:
![image](https://user-images.githubusercontent.com/4549888/41151617-8fa2f0b2-6b11-11e8-9417-b0305e5cd4d0.png)
If you do please delete them and try again.
* The HoloToolkit build window never worked properly for me: 
I always export manually via `File -> Build Settings ... -> Build` and then open the SLN from VS.
  * I also always delete the folder with the previously exported SLN to make sure there are no side effects from previous export
  * Beware! This comes with the drawback that you have to add the reference to `SQLite` every time.
* If you go back and forth between different Unity versions deleting the `Library` and `Temp` (if it exists) folders in between might help.

**Comment by JeffreyCKM** [comment]
Due to time restraint, our team decided to switch to HTC Vive which works perfectly fine. It has been confusing and I do not have any of the folders on the previous build. Thanks for assisting me with the issue
