### ISSUE TITLE
Panning Unity Android is Jump/Clunky

### ISSUE THREAD

**Issue by iiidefektiii** [mapbox/mapbox-unity-sdk#891]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.4.3 f1
  * Scripting Runtime Version: .net 3.5
  * Scripting Backend: mono
  * Api Compatibility Level: .net 2.0 subset
* Mapbox SDK version: 1.4.3
* The platform you're building to: Android/Editor
* A description of what you're trying to do: Panning map is super clunky. Is there anything that can be done to make it smooth? I literally have 2 polgons visible with the map and it jumps all over when panning. I tried changing pan speed but it still seems to "jump" when panning.
* Steps to recreate the bug if appropriate: Create a new project add some polygon buildings through studio connect your styles and dataset. 
* Links to your logs are also helpful: 

Device: Pixel 2 XL

**Comment by jordy-isaac** [comment]
Smoother zooming/panning is something that we'll be working on in the future. There aren't immediate plans for this to improve right away, but we're aware. Thanks for your input.
