### ISSUE TITLE
Restrict map panning with zoomable map

### ISSUE THREAD

**Issue by DutchRose-Jochem** [mapbox/mapbox-unity-sdk#894]
Not sure if this is the right place to ask this.
But is it possible to do this https://www.mapbox.com/ios-sdk/examples/constraining-gestures/ inside the ZoomableMap example?

I want to show only a specific area in my app for Android and iOS, in which the user can zoom and pan.

**Comment by jordy-isaac** [comment]
Hi @DutchRose-Jochem. You're in the right spot. There are ways to accomplish this, but it might depend on your use case. The easiest way is to constrain to the main camera from moving and have the extent options on the Map to be set to be camera bounds.

**Comment by DutchRose-Jochem** [comment]
Hi @jordy-isaac. Thanks for your reply!
I still want to zoom in and out and be able to pan.
I've added the QuadTreeCameraMovement script to the map for the zooming and panning. I already managed to constrain the zoom levels. Preferably I want to constrain the panning by defining 2 coordinates as the borders.

The app I'm creating is location based and users should only see the part of the map where everything takes place.

Does your suggestion work for this use case?

**Comment by kristoffergalicha** [comment]
Hi, did you managed to have restriction in panning and zoom i/o?

**Comment by DutchRose-Jochem** [comment]
Hi, yeah I managed to get some restrictions on panning and zooming, although it's not working as smoothly as I'd like it to be. It's been a while so I had to dig up how I did it.

Basically I added 'max zoom' and 'min zoom' floats to the QuadTreeCameraMovement script for the zoom restriction. For panning I added 2 geocodes for the top left border and the bottom right border. For zooming I added this to the zoom function:

`var zoom = Mathf.Max(_minZoom, Mathf.Min(_mapManager.Zoom + zoomFactor * _zoomSpeed, _maxZoom));
_mapManager.UpdateMap(_mapManager.CenterLatitudeLongitude, zoom);`

In the PanMap function I did this:

            float factor = _panSpeed * Conversions.GetTileScaleInMeters((float)0, _mapManager.AbsoluteZoom) / _mapManager.UnityTileSize;

            if (topLeftBorder.Length > 0 && bottomRightBorder.Length > 0)
            {
                Vector3 topLeftBorderPosition = _mapManager.GeoToWorldPosition(Conversions.StringToLatLon(topLeftBorder), false);
                Vector3 bottomRightBorderPosition = _mapManager.GeoToWorldPosition(Conversions.StringToLatLon(bottomRightBorder), false);

                var vertExtent = _referenceCamera.orthographicSize;
                var horzExtent = vertExtent * Screen.width / Screen.height;

                if ((topLeftBorderPosition.x >= -horzExtent && offsetX < 0) || (bottomRightBorderPosition.x <= horzExtent && offsetX > 0))
                {
                    offsetX = 0;
                }

                if ((topLeftBorderPosition.z <= vertExtent && offsetZ > 0) || (bottomRightBorderPosition.z >= -vertExtent && offsetZ < 0))
                {
                    offsetZ = 0;
                }
            }

            _velocity = new Vector3(offsetX, 0, offsetZ);

            var latlongDelta = Conversions.MetersToLatLon(new Vector2d(offsetX * factor, offsetZ * factor));
            var newLatLong = _mapManager.CenterLatitudeLongitude + latlongDelta;

            _mapManager.UpdateMap(newLatLong, _mapManager.Zoom);

I hope this helps. It's been awhile, so maybe I'm forgetting some things, or this doesn't work anymore with the latest MapBox version.

**Comment by kristoffergalicha** [comment]
Thank you so much, i'm new to this. will try this now :)
