### ISSUE TITLE
Trouble merging ARCore package with Mapbox package. 

### ISSUE THREAD

**Issue by jarrettblumRT** [mapbox/mapbox-unity-sdk#895]
* 2018.1.3f1: 
  Scripting Runtime Version: 4.x
  Scripting Backend: Visual Studio
Api Compatibility Level: .NET 4.x
Mapbox SDK version: v1.4.3
The platform you're building to: Android

A description of what you're trying to do: Integrate an existing AR application into the mapbox project. 

So I have previously built an AR application using ARCore and Unity. This works fine on it's own and if I save it out as a package and bring it into a new project it's fine. But if I try to pull it into a project that I have pulled a map box package into then my ARCore application will just build to a black screen. 

I know that Mapbox uses ARCore but I am having trouble finding the disconnect and whether files are being over written or whether there is a better way to do this. 

Thanks.

**Comment by BergWerkGIS** [comment]
> ... my ARCore application will just build to a black screen.

Have you checked ARCore support under XR settings?

**Comment by jarrettblumRT** [comment]
Yes this was one of the first things I checked. 

The current version of ARCore in mapbox does not have the augmented images functionality which I am using in my other project.

**Comment by jordy-isaac** [comment]
Was the previous project using ARCore 1.2 @jarrettblumRT ?

**Comment by jarrettblumRT** [comment]
Yes I was using 1.2

I have gotten to the point where it is almost working but I'm getting the following error that I think has to do with the TextureSideWallModifier.cs file 

NullReferenceException: Object reference not set to an instance of an object
Mapbox.Unity.MeshGeneration.Modifiers.TextureSideWallModifier.Initialize () (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/TextureSideWallModifier.cs:71)
Mapbox.Unity.MeshGeneration.Modifiers.ModifierStack.Initialize () (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/ModifierStack.cs:107)
Mapbox.Unity.MeshGeneration.Interfaces.VectorLayerVisualizer.Initialize () (at Assets/Mapbox/Unity/MeshGeneration/LayerVisualizers/VectorLayerVisualizer.cs:302)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory.OnInitialized () (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:86)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Initialize (IFileSource fileSource) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:96)
Mapbox.Unity.Map.AbstractMapVisualizer.Initialize (IMapReadable map, IFileSource fileSource) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:104)
Mapbox.Unity.Map.AbstractMap.InitializeMap (Mapbox.Unity.Map.MapOptions options) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:479)
Mapbox.Unity.Map.AbstractMap.SetUpMap () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:447)
Mapbox.Unity.Map.AbstractMap.Initialize (Vector2d latLon, Int32 zoom) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:502)
Mapbox.Unity.Map.InitializeMapWithLocationProvider.LocationProvider_OnLocationUpdated (Location location) (at Assets/Mapbox/Unity/Map/InitializeMapWithLocationProvider.cs:30)
Mapbox.Unity.Location.AbstractLocationProvider.SendLocation (Location location) (at Assets/Mapbox/Unity/Location/AbstractLocationProvider.cs:26)
Mapbox.Unity.Location.AbstractEditorLocationProvider+<QueryLocation>c__Iterator0.MoveNext () (at Assets/Mapbox/Unity/Location/AbstractEditorLocationProvider.cs:40)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)


Seems to have a problem with this section.

public override void Initialize()
		{
			base.Initialize();
			foreach (var atlasEntity in _options.atlasInfo.Textures)
			{
				atlasEntity.CalculateParameters();
			}
		}

**Comment by jarrettblumRT** [comment]
Ok, I got both scenes running in the same project. But now the mapbox scene no longer uses my phones camera and instead the background is just blue and the camera isn't moving when I move the phone.

**Comment by jarrettblumRT** [comment]
I added a position tracker and a AR background renderer to the camera. Everything is almost working now, this can be closed out.

**Comment by SzzzMK47** [comment]
how did u implement ar camera into mapbox????
i want to switch between the camera and mapbox when button pressed but i don't know how

**Comment by adityaspt** [comment]
@jarrettblumRT How did you solve this conflict between ARcore and Mapbox (containing ar core packages)?

I am struggling with this
