### ISSUE TITLE
ReplaceFeatureModifier "ArgumentOutOfRangeException: Cannot be negative." error

### ISSUE THREAD

**Issue by SebastianPietraszek** [mapbox/mapbox-unity-sdk#899]
* Unity version: 2018.1.6f1
  * Scripting Runtime Version: .NET 3.5 Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET 2.0 Subset
* Mapbox SDK version: 1.4.3
* The platform you're building to: Android, iOS
* A description of what you're trying to do:
Use ReplaceFeatureModifier on [Leaning Tower of Pisa](https://www.openstreetmap.org/way/35667218#map=19/43.72301/10.39663).
* Steps to recreate the bug if appropriate:
1. Open included example scene:
![image](https://user-images.githubusercontent.com/40030209/42278546-7a011790-7f9b-11e8-8695-ce197e878ea9.png)
2. Change 'CitySimulationMap' AbstractMap location to latlon 43.72303, 10.39666:
![image](https://user-images.githubusercontent.com/40030209/42278580-98c72bec-7f9b-11e8-8afa-02b846917129.png)
3. Do the same for ReplaceFeatureModifier:
![image](https://user-images.githubusercontent.com/40030209/42278606-b05d038a-7f9b-11e8-84f2-7ca9de8b9650.png)
4. Run

`ArgumentOutOfRangeException: Cannot be negative.
Parameter name: length
System.String.Substring (Int32 startIndex, Int32 length) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/String.cs:348)
Mapbox.Unity.MeshGeneration.Modifiers.ReplaceFeatureModifier.FeaturePreProcess (Mapbox.Unity.MeshGeneration.Data.VectorFeatureUnity feature) (at Assets/Mapbox/Unity/MeshGeneration/Modifiers/MeshModifiers/ReplaceFeatureModifier.cs:76)`

![image](https://user-images.githubusercontent.com/40030209/42278483-40ef65ec-7f9b-11e8-90a6-a6f06bfa79b1.png)

As you can see FeatureId Length is equal to 1.
I've looked up all the buildings id's on the neighberhood of Leaning Tower of Pisa and all are lower numbers (0, 1, 5, 13...).
What can be the problem here?

**Comment by jordy-isaac** [comment]
I was able to reproduce this as well. I tried to use `Explicitly blocked feature IDs` to filter out the tower of pisa, but I still could not get it to work. @apavani do you have an idea of how to get this to work?

**Comment by jordy-isaac** [comment]
I would suggest removing the building from the scene by feature ID.

If you run your scene, in the scene window find and click the building you want to replace. Once you select the game object, you can get the feature ID:

<img width="689" alt="screen shot 2018-08-14 at 2 39 38 pm" src="https://user-images.githubusercontent.com/33474236/44120344-edca9b56-9fd0-11e8-9c8d-d96dbccf14f3.png">


Copy this ID which is the number after the title. Then head to the ReplaceFeaturesModifier. Add the building ID as an element to the array. This should remove the building and then you can replace it with your custom model at the lat lon of the building that you removed.

<img width="370" alt="screen shot 2018-08-14 at 2 39 46 pm" src="https://user-images.githubusercontent.com/33474236/44120358-fb5ff9be-9fd0-11e8-90e9-38f75297d350.png">

**Comment by Mowalle** [comment]
I'm having the same problem@SebastianPietraszek 's city and in another city in Germany. I'm assuming your AbstractMap has "Buildings with Unique IDs" under FEATURES > Advanced unchecked? Because that will produce buildings with a short ID for me (0, 1, 2, ...), which in turn leads to the exception described in the OP (since it seems to substract 3 digits from the ID and will subsequently ask for a substring from the range [0, -1]). This happens even when trying to filter the feature ID explicitely. 

Unfortunately, with "Buildings with Unique IDs" checked, none of the buildings will render in the city at all. Is there another workaround other than removing the generated GameObjects manually?
