### ISSUE TITLE
The token sometimes invalid and sometimes uninvalid . In China

### ISSUE THREAD

**Issue by weacw** [mapbox/mapbox-unity-sdk#900]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.3f1
  * Scripting Runtime Version: 4.6
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .Net2 subset
* Mapbox SDK version: 1.43
* The platform you're building to:iOS

The token sometimes invalid and sometimes uninvalid . In China!

**Comment by jordy-isaac** [comment]
Does this happen on and off with the same token? Do you have a reliable way to reproduce this? If so please let us know.

**Comment by jordy-isaac** [comment]
Thanks for the additional info. @jim-martin might have some ideas for you.

**Comment by jim-martin** [comment]
Hi @weacw, can you share any other information about when this issue occurs? Are there differences in your network setup between the two screenshots you shared?

**Comment by weacw** [comment]
Hi @jim-martin ,
Thank you for your reply.

> can you share any other information about when this issue occurs? 

Unitypackage downloaded from the maobox website, enter the key, can be used for the first time, but can not be used after a few minutes.


> Are there differences in your network setup between the two screenshots you shared?

There is no difference in the network.


**I am in China,
Sometimes it can't be used after a while.**

**Comment by chenaptx** [comment]
I am in China.
However, I have the lantern on and can access google.
 Why is it still blocked?
