### ISSUE TITLE
Making Mac OS App build from Unity Editor (Mac OS) which works fine.

### ISSUE THREAD

**Issue by Spirit30** [mapbox/mapbox-unity-sdk#902]
Hi Team 

Thanks for your job on MapBox.
I want to run MapBox example in Mac OS app builded with Unity.

It works fine in Unity Editor on Mac OS. But when deploy as an app build on same platform there is no location loading and I have message in /Users/maximbotvinev/Library/Logs/Unity/Player.log:
Location service updates are not enabled. Check LocationService.status before querying last location.

I'm trying to find #if UNITY_EDITOR usages in solution to eliminate differences between Mac OS Editor and Mac OS App.

Give me a Hint please which classes and methods I should look first of all?
What I should pay attention to as well?

Kind regards,
Max

* Unity version: 2017.3
  * Scripting Runtime Version: .Net 3.5
  * Scripting Backend: Mono
  * Api Compatibility Level: Mac OS
* Mapbox SDK version: 1.4.3
* The platform you're building to: Mac OS
* A description of what you're trying to do: Achieve same work for example content in Mac OS app build as in Mac OS Unity Editor.
* Steps to recreate the bug if appropriate: Build and run example scenes on Mac OS. Downloading doesn't start.
* Links to your logs are also helpful: 
Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
2018-07-05 13:32:35.364 LocationTest[1600:419643] Color LCD preferred device: AMD Radeon Pro 450 (high power)
2018-07-05 13:32:35.364 LocationTest[1600:419643] Metal devices available: 2
2018-07-05 13:32:35.364 LocationTest[1600:419643] 0: Intel(R) HD Graphics 530 (low power)
2018-07-05 13:32:35.364 LocationTest[1600:419643] 1: AMD Radeon Pro 450 (high power)
2018-07-05 13:32:35.364 LocationTest[1600:419643] Forcing user selected device: Intel(R) HD Graphics 530 (low power)
Initializing Metal device caps: Intel(R) HD Graphics 530
Begin MonoManager ReloadAssembly
- Completed reload, in  0.032 seconds
WARNING: Shader Unsupported: 'Hidden/VideoDecodeOSX' - Pass 'FLIP_RGBARECT_TO_RGBA' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/VideoDecodeOSX' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.
Metal RecreateSurface[0x103a74020]: surface size 1650x1050
Setting up 4 worker threads for Enlighten.
  Thread -> id: 7000118a6000 -> priority: 1 
  Thread -> id: 700011929000 -> priority: 1 
  Thread -> id: 7000119ac000 -> priority: 1 
  Thread -> id: 700011a2f000 -> priority: 1 
UnloadTime: 1.922089 ms
Location service updates are not enabled. Check LocationService.status before querying last location.
Location service updates are not enabled. Check LocationService.status before querying last location.
Location service updates are not enabled. Check LocationService.status before querying last location.
...

**Comment by Spirit30** [comment]
We've implemented ad hoc Mac OS support for Map Box SDK in our project.
For development services of doing that for you contact us at: biz@giganeo.com

www.giganeo.com
Regards

**Comment by jordy-isaac** [comment]
@Spirit30 Can you send in screenshots of your build and player settings?
