### ISSUE TITLE
map labels problem with Persian and Arabic Texts

### ISSUE THREAD

**Issue by vahidreza** [mapbox/mapbox-unity-sdk#904]
hi
Im using the most recent mapbox unity sdk (1.4.3)
when I locate areas in Arabic countries or Iran all the persian or Arabic labels are problematic.
There is an article for fixing JS library [here](https://blog.mapbox.com/improving-arabic-and-hebrew-text-in-map-labels-fd184cf5ebd1) stating the very same problem. 
How I can fix these labels in unity?

**Comment by jordy-isaac** [comment]
We don't have out of the box support for this, but If you're bringing custom data into unity, you can workaround this make your own custom layer for labeling. This custom layer would need to be prepared by you and then uploaded to a Mapbox account. 

The main task before creating a custom layer would be to find label data in your desired languages and geographies and organize everything into a single geographic data file such as a GeoJSON or a Shapefile. I would recommend storing all the languages in the same file, with different data fields for each language. You can then upload this file to your Mapbox account, add it as a new layer in a map style project. From there, you can manage all of your different language styles from one main project just by switching out the label text field.

**Comment by vahidreza** [comment]
tnx @jordy-isaac but I guess this does not really related with the labels data itself but it is related to how the component renders text on the client side. 

As I mentioned the same has happened in JS library and in unity there are some libraries which takes an Arabic text and render them correctly in unity because if you just simply try to type a text in arabic in a text field you will be presented with something that is shown in mentioned link.

I need something like a pre-render function in unity which is called before rendering each label and in it I can rebuild the text using those methods. This may work but needs a test and needs your support.

There might be other solutions as well which Im eagerly waiting to be available.
