### ISSUE TITLE
The "Location Status" Script reverts the Latitude and Longitude 

### ISSUE THREAD

**Issue by zxcvb7653** [mapbox/mapbox-unity-sdk#911]
As the title suggest 

This is the coordinates I set it to. 
<img width="467" alt="screen shot 2018-07-12 at 4 24 35 pm" src="https://user-images.githubusercontent.com/39035665/42643048-1f21189c-85f0-11e8-9530-6ae5a1dd2234.png">

And this is the cordinates it shows from the "Location Status" Script
<img width="446" alt="screen shot 2018-07-12 at 4 24 39 pm" src="https://user-images.githubusercontent.com/39035665/42643060-2253b7b8-85f0-11e8-9711-4cd34f0640f3.png">

Is there an easier way to find the location in the form of string?

**Comment by jordy-isaac** [comment]
@zxcvb7653 I believe that this is returned in a string from by the `LocationStatus` script. Check the `Canvas` of the `LocationBasedGame` example and you'll see the `Status Text` field serialized where the coords are fed in as a string.

**Comment by zxcvb7653** [comment]
Thank you for replying!
Yes, it does feed in as a string, but the problem with the "location status" script is that it will come out as **"Longitude, Latitude"** instead of **"Latitude, Longitude"** which is inconsistent with the rest of the SDK.
Or am I just using it wrong?

**Comment by jordy-isaac** [comment]
Thanks for pointing that out, @zxcvb7653 if you'd like to submit a PR we'd welcome and review it.
