### ISSUE TITLE
unloaded unity tiles in manhantann area 

### ISSUE THREAD

**Issue by wzy221** [mapbox/mapbox-unity-sdk#912]
Hello, i am using mapbox unity sdk and it works in other places when all unity tiles can show up. however, when i try to change the postion to manhantann, there is about 9 places which desnot show the unity tile. and it keeps saying loading the data. 
 ![capture](https://user-images.githubusercontent.com/32991708/42727675-58246402-8779-11e8-843f-86564fbd1fe3.JPG)
when i change to other place, the map can works well. The raw map in mapbox looks like this.
![image](https://user-images.githubusercontent.com/32991708/42727707-7552d054-8779-11e8-9602-e7554384963c.png)
so acutally it should works.  i dont know if there is some restriction on some part visualization or it is the issue with my map? i have made the map public and its url is 
mapbox://styles/zwang002/cjjlr9ii3464y2sqrc976kwos

the location for such unloaded unity tiles are in   postions like  40.778127, -73.965833 / 40.781068, -73.959573

**Comment by BergWerkGIS** [comment]
@wzy221 there's an error loading those tiles:

![image](https://user-images.githubusercontent.com/4549888/42746697-6a8d421a-88d9-11e8-9298-dcf20e372d05.png)

Do you see any errors in the console?
If yes, please post them here.

If not, attach `TileErrorHandler.cs` script to the map, run again and post errors here.
