### ISSUE TITLE
Persistent Problems with custom Mapbox style

### ISSUE THREAD

**Issue by thecommonegret** [mapbox/mapbox-unity-sdk#915]
Hi,
I'm using Mapbox's AR Tabletop template in Unity with a custom map style from Mapbox Studio (mapbox://styles/bwellington/cjgzo5lhh000i2rpgp4xdhbn1) but am experiencing persistent inconsistencies: 

- The most troublesome of which is the inability to update the map image when re-published in Studio. Clearing the cache in the Mapbox menu doesn't seem to help.
- Some layers don't want to appear at all. Are there particular things to keep in mind regarding compatibility? Some lines show up, some don't, some polygons show up, some don't.
- When will the panning and zooming bug when utilizing the 'Terrain With Elevation' be fixed? 

Best,
Matthew

Unity version: 2018.2
Mapbox SDK version: 1.4.3
The platform you're building to: Android

**Comment by jordy-isaac** [comment]
@thecommonegret I see you have a duplicate ticket open with mapbox support so I'll close this issue.

**Comment by agrignard** [comment]
I am experimenting the same issue, when I update my Custom layer using mapbox studio the map image doesn't update even after clearing the cache.
