### ISSUE TITLE
Error closing application - Assertion failed: Transform has SetIsDispatchInterested present when destroying the hierarchy. Systems must deregister themselves in Deactivate.

### ISSUE THREAD

**Issue by DSuppo** [mapbox/mapbox-unity-sdk#916]
Hello,
I'm using Unity 2018.1.1f1, with Mapbox SDK 1.44, with the very basic sample scene "WorldScaleAR" provided with the SDK.

Each time I stop the apllication from Unity Editor I get the error message
"Assertion failed: Transform has SetIsDispatchInterested present when destroying the hierarchy. Systems must deregister themselves in Deactivate.".

At the same time each time I close the app from Android I get the error "The application unexpectedly closed".

Can you help me to understand which is the problem?
Many thanks!

**Comment by jordy-isaac** [comment]
I was able to reproduce this. The console error occurs when exiting play mode on the example scene. @atripathi-mb would you mind taking a look into this?

**Comment by DSuppo** [comment]
Thank-you for your reply,
I'd do it with pleasure


Daniele Suppo
m: +48.795.927.972 | skype: d.suppo.issimissimo

issimissimo | ul. Nowogrodzka 31 Warsaw
www.issimissimo.com [http://www.issimissimo.com/]
Il 23/07/2018 16:57:01, JW <notifications@github.com> ha scritto:
I was able to reproduce this. The console error occurs when exiting play mode on the example scene. @atripathi-mb [https://github.com/atripathi-mb] would you mind taking a look into this?

**Comment by DSuppo** [comment]
But... I would need to know what to look


Daniele Suppo
m: +48.795.927.972 | skype: d.suppo.issimissimo

issimissimo | ul. Nowogrodzka 31 Warsaw
www.issimissimo.com [http://www.issimissimo.com/]
Il 23/07/2018 16:57:01, JW <notifications@github.com> ha scritto:
I was able to reproduce this. The console error occurs when exiting play mode on the example scene. @atripathi-mb [https://github.com/atripathi-mb] would you mind taking a look into this?

**Comment by atripathi-mb** [comment]
@DSuppo @jordy-isaac Looks like a Unity issue. 
Disabling the `AR Point Cloud Visualizer` on the `AR Root` GameObject removes the error. 

![image](https://user-images.githubusercontent.com/32286016/43170446-f6e62818-8f59-11e8-9d53-f79d4c9092d2.png)
