### ISSUE TITLE
Orientation & Stabilization Issue

### ISSUE THREAD

**Issue by devrajn-hexaware** [mapbox/mapbox-unity-sdk#917]
Unity version: 2017.3.1.f1
Mapbox SDK version: 1.4.1
The platform : Android

When i open the app the object placed in a particular lat long seem to have orientation issue but once when i move physically it seems to be fixed. Is there any way to fix this.

Also the object drifts away and moves to different location. Is there any way to fix this as well.

Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Have you taken a look at the [manual alignment example](https://www.mapbox.com/unity-sdk/maps/examples/world-scale-manual-align-ar/) scene for a way to orientate your scene?
