### ISSUE TITLE
Port procedural example navigation menu from old repo

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#92]
To streamline our built-in examples and help facilitate testing, we should bring in the main scene and scene build editor scripts.

**Comment by BergWerkGIS** [comment]
My quick hack (hard coded paths) to export each scene separately:

https://github.com/mapbox/mapbox-unity-sdk/blob/BergWerk-GIS-build-all-scenes/sdkproject/Assets/Mapbox/Unity/Editor/Build/BuildAllScenes.cs

Currently works for:
* Windows Standalone x64
* Windows Store / UWP
* Android

**Comment by david-rhodes** [comment]
Done!
