### ISSUE TITLE
[Beginner MapBox User] Difficulty Rendering Map made From Custom Dataset. Vector Panel No Longer Seems Supported. 

### ISSUE THREAD

**Issue by volnam** [mapbox/mapbox-unity-sdk#920]
Sorry for my ignorance, but I am having difficulty accessing the points of interest in a custom dataset, and many tutorials appear outdated (perhaps due to a recent change?). I am trying a basic setup with a Map prefab in a default scene. I have tried a number of solutions, including connecting the Map ID from my dataset to the Map Layers Panel:

Data Source: Custom
Map ID: username.lotsOfNumbers

In the Points of Interest panel, I am seeing the error message: "In order to place points of interest please add mapbox.mapbox-streets-v7," however, right now I would only like points of interest based on my dataset. 

If anyone could steer me in the proper direction I would be super grateful. I am clearly missing something fundamental.

Thanks!

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by atripathi-mb** [comment]
@volnam The `PointsOfInterest` section currently only supports POI's from the ` mapbox.mapbox-streets-v7` tileset. For custom tilesets, use the `Features` section and choose a `primitive type = points` 
![image](https://user-images.githubusercontent.com/32286016/43169694-e869827e-8f56-11e8-9cb1-da2148085e5f.png)

Use the `DataExplorer` example and `Pois` layer or `PoiLabels` layer for reference
