### ISSUE TITLE
Display a graticule over the map

### ISSUE THREAD

**Issue by raggnic** [mapbox/mapbox-unity-sdk#921]
Hi mapbox community!

I'd like to display a graticule over the map tiles, and currently I'm considering different alternatives : 
* having a tiled raster dataset to display in an overlay layer
* having a vector dataset to display in an overlay layer
* generate and display graticule on the fly 

Which way do you think is more appropriate/feasible?

Regards
Nicolas

**Comment by jordy-isaac** [comment]
@raggnic Those would all be feasible except that maps are generated at runtime so doing this on the fly might be difficult. What are you building? The best way to approach it might largely depend on your use case.

**Comment by raggnic** [comment]
It's an application in augmented reality that displays a map with POI and zones over it. The end-users are used to graticule (i.e. MGRS), so they are asking for it. 
The tiles come from a WMTS server.

**Comment by jordy-isaac** [comment]
I would consider making a vector tileset and bringing it into Mapbox studio to be consumed in Unity. Here's the documentation on [custom data](https://www.mapbox.com/unity-sdk/maps/examples/data-explorer/#custom-data)

**Comment by raggnic** [comment]
I'm not sure it will be possible, users are offline
I'm thinking of doing a custom factory that generates a custom texture for each tile where i would draw the graticule
