### ISSUE TITLE
Extrusion for Primitive Point Type using vector layer data

### ISSUE THREAD

**Issue by PauloDeMello** [mapbox/mapbox-unity-sdk#922]
* Unity version: 2017.4.6f1
* Mapbox SDK version: 1.4.4
* The platform you're building to: Windows
* A description of what you're trying to do:
Hi, so I have some data that I wanted to visualize in unity.
So far I have added my vector layer in (shapefile of roads with traffic data on certain roads) and added a point primitive type visualizer with a prefab modifier that shows a cylinder. I was wondering if there was a way to vary the heights of the cylinders based on the vector data (road traffic numbers).
![mapboxpoint](https://user-images.githubusercontent.com/41569576/43206347-67d7efb6-901d-11e8-9900-b98363c62759.png)

I've tried the polygon primitive type and set the Extrusion Type to Property Height, and it seemed to have worked fine with the data, but it ended up being visualized like this:

![mapboxpolygon](https://user-images.githubusercontent.com/41569576/43206413-98d3a326-901d-11e8-8dbd-e986d896bde7.png)

So I was wondering if there was actually a way to set up an extrusion (based on my vector layer data) for my cylinders.

Any help would be much appreciated, thanks!

**Comment by jordy-isaac** [comment]
It is possible to style based on vector data. We're doing something very similar in the traffic and directions example in the latest version of the SDK. It does look like you're on 1.4.4 so please check out that example and see how the congestion layers are set up.
