### ISSUE TITLE
Allow maps with elevation to be snapped to y = 0

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#93]
Depending on zoom level and elevation, maps will have varying `y` values. This lack of consistency makes it hard to plan camera position.

Alternatively, we could create a camera controller script that tries to align itself to the terrain with a smooth follow.

WIP: https://github.com/mapbox/mapbox-unity-sdk/tree/snapToOrigin

**Comment by brnkhy** [comment]
push to develop
