### ISSUE TITLE
[Support/Bug] Customised points of interest appears and disappear inconstantly at different zoom level, please come take a quick look?

### ISSUE THREAD

**Issue by zxcvb7653** [mapbox/mapbox-unity-sdk#930]
* Unity version:  2017.4.0f1
* Mapbox SDK version: v1.4.3
* The platform you're building to: IOS

I am trying to create customised points of interest using the built-in version `AbstractMap` script. But the prefab appears and disappearing inconstantly at different zoom levels

<img width="451" alt="screen shot 2018-07-26 at 11 25 03 am" src="https://user-images.githubusercontent.com/39035665/43257242-2ec690ce-90c7-11e8-94a8-0572a06030ab.png">

**The POI Prefab apears fine at run time**
<img width="1041" alt="screen shot 2018-07-26 at 11 23 08 am" src="https://user-images.githubusercontent.com/39035665/43257249-3528376a-90c7-11e8-9979-30f1584b833c.png">

<img width="1018" alt="screen shot 2018-07-26 at 11 23 20 am" src="https://user-images.githubusercontent.com/39035665/43257265-3fa17bd4-90c7-11e8-997c-532f1088ece7.png">

**As you zoom in close enough the prefab disapears.** 
(I believe the tile of the map is disabled because it is at a different zoom level?)
<img width="1044" alt="screen shot 2018-07-26 at 11 23 25 am" src="https://user-images.githubusercontent.com/39035665/43257268-43fbbb40-90c7-11e8-8dc7-da574cd43b77.png">

<img width="1037" alt="screen shot 2018-07-26 at 11 23 36 am" src="https://user-images.githubusercontent.com/39035665/43257277-48785304-90c7-11e8-835e-ec6d031f1a62.png">

**Then If you carrying on zooming in the prefab reappears.**
<img width="1041" alt="screen shot 2018-07-26 at 11 23 51 am" src="https://user-images.githubusercontent.com/39035665/43257284-4d60af74-90c7-11e8-823d-5ed7e51ac3e7.png">

**It disappears when you zoom out again.** 
<img width="1036" alt="screen shot 2018-07-26 at 11 24 05 am" src="https://user-images.githubusercontent.com/39035665/43257299-54f33ae0-90c7-11e8-8719-c0ce37c3a47d.png">

**It does not apear when you zoom back in**
<img width="1046" alt="screen shot 2018-07-26 at 11 24 22 am" src="https://user-images.githubusercontent.com/39035665/43257303-5ae7ece8-90c7-11e8-8bda-a9c78dc373c3.png">

**No POI appears as it zooms out, until it reaches far enough....**
<img width="1044" alt="screen shot 2018-07-26 at 11 24 28 am" src="https://user-images.githubusercontent.com/39035665/43257313-651e1016-90c7-11e8-9ffa-1d0f1ff3a977.png">

**Then apears again when you zoom back in**
<img width="1044" alt="screen shot 2018-07-26 at 11 24 36 am" src="https://user-images.githubusercontent.com/39035665/43257326-6a6d70e8-90c7-11e8-9adb-93993fe54a8e.png">

Is this a bug? Or am I using it incorrectly?
Or do you think I should take the `SpawnOnMap` script and modify it into something I want? However the problem with the SpawnOnMap script is that prefabs appears on run time instead of checking whether the POI is within the tiles that are showing. 

Thank you for spending your time on reading this, any help is much appreciated. :)

Ellie <3

**Comment by jordy-isaac** [comment]
Have you checked the zoom extent of the tileset data to see if it's available at the zoom level for your map in Unity?
