### ISSUE TITLE
Arrow road in AR problem

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#931]
Mapbox SDK version: 1.4.4
I'm trying to use arrow road to navigate user to the destination.
![image](https://user-images.githubusercontent.com/38349902/43263006-9ae87cc0-9114-11e8-95be-7097d2399153.png)
![image](https://user-images.githubusercontent.com/38349902/43263046-ba21aa94-9114-11e8-8040-1b5e9580f119.png)
![image](https://user-images.githubusercontent.com/38349902/43263211-3128aa8e-9115-11e8-9b2b-cb6c20ccfdd4.png)
![image](https://user-images.githubusercontent.com/38349902/43263180-1684ee5e-9115-11e8-923e-cefeb903dc5d.png)

But it doesn't work,or should I modify `LoftModifier.cs`??

**Comment by jordy-isaac** [comment]
Hi @willychang21  The way the loft modifier works is as follows:

You provide a slice and it adds volume

![guid-a7002ee4-309b-4ad6-b4ad-fd2be02bacfa](https://user-images.githubusercontent.com/33474236/43488315-23ce666e-94ce-11e8-84ed-ce6aee905966.png)

One possibility, although admittedly not easy would be to change the loft object to just two points so it'll create a flat road, then add those arrows as tiling texture.

**Comment by willychang21** [comment]
@jordy-isaac  thanks for your reply , l  will try it.

**Comment by Heesunni** [comment]
> @ jordy-isaac 
hello! Did you solved that problem?
i want to modified path like you! so if you solved it please help me... :(
