### ISSUE TITLE
Placing markers / meshes on custom feature points only?

### ISSUE THREAD

**Issue by GarryGuanDoubleG** [mapbox/mapbox-unity-sdk#933]
Hello,
Using the DataExplorer scene as a demo, I plugged in a custom tileset (username.tilesetKey) into Map Layers->Data Source, but the none of the feature points are showing up. How can I place a mesh / marker for each feature point in the tileset?

![image](https://user-images.githubusercontent.com/7054506/43361105-8cf0a4cc-9294-11e8-84dc-605ff71baaa0.png)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @GarryGuanDoubleG. I'd need to take a look at your tileset to troubleshoot. If you'd rather not share the ID of it publicly, please email email help@mapbox.com so that we can assist you there.

**Comment by atripathi-mb** [comment]
@GarryGuanDoubleG From the screenshot it looks like you are using `poi_label` as the layer name. What is the name of the layer in your custom tileset? You need to use the actual layer name in order to display the points
