### ISSUE TITLE
Big issue with property drawers - just me?

### ISSUE THREAD

**Issue by Naphier** [mapbox/mapbox-unity-sdk#935]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.1.6f1
  * Scripting Runtime Version:  .NET 4.x
  * Scripting Backend:  Mono
  * Api Compatibility Level:  .NET 4.x
* Mapbox SDK version:  1.4.3 (1.4.4 doesn't seem to be available as UnityPackage yet?)
* The platform you're building to: n/a Unity Editor issue
* A description of what you're trying to do: Implement AbstractMap
* Steps to recreate the bug if appropriate: Create Implementation of AbstractMap, attach component to a gameobject. Property drawers are incorrect and many errors (see below)
* Links to your logs are also helpful: 
`ArgumentException: Getting control 13's position in a group with only 13 controls when doing repaint`

Sometimes I can see the first couple of properties in the inspector, but now it just flashes the properties for a quick second then they all disappear. I've tried resetting the layout of the Unity Editor. I've tried changing MapOptionsDrawer.lineHeight to various fixed values. I've tried changing MapOptionsDrawer.GetPropertyHeight to various fixed values. If I turn off some of the property drawers by commenting out the code in the PropertyDrawer's OnGUI method then I can see some of the foldouts, but if I open any of those then the issue is also persistent in them.
![untitled-1](https://user-images.githubusercontent.com/10132540/43412691-fd6bb6ca-93fb-11e8-983c-2d3d6b6cf3b4.png)

We're trying to update for a US gov event next week and this is a major show stopper since we can't edit any of the properties.

**Comment by Naphier** [comment]
Update:
It's not just me. My other teammates have this issue. 
I found a game object that's just got AbstractMap on it in the CitySimulator scene and everything's fine. So apparently it's just an issue when you have a class inheriting from AbstractMap. So I'm guessing this is a Unity issue. But you guys should be aware. Now I have to figure out how to implement the new SDK without using a class inheriting from AbstractMap...

**Comment by atripathi-mb** [comment]
@Naphier Unity UI doesn't work very well with inheritance. If you create a class inherited from `AbstractMap` then you will also need to create a class inheriting from `MapMangerEditor` and add an attribute to explicitly define which class is it customEditor for. 

We answered the same question in this ticket #862

**Comment by Naphier** [comment]
k, thanks
