### ISSUE TITLE
SDK without AR -> Errors

### ISSUE THREAD

**Issue by ls29322** [mapbox/mapbox-unity-sdk#938]
Unity 2017.1.2f1 , C# 
Android, API 16+
Mapbox SDK 1.4.4

When I import the package without AR folders (MapboxAR, UnityARInterface, GoogleARCore, UnityARKitPlugin) Unity is giving me those errors:
![image](https://user-images.githubusercontent.com/15261880/43515929-28ee059e-9584-11e8-8a44-08eb01630d5e.png)

Which assemble I am missing? from which folder?

Thanks

**Comment by jordy-isaac** [comment]
@ls29322 Does this also happen with Unity 2018?

**Comment by ls29322** [comment]
@jordy-isaac  yes, it works, at least on 2018.2, there's a patch or something to work on 2017.1? Thanks

**Comment by jordy-isaac** [comment]
@ls29322 There isn't a patch for it so we'd suggest using 2018. Hope this helps!
