### ISSUE TITLE
RangeTileProvider should use N, E, S, W as identifiers

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#94]
Rather than X, Y, Z, W.

**Comment by brnkhy** [comment]
And we should solve this in editor script, right?

**Comment by david-rhodes** [comment]
@brnkhy There's no need to complicate it with an editor script, right? We can just make this 4 separate serialized fields, right?

**Comment by brnkhy** [comment]
@david-rhodes ah sure fields would work, I thought of another class to keep them for a second, which would have been wasteful.

**Comment by brnkhy** [comment]
![unity_2017-06-08_18-17-01](https://user-images.githubusercontent.com/1465390/26936220-b2ea9a8a-4c76-11e7-8835-535841bb0049.png)

working on this and I think we can use an image like above to explain what's going on. It loads one to west, two to north, three to east, 4 to south. Should be self explanatory right?

**Comment by david-rhodes** [comment]
@brnkhy Looks great--thanks!
