### ISSUE TITLE
How to detect if a point/coordinate is on water ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#941]
Well the title says all... 

Only found this for android, but it doesn't help me at all : https://stackoverflow.com/questions/42708403/mapbox-ability-to-detect-if-coordinates-is-on-a-body-of-water

Is there anyway to query a specific tile for the point being on water ? 
I would be glad for a fast reply :)

**Comment by jordy-isaac** [comment]
@genaray Do you have a similar use case to the user in that stack over flow thread? 

You can access the `water` layer in `Map Layers > Features` and then you can use filters and game object modifiers to do what you would like depending on your use case.

**Comment by genaray** [comment]
@jordy-isaac Thanks ! Well are there any code samples ? I have no idea how to do that... and what about older versions ? Im havent updated since months...

**Comment by genaray** [comment]
@jordy-isaac Hello ?

**Comment by genaray** [comment]
@jordy-isaac Could I get some more help please ?

**Comment by jordy-isaac** [comment]
@genaray There are multiple ways you can do this, but one way might be to set up a vector layer visualizer with the `water` or `waterway` layer from the [streets tileset](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#waterway). You could use filters for the `class` or `type` on the tileset to show as many or as little as you want. You can also use something like use a `TagModifier` or `LayerModifier` to show or hide them.

Below I configured a waterway visualizer. I didn't make a filter but you can see where you'd do so.

<img width="452" alt="screen shot 2018-08-09 at 3 49 19 pm" src="https://user-images.githubusercontent.com/33474236/43932112-28615eea-9bf7-11e8-99da-4b83a317e38e.png">

 I added a `TagModifier` to add the tag `Waterway` to any feature that matches. Be sure to add the tag to the tag manage before running the scene.

<img width="474" alt="screen shot 2018-08-09 at 3 49 28 pm" src="https://user-images.githubusercontent.com/33474236/43932191-76da2958-9bf7-11e8-8ae3-3cc1cb950708.png">

When you press play, those features contain the tag. 

<img width="704" alt="screen shot 2018-08-09 at 4 09 16 pm" src="https://user-images.githubusercontent.com/33474236/43932212-919f5a06-9bf7-11e8-9d5a-aa8c891d4f0a.png">
