### ISSUE TITLE
Question - Render map as infinite

### ISSUE THREAD

**Issue by Emixam23** [mapbox/mapbox-unity-sdk#942]
Hi,

I would like to know how can I manage to render the map "as infinite"?

Thanks :)

**Comment by jordy-isaac** [comment]
Hi @Emixam23 Can you provide a little more context and info about what you're trying to create?

**Comment by Emixam23** [comment]
Hi,

Yeah of course, my apologies..

I am looking to have a map with extruded building :) I would like to add Transforms onto the map, such as pin, but in 3D. I was first trying to make it through Mapbox-gl-android, but they don't support 3D models. I then began with Unity3D-mapbox but, unlike in Mobile, the map is only a "square scene". -> The view of the map isn't infinite

**Comment by atripathi-mb** [comment]
@Emixam23 what do you mean by 
> view of the map isn’t infinite

The extent of the map is controlled by the `Extent Type` setting under General section of the map. 

Note - loading a large number of tiles might lead to lower rendering performance on mobile devices

**Comment by Emixam23** [comment]
Oh ok :)

So I think I just don't get it... If you say that extend the map make the rendering of it slower, then it means that you don't render it at the maximum. So how do you manage if the user moves or look at somewhere where the map isn't extended?

Thanks !

**Comment by Emixam23** [comment]
I would like to achieve something like this -> http://demo.f4map.com/#lat=48.0079408&lon=0.1958507&zoom=18&camera.theta=70.546&camera.phi=-90.345

As you can see (even if the extrusion depends on where you're looking at), if you're moving around, you'll feel that the map never ends, and I am trying to achieve something like that :) 

I am trying to create something as exploration, if an user hit the edge of the map, it's not good ^^'

Thanks !

**Comment by jordy-isaac** [comment]
The more tiles you load the bigger the hit to performance as well. I would give that effect to your scene by manipulating the camera and skybox. You can try setting the` Extent Options` to `Range Around Transform` and `Dispose Buffers` to an appropriate value your scene
