### ISSUE TITLE
AR MapBox - dynamic creation of POI's (after Map Initialization), not working (SpawnPrefabAtGeoLocation))

### ISSUE THREAD

**Issue by anent2005** [mapbox/mapbox-unity-sdk#943]
Hello,
I am developing an Android Unity app, using Mapbox SDK.
It is required to create POI's after map initialization, calling an Endpoint that provides POI's based on location. 
I am using MapBox SDK  & Unity 1018.1.6f1.
During short time intervals I must "Insert" into AR Map custom POI's using this method.
**map.SpawnPrefabAtGeoLocation**.
The method is called, the pois are inserted into mapbox structures (checked on debug) but nothing happens!
The prefab models are never created!
All the samples that are using POI's (with GPS position), are prepared even before the map is created, in the Unity Editor.
I am struggling with this problem and can't seem to find a solution.
I have called after this method -> map.UpdateMap but this is not working.
The only way to make this work, is to start my scene with the map object "inactive" and put my Poi's and then activate the map.
But this is not acceptable, since it is required to provide "live" POI's to the AR Map.
I am using the example scene WorldScaleAR, as base for my AR Scene.
Please, any help how to create dynamic POI's after Map creation is wellcomed!

**Comment by emartinDesignInteractive** [comment]
I tried this, the only way to get the points to respawn is to call map.Initialize() which is a horribly inefficient way to do this

**Comment by anent2005** [comment]
Thanks for the info! I will try this. 
I agree with you, this is totally inefficient.

**Comment by emartinDesignInteractive** [comment]
@anent2005 I would recommend not going with this approach. I would manually place the prefabs using the AbstractMap GeoToWorldPosition (also found in the Conversions package). This method does not account for any rotation that may have occurred to the map so you would also need to rotate the object appropriately.

**Comment by atripathi-mb** [comment]
@anent2005 Have you tried the script `SpawnOnMap` script ? It spawns prefabs on the map after it has initialized.

@emartinDesignInteractive Could you elaborate on this, please? 
> map.Initialize() which is a horribly inefficient way to do this

This is an event triggered once the map is ready, if I understand the question correctly - this is what is required. right?

>This method does not account for any rotation that may have occurred to the map so you would also need to rotate the object appropriately.

`GeoToWorldPosition` method on AbstractMap takes the map's transform and provides the world position. So rotation/translation/scale are all accounted for.

**Comment by anent2005** [comment]
**@atripathi-mb**
I have tried the script you mentioned (SpawnOnMap).
The script works perfect in 2d maps, but in AR map the models are rendered as static images and have a strange behaviour (follow the camera on rotation). 
This is the code in the update event:
 _for (int i = 0; i < _spawnedObjects.Count; i++)
        {
            var spawnedObject = _spawnedObjects[i];
            var location = _locations[i];
            spawnedObject.transform.localPosition = _map.GeoToWorldPosition(location, true);
            spawnedObject.transform.localScale = new Vector3(_spawnScale, _spawnScale, _spawnScale);
        }_
Only POI's created as mentioned in the first post, before map initialization are rendered correctly in AR map as 3d models in the correct positions.
I am running under deadlines and Mapbox seems not very stable. Any help how to overcome the mapbox limitations is welcomed.
**@emartinDesignInteractive** 
If you a working sample how to create "live" POI's that work correctly on AR map, please give me a small fragment.
Thanks

**Comment by atripathi-mb** [comment]
@anent2005 
> The script works perfect in 2d maps, but in AR map the models are rendered as static images and have a strange behaviour (follow the camera on rotation).

Can you send us a video/ screenshot of this issue? SpawnOnMap will spawn the prefab as-is. Has nothing to do with (rendering static images or rotation with camera might be due to scripts/behaviors on the prefab)

> Mapbox seems not very stable. Any help how to overcome the mapbox limitations is welcomed.
Can you elaborate, please?

> If you have a working sample how to create "live" POI's that work correctly on AR map, please give me a small fragment.

Check this script, this is placing the player ( prefab) using the live location from the device. 
https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Examples/Scripts/PositionWithLocationProvider.cs

**Comment by anent2005** [comment]
Hello,
Why this issue is closed?
I don't see any kind of fix. 
Please, explain!

**Comment by atripathi-mb** [comment]
@anent2005 Issue was closed because we did not hear back from you after the last comment. Please provide more details on the issue and feel free to re-open the ticket.
