### ISSUE TITLE
mapbox-streets-v7 - getting all the features from poi_label layer that meet maki=attraction and are inside boundary area

### ISSUE THREAD

**Issue by SebastianPietraszek** [mapbox/mapbox-unity-sdk#948]
Is there any possibility to get all the features that are distributed over a large area like a city or even country from _poi_label_ layer using [mapbox-streets-v7](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/) data?
I've been thinking about using [overpass turbo](http://overpass-turbo.eu/) for this purpose but I don't have any certainty that the data that I will receive will be 1 to 1 with what is in _mapbox-streets-v7_. I don't know what criteria you've been using to create the vector data besides that it's based on _OSM_ data. I mean, how can I know that what I find in _OSM_ by tag _tourism=attraction_ is the same as _maki=attraction_ in _poi_label_?
I've also thought about using MapBox Api [retrieve features from vector tiles](https://www.mapbox.com/api-documentation/#retrieve-features-from-vector-tiles), but with that approach that would require millions of requests.
Is there any other, better way to archive what I need?
Thanks!

**Comment by atripathi-mb** [comment]
@SebastianPietraszek Could you describe a little more about what are you trying to do, so we can help you better?

> Is there any possibility to get all the features that are distributed over a large area like a city or even country from poi_label layer using mapbox-streets-v7 data?

Yes, you can query poi_label for a large area ( at different zoom levels).

> I've been thinking about using overpass turbo for this purpose but I don't have any certainty that the data that I will receive will be 1 to 1 with what is in mapbox-streets-v7. I don't know what criteria you've been using to create the vector data besides that it's based on OSM data. I mean, how can I know that what I find in OSM by tag tourism=attraction is the same as maki=attraction in poi_label?

Here is a ticket that can give you some insight into how we use tags https://github.com/mapbox/mapbox-streets-source/issues/651

> I've also thought about using MapBox Api retrieve features from vector tiles, but with that approach that would require millions of requests.

Can you give us more details on what you are trying to do? Are you trying to fetch this data inside Unity? You can create a feature layer and it will do the queries for you in an optimized way.

**Comment by SebastianPietraszek** [comment]
Thanks for your reply.
We want to store a list of all the `maki:attraction` features on a DB where we will add more information such as a description. We will be displaying this features on Unity as the user moves around, and we want to download the extra data from our DB using the displayed feature's id. So to feed our DB, we are trying to get a list of all the attractions from Mapbox.

**Comment by jordy-isaac** [comment]
@SebastianPietraszek thanks for clarification. In that case the best way to approach it would be to get features tagged `tourism=attraction` from OSM using overpass turbo and then create a custom tileset. We have a [guide](https://www.mapbox.com/help/overpass-turbo/) that can show you this process. Once it's in a tileset, you can consume it inside of Unity. You can find the guide on using custom data inside the Maps SDK for Unity [here](https://www.mapbox.com/unity-sdk/maps/examples/data-explorer/#custom-data).
