### ISSUE TITLE
Wrong map tiles and distorted map

### ISSUE THREAD

**Issue by DSuppo** [mapbox/mapbox-unity-sdk#952]
Hi,
updating map to a new location I get overlapping tiles and a confused map (only in the center it's right).
The problem is in Editor, as well obviously on mobile.
You can see in the attached picture what I mean
Many thanks for your help!

![wrongmap](https://user-images.githubusercontent.com/41523122/43921432-6a0eef56-9c24-11e8-9be1-d4ff3df696da.jpg)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
2018.1.6f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
144
* The platform you're building to:
Android but the problem is ineditor too
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
Hi @DSuppo how are you updating the map?

**Comment by DSuppo** [comment]
Hi Jordy
I udpate the map with

Mapbox.Unity.Map.AbstarctMap.UpdateMap(Vector2d latitudeLongitude, int zoomFactor);


Daniele Suppo
m: +48.795.927.972 | skype: d.suppo.issimissimo

issimissimo | ul. Nowogrodzka 31 Warsaw
www.issimissimo.com [http://www.issimissimo.com/]
Il 10/08/2018 03:15:58, Jordy W. <notifications@github.com> ha scritto:
Hi @DSuppo [https://github.com/DSuppo] how are you updating the map?

**Comment by DSuppo** [comment]
Hi Jordy, can you help me on my issue?

**Comment by DSuppo** [comment]
I think that it's a bug using "world scale" for map. Can you help me to solve it?

**Comment by jordy-isaac** [comment]
Closing in favor of https://github.com/mapbox/mapbox-unity-sdk/issues/984
