### ISSUE TITLE
Is there a way to make visibility analysis

### ISSUE THREAD

**Issue by dingfengboo** [mapbox/mapbox-unity-sdk#954]
I want to know the intervisibility between two points.

**Comment by jordy-isaac** [comment]
@dingfengboo My first thought would be to raycast between the points. You'll want to make sure that you have colliders on the terrain or other features that might be between the points.

**Comment by dingfengboo** [comment]
@jordy-isaac Good idea, thank you!

**Comment by fredrikmoger** [comment]
@dingfengboo, did it work out?
