### ISSUE TITLE
[Support] Is there a way to reduce new tile set to load when changing the zoom level.

### ISSUE THREAD

**Issue by zxcvb7653** [mapbox/mapbox-unity-sdk#958]
When zooming in and out the tiles turn blank and lag out the whole machine to retrieve new set vector tiles. 

Is there a way to increase the zoom extent of the tiles used at different zoom levels? I hope this would reduce the amount of data use and smooth out the user experience. My game does not require too much detail so the detailed information on the tiles is not as significant.

Expanding the zoom extent of each tileset might also solve the issues I addressed here, where zooming in and out of POI does not appear consistently: https://github.com/mapbox/mapbox-unity-sdk/issues/930#issuecomment-408273807

I have looked into this: https://www.mapbox.com/help/adjust-tileset-zoom-extent/ 
But I don't think it is not exactly what I am looking for. From my understanding, it only controls when the data is visible at different zoom levels. 

Can I use this method to adjust how much a tileset can zoom in and out before it loads a new set of tiles?

I hope my questions make sense, any help would be appreciated! :)
El <3

**Comment by jordy-isaac** [comment]
@zxcvb7653 We have some performances improvements coming with the next release that will address zoom performance. It should be coming out shortly and you can also keep an eye on the `develop` branch if you'd like to see if the improvements are helping your issue.
