### ISSUE TITLE
Port unit tests from sdk-cs

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#96]
Unity has a built-in editor test runner, but we can also add NUnit packages to our solutions to run tests there (just make sure tests are nested in an `Editor` folder).

We will also need to ensure our tests work with .NET 3.5.

**Comment by BergWerkGIS** [comment]
Started work on unit tests here:
https://github.com/mapbox/mapbox-unity-sdk/tree/unittests

For a quick start going to throw away everything that isn't easy to get working.

----

@david-rhodes I see that `PlayMode` and `EditMode` tests can be created.
Would it be possible to have UnityCloudBuild execute `PlayMode` tests, eg panning around in the `Slippy` example?

-----

Reminder: Revist the more challenging stuff eg mocking api calls.
FYI: mocking is needed to have control over what is returned to the sdk.

![image](https://user-images.githubusercontent.com/4549888/27329798-3f957cae-55b7-11e7-8315-deb0c9835bd8.png)
