### ISSUE TITLE
Update location in WorldScale AR example

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#966]
Hi,
I'm using the WorldScale AR to build an indoor navigation AR app.
I'm getting LatLong and Heading from my service provider. I want to use this continuous string of Latlongs to constantly update my location on the map. How to do it? In which script will I have to call my data?
I'm planning to use spawnonmap.cs to put some objects at a location on the map. 
So, the only issue is how to update the user location on map in AR?

Regards,
Tarak Shah.

**Comment by DennyLindberg** [comment]
The WorldScale AR example should already have the user position update based on the device hardware. (see the LocationProvider prefab placed under WorldAlignmentKit object in that scene)

If you need to download your LatLong and Heading from a server, then I recommend using coroutines in a separate script component that you add to your AbstractMap object in the scene. Here is some pseudo-code that gives you the basic idea. Perhaps add the code from SpawnOnMap.cs for the other stuff. Note that the code won't work as is, it is only there to present the idea. Also note that the yield is based on a variable and not the server response time, I guess that you can add another yield for the download itself.

```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using Mapbox.Unity.Map;

public class RealtimeUpdate : MonoBehaviour
{
    // Assign this script component to the abstract map
    public float updateDuration = 1.0f;
    AbstractMap map;

    void Awake()
    {
        map = GetComponent<AbstractMap>();

        if (map == null)
        {
            Debug.LogWarning("Could not find AbstractMap...");
            enabled = false;
            return;
        }

        map.OnInitialized += OnMapReady;
    }

    void OnMapReady()
    {
        map.OnInitialized -= OnMapReady;

        // A coroutine is a main-thread blocking call that will pause whenever there is a yield call
        StartCoroutine(ProcessExternalData());
    }

    IEnumerator ProcessExternalData()
    {
        while (true)
        {
            // Do your stuff here
            var myData = GetSomeDataWithWWW();

            foreach (var entry in myData)
            {
                GameObject go = SpawnOrUpdateObjectBasedOnEntry(entry);
                go.transform.position = map.GeoToWorldPosition(entry.latlong);
                go.transform.rotation = map.transform.rotation;

                // Note that you might have to parent your object to the map or its tiles if you are ever going
                // to transform the map after it has loaded. Otherwise the objects won't follow unless you update their
                // transforms using LateUpdate()
            }

            // yield tells the coroutine to pause until a condition is met.
            // In this case it is paused until time has passed.
            yield return new WaitForSeconds(updateDuration);
        }
    }
}
```

**Comment by tarakinsuide** [comment]
Hi Denny,

I'm using Unity as a library for my android project. I'm getting latlong on android app.
I need to send the android device data to the unity where my mailbox scene is set. My question is where should I send the data to? To which script? And how?
