### ISSUE TITLE
BUG - Assertion failed: Geometry jobs should not be launched for empty tasks

### ISSUE THREAD

**Issue by greglemonmapbox** [mapbox/mapbox-unity-sdk#978]
**Context:** 

Unity error.

**Problem:** 

When building a map, Unity occasionally throws an error - 

"Assertion failed: Geometry jobs should not be launched for empty tasks."

No additional information is available after the error message; initial research suggest this may have to do with empty UI text containers or attempting mesh rendering jobs where mesh.vertices.Length = 0.

https://answers.unity.com/questions/1306119/geometry-jobs-should-not-be-launched-for-empty-tas.html

https://issuetracker.unity3d.com/issues/setting-ui-text-component-text-to-empty-throws-error

**Solution:** 

- [ ] Find way to repro this bug
- [ ] find and document the source/scope of the problem
- [ ] Fix
- [ ] Review and test

**Comment by brnkhy** [comment]
I'm not sure about this error, it occasionally pops in some version of Unity Editor. Sometimes just dissappear after an editor reset. So might not be an error on our side but I think `mesh rendering jobs where mesh.vertices.Length = 0` is a reasonable suspicion. I would just expect to get it more consistently if that was the case.
