### ISSUE TITLE
Add feedback to `MapVisualizer` inspector to help configure properly

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#98]
Warn user if a `TerrainFactory` is missing, as this is needed to render the raster results.

**Comment by brnkhy** [comment]
You don't have to have a TerrainFactory though. Remember contour line demo or a Godus style terrain wouldn't have it (they ar ejust mesh factory as contour lines are in vector data).

**Comment by david-rhodes** [comment]
@brnkhy I suppose I meant if you add a `MapImageFactory`, then we should warn that terrain is also needed, even if only `FlatTerrain`.

**Comment by brnkhy** [comment]
@david-rhodes ah alright that makes sense.

**Comment by david-rhodes** [comment]
Not super important.
