### ISSUE TITLE
Question: How to Add 3D objects in real time

### ISSUE THREAD

**Issue by 16273849** [mapbox/mapbox-unity-sdk#983]
I would like to add some object in the Mapbox Unity build platform at "real time", "longitude latutide" specified location. 
Such as some display 3d object from a shop.
or some special attractions just comes up few sec ago. 
Also would like to show in AR mode and 3d map mode. Any Ideas please suggest,  thank you. 

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by tarakinsuide** [comment]
I think the spawnonmap.cs script should work. I'll put your object at a LatLong.

**Comment by jordy-isaac** [comment]
Have a look at the [SpawnOnMap](https://www.mapbox.com/unity-sdk/maps/overview/add-markers/) script. Another thing to check out might be the [POI example](https://www.mapbox.com/unity-sdk/maps/examples/poi-placement/).
