### ISSUE TITLE
Road Label Orientation

### ISSUE THREAD

**Issue by thehen** [mapbox/mapbox-unity-sdk#986]
I've been using MapBox to build a real-world game in Unity. I need to display road names as a separate vector layer so that they exist in 3D space.

At the moment I can only get point data, no orientation data , so I can't align road names to the roads themselves. Is there a way to do this?

**Comment by jordy-isaac** [comment]
Hi @thehen. Unfortunately, the built in label placement using the layout property of the tileset won't work in Unity. You'll need to do the orientation calculation yourself from the geometry.

The `road_label` layer contains the same geometry as `road`,  but at high zoom levels, but at low zoom levels it becomes point features.
