### ISSUE TITLE
Problem with AbstractMap derived classes in inspector

### ISSUE THREAD

**Issue by raggnic** [mapbox/mapbox-unity-sdk#987]
Hi

In our project we've extended AbstractMap. I've tried to update the mapbox sdk to the latest version (1.4.5 at this time), but I have issues with the inspector custom panel for the AbstractMap based class.
The panel is corrupted and I have a lot of error messages
![unityerror](https://user-images.githubusercontent.com/28299760/44796090-86420b80-abac-11e8-8845-e6784eb6516e.png)

I can use this class to reproduce the issue in the repo project
```
public class NewMap : AbstractMap {
   
    // Use this for initialization
    void Start () {
        
    }
    
    // Update is called once per frame
    void Update () {
        
    }
}
```

I've tried on Unity 2017.4.5f1 and 2017.4.10f1.

**Comment by atripathi-mb** [comment]
@raggnic  Please refer to this ticket. Unity doesn't support inherited classes with custom inspectors. You need to create a derived class for the custom editor as well. 
https://github.com/mapbox/mapbox-unity-sdk/issues/862#issuecomment-397171698

**Comment by raggnic** [comment]
Thank you Abhishek, I will try this!

Until now it was not required for the inspector to work with our derived class, but i guess it is Murphy's Law
