### ISSUE TITLE
Title: Problem with AR world scale mapbox

### ISSUE THREAD

**Issue by mmsbba4** [mapbox/mapbox-unity-sdk#988]
I tried to use scene World Scale AR in the mapbox. However, when I used, the direction of AR map is incorrect in the real world.
Can I ask you about mapbox that does any API support this direction's synchronization?, please!
thank you a lot! 

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2018.2.1f1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by jordy-isaac** [comment]
@mmsbba,

Localization is a difficult problem to solve. I would check out the [manual alignment example](https://www.mapbox.com/unity-sdk/maps/examples/world-scale-manual-align-ar/). We've also had a fair amount of success using [Sturfee](https://sturfee.com/sdk.html).
