### ISSUE TITLE
Some Profiling

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#99]
I exported the **`Slippy` example** to `Windows native x64` and panned around for a little less than 1 minute.

### CPU Usage

During that 1 minute the player used about ~19 seconds CPU time.
Seconds column is CPU time in milliseconds (values are inclusive -> line is the sum of those below it).

* `UnityWebRequest` took ~5sec
![image](https://cloud.githubusercontent.com/assets/4549888/26553260/279689d2-448b-11e7-9247-a6812a5a0b38.png)

* `JobQueue::WorkLoop` (that executes `UnityWebRequest`) and `RunGfxDeviceWorker` for almost everything done by `RyunThreadWrapper` ~9.5sec
![image](https://cloud.githubusercontent.com/assets/4549888/26553416/c9f452c2-448b-11e7-9948-3e00ed8cfa7c.png)

* `PlayerLoop` and `Camera:Render` seem to be quite fast: ~2.5sec and 0.9sec
![image](https://cloud.githubusercontent.com/assets/4549888/26553541/61e730fe-448c-11e7-95d7-6e06fe8bc985.png)

* Unfortunately there's also 5sec segment for which no stack trace is available:
![image](https://cloud.githubusercontent.com/assets/4549888/26553689/0e9216a2-448d-11e7-90df-47aa2ad29b65.png)

### Memory Usage

Memory usage peaked at ~430MB and it's pretty clear where the lion's share of tiles were loaded:
![image](https://cloud.githubusercontent.com/assets/4549888/26554187/40d02f58-448f-11e7-9fb4-b00ad74e07b0.png)

Did another profile and continuously panned for more than 2 minutes.
Memory usage stayed well below 500MB during the whole time:
![image](https://cloud.githubusercontent.com/assets/4549888/26554802/5d4f0188-4492-11e7-96d2-09bdafc97c05.png)

**Comment by BergWerkGIS** [comment]
Fun fact revealed when checking heap allocations: `UnityWebRequest` seems to be powered by `curl`:
![image](https://cloud.githubusercontent.com/assets/4549888/26555866/74b5a2be-4497-11e7-9795-862dc5b1925e.png)

**Comment by brnkhy** [comment]
@BergWerkGIS just to confirm if I got that right; among 19 seconds of cpu usage, around 5 second was just web calls right? and this "time", is not waiting time but cpu processing time? Might sound silly but I'm asking because... isn't that way too high?

**Comment by BergWerkGIS** [comment]
@brnkhy good point. Will drill deeper, processing time might be included in those 5 seconds because of our callback design.

**Comment by BergWerkGIS** [comment]
This is from another ~1 minute profiling session, so the numbers are not 100% the same as above, but following the hot `UnityWebRequest` path to the end doesn't reveal anything other than `curl` releated stuff: 

![image](https://cloud.githubusercontent.com/assets/4549888/26594489/1a24036e-4568-11e7-972c-88efcca8003a.png)

I couldn't find any of our class namces either by following other hot paths or by searching the trace for their names.
Probably the names get mangled during `IL2CPP` step.
Will try some other tools to find impact of our code.
