### ISSUE TITLE
Gps update ignored due to bad accuracy: 65.0>45.0

### ISSUE THREAD

**Issue by neogithub** [mapbox/mapbox-unity-sdk#996]
Deploying the world scale example scene. Sometimes doesn't ask about camera, sometimes does. Never works with gps. Same error just lists to infinity. Map does not update either.

2017.3 & 2018.2
iOS (mix of 11.4.1 and 12.0 betas)
Building locally. 
Tried on 2 phones, 4 iPads. Same error and lack of updating. The only change from the prefab or example scene is I update the editor latlong to my area. The app does update to show the proper location when deployed but no updates.

**Comment by jordy-isaac** [comment]
Hi @neogithub Can you let us know a bit more about what you mean by the GPS is not working? Is it that the alignment is off? Please provide a bit more detail on what's happening. You also mention an error, can you let us know what error you're seeing?

If the GPS is locating your device, but the alignment is off, you might want to check out the [manual alignment example](https://www.mapbox.com/unity-sdk/maps/examples/world-scale-manual-align-ar/), and or try integrating a tool like [Sturfee](https://sturfee.com/sdk.html) to localize your device to the environment.
