### ISSUE TITLE
Is support for the IL2CPP scripting backend being looked at?

### ISSUE THREAD

**Issue by BrentKingma** [mapbox/mapbox-unity-sdk#997]
Have read the following posts:
https://github.com/mapbox/mapbox-unity-sdk/pull/485
https://github.com/mapbox/mapbox-unity-sdk/issues/734
https://github.com/mapbox/mapbox-unity-sdk/pull/945

Just want to know if support for the IL2CPP scripting backend is being looked at?

Thanks

**Comment by atripathi-mb** [comment]
@BrentKingma IL2CPP is an limitation only for UWP builds. Are you looking to build for UWP using the IL2CPP?

**Comment by BrentKingma** [comment]
@atripathi-mb Yes, I am currently busy on a project for the Hololens and I am using IL2CPP for the networking part of my project as it is pretty efficient at it.

**Comment by atripathi-mb** [comment]
@BrentKingma The support for IL2CPP for UWP builds is on the list of enhancements but not a priority currently.Unfortunately, we don't have a fixed timeline for this fix to be available.

**Comment by BrentKingma** [comment]
Ok, thanks
Thats all I needed to know.
Thanks for the help.

**Comment by lukemadera** [comment]
@abhishektrip any update on this? I'd really love to use Mapbox but we need a Windows build and this is a blocker.

**Comment by mertusta1996** [comment]
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
